"""
Fix thin topics:
  - leverage-strategies: has 20q/8fc but guide is only 715 chars — expand guide
  - fin-macroeconomics: only 3q/3fc/1738 guide — expand everything
Run: python3 scripts/fix_thin_topics.py
"""
import json
from pathlib import Path

BASE = Path(__file__).parent.parent / "src/content/topics"


def patch(folder, filename, updates):
    p = BASE / folder / filename
    d = json.loads(p.read_text())
    d.update(updates)
    p.write_text(json.dumps(d, indent=2, ensure_ascii=False))
    print(f"  PATCHED {filename}: guide={len(d['guide'])} q={len(d['questions'])} fc={len(d['flashcards'])}")


# ── LEVERAGE STRATEGIES — expand guide (already has 20q/8fc) ─────────────────

LEVERAGE_GUIDE = "\n".join([
    "# Leverage Strategies — Max Output, Min Effort",
    "",
    "## What Is Leverage in the Context of Knowledge Work?",
    "",
    "Leverage is the principle that some actions produce disproportionately large results",
    "relative to the effort invested. A lever multiplies force — in your learning and career,",
    "some activities multiply your output by 10x while others barely move the needle.",
    "",
    "```",
    "Low leverage (1:1):            High leverage (1:many):",
    "  Fix one bug                    Write a test that catches 50 future bugs",
    "  Answer one question            Write a doc that answers 1000 questions",
    "  Learn one framework            Learn the mental model underlying all frameworks",
    "  Do one task manually           Automate the task",
    "",
    "Naval Ravikant: 'Leverage is one of the most important concepts for building wealth.",
    "Code and media are force multipliers — write once, scales infinitely.'",
    "```",
    "",
    "---",
    "",
    "## The Four Types of Leverage",
    "",
    "```",
    "1. LABOUR (weakest, requires permission):",
    "   Get others to work for you. Scales linearly — 10 people = 10x output.",
    "   Requires: management, coordination, good judgment in hiring.",
    "   Example: managing a team of engineers.",
    "",
    "2. CAPITAL (powerful, requires money or trust):",
    "   Money working for you. Invest, automate, buy tools.",
    "   Example: paying for AWS instead of hosting your own servers.",
    "",
    "3. CODE (most accessible lever for developers):",
    "   Write once, runs for millions of users, 24/7, for free.",
    "   No marginal cost per execution.",
    "   Example: a SaaS product, an open-source library, an automation script.",
    "",
    "4. MEDIA/CONTENT (new, massive scale):",
    "   Write an article, record a video, build a course.",
    "   Reaches millions with same effort as reaching one person.",
    "   Example: a YouTube tutorial, a Twitter thread, a GitHub README.",
    "",
    "As a developer: CODE and MEDIA are your highest-leverage tools.",
    "Code scales infinitely with near-zero marginal cost.",
    "Writing/teaching multiplies how much you help others.",
    "```",
    "",
    "---",
    "",
    "## Applying Leverage in Daily Developer Work",
    "",
    "```",
    "AUTOMATION (code leverage):",
    "  Identify: what do you do manually 3+ times per week?",
    "  Automate it. One hour of scripting saves 5 minutes × 100 uses = 8 hours.",
    "",
    "  Examples:",
    "  - Shell script for dev environment setup",
    "  - GitHub Actions for deployment (do it once, runs on every push)",
    "  - Cron job for data reports you manually pulled",
    "  - Template repos for new projects",
    "",
    "DEFAULTS AND TEMPLATES:",
    "  Create reusable starting points. Every new project starts at 80% done.",
    "  - Spring Boot template with OpenAPI, JWT, health checks pre-configured",
    "  - Docker Compose template with app + postgres + redis",
    "  - Testing scaffold with pytest fixtures and factories",
    "",
    "DOCUMENTATION AS LEVERAGE:",
    "  A great README saves 30 minutes per person who reads it.",
    "  If 100 developers use your library = 50 hours saved.",
    "  Investment: 2 hours writing. Return: 50+ hours multiplied.",
    "",
    "LEARNING IN PUBLIC:",
    "  Write blog posts/tweets about problems you solved.",
    "  You would have solved the problem anyway.",
    "  Writing it down takes 2 extra hours.",
    "  Others get the knowledge. You get reputation and deeper understanding.",
    "```",
    "",
    "---",
    "",
    "## AI as a Leverage Multiplier",
    "",
    "```",
    "AI (LLM tools) are a massive new leverage layer for developers.",
    "",
    "CODE GENERATION:",
    "  Boilerplate: 30 seconds with GitHub Copilot vs 15 minutes manually",
    "  Test generation: 'write tests for this function' → 5 minute task vs 30 minutes",
    "  Documentation: 'document this class' → instant vs tedious manual writing",
    "",
    "DECISION SUPPORT:",
    "  'Explain trade-offs of Redis vs Memcached for my use case'",
    "  'Review this database schema for potential issues'",
    "  'What edge cases am I missing in this design?'",
    "",
    "LEARNING ACCELERATOR:",
    "  'Explain this concept to me as if I'm a Java developer learning it for first time'",
    "  'What questions should I ask in an interview about Kubernetes?'",
    "  'Walk me through this complex piece of code step by step'",
    "",
    "AI leverage compound:",
    "  AI helps you learn faster → bigger knowledge base",
    "  Bigger knowledge base → you ask better questions",
    "  Better questions → better AI answers",
    "  Better answers → higher quality output faster",
    "",
    "PRACTICAL WORKFLOW:",
    "  1. Understand requirements → use AI for research",
    "  2. Design architecture → AI as rubber duck / design reviewer",
    "  3. Implement core logic → write by hand (deep understanding needed)",
    "  4. Implement boilerplate/tests → use AI heavily",
    "  5. Review → use AI to spot patterns, missing error handling",
    "  6. Document → use AI for first draft",
    "```",
    "",
    "---",
    "",
    "## Time Leverage — Compound Learning",
    "",
    "```",
    "COMPOUND LEARNING:",
    "  1% better each day = 37x better in a year (1.01^365 = 37.78)",
    "  Learning compounds: today's knowledge makes tomorrow's learning faster",
    "",
    "  Day 1: Learn what a container is",
    "  Week 2: Understand Docker (built on containers, easier to grasp)",
    "  Month 2: Understand Kubernetes (built on Docker, easier to grasp)",
    "  Month 4: Understand Helm/ArgoCD (built on K8s, easier to grasp)",
    "  Each concept is leverage for the next.",
    "",
    "DELIBERATE PRACTICE vs PASSIVE LEARNING:",
    "  Passive: read about data structures (low retention, low leverage)",
    "  Active:  solve data structure problems (high retention, direct skill)",
    "  Teach:   explain data structures to someone (highest retention + reputation)",
    "",
    "SPACED REPETITION (used in this app!):",
    "  Reviewing at increasing intervals: 1 day → 3 days → 7 days → 30 days",
    "  Same information, fraction of study time",
    "  Knowledge with higher retention per hour invested",
    "  → This IS leverage applied to learning",
    "",
    "DEEP WORK vs SHALLOW WORK:",
    "  4 hours focused coding > 8 hours of interrupted meetings + coding",
    "  High-leverage work requires uninterrupted deep focus",
    "  Protect morning hours for deep work, shallow tasks in afternoon",
    "```",
    "",
    "---",
    "",
    "## Networking and Reputation Leverage",
    "",
    "```",
    "YOUR REPUTATION IS AN ASSET THAT COMPOUNDS:",
    "",
    "  Contribute to open source:",
    "    10 quality PRs merged → GitHub profile shows technical depth",
    "    Technical depth → job offers, collaborations, trust",
    "    One hour of contribution = long-term career asset",
    "",
    "  Write technical content:",
    "    One great article → shared, read by 10,000 people",
    "    Positions you as expert in that area",
    "    Hiring managers Google your name — they find your articles",
    "",
    "  Build in public:",
    "    Share what you're building, problems you solved",
    "    Demonstrates work ethic, technical skill, communication",
    "    One tweet storm about a hard problem solved = credibility",
    "",
    "NETWORK LEVERAGE:",
    "  'Your network is your net worth' — who you know multiplies what you can do.",
    "  One strong technical mentor = 5 years of mistakes avoided.",
    "  One hiring manager in your network = dozens of referred applications.",
    "",
    "TEACH TO LEVERAGE LEARNING:",
    "  The Feynman technique: explain concept simply → identify gaps → fill gaps",
    "  Teaching forces you to deeply understand what you know",
    "  Record yourself explaining: replay catches your own unclear explanations",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "LEVERAGE STRATEGIES",
    "|",
    "+-- FOUR LEVERS",
    "|   +-- Code: write once, scales infinitely",
    "|   +-- Media: write once, reaches millions",
    "|   +-- Capital: money working for you",
    "|   +-- Labour: people multiplying your output",
    "|",
    "+-- DEVELOPER LEVERAGE",
    "|   +-- Automate repetitive tasks",
    "|   +-- Templates and defaults",
    "|   +-- Document thoroughly",
    "|   +-- AI as multiplier",
    "|",
    "+-- LEARNING LEVERAGE",
    "|   +-- Compound learning (concepts build on concepts)",
    "|   +-- Active > passive (solve > read)",
    "|   +-- Teach to learn (Feynman technique)",
    "|   +-- Spaced repetition (SM-2 in this app)",
    "|",
    "+-- REPUTATION LEVERAGE",
    "    +-- Open source contributions",
    "    +-- Technical writing",
    "    +-- Building in public",
    "    +-- Strong network",
    "```",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **How to Get Rich (without getting lucky)** by Naval Ravikant (tweetstorm):",
    "  https://www.youtube.com/watch?v=1-TZqOsVCNM",
    "- **Learn Like a Pro** by Barbara Oakley:",
    "  https://www.youtube.com/watch?v=O96fWhyeD5g",
    "",
    "### Articles",
    "- **Leverage and Technology** by Naval Ravikant: https://nav.al/leverage",
    "- **Deep Work** by Cal Newport — book summary: https://www.samuelthomasdavies.com/book-summaries/business/deep-work/",
])

patch("finance", "leverage-strategies.json", {"guide": LEVERAGE_GUIDE})

# ── FIN MACROECONOMICS — expand everything ────────────────────────────────────

MACRO_GUIDE = "\n".join([
    "# Macroeconomics for Developers",
    "",
    "## Why Should a Developer Care About Macroeconomics?",
    "",
    "Macro affects your career, salary, company's budget, and the tech industry's hiring cycles.",
    "Interest rate rises → VC funding dries up → tech layoffs → fewer jobs.",
    "Inflation → your real salary falls even if nominal salary stays the same.",
    "Recession → company freezes hiring, cuts cloud budgets, kills new projects.",
    "",
    "```",
    "2021 (low rates):    2022-2023 (rate hikes):",
    "  Cheap money           Expensive money",
    "  → VC invests freely   → VC pulls back",
    "  → Companies hire      → Companies lay off",
    "  → Salaries spike      → Salaries flatten",
    "  → 'Great Resignation' → 'Survival Mode'",
    "",
    "The macro cycle is the tide. You swim better if you understand the tide.",
    "```",
    "",
    "---",
    "",
    "## Key Macroeconomic Concepts",
    "",
    "```",
    "GDP (Gross Domestic Product):",
    "  Total value of goods/services produced in a country in a year.",
    "  Growing GDP = economy expanding = more hiring, more investment",
    "  Shrinking GDP for 2+ quarters = RECESSION = companies cut costs",
    "",
    "INFLATION:",
    "  General rise in prices over time.",
    "  Measured by CPI (Consumer Price Index) and PCE.",
    "  Target: ~2% per year (mild inflation = healthy economy)",
    "  > 5%: serious inflation — your savings lose purchasing power",
    "",
    "  For developers: salary negotiation timing matters.",
    "  If inflation is 8% and you got 3% raise: real pay cut of 5%.",
    "",
    "INTEREST RATES (set by central bank, e.g. Fed in US):",
    "  The cost of borrowing money.",
    "  High rates → borrowing expensive → companies invest less → fewer jobs",
    "  Low rates  → borrowing cheap → companies invest more → more jobs, startups",
    "",
    "  Tech industry is uniquely sensitive to interest rates:",
    "  Most startups are funded by borrowed VC money.",
    "  High rates = VCs can earn 5% safe in bonds instead of risking in startups.",
    "  → VC funding to startups drops sharply when rates rise.",
    "```",
    "",
    "---",
    "",
    "## The Interest Rate Cycle and Tech",
    "",
    "```",
    "FEDERAL FUNDS RATE history (simplified):",
    "",
    "  2008 (financial crisis): Fed cuts to 0%",
    "  2015-2018: Fed gradually raises",
    "  2020 (COVID): Fed cuts back to 0%",
    "  2022-2023: Fed raises aggressively (0% → 5.5% in 18 months)",
    "  2024: Fed starts cutting",
    "",
    "Impact on tech industry:",
    "",
    "  0% era (2020-2022):",
    "  └─ Startup valuations 10-100x revenue (growth priced in)",
    "  └─ Hiring frenzy (Netflix, Meta, Google all hiring 10K+/year)",
    "  └─ Remote work salaries jump",
    "  └─ 'Web3', 'metaverse' bubbles inflate",
    "",
    "  5.5% era (2022-2024):",
    "  └─ 'Discount Rate' math: future cash flows worth less → valuations crater",
    "  └─ 200K+ tech layoffs in 2022-2023",
    "  └─ IPO market freezes",
    "  └─ VC funding down 60%+",
    "  └─ Startups forced to profitability (good discipline, actually)",
    "",
    "Career lesson: low-rate environment = negotiate hard, leverage scarcity.",
    "High-rate environment = focus on stability, demonstrate value, avoid risky startups.",
    "```",
    "",
    "---",
    "",
    "## Inflation and Your Real Salary",
    "",
    "```",
    "REAL vs NOMINAL salary:",
    "  Nominal: the number on your payslip ($100K)",
    "  Real:    purchasing power adjusted for inflation",
    "",
    "  2020 salary: $100K",
    "  2021 inflation: 7%",
    "  2022 salary (no raise): $100K nominal",
    "  2022 real salary: $100K / 1.07 = $93,458 in 2020 dollars",
    "  → Real pay cut of 6.5% with no change in nominal salary",
    "",
    "TECH SALARIES vs INFLATION:",
    "  2020-2022: tech salaries rose 20-40% (demand > supply of engineers)",
    "  2022-2024: salaries stagnant/declining (layoffs, lower demand)",
    "  Engineers who changed jobs in 2020-2021 saw 30-50% raises.",
    "  Those who stayed at same company: inflation eroded real salary.",
    "",
    "LESSON: Understand your real salary = nominal salary / (1+inflation rate)",
    "Negotiate raises ahead of inflation rate to stay neutral.",
    "Change companies every 2-3 years for compensation reset.",
    "```",
    "",
    "---",
    "",
    "## Cloud and Tech Infrastructure in Economic Context",
    "",
    "```",
    "CLOUD SPENDING follows economic cycles:",
    "",
    "  Growth phase: companies throw money at cloud for speed",
    "  Recession/rate hike: CFO demands FinOps — cloud bills cut 30-50%",
    "",
    "  2022: 'FinOps' became a top priority at every company.",
    "  Cloud waste discovered: unused EC2 instances, over-provisioned RDS,",
    "  dev environments running 24/7, no reserved instances.",
    "",
    "  For developers in a downturn: understand cloud costs.",
    "  Knowing AWS cost optimisation = job security in tight markets.",
    "  'This engineer owns cost' = highly valued.",
    "",
    "TECH INVESTMENT PRIORITIES shift:",
    "  Bull market: invest in growth (new features, new products)",
    "  Bear market: invest in efficiency (automation, cost cuts, reliable systems)",
    "",
    "  Skills more valued in downturns:",
    "    Platform engineering (makes 10 engineers as productive as 15)",
    "    Observability (find and fix expensive inefficiencies)",
    "    AI automation (reduce headcount needed for tasks)",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "MACROECONOMICS FOR DEVELOPERS",
    "|",
    "+-- KEY INDICATORS",
    "|   +-- GDP: economy size and growth",
    "|   +-- Inflation: purchasing power erosion",
    "|   +-- Interest rates: cost of money",
    "|   +-- Unemployment: labour market tightness",
    "|",
    "+-- TECH CYCLE",
    "|   +-- Low rates → VC boom → hiring frenzy",
    "|   +-- High rates → VC pullback → layoffs",
    "|   +-- Cycle: ~5-7 years bull → bear → bull",
    "|",
    "+-- YOUR SALARY",
    "|   +-- Real = nominal / (1 + inflation)",
    "|   +-- Job switch = compensation reset",
    "|   +-- Negotiate before rate hikes dry up budgets",
    "|",
    "+-- CLOUD COSTS",
    "    +-- Follows economic cycle (growth vs efficiency)",
    "    +-- FinOps valuable in downturns",
    "    +-- Cost ownership = career security",
    "```",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **How the Economic Machine Works** by Ray Dalio:",
    "  https://www.youtube.com/watch?v=PHe0bXAIuk0 (30 min, must watch)",
    "- **Why Tech Layoffs Happened** by PatrickBoyle: https://www.youtube.com/watch?v=QLQR0UEOUUE",
    "",
    "### Articles",
    "- **Principles for Navigating Big Debt Crises** — Ray Dalio (free PDF): https://economicprinciples.org/",
    "- **The Tech Salary Guide** by levels.fyi: https://levels.fyi/",
])

MACRO_Q = [
    {"id":"macro-q1","type":"mcq","prompt":"Why did tech layoffs spike in 2022-2023?",
     "choices":["AI replaced engineers","Federal Reserve raised interest rates from 0% to 5.5%. High rates: 1) VCs can earn safe returns in bonds, reducing startup funding. 2) Future revenue worth less (higher discount rate) → valuations crash. 3) Overhired companies cut costs to survive higher borrowing costs.","Tech bubble simply popped","Cloud adoption declined"],
     "answerIndex":1,"explanation":"Interest rate math: at 0%, a company earning $1M in 5 years has present value $1M (no discount). At 5.5%, discounted back 5 years: $1M / (1.055^5) = $765K. Tech companies priced on future growth get hit hardest. VC funding dried up → startups couldn't raise → layoffs to extend runway.","tags":["rates","tech-cycle","macro"]},
    {"id":"macro-q2","type":"mcq","prompt":"Real salary vs nominal salary — you earn $120K in 2023, inflation was 4%. What is your real 2022-equivalent salary?",
     "choices":["$120,000","$115,385 ($120K / 1.04). Your $120K buys the same as $115,385 did in 2022. If you didn't get at least a 4% raise, your purchasing power declined.","$124,800","$96,000"],
     "answerIndex":1,"explanation":"Real salary = nominal / (1 + inflation rate). 4% inflation: $120K / 1.04 = $115,385 in prior-year dollars. Implication: to maintain purchasing power, raises must exceed inflation rate. In 2022 (7% inflation), even a 5% raise was a real pay cut.","tags":["salary","inflation","real-wages"]},
    {"id":"macro-q3","type":"mcq","prompt":"What does the Fed 'lowering interest rates' signal to the tech industry?",
     "choices":["Higher taxes incoming","Cheaper borrowing: companies invest more, VCs take on more risk (bonds less attractive), startup funding increases, hiring picks up, cloud spending grows. Historically preludes a tech hiring boom.","Less cloud adoption","Inflation is guaranteed"],
     "answerIndex":1,"explanation":"Fed rate cuts → lower 'risk-free rate' (bond yields fall). VCs: risk premium over bonds stays same, but absolute returns needed from bonds are lower → startups more attractive. Capital flows to growth assets. 2020: Fed cut to 0% → 2021-2022 hiring frenzy. 2024 cuts → same dynamics beginning.","tags":["interest-rates","vc-funding","hiring"]},
    {"id":"macro-q4","type":"mcq","prompt":"What is a recession and how should a developer prepare for one?",
     "choices":["Any period of rising unemployment","Two or more consecutive quarters of negative GDP growth. Developer preparation: build emergency fund (6 months expenses), avoid switching to risky startups near cycle peaks, focus on in-demand skills (cloud costs, observability), demonstrate measurable business impact.","When tech stocks fall 20%","Inflation above 5%"],
     "answerIndex":1,"explanation":"Recession: GDP shrinks for 2+ quarters. Tech often enters recession sentiment before official declaration if VC funding collapses. Preparation: 1) Emergency fund — layoffs happen fast. 2) In-demand skills (cost efficiency > growth features in downturns). 3) Avoid joining overfunded unprofitable startups late in bull cycles.","tags":["recession","career","preparation"]},
    {"id":"macro-q5","type":"mcq","prompt":"'FinOps' became critical in 2022-2023 because:",
     "choices":["New compliance requirements","Rate hikes forced companies to cut cloud bills 30-50%. Cloud waste discovered: idle instances, over-provisioned databases, no reserved instances. Engineers who could own and reduce cloud costs became highly valued during budget cuts.","AWS raised prices","Kubernetes required it"],
     "answerIndex":1,"explanation":"FinOps = financial operations for cloud. In growth mode: cloud bill is an afterthought. In survival mode: CFO demands cloud bill cut by 30%. Engineering teams audited idle resources, right-sized instances, bought Reserved Instances, killed dev environments overnight. Cloud cost ownership = job security in downturns.","tags":["finops","cloud-costs","recession"]},
    {"id":"macro-q6","type":"mcq","prompt":"What is the 'discount rate' and why does it make tech valuations sensitive to interest rates?",
     "choices":["A coupon code","The rate used to calculate present value of future cash flows. High discount rate: future revenue worth much less today. Tech companies valued on future growth get destroyed when rates rise — their future profits are discounted heavily.","Bank fees","AWS pricing tier"],
     "answerIndex":1,"explanation":"PV = FV / (1+r)^n. $1M in year 5: at r=0%, PV=$1M. At r=10%, PV=$1M/1.1^5=$621K. Tech companies priced at 20x future revenue: at 0% rates = $20M valuation. Same company at 10% rates: future revenue discounted → $12M valuation. Same business, 40% value drop purely from rate change.","tags":["valuation","discount-rate","tech-stocks"]},
    {"id":"macro-q7","type":"mcq","prompt":"What cycle length should developers use for career planning?",
     "choices":["1 year","Economic cycles average 5-10 years (boom to bust to boom). Tech hiring cycles: 2015-2019 boom, 2020-2022 boom, 2022-2023 bust. Plan: switch companies every 2-3 years for salary resets, build savings in boom times for recessions.","20 years","Cycles don't affect developers"],
     "answerIndex":1,"explanation":"Tech hiring cycles: tend to follow Fed policy and VC sentiment cycles. Boom (2020-2021): negotiate aggressively, multiple offers viable. Bust (2022-2023): stability > optimisation. Recovery (2024+): pick up pace of negotiation again. Engineers who stay flat during boom and switch during recovery miss compensation gains.","tags":["career-cycle","negotiation"]},
    {"id":"macro-q8","type":"mcq","prompt":"Inflation at 6% and you received a 4% raise. What happened to your real compensation?",
     "choices":["It increased by 4%","Real compensation fell approximately 2% (4% nominal - 6% inflation). In 2022: many tech workers received no raise while inflation hit 8-9% — effective 8-9% pay cut.","It stayed the same","Real compensation increased 2%"],
     "answerIndex":1,"explanation":"Approximate real raise = nominal raise % - inflation %. 4% - 6% = -2% real. Exact: (1.04/1.06) - 1 = -1.89%. Over 3 years of this: significant purchasing power erosion. Active job seekers in 2022 got 20-40% raises beating inflation. Those who stayed: 10-15% real pay cut over 2 years.","tags":["inflation","real-wages","career"]},
    {"id":"macro-q9","type":"mcq","prompt":"Why is understanding cloud spending important during economic downturns?",
     "choices":["Cloud becomes free","Companies aggressively cut cloud costs in downturns. Engineers who own cloud efficiency: job-protecting skill. Cloud bills: often 20-40% of a startup's burn rate. Cutting 30% = extending runway 3-6 months. That's survival.","Cloud spending always grows","Cloud is irrelevant in recessions"],
     "answerIndex":1,"explanation":"Startup burn rate example: $500K/month total, $150K is AWS. Cutting AWS by 30% = $45K/month saved = $540K/year. At current burn: 1+ extra month of runway. For a startup trying to reach profitability: cloud optimisation can be the difference between survival and shutdown.","tags":["cloud-costs","startup","recession"]},
    {"id":"macro-q10","type":"mcq","prompt":"Compound learning analogy to compound interest — what is the key insight?",
     "choices":["Learning is slower than finance","Knowledge compounds: knowing A makes learning B faster (B builds on A), which makes C faster. 1% daily improvement = 37x in a year. Early learning investments (fundamentals) have highest compounding leverage. Skipping fundamentals = slower compounding.","They are unrelated","Compound learning requires formal education"],
     "answerIndex":1,"explanation":"Investment: $1 growing 1%/day for 365 days = $37.78. Knowledge: understand TCP/IP → learning HTTP much easier. Know HTTP → learning REST APIs faster. Know REST → learning GraphQL faster. Foundational knowledge has the most compounding power. This is why CS fundamentals matter even for web developers.","tags":["compound-learning","leverage","fundamentals"]},
    {"id":"macro-q11","type":"mcq","prompt":"Should you join a funded startup during a bear market (high interest rates)?",
     "choices":["Always yes — startups are always better","High risk: VC funding is tight, runway may be limited, layoffs likely if they fail to raise next round. Unless you have equity that could be valuable at credible exit, the risk/reward may favour stable employment. Well-funded profitable startups: different.","Always no","Timing doesn't matter"],
     "answerIndex":1,"explanation":"During high-rate environment: startup funding down 60%+, valuations compressed = equity worth less. Startups that raised at 2021 valuations: equity underwater. Solid company with 18+ months runway and path to profitability: acceptable. Pre-revenue startup burning $500K/month with 9 months runway: significant risk.","tags":["startup","risk","timing"]},
    {"id":"macro-q12","type":"mcq","prompt":"What macroeconomic indicator most directly predicts tech hiring?",
     "choices":["Oil prices","Venture capital funding flows. VC investment leads hiring by 6-12 months: when VCs invest heavily, companies that raise then hire aggressively 6 months later. VC funding is itself driven by: interest rates, exits/IPOs market, LP returns.","GDP alone","Trade deficits"],
     "answerIndex":1,"explanation":"Tech hiring chain: Fed rates → bond yields → VC fund returns → VC investment → startup hiring. VC data is public (Crunchbase, PitchBook) with a quarter lag. VC funding in Q3 frequently predicts hiring intensity in Q1 of following year. Tracking VC activity = forward indicator of tech job market.","tags":["vc-funding","hiring","macro"]},
    {"id":"macro-q13","type":"mcq","prompt":"What is 'nominal' vs 'real' GDP growth?",
     "choices":["Same thing","Nominal GDP: total value in current dollars — includes inflation effect. Real GDP: adjusted for inflation. If nominal GDP grew 5% but inflation was 4%, real GDP growth was only 1%. Recessions defined by real GDP.","Real GDP includes government spending","Nominal GDP is per capita"],
     "answerIndex":1,"explanation":"Nominal GDP can rise while economy shrinks if inflation is high enough. Real GDP growth = nominal GDP growth - inflation rate (approximately). 2022 US: nominal GDP appeared positive, but real GDP contracted two quarters in a row — technically a recession by some definitions, though official NBER didn't call it one.","tags":["gdp","nominal","real"]},
    {"id":"macro-q14","type":"mcq","prompt":"Developer skill most valued in economic downturns vs upturns:",
     "choices":["Same skills matter regardless","Upturn: growth features, new products, speed of delivery. Downturn: cost reduction, reliability, observability, automation (reduce headcount), FinOps. Platform engineers (enable others) valued in downturns. Feature developers more valued in growth phases.","Downturns value security only","Upturns value security only"],
     "answerIndex":1,"explanation":"Recession hiring: 'do more with less'. Platform engineering (CI/CD, developer tools) = 1 infra engineer enables 10 product engineers = high leverage. Observability = find and fix expensive issues. AI automation = reduce manual work costs. Feature development slows when product investment pauses.","tags":["career","recession","skills"]},
    {"id":"macro-q15","type":"mcq","prompt":"What is the 'venture capital funding cycle' and why does it follow interest rates?",
     "choices":["VC cycles are random","VC LPs (pension funds, endowments) have target returns. At 0% rates: bonds return 0%, VC at 15% expected return looks great. At 5% rates: bonds safe at 5%, VC must return 20%+ to compensate risk. Higher hurdle → VCs more selective → less funding → fewer startups hired.","Only affected by IPO market","Not related to interest rates"],
     "answerIndex":1,"explanation":"VC as an asset class competes with other investments. Opportunity cost: LP chooses between bond (safe 5%) and VC fund (risky 15%). When bond yields rise, VC must offer higher returns to justify allocation. Higher return requirements = VCs invest less, more selectively, at lower valuations. 2022: VC investment fell 60%+ globally.","tags":["vc","interest-rates","funding"]},
    {"id":"macro-q16","type":"mcq","prompt":"What is 'burn rate' and why do developers need to understand it?",
     "choices":["Server processing speed","Rate at which a startup spends its cash reserve, usually measured monthly. Runway = cash / burn rate. High burn rate + low runway = company may shut down or do emergency layoffs. Developer: join companies with 18+ months runway.","Code deployment frequency","Memory usage rate"],
     "answerIndex":1,"explanation":"Startup: $3M raised, burns $300K/month = 10 months runway. Needs to raise or hit profitability in 10 months or fold. In 2022-2023 rate environment, many startups couldn't raise next round at acceptable valuation → layoffs or shutdown. Asking 'what's your runway?' before joining a startup is prudent.","tags":["startup","burn-rate","risk"]},
    {"id":"macro-q17","type":"mcq","prompt":"Why do cloud providers like AWS benefit from both bull and bear markets?",
     "choices":["They don't benefit in bear markets","Bull: companies use cloud for rapid scaling without capital outlay. Bear: FinOps — companies audit and shift from owned hardware to optimised cloud (consolidation, reserved instances). Cloud is essential infrastructure in both phases.","They only benefit in bull markets","AWS profits from data breaches"],
     "answerIndex":1,"explanation":"AWS 2022-2023: slowed growth but didn't collapse. Companies couldn't cut cloud entirely (apps run there). They optimised: reserved instances (commit to usage for discount), spot instances, rightsizing. Net: cloud spending more efficient, not eliminated. AWS earns less per workload but workloads stay.","tags":["aws","cloud","economic-cycle"]},
    {"id":"macro-q18","type":"mcq","prompt":"What does 'quantitative tightening' (QT) mean and how does it affect developers?",
     "choices":["Reducing software bugs","Fed selling bonds from its balance sheet, reducing money supply. Makes credit tighter, borrowing more expensive (reinforces rate hikes). Effect: even slower startup funding, lower evaluations, tech spending cuts.","Reducing cloud capacity","Reducing server costs"],
     "answerIndex":1,"explanation":"2020-2021: Fed did QE (buying bonds, expanding balance sheet, pumping money). 2022+: QT (selling bonds, shrinking money supply, removing liquidity). Double impact on tech: 1) higher rates → higher borrowing costs. 2) QT → less money sloshing around looking for returns → less VC allocation to tech.","tags":["fed-policy","qt","macro"]},
    {"id":"macro-q19","type":"mcq","prompt":"What should you do with savings during a tech bull market (low rates, hiring frenzy)?",
     "choices":["Spend freely — good times last","Build emergency fund (6+ months expenses), invest consistently (never try to time markets), avoid lifestyle inflation, build negotiating power through skills. Good times are when to prepare for bad times.","Take maximum financial risk","Quit and start a company immediately"],
     "answerIndex":1,"explanation":"Bull market behaviour: salary high, bonuses large, stock vesting well. Risk: lifestyle inflation (expensive rent, car, etc.) that's hard to reverse. Preparation: automate savings (pay yourself first), build 6-12 month emergency fund, index fund investments, pay down high-interest debt. When downturn hits: you have runway.","tags":["personal-finance","career","preparation"]},
    {"id":"macro-q20","type":"mcq","prompt":"How does the stock market relate to tech hiring, and is it a reliable indicator?",
     "choices":["Stock market has no relation","Stock market is a leading indicator (forward-looking) but imperfect. NASDAQ down 30%+ = tech company valuations down → hiring freeze typically follows 3-6 months later. But: profitable big tech (Google, Microsoft) can absorb stock drops better than unprofitable startups.","Stock market is perfectly correlated","Only small caps matter"],
     "answerIndex":1,"explanation":"Correlation not causation. NASDAQ crashed in 2022: tech hiring froze with 3-6 month lag. But: large profitable tech (Microsoft, Apple) hired more slowly, not emergency cuts. Unprofitable growth startups: immediate cuts. Better indicator than stock market: VC funding rounds, startup job postings, and weekly earnings calls from major tech companies.","tags":["stock-market","hiring","indicators"]},
]

MACRO_FC = [
    {"id":"macro-fc1","front":"Real salary formula","back":"Real salary = nominal salary / (1 + inflation rate). Approximate: real raise = nominal raise % - inflation %. If inflation=7% and raise=3%: real pay cut of ~4%. To stay neutral: raise must equal inflation rate. Job switch is the fastest way to reset.","tags":["salary","inflation"]},
    {"id":"macro-fc2","front":"Fed rate impact on tech hiring","back":"Rates ↑ → bond yields ↑ → VC opportunity cost ↑ → less VC funding → startups lay off or freeze hiring. Rates ↓ → bonds less attractive → VC invests more → hiring picks up. Lag: 6-12 months from rate change to hiring impact.","tags":["interest-rates","hiring"]},
    {"id":"macro-fc3","front":"Economic cycle for career planning","back":"Bull (low rates): negotiate aggressively, switch companies for 20-30% raises, stock options have positive momentum. Bear (high rates): prioritise stability, build cash reserves, focus on efficiency skills (cloud cost, platform eng), avoid late-stage underfunded startups.","tags":["career","economic-cycle"]},
    {"id":"macro-fc4","front":"Startup runway calculation","back":"Runway months = total cash / monthly burn rate. < 12 months: risky time to join. 18+ months: reasonable stability. 36+ months: very stable. Before joining: ask 'what's the runway?' and 'what are the next milestones?' Profitable = no runway concern.","tags":["startup","burn-rate"]},
    {"id":"macro-fc5","front":"FinOps in downturns","back":"Bear market: CFO mandates cloud bill cuts 30-50%. Valuable skills: identify idle resources, rightsize instances, buy Reserved Instances, eliminate dev/test waste, implement auto-shutdown. AWS cost reduction = extending company runway. Knowing this = job security.","tags":["finops","cloud","recession"]},
    {"id":"macro-fc6","front":"Compound learning = compound interest","back":"1% better daily = 37x in a year (1.01^365). Knowledge builds on knowledge: TCP→HTTP→REST→GraphQL each easier because of prior. Invest in fundamentals early (highest compounding leverage). Teach others: solidifies your own knowledge AND builds reputation.","tags":["compound-learning","leverage"]},
    {"id":"macro-fc7","front":"GDP recession definition","back":"Two or more consecutive quarters of REAL GDP growth being negative. Real GDP = nominal GDP adjusted for inflation. Recession signals for developers: VC funding falls, companies freeze headcount, cloud budgets cut. Typically: hiring lags GDP by 2-3 quarters.","tags":["gdp","recession"]},
    {"id":"macro-fc8","front":"Discount rate and tech valuations","back":"PV = FV / (1+r)^years. At r=0%: $1M in 5 years = $1M today. At r=10%: $1M in 5 years = $621K today. Tech companies priced on future growth: high rates → future earnings worth much less → valuations crash. Direct cause of 2022 tech valuation collapse.","tags":["valuation","discount-rate"]},
]

MACRO_PROJ = {
    "brief": "It is Q1 2026. The Fed has cut rates twice from their 2023 peak. You need to make the following decisions: 1) Should you negotiate a salary increase now or wait 6 months? 2) A Series B startup (18 months runway) is offering you 20% more salary + 0.5% equity. Should you take it? 3) Your company is asking you to help cut cloud bills by 30%. Where would you start? Reason through each using macroeconomic principles.",
    "checklist": [
        {"id":"m1","text":"Salary timing: Fed cuts signal hiring recovery in 6-12 months. Negotiate now while the next cycle begins, before competition increases.","weight":20},
        {"id":"m2","text":"Startup analysis: 18 months runway + Series B = reasonable stability. Check: burn rate vs MRR growth, path to profitability. Equity: 0.5% of what valuation? Model exit scenarios.","weight":20},
        {"id":"m3","text":"Cloud cuts: start with idle/overnight dev environments (often 20-30% waste). Then: rightsize over-provisioned RDS/ElastiCache. Buy Reserved Instances for steady-state workloads.","weight":20},
        {"id":"m4","text":"Real salary: current inflation ~3%. Negotiate at minimum 3% + performance component to maintain purchasing power.","weight":20},
        {"id":"m5","text":"Equity discounting: startup equity has discount rate too. Apply personal discount rate (opportunity cost) to determine if 0.5% compensates for job security risk differential.","weight":20},
    ],
    "hints": [
        "Equity value: 0.5% × (potential exit valuation) × (probability of exit) × (probability of staying to vest) × (dilution discount). Very rough: at $20M exit, 0.5% = $100K pre-tax before dilution.",
        "FinOps quick wins: AWS Trusted Advisor identifies low-hanging fruit. Cost Explorer by service. Enable S3 Intelligent-Tiering. Delete unattached EBS volumes.",
        "Negotiation timing: early in a rate-cutting cycle (now) = leverage improving. Competition for engineers has been low, about to rise. Negotiate before the market gets competitive again.",
    ]
}

patch("finance", "fin-macroeconomics.json", {
    "guide": MACRO_GUIDE,
    "questions": MACRO_Q,
    "flashcards": MACRO_FC,
    "project": MACRO_PROJ,
})

print("\n=== Thin topics fixed ===")
print("  leverage-strategies: guide expanded to full ~5000 chars")
print("  fin-macroeconomics: guide + questions + flashcards fully done")
print("")
print("💡 Macroeconomics is a context-switch topic! Try one of these after heavy tech topics:")
print("  - leverage-strategies (30 min read)")
print("  - fin-macroeconomics (1 hr, career & world context)")

