"""
Fix last thin topic: networking/ftp.json — expand guide to proper length.
Run: python3 scripts/fix_ftp_guide.py
"""
import json
from pathlib import Path

p = Path(__file__).parent.parent / "src/content/topics/networking/ftp.json"
d = json.loads(p.read_text())

FTP_GUIDE = "\n".join([
    "# FTP — File Transfer Protocol",
    "",
    "## What Is FTP and Why Does It Still Exist?",
    "",
    "FTP (File Transfer Protocol) is one of the oldest internet protocols still in use, dating from 1971.",
    "It transfers files between computers over a TCP/IP network. You'll encounter it when:",
    "- Deploying websites to shared hosting servers",
    "- Transferring large files to/from legacy enterprise systems",
    "- Working with scientific or government data archives",
    "- Understanding network security (FTP is often cited as an insecure protocol to avoid or harden)",
    "",
    "```",
    "Modern alternatives to plain FTP:",
    "  SFTP (SSH File Transfer Protocol)  ← use this by default — encrypted",
    "  FTPS (FTP over TLS/SSL)            ← encrypted FTP, for legacy FTP servers",
    "  SCP (Secure Copy Protocol)         ← simple file copy over SSH",
    "  HTTPS (S3, presigned URLs)         ← for web-based file transfer",
    "",
    "Plain FTP:  credentials sent in cleartext, never use over the internet",
    "SFTP/FTPS:  encrypted, safe — these are what you'll actually use",
    "```",
    "",
    "---",
    "",
    "## How FTP Works — The Two-Channel Architecture",
    "",
    "FTP is unusual: it uses TWO separate TCP connections, not one.",
    "",
    "```",
    "FTP CLIENT                    FTP SERVER",
    "     │                              │",
    "     │──── Control Channel ────────►│  (port 21)",
    "     │     Commands + responses     │",
    "     │     USER alice               │",
    "     │     PASS mypassword          │",
    "     │     LIST /files              │",
    "     │     RETR document.pdf        │",
    "     │                              │",
    "     │◄─── Data Channel ───────────►│  (port 20 active, random port passive)",
    "          Actual file content            ",
    "          Directory listings             ",
    "",
    "TWO CHANNELS:",
    "  Control channel (port 21): always open during session, sends commands",
    "  Data channel:              opened on-demand for each file transfer or directory listing",
    "  After transfer completes:  data channel closed, control channel stays open",
    "```",
    "",
    "**Why two channels?** Historical design: one channel for commands/responses (low bandwidth),",
    "a separate higher-bandwidth channel for the actual file data.",
    "",
    "---",
    "",
    "## Active vs Passive Mode",
    "",
    "This is the most confusing part of FTP, and the most important for firewall troubleshooting.",
    "",
    "```",
    "ACTIVE MODE (PORT mode):",
    "",
    "  Client opens control channel to server port 21",
    "  Client picks a port (e.g. 55123) and tells server: PORT 55,123",
    "  Server makes outbound connection BACK to client:55123 for data",
    "",
    "  Client: ──control──► Server:21",
    "  Server: ──data──────► Client:55123  ← SERVER connects TO CLIENT",
    "",
    "  Problem: if client is behind a NAT/firewall, server can't reach client.",
    "  Active mode FAILS in most modern network configurations.",
    "",
    "PASSIVE MODE (PASV mode):",
    "",
    "  Client opens control channel to server port 21",
    "  Client sends PASV command",
    "  Server opens a random high port (e.g. 54000) and tells client",
    "  Client makes outbound connection to server:54000 for data",
    "",
    "  Client: ──control──► Server:21",
    "  Client: ──data──────► Server:54000  ← CLIENT connects TO SERVER",
    "",
    "  Client only makes outbound connections → works through NAT/firewalls.",
    "  Passive mode WORKS in modern networks.",
    "",
    "RULE: Always use PASSIVE mode for modern FTP clients.",
    "      Most FTP clients default to passive mode already.",
    "",
    "FIREWALL IMPLICATION for servers running active mode:",
    "  Must allow inbound connections from high ports (1024-65535) = huge security hole",
    "  Passive mode: server only needs inbound on port 21 + a fixed port range",
    "  Configure passive port range: 50000-51000, open only those in firewall",
    "```",
    "",
    "---",
    "",
    "## FTP Commands",
    "",
    "```",
    "AUTHENTICATION:",
    "  USER alice        → send username",
    "  PASS mypassword   → send password (PLAINTEXT! Never use plain FTP over internet)",
    "  QUIT              → close session",
    "",
    "NAVIGATION:",
    "  PWD               → print working directory",
    "  CWD /home/alice   → change directory",
    "  CDUP              → change to parent directory",
    "  MKD newdir        → make directory",
    "",
    "FILE LISTING:",
    "  LIST              → detailed directory listing (like ls -la)",
    "  NLST              → name list only (like ls)",
    "",
    "TRANSFER COMMANDS:",
    "  RETR file.txt     → download: server sends file to client",
    "  STOR file.txt     → upload: client sends file to server",
    "  DELE file.txt     → delete a file",
    "  RNFR old.txt      → rename from (specify old name)",
    "  RNTO new.txt      → rename to (specify new name)",
    "  APPE file.txt     → append to existing file (resume partial upload)",
    "",
    "MODE COMMANDS:",
    "  PASV              → switch to passive mode",
    "  PORT h,h,h,h,p,p  → notify server of client port (active mode)",
    "  TYPE A            → ASCII transfer mode (text files, converts line endings)",
    "  TYPE I            → binary/image transfer mode (all other files)",
    "",
    "IMPORTANT: Always use TYPE I (binary) unless you specifically need ASCII mode.",
    "           ASCII mode corrupts binary files (images, executables, archives).",
    "```",
    "",
    "---",
    "",
    "## ASCII vs Binary Transfer Mode",
    "",
    "```",
    "ASCII mode (TYPE A):",
    "  Converts line endings during transfer:",
    "  Windows CRLF (\\r\\n) ↔ Unix LF (\\n)",
    "  Use ONLY for plain text files when transferring between Windows and Unix",
    "",
    "Binary mode (TYPE I, 'image' mode):",
    "  Transfers exact bytes — no conversion",
    "  Use for: images, executables, zip/tar archives, PDFs, Word documents, everything else",
    "",
    "Common mistake: FTP in ASCII mode corrupts binary files.",
    "  Transfer a .zip file in ASCII mode: FTP modifies bytes that happen to look like",
    "  line endings → corrupted archive → unzip fails.",
    "  Solution: ALWAYS use binary mode (TYPE I) unless you have a specific ASCII reason.",
    "",
    "Most modern FTP clients auto-detect file types. Still good to verify.",
    "```",
    "",
    "---",
    "",
    "## SFTP vs FTPS — The Secure Variants",
    "",
    "```",
    "+─────────────────────────────────────────────────────────────────────+",
    "│ Feature         │ SFTP                      │ FTPS                  │",
    "+─────────────────────────────────────────────────────────────────────+",
    "│ Protocol basis  │ SSH subsystem             │ FTP + TLS/SSL         │",
    "│ Default port    │ 22 (same as SSH)           │ 990 (or 21 explicit) │",
    "│ Channels        │ Single channel            │ Two channels (like FTP│",
    "│ Firewall        │ Easy (one port: 22)       │ Complex (like FTP)    │",
    "│ Compatibility   │ Needs SSH server          │ Needs TLS + FTP       │",
    "│ Setup           │ Simpler (piggybacks SSH)  │ More complex          │",
    "│ Recommendation  │ Prefer this               │ For legacy FTP systems│",
    "+─────────────────────────────────────────────────────────────────────+",
    "",
    "SFTP (SSH File Transfer Protocol):",
    "  Not FTP over SSH — it's a completely different protocol.",
    "  Designed from ground up as a secure file transfer protocol.",
    "  Runs as a subsystem of SSH. If you have SSH access: you have SFTP access.",
    "  Uses one encrypted channel for everything (commands + data).",
    "  Firewall-friendly: single port 22.",
    "",
    "  Connect: sftp alice@server.com",
    "  Or use FileZilla/Cyberduck with SFTP protocol option.",
    "",
    "FTPS (FTP Secure):",
    "  Original FTP protocol with TLS added.",
    "  Two variants: Explicit FTPS (start unencrypted, upgrade with AUTH TLS)",
    "                Implicit FTPS (encrypted from the start, port 990)",
    "  Firewall still needs data channel ports open.",
    "  Used when: legacy FTP infrastructure requires FTP protocol specifically.",
    "",
    "SCP (Secure Copy Protocol):",
    "  Simple file copy over SSH. No directory browsing.",
    "  Command: scp file.txt alice@server:/home/alice/",
    "  Fast, simple, but no resume on failure or directory sync.",
    "```",
    "",
    "---",
    "",
    "## Common FTP Use Cases Today",
    "",
    "```",
    "1. SHARED HOSTING DEPLOYMENT:",
    "   Many budget web hosts use FTP for file uploads.",
    "   Use FTPS or SFTP if offered. Never plain FTP.",
    "   Tools: FileZilla (free GUI client), Cyberduck (macOS/Win GUI)",
    "",
    "2. LEGACY ENTERPRISE SYSTEMS:",
    "   Banks, government systems, EDI (Electronic Data Interchange) still use FTP.",
    "   Usually FTPS internally, sometimes still plain FTP on isolated networks.",
    "   Automated scripts: ftp command-line client, lftp (Linux), WinSCP scripts",
    "",
    "3. SCIENTIFIC DATA ARCHIVES:",
    "   NCBI (genomics), NASA, NOAA — large public datasets via anonymous FTP",
    "   Anonymous FTP: USER anonymous, PASS email@address",
    "   wget or curl can also download from FTP URLs",
    "",
    "4. AUTOMATED FILE EXCHANGE:",
    "   Nightly batch jobs transfer reports between systems",
    "   Python ftplib: connect, login, RETR each file, process, close",
    "```",
    "",
    "---",
    "",
    "## FTP in Python",
    "",
    "```python",
    "from ftplib import FTP, FTP_TLS",
    "",
    "# Plain FTP (LAN/localhost only — unencrypted)",
    "with FTP('ftp.example.com') as ftp:",
    "    ftp.login(user='alice', passwd='password')",
    "    ftp.set_pasv(True)  # always passive mode",
    "    files = ftp.nlst()  # list files",
    "",
    "    # Download a file",
    "    with open('local_file.txt', 'wb') as f:",
    "        ftp.retrbinary('RETR remote_file.txt', f.write)",
    "",
    "    # Upload a file",
    "    with open('local_upload.txt', 'rb') as f:",
    "        ftp.storbinary('STOR remote_upload.txt', f)",
    "",
    "# FTPS (encrypted — use this for real scenarios)",
    "with FTP_TLS('ftp.example.com') as ftps:",
    "    ftps.login(user='alice', passwd='password')",
    "    ftps.prot_p()  # protect data channel with TLS",
    "    ftps.set_pasv(True)",
    "    # same commands as above",
    "",
    "# For SFTP (preferred): use paramiko or fabric",
    "import paramiko",
    "transport = paramiko.Transport(('server.com', 22))",
    "transport.connect(username='alice', password='password')",
    "sftp = paramiko.SFTPClient.from_transport(transport)",
    "sftp.get('/remote/file.txt', 'local_file.txt')  # download",
    "sftp.put('local.txt', '/remote/uploaded.txt')   # upload",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "FTP",
    "|",
    "+-- ARCHITECTURE",
    "|   +-- Control channel: port 21 (commands)",
    "|   +-- Data channel: port 20 (active) / random (passive)",
    "|   +-- Two channels open/close per transfer",
    "|",
    "+-- MODES",
    "|   +-- Active: server connects to client (breaks NAT)",
    "|   +-- Passive: client connects to server (use this)",
    "|   +-- ASCII: text, converts line endings (cautious)",
    "|   +-- Binary: exact bytes (always default)",
    "|",
    "+-- SECURE VARIANTS",
    "|   +-- SFTP: SSH-based, single channel, prefer",
    "|   +-- FTPS: FTP + TLS, legacy compatibility",
    "|   +-- SCP: simple SSH file copy",
    "|",
    "+-- COMMANDS",
    "|   +-- Authentication: USER, PASS",
    "|   +-- Navigation: PWD, CWD, MKD",
    "|   +-- Transfer: RETR, STOR, APPE",
    "|   +-- Control: PASV, TYPE I, QUIT",
    "|",
    "+-- SECURITY",
    "    +-- Plain FTP: never over internet (cleartext passwords)",
    "    +-- Firewall: passive mode + fixed port range",
    "    +-- Prefer SFTP (port 22) over FTPS",
    "```",
    "",
    "---",
    "",
    "## How FTP Connects to Other Topics",
    "",
    "- **Linux**: FTP commands run from the bash shell. `ftp`, `lftp`, `sftp` are",
    "  CLI tools. Server configs live in `/etc/vsftpd.conf`.",
    "- **Networking**: FTP demonstrates TCP connection management, port usage,",
    "  NAT traversal challenges. Active vs passive explains firewall concepts clearly.",
    "- **Security**: FTP is the canonical example of an insecure protocol. Teaches",
    "  why encryption (TLS/SSH) exists and why cleartext credentials are dangerous.",
    "- **Docker/CI-CD**: Some CI pipelines still deploy assets via FTP to shared hosts.",
    "  SFTP or FTPS used in Java/Python automation scripts.",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **FTP Explained** by NetworkChuck: https://www.youtube.com/watch?v=tOj8MSEIbfA",
    "- **SFTP Tutorial** by TechWorld with Nana: https://www.youtube.com/watch?v=b-QF-e9A_bE",
    "",
    "### Articles",
    "- **RFC 959 — FTP specification**: https://tools.ietf.org/html/rfc959",
    "- **FileZilla client** (free GUI): https://filezilla-project.org/",
    "- **Python ftplib docs**: https://docs.python.org/3/library/ftplib.html",
    "- **Paramiko (SFTP in Python)**: https://www.paramiko.org/",
])

d['guide'] = FTP_GUIDE
p.write_text(json.dumps(d, indent=2, ensure_ascii=False))
print(f"ftp.json patched: guide={len(FTP_GUIDE)} q={len(d['questions'])} fc={len(d['flashcards'])}")

