"""
Foundations Batch 1: Conceptual mental models
  - time-space-complexity (order 1)
  - recursion-mental-model (order 2)
Run: python3 scripts/foundations_batch1.py
"""
import json
from pathlib import Path

BASE = Path(__file__).parent.parent / "src/content/topics/foundations"
BASE.mkdir(parents=True, exist_ok=True)


def write(filename, data):
    out = BASE / filename
    if out.exists():
        existing = json.loads(out.read_text())
        if len(existing.get("questions", [])) >= 20:
            print(f"  SKIP {filename} (already complete)")
            return
    out.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    print(f"  WROTE {filename}: guide={len(data['guide'])} q={len(data['questions'])} fc={len(data['flashcards'])}")


# ── TIME & SPACE COMPLEXITY ──────────────────────────────────────────────────

COMPLEXITY_GUIDE = "\n".join([
    "# Time & Space Complexity",
    "",
    "## Why Care About Complexity?",
    "",
    "Your code might run on 10 items in your test, but production might have 10 million.",
    "How do you know if your algorithm will still finish in seconds — or will hang for hours?",
    "",
    "**Big-O notation** is a shorthand for: 'as input size grows, how does running time grow?'",
    "",
    "```",
    "  Items (n)     O(1)    O(log n)   O(n)      O(n log n)   O(n^2)         O(2^n)",
    "  10            1       3          10        33           100            1024",
    "  100           1       7          100       664          10,000         huge",
    "  1,000         1       10         1,000     9,966        1,000,000      crash",
    "  1,000,000     1       20         1M        20M          1 trillion!    impossible",
    "",
    "  Notice: O(n^2) at 1M items = 1 trillion operations = ~1000 SECONDS!",
    "          O(n)   at 1M items = 1M operations         = ~1 millisecond.",
    "  Same task, 1 million times difference in performance.",
    "```",
    "",
    "---",
    "",
    "## Big-O — The Growth Rate Hierarchy",
    "",
    "Big-O describes **the worst-case upper bound** of growth, ignoring constants and small terms.",
    "",
    "```",
    "From fastest growing (slowest) to slowest growing (fastest):",
    "",
    "O(1)        = constant         — independent of n",
    "                                  array[i], hash get, push to stack",
    "",
    "O(log n)    = logarithmic      — halves the problem each step",
    "                                  binary search, balanced BST lookup",
    "",
    "O(n)        = linear           — touches each element once",
    "                                  loop through array, max value",
    "",
    "O(n log n)  = linearithmic     — divide-and-conquer sorting",
    "                                  merge sort, quick sort (avg)",
    "",
    "O(n^2)      = quadratic        — nested loops over n",
    "                                  bubble sort, comparing all pairs",
    "",
    "O(n^3)      = cubic            — triple-nested",
    "                                  naive matrix multiply",
    "",
    "O(2^n)      = exponential      — recursive branching",
    "                                  naive Fibonacci, subset generation",
    "",
    "O(n!)       = factorial        — permutations",
    "                                  brute-force traveling salesman",
    "```",
    "",
    "---",
    "",
    "## How to Calculate Big-O — Step by Step",
    "",
    "```java",
    "// Example 1:",
    "void example1(int n) {",
    "    System.out.println('hi');     // 1 operation",
    "    System.out.println('hi');     // 1 operation",
    "}",
    "// Total: 2 operations, regardless of n",
    "// Big-O: O(1) — drop the constant 2",
    "",
    "// Example 2:",
    "void example2(int n) {",
    "    for (int i = 0; i < n; i++) {  // runs n times",
    "        System.out.println(i);      //   1 op per iteration",
    "    }",
    "}",
    "// Total: n × 1 = n operations",
    "// Big-O: O(n)",
    "",
    "// Example 3:",
    "void example3(int n) {",
    "    for (int i = 0; i < n; i++) {        // n times",
    "        for (int j = 0; j < n; j++) {    //   n times",
    "            System.out.println(i + j);   //     1 op",
    "        }",
    "    }",
    "}",
    "// Total: n × n × 1 = n^2 operations",
    "// Big-O: O(n^2)",
    "",
    "// Example 4 (TRICKY!):",
    "void example4(int n) {",
    "    for (int i = 0; i < n; i++) {        // n times",
    "        System.out.println(i);            //   1 op",
    "    }",
    "    for (int j = 0; j < n; j++) {        // n times",
    "        System.out.println(j);            //   1 op",
    "    }",
    "}",
    "// Total: n + n = 2n operations",
    "// Big-O: O(n) — drop the constant 2",
    "// Sequential loops ADD; nested loops MULTIPLY.",
    "```",
    "",
    "---",
    "",
    "## Rules of Thumb",
    "",
    "```",
    "1. DROP CONSTANTS:",
    "   O(2n) → O(n)",
    "   O(500) → O(1)",
    "   O(n/2) → O(n)",
    "",
    "2. DROP NON-DOMINANT TERMS:",
    "   O(n^2 + n) → O(n^2)",
    "   O(n + log n) → O(n)",
    "   O(2^n + 1000n) → O(2^n)",
    "",
    "3. DIFFERENT INPUTS = DIFFERENT VARIABLES:",
    "   for (int i = 0; i < a; i++) {",
    "     for (int j = 0; j < b; j++) {  ← b is independent of a",
    "       ...",
    "     }",
    "   }",
    "   Big-O: O(a × b)  NOT  O(n^2)",
    "",
    "4. RECURSIVE BRANCHING IS EXPONENTIAL:",
    "   fib(n) calls fib(n-1) and fib(n-2) — branching factor 2",
    "   Big-O: O(2^n)",
    "",
    "5. LOG SHOWS UP WHEN YOU HALVE:",
    "   Binary search: halve search space each step",
    "   Tree traversal: balanced tree height = log n",
    "   How many times can n be halved before reaching 1? log_2(n) times.",
    "```",
    "",
    "---",
    "",
    "## Common Operations Cheat Sheet",
    "",
    "```",
    "ARRAY:",
    "  Access by index (arr[i]):    O(1)",
    "  Search for value:            O(n)",
    "  Insert at end (amortised):   O(1)",
    "  Insert at front:             O(n) — shifts everything",
    "  Sort:                        O(n log n)",
    "",
    "ARRAYLIST / DYNAMIC ARRAY (Java's ArrayList):",
    "  Same as array, but resize on full = amortised O(1) for append",
    "",
    "LINKED LIST:",
    "  Access by index:             O(n) — must traverse",
    "  Insert/delete at head/tail:  O(1) — if you have the reference",
    "  Insert in middle:            O(n) — find then O(1) link",
    "",
    "HASH MAP / HASH SET:",
    "  Get/Put/Contains (avg):      O(1)",
    "  Get/Put/Contains (worst):    O(n) — when many collisions",
    "  Iterate all keys:            O(n)",
    "",
    "BINARY SEARCH TREE (balanced):",
    "  Insert/Search/Delete:        O(log n)",
    "  Worst case (unbalanced):     O(n) — like a linked list",
    "",
    "HEAP / PRIORITY QUEUE:",
    "  Insert:                      O(log n)",
    "  Peek min/max:                O(1)",
    "  Extract min/max:             O(log n)",
    "",
    "STACK / QUEUE (LinkedList-backed):",
    "  Push/Pop/Enqueue/Dequeue:    O(1)",
    "",
    "SORTING:",
    "  Quicksort (avg):             O(n log n)",
    "  Quicksort (worst):           O(n^2) — already sorted with bad pivot",
    "  Mergesort:                   O(n log n) — guaranteed",
    "  Bubble/Insertion/Selection:  O(n^2)",
    "",
    "GRAPH:",
    "  BFS/DFS (V vertices, E edges): O(V + E)",
    "  Dijkstra with heap:          O((V + E) log V)",
    "```",
    "",
    "---",
    "",
    "## Space Complexity — Memory Usage",
    "",
    "```",
    "Space complexity = how much extra memory does the algorithm use",
    "(not counting the input itself).",
    "",
    "void sumOf(int[] arr) {                    // input: arr",
    "    int sum = 0;                            // O(1) extra space",
    "    for (int x : arr) sum += x;",
    "}",
    "// Space: O(1)",
    "",
    "int[] doubleArray(int[] arr) {              // input: arr",
    "    int[] result = new int[arr.length];     // O(n) extra space",
    "    for (int i = 0; i < arr.length; i++) {",
    "        result[i] = arr[i] * 2;",
    "    }",
    "    return result;",
    "}",
    "// Space: O(n)",
    "",
    "// RECURSION USES STACK SPACE",
    "int fib(int n) {",
    "    if (n <= 1) return n;",
    "    return fib(n-1) + fib(n-2);",
    "}",
    "// Space: O(n) — call stack depth, even though branching is 2^n in time",
    "// Each recursive call adds a stack frame (function arguments, locals).",
    "// Stack overflow when depth exceeds ~1MB (~10000 frames in Java).",
    "```",
    "",
    "---",
    "",
    "## Real-World Mental Calibration",
    "",
    "```",
    "ROUGH RULE: A modern CPU does ~10^8 simple operations per second.",
    "",
    "If n = 10^6 (1 million):",
    "  O(n)        = 10^6 ops    = ~10ms      ✓ instant",
    "  O(n log n)  = 2×10^7 ops  = ~200ms     ✓ acceptable",
    "  O(n^2)      = 10^12 ops   = ~3 hours   ✗ too slow",
    "",
    "If n = 10^9 (1 billion):",
    "  O(n)        = 10^9 ops    = ~10s       ✓ slow but ok for batch",
    "  O(n log n)  = 3×10^10 ops = ~5 min    ✓ tolerable",
    "  O(n^2)      = 10^18 ops   = 30+ years  ✗ never",
    "",
    "PRACTICAL THRESHOLDS (for online API or interactive UI):",
    "  n ≤ 10:           any algorithm works (even O(n!) for n ≤ 8)",
    "  n ≤ 100:          O(n^3) ok",
    "  n ≤ 1,000:        O(n^2) ok",
    "  n ≤ 1,000,000:    O(n log n) needed",
    "  n ≤ 10,000,000:   O(n) needed",
    "  n > 10^9:         O(log n) or pre-computed",
    "",
    "INTERVIEW HEURISTIC: if your O(n^2) solution looks reasonable,",
    "the interviewer almost certainly wants you to find an O(n log n) or O(n) approach.",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "TIME & SPACE COMPLEXITY",
    "|",
    "+-- BIG-O NOTATION",
    "|   +-- Worst-case upper bound",
    "|   +-- Drop constants, drop non-dominants",
    "|   +-- Sequential adds, nested multiplies",
    "|",
    "+-- HIERARCHY (best to worst)",
    "|   +-- O(1)        constant",
    "|   +-- O(log n)    halve each step",
    "|   +-- O(n)        single pass",
    "|   +-- O(n log n)  divide-and-conquer sort",
    "|   +-- O(n^2)      nested loops",
    "|   +-- O(2^n)      recursive branching",
    "|   +-- O(n!)       permutations",
    "|",
    "+-- DATA STRUCTURE OPS",
    "|   +-- Array: O(1) access, O(n) search",
    "|   +-- HashMap: O(1) avg, O(n) worst",
    "|   +-- BST balanced: O(log n) all ops",
    "|   +-- Heap: O(log n) insert/extract",
    "|",
    "+-- SPACE COMPLEXITY",
    "    +-- Auxiliary memory used by algorithm",
    "    +-- Recursion = O(depth) stack frames",
    "    +-- Tradeoff: space for time (memoisation)",
    "```",
    "",
    "---",
    "",
    "## How This Connects to Other Topics",
    "",
    "- **DSA**: every algorithm and data structure topic uses Big-O analysis",
    "- **System Design**: 'will this scale to 1M users?' = Big-O thinking on a system level",
    "- **Database queries**: SQL EXPLAIN shows query complexity (full scan = O(n), index = O(log n))",
    "- **Frontend rendering**: O(n^2) re-renders kill React performance — same Big-O thinking",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **Big O Notation in 5 Minutes** by Jeff Dean: https://www.youtube.com/watch?v=__vX2sjlpXU",
    "- **Big O Notation, Time and Space Complexity** by HackerRank: https://www.youtube.com/watch?v=v4cd1O4zkGw",
    "",
    "### Articles",
    "- **Big-O Cheat Sheet**: https://www.bigocheatsheet.com/",
    "- **Big-O Algorithms** by Khan Academy: https://www.khanacademy.org/computing/computer-science/algorithms/asymptotic-notation/a/big-o-notation",
])

COMPLEXITY_Q = [
    {"id":"cmplx-q1","type":"mcq","prompt":"What does Big-O notation describe?",
     "choices":["The exact number of operations","An upper bound on growth rate as input size approaches infinity, ignoring constants and lower-order terms","The best-case running time","The memory layout of an algorithm"],
     "answerIndex":1,"explanation":"Big-O is asymptotic notation. It describes how an algorithm's runtime/memory grows as n grows large, ignoring constants (5n vs 1n both = O(n)) and lower-order terms (n^2 + n = O(n^2)). It's a worst-case upper bound — the algorithm performs no worse than this growth rate.","tags":["big-o","fundamentals"]},
    {"id":"cmplx-q2","type":"mcq","prompt":"Two sequential O(n) loops over the same input — what's the total complexity?",
     "choices":["O(n^2)","O(2n) which simplifies to O(n) — sequential loops add, then we drop constants","O(n log n)","O(1)"],
     "answerIndex":1,"explanation":"Sequential operations ADD. n + n = 2n. Big-O drops constants: O(2n) = O(n). Compare to NESTED loops which multiply: O(n×n) = O(n^2). Recognising sequential vs nested is the most common Big-O mistake.","tags":["big-o","sequential","calculation"]},
    {"id":"cmplx-q3","type":"mcq","prompt":"Binary search on a sorted array of n elements — what's the complexity?",
     "choices":["O(n)","O(log n) — each step halves the search space, so the number of steps is log_2(n)","O(n log n)","O(1)"],
     "answerIndex":1,"explanation":"Binary search halves the remaining search range each comparison. Starting at n, the question is: how many times can you halve n before reaching 1? Answer: log_2(n) times. For n=1M, that's only ~20 comparisons. This is why sorted arrays + binary search beat linear search dramatically.","tags":["big-o","binary-search","logarithmic"]},
    {"id":"cmplx-q4","type":"mcq","prompt":"What is the time complexity of accessing arr[i] in a Java array?",
     "choices":["O(n)","O(1) — array access by index uses pointer arithmetic: base_address + (i × element_size). Single memory read regardless of array size or position.","O(log n)","O(i)"],
     "answerIndex":1,"explanation":"Arrays store elements in contiguous memory. arr[i] = base + i*sizeof(element). Computed in constant time, single memory access. Linked list arr[i] is O(n) because you must walk node by node. This is why arrays are preferred for random access.","tags":["array","access","constant"]},
    {"id":"cmplx-q5","type":"mcq","prompt":"What is the WORST-case time complexity of HashMap.get(key) in Java?",
     "choices":["O(1) always","O(log n)","O(n) — when many keys hash to the same bucket (collisions), lookup degrades to a linear scan of that bucket. Java 8+ converts long collision chains to a tree (O(log n)) at threshold.","O(n^2)"],
     "answerIndex":2,"explanation":"HashMap average-case: O(1). Worst-case: O(n) when all keys hash to same bucket. Java 8+ improvement: when bucket has 8+ entries, converts to red-black tree, making worst-case O(log n). Most code only cares about average. Bad hash function or adversarial input can trigger worst case.","tags":["hashmap","worst-case"]},
    {"id":"cmplx-q6","type":"codeOutput","prompt":"What is the time complexity of this Java code?",
     "code":"void f(int[] a, int[] b) {\n    for (int x : a) {\n        for (int y : b) {\n            System.out.println(x + y);\n        }\n    }\n}",
     "choices":["O(n)","O(n^2) — nested loops over same n","O(a × b) where a and b are different sizes","O(a + b)"],
     "answerIndex":2,"explanation":"Nested loops multiply, but a and b are DIFFERENT inputs. Don't lazily call this O(n^2) — that assumes a.length == b.length. Correct: O(a × b). If a=1000 and b=10, it's 10,000 operations, not 1,000,000. Different inputs need different variables in Big-O analysis.","tags":["big-o","multiple-inputs"]},
    {"id":"cmplx-q7","type":"mcq","prompt":"What is the space complexity of recursive Fibonacci: fib(n) returns fib(n-1) + fib(n-2)?",
     "choices":["O(2^n)","O(n) — call stack depth is at most n, even though TIME complexity is O(2^n) due to recursive branching","O(1)","O(log n)"],
     "answerIndex":1,"explanation":"Subtle: time vs space differ. Time: each call branches into 2, so total calls is O(2^n). Space: at any moment, only one branch is being computed; max stack depth = n (going from fib(n) down to fib(0)). Once fib(n-1) returns, that stack space is reclaimed before fib(n-2) is called.","tags":["recursion","space-complexity","fibonacci"]},
    {"id":"cmplx-q8","type":"mcq","prompt":"O(n^2 + 1000n + 5) simplifies to:",
     "choices":["O(n^2 + 1000n)","O(n^2) — drop non-dominant terms (1000n is dwarfed by n^2 for large n) and constants","O(n^3)","O(1000n)"],
     "answerIndex":1,"explanation":"Drop non-dominant terms: as n grows, n^2 dwarfs 1000n. At n=10000: n^2 = 10^8, 1000n = 10^7 — the n^2 term is 10x bigger. At n=10^6: n^2 = 10^12 vs 1000n = 10^9 — 1000x. Constants and lower-order terms become irrelevant. Final: O(n^2).","tags":["big-o","simplification"]},
    {"id":"cmplx-q9","type":"mcq","prompt":"For an input of n=10^6, which complexity is too slow for a typical interactive web request (target <100ms)?",
     "choices":["O(n)","O(n log n)","O(n^2) — 10^12 operations ≈ 1000+ seconds","O(log n)"],
     "answerIndex":2,"explanation":"Mental model: ~10^8 simple ops/sec on a modern CPU. n=10^6: O(n)=10^6=10ms (fine), O(n log n)=2×10^7=200ms (borderline), O(n^2)=10^12=10000s (impossible). Online APIs need O(n) or better at n=10^6. O(n^2) is fine only when n ≤ ~3000.","tags":["big-o","practical","performance"]},
    {"id":"cmplx-q10","type":"mcq","prompt":"What is the time complexity of mergesort?",
     "choices":["O(n^2) worst case","O(n log n) — guaranteed in ALL cases (best, average, worst). Divide step has log n levels, each level processes n elements.","O(n log log n)","O(n) average"],
     "answerIndex":1,"explanation":"Mergesort divides the array log n times (each step halves), and at each level merges n elements total. Result: n × log n = O(n log n). Unlike quicksort (which can degrade to O(n^2) on bad pivots), mergesort guarantees O(n log n) in worst case. Trade-off: O(n) extra space.","tags":["sorting","mergesort","divide-and-conquer"]},
    {"id":"cmplx-q11","type":"mcq","prompt":"Inserting at the FRONT of an ArrayList of size n — complexity?",
     "choices":["O(1)","O(log n)","O(n) — must shift all existing elements one position to the right","O(n^2)"],
     "answerIndex":2,"explanation":"ArrayList stores elements in a backing array. Inserting at front: every existing element shifts right by 1 = n shifts = O(n). Inserting at END is O(1) amortised (occasional resize). For frequent front inserts: use ArrayDeque or LinkedList instead.","tags":["arraylist","insertion"]},
    {"id":"cmplx-q12","type":"mcq","prompt":"In a balanced binary search tree (Red-Black, AVL), search complexity is:",
     "choices":["O(n)","O(log n) — tree height is bounded at log_2(n) due to balancing rotations","O(1)","O(n log n)"],
     "answerIndex":1,"explanation":"Balanced BSTs maintain height ~log n via rotations. Each search descends one level per comparison. Worst case: log_2(n) comparisons. For n=1M: ~20 comparisons. Java TreeMap uses red-black tree. Unbalanced BST (insert sorted data) degenerates to linked list = O(n) — that's why balancing matters.","tags":["bst","balanced","search"]},
    {"id":"cmplx-q13","type":"mcq","prompt":"What does 'amortised O(1)' mean for ArrayList.add() at end?",
     "choices":["Always exactly O(1)","Average over a long sequence of operations: most adds are O(1), but occasional resizes cost O(n). Total cost / number of operations = O(1) on average.","Best-case O(1)","Worst-case O(1)"],
     "answerIndex":1,"explanation":"ArrayList grows by doubling when full. Most adds: O(1). When full, resize: copy n elements to new array = O(n) for that one add. But resizes are rare: after n adds, only log(n) resizes happened. Total: n + 2 + 4 + ... + n = ~3n operations for n adds. Per add: 3n/n = 3 = O(1) amortised.","tags":["amortised","arraylist","analysis"]},
    {"id":"cmplx-q14","type":"mcq","prompt":"Which algorithm is correctly classified?",
     "choices":["Bubble sort: O(n log n)","Quick sort average: O(n log n) — typical good-pivot case","Hash insert: O(log n)","Linear search: O(log n)"],
     "answerIndex":1,"explanation":"Quicksort: average O(n log n), worst O(n^2). Bubble sort: O(n^2). Hash insert avg: O(1). Linear search: O(n). Knowing the standard complexities is essential for technical interviews and choosing the right algorithm for a problem.","tags":["complexities","standard"]},
    {"id":"cmplx-q15","type":"mcq","prompt":"Time complexity of generating all subsets of n elements:",
     "choices":["O(n^2)","O(2^n) — there are 2^n subsets (each element either in or out), and we must produce each","O(n!)","O(n log n)"],
     "answerIndex":1,"explanation":"For n elements, there are 2^n possible subsets (each element has 2 choices: included/excluded). Even just enumerating them is O(2^n). For n=20: 1M subsets. For n=30: 1 billion. n=40: 1 trillion (intractable). This is why subset/power-set algorithms work only for small n.","tags":["big-o","exponential","subsets"]},
    {"id":"cmplx-q16","type":"mcq","prompt":"Memoisation vs naive recursion — typical impact on Fibonacci?",
     "choices":["No change","Time O(2^n) → O(n), space O(n) → O(n) — memo cache trades space for huge time savings","Time stays the same","Time worse"],
     "answerIndex":1,"explanation":"Naive fib(n) recomputes fib(5) hundreds of times in fib(40). Memoisation: cache results. Each fib(k) computed exactly once. Time goes from O(2^n) to O(n). Space increases from O(n) call stack to O(n) call stack + O(n) cache = still O(n). Classic 'space for time' trade.","tags":["memoisation","dynamic-programming","recursion"]},
    {"id":"cmplx-q17","type":"multi","prompt":"Which operations are O(1) on average for HashMap?",
     "choices":["get(key)","put(key, value)","containsKey(key)","keySet()"],
     "answerIndexes":[0,1,2],"explanation":"get/put/containsKey/remove are all O(1) average (worst O(n) on collisions). keySet() returns a view but iterating it is O(n). Just calling keySet() is O(1) (returns lazy view), but iterating O(n).","tags":["hashmap","operations"]},
    {"id":"cmplx-q18","type":"mcq","prompt":"What is O(n) space complexity caused by in this code?",
     "choices":["The for loop","Creating a new array of size n inside the function — auxiliary space, separate from input","The print statements","Nothing — it's O(1)"],
     "answerIndex":1,"explanation":"Space complexity counts EXTRA memory beyond input. A new array allocates n elements = O(n) auxiliary space. Loop variables and print statements use O(1). The input array doesn't count (we already had it). To reduce: try to modify in-place if possible.","tags":["space-complexity","auxiliary"]},
    {"id":"cmplx-q19","type":"mcq","prompt":"Why is binary search O(log n) and not O(n/2)?",
     "choices":["They're the same","O(n/2) simplifies to O(n) (drop constants), and binary search isn't 'half the work' — it RECURSIVELY halves until reaching 1, doing log_2(n) comparisons total.","Binary search uses logarithm","Convention"],
     "answerIndex":1,"explanation":"Common confusion. n/2 = doing half the work once = still linear (Big-O drops constants). Binary search keeps halving the remaining range: n → n/2 → n/4 → n/8 → ... → 1. Number of halvings to go from n to 1 = log_2(n). That's why it's O(log n), not O(n/2).","tags":["binary-search","logarithmic","misconception"]},
    {"id":"cmplx-q20","type":"mcq","prompt":"For Heap (PriorityQueue) in Java, which operation is O(1)?",
     "choices":["offer (insert)","poll (extract min)","peek (look at min) — accessing root of heap is constant time","contains"],
     "answerIndex":2,"explanation":"Min-heap: smallest element is always at root (index 0 of array-backed heap). peek() returns it in O(1). offer() and poll() require sift-up/sift-down to maintain heap property, both O(log n). contains() requires linear scan O(n) — heaps aren't designed for searching arbitrary values.","tags":["heap","priority-queue","operations"]},
]

COMPLEXITY_FC = [
    {"id":"cmplx-fc1","front":"Big-O simplification rules","back":"1) Drop constants: O(2n)=O(n), O(500)=O(1). 2) Drop non-dominant terms: O(n^2+n)=O(n^2). 3) Sequential ops add, nested ops multiply. 4) Different inputs = different variables: O(a × b) not O(n^2).","tags":["big-o","rules"]},
    {"id":"cmplx-fc2","front":"Complexity hierarchy","back":"O(1) < O(log n) < O(n) < O(n log n) < O(n^2) < O(2^n) < O(n!). At n=10^6: O(n)=10ms, O(n log n)=200ms, O(n^2)=hours, O(2^n)=impossible. Choose algorithm based on expected n.","tags":["big-o","hierarchy"]},
    {"id":"cmplx-fc3","front":"Array vs LinkedList vs HashMap","back":"Array: O(1) access by index, O(n) search. LinkedList: O(n) access, O(1) head/tail insert. HashMap: O(1) avg get/put/contains. Pick by: random access frequency, insert position, lookup pattern.","tags":["data-structures","complexity"]},
    {"id":"cmplx-fc4","front":"BST balanced vs unbalanced","back":"Balanced BST (Red-Black, AVL): O(log n) all ops, height bounded. Unbalanced (insert sorted): degenerates to linked list, O(n). Java TreeMap is red-black. C++ std::map too. Manually implementing BST without rotations = bug.","tags":["bst","balanced"]},
    {"id":"cmplx-fc5","front":"Sorting algorithms cheat sheet","back":"Quicksort: avg O(n log n), worst O(n^2). Mergesort: O(n log n) guaranteed, O(n) extra space. Heapsort: O(n log n) guaranteed, O(1) space. Insertion: O(n^2), but O(n) on nearly-sorted. Bubble: never use (O(n^2)).","tags":["sorting","algorithms"]},
    {"id":"cmplx-fc6","front":"Recursion = stack space","back":"Each recursive call adds a stack frame (locals, return address). Depth d = O(d) space. Java default stack: ~1MB ≈ 10K frames. Too deep = StackOverflowError. Convert to iteration with explicit stack, or use tail-call optimisation (not Java).","tags":["recursion","stack"]},
    {"id":"cmplx-fc7","front":"Memoisation: space for time","back":"Cache previously computed results. Naive fib(n)=O(2^n). Memoised fib(n)=O(n) time, O(n) space. Apply when: 1) function deterministic, 2) overlapping subproblems, 3) memory available. Map<Input, Output> in instance variable.","tags":["memoisation","dp"]},
    {"id":"cmplx-fc8","front":"Practical n thresholds","back":"For interactive (<100ms): n<10⁶ → need O(n log n). n<10⁹ → need O(n) or pre-compute. n<10¹² → need O(log n) or external. n>10¹² → distributed/streaming. Match algorithm complexity to expected n!","tags":["performance","scale"]},
]

COMPLEXITY_PROJ = {
    "brief": "You're optimising a feature that ranks 100,000 search results by relevance. The naive implementation uses a nested O(n^2) loop that's taking 8 seconds. Design a faster approach: 1) Identify what makes the current code O(n^2). 2) Propose 3 alternative approaches with their complexities. 3) Pick the best for this use case. 4) Estimate runtime improvement.",
    "checklist": [
        {"id":"c1","text":"Identify the O(n²) cause: probably nested comparison or score calculation. State it precisely.","weight":20},
        {"id":"c2","text":"Approach 1: pre-compute scores once O(n), then sort O(n log n) — total O(n log n)","weight":20},
        {"id":"c3","text":"Approach 2: heap of top-K results — O(n log k) where k=20 results shown","weight":20},
        {"id":"c4","text":"Approach 3: parallelise across cores — same Big-O but constant speedup proportional to cores","weight":20},
        {"id":"c5","text":"Estimate: O(n²)=10^10 ops≈100s. O(n log n)=2×10^6 ops≈20ms. ~5000x speedup. Best choice: pre-compute + sort.","weight":20},
    ],
    "hints": [
        "If only top 20 results displayed: O(n log k) heap approach has the smallest k factor — fastest in practice for top-K.",
        "Be careful: if scores need to be recomputed per query (depend on query terms), pre-compute may not apply. Then heap of top-K is optimal.",
        "Constants matter: O(n log n) sort with cache-friendly contiguous memory is often faster than O(n) algorithms that pointer-chase.",
    ]
}

write("time-space-complexity.json", {
    "id": "time-space-complexity",
    "unit": 1,
    "order": 1,
    "title": "Time & Space Complexity",
    "summary": "Big-O notation, complexity hierarchy, common data structure operations, and practical performance thinking.",
    "prereqs": [],
    "guide": COMPLEXITY_GUIDE,
    "questions": COMPLEXITY_Q,
    "flashcards": COMPLEXITY_FC,
    "project": COMPLEXITY_PROJ,
})

# ── RECURSION MENTAL MODEL ───────────────────────────────────────────────────

RECURSION_GUIDE = "\n".join([
    "# Recursion — A Mental Model That Works",
    "",
    "## What Is Recursion?",
    "",
    "A recursive function calls itself. Sounds simple, but new programmers find it mind-bending.",
    "The key insight: **trust the recursion**. Don't try to trace through every call manually.",
    "Instead, think 'if my function works for smaller inputs, it works for the bigger one.'",
    "",
    "```",
    "Imagine looking up a word in a paper dictionary:",
    "  Open dictionary in middle, see word at top of page.",
    "  Word starts with M, my word starts with R → look in second half.",
    "  Take second half, open in middle, see Q.",
    "  My word starts with R → look in second half of THAT.",
    "  Continue until you find your word or run out of pages.",
    "",
    "Each step: 'do same operation on smaller input.' That's recursion.",
    "```",
    "",
    "---",
    "",
    "## Anatomy of a Recursive Function",
    "",
    "Every recursive function MUST have two things:",
    "",
    "```",
    "1. BASE CASE: a condition that stops recursion (no more calls)",
    "2. RECURSIVE CASE: calls itself with a SMALLER input",
    "",
    "If missing base case  → infinite recursion → StackOverflowError",
    "If recursive case isn't smaller → infinite recursion → StackOverflowError",
    "",
    "Example — factorial:",
    "",
    "  int factorial(int n) {",
    "      if (n <= 1) return 1;          // BASE CASE — stops here",
    "      return n * factorial(n - 1);    // RECURSIVE CASE — smaller input",
    "  }",
    "",
    "  factorial(4)",
    "    = 4 * factorial(3)",
    "        = 4 * (3 * factorial(2))",
    "            = 4 * (3 * (2 * factorial(1)))",
    "                = 4 * (3 * (2 * 1))    ← base case returns 1",
    "                = 4 * (3 * 2)",
    "                = 4 * 6",
    "                = 24",
    "```",
    "",
    "---",
    "",
    "## The Three Steps to Solve Any Recursion",
    "",
    "```",
    "STEP 1: BASE CASE",
    "  What's the simplest input where the answer is obvious?",
    "  - factorial(0) or factorial(1) = 1",
    "  - sum of empty list = 0",
    "  - reverse of empty string = empty string",
    "",
    "STEP 2: RECURSIVE CASE",
    "  Assume the function works for a smaller input (TRUST IT).",
    "  How can you use that result to solve the current one?",
    "  - factorial(n) = n × factorial(n-1)",
    "  - sum([first, ...rest]) = first + sum(rest)",
    "  - reverse(s) = reverse(s[1:]) + s[0]",
    "",
    "STEP 3: VERIFY PROGRESS",
    "  Each recursive call must move TOWARD the base case.",
    "  - factorial(n-1) is smaller than n ✓",
    "  - rest is shorter than original ✓",
    "  - s[1:] is shorter than s ✓",
    "",
    "If all three are correct, the function works. Don't trace manually.",
    "```",
    "",
    "---",
    "",
    "## Visualising the Call Stack",
    "",
    "```",
    "Each function call adds a STACK FRAME (locals + return address).",
    "When the call returns, its frame is removed.",
    "",
    "factorial(3):",
    "",
    "Time →",
    "",
    "  Stack:                       Return value:",
    "  ┌─────────────┐",
    "  │ factorial(3)│",
    "  └─────────────┘",
    "       │ calls",
    "       ▼",
    "  ┌─────────────┐",
    "  │ factorial(2)│",
    "  ├─────────────┤",
    "  │ factorial(3)│",
    "  └─────────────┘",
    "       │ calls",
    "       ▼",
    "  ┌─────────────┐",
    "  │ factorial(1)│   returns 1 (base case)",
    "  ├─────────────┤",
    "  │ factorial(2)│",
    "  ├─────────────┤",
    "  │ factorial(3)│",
    "  └─────────────┘",
    "       │ unwinds",
    "       ▼",
    "  ┌─────────────┐",
    "  │ factorial(2)│   returns 2 * 1 = 2",
    "  ├─────────────┤",
    "  │ factorial(3)│",
    "  └─────────────┘",
    "       │ unwinds",
    "       ▼",
    "  ┌─────────────┐",
    "  │ factorial(3)│   returns 3 * 2 = 6",
    "  └─────────────┘",
    "       │",
    "       ▼",
    "  Final result: 6",
    "",
    "Stack depth = max number of nested calls = O(n) for factorial",
    "```",
    "",
    "---",
    "",
    "## Common Recursion Patterns",
    "",
    "```",
    "PATTERN 1: REDUCE-AND-COMBINE",
    "",
    "  Problem can be split: solve smaller part, combine with current.",
    "",
    "  int sumList(List<Integer> list) {",
    "      if (list.isEmpty()) return 0;",
    "      return list.get(0) + sumList(list.subList(1, list.size()));",
    "  }",
    "",
    "PATTERN 2: DIVIDE-AND-CONQUER",
    "",
    "  Split input into halves, recurse on each, combine.",
    "",
    "  int[] mergeSort(int[] arr) {",
    "      if (arr.length <= 1) return arr;",
    "      int mid = arr.length / 2;",
    "      int[] left = mergeSort(slice(arr, 0, mid));      // recurse",
    "      int[] right = mergeSort(slice(arr, mid, arr.length)); // recurse",
    "      return merge(left, right);",
    "  }",
    "",
    "PATTERN 3: BACKTRACKING (try all paths)",
    "",
    "  Try a choice, recurse, undo if it doesn't lead to solution.",
    "",
    "  void permute(char[] chars, int start) {",
    "      if (start == chars.length) {",
    "          print(chars);   // base case: full permutation",
    "          return;",
    "      }",
    "      for (int i = start; i < chars.length; i++) {",
    "          swap(chars, start, i);     // try this choice",
    "          permute(chars, start + 1); // recurse",
    "          swap(chars, start, i);     // undo (backtrack)",
    "      }",
    "  }",
    "",
    "PATTERN 4: TREE / GRAPH TRAVERSAL",
    "",
    "  Process current node, recurse on children.",
    "",
    "  int treeSum(TreeNode node) {",
    "      if (node == null) return 0;            // base case",
    "      return node.val + treeSum(node.left) + treeSum(node.right);",
    "  }",
    "",
    "PATTERN 5: TAIL RECURSION (loop in recursion form)",
    "",
    "  Recursive call is the LAST thing the function does.",
    "  Some languages optimise this to a loop (no stack growth) — Java does NOT.",
    "",
    "  int factorialTail(int n, int acc) {",
    "      if (n <= 1) return acc;",
    "      return factorialTail(n - 1, n * acc);  // last operation",
    "  }",
    "  // Initial call: factorialTail(5, 1)",
    "```",
    "",
    "---",
    "",
    "## When NOT to Use Recursion",
    "",
    "```",
    "1. STACK OVERFLOW RISK:",
    "   Java default stack size: ~1MB ≈ 10,000 frames",
    "   Don't recurse deeper than this. For depth >10K, use iteration.",
    "",
    "   Bad: factorial(100000) → StackOverflowError",
    "   Fix: convert to a for loop accumulating result.",
    "",
    "2. EXPONENTIAL TIME WITHOUT MEMOISATION:",
    "",
    "   int fib(int n) {",
    "       if (n <= 1) return n;",
    "       return fib(n-1) + fib(n-2);     // O(2^n) time!",
    "   }",
    "",
    "   fib(40) takes seconds. fib(50) hours. fib(60) impossible.",
    "   Fix: memoise (cache results) or convert to bottom-up DP.",
    "",
    "3. WHEN ITERATION IS CLEARER:",
    "   sumOfArray with for loop: 3 lines, obvious.",
    "   sumOfArray with recursion: 4 lines, requires base-case thinking.",
    "   Don't be cute — use the simpler form.",
    "",
    "4. PERFORMANCE-CRITICAL CODE:",
    "   Function call overhead: each call has push/pop/jump = slow.",
    "   Iteration is faster for the same algorithm in CPU-bound code.",
    "```",
    "",
    "---",
    "",
    "## Recursion vs Iteration — Conversion",
    "",
    "Most recursive functions can be rewritten as loops with an explicit stack.",
    "",
    "```java",
    "// Recursive in-order BST traversal",
    "void inOrder(TreeNode node) {",
    "    if (node == null) return;",
    "    inOrder(node.left);",
    "    print(node.val);",
    "    inOrder(node.right);",
    "}",
    "",
    "// Iterative version using explicit Deque as stack",
    "void inOrderIterative(TreeNode root) {",
    "    Deque<TreeNode> stack = new ArrayDeque<>();",
    "    TreeNode current = root;",
    "    while (current != null || !stack.isEmpty()) {",
    "        while (current != null) {",
    "            stack.push(current);",
    "            current = current.left;",
    "        }",
    "        current = stack.pop();",
    "        print(current.val);",
    "        current = current.right;",
    "    }",
    "}",
    "// Same O(n) time, but no stack overflow risk for deep trees.",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "RECURSION",
    "|",
    "+-- ANATOMY",
    "|   +-- Base case (stops)",
    "|   +-- Recursive case (smaller input)",
    "|   +-- Progress toward base",
    "|",
    "+-- THINKING APPROACH",
    "|   +-- TRUST the recursion",
    "|   +-- Don't trace manually",
    "|   +-- 'If it works for n-1, does it work for n?'",
    "|",
    "+-- PATTERNS",
    "|   +-- Reduce-and-combine (sum, fib)",
    "|   +-- Divide-and-conquer (mergesort)",
    "|   +-- Backtracking (permutations)",
    "|   +-- Tree/graph traversal",
    "|   +-- Tail recursion",
    "|",
    "+-- PITFALLS",
    "|   +-- Missing base case → stack overflow",
    "|   +-- Not getting smaller → stack overflow",
    "|   +-- Naive fib = O(2^n) without memoisation",
    "|",
    "+-- COMPLEXITY",
    "|   +-- Time: count total calls",
    "|   +-- Space: max stack depth",
    "|   +-- Branching factor matters!",
    "|",
    "+-- ITERATION CONVERSION",
    "    +-- Replace stack frames with explicit Deque",
    "    +-- Avoids StackOverflowError",
    "    +-- Often faster (less overhead)",
    "```",
    "",
    "---",
    "",
    "## How Recursion Connects to Other Topics",
    "",
    "- **Trees & Graphs**: nearly all tree/graph algorithms are naturally recursive",
    "- **Divide-and-conquer**: mergesort, quicksort, binary search",
    "- **Dynamic Programming**: top-down DP = recursion + memoisation",
    "- **Backtracking**: solving puzzles, generating combinations, N-queens",
    "- **Functional Programming**: recursion replaces loops in pure FP languages",
    "",
    "---",
    "",
    "## Common Beginner Mistakes",
    "",
    "1. **No base case** — function never returns, stack blows up",
    "2. **Base case never reached** — recursion not making input smaller",
    "3. **Trying to trace recursion manually** — works for depth 3, impossible for depth 20",
    "4. **Forgetting return statement** — `factorial(n-1)` instead of `return n * factorial(n-1)`",
    "5. **Recomputing same subproblem** — naive fib is O(2^n); memoise for O(n)",
    "6. **Stack overflow on deep input** — recursion depth > ~10K crashes Java",
    "7. **Modifying shared state** — backtracking must restore state on return",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **5 Simple Steps to Solve Recursion** by Reducible: https://www.youtube.com/watch?v=ngCos392W4w",
    "- **Recursion Visualised** by Computerphile: https://www.youtube.com/watch?v=Mv9NEXX1VHc",
    "",
    "### Articles",
    "- **The Little Book of Recursion** (free): https://inventwithpython.com/recursion/",
    "- **Visualising Recursion** (interactive): https://recursion.vercel.app/",
])

RECURSION_Q = [
    {"id":"rec-q1","type":"mcq","prompt":"What MUST every recursive function have?",
     "choices":["A loop","A base case (stopping condition) AND a recursive case that moves toward the base","A return type of int","An array parameter"],
     "answerIndex":1,"explanation":"Both are required: 1) base case to stop recursion (otherwise infinite calls = StackOverflowError), 2) recursive case making input smaller (otherwise same input → infinite recursion). Missing either guarantees a crash. Always write the base case FIRST when implementing.","tags":["recursion","fundamentals","base-case"]},
    {"id":"rec-q2","type":"mcq","prompt":"What is the time complexity of naive recursive Fibonacci: fib(n) = fib(n-1) + fib(n-2)?",
     "choices":["O(n)","O(2^n) — each call branches into 2 calls, building an exponential call tree","O(n log n)","O(n^2)"],
     "answerIndex":1,"explanation":"Each call makes 2 calls. Tree depth n. Total nodes ≈ 2^n. Same subproblems computed many times: fib(40) requires ~10^9 calls. fib(45) takes ~30 seconds. Memoisation reduces this to O(n) by caching each fib(k) once.","tags":["fibonacci","complexity","exponential"]},
    {"id":"rec-q3","type":"mcq","prompt":"Why does this code cause StackOverflowError?\n\nint f(int n) { return f(n - 1) + 1; }",
     "choices":["Too much memory","No base case — recursion never stops, infinitely deep call stack",
      "Compilation error","Wrong return type"],
     "answerIndex":1,"explanation":"Missing base case. Each call adds a stack frame. After ~10K frames (Java default 1MB stack), JVM throws StackOverflowError. Fix: add 'if (n == 0) return 0;' or similar before the recursive call. ALWAYS write the base case FIRST.","tags":["stack-overflow","base-case"]},
    {"id":"rec-q4","type":"mcq","prompt":"What is the SPACE complexity of naive recursive Fibonacci?",
     "choices":["O(2^n) like time","O(n) — at any moment, only one branch is being computed; max stack depth is n. Space is reclaimed when each call returns.","O(1)","O(log n)"],
     "answerIndex":1,"explanation":"Time: O(2^n) due to recursive branching. Space: only one path through the recursion tree exists in memory at a time. After fib(n-1) returns, its frames are freed before fib(n-2) starts. Max simultaneous depth = n. Subtle but important: time and space differ.","tags":["fibonacci","space-complexity"]},
    {"id":"rec-q5","type":"mcq","prompt":"Tail recursion is when:",
     "choices":["The function recurses many times","The recursive call is the LAST operation in the function — no further work after the call returns","The function is in a loop","The function calls itself once"],
     "answerIndex":1,"explanation":"Tail recursion: 'return f(...)' with no operations after. Some languages (Scala, Scheme, JS strict mode) optimise this to a loop, eliminating stack growth (TCO). Java does NOT optimise tail calls — same stack overflow risk. Convert to iteration manually.","tags":["tail-recursion","optimisation"]},
    {"id":"rec-q6","type":"codeOutput","prompt":"What does this print?\n\nvoid f(int n) {\n    if (n == 0) return;\n    System.out.print(n + \" \");\n    f(n - 1);\n    System.out.print(n + \" \");\n}\nf(3);",
     "code":"f(3) prints n, calls f(2), then prints n again",
     "choices":["3 2 1 1 2 3","3 2 1 0 1 2 3","3 3 2 2 1 1","3 2 1"],
     "answerIndex":0,"explanation":"Pre-order print: 3 2 1 (going down). Then call returns: each prints n again on the way back: 1 2 3. Total: '3 2 1 1 2 3'. The pattern of work-before-call vs work-after-call is fundamental to tree traversals (pre/in/post-order).","tags":["recursion","trace","output"]},
    {"id":"rec-q7","type":"mcq","prompt":"Memoisation transforms naive Fibonacci from O(2^n) to:",
     "choices":["O(n^2)","O(n) time, O(n) space — each fib(k) computed exactly once and cached","O(log n)","O(1)"],
     "answerIndex":1,"explanation":"Naive fib(n) recomputes fib(5) hundreds of times in fib(40). Memoised: store result on first computation, return cached on subsequent. Each fib(k) for k=0..n computed once = O(n) calls. Cache + call stack = O(n) space. Trade space for time, classic dynamic programming.","tags":["memoisation","fibonacci","dp"]},
    {"id":"rec-q8","type":"mcq","prompt":"What is the maximum recursion depth typically supported in Java?",
     "choices":["1 million","About 10,000-20,000 frames (default stack ~1MB)","Unlimited","100"],
     "answerIndex":1,"explanation":"Default JVM thread stack size is 512KB-1MB. Each frame uses 50-200 bytes (locals, return addr). Max depth ~10K. Configurable: -Xss2m (2MB stack). For deeper recursion: convert to iteration with explicit Deque<>. Tree depth is rarely an issue; linked list/array recursion can blow up.","tags":["stack","limits","java"]},
    {"id":"rec-q9","type":"mcq","prompt":"Backtracking pattern — what's the key step that distinguishes it from regular recursion?",
     "choices":["Multiple return values","UNDOING the choice after the recursive call returns — exploring all paths by trying each, then reverting state",
      "Using a stack","No base case"],
     "answerIndex":1,"explanation":"Backtracking: try a choice, recurse, undo. The undo step (backtrack) lets the algorithm explore other paths. Example: N-queens places queen, recurses, removes queen if solution not found. Permutations swap, recurse, swap back. Without undo, you'd corrupt shared state.","tags":["backtracking","pattern"]},
    {"id":"rec-q10","type":"mcq","prompt":"Trust the recursion principle: when implementing 'reverse a linked list recursively', what should you assume?",
     "choices":["Nothing — trace through every call","Assume the recursive call CORRECTLY reverses the rest of the list, then just attach the current node correctly. Don't trace mentally.","The function is iterative","All bases cases are wrong"],
     "answerIndex":1,"explanation":"The 'leap of faith' is essential. reverse(head): assume reverse(head.next) returns the reversed sublist correctly. Then your only job: attach 'head' as the new tail. This thinking pattern works for ALL tree/list recursion. Don't try to mentally simulate deep recursion — trust the smaller case works.","tags":["recursion","mental-model"]},
    {"id":"rec-q11","type":"mcq","prompt":"Why is iteration often faster than recursion for the same algorithm?",
     "choices":["Iteration uses less memory always","Function call overhead: each recursive call requires push/pop of stack frame, parameter passing, return jumps. Iteration avoids this in a tight loop.","Compilers can't optimise recursion","Recursion is asymptotically slower"],
     "answerIndex":1,"explanation":"Iteration in a tight loop: a few CPU instructions per iteration. Recursion: parameter packaging, stack push, jump, return jump, stack pop = 10x more overhead per 'step'. Same Big-O, but constant factor differs. For performance-critical code, prefer iteration. For clarity, recursion.","tags":["performance","iteration"]},
    {"id":"rec-q12","type":"mcq","prompt":"What's wrong with this 'sum array' function?\n\nint sum(int[] arr, int i) {\n    if (i == arr.length) return 0;\n    sum(arr, i + 1);\n    return arr[i];\n}",
     "choices":["Missing base case","Recursive call result is discarded — should be 'return arr[i] + sum(arr, i+1)'",
      "Index out of bounds","Stack overflow"],
     "answerIndex":1,"explanation":"The function calls sum recursively but THROWS AWAY the result. Each call returns just arr[i], not the sum. To fix: 'return arr[i] + sum(arr, i+1);'. Common bug: forgetting to combine the recursive result with current value.","tags":["recursion","bug"]},
    {"id":"rec-q13","type":"mcq","prompt":"For a balanced binary tree with n nodes, recursive traversal complexity is:",
     "choices":["O(log n) time, O(n) space","O(n) time (visit each node once), O(log n) space (tree height = call stack depth)",
      "O(n^2)","O(2^n)"],
     "answerIndex":1,"explanation":"Tree traversal: each node visited once → O(n) time. Recursion depth = max path from root to leaf = tree height. Balanced tree: height log n. Skewed tree (degenerate): height n. So balanced O(log n) space, unbalanced O(n) space. This is why we balance trees!","tags":["tree","traversal","complexity"]},
    {"id":"rec-q14","type":"mcq","prompt":"How does the 'pre-order' vs 'post-order' tree traversal differ in code?",
     "choices":["Different tree types","WHEN you process the current node: pre-order = process THEN recurse; post-order = recurse THEN process. Order changes which nodes get processed first.",
      "Pre-order is iterative","No difference"],
     "answerIndex":1,"explanation":"Pre-order: process node, recurse left, recurse right. Visits root before children. Used for tree COPY. Post-order: recurse left, recurse right, process node. Visits children before root. Used for tree DELETION (delete children first). In-order (BST): recurse left, process, recurse right. Yields sorted order for BST.","tags":["tree","traversal","ordering"]},
    {"id":"rec-q15","type":"mcq","prompt":"What does this print?\n\nint f(int n) {\n    if (n == 0) return 0;\n    return n + f(n - 1);\n}\nSystem.out.println(f(5));",
     "choices":["5","15 — sum 5+4+3+2+1+0","10","25"],
     "answerIndex":1,"explanation":"f(5)=5+f(4)=5+4+f(3)=5+4+3+f(2)=...=5+4+3+2+1+0=15. Classic 'sum 1 to n' via recursion. Iterative: n*(n+1)/2 = 5*6/2 = 15. Same answer, recursive form vs closed-form. Recognise the pattern: each call adds n and reduces.","tags":["recursion","trace","sum"]},
    {"id":"rec-q16","type":"multi","prompt":"Which patterns naturally use recursion? (Select all)",
     "choices":["Tree traversal (pre/in/post-order)","Divide and conquer (mergesort)","Backtracking (permutations, N-queens)","Iterating a fixed-size array"],
     "answerIndexes":[0,1,2],"explanation":"Trees: hierarchical structure matches recursion perfectly. Divide-and-conquer: split into smaller similar subproblems. Backtracking: try-recurse-undo paradigm. Fixed-size array iteration: for-loop is more idiomatic and faster — recursion adds unnecessary overhead.","tags":["patterns","when-to-use"]},
    {"id":"rec-q17","type":"mcq","prompt":"Recursion vs Stack-based iteration — when is iteration mandatory?",
     "choices":["Always","When recursion depth might exceed JVM stack limit (~10K frames). E.g., processing a 1M-node linked list recursively will StackOverflowError; iteration handles any size.",
      "When recursion is slow","Never"],
     "answerIndex":1,"explanation":"For deep linear recursion (linked list of N=10⁶ nodes), recursion will crash. Convert to iteration with explicit Deque<Node>. Java has no tail-call optimisation. Trees with bounded depth (height < 30 for balanced tree of 1B nodes) are safe with recursion.","tags":["stack-overflow","iteration","conversion"]},
    {"id":"rec-q18","type":"mcq","prompt":"What is mutual recursion?",
     "choices":["A function calling itself twice","Two or more functions that call each other — a calls b, b calls a, eventually one hits a base case",
      "Recursion across threads","Recursion in classes"],
     "answerIndex":1,"explanation":"Mutual recursion: isEven(n) returns isOdd(n-1); isOdd(n) returns isEven(n-1). They alternate calls. Less common than self-recursion but useful for state-machine-like problems. Same StackOverflowError risk if no base case.","tags":["mutual-recursion"]},
    {"id":"rec-q19","type":"mcq","prompt":"Top-down DP (memoisation) vs bottom-up DP (tabulation) for Fibonacci — both achieve O(n) time. Difference?",
     "choices":["No difference","Top-down: recursive with cache, intuitive ('what does fib(n) need?'). Bottom-up: iterative loop building up from fib(0). Same complexity but bottom-up has no recursion overhead and no stack overflow risk.",
      "Bottom-up is asymptotically faster","Top-down uses more time"],
     "answerIndex":1,"explanation":"Top-down (recursion + memo): natural to write, follows problem definition. Risk: stack overflow for deep n. Bottom-up (iteration): build dp[0], dp[1], ..., dp[n] in a loop. No recursion, faster constants, no stack issue. Most production DP code is bottom-up.","tags":["dp","memoisation","tabulation"]},
    {"id":"rec-q20","type":"mcq","prompt":"In backtracking, what's the consequence of FORGETTING to undo a choice after the recursive call?",
     "choices":["Nothing — recursion handles it","State leakage: subsequent recursive paths see corrupted state, generating wrong/duplicate results. The undo (e.g., swap back, remove from set) is essential.",
      "Compilation error","Faster execution"],
     "answerIndex":1,"explanation":"Backtracking explores ONE path at a time. After exploring with choice X, you must restore state so you can try choice Y from the SAME starting state. Forgetting undo: 'add x to set, recurse, [forget to remove x]' → next iteration sees x already in set. Always undo immediately after recursion returns.","tags":["backtracking","state-management"]},
]

RECURSION_FC = [
    {"id":"rec-fc1","front":"Recursion checklist","back":"1) Base case (when to stop) — write FIRST. 2) Recursive case (smaller input). 3) Verify each call moves toward base. Missing any = StackOverflowError. Trust the recursion: assume recursive call works for smaller input.","tags":["recursion","fundamentals"]},
    {"id":"rec-fc2","front":"Time vs space for recursion","back":"Time: count total recursive calls. Branching factor matters: fib has 2 children = O(2^n). Linear recursion (factorial, sum) = O(n). Space: max stack depth at any moment. Linear recursion: O(n). Tree traversal: O(height) = O(log n) balanced, O(n) skewed.","tags":["complexity"]},
    {"id":"rec-fc3","front":"Recursion patterns","back":"Reduce-and-combine: solve smaller, combine with current (factorial, sum). Divide-and-conquer: split halves, recurse each, merge (mergesort). Backtracking: try, recurse, undo (permute, N-queens). Tree traversal: process node + recurse children.","tags":["patterns"]},
    {"id":"rec-fc4","front":"When to convert recursion to iteration","back":"1) Depth >10K (Java stack limit). 2) Performance-critical (function call overhead). 3) When iteration is genuinely clearer. Use explicit Deque<> as stack for tree/graph algorithms. for-loop replaces simple linear recursion.","tags":["iteration","optimisation"]},
    {"id":"rec-fc5","front":"Memoisation transformation","back":"Add Map<Input,Output> cache. On entry: if cache contains input, return cached value. On exit: store result before returning. Naive fib O(2^n) → memoised O(n). Each subproblem solved once. Trade space for time.","tags":["memoisation","dp"]},
    {"id":"rec-fc6","front":"Backtracking template","back":"void solve(state) { if (isComplete(state)) record(); for (choice : choices) { make(choice); solve(state); undo(choice); } }. The undo is critical — forgetting it leaks state across paths.","tags":["backtracking","template"]},
    {"id":"rec-fc7","front":"Tree traversal orders","back":"Pre-order: process, left, right (root first — for tree COPY). In-order: left, process, right (BST in sorted order). Post-order: left, right, process (children first — for tree DELETION). DFS pattern in all three.","tags":["tree","traversal"]},
    {"id":"rec-fc8","front":"Trust the recursion mantra","back":"When writing recursive function: assume the recursive call CORRECTLY solves the smaller problem. Your only job: combine its result with current data to solve current case. Don't mentally trace deep — write base + recursive case clearly.","tags":["mental-model","problem-solving"]},
]

RECURSION_PROJ = {
    "brief": "You're given a deeply nested JSON object representing a company org chart (employees with direct reports). Design recursive functions to: 1) Count total employees in any sub-tree. 2) Find the highest-paid employee at any level. 3) Print the chart with proper indentation (nested visualisation). 4) Find all leaves (employees with no reports). For each: identify base case, recursive case, complexity.",
    "checklist": [
        {"id":"r1","text":"countEmployees: base = 1 (just current employee). Recursive: 1 + sum of countEmployees(report). Time: O(n) where n=total employees.","weight":20},
        {"id":"r2","text":"highestPaid: base = current employee (no reports). Recursive: max(current.salary, max of recursive results from each report). Time: O(n).","weight":20},
        {"id":"r3","text":"printChart: pre-order traversal with depth parameter. Print '\\t'.repeat(depth) + name. Recurse on each report with depth+1. Time: O(n).","weight":20},
        {"id":"r4","text":"findLeaves: base = if reports empty, return [current]. Recursive: flatten recursive results from all reports. Time: O(n).","weight":20},
        {"id":"r5","text":"Convert to iteration with explicit Deque<Employee> for org charts that might exceed stack limit (depth >10K levels).","weight":20},
    ],
    "hints": [
        "All four functions follow the same pattern: process current employee, recurse on each direct report, combine results. The differences are in HOW you combine.",
        "For unbalanced org charts (some reports have many sub-reports), space complexity = O(max depth) for recursion stack. Average org chart is shallow (<10 levels) so safe.",
        "Iteration version: use Deque<Employee> as stack. Push root. While not empty: pop, process, push each report. Result built in result list as you go.",
    ]
}

write("recursion-mental-model.json", {
    "id": "recursion-mental-model",
    "unit": 1,
    "order": 2,
    "title": "Recursion Mental Model",
    "summary": "Trust-the-recursion thinking, base/recursive cases, common patterns, and converting recursion to iteration.",
    "prereqs": ["time-space-complexity"],
    "guide": RECURSION_GUIDE,
    "questions": RECURSION_Q,
    "flashcards": RECURSION_FC,
    "project": RECURSION_PROJ,
})

print("\n=== Foundations Batch 1 Complete ===")
print("Written:")
print("  - foundations/time-space-complexity.json")
print("  - foundations/recursion-mental-model.json")
print("")
print("💡 Next: run foundations_batch2.py for memory/pointers/SQL/embedded-DBs")

