"""
Foundations Batch 2a: Systems mental models
  - memory-stack-heap (order 3)
  - pointers-references (order 4)
Run: python3 scripts/foundations_batch2a.py
"""
import json
from pathlib import Path

BASE = Path(__file__).parent.parent / "src/content/topics/foundations"
BASE.mkdir(parents=True, exist_ok=True)


def write(filename, data):
    out = BASE / filename
    if out.exists():
        existing = json.loads(out.read_text())
        if len(existing.get("questions", [])) >= 20:
            print(f"  SKIP {filename} (already complete)")
            return
    out.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    print(f"  WROTE {filename}: guide={len(data['guide'])} q={len(data['questions'])} fc={len(data['flashcards'])}")


# ── MEMORY: STACK vs HEAP ────────────────────────────────────────────────────

MEMORY_GUIDE = "\n".join([
    "# Memory — Stack vs Heap",
    "",
    "## Why Should I Care About Memory?",
    "",
    "When your code runs, every variable lives somewhere in RAM. Whether it lives on",
    "the **stack** or the **heap** affects: how fast it's accessed, when it's freed,",
    "whether you can have memory leaks, and what happens when you pass it to a function.",
    "",
    "Understanding stack vs heap explains:",
    "- Why local variables disappear when a function returns",
    "- Why `new SomeObject()` survives across function calls",
    "- Why infinite recursion crashes with StackOverflowError",
    "- Why allocating millions of objects causes OutOfMemoryError",
    "- What the JVM garbage collector actually does",
    "",
    "---",
    "",
    "## The Big Picture: Two Regions of Memory",
    "",
    "```",
    "  ┌─────────────────────────────────────┐",
    "  │           HIGH ADDRESSES            │",
    "  │  ┌───────────────────────────────┐  │",
    "  │  │            STACK              │  │ ← grows DOWNWARD",
    "  │  │  function call frames here    │  │",
    "  │  │  fast, automatic, small       │  │",
    "  │  ├───────────────────────────────┤  │",
    "  │  │           ↓ (free)            │  │",
    "  │  │           ↑ (free)            │  │",
    "  │  ├───────────────────────────────┤  │",
    "  │  │             HEAP              │  │ ← grows UPWARD",
    "  │  │  objects, arrays, dynamic     │  │",
    "  │  │  large, slower, GC-managed    │  │",
    "  │  ├───────────────────────────────┤  │",
    "  │  │  STATIC / METASPACE           │  │ ← class data, constants",
    "  │  ├───────────────────────────────┤  │",
    "  │  │  CODE                         │  │ ← compiled bytecode",
    "  │  └───────────────────────────────┘  │",
    "  │           LOW ADDRESSES             │",
    "  └─────────────────────────────────────┘",
    "```",
    "",
    "---",
    "",
    "## The Stack — Fast, Automatic, Small",
    "",
    "```",
    "WHAT LIVES HERE:",
    "  - Function parameters",
    "  - Local variables (primitives in Java/C, pointers in C)",
    "  - Return addresses (where to go when function ends)",
    "",
    "HOW IT WORKS:",
    "  Each function call allocates a 'stack frame' on top.",
    "  Function returns: frame is popped (instantly freed).",
    "  No need to manually free — automatic.",
    "",
    "CHARACTERISTICS:",
    "  Speed:        Very fast (just move stack pointer)",
    "  Size:         Small (~1MB default per thread in Java)",
    "  Lifetime:     Tied to function call — vanishes on return",
    "  Allocation:   Always succeeds (until size limit)",
    "  Errors:       StackOverflowError when too deep",
    "",
    "  void example() {",
    "      int x = 10;        // x is on the stack",
    "      int y = 20;        // y is on the stack",
    "      add(x, y);         // new frame for add() pushed",
    "  }                       // frame popped: x, y are gone",
    "```",
    "",
    "**Stack frame in detail (for `factorial(3)` calling `factorial(2)`):**",
    "",
    "```",
    "  ┌──────────────────────────────┐  ← top of stack",
    "  │ factorial(2) frame:          │",
    "  │   n = 2                      │",
    "  │   return addr = ...          │",
    "  ├──────────────────────────────┤",
    "  │ factorial(3) frame:          │",
    "  │   n = 3                      │",
    "  │   return addr = main()       │",
    "  ├──────────────────────────────┤",
    "  │ main() frame:                │",
    "  │   args                       │",
    "  └──────────────────────────────┘  ← bottom of stack",
    "",
    "When factorial(2) returns, its frame is popped instantly.",
    "Control returns to factorial(3) at the saved return address.",
    "```",
    "",
    "---",
    "",
    "## The Heap — Big, Dynamic, GC-Managed",
    "",
    "```",
    "WHAT LIVES HERE:",
    "  - Objects (everything created with `new` in Java)",
    "  - Arrays (Java/C# arrays are objects)",
    "  - Strings",
    "  - Anything that needs to OUTLIVE the function that created it",
    "",
    "HOW IT WORKS:",
    "  `new Foo()` allocates space in heap, returns a reference (address).",
    "  The reference is a small pointer; the actual object lives in heap.",
    "  Multiple references can point to the same heap object.",
    "  When no references exist anymore, GC reclaims the memory.",
    "",
    "CHARACTERISTICS:",
    "  Speed:        Slower (allocator finds space, GC tracks)",
    "  Size:         Large (configurable, GBs)",
    "  Lifetime:     Until garbage collected (no live references)",
    "  Allocation:   Can fail (OutOfMemoryError when full)",
    "  Errors:       OOM, memory leaks (refs that should be released)",
    "",
    "  void example() {",
    "      // x is on stack (reference), object is on heap",
    "      MyClass x = new MyClass();",
    "      doStuff(x);",
    "  }",
    "  // x (reference) is gone, but object on heap may still",
    "  // exist if doStuff() saved a reference somewhere.",
    "```",
    "",
    "**Visualising stack and heap together:**",
    "",
    "```java",
    "void foo() {",
    "    int n = 42;",
    "    String s = \"hello\";",
    "    int[] arr = new int[]{1, 2, 3};",
    "}",
    "```",
    "",
    "```",
    "  STACK (foo's frame)            HEAP",
    "  ┌────────────────┐             ┌───────────────────┐",
    "  │ n = 42          │             │ String 'hello'    │ ← s points here",
    "  │ s ──────────────┼────────────►│                   │",
    "  │ arr ────────────┼────┐        ├───────────────────┤",
    "  │ return addr     │    │        │ int[3] {1,2,3}    │ ← arr points here",
    "  └────────────────┘    └───────►│                   │",
    "                                  └───────────────────┘",
    "",
    "  After foo() returns:",
    "  - Stack frame is popped (n, s, arr — all gone)",
    "  - But HEAP objects may still exist (if other refs held)",
    "  - Otherwise, garbage collector reclaims them later",
    "```",
    "",
    "---",
    "",
    "## Java: Primitives vs References",
    "",
    "```",
    "PRIMITIVES (int, long, double, char, boolean, byte, short, float):",
    "  Stored DIRECTLY in stack (or in object fields on heap).",
    "  Pass-by-value: a copy is made when passed to functions.",
    "",
    "REFERENCE TYPES (everything else: String, Object, arrays, your classes):",
    "  Reference (address) is on stack, ACTUAL OBJECT is on heap.",
    "  Pass-by-value: the REFERENCE value is copied.",
    "  Both copies point to the SAME heap object.",
    "  Modifying the object's fields is visible to caller.",
    "  Re-assigning the reference does NOT affect caller.",
    "",
    "Example:",
    "",
    "  void modifyPrimitive(int x) { x = 99; }       // affects nothing",
    "  void modifyList(List<Integer> list) { list.add(99); }  // visible!",
    "  void reassignList(List<Integer> list) {",
    "      list = new ArrayList<>();   // local re-bind, caller unaffected",
    "  }",
    "",
    "  int n = 10;",
    "  modifyPrimitive(n);           // n still 10",
    "",
    "  List<Integer> l = new ArrayList<>();",
    "  modifyList(l);                // l now contains 99",
    "  reassignList(l);              // l unchanged, still contains 99",
    "",
    "Common confusion: Java is ALWAYS pass-by-value.",
    "  For references, the value being passed is the address.",
    "  This explains the 'modifies object but not the variable' behaviour.",
    "```",
    "",
    "---",
    "",
    "## Garbage Collection (Java/JVM)",
    "",
    "```",
    "Heap memory must be RECLAIMED when objects are no longer used.",
    "C/C++: programmer manually free()s — bug-prone.",
    "Java/Go/Python/JS: garbage collector does it automatically.",
    "",
    "GC ROOTS:",
    "  Starting points where 'live' references begin:",
    "  - Local variables (stack frames currently active)",
    "  - Static fields (class-level)",
    "  - JNI references (native code)",
    "  - Thread-local storage",
    "",
    "MARK-AND-SWEEP (simplified):",
    "  1. MARK: starting from GC roots, follow every reference and mark all",
    "          reachable objects as 'live'.",
    "  2. SWEEP: any heap object NOT marked is unreachable — reclaim its memory.",
    "",
    "  Roots                              Heap",
    "    │                                  │",
    "    ├─► Object A ──► Object B          │",
    "    │                  │               │",
    "    │                  └─► Object C    │",
    "    │                                  │",
    "    └─► Object D                       │  Object X (no ref → garbage)",
    "                                       │  Object Y (no ref → garbage)",
    "    Live: A, B, C, D",
    "    Garbage: X, Y → reclaimed",
    "",
    "GENERATIONAL GC (modern JVMs):",
    "  Most objects die young (request handlers, temp vars).",
    "  Heap split into 'young' (Eden + Survivor) and 'old' (Tenured) generations.",
    "  Young GC: frequent, fast (only scans young region).",
    "  Old GC (full GC): rare, slower (scans entire heap).",
    "  Modern collectors: G1, ZGC, Shenandoah — low-pause, parallel.",
    "```",
    "",
    "---",
    "",
    "## Memory Leaks in GC Languages",
    "",
    "GC doesn't prevent ALL leaks — only frees objects with NO references.",
    "If you accidentally hold a reference, the object stays forever.",
    "",
    "```java",
    "// COMMON LEAKS:",
    "",
    "// 1. Static collection grows forever",
    "static Map<String, User> CACHE = new HashMap<>();",
    "// Adding to CACHE without ever removing → leak",
    "// Fix: use a bounded cache (LinkedHashMap with removeEldestEntry, or Caffeine)",
    "",
    "// 2. Listener not removed",
    "button.addClickListener(this::handleClick);",
    "// Component destroyed but listener remains → leaks 'this'",
    "// Fix: removeClickListener in cleanup",
    "",
    "// 3. ThreadLocal not removed",
    "ThreadLocal<BigData> tl = new ThreadLocal<>();",
    "tl.set(new BigData());",
    "// In a thread pool, threads live forever → BigData held forever",
    "// Fix: tl.remove() in finally block",
    "",
    "// 4. Inner class holding outer reference",
    "class Outer {",
    "    void start() {",
    "        new Thread(() -> {",
    "            // anonymous Runnable holds implicit ref to Outer instance",
    "            doSomething();",
    "        }).start();",
    "    }",
    "}",
    "// Outer can't be GC'd until thread ends",
    "// Fix: use static lambdas or pass needed fields explicitly",
    "```",
    "",
    "**Tools to find leaks:**",
    "- VisualVM, JProfiler, YourKit (Java)",
    "- Heap dumps: `jmap -dump:live,file=heap.hprof <pid>`",
    "- Eclipse MAT (Memory Analyzer Tool) — analyse the heap dump",
    "",
    "---",
    "",
    "## Stack Overflow vs OutOfMemory",
    "",
    "```",
    "STACK OVERFLOW (StackOverflowError):",
    "  Cause: too many nested function calls (deep recursion)",
    "  Stack depth exceeds limit (~10K frames in Java default)",
    "  Fix: convert recursion to iteration with explicit Deque<>",
    "       OR increase stack size: java -Xss2m",
    "",
    "OUT OF MEMORY (OutOfMemoryError):",
    "  Cause: heap is full, can't allocate new objects",
    "  Either: legitimate large data set, OR memory leak",
    "  Fix:",
    "    - Increase heap: java -Xmx4g (max heap 4GB)",
    "    - Find leak with profiler",
    "    - Stream/page through data instead of loading all",
    "",
    "  Different errors. Different causes. Different fixes.",
    "```",
    "",
    "---",
    "",
    "## C/C++: Manual Memory Management",
    "",
    "Java/Python/Go developers don't manage memory manually, but you'll see this in legacy code:",
    "",
    "```c",
    "void leakExample() {",
    "    int* arr = malloc(100 * sizeof(int));   // allocate on heap",
    "    // ... use arr ...",
    "    // OOPS: forgot to free(arr) → memory leak",
    "}",
    "",
    "void correctExample() {",
    "    int* arr = malloc(100 * sizeof(int));",
    "    // ... use arr ...",
    "    free(arr);   // manually release heap memory",
    "}",
    "",
    "void useAfterFree() {",
    "    int* arr = malloc(100 * sizeof(int));",
    "    free(arr);",
    "    arr[0] = 42;   // BUG! using freed memory — undefined behaviour",
    "}",
    "",
    "void doubleFree() {",
    "    int* arr = malloc(100 * sizeof(int));",
    "    free(arr);",
    "    free(arr);   // BUG! freeing twice — heap corruption",
    "}",
    "",
    "// Modern C++ uses RAII (smart pointers) to avoid these bugs:",
    "std::unique_ptr<int[]> arr(new int[100]);",
    "// auto-freed when arr goes out of scope, no manual free needed",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "MEMORY",
    "|",
    "+-- STACK",
    "|   +-- Function frames",
    "|   +-- Locals + parameters",
    "|   +-- Fast (~ns)",
    "|   +-- Auto-freed on return",
    "|   +-- Small (1MB default)",
    "|   +-- StackOverflowError",
    "|",
    "+-- HEAP",
    "|   +-- Objects (new in Java)",
    "|   +-- Survives function returns",
    "|   +-- Slower (allocator + GC)",
    "|   +-- Large (GB)",
    "|   +-- OutOfMemoryError",
    "|",
    "+-- JAVA SPECIFICS",
    "|   +-- Primitives on stack",
    "|   +-- Objects on heap",
    "|   +-- References on stack point to heap",
    "|   +-- Pass-by-value (incl. references)",
    "|",
    "+-- GARBAGE COLLECTION",
    "|   +-- Mark live objects from GC roots",
    "|   +-- Sweep unmarked → garbage",
    "|   +-- Generational (young/old)",
    "|   +-- Modern: G1, ZGC, Shenandoah",
    "|",
    "+-- LEAKS DESPITE GC",
    "    +-- Static collections growing",
    "    +-- Unremoved listeners",
    "    +-- ThreadLocal in pools",
    "    +-- Inner class capturing outer",
    "```",
    "",
    "---",
    "",
    "## How Memory Connects to Other Topics",
    "",
    "- **Recursion**: each call uses stack — too deep = StackOverflowError",
    "- **Big-O**: space complexity = heap usage by your data structures",
    "- **JVM tuning**: `-Xmx` (max heap), `-Xss` (stack size), GC algorithm choice",
    "- **Performance**: cache locality (contiguous arrays beat linked lists)",
    "- **Concurrency**: heap is shared between threads, stack is per-thread",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **Stack vs Heap explained** by Jenny's Lectures: https://www.youtube.com/watch?v=ZTuRZuRi-mU",
    "- **Java Memory Model** by Java Brains: https://www.youtube.com/watch?v=UcoQqLbT_Wo",
    "",
    "### Articles",
    "- **JVM Memory Model**: https://www.baeldung.com/java-stack-heap",
    "- **Garbage Collection in Java**: https://www.oracle.com/technical-resources/articles/java/g1gc.html",
])

MEMORY_Q = [
    {"id":"mem-q1","type":"mcq","prompt":"What's the key difference between stack and heap memory?",
     "choices":["Stack is faster but smaller; heap is bigger but slower","Stack is for primitives only","Stack lives in CPU cache","No difference, both are RAM"],
     "answerIndex":0,"explanation":"Stack: fast (move pointer), small (1MB), auto-managed (frame popped on return), tied to function calls. Heap: slower (allocator + GC), large (GB), managed by GC, survives function returns. Stack for short-lived locals; heap for objects that must outlive the creator.","tags":["memory","stack","heap"]},
    {"id":"mem-q2","type":"mcq","prompt":"In Java, where do PRIMITIVE local variables (int, double, boolean) live?",
     "choices":["Heap","Stack — directly inside the function's stack frame","CPU registers only","Constant pool"],
     "answerIndex":1,"explanation":"Java primitives in local scope live on the stack inside the current frame. They have no object header. When the function returns, the frame is popped and primitives are gone. Compare to objects: 'Integer i' is a reference on stack pointing to an object on heap.","tags":["java","stack","primitives"]},
    {"id":"mem-q3","type":"mcq","prompt":"In Java, where does the OBJECT created by `new ArrayList<>()` live?",
     "choices":["Stack","Heap — the actual object always lives on heap. The variable holding the reference may be on stack (local var) or heap (field of another object).","Constant pool","Both stack and heap"],
     "answerIndex":1,"explanation":"In Java, ALL objects (anything created with new) live on the heap. The reference (pointer) might be on the stack if it's a local variable. So 'ArrayList<Integer> list = new ArrayList<>()': 'list' (reference) on stack, ArrayList object itself on heap.","tags":["java","heap","objects"]},
    {"id":"mem-q4","type":"mcq","prompt":"What causes a StackOverflowError in Java?",
     "choices":["Too many objects allocated","Stack memory full from too many nested function calls (deep recursion is the most common cause)","Heap fragmentation","Static fields too large"],
     "answerIndex":1,"explanation":"Each function call adds a stack frame. Default stack size is ~1MB. Frames use 50-200 bytes each, so ~10K frames fit. Infinite recursion or unbounded recursion exceeds this. Fix: convert to iteration with explicit Deque, or increase stack size with -Xss flag.","tags":["stack","errors"]},
    {"id":"mem-q5","type":"mcq","prompt":"What causes OutOfMemoryError in Java?",
     "choices":["Stack full","HEAP is full — either legitimate large data set or a memory leak preventing GC from reclaiming objects","Disk full","Network timeout"],
     "answerIndex":1,"explanation":"OOME = heap exhausted. Causes: 1) Genuinely too much data (load entire DB into memory) — fix: stream/paginate. 2) Memory leak — refs held to objects no longer needed (caches, listeners, ThreadLocal). Fix: profile with VisualVM, take heap dump, find leak.","tags":["heap","errors","oom"]},
    {"id":"mem-q6","type":"mcq","prompt":"What does 'Java is pass-by-value' mean for object references?",
     "choices":["Java creates a deep copy of objects","Java copies the REFERENCE (address) value. Both caller and callee point to the SAME object on heap. Mutating fields is visible; reassigning the local reference is NOT.","Java is pass-by-reference","References can't be passed"],
     "answerIndex":1,"explanation":"Java passes references by value. The address bits are copied. Both refs point to same heap object — so list.add() is seen by caller. But 'list = new ArrayList<>()' inside method just rebinds the LOCAL copy, caller unaffected. This nuance trips up beginners.","tags":["java","pass-by-value","references"]},
    {"id":"mem-q7","type":"codeOutput","prompt":"What does this print?\n\nvoid f(int x) { x = 99; }\nint n = 10;\nf(n);\nSystem.out.println(n);",
     "code":"primitive passed by value",
     "choices":["10 — primitives are copied; modifying x in f doesn't affect n","99","0","Compile error"],
     "answerIndex":0,"explanation":"Primitives are passed by value. f receives a COPY of n. Setting x=99 modifies only the local copy. n is unchanged. Output: 10. Same goes for any primitive type. Pass an array or object, and mutations to the object's contents WOULD be visible.","tags":["pass-by-value","primitives"]},
    {"id":"mem-q8","type":"codeOutput","prompt":"What does this print?\n\nvoid g(int[] arr) { arr[0] = 99; }\nint[] a = {10, 20};\ng(a);\nSystem.out.println(a[0]);",
     "code":"array element modification through reference",
     "choices":["10","99 — the reference points to same array on heap; modifying contents is visible","Compile error","null"],
     "answerIndex":1,"explanation":"Array is on heap. arr (in g) and a (in caller) both reference the same heap array. arr[0] = 99 modifies the heap object. Caller sees the change because it points to the same object. This is why mutating method parameters can have surprising effects.","tags":["pass-by-value","references","arrays"]},
    {"id":"mem-q9","type":"codeOutput","prompt":"What does this print?\n\nvoid h(int[] arr) { arr = new int[]{99, 100}; }\nint[] a = {10, 20};\nh(a);\nSystem.out.println(a[0]);",
     "code":"reassigning local reference does not affect caller",
     "choices":["99","10 — assigning to arr inside h rebinds the LOCAL parameter; caller's variable a still points to the original array","100","Error"],
     "answerIndex":1,"explanation":"Inside h, arr is a local copy of the reference. 'arr = new int[]{...}' rebinds the local arr to a new heap array. The caller's variable a is untouched. Caller still sees original array. Subtle but critical: only mutations through the reference affect caller.","tags":["pass-by-value","references"]},
    {"id":"mem-q10","type":"mcq","prompt":"What does the JVM Garbage Collector do?",
     "choices":["Frees stack memory","Identifies heap objects with NO live references (unreachable from GC roots) and reclaims their memory automatically","Compresses files","Compiles bytecode"],
     "answerIndex":1,"explanation":"GC tracks heap objects. Starting from GC roots (active locals, statics), it traces all reachable objects. Anything unreachable = garbage = memory reclaimed. You don't manually free. But you can still leak if you accidentally hold references (caches, listeners).","tags":["gc","jvm"]},
    {"id":"mem-q11","type":"mcq","prompt":"Which is a common memory leak in Java despite garbage collection?",
     "choices":["Adding to a static Map without ever removing entries — references stay forever, GC can't reclaim","All allocations leak","Recursion always leaks","Lambdas always leak"],
     "answerIndex":0,"explanation":"GC frees objects with NO references. A static Map<String, User> that grows forever holds references to all User objects forever. They can't be GC'd. Fix: bounded cache (LinkedHashMap removeEldestEntry, Caffeine, Guava). Other leaks: unremoved listeners, ThreadLocal in pools.","tags":["leaks","static","cache"]},
    {"id":"mem-q12","type":"mcq","prompt":"What are GC roots?",
     "choices":["The heap itself","Starting points the GC uses to trace live references: active stack frames, static fields, JNI refs, thread-local storage. Anything reachable from a root is 'live'.","Database connections","Object constructors"],
     "answerIndex":1,"explanation":"GC roots: things the JVM knows are 'live'. From these, GC walks the reference graph and marks reachable objects. Unreachable = garbage. Stack frames are roots (their locals reference live objects). Statics are roots (class-level). JNI refs from native code are roots.","tags":["gc","roots"]},
    {"id":"mem-q13","type":"mcq","prompt":"In a generational garbage collector, the 'young generation' holds:",
     "choices":["Old objects","Newly allocated objects, which mostly die young (locals, request-scoped data). Cleared frequently and quickly.","Static fields","Class metadata"],
     "answerIndex":1,"explanation":"Generational hypothesis: most objects die young. Young gen is small + cleared often (fast). Survivors get promoted to old gen (collected less often, slower). This optimisation makes most GCs much faster than naive mark-sweep. Eden + Survivor spaces in HotSpot.","tags":["gc","generational"]},
    {"id":"mem-q14","type":"mcq","prompt":"Why do String objects (often) live in a special pool in Java?",
     "choices":["For security","String interning: identical string literals are deduplicated to save memory; multiple variables can share one String object on the heap","Strings are primitive","Required by JVM"],
     "answerIndex":1,"explanation":"String pool (interning): 'hello' literal stored once, all variables pointing to 'hello' share the same object. Saves memory for repeated literals. String s = 'x'; String t = 'x'; s == t (TRUE — same reference). Use .intern() to manually intern. Doesn't apply to 'new String()'.","tags":["strings","interning"]},
    {"id":"mem-q15","type":"mcq","prompt":"What does the -Xmx2g JVM flag do?",
     "choices":["Sets stack size","Sets MAXIMUM heap size to 2GB. JVM will allocate up to this and never more, throwing OOME if exceeded.","Sets buffer pool","Disables GC"],
     "answerIndex":1,"explanation":"-Xmx: max heap size. -Xms: initial heap size. -Xss: stack size per thread. Set -Xmx based on your workload + headroom. Too small = OOME. Too large on shared host = waste. Common production: -Xmx4g for moderate apps, more for heavy.","tags":["jvm","flags","heap"]},
    {"id":"mem-q16","type":"mcq","prompt":"In C, what's the bug?\n\nint* p = malloc(100);\nfree(p);\np[0] = 42;",
     "choices":["No bug","Use-after-free: writing to memory that was just released. Undefined behaviour — could corrupt heap, crash, or silently work then fail later.","Memory leak","Double allocation"],
     "answerIndex":1,"explanation":"After free(p), the memory is returned to the allocator and may be reused for another allocation. Writing to it corrupts whatever now lives there. UB: program may crash, or appear to work then fail. Modern C++: use std::unique_ptr to prevent. Java: GC handles this — no use-after-free possible.","tags":["c","memory","uaf"]},
    {"id":"mem-q17","type":"multi","prompt":"Which can cause OutOfMemoryError in Java? (Select all)",
     "choices":["Loading a 10GB file fully into memory","Static cache that never evicts","Adding listeners without removing them","An infinite loop with int counter"],
     "answerIndexes":[0,1,2],"explanation":"All three can fill the heap: 1) genuine large data without streaming, 2) cache holds refs forever, 3) each listener holds object alive. The infinite loop with int doesn't allocate — uses fixed stack space; would hang CPU but not OOM unless the loop body allocates.","tags":["oom","leaks"]},
    {"id":"mem-q18","type":"mcq","prompt":"How do you find a memory leak in a running Java app?",
     "choices":["Add print statements","Take a heap dump (jmap -dump:live,file=heap.hprof PID), open in Eclipse MAT or VisualVM. Look at biggest objects/retained sizes. Compare two dumps over time.","Restart the JVM","Disable GC"],
     "answerIndex":1,"explanation":"Heap dump: snapshot of all heap objects + references. Tools (MAT, VisualVM, JProfiler) analyse: dominators, retained heap, leak suspects. Take 2 dumps after a leak operation; compare object counts. Pinpoint which class is growing. Then trace back through references to find the holder.","tags":["debugging","leaks","tools"]},
    {"id":"mem-q19","type":"mcq","prompt":"What is the difference between -Xmx and -Xss JVM flags?",
     "choices":["Same thing","-Xmx: maximum heap size (objects). -Xss: stack size PER THREAD (function call frames). Both increase memory use but for different regions.","-Xss is for SSL","-Xmx is for metaspace"],
     "answerIndex":1,"explanation":"-Xmx (heap) and -Xss (stack) target different memory regions. Increase -Xmx if OOME on heap. Increase -Xss if StackOverflowError (deep recursion). Note: -Xss is per thread — 1000 threads × 2MB stack = 2GB just for stacks. Default Xss is 1MB.","tags":["jvm","flags"]},
    {"id":"mem-q20","type":"mcq","prompt":"Which JVM garbage collector is good for low-pause production apps?",
     "choices":["Serial GC","G1 (default in Java 9+) — designed for low-pause, can target a max pause time. ZGC and Shenandoah for sub-millisecond pauses on huge heaps.","Mark-sweep manual","Reference counting"],
     "answerIndex":1,"explanation":"Serial GC: single-thread, stops everything. OK for desktop apps. Parallel GC: multi-thread, still stops world. CMS: concurrent (deprecated). G1: regional, low-pause target. ZGC, Shenandoah: sub-millisecond pauses, even for 100GB+ heaps. Most production: G1 or ZGC.","tags":["jvm","gc","tuning"]},
]

MEMORY_FC = [
    {"id":"mem-fc1","front":"Stack vs Heap quick reference","back":"Stack: fast, small (~1MB), auto-managed, function-scoped. Holds frames + primitives + references. Heap: slower, large (GB), GC-managed, lives until unreferenced. Holds objects + arrays. StackOverflowError vs OutOfMemoryError = different root causes.","tags":["memory","fundamentals"]},
    {"id":"mem-fc2","front":"Java pass-by-value rule","back":"Java is ALWAYS pass-by-value. For primitives: value copied (changes don't propagate). For objects: REFERENCE value (address) copied — both pointers go to same heap object, so mutating fields IS visible to caller, but reassigning the local ref is NOT.","tags":["java","pass-by-value"]},
    {"id":"mem-fc3","front":"GC roots — what's a root?","back":"GC roots are starting points for liveness tracking: 1) Active stack frames' local variables, 2) Static fields, 3) JNI references from native code, 4) ThreadLocal storage. Anything reachable from any root = live. Otherwise = garbage.","tags":["gc","roots"]},
    {"id":"mem-fc4","front":"Memory leak patterns in GC languages","back":"GC frees only unreferenced objects. Leaks happen when refs are accidentally held: 1) Static Map/List growing forever (use bounded cache). 2) Listeners not removed. 3) ThreadLocal in thread pool. 4) Anonymous inner class capturing outer.","tags":["leaks","patterns"]},
    {"id":"mem-fc5","front":"JVM memory flags","back":"-Xmx2g: max heap = 2GB. -Xms1g: initial heap = 1GB. -Xss512k: stack per thread = 512KB. Set Xmx based on workload + 30% headroom. Watch GC logs (-Xlog:gc) to see if heap is too small. Big Xss × many threads = surprising RAM use.","tags":["jvm","flags"]},
    {"id":"mem-fc6","front":"Generational GC concept","back":"Most objects die young (request handlers, locals). Young gen: small, fast minor GC. Old gen: larger, infrequent major GC. Promotion: surviving young objects move to old. G1, ZGC, Shenandoah are modern low-pause collectors used in production.","tags":["gc","generational"]},
    {"id":"mem-fc7","front":"Use heap dump to find leaks","back":"jmap -dump:live,file=heap.hprof <pid>. Open in Eclipse MAT. Look at: Dominator tree (biggest retainers), Leak Suspects report. Take 2 dumps over time, compare counts to spot growing classes. Trace incoming refs to find holder.","tags":["debugging","tools"]},
    {"id":"mem-fc8","front":"Stack overflow vs OOM","back":"StackOverflowError: stack full from deep recursion. Fix: iteration with explicit Deque, or -Xss for bigger stack. OutOfMemoryError: heap full. Fix: -Xmx for bigger heap, or fix leak with profiler, or stream large data. Different errors, different root causes.","tags":["errors","jvm"]},
]

MEMORY_PROJ = {
    "brief": "Your Java REST service runs fine for a week, then crashes with OutOfMemoryError. Restart fixes it temporarily. Design a debugging approach: 1) How to capture state without losing the running process. 2) Which tool to analyse the dump. 3) What to look for. 4) Common patterns of leaks to check. 5) How to validate the fix.",
    "checklist": [
        {"id":"m1","text":"Capture heap dump without killing JVM: jmap -dump:live,format=b,file=heap.hprof <pid>. Or auto-dump on OOM with -XX:+HeapDumpOnOutOfMemoryError.","weight":20},
        {"id":"m2","text":"Open dump in Eclipse MAT (Memory Analyzer Tool). Use Leak Suspects report and Dominator Tree to find biggest retained heap.","weight":20},
        {"id":"m3","text":"Look for: large collection sizes, classes with surprisingly many instances, retained-by chains showing what holds the leaked objects.","weight":20},
        {"id":"m4","text":"Common patterns: static cache without eviction, listeners not removed, ThreadLocal in thread pool, inner classes capturing outer.","weight":20},
        {"id":"m5","text":"Validate fix: take heap dump pre and post operation. Confirm count of leaked-class instances no longer grows. Run load test for hours. Watch heap usage flatten not climb.","weight":20},
    ],
    "hints": [
        "If dump is too big to open: jmap -histo for class-instance-count only, much faster, identifies class without full structure.",
        "Use VisualVM in development to watch live heap. Real-time graph during a test scenario reveals which operation triggers the growth.",
        "If you can reproduce in a test environment: set -Xmx64m to force OOM faster, then dump on OOM. Tiny heap exposes leaks quickly.",
    ]
}

write("memory-stack-heap.json", {
    "id": "memory-stack-heap",
    "unit": 1,
    "order": 3,
    "title": "Memory: Stack vs Heap",
    "summary": "How memory is organised, when stack vs heap is used, garbage collection, and finding memory leaks.",
    "prereqs": ["recursion-mental-model"],
    "guide": MEMORY_GUIDE,
    "questions": MEMORY_Q,
    "flashcards": MEMORY_FC,
    "project": MEMORY_PROJ,
})

# ── POINTERS & REFERENCES ────────────────────────────────────────────────────

POINTERS_GUIDE = "\n".join([
    "# Pointers & References",
    "",
    "## Pointer = Address of a Memory Location",
    "",
    "A pointer is a variable that stores the **memory address** of another variable.",
    "Java doesn't have explicit pointers, but it has 'references' — which are pointers",
    "with safety rails (no arithmetic, no use-after-free).",
    "",
    "Understanding pointers/references explains:",
    "- Why two variables can affect each other's data",
    "- Why null/undefined errors crash programs",
    "- How linked lists and trees actually work",
    "- Why Java is 'pass-by-value but objects feel like by-reference'",
    "- The difference between == and .equals() in Java",
    "",
    "---",
    "",
    "## The Mental Model: Variables Are Boxes Holding Either Values or Addresses",
    "",
    "```",
    "PRIMITIVE (value type):",
    "  int x = 42;",
    "",
    "  Memory:",
    "  ┌─────────────────┐",
    "  │   x: 42         │   ← x's box holds the value 42 directly",
    "  └─────────────────┘",
    "",
    "REFERENCE (object):",
    "  String s = \"hello\";",
    "",
    "  Memory:",
    "  ┌─────────────────┐         ┌─────────────────┐",
    "  │   s: 0x7FA1     │ ──────► │  String 'hello' │  ← actual object on heap",
    "  └─────────────────┘         └─────────────────┘",
    "  (s holds an ADDRESS;  the object is somewhere else)",
    "",
    "POINTER in C:",
    "  int  x = 42;",
    "  int* p = &x;       // p holds the address of x",
    "",
    "  Memory:",
    "  ┌─────────────────┐         ┌─────────────────┐",
    "  │   p: 0x7FFC     │ ──────► │   x: 42         │",
    "  └─────────────────┘         └─────────────────┘",
    "",
    "  *p reads what's at the address (42). p reads the address itself.",
    "```",
    "",
    "---",
    "",
    "## Java References vs C Pointers",
    "",
    "```",
    "+──────────────────────+──────────────────────+──────────────────────+",
    "│ Feature              │ C Pointer            │ Java Reference       │",
    "+──────────────────────+──────────────────────+──────────────────────+",
    "│ Holds address?       │ Yes                  │ Yes                  │",
    "│ Pointer arithmetic   │ Yes (p+1, p++)       │ NO                   │",
    "│ Manual free          │ Yes (free(p))        │ NO (GC)              │",
    "│ Can dangle           │ Yes (use-after-free) │ NO (GC keeps alive)  │",
    "│ NULL pointer         │ Yes (dereferencing crashes)│ Yes (NullPointerException)│",
    "│ Pointer-to-pointer   │ Yes (int**)          │ No                   │",
    "│ Type safety          │ Loose (cast freely)  │ Strict (typed)       │",
    "│ Function pointers    │ Yes                  │ Method references    │",
    "+──────────────────────+──────────────────────+──────────────────────+",
    "",
    "Java references = 'safe pointers'. You can:",
    "  - dereference (call methods, access fields): obj.method()",
    "  - reassign: obj = newObj;",
    "  - compare with == (compares addresses, not contents!)",
    "  - test for null: if (obj == null)",
    "",
    "You CANNOT:",
    "  - do address arithmetic",
    "  - manually free",
    "  - cast unrelated types",
    "```",
    "",
    "---",
    "",
    "## == vs .equals() in Java",
    "",
    "This is THE most common Java pitfall related to references.",
    "",
    "```",
    "==          compares ADDRESSES (do both refs point to same object?)",
    ".equals()   compares CONTENTS (are the values logically equal?)",
    "",
    "String s1 = \"hello\";",
    "String s2 = \"hello\";",
    "String s3 = new String(\"hello\");",
    "",
    "  s1 ──────────► [ String 'hello' ]   ← interned, both s1 and s2 point here",
    "  s2 ─────────────────^",
    "  s3 ──────────► [ String 'hello' ]   ← separate object via 'new'",
    "",
    "  s1 == s2          → true   (same reference, due to string interning)",
    "  s1 == s3          → false  (different objects on heap)",
    "  s1.equals(s2)     → true   (same content)",
    "  s1.equals(s3)     → true   (same content)",
    "",
    "RULE: Always use .equals() for value comparison. == only for null check or identity.",
    "",
    "FOR PRIMITIVES: == is correct (value comparison)",
    "  int a = 5, b = 5;",
    "  a == b → true",
    "",
    "FOR Integer (boxed): subtle!",
    "  Integer x = 100, y = 100;",
    "  x == y → true (cached)",
    "  Integer p = 200, q = 200;",
    "  p == q → false (no cache for this range)",
    "  Always use .equals() for Integer comparisons.",
    "```",
    "",
    "---",
    "",
    "## Null References — The Billion Dollar Mistake",
    "",
    "Tony Hoare, who invented null in 1965, called it his 'billion dollar mistake' for",
    "the years of NullPointerException bugs it has caused.",
    "",
    "```",
    "String name = null;       // name points to nothing",
    "name.length();            // NullPointerException at runtime!",
    "",
    "// Why? You're trying to read from address 'nowhere'.",
    "// In C: dereferencing NULL crashes the program.",
    "// In Java: NPE thrown, can be caught.",
    "",
    "DEFENCE STRATEGIES (modern Java):",
    "",
    "1. Optional<T> — explicit absence",
    "   Optional<User> findById(int id) { ... }",
    "   findById(42).ifPresent(u -> println(u.getName()));",
    "",
    "2. Check before access",
    "   if (name != null) {",
    "       println(name.length());",
    "   }",
    "",
    "3. Use Objects.requireNonNull() — fail fast at boundaries",
    "   public void process(User u) {",
    "       Objects.requireNonNull(u, \"user must not be null\");",
    "       // continue with non-null u",
    "   }",
    "",
    "4. Annotations: @NonNull, @Nullable",
    "   void greet(@NonNull String name) { ... }",
    "   IDE/tools can warn at COMPILE time on null arguments.",
    "",
    "5. Kotlin / Modern languages: nullable types in the type system",
    "   String?  → may be null, must check",
    "   String   → cannot be null, compiler enforces",
    "```",
    "",
    "---",
    "",
    "## Aliasing — When Two Variables Point to Same Thing",
    "",
    "```java",
    "List<Integer> a = new ArrayList<>();",
    "a.add(1);",
    "a.add(2);",
    "",
    "List<Integer> b = a;       // b points to SAME list",
    "b.add(99);",
    "",
    "System.out.println(a);     // [1, 2, 99]  — modified through b!",
    "System.out.println(b);     // [1, 2, 99]",
    "System.out.println(a == b); // true (same object)",
    "```",
    "",
    "**Visualisation:**",
    "",
    "```",
    "  Stack:                     Heap:",
    "  ┌──────────────┐           ┌─────────────────────┐",
    "  │ a: 0x100  ──┼───────────►│ ArrayList [1,2,99]  │",
    "  │ b: 0x100  ──┼───────────►^                     │",
    "  └──────────────┘           └─────────────────────┘",
    "",
    "  Both a and b hold the same address. Mutations through either",
    "  are visible to both. This is ALIASING.",
    "",
    "  To get an independent copy:",
    "  List<Integer> c = new ArrayList<>(a);  // copy constructor",
    "  c.add(999);  // doesn't affect a or b",
    "```",
    "",
    "Aliasing causes subtle bugs in concurrent code, mutable shared state, and accidental",
    "modifications. Defensive copy or immutable types prevent these.",
    "",
    "---",
    "",
    "## Linked Data Structures = Pointers in Action",
    "",
    "```",
    "A linked list is just nodes that hold references to each other:",
    "",
    "  class Node {",
    "      int value;",
    "      Node next;       // reference to next node, or null",
    "  }",
    "",
    "  Node n3 = new Node(3, null);     // tail points to null",
    "  Node n2 = new Node(2, n3);       // n2.next points to n3",
    "  Node n1 = new Node(1, n2);       // n1.next points to n2",
    "",
    "  Memory layout:",
    "",
    "  Stack:                     Heap:",
    "  n1 ────► [1 | next] ────► [2 | next] ────► [3 | null]",
    "",
    "  Walk the list:",
    "  Node curr = n1;",
    "  while (curr != null) {",
    "      System.out.println(curr.value);",
    "      curr = curr.next;       // follow the reference",
    "  }",
    "  // Prints: 1, 2, 3",
    "",
    "TREES, GRAPHS — same idea: each node holds references to others.",
    "  Binary tree: node has left, right",
    "  Graph: node has list<Node> neighbours",
    "  All built on references / pointers.",
    "```",
    "",
    "---",
    "",
    "## Shallow vs Deep Copy",
    "",
    "When you copy an object that CONTAINS references, do you copy the references or the things they point to?",
    "",
    "```java",
    "class Person {",
    "    String name;",
    "    List<String> hobbies;",
    "}",
    "",
    "Person alice = new Person(\"Alice\", new ArrayList<>(List.of(\"hiking\")));",
    "",
    "// Shallow copy: copy fields, but reference fields share same target",
    "Person aliceCopy = new Person(alice.name, alice.hobbies);",
    "aliceCopy.hobbies.add(\"reading\");",
    "// alice.hobbies now also contains 'reading'!",
    "// because both point to same ArrayList",
    "",
    "// Deep copy: recursively copy all referenced objects",
    "Person aliceDeep = new Person(alice.name, new ArrayList<>(alice.hobbies));",
    "aliceDeep.hobbies.add(\"swimming\");",
    "// alice.hobbies unchanged — independent list",
    "",
    "// In Java, default Object.clone() is shallow.",
    "// For deep copy: implement copy constructor or use serialisation/Cloneable + override.",
    "```",
    "",
    "**Visualisation:**",
    "",
    "```",
    "Original (alice):",
    "  Person ──► name: 'Alice'",
    "         └─► hobbies ──► [hiking]",
    "",
    "Shallow copy:",
    "  PersonA ──► name: 'Alice'           ← copied (or shared if String pool)",
    "          └─► hobbies ──┐",
    "  PersonB ──► name: 'Alice'",
    "          └─► hobbies ──┴─► [hiking]    ← BOTH point to same list!",
    "",
    "Deep copy:",
    "  PersonA ──► name: 'Alice'",
    "          └─► hobbies ──► [hiking]      ← original list",
    "  PersonB ──► name: 'Alice'",
    "          └─► hobbies ──► [hiking]      ← INDEPENDENT copy",
    "```",
    "",
    "---",
    "",
    "## C Pointer Examples (Just for Mental Model)",
    "",
    "```c",
    "// Basic pointer",
    "int x = 10;",
    "int* p = &x;       // p = address of x",
    "*p = 20;           // dereference: write 20 to where p points",
    "// Now x == 20",
    "",
    "// Pointer arithmetic (Java has nothing like this)",
    "int arr[] = {1, 2, 3, 4};",
    "int* p = arr;      // p points to arr[0]",
    "*(p + 2);          // *(p+2) = arr[2] = 3",
    "p++;               // now p points to arr[1]",
    "",
    "// Pointer to pointer",
    "int x = 5;",
    "int* p = &x;",
    "int** pp = &p;     // pp = address of p",
    "**pp = 99;         // dereference twice: x = 99",
    "",
    "// Common bug: dangling pointer",
    "int* p;",
    "{",
    "    int x = 10;",
    "    p = &x;",
    "}  // x goes out of scope; p now dangles!",
    "*p; // undefined behaviour — x is gone",
    "",
    "// Java: GC keeps x alive as long as p references it. No dangling possible.",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "POINTERS & REFERENCES",
    "|",
    "+-- WHAT THEY ARE",
    "|   +-- Variable holding a memory address",
    "|   +-- Java references = safe pointers",
    "|   +-- C pointers = unrestricted",
    "|",
    "+-- JAVA SPECIFICS",
    "|   +-- == compares addresses",
    "|   +-- .equals() compares contents",
    "|   +-- Always .equals() for objects",
    "|   +-- Integer auto-unbox subtleties",
    "|",
    "+-- NULL",
    "|   +-- Address pointing to nothing",
    "|   +-- Dereferencing → NullPointerException",
    "|   +-- Defences: Optional, requireNonNull, @NonNull",
    "|",
    "+-- ALIASING",
    "|   +-- Two refs to same object",
    "|   +-- Mutations through one visible to other",
    "|   +-- Defensive copy or immutability prevents bugs",
    "|",
    "+-- SHALLOW vs DEEP COPY",
    "|   +-- Shallow: copies references, shares targets",
    "|   +-- Deep: recursively copies everything",
    "|",
    "+-- DATA STRUCTURES",
    "    +-- Linked list = nodes with next references",
    "    +-- Tree = node with left, right references",
    "    +-- Graph = node with list<Node>",
    "    +-- All built on references",
    "```",
    "",
    "---",
    "",
    "## How Pointers/References Connect to Other Topics",
    "",
    "- **Memory (stack/heap)**: references on stack point to heap objects",
    "- **Linked List, Tree, Graph**: nodes connected by references",
    "- **Garbage Collection**: GC tracks references to determine liveness",
    "- **Concurrency**: shared mutable state via aliasing causes races",
    "- **Immutability**: prevents aliasing bugs by design (Strings, records)",
    "",
    "---",
    "",
    "## Common Beginner Mistakes",
    "",
    "1. **Using == for String/object equality** — compares addresses, not content",
    "2. **NullPointerException without checking** — always validate or use Optional",
    "3. **Sharing mutable state** without realising it's the same object (aliasing)",
    "4. **Shallow copy when deep copy needed** — modifications leak across copies",
    "5. **Modifying a list while iterating** — ConcurrentModificationException",
    "6. **Returning a reference to internal state** — caller can mutate your private data",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **Pointers in C/C++ Explained** by mycodeschool: https://www.youtube.com/watch?v=LMoyzKduFc4",
    "- **Java Pass-By-Value vs Reference** by Cave of Programming: https://www.youtube.com/watch?v=t7SBOSmmMIA",
    "",
    "### Articles",
    "- **Pass-by-value in Java** (Baeldung): https://www.baeldung.com/java-pass-by-value-or-pass-by-reference",
    "- **Optional in Java** (Baeldung): https://www.baeldung.com/java-optional",
])

POINTERS_Q = [
    {"id":"ptr-q1","type":"mcq","prompt":"What does a pointer/reference variable actually store?",
     "choices":["A copy of the value","The MEMORY ADDRESS of another variable or object — not the value itself","A function","A type tag"],
     "answerIndex":1,"explanation":"Pointers/references hold an address. Through that address, you can access the actual data. The variable holding the address is small (typically 8 bytes); the object it points to may be much larger and lives elsewhere (heap).","tags":["pointers","references","fundamentals"]},
    {"id":"ptr-q2","type":"mcq","prompt":"In Java, what does '==' compare for object references?",
     "choices":["Object contents","The ADDRESS — whether both variables point to the SAME object on the heap. Use .equals() for content comparison.","Object types","Hash codes"],
     "answerIndex":1,"explanation":"== compares addresses for objects. s1 == s2 is true only if both refer to identical heap object. For value comparison: .equals(). 'String a = new String(\"x\"); String b = new String(\"x\"); a == b → false. a.equals(b) → true'. This trips up beginners constantly.","tags":["java","equality","references"]},
    {"id":"ptr-q3","type":"codeOutput","prompt":"What does this print?\n\nString s1 = \"hello\";\nString s2 = new String(\"hello\");\nSystem.out.println(s1 == s2);\nSystem.out.println(s1.equals(s2));",
     "code":"interned literal vs new",
     "choices":["true, true","false, true","false, false — they're different objects with same content","true, false"],
     "answerIndex":1,"explanation":"s1 = literal → interned in String pool. s2 = new String() → new heap object. Different addresses (==) gives false. Same content, .equals() gives true. ALWAYS use .equals() for String comparison. == only works coincidentally with interned literals.","tags":["string","equality"]},
    {"id":"ptr-q4","type":"codeOutput","prompt":"What does this print?\n\nList<Integer> a = new ArrayList<>(List.of(1, 2));\nList<Integer> b = a;\nb.add(99);\nSystem.out.println(a);",
     "code":"aliasing — two refs to same list",
     "choices":["[1, 2]","[1, 2, 99] — a and b are aliases (same object); modification through b is visible through a","Compile error","Null"],
     "answerIndex":1,"explanation":"List<Integer> b = a does NOT copy. b becomes another reference to the same ArrayList. b.add(99) modifies the shared object. a sees the change. To get an independent copy: 'new ArrayList<>(a)'. Aliasing is a leading source of bugs in mutable shared state.","tags":["aliasing","lists"]},
    {"id":"ptr-q5","type":"mcq","prompt":"What is a NullPointerException in Java?",
     "choices":["A compile error","Runtime error when you dereference (call method on / access field of) a reference that is null — pointing to no object","Memory leak","Out of memory"],
     "answerIndex":1,"explanation":"NPE: you tried to use a null reference. 'String s = null; s.length();' throws NPE. The JVM checks before each method call/field access. Defences: Optional<T>, null checks, @NonNull annotations, requireNonNull at boundaries. Most common Java bug in production.","tags":["null","npe"]},
    {"id":"ptr-q6","type":"mcq","prompt":"What is the difference between shallow copy and deep copy?",
     "choices":["No difference","Shallow: copies fields (reference fields point to same target). Deep: recursively copies all referenced objects, creating fully independent structure.","Deep is faster","Shallow only works for primitives"],
     "answerIndex":1,"explanation":"Shallow copy: a Person with a List field — copy gets new Person but same List. Modifying list via either Person affects both. Deep copy: recursively allocates new List, new contents. Independent. Default Object.clone() is shallow. Use copy constructors for deep.","tags":["copy","shallow-deep"]},
    {"id":"ptr-q7","type":"mcq","prompt":"In Java, calling 'list.add(99)' inside a method DOES modify the caller's list. Why?",
     "choices":["Java is pass-by-reference","Java passes references by value: the address bits are copied, but both the local copy and caller's variable point to the SAME list on the heap. Mutating through the reference is visible to caller.","JVM magic","Lists are special"],
     "answerIndex":1,"explanation":"Java is always pass-by-value. For objects, the value passed is the reference (address). Method's local var has its own copy of the address but it points to the same object. Mutating fields is visible. Reassigning the local var (list = new ArrayList<>()) is NOT visible to caller.","tags":["pass-by-value","references"]},
    {"id":"ptr-q8","type":"codeOutput","prompt":"What does this print?\n\nInteger a = 100, b = 100;\nInteger c = 200, d = 200;\nSystem.out.println(a == b);\nSystem.out.println(c == d);",
     "code":"Integer cache subtlety",
     "choices":["true, true","true, false — Integer caches values -128 to 127, so a and b share, but c and d are new objects","false, false","false, true"],
     "answerIndex":1,"explanation":"Integer.valueOf() caches -128 to 127 (auto-boxing range). Within range: same reference, == works. Outside range: new objects, == fails. CONCLUSION: never use == for Integer/Long etc. Always .equals() or unbox to int first. This is a notorious Java pitfall.","tags":["java","integer-cache"]},
    {"id":"ptr-q9","type":"mcq","prompt":"What is a 'dangling pointer' in C?",
     "choices":["A null pointer","A pointer to memory that has been freed/deallocated. Reading or writing through it is undefined behaviour — may crash, may silently corrupt.","An array pointer","A function pointer"],
     "answerIndex":1,"explanation":"Dangling pointer in C: free(p) but still using p. Memory may be reused for something else. Writing to it corrupts whatever now lives there. Java: GC keeps objects alive as long as references exist — no dangling possible. C++ smart pointers (unique_ptr, shared_ptr) prevent these bugs.","tags":["c","dangling","memory-bug"]},
    {"id":"ptr-q10","type":"mcq","prompt":"What does Optional<T> in Java solve?",
     "choices":["Memory leaks","Makes the absence of a value EXPLICIT in the type signature, forcing the caller to handle it. Reduces NullPointerException by design.","Concurrency","Generics"],
     "answerIndex":1,"explanation":"Optional<User> findById(int id): caller knows the result MAY be absent. Compiler reminds them: must call .orElse(), .ifPresent(), .map() etc. Better than nullable User which silently allows NPE. Best practice: never return null from public APIs — use Optional.","tags":["optional","null-safety"]},
    {"id":"ptr-q11","type":"mcq","prompt":"What is the difference between Java references and C pointers?",
     "choices":["Same","Java refs are 'safe pointers': no arithmetic (p+1), no manual free, can't dangle (GC), strict types. C pointers allow all of these but with greater bug risk.","Java has no pointers","C has no references"],
     "answerIndex":1,"explanation":"Java refs are restricted: no &p, no *p, no p++, no p+5. The JVM/GC manage memory. Strict typing prevents casting unrelated types. C is more powerful (raw memory access) but error-prone. Modern C++ smart pointers add safety similar to Java refs.","tags":["c","java","comparison"]},
    {"id":"ptr-q12","type":"mcq","prompt":"In linked list traversal: 'while (curr != null) { ... curr = curr.next; }' — what is happening?",
     "choices":["Copying nodes","Following references: curr starts at head, then re-points to each next node via the curr.next reference field. When curr = null, end of list reached.","Sorting","Concatenating"],
     "answerIndex":1,"explanation":"Linked list = chain of nodes connected by 'next' references. Traversal: walk references one at a time. Each node's 'next' field is a reference to the next node, or null if it's the last. This is the canonical use of pointers/references for data structures.","tags":["linked-list","traversal"]},
    {"id":"ptr-q13","type":"mcq","prompt":"You return your private List<Integer> from a getter. What's the bug?",
     "choices":["No bug","Caller has a reference to your INTERNAL list and can mutate it. Encapsulation broken. Fix: return new ArrayList<>(internal) or Collections.unmodifiableList(internal).","Slow performance","Compile error"],
     "answerIndex":1,"explanation":"Returning the same reference exposes internal state. Caller does .add(...) and corrupts your object. Defensive copy: return new ArrayList<>(internal). Or unmodifiable view: Collections.unmodifiableList(internal). Or use immutable collection (List.copyOf). Common encapsulation bug.","tags":["encapsulation","defensive-copy"]},
    {"id":"ptr-q14","type":"mcq","prompt":"Why is Java's String class immutable?",
     "choices":["Performance only","Safety: many things hold references to a String (HashMap keys, security checks). If String were mutable, holders could see the value change unexpectedly. Immutability eliminates aliasing risks.","Random choice","Required by JVM"],
     "answerIndex":1,"explanation":"Immutable String prevents aliasing bugs: holder can trust the value won't change. HashMap rebuilds wouldn't be needed (key contents stable). Concurrency: no synchronisation. Security: pathnames, class names can't be mutated mid-check. Immutability is a design pattern that eliminates whole classes of bugs.","tags":["string","immutability"]},
    {"id":"ptr-q15","type":"multi","prompt":"Which prevent NullPointerException? (Select all)",
     "choices":["Optional<T>","Objects.requireNonNull(x, msg) at method entry","@NonNull annotations + IDE/compile checks","Adding more null checks everywhere defensively"],
     "answerIndexes":[0,1,2],"explanation":"All three actually help. Optional makes absence explicit in the type. requireNonNull fails fast at boundaries. @NonNull lets tools warn at compile. Defensive null checks 'everywhere' (option 4) is an anti-pattern — bloats code, hides intent. Better: design with non-nullable defaults, use Optional only where absence is meaningful.","tags":["null-safety","practices"]},
    {"id":"ptr-q16","type":"mcq","prompt":"What is 'aliasing' in programming?",
     "choices":["Renaming variables","Two or more variables referencing the SAME underlying object — modifications through one are visible through all others","Caching","Type casting"],
     "answerIndex":1,"explanation":"Aliasing: 'b = a' for objects creates an alias. Both vars point to same heap object. Modifying through b affects view from a. Causes bugs especially in mutable shared state. Mitigations: defensive copy, immutability, ownership types (Rust). Source of many concurrency bugs.","tags":["aliasing","mutability"]},
    {"id":"ptr-q17","type":"mcq","prompt":"In Java, 'a.equals(b)' returns true but 'a.hashCode() != b.hashCode()'. What's the bug?",
     "choices":["Java is broken","CONTRACT violation: if a.equals(b) is true, hashCode() MUST be equal. Otherwise HashMap and HashSet break (two equal keys land in different buckets, can't be retrieved).","Just a warning","Hashing optional"],
     "answerIndex":1,"explanation":"Java's equals/hashCode contract: equal objects MUST have equal hash codes. If you override equals(), you MUST override hashCode() consistently. Otherwise HashMap.get(key) won't find your object: it computes hash, goes to bucket B, but your equal-key was placed in bucket A.","tags":["java","equals-hashcode","contract"]},
    {"id":"ptr-q18","type":"mcq","prompt":"What is a memory address in plain terms?",
     "choices":["A function pointer","A unique number identifying one specific location in RAM. Like a postal address for a building.","A class name","A file path"],
     "answerIndex":1,"explanation":"RAM is a giant array. Each byte has a unique address (e.g. 0x7FFC000A in 64-bit). Pointer/reference = a number representing this address. To read what's there: dereference the pointer. The OS and CPU translate virtual addresses to physical addresses (you don't see physical).","tags":["memory","address"]},
    {"id":"ptr-q19","type":"mcq","prompt":"In Kotlin, 'String' vs 'String?' — what's the difference?",
     "choices":["No difference","String CANNOT be null (compiler enforces). String? CAN be null and you must explicitly handle it (?. or !!). Type system encodes nullability.","Performance","Generic"],
     "answerIndex":1,"explanation":"Kotlin uses non-null types by default. 'val s: String' compiler ensures s is never null. 'val s: String?' requires safe calls (s?.length) or assertions (s!!.length). Eliminates NullPointerException at compile time. Java is gradually adding similar with @NonNull/@Nullable but not enforced by language.","tags":["kotlin","null-safety"]},
    {"id":"ptr-q20","type":"mcq","prompt":"Why does this defensive copy NOT fully protect: 'return new ArrayList<>(internalList)' for List<Person>?",
     "choices":["It's a complete defence","Shallow copy only — the new list contains the SAME Person references. Caller can still mutate Person objects. Need DEEP copy: stream and copy each Person.","Compile fails","Always works"],
     "answerIndex":1,"explanation":"new ArrayList<>(other) creates a new list but shares element references. If Person is mutable, caller can do list.get(0).setName('attacker'). To fully protect: return new ArrayList containing copies of each Person. Best: make Person immutable (record + final fields).","tags":["defensive-copy","shallow"]},
]

POINTERS_FC = [
    {"id":"ptr-fc1","front":"Pointer/Reference definition","back":"Variable holding a memory address. Through it you access the actual data. Java refs = safe pointers (no arithmetic, no manual free, no dangling — GC tracks). C pointers = full power but error-prone.","tags":["pointers","fundamentals"]},
    {"id":"ptr-fc2","front":"== vs .equals() in Java","back":"== compares ADDRESSES (same object?). .equals() compares CONTENTS (same value?). For Strings/Objects: ALWAYS .equals(). For primitives (int, char, boolean): == works. Integer caches -128..127 — never use == for boxed types.","tags":["java","equality"]},
    {"id":"ptr-fc3","front":"Aliasing and how to prevent bugs","back":"Aliasing: 'b = a' makes b another reference to same object. Mutation through b visible to a. Defences: 1) Immutable types (record, String). 2) Defensive copy (new ArrayList<>(...)). 3) Unmodifiable views (Collections.unmodifiableList).","tags":["aliasing","mutability"]},
    {"id":"ptr-fc4","front":"NullPointerException defences","back":"1) Optional<T> for return values. 2) Objects.requireNonNull(x, msg) at method entry. 3) @NonNull annotations + tooling. 4) Kotlin-style nullable types in modern languages. AVOID excessive null-checking everywhere.","tags":["null","npe"]},
    {"id":"ptr-fc5","front":"Shallow vs Deep copy","back":"Shallow: copy fields, reference fields share targets. Deep: recursively copy referenced objects too. Object.clone() default = shallow. For deep: copy constructor with new collections + cloned elements. Safer: immutable types eliminate need.","tags":["copy","shallow-deep"]},
    {"id":"ptr-fc6","front":"Java pass-by-value rule","back":"Java is ALWAYS pass-by-value. For primitives: value copied. For objects: REFERENCE value (address) copied. Both refs point to same heap object — mutations visible. Re-binding the local ref does NOT propagate to caller. There's no pass-by-reference in Java.","tags":["java","pass-by-value"]},
    {"id":"ptr-fc7","front":"Linked structure pattern","back":"Linked list: Node{value, Node next}. Tree: Node{left, right}. Graph: Node{List<Node> neighbours}. Walk: while(curr!=null) { use curr; curr=curr.next; }. Build: new Node(value, existingNode). All built on references.","tags":["linked-list","structures"]},
    {"id":"ptr-fc8","front":"equals/hashCode contract","back":"If a.equals(b), then a.hashCode() == b.hashCode(). Override BOTH together. Violation breaks HashMap, HashSet (key in wrong bucket, can't be retrieved). IDE generates both. Use records (auto-generates correctly) or Objects.hash() helper.","tags":["java","contract","hashing"]},
]

POINTERS_PROJ = {
    "brief": "You're reviewing a junior dev's Java code. They've created a User class with: a password field (String), a List<Role> roles, and methods for getRoles() returning the list directly, equals() based only on user.id, and missing hashCode(). Identify all reference/pointer-related issues, explain the implications, and rewrite the class safely.",
    "checklist": [
        {"id":"p1","text":"getRoles() exposes internal list — caller can mutate User's roles. Fix: return Collections.unmodifiableList(roles) or new ArrayList<>(roles), or return immutable List.copyOf(roles).","weight":20},
        {"id":"p2","text":"hashCode() missing while equals() overridden — breaks HashMap/HashSet contract. Two equal users might land in different buckets. Add hashCode() returning Objects.hash(id) consistent with equals.","weight":20},
        {"id":"p3","text":"Password as String — JVM keeps Strings in pool, can't securely wipe. Use char[] (clearable with Arrays.fill) or modern: java.security.Password. Defensive copy on input.","weight":20},
        {"id":"p4","text":"Constructor takes List<Role> — store defensive copy: this.roles = new ArrayList<>(roles). Otherwise external mutations of caller's list affect User's state.","weight":20},
        {"id":"p5","text":"Better: convert to a record (Java 14+): User(int id, char[] password, List<Role> roles). Records auto-generate equals/hashCode/toString correctly. Combine with List.copyOf in compact constructor.","weight":20},
    ],
    "hints": [
        "Records solve most of these issues automatically: equals/hashCode generated from all components, fields are final (no aliasing leak via setters).",
        "If User must be a class (not record): minimum: defensive copy in constructor, unmodifiable getter, both equals AND hashCode using id only, and char[] for password.",
        "Modern Java: 'Collection.unmodifiableList' returns a view (caller can't mutate) but if you mutate internal, they see it. 'List.copyOf' returns truly independent immutable copy.",
    ]
}

write("pointers-references.json", {
    "id": "pointers-references",
    "unit": 1,
    "order": 4,
    "title": "Pointers & References",
    "summary": "Memory addresses, Java references vs C pointers, == vs equals, null safety, aliasing, and defensive copying.",
    "prereqs": ["memory-stack-heap"],
    "guide": POINTERS_GUIDE,
    "questions": POINTERS_Q,
    "flashcards": POINTERS_FC,
    "project": POINTERS_PROJ,
})

print("\n=== Foundations Batch 2a Complete ===")
print("Written:")
print("  - foundations/memory-stack-heap.json")
print("  - foundations/pointers-references.json")
print("")
print("💡 Next: run foundations_batch2b.py for SQL + embedded DBs")

