"""
Foundations Batch 2b: Database fundamentals
  - relational-databases-sql (order 5)
  - embedded-databases (order 6)
Run: python3 scripts/foundations_batch2b.py
"""
import json
from pathlib import Path

BASE = Path(__file__).parent.parent / "src/content/topics/foundations"
BASE.mkdir(parents=True, exist_ok=True)


def write(filename, data):
    out = BASE / filename
    if out.exists():
        existing = json.loads(out.read_text())
        if len(existing.get("questions", [])) >= 20:
            print(f"  SKIP {filename} (already complete)")
            return
    out.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    print(f"  WROTE {filename}: guide={len(data['guide'])} q={len(data['questions'])} fc={len(data['flashcards'])}")


# ── RELATIONAL DATABASES & SQL ───────────────────────────────────────────────

SQL_GUIDE = "\n".join([
    "# Relational Databases & SQL",
    "",
    "## What Is a Relational Database?",
    "",
    "A relational database stores data in **tables** (rows and columns), like spreadsheets,",
    "where tables can be **related** to each other via shared values (foreign keys).",
    "",
    "**SQL** (Structured Query Language) is the language you use to query and modify the data.",
    "",
    "Almost every real-world software system uses a relational database for its core data:",
    "- E-commerce: users, products, orders",
    "- Banking: accounts, transactions, balances",
    "- Social: users, posts, follows",
    "- Even your phone's contacts app (uses SQLite under the hood)",
    "",
    "**Popular relational databases:**",
    "- **PostgreSQL** — open-source, feature-rich, the favourite of modern devs",
    "- **MySQL / MariaDB** — open-source, widely used in legacy systems",
    "- **Oracle** — enterprise heavyweight",
    "- **SQL Server** — Microsoft's option",
    "- **SQLite** — embedded, single-file, used in mobile apps",
    "",
    "---",
    "",
    "## The Anatomy of a Table",
    "",
    "```",
    "  users table:",
    "  +────+──────────+──────────────────+──────────+",
    "  │ id │ name     │ email            │ age      │",
    "  +────+──────────+──────────────────+──────────+",
    "  │ 1  │ Alice    │ alice@example.com│ 28       │",
    "  │ 2  │ Bob      │ bob@example.com  │ 35       │",
    "  │ 3  │ Charlie  │ charlie@gmail.com│ 22       │",
    "  +────+──────────+──────────────────+──────────+",
    "",
    "  Each ROW = one record (one user).",
    "  Each COLUMN = one attribute (e.g. age).",
    "  Columns have TYPES (integer, varchar, timestamp).",
    "  PRIMARY KEY (here: id) uniquely identifies each row.",
    "```",
    "",
    "**Multi-table example:**",
    "",
    "```",
    "  users:                    orders:",
    "  +────+─────────+         +─────+─────────+──────────+",
    "  │ id │ name    │         │ id  │ user_id │ amount   │",
    "  +────+─────────+         +─────+─────────+──────────+",
    "  │ 1  │ Alice   │←────────│ 100 │ 1       │ 49.99    │",
    "  │ 2  │ Bob     │         │ 101 │ 1       │ 19.99    │",
    "  +────+─────────+         │ 102 │ 2       │ 99.00    │",
    "                           +─────+─────────+──────────+",
    "",
    "  orders.user_id is a FOREIGN KEY referencing users.id",
    "  This is the 'relation' in 'relational database'.",
    "  Alice (id=1) has two orders. Bob has one.",
    "```",
    "",
    "---",
    "",
    "## SELECT — Reading Data",
    "",
    "```sql",
    "-- Get all columns, all rows:",
    "SELECT * FROM users;",
    "",
    "-- Specific columns:",
    "SELECT name, email FROM users;",
    "",
    "-- Filter rows with WHERE:",
    "SELECT * FROM users WHERE age >= 18;",
    "SELECT * FROM users WHERE name = 'Alice';",
    "SELECT * FROM users WHERE email LIKE '%@gmail.com';",
    "",
    "-- Sort with ORDER BY:",
    "SELECT * FROM users ORDER BY age DESC;     -- newest first",
    "SELECT * FROM users ORDER BY name ASC;     -- alphabetical",
    "",
    "-- Limit rows returned:",
    "SELECT * FROM users LIMIT 10;",
    "SELECT * FROM users ORDER BY id LIMIT 10 OFFSET 20;  -- pagination",
    "",
    "-- Aggregate functions:",
    "SELECT COUNT(*) FROM users;                -- total users",
    "SELECT AVG(age) FROM users;                -- average age",
    "SELECT MIN(age), MAX(age) FROM users;",
    "",
    "-- GROUP BY + aggregate:",
    "SELECT user_id, COUNT(*) AS order_count, SUM(amount) AS total_spent",
    "FROM orders",
    "GROUP BY user_id;",
    "-- Result:",
    "-- user_id | order_count | total_spent",
    "-- 1       | 2           | 69.98",
    "-- 2       | 1           | 99.00",
    "",
    "-- HAVING filters AFTER grouping:",
    "SELECT user_id, COUNT(*) AS cnt",
    "FROM orders",
    "GROUP BY user_id",
    "HAVING COUNT(*) > 5;",
    "```",
    "",
    "---",
    "",
    "## JOINs — Combining Tables",
    "",
    "```sql",
    "-- INNER JOIN: only rows that match in BOTH tables",
    "SELECT u.name, o.amount",
    "FROM users u",
    "INNER JOIN orders o ON o.user_id = u.id;",
    "",
    "-- Result: only users WITH orders",
    "-- name  | amount",
    "-- Alice | 49.99",
    "-- Alice | 19.99",
    "-- Bob   | 99.00",
    "-- (Charlie has no orders → excluded)",
    "",
    "-- LEFT JOIN: all rows from LEFT table, NULL for unmatched right",
    "SELECT u.name, o.amount",
    "FROM users u",
    "LEFT JOIN orders o ON o.user_id = u.id;",
    "",
    "-- Result: all users, NULL where no orders",
    "-- name    | amount",
    "-- Alice   | 49.99",
    "-- Alice   | 19.99",
    "-- Bob     | 99.00",
    "-- Charlie | NULL",
    "",
    "-- RIGHT JOIN: mirror of LEFT (rare; usually use LEFT)",
    "-- FULL OUTER JOIN: all rows from both tables (NULL where no match)",
    "```",
    "",
    "**JOIN visualisation:**",
    "",
    "```",
    "  INNER JOIN              LEFT JOIN              FULL OUTER JOIN",
    "                                                                ",
    "    users  orders          users  orders          users  orders",
    "      ◯─────◯                ◯─────◯                ◯─────◯  ",
    "      │     │                │     │                │     │  ",
    "      └─────┘                └─────┘                └─────┘  ",
    "       only                  all left              all from",
    "       intersection         + matches              both sides",
    "```",
    "",
    "---",
    "",
    "## INSERT, UPDATE, DELETE — Modifying Data",
    "",
    "```sql",
    "-- INSERT: add new rows",
    "INSERT INTO users (name, email, age)",
    "VALUES ('Diana', 'diana@example.com', 30);",
    "",
    "-- INSERT multiple rows:",
    "INSERT INTO users (name, email, age) VALUES",
    "    ('Eve', 'eve@example.com', 25),",
    "    ('Frank', 'frank@example.com', 40);",
    "",
    "-- UPDATE: modify existing rows",
    "UPDATE users SET age = 29 WHERE id = 1;",
    "",
    "-- ALWAYS use WHERE — without it, updates ALL rows!",
    "UPDATE users SET active = false;   -- updates EVERY user!",
    "",
    "-- DELETE: remove rows",
    "DELETE FROM orders WHERE id = 100;",
    "",
    "-- DANGEROUS without WHERE:",
    "DELETE FROM users;     -- deletes ALL users! Use TRUNCATE for clean wipe.",
    "",
    "-- Best practice: write SELECT first, verify, then change to UPDATE/DELETE",
    "SELECT * FROM users WHERE last_login < '2020-01-01';   -- preview",
    "DELETE FROM users WHERE last_login < '2020-01-01';     -- act",
    "```",
    "",
    "---",
    "",
    "## Schema Design Basics",
    "",
    "```sql",
    "CREATE TABLE users (",
    "    id          SERIAL PRIMARY KEY,            -- auto-increment ID",
    "    name        VARCHAR(100) NOT NULL,",
    "    email       VARCHAR(255) UNIQUE NOT NULL,  -- no duplicates",
    "    age         INTEGER CHECK (age >= 0),      -- validation",
    "    created_at  TIMESTAMPTZ DEFAULT NOW()      -- auto-set on insert",
    ");",
    "",
    "CREATE TABLE orders (",
    "    id          SERIAL PRIMARY KEY,",
    "    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,",
    "    amount      DECIMAL(10, 2) NOT NULL,       -- money: 10 digits, 2 decimal",
    "    created_at  TIMESTAMPTZ DEFAULT NOW()",
    ");",
    "",
    "-- INDEX: speeds up queries on this column",
    "CREATE INDEX idx_orders_user_id ON orders(user_id);",
    "CREATE INDEX idx_orders_created ON orders(created_at);",
    "",
    "KEY CONSTRAINTS:",
    "  PRIMARY KEY: unique identifier, not null, indexed",
    "  FOREIGN KEY: references another table — DB enforces referential integrity",
    "  UNIQUE:      no two rows can have same value",
    "  NOT NULL:    column required",
    "  CHECK:       custom validation rule",
    "  DEFAULT:     value if not specified on insert",
    "",
    "DATA TYPES (PostgreSQL examples):",
    "  INTEGER, BIGINT, SMALLINT, SERIAL (auto-incrementing int)",
    "  TEXT, VARCHAR(n), CHAR(n)",
    "  DECIMAL(p, s), NUMERIC, REAL, DOUBLE PRECISION",
    "  BOOLEAN",
    "  DATE, TIME, TIMESTAMP, TIMESTAMPTZ (with timezone)",
    "  UUID, JSON, JSONB, ARRAY",
    "  BYTEA (binary)",
    "```",
    "",
    "---",
    "",
    "## Indexes — How Lookups Get Fast",
    "",
    "```",
    "WITHOUT INDEX:",
    "  SELECT * FROM users WHERE email = 'alice@example.com';",
    "  → DB scans EVERY row checking emails. O(n) — slow for big tables.",
    "",
    "WITH INDEX on email:",
    "  → DB walks a B-tree (~log n) to find row. O(log n).",
    "",
    "  For 1M users:",
    "  Without index: 1M comparisons (~100ms)",
    "  With index:    20 comparisons (~0.1ms) → 1000x faster!",
    "",
    "INDEX = a sorted data structure (B-tree typically) on one or more columns.",
    "  Stored separately from the table.",
    "  Updated automatically on INSERT/UPDATE/DELETE.",
    "",
    "WHEN TO INDEX:",
    "  Columns frequently in WHERE",
    "  Columns frequently in JOIN ON",
    "  Columns frequently in ORDER BY",
    "  Foreign keys (almost always)",
    "",
    "WHEN NOT TO INDEX:",
    "  Tiny tables (full scan is faster)",
    "  Columns with few distinct values (e.g. boolean) — index doesn't help much",
    "  Write-heavy tables — every index slows INSERT/UPDATE",
    "",
    "RULE OF THUMB: index any column you filter or join on. Profile slow queries with EXPLAIN.",
    "",
    "EXPLAIN — see how DB executes your query:",
    "  EXPLAIN ANALYZE SELECT * FROM users WHERE email = 'alice@example.com';",
    "  → Shows 'Index Scan' (good) or 'Seq Scan' (bad if table is large).",
    "```",
    "",
    "---",
    "",
    "## ACID Transactions",
    "",
    "ACID is the foundation of database trustworthiness:",
    "",
    "```",
    "ATOMICITY:",
    "  All-or-nothing. Either ALL changes commit, or NONE do.",
    "  Money transfer: deduct from A AND add to B — both happen, or neither.",
    "",
    "CONSISTENCY:",
    "  DB never violates rules (constraints, foreign keys, types).",
    "  Failed transaction rolls back; constraints prevent invalid states.",
    "",
    "ISOLATION:",
    "  Concurrent transactions don't interfere.",
    "  Reading half-applied data of another transaction = bad. Isolation prevents.",
    "  Levels: READ UNCOMMITTED (loosest), READ COMMITTED (default), ",
    "          REPEATABLE READ, SERIALIZABLE (strictest, slowest).",
    "",
    "DURABILITY:",
    "  Once committed, data survives crashes (written to disk).",
    "  Power outage right after COMMIT? Data is safe.",
    "",
    "EXAMPLE TRANSACTION:",
    "  BEGIN;",
    "    UPDATE accounts SET balance = balance - 100 WHERE id = 1;",
    "    UPDATE accounts SET balance = balance + 100 WHERE id = 2;",
    "    -- if any error, ROLLBACK auto",
    "  COMMIT;",
    "",
    "  If second UPDATE fails: BEGIN..ROLLBACK undoes the first too.",
    "  No partial state ever seen by other transactions.",
    "```",
    "",
    "---",
    "",
    "## Normalisation — Avoiding Duplicate Data",
    "",
    "```",
    "BAD (denormalised — redundant data):",
    "  orders:",
    "  +─────+─────────────+──────────────────+─────────+",
    "  │ id  │ user_name   │ user_email       │ amount  │",
    "  +─────+─────────────+──────────────────+─────────+",
    "  │ 100 │ Alice       │ alice@example.com│ 49.99   │",
    "  │ 101 │ Alice       │ alice@example.com│ 19.99   │",
    "  +─────+─────────────+──────────────────+─────────+",
    "",
    "  Problems:",
    "  - Alice's email stored twice → 'update email' must update many rows",
    "  - Easy for data to get inconsistent",
    "  - Wastes storage",
    "",
    "GOOD (normalised — split into related tables):",
    "  users:",
    "  +────+───────+──────────────────+",
    "  │ id │ name  │ email            │",
    "  +────+───────+──────────────────+",
    "  │ 1  │ Alice │ alice@example.com│",
    "  +────+───────+──────────────────+",
    "",
    "  orders:",
    "  +─────+─────────+─────────+",
    "  │ id  │ user_id │ amount  │",
    "  +─────+─────────+─────────+",
    "  │ 100 │ 1       │ 49.99   │",
    "  │ 101 │ 1       │ 19.99   │",
    "  +─────+─────────+─────────+",
    "",
    "  Update email once. JOIN to combine when needed.",
    "",
    "NORMAL FORMS (informally):",
    "  1NF: no repeating groups, each cell is atomic (no comma-separated lists in a column)",
    "  2NF: no partial dependencies (every non-key column depends on the FULL primary key)",
    "  3NF: no transitive dependencies (non-key columns don't depend on other non-key)",
    "",
    "  Most production schemas aim for 3NF.",
    "  Sometimes denormalise for read performance (caching computed totals).",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "RELATIONAL DATABASES & SQL",
    "|",
    "+-- BASIC STRUCTURE",
    "|   +-- Tables (rows, columns)",
    "|   +-- Primary keys (unique row id)",
    "|   +-- Foreign keys (relationships)",
    "|   +-- Constraints (NOT NULL, UNIQUE, CHECK)",
    "|",
    "+-- SQL OPERATIONS (CRUD)",
    "|   +-- SELECT (read)",
    "|   +-- INSERT (create)",
    "|   +-- UPDATE (modify)",
    "|   +-- DELETE (remove)",
    "|",
    "+-- QUERYING",
    "|   +-- WHERE (filter rows)",
    "|   +-- ORDER BY (sort)",
    "|   +-- GROUP BY (aggregate)",
    "|   +-- HAVING (filter groups)",
    "|   +-- LIMIT/OFFSET (paginate)",
    "|   +-- JOINs (INNER, LEFT, RIGHT, FULL)",
    "|",
    "+-- INDEXES",
    "|   +-- Speed up lookups (B-tree)",
    "|   +-- Slow down writes",
    "|   +-- EXPLAIN to verify usage",
    "|",
    "+-- ACID TRANSACTIONS",
    "|   +-- Atomicity (all or nothing)",
    "|   +-- Consistency (constraints upheld)",
    "|   +-- Isolation (concurrent safety)",
    "|   +-- Durability (survives crash)",
    "|",
    "+-- SCHEMA DESIGN",
    "    +-- Normalisation (1NF, 2NF, 3NF)",
    "    +-- Avoid duplication",
    "    +-- Sometimes denormalise for speed",
    "```",
    "",
    "---",
    "",
    "## How SQL Connects to Other Topics",
    "",
    "- **Big-O**: queries with indexes are O(log n); without are O(n). Same thinking.",
    "- **System Design**: master-replica, sharding, partitioning all build on relational basics.",
    "- **NoSQL**: understand SQL first; NoSQL is about trade-offs against this base.",
    "- **Java/Spring**: JPA/Hibernate translate Java objects to SQL queries. Knowing SQL helps debug performance.",
    "",
    "---",
    "",
    "## Common Beginner Mistakes",
    "",
    "1. **UPDATE/DELETE without WHERE** — modifies/deletes ALL rows. Always preview with SELECT first.",
    "2. **N+1 query problem** — looping in app code, querying for each item. Use JOIN instead.",
    "3. **No indexes on foreign keys** — slow JOINs and CASCADE operations.",
    "4. **Wrong data type for money** — use DECIMAL(p,s), never FLOAT (rounding errors).",
    "5. **Storing dates as strings** — use TIMESTAMP/DATE types for proper comparison/sorting.",
    "6. **Comparing NULL with =** — use IS NULL/IS NOT NULL. NULL = NULL is NULL, not TRUE!",
    "7. **SELECT * in production** — fetches unnecessary columns; specify needed columns.",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **SQL Tutorial — Full Database Course for Beginners** by freeCodeCamp: https://www.youtube.com/watch?v=HXV3zeQKqGY",
    "- **Database Indexing Explained** by Hussein Nasser: https://www.youtube.com/watch?v=HubezKbFL7E",
    "",
    "### Articles",
    "- **Mode SQL Tutorial** (interactive): https://mode.com/sql-tutorial/",
    "- **SQLBolt** (interactive lessons): https://sqlbolt.com/",
    "- **Use The Index, Luke** (deep on indexing): https://use-the-index-luke.com/",
])

SQL_Q = [
    {"id":"sql-q1","type":"mcq","prompt":"What is a PRIMARY KEY in a relational database?",
     "choices":["The first column","A column (or set) that uniquely identifies each row — automatically NOT NULL and indexed","The largest column","Optional"],
     "answerIndex":1,"explanation":"Primary key uniquely identifies each row. Cannot be NULL. Cannot be duplicated. Automatically indexed for fast lookups. Conventionally an auto-incrementing 'id' integer or a UUID. Foundation of relational integrity — foreign keys reference primary keys.","tags":["sql","primary-key"]},
    {"id":"sql-q2","type":"mcq","prompt":"What does this query return?\n\nSELECT name, COUNT(*)\nFROM users\nGROUP BY name\nHAVING COUNT(*) > 1;",
     "choices":["All users","Names that appear more than once and how many times — useful for finding duplicates","Single random user","Compile error"],
     "answerIndex":1,"explanation":"GROUP BY name groups rows by name. COUNT(*) counts rows per group. HAVING filters groups (you cannot filter aggregates with WHERE). Result: only names appearing more than once. WHERE filters before grouping; HAVING filters after.","tags":["sql","group-by","having"]},
    {"id":"sql-q3","type":"mcq","prompt":"INNER JOIN vs LEFT JOIN — what's the difference?",
     "choices":["Identical","INNER JOIN: returns only rows with a match in BOTH tables. LEFT JOIN: returns ALL rows from left table, NULL for missing right side.","LEFT JOIN is faster","INNER JOIN is older"],
     "answerIndex":1,"explanation":"INNER JOIN: 'Alice has no orders' → Alice excluded from result. LEFT JOIN users LEFT JOIN orders: Alice included with NULL orders. Use LEFT when you want all of left even if no match. RIGHT JOIN: mirror of LEFT (rare). FULL OUTER: all from both, NULL where no match.","tags":["sql","joins"]},
    {"id":"sql-q4","type":"mcq","prompt":"Why is 'DELETE FROM users;' (no WHERE) dangerous?",
     "choices":["Slow performance","Deletes EVERY row in the users table — irreversible without backup. Always include WHERE, or use TRUNCATE for intentional full clear.","Compile error","Triggers a backup"],
     "answerIndex":1,"explanation":"Without WHERE, DELETE/UPDATE applies to entire table. Same disaster: 'UPDATE users SET active=false' deactivates everyone. Best practice: always write SELECT first to verify rows, THEN change to UPDATE/DELETE. Many DBs allow safe-update mode that requires WHERE.","tags":["sql","safety"]},
    {"id":"sql-q5","type":"mcq","prompt":"What does an INDEX on the 'email' column do?",
     "choices":["Forces uniqueness","Creates a separate sorted data structure (typically B-tree) so queries filtering by email run in O(log n) instead of O(n) full table scan","Slows queries","Compresses data"],
     "answerIndex":1,"explanation":"Index = sorted lookup structure. Email queries become O(log n). For 1M users: ~20 comparisons vs 1M without. Trade-off: indexes slow INSERT/UPDATE/DELETE (must update index too) and use disk space. Index columns used in WHERE, JOIN, ORDER BY.","tags":["sql","indexes"]},
    {"id":"sql-q6","type":"mcq","prompt":"What does ACID stand for in database transactions?",
     "choices":["A coding standard","Atomicity (all-or-nothing), Consistency (constraints upheld), Isolation (concurrent transactions don't interfere), Durability (survives crashes)","A backup format","Auth standard"],
     "answerIndex":1,"explanation":"ACID is foundational. Atomicity: BEGIN..COMMIT either both happen or neither. Consistency: constraints (FK, CHECK) always valid. Isolation: levels READ COMMITTED, REPEATABLE READ, SERIALIZABLE. Durability: COMMIT writes to durable storage. NoSQL often relaxes these for scale.","tags":["sql","acid","transactions"]},
    {"id":"sql-q7","type":"mcq","prompt":"What does a FOREIGN KEY do?",
     "choices":["Encrypts data","Establishes a referential link to another table's primary key — DB enforces that referenced row exists","Backs up automatically","Sorts the table"],
     "answerIndex":1,"explanation":"FOREIGN KEY (user_id) REFERENCES users(id): every order's user_id must match an existing user.id. DB rejects orphan inserts and can CASCADE deletes. Maintains referential integrity. Always index foreign keys (DB doesn't always do this automatically).","tags":["sql","foreign-key"]},
    {"id":"sql-q8","type":"mcq","prompt":"What's wrong with: WHERE email = NULL?",
     "choices":["Nothing","NULL comparisons with = always return NULL (treated as not-true), so this matches no rows. Use 'IS NULL' instead.","Returns all rows","Compile error"],
     "answerIndex":1,"explanation":"NULL means 'unknown'. NULL = NULL is NULL (not TRUE). NULL = anything is NULL. Use 'WHERE email IS NULL' or 'IS NOT NULL'. Subtle source of bugs — query returns empty result silently. Three-valued logic in SQL: TRUE, FALSE, UNKNOWN.","tags":["sql","null"]},
    {"id":"sql-q9","type":"mcq","prompt":"You have orders and need each user's total spending. Best query?",
     "choices":["SELECT * FROM orders ORDER BY user_id","SELECT user_id, SUM(amount) FROM orders GROUP BY user_id","SELECT * FROM orders WHERE amount > 0","SELECT COUNT(*) FROM orders"],
     "answerIndex":1,"explanation":"GROUP BY user_id buckets rows by user. SUM(amount) sums each bucket. Returns one row per user with their total. Add JOIN to users to get names. ORDER BY SUM(amount) DESC for top spenders. This is the canonical aggregation pattern.","tags":["sql","aggregation","group-by"]},
    {"id":"sql-q10","type":"mcq","prompt":"What is the N+1 query problem?",
     "choices":["Too many rows","Loop in application code that fires 1 query for the list, then 1 query per item — for 100 users, 101 queries total. Should be 1 query with JOIN.","Too few rows","An index issue"],
     "answerIndex":1,"explanation":"Classic ORM/lazy-load pitfall. Get 100 users (1 query). Loop accessing user.orders triggers 100 separate queries. 101 total = N+1. Fix: eager-fetch with JOIN, or batch (WHERE user_id IN (...)). Single biggest performance issue in many apps.","tags":["sql","performance","n-plus-one"]},
    {"id":"sql-q11","type":"mcq","prompt":"What data type should you use for money?",
     "choices":["FLOAT","DOUBLE","DECIMAL/NUMERIC with explicit precision (e.g. DECIMAL(10,2)) — exact arithmetic, no floating-point rounding errors","INTEGER"],
     "answerIndex":2,"explanation":"FLOAT/DOUBLE use binary floating-point: 0.1 + 0.2 = 0.30000000000000004. Catastrophic for money (off-by-cents in totals). DECIMAL stores exact decimal values: DECIMAL(10,2) = up to 10 digits, 2 after decimal. Some systems use INTEGER cents (multiply by 100) — also exact.","tags":["sql","types","money"]},
    {"id":"sql-q12","type":"mcq","prompt":"BEGIN; UPDATE A...; UPDATE B...; ROLLBACK; — what happened?",
     "choices":["A changed, B didn't","Both updates UNDONE — transaction rolled back. DB returned to pre-BEGIN state. This is atomicity in action.","Compile error","B changed, A didn't"],
     "answerIndex":1,"explanation":"BEGIN starts transaction. ROLLBACK reverses ALL changes since BEGIN. Atomic property: either all changes commit, or none take effect. Failure recovery: catch exception in code, ROLLBACK; report error. ROLLBACK after COMMIT does nothing — once committed, you need a compensating transaction.","tags":["transactions","rollback"]},
    {"id":"sql-q13","type":"mcq","prompt":"What is normalisation?",
     "choices":["Encryption","Organising data to eliminate redundancy by splitting tables linked by foreign keys — usually aiming for 3NF (no transitive dependencies)","Sorting rows","Indexing"],
     "answerIndex":1,"explanation":"Normalisation reduces duplication. Bad: storing user_email in every order row. Good: orders.user_id references users.id, email stored once in users. Updates affect one row. Normal forms: 1NF (atomic columns), 2NF (no partial deps on composite key), 3NF (no transitive deps). Sometimes denormalise for read performance.","tags":["sql","normalisation"]},
    {"id":"sql-q14","type":"multi","prompt":"Which query results are slow without an index? (Select all)",
     "choices":["SELECT * FROM users WHERE email = 'a@b.com'","SELECT * FROM orders WHERE user_id = 42","SELECT * FROM users","SELECT name FROM users WHERE id = 1"],
     "answerIndexes":[0,1],"explanation":"WHERE on non-indexed column = full table scan O(n). Both filtering by email and user_id need index for speed. SELECT * (no filter) reads everything regardless. Filter by primary key (id) — already indexed (PK auto-indexed) so #4 is fast.","tags":["sql","indexes","performance"]},
    {"id":"sql-q15","type":"mcq","prompt":"What does EXPLAIN do?",
     "choices":["Documents the query","Shows the DB's execution plan: which indexes used, scan types, estimated cost — for query optimisation","Runs query slower","Adds indexes"],
     "answerIndex":1,"explanation":"EXPLAIN shows how DB will execute query. Look for: 'Seq Scan' (full table scan, slow), 'Index Scan' (uses index, fast), 'Hash Join' vs 'Nested Loop'. EXPLAIN ANALYZE actually runs the query and shows real timing. Essential for diagnosing slow queries.","tags":["sql","explain","optimisation"]},
    {"id":"sql-q16","type":"mcq","prompt":"Why use parameterised queries / prepared statements?",
     "choices":["Looks pretty","SECURITY: prevents SQL injection. User input is sent as parameter, never concatenated into the SQL string — DB treats it as data, not code.","Faster","Required by JDBC"],
     "answerIndex":1,"explanation":"SQL injection: user enters 'admin'; DROP TABLE users; --' as username. Concatenation builds malicious query. Parameterised: 'WHERE name = ?' with bound parameter — DB treats input as VALUE, never as SQL. Always use ? placeholders or PreparedStatement in Java/JDBC.","tags":["sql","security","injection"]},
    {"id":"sql-q17","type":"mcq","prompt":"What's the difference between TRUNCATE and DELETE without WHERE?",
     "choices":["Same","TRUNCATE: fast (drops table data, resets auto-increment), can't be in transaction (in some DBs), no row triggers fire. DELETE: row-by-row, transactional, triggers fire — slower for large tables.","TRUNCATE keeps schema","TRUNCATE is for backups"],
     "answerIndex":1,"explanation":"TRUNCATE: instant (deallocates pages), resets identity counters, lighter on log. Can't ROLLBACK in some DBs. DELETE: per-row processing, full transactional support, trigger firing per row, much slower for large tables. Both empty the table, keep schema. Choose based on context.","tags":["sql","truncate","delete"]},
    {"id":"sql-q18","type":"mcq","prompt":"What is a transaction isolation level READ COMMITTED?",
     "choices":["No isolation","Default in many DBs: a query reads only data committed by other transactions before this query starts. Prevents dirty reads (seeing uncommitted changes).","Highest isolation","Lowest isolation"],
     "answerIndex":1,"explanation":"READ COMMITTED: each statement sees committed data. Prevents dirty reads. But: same query in same transaction can return different rows if another tx commits between (non-repeatable read). Stricter: REPEATABLE READ (snapshot at tx start). SERIALIZABLE: full isolation, slowest.","tags":["sql","isolation","transactions"]},
    {"id":"sql-q19","type":"mcq","prompt":"What's wrong with `SELECT *` in production code?",
     "choices":["Always wrong","Fetches all columns even if you only need a few — wastes network/memory; breaks if schema adds columns; less explicit; and prevents covering-index optimisations.","Slow only","No issue"],
     "answerIndex":1,"explanation":"SELECT * is convenient in ad-hoc queries but wastes bandwidth and resources. SELECT name, email is explicit and faster. Schema changes adding columns silently shift downstream code. Use specific columns in production code; SELECT * only for exploration.","tags":["sql","best-practices"]},
    {"id":"sql-q20","type":"mcq","prompt":"For pagination of 1000+ rows, why is OFFSET inefficient at high pages?",
     "choices":["No issue","DB must SCAN and skip OFFSET rows before returning the page — page 1000 of 100 means scanning 100,000 rows. Better: keyset pagination using WHERE id > last_id LIMIT N.","OFFSET is fastest","SQL bug"],
     "answerIndex":1,"explanation":"OFFSET 100000 LIMIT 100: DB reads 100,100 rows, discards first 100,000. Slow for deep pages. Keyset (cursor) pagination: WHERE id > last_seen_id ORDER BY id LIMIT 100 — DB jumps directly via index, O(log n) regardless of page number. Use for infinite scroll.","tags":["sql","pagination","performance"]},
]

SQL_FC = [
    {"id":"sql-fc1","front":"SELECT clause execution order","back":"Logical order: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT. Knowing this explains why aliases in SELECT can't be used in WHERE (computed after). HAVING filters groups, WHERE filters rows.","tags":["sql","ordering"]},
    {"id":"sql-fc2","front":"JOIN types quick reference","back":"INNER JOIN: only matches in both. LEFT JOIN: all from left + matching right (NULL if no match). RIGHT JOIN: mirror (rare). FULL OUTER: all rows from both. CROSS JOIN: cartesian product (avoid unless intentional).","tags":["sql","joins"]},
    {"id":"sql-fc3","front":"Index trade-offs","back":"Speeds reads (WHERE, JOIN, ORDER BY). Slows writes (every INSERT/UPDATE/DELETE updates indexes). Costs disk space. Rule: index columns frequently filtered on, especially foreign keys. Profile slow queries with EXPLAIN ANALYZE.","tags":["sql","indexes"]},
    {"id":"sql-fc4","front":"ACID summary","back":"Atomicity (all-or-nothing), Consistency (constraints upheld), Isolation (concurrent transactions don't see each other's incomplete state), Durability (commit survives crash). Foundation of trustworthy DBs. NoSQL often trades these for scale.","tags":["sql","acid"]},
    {"id":"sql-fc5","front":"NULL handling","back":"NULL means unknown. NULL = NULL is NULL, not TRUE! Use IS NULL / IS NOT NULL. NULL in arithmetic returns NULL. In aggregates: COUNT(col) skips NULLs, COUNT(*) counts all rows. ORDER BY: NULLs first/last varies by DB.","tags":["sql","null"]},
    {"id":"sql-fc6","front":"N+1 query problem and fix","back":"Loop fetching list (1 query) then per-item details (N queries) = N+1 total. Fix: 1) JOIN to fetch all in single query. 2) Batch with WHERE id IN (...). 3) ORM eager-fetch hint. Always check ORM-generated SQL in development.","tags":["sql","performance"]},
    {"id":"sql-fc7","front":"Use parameterised queries","back":"NEVER concatenate user input into SQL — SQL injection risk. Use ? placeholders or PreparedStatement. DB treats parameter as VALUE not CODE. 'WHERE name = ?' bound to user input. OWASP top web security risk historically.","tags":["sql","security"]},
    {"id":"sql-fc8","front":"Money — use DECIMAL not FLOAT","back":"FLOAT/DOUBLE = binary floating-point. Sum of cents accumulates errors. Use DECIMAL(p,s): DECIMAL(10,2) for max 10 digits with 2 decimal. Or store as INTEGER cents (× 100). Exact arithmetic guaranteed.","tags":["sql","types","money"]},
]

SQL_PROJ = {
    "brief": "Design the SQL schema for a simple e-commerce site: users, products, orders, order_items. Include: appropriate primary keys, foreign keys, indexes, constraints, and at least 5 SELECT queries that solve real business questions (top customers, monthly revenue, etc.).",
    "checklist": [
        {"id":"s1","text":"Tables with PRIMARY KEY (SERIAL/UUID), FOREIGN KEY constraints (orders.user_id REFERENCES users), NOT NULL where appropriate, DECIMAL(10,2) for prices, TIMESTAMPTZ DEFAULT NOW() for timestamps.","weight":20},
        {"id":"s2","text":"Indexes on foreign keys (orders.user_id), commonly-filtered columns (orders.created_at for reports), unique constraint on users.email.","weight":20},
        {"id":"s3","text":"Top 10 customers by total spent: SELECT u.name, SUM(oi.price * oi.qty) total FROM users u JOIN orders o ON o.user_id = u.id JOIN order_items oi ON oi.order_id = o.id GROUP BY u.id, u.name ORDER BY total DESC LIMIT 10.","weight":20},
        {"id":"s4","text":"Monthly revenue: SELECT date_trunc('month', created_at) AS month, SUM(amount) FROM orders GROUP BY month ORDER BY month. Add WHERE created_at > NOW() - INTERVAL '12 months' for last year.","weight":20},
        {"id":"s5","text":"Out-of-stock products: SELECT * FROM products WHERE stock = 0. Trending: products with most orders in last 30 days using JOIN + GROUP BY + ORDER BY count.","weight":20},
    ],
    "hints": [
        "order_items is a join table linking orders ↔ products with quantity/price snapshot. PK = (order_id, product_id) composite or separate id. Always FK both columns.",
        "Snapshot price in order_items at purchase time — products.price changes over time. Without snapshot, old orders show wrong totals.",
        "For analytics queries on millions of orders: consider partitioning orders by created_at month, materialised views for monthly summaries, and read replicas to keep analytics off primary.",
    ]
}

write("relational-databases-sql.json", {
    "id": "relational-databases-sql",
    "unit": 1,
    "order": 5,
    "title": "Relational Databases & SQL",
    "summary": "Tables, queries, joins, transactions, indexes, normalisation, and the ACID guarantees that make databases trustworthy.",
    "prereqs": ["pointers-references"],
    "guide": SQL_GUIDE,
    "questions": SQL_Q,
    "flashcards": SQL_FC,
    "project": SQL_PROJ,
})


# ── EMBEDDED DATABASES ────────────────────────────────────────────────────────

EMBED_GUIDE = "\n".join([
    "# Embedded Databases — SQLite, RocksDB, LevelDB",
    "",
    "## What Is an Embedded Database?",
    "",
    "An embedded database **runs INSIDE your application process**, not as a separate server.",
    "Your app links the DB as a library and reads/writes data via in-process function calls.",
    "No network. No socket. No daemon. No DBA.",
    "",
    "```",
    "TRADITIONAL CLIENT-SERVER DATABASE:",
    "                                                              ",
    "  +─────────────+    network/socket   +──────────────+        ",
    "  │  Your App   │ ─────────────────►  │  Postgres    │        ",
    "  │ (process A) │ ◄─────────────────  │  (process B) │        ",
    "  +─────────────+                     +──────────────+        ",
    "                                       runs separately,        ",
    "                                       can be on another       ",
    "                                       machine                 ",
    "",
    "EMBEDDED DATABASE:",
    "                                                              ",
    "  +────────────────────────────────────+                     ",
    "  │  Your App                          │                     ",
    "  │  ┌──────────────────────────────┐  │                     ",
    "  │  │  SQLite library (linked)     │  │                     ",
    "  │  │  reads/writes local file     │  │                     ",
    "  │  └──────────┬───────────────────┘  │                     ",
    "  │             │ direct file I/O       │                     ",
    "  └─────────────┼───────────────────────+                     ",
    "                ▼                                              ",
    "         data.db (single file on disk)                         ",
    "```",
    "",
    "**Why use embedded?**",
    "- No separate server process to manage",
    "- Zero-config: just a file",
    "- Faster than network DB for small/single-user apps (no IPC overhead)",
    "- Perfect for: mobile apps, desktop apps, IoT, CLI tools, browser apps, tests",
    "",
    "**Real-world examples (you've used these without knowing!):**",
    "- iOS/Android apps: SQLite stores your contacts, photos, app settings",
    "- Firefox/Chrome: SQLite stores history, cookies, bookmarks",
    "- Skype, WhatsApp: SQLite for message storage",
    "- Adobe Lightroom: SQLite catalog",
    "- Cassandra, RocksDB-based stores: RocksDB as storage engine",
    "",
    "---",
    "",
    "## SQLite — The Embedded SQL Database",
    "",
    "SQLite is a C library that implements a **full SQL database in a single file**.",
    "It's the most-deployed database in the world (in every smartphone, every Mac, every browser).",
    "",
    "```",
    "FEATURES:",
    "  Full SQL support (SELECT, JOIN, transactions, indexes)",
    "  ACID-compliant transactions",
    "  Cross-platform (any OS that has files)",
    "  Single file = your entire database",
    "  Tiny (~600KB compiled)",
    "  Public domain (no license)",
    "",
    "USAGE PATTERN:",
    "  1. Link SQLite library into your app",
    "  2. Open a file as your DB: sqlite3.open('data.db')",
    "  3. Run SQL queries through the API",
    "  4. SQLite reads/writes the file as needed",
    "",
    "JAVA EXAMPLE (using sqlite-jdbc):",
    "  Class.forName(\"org.sqlite.JDBC\");",
    "  Connection conn = DriverManager.getConnection(\"jdbc:sqlite:data.db\");",
    "  Statement stmt = conn.createStatement();",
    "  stmt.execute(\"CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT)\");",
    "  stmt.execute(\"INSERT INTO users (name) VALUES ('Alice')\");",
    "  ResultSet rs = stmt.executeQuery(\"SELECT * FROM users\");",
    "  while (rs.next()) {",
    "      System.out.println(rs.getInt(\"id\") + \" \" + rs.getString(\"name\"));",
    "  }",
    "  conn.close();",
    "",
    "PYTHON EXAMPLE (built into stdlib):",
    "  import sqlite3",
    "  conn = sqlite3.connect('data.db')",
    "  c = conn.cursor()",
    "  c.execute('CREATE TABLE IF NOT EXISTS users (id INTEGER, name TEXT)')",
    "  c.execute('INSERT INTO users VALUES (1, ?)', ('Alice',))",
    "  conn.commit()",
    "  for row in c.execute('SELECT * FROM users'):",
    "      print(row)",
    "  conn.close()",
    "```",
    "",
    "**Limitations of SQLite:**",
    "",
    "```",
    "Concurrency: Only ONE writer at a time (database-level lock).",
    "             Many readers OK in WAL mode.",
    "Network:     No client-server. Multiple processes via filesystem only — risky.",
    "Scale:       Designed for ~hundreds of GB max, single-user/single-app.",
    "Features:    Lacks some advanced SQL (no native UUID, limited JSON ops, no",
    "             full-text-search by default, weak type system — TEXT can hold int).",
    "",
    "RULE: SQLite is excellent for embedded local data. Not a server-grade DB.",
    "```",
    "",
    "---",
    "",
    "## RocksDB — The Embedded Key-Value Store",
    "",
    "RocksDB is a high-performance **embedded key-value store** by Facebook (now Meta).",
    "Originally a fork of Google's LevelDB, optimised for SSDs and large datasets.",
    "",
    "```",
    "WHAT IT IS:",
    "  Library, not a server.",
    "  Stores key-value pairs (both bytes).",
    "  No SQL, no schema, no joins — JUST get/put/delete by key.",
    "  Optimised for write-heavy workloads.",
    "",
    "ARCHITECTURE — LSM TREE (Log-Structured Merge Tree):",
    "",
    "  Writes go to:                                           ",
    "    1. MemTable (in-memory sorted table) — fast            ",
    "    2. WAL (Write-Ahead Log) — durability                  ",
    "                                                            ",
    "  When MemTable fills:                                      ",
    "    Flushed to disk as immutable SSTable (Sorted String Table)",
    "                                                            ",
    "  Background compaction merges SSTables to reduce overlap.",
    "  Read path: check MemTable, then SSTables newest-first until found.",
    "",
    "  +───────────────────+",
    "  │   MemTable (RAM)  │  ← writes here",
    "  +─────────┬─────────+",
    "            │ flush",
    "            ▼",
    "  +───────────────────+",
    "  │   SSTable L0      │",
    "  +───────────────────+",
    "  │   SSTable L0      │",
    "  +───────────────────+",
    "       compact",
    "  +───────────────────+",
    "  │   SSTable L1      │  ← merged, sorted, larger",
    "  +───────────────────+",
    "  │   SSTable L2      │  ← yet larger, less recent",
    "  +───────────────────+",
    "",
    "BENEFITS:",
    "  Very fast writes (sequential, append-only)",
    "  Compresses well (sorted runs)",
    "  Scales to TBs on a single node",
    "",
    "TRADE-OFFS vs B-tree (SQLite):",
    "  Write amplification (compaction rewrites data)",
    "  Reads can hit multiple files",
    "  More complex internally",
    "",
    "USE CASES:",
    "  Storage engine for many DBs: Cassandra, CockroachDB, Yugabyte, MyRocks",
    "  Time-series (lots of writes, mostly recent reads)",
    "  Embedded caches needing persistence",
    "  Apache Kafka uses RocksDB for state stores in Kafka Streams",
    "",
    "JAVA EXAMPLE (using rocksdbjni):",
    "  Options options = new Options().setCreateIfMissing(true);",
    "  RocksDB db = RocksDB.open(options, \"/path/to/db\");",
    "  db.put(\"key1\".getBytes(), \"value1\".getBytes());",
    "  byte[] value = db.get(\"key1\".getBytes());",
    "  db.delete(\"key1\".getBytes());",
    "  db.close();",
    "```",
    "",
    "---",
    "",
    "## SQLite vs RocksDB — When to Use Which",
    "",
    "```",
    "+──────────────────────+──────────────────────+──────────────────────+",
    "│ Feature              │ SQLite               │ RocksDB              │",
    "+──────────────────────+──────────────────────+──────────────────────+",
    "│ Data model           │ Relational (SQL)     │ Key-Value            │",
    "│ Schema               │ Yes (tables)         │ No (just bytes)      │",
    "│ Query language       │ SQL                  │ get/put/delete/scan  │",
    "│ ACID                 │ Yes                  │ Yes (per-batch)      │",
    "│ Joins                │ Yes                  │ No (do in app)       │",
    "│ Indexes              │ Auto + manual        │ Sort order = primary │",
    "│ Storage engine       │ B-tree               │ LSM tree             │",
    "│ Best for             │ Mixed read/write SQL │ Heavy writes, KV     │",
    "│ Size cap             │ ~140 TB (hard), few GB practical │ TBs scale│",
    "│ Concurrent writers   │ One                  │ One (per-CF)         │",
    "│ Single file          │ Yes                  │ Directory of files   │",
    "│ Typical use          │ App local DB, mobile │ DB storage engine,   │",
    "│                      │ apps, browser, tests │ analytics, streaming │",
    "+──────────────────────+──────────────────────+──────────────────────+",
    "",
    "RULE OF THUMB:",
    "  Need SQL/relational? → SQLite",
    "  Need raw KV speed at scale? → RocksDB",
    "  Need both? → Use SQLite for app data, embed RocksDB for caches/streams",
    "```",
    "",
    "---",
    "",
    "## Other Embedded Databases",
    "",
    "```",
    "LEVELDB (Google):",
    "  Predecessor of RocksDB. Simpler, smaller, less optimised.",
    "  Used by Bitcoin Core, Chromium IndexedDB.",
    "",
    "BERKELEY DB (Oracle):",
    "  Old-school embedded KV. Ubiquitous in legacy Unix software.",
    "  Multiple flavours: BTree, Hash, Queue, Recno.",
    "",
    "DUCKDB:",
    "  Modern embedded analytical DB ('SQLite for analytics').",
    "  Column-store, designed for OLAP — fast on analytical queries over millions of rows.",
    "  Pandas users love it: directly query Parquet files via SQL.",
    "",
    "H2 (Java):",
    "  Pure-Java embedded SQL database. Used heavily in Java integration tests.",
    "  Can run in-memory (no file at all) for blazing-fast unit tests.",
    "",
    "BADGER (Go):",
    "  LSM-based KV store written in pure Go. Used by Dgraph.",
    "",
    "BOLTDB (Go):",
    "  B-tree based KV store, ACID. Used by etcd until v3 (now bbolt fork).",
    "",
    "EMBEDDED VECTOR DATABASES (newer, AI-related):",
    "  ChromaDB, FAISS — for embedding/vector storage in RAG systems.",
    "```",
    "",
    "---",
    "",
    "## When to Use Embedded vs Client-Server DB",
    "",
    "```",
    "USE EMBEDDED WHEN:",
    "  ✓ Single-user app (mobile, desktop)",
    "  ✓ App needs to work fully offline",
    "  ✓ Don't want server ops burden",
    "  ✓ Data doesn't need to be shared between processes/machines",
    "  ✓ Tests (in-memory SQLite/H2 for fast unit tests)",
    "  ✓ CLI tools, IDEs, build tools (caching local state)",
    "",
    "USE CLIENT-SERVER WHEN:",
    "  ✓ Multiple apps/services need same data",
    "  ✓ Concurrent writes from many clients",
    "  ✓ Multi-machine deployment (cloud)",
    "  ✓ Need DBA tools, replication, backup automation",
    "  ✓ Data exceeds single-machine capacity",
    "  ✓ Production web app at scale",
    "",
    "HYBRID PATTERNS:",
    "  Mobile app: SQLite locally + sync to PostgreSQL backend",
    "  Web app: PostgreSQL primary + SQLite for ephemeral session/cache state",
    "  Distributed DB: each node uses RocksDB internally; nodes coordinate via network",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "EMBEDDED DATABASES",
    "|",
    "+-- DEFINITION",
    "|   +-- Library inside your process",
    "|   +-- No separate server",
    "|   +-- Direct file I/O",
    "|",
    "+-- SQLITE",
    "|   +-- Full SQL + ACID",
    "|   +-- Single file",
    "|   +-- B-tree storage",
    "|   +-- Mobile, browser, tests",
    "|   +-- One writer at a time",
    "|",
    "+-- ROCKSDB",
    "|   +-- Key-Value only",
    "|   +-- LSM tree storage",
    "|   +-- Write-optimised",
    "|   +-- Storage engine for distributed DBs",
    "|   +-- TB-scale single node",
    "|",
    "+-- LEVELDB / BADGER / BOLTDB",
    "|   +-- Other KV stores",
    "|   +-- Different language ecosystems",
    "|",
    "+-- DUCKDB",
    "|   +-- Embedded analytical",
    "|   +-- Column-store",
    "|   +-- 'SQLite for OLAP'",
    "|",
    "+-- USE CASES",
    "|   +-- Mobile apps (SQLite)",
    "|   +-- Browser storage",
    "|   +-- Test suites (in-memory)",
    "|   +-- Local caches",
    "|   +-- DB storage engines",
    "|",
    "+-- CONTRAST CLIENT-SERVER",
    "    +-- SQLite ≠ PostgreSQL replacement",
    "    +-- Multi-process writes need server",
    "    +-- Single-user/single-process = embedded",
    "```",
    "",
    "---",
    "",
    "## How Embedded DBs Connect to Other Topics",
    "",
    "- **SQL fundamentals**: SQLite gives you SQL learning with zero setup",
    "- **Java testing**: H2 in-memory DB for fast unit/integration tests",
    "- **Distributed databases**: Cassandra, CockroachDB, Yugabyte all use RocksDB internally",
    "- **Mobile development**: SQLite is THE local persistence on iOS/Android",
    "- **Browser**: IndexedDB and origin-private SQLite (OPFS) for offline web apps",
    "- **Kafka Streams**: state stores backed by RocksDB",
    "",
    "---",
    "",
    "## Common Beginner Mistakes",
    "",
    "1. **Treating SQLite like Postgres** — it's not for multi-process writes; concurrent writers will block",
    "2. **No backups** — single file is easy to copy; not doing it = data loss",
    "3. **Storing huge BLOBs in SQLite** — works but degrades performance; consider files + SQLite metadata",
    "4. **Ignoring WAL mode** — default rollback-journal mode has worse concurrency; PRAGMA journal_mode=WAL",
    "5. **Using SQLite over network filesystem** — corruption risk; only on local disks",
    "6. **Choosing RocksDB when SQLite would do** — SQL is easier when you need queries; KV is overkill",
    "7. **Forgetting embedded DB needs migration scripts** — schema changes still apply",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **SQLite Explained** by Hussein Nasser: https://www.youtube.com/watch?v=Jib2AmRb_rk",
    "- **RocksDB and LSM Trees** by Facebook Engineering: https://www.youtube.com/watch?v=jGCv4r8CJEI",
    "",
    "### Articles",
    "- **SQLite Documentation**: https://www.sqlite.org/docs.html",
    "- **SQLite: When to use** (official): https://www.sqlite.org/whentouse.html",
    "- **RocksDB Wiki**: https://github.com/facebook/rocksdb/wiki",
    "- **DuckDB intro**: https://duckdb.org/why_duckdb",
])

EMBED_Q = [
    {"id":"emb-q1","type":"mcq","prompt":"What defines an 'embedded' database?",
     "choices":["A database with mobile support","Runs INSIDE the application process as a library — not a separate server. Direct file I/O, no network or socket.","Encrypted DB","Cloud-only DB"],
     "answerIndex":1,"explanation":"Embedded DB is a library you link into your app. SQLite, RocksDB, H2, LevelDB. Same process, in-process function calls instead of network round trips. Examples: every iOS/Android app uses SQLite. Browser uses SQLite for history. Vs Postgres which runs as separate server.","tags":["embedded","fundamentals"]},
    {"id":"emb-q2","type":"mcq","prompt":"What is SQLite?",
     "choices":["A NoSQL database","A C library implementing a full SQL database in a SINGLE FILE — most-deployed DB in the world (every phone, every browser)","A cloud service","A backup format"],
     "answerIndex":1,"explanation":"SQLite is the most widely-deployed DB ever. ~600KB library, public domain. Full SQL + ACID. Single file = entire database. Used by: iOS, Android, Mac, Windows, Firefox, Chrome, Skype, every Adobe product, etc. Perfect for: app local data, tests, single-user systems.","tags":["sqlite"]},
    {"id":"emb-q3","type":"mcq","prompt":"What is the main concurrency limitation of SQLite?",
     "choices":["No concurrency","Single writer at a time (database-level lock); many readers OK in WAL mode. Multiple processes writing concurrently will queue/block.","Only 5 connections","Read-only"],
     "answerIndex":1,"explanation":"SQLite serialises writes via file lock. Default rollback-journal: writers block readers too. WAL mode (PRAGMA journal_mode=WAL): readers don't block writers, but still only 1 writer. For many concurrent writers, use a server DB (Postgres, MySQL).","tags":["sqlite","concurrency"]},
    {"id":"emb-q4","type":"mcq","prompt":"What is RocksDB?",
     "choices":["A SQL DB","An embedded high-performance KEY-VALUE store. LSM-tree storage. Optimised for write-heavy workloads on SSDs. Storage engine for many distributed DBs.","Cloud DB","Browser API"],
     "answerIndex":1,"explanation":"RocksDB is Meta's embedded KV store, fork of Google's LevelDB. No SQL, no schema, just byte-key-byte-value. LSM tree internals make writes very fast. Used as storage engine in: Cassandra, CockroachDB, Yugabyte, MyRocks, Kafka Streams state stores.","tags":["rocksdb"]},
    {"id":"emb-q5","type":"mcq","prompt":"What is an LSM tree?",
     "choices":["A B-tree","Log-Structured Merge tree: writes go to in-memory MemTable + WAL, then flush to immutable sorted SSTables on disk; background compaction merges them. Optimised for fast sequential writes.","Linked list","Tree of indexes"],
     "answerIndex":1,"explanation":"LSM tree: writes are sequential (fast on SSD/HDD). MemTable in RAM, WAL for durability, periodic flush to immutable SSTable files. Background compaction merges/dedupes. Reads: check MemTable then SSTables newest-first. Trade-off: write amplification but very fast sustained writes. Powers RocksDB, Cassandra, ScyllaDB.","tags":["lsm","storage"]},
    {"id":"emb-q6","type":"mcq","prompt":"When should you choose SQLite over PostgreSQL?",
     "choices":["Never","Single-user/single-process apps (mobile, desktop, CLI tools), unit tests (in-memory), embedded scenarios where you want zero server ops. NOT for multi-user web apps at scale.","Always","Only for SQL queries"],
     "answerIndex":1,"explanation":"SQLite excels: mobile apps, desktop apps, CLI tools, browser storage, fast unit tests. Postgres excels: multi-client web apps, concurrent writers, multi-machine, big production. Wrong tool: putting SQLite behind a high-traffic web service — concurrent writes block each other.","tags":["sqlite","when-to-use"]},
    {"id":"emb-q7","type":"mcq","prompt":"What are SSTables in RocksDB/LSM trees?",
     "choices":["Schema tables","Sorted String Tables: immutable on-disk files, sorted by key. Once written, never modified. Compaction merges multiple SSTables into new ones, deleting old.","Stack tables","Cache layer"],
     "answerIndex":1,"explanation":"SSTable: immutable file holding sorted key-value pairs. Memtable flushes become Level-0 SSTables. Background compaction merges them into Level-1, etc. Immutability means: easy to compress, no in-place writes, simpler concurrency. Reads may need to check multiple SSTables (Bloom filters help skip).","tags":["rocksdb","sstable"]},
    {"id":"emb-q8","type":"mcq","prompt":"What is H2 database commonly used for in Java projects?",
     "choices":["Production","Pure-Java embedded SQL DB; widely used for fast unit/integration tests in IN-MEMORY mode (jdbc:h2:mem:testdb) — starts in milliseconds, no file IO.","Java applet support","Object storage"],
     "answerIndex":1,"explanation":"H2: Java implementation of SQL DB. Embedded mode (file or in-memory). Spring Boot's default test DB. In-memory: 'jdbc:h2:mem:testdb' starts fresh each test run, blazing fast. Caveat: SQL dialect differs slightly from production (Postgres, MySQL) — use Testcontainers for production parity.","tags":["h2","testing"]},
    {"id":"emb-q9","type":"mcq","prompt":"What is DuckDB?",
     "choices":["Same as SQLite","Embedded ANALYTICAL DB ('SQLite for OLAP'): columnar storage, vectorised execution, optimised for aggregating millions of rows. Can directly query Parquet/CSV files via SQL.","NoSQL","Game engine"],
     "answerIndex":1,"explanation":"DuckDB is the analytical sibling of SQLite. Column-store (vs SQLite's row-store) makes scanning + aggregating columns very fast. Pandas/Python users: pd.read_sql('SELECT * FROM read_parquet(\"big.parquet\")', duckdb_conn). Modern ETL/analysis tool replacing many uses of Spark for medium-scale analytics.","tags":["duckdb","analytics"]},
    {"id":"emb-q10","type":"mcq","prompt":"Why is SQLite NOT recommended over network file systems (NFS, SMB)?",
     "choices":["Slow","File locking semantics differ between local FS and network FS — can cause database corruption or lost writes. SQLite docs explicitly warn against it.","Too modern","No reason"],
     "answerIndex":1,"explanation":"SQLite uses fcntl/POSIX file locks. Many network filesystems implement these incorrectly or partially. Two clients on NFS think they have exclusive lock simultaneously → concurrent writes → corruption. Always use SQLite on LOCAL disk only. For shared data, use a real DB server.","tags":["sqlite","networking"]},
    {"id":"emb-q11","type":"mcq","prompt":"What is the WAL (Write-Ahead Log) in SQLite?",
     "choices":["A backup","A separate file where new changes are appended; reads use the original DB file + WAL. Allows readers and writer to proceed without blocking each other.","File watcher","Web service"],
     "answerIndex":1,"explanation":"PRAGMA journal_mode=WAL. Writes go to WAL file. Periodically, WAL is checkpointed (merged into main DB file). Readers use a snapshot view of (main + WAL up to a point). Writer doesn't block readers. Better concurrency than default rollback-journal mode. Standard for production SQLite use.","tags":["sqlite","wal","concurrency"]},
    {"id":"emb-q12","type":"mcq","prompt":"What's the typical use of RocksDB in a distributed database like Cassandra?",
     "choices":["Network protocol","STORAGE ENGINE on each node — Cassandra coordinates network/replication, but each node uses RocksDB-like LSM internally to store/read its shard of data.","Backup tool","Query language"],
     "answerIndex":1,"explanation":"Distributed DBs separate concerns: networking/replication (Cassandra logic) and local storage (RocksDB or similar LSM). Each node uses embedded engine for its data files. Cassandra historically used its own LSM (similar to RocksDB), CockroachDB and Yugabyte literally use RocksDB. Embedded engine + distribution layer is a common pattern.","tags":["rocksdb","distributed"]},
    {"id":"emb-q13","type":"mcq","prompt":"What's a major TRADE-OFF of LSM trees vs B-trees?",
     "choices":["LSM is always better","WRITE AMPLIFICATION: compaction periodically rewrites data, so total bytes written to disk > bytes the user wrote. Trade for sequential writes + better compression vs B-tree's in-place updates.","B-tree is faster always","No difference"],
     "answerIndex":1,"explanation":"LSM: write user-data once to MemTable+WAL, then again on flush, then again on each compaction level. Total writes 5-10× user data = write amplification. Trade-off worth it on SSDs (sequential writes are very fast). B-tree: writes in place, lower amplification, but random I/O. Choose based on workload pattern.","tags":["lsm","tradeoffs"]},
    {"id":"emb-q14","type":"mcq","prompt":"What is the role of the WAL in RocksDB?",
     "choices":["For backups","Durability: every write is appended to WAL on disk before MemTable update. On crash, WAL is replayed to recover MemTable contents not yet flushed.","Backup","Network logging"],
     "answerIndex":1,"explanation":"Write order: 1) append to WAL, 2) update MemTable. On crash before flush: WAL replay rebuilds MemTable. Once MemTable is flushed to SSTable, the WAL portion can be discarded. WAL is similar concept across LSM systems and even traditional DBs (Postgres WAL, MySQL InnoDB redo log).","tags":["wal","durability"]},
    {"id":"emb-q15","type":"multi","prompt":"Which scenarios fit an embedded DB? (Select all)",
     "choices":["Mobile app needing offline storage","Unit test suite needing fast DB setup","Multi-user web app with 1000 concurrent writers","CLI tool caching local state"],
     "answerIndexes":[0,1,3],"explanation":"Mobile: single-user, offline → SQLite perfect. Tests: in-memory H2/SQLite are blazing fast. CLI tool: local persistent cache → SQLite. Multi-user web app at scale: NEEDS server DB (Postgres) — concurrent writes overwhelm SQLite's single-writer model.","tags":["embedded","when-to-use"]},
    {"id":"emb-q16","type":"mcq","prompt":"What is BadgerDB?",
     "choices":["A SQL DB","Pure-Go LSM-based key-value store, used by graph DB Dgraph. Comparable to RocksDB but Go-native (no JNI).","Java DB","Browser DB"],
     "answerIndex":1,"explanation":"Badger: pure-Go KV store. Same LSM-tree concept as RocksDB. Advantage in Go ecosystems: no CGO/JNI dependency, easier cross-compilation. Used by Dgraph (graph DB) for storage. Pattern: every language ecosystem tends to have its native LSM KV (RocksDB for C++, Badger for Go, sled for Rust, RocksDB-jni for Java).","tags":["badgerdb","go"]},
    {"id":"emb-q17","type":"mcq","prompt":"In SQLite, why might you want to enable WAL mode in production?",
     "choices":["Faster reads","Better concurrency: readers and writer don't block each other, plus better crash safety (WAL is appended; main file unchanged until checkpoint). Standard for production SQLite usage.","Required","More features"],
     "answerIndex":1,"explanation":"Default journal mode (rollback): writer holds lock, blocks readers + other writers. WAL mode: writer appends to WAL file; readers see consistent snapshot of (main file + WAL prefix). They don't block each other. Crash recovery via WAL replay. Trade: reads need to consult both files, but throughput is much higher.","tags":["sqlite","wal"]},
    {"id":"emb-q18","type":"mcq","prompt":"Why are SQLite tests so much faster than Postgres tests?",
     "choices":["SQLite is faster always","Embedded = no IPC: in-memory mode (':memory:' or H2 mem:) means table CREATE/DROP for each test takes microseconds vs milliseconds. No network, no separate process, no file flush.","Postgres is broken","SQL difference"],
     "answerIndex":1,"explanation":"Test loop creating/dropping tables hundreds of times. Postgres: each test = network round trip × N + disk flush per transaction. SQLite in-memory: function calls + RAM only. Suite: SQLite tests run in seconds, equivalent Postgres tests can take minutes. Trade-off: SQL dialect drift → use Testcontainers for production parity on critical paths.","tags":["embedded","testing","performance"]},
    {"id":"emb-q19","type":"mcq","prompt":"What's a serious risk if you don't enable foreign keys in SQLite?",
     "choices":["No risk","DEFAULT is OFF for backward compatibility — referenced rows can be deleted without errors, leaving orphan child rows. Always: PRAGMA foreign_keys = ON;","Performance","SQL syntax"],
     "answerIndex":1,"explanation":"SQLite added FK support but defaults OFF for backward compat. With FK off: DELETE FROM users where ID has orders → deletes user, leaves orphan orders. Run 'PRAGMA foreign_keys = ON;' on every connection. JDBC drivers usually do this automatically; verify in your tooling.","tags":["sqlite","integrity"]},
    {"id":"emb-q20","type":"mcq","prompt":"Why does compaction need to run in LSM-tree systems?",
     "choices":["Compress","Merge multiple SSTables into fewer/larger ones — removes deleted/superseded entries, reduces read amplification (fewer files to check per read), reclaims space.","For backups","Random optimisation"],
     "answerIndex":1,"explanation":"Without compaction: dozens of SSTables accumulate. Read latency: check ALL of them per query (Bloom filters help but still expensive). Deleted keys still stored. Compaction: merge sorted files, drop obsolete entries, write new file. Trade-off (write amplification) for reduced read amplification + space reclaim. Tunable in RocksDB.","tags":["lsm","compaction"]},
]

EMBED_FC = [
    {"id":"emb-fc1","front":"Embedded vs client-server DB","back":"Embedded (SQLite, RocksDB, H2): library inside your process, direct file I/O, no server. Client-server (Postgres, MySQL): separate process, network protocol, multi-client. Choose based on: single-user vs multi-user, offline-capability needed, ops complexity tolerance.","tags":["embedded","fundamentals"]},
    {"id":"emb-fc2","front":"SQLite quick facts","back":"Most-deployed DB in the world. ~600KB library. Full SQL + ACID. Single file = entire DB. Single writer at a time. Public domain. Use for: mobile apps, browsers, CLI tools, fast tests. Don't use for: high-concurrency web servers, network filesystems.","tags":["sqlite"]},
    {"id":"emb-fc3","front":"RocksDB at a glance","back":"Embedded KV store from Meta (forked LevelDB). LSM tree storage. Write-optimised. Used as storage engine in: Cassandra, CockroachDB, Yugabyte, Kafka Streams. No SQL — just put/get/delete/scan by byte keys. TB-scale on single node.","tags":["rocksdb"]},
    {"id":"emb-fc4","front":"LSM tree workflow","back":"Write: append to WAL + insert into MemTable. When MemTable fills: flush to immutable Level-0 SSTable. Background compaction merges SSTables into higher levels (less recent). Read: check MemTable → SSTables newest first. Bloom filter helps skip. Trade-off: write amplification vs sequential writes on SSD.","tags":["lsm","storage"]},
    {"id":"emb-fc5","front":"SQLite WAL mode","back":"PRAGMA journal_mode=WAL. Writes go to WAL file (append-only). Readers see consistent (main + WAL) snapshot — don't block writer. Periodic checkpoint merges WAL into main. Production-grade SQLite always uses WAL. Better concurrency, better crash safety.","tags":["sqlite","wal"]},
    {"id":"emb-fc6","front":"H2 in-memory tests","back":"jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1. Spring Boot's test default. Fresh DB each run, microsecond startup. Caveat: SQL dialect drift from Postgres/MySQL — use Testcontainers (real Postgres in Docker) for production parity on integration tests.","tags":["h2","testing"]},
    {"id":"emb-fc7","front":"DuckDB use case","back":"Embedded analytical DB. Column-store, vectorised. 'SQLite for OLAP'. Query Parquet/CSV directly: SELECT * FROM read_parquet('file.parquet'). Replaces many uses of Spark for medium-scale analytics. Pandas integration: query DataFrames with SQL.","tags":["duckdb","analytics"]},
    {"id":"emb-fc8","front":"When NOT to use embedded","back":"Multi-process writes (use Postgres). Multi-machine deployment (use distributed DB). Need DBA tools, replication, backup automation (use server). Network-shared filesystems (corruption risk). Datasets > single-machine capacity. Embedded ≠ all problems.","tags":["embedded","when-not-to"]},
]

EMBED_PROJ = {
    "brief": "You're building a desktop note-taking app (like Obsidian). It needs to work fully offline, store thousands of notes with tags, support full-text search, and sync to cloud later. Choose your storage architecture: which embedded DB(s), what schema, how full-text search works, and how cloud sync would integrate.",
    "checklist": [
        {"id":"e1","text":"Primary store: SQLite for relational data (notes table, tags table, note_tags join). PRAGMA journal_mode=WAL and PRAGMA foreign_keys=ON. Single file in user data dir.","weight":20},
        {"id":"e2","text":"Schema: notes(id, title, body, created_at, updated_at, sync_state); tags(id, name UNIQUE); note_tags(note_id, tag_id) composite PK + FKs. Index on notes.updated_at for sort.","weight":20},
        {"id":"e3","text":"Full-text search: SQLite FTS5 virtual table linked to notes (CREATE VIRTUAL TABLE notes_fts USING fts5(title, body, content=notes)). Triggers keep FTS in sync. Search: SELECT * FROM notes_fts WHERE notes_fts MATCH 'query'.","weight":20},
        {"id":"e4","text":"Sync state column tracks: 'local-only', 'synced', 'modified-since-sync'. Sync layer reads modified rows since last sync timestamp, pushes to cloud, updates state on success.","weight":20},
        {"id":"e5","text":"Backup: file copy of the .db file (with WAL checkpoint first). Document recovery: just restore the file. No server needed. User can copy DB to USB stick to move between machines.","weight":20},
    ],
    "hints": [
        "FTS5 virtual table sits ALONGSIDE notes table; sync triggers (INSERT/UPDATE/DELETE) keep it consistent. Query syntax supports phrase, prefix, near, and column filters.",
        "For very large note bodies (10MB+ each), consider storing body in a separate file referenced by path. SQLite is OK with BLOBs but > 1GB DBs slow down significantly.",
        "Sync conflict resolution: each row has updated_at + (optionally) version vector. Last-writer-wins with conflict marker for user. Or 3-way merge if you can detect base version. Hard problem — start simple.",
    ]
}

write("embedded-databases.json", {
    "id": "embedded-databases",
    "unit": 1,
    "order": 6,
    "title": "Embedded Databases",
    "summary": "SQLite, RocksDB, H2, DuckDB — when to use in-process databases vs client-server, with internals (B-tree vs LSM).",
    "prereqs": ["relational-databases-sql"],
    "guide": EMBED_GUIDE,
    "questions": EMBED_Q,
    "flashcards": EMBED_FC,
    "project": EMBED_PROJ,
})

print("\n=== Foundations Batch 2b Complete ===")
print("Written:")
print("  - foundations/relational-databases-sql.json")
print("  - foundations/embedded-databases.json")
print("")
print("All 6 foundation topics done.")

