"""
Batch 3a: Specialist Topics
  - distributed-systems (order 116) → security/ folder
  - database-internals (order 117) → security/ folder
Run: python3 scripts/new_topics_batch3a.py
"""
import json
from pathlib import Path

BASE = Path(__file__).parent.parent / "src/content/topics"


def write(folder, filename, data):
    out = BASE / folder / filename
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists():
        existing = json.loads(out.read_text())
        if len(existing.get("questions", [])) >= 20:
            print(f"  SKIP {filename} (already complete)")
            return
    out.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    g = len(data['guide'])
    q = len(data['questions'])
    fc = len(data['flashcards'])
    print(f"  WROTE {filename}: guide={g} q={q} fc={fc}")


# ── DISTRIBUTED SYSTEMS ──────────────────────────────────────────────────────

DS_GUIDE = "\n".join([
    "# Distributed Systems",
    "",
    "## What Is a Distributed System?",
    "",
    "A distributed system is a collection of independent computers that appear to users",
    "as a single coherent system. Your laptop calling an API, that API calling a database",
    "replica in another region — that's a distributed system.",
    "",
    "```",
    "Single machine (simple):",
    "  App ──► DB",
    "  If DB crashes → app down. But: easy consistency, no network issues.",
    "",
    "Distributed (complex but scalable):",
    "  App servers (3) ──► DB primary",
    "                   └─► DB replica (Europe)",
    "                   └─► DB replica (Asia)",
    "  More capacity. But: what if primary → Europe replica is slow?",
    "  Is the replica stale? Did the write reach it?",
    "```",
    "",
    "Distributed systems introduce a new class of problems:",
    "- **Partial failures**: some nodes work, others don't",
    "- **Network partitions**: nodes can't communicate but both think they're right",
    "- **Clocks**: different machines have different times",
    "- **Consistency**: does everyone see the same data?",
    "",
    "---",
    "",
    "## CAP Theorem",
    "",
    "```",
    "CAP Theorem (Eric Brewer, 2000):",
    "A distributed data store can guarantee at most TWO of these three properties:",
    "",
    "  C — Consistency:          Every read returns the most recent write",
    "                            (or an error, never stale data)",
    "  A — Availability:         Every request receives a response",
    "                            (not an error, though might be stale)",
    "  P — Partition tolerance:  System continues operating during",
    "                            network partition (message loss)",
    "",
    "                    CAP Triangle:",
    "                       C",
    "                      / \\",
    "                     /   \\",
    "               CP   /     \\  CA",
    "                   /  AP   \\",
    "                  A─────────P",
    "",
    "In practice: P is NOT optional. Network partitions happen.",
    "So real choice is: CP or AP during a partition.",
    "",
    "CP (Consistency + Partition tolerance):",
    "  Example: HBase, Zookeeper, Etcd",
    "  During partition: refuse writes to avoid inconsistency",
    "  Use when: financial transactions, inventory (you can't oversell)",
    "",
    "AP (Availability + Partition tolerance):",
    "  Example: Cassandra, CouchDB, DynamoDB (default)",
    "  During partition: accept writes, risk inconsistency (stale reads)",
    "  Use when: social feeds, shopping cart, DNS",
    "",
    "MongoDB claim: 'CP' but configurable.",
    "Cassandra: 'AP' by default, can tune toward CP with quorum reads/writes.",
    "```",
    "",
    "---",
    "",
    "## Consistency Models — A Spectrum",
    "",
    "```",
    "Strong ◄────────────────────────────────────────► Eventual",
    "(Slower, simpler reasoning)              (Faster, harder reasoning)",
    "",
    "LINEARISABILITY (strongest):",
    "  Every operation appears instantaneous. Reads always see latest write.",
    "  Like a single machine. Very expensive in distributed systems.",
    "  Use: coordination services (Zookeeper, etcd), leader election.",
    "",
    "SEQUENTIAL CONSISTENCY:",
    "  All operations appear in same global order to all nodes.",
    "  Not necessarily real-time order though.",
    "",
    "CAUSAL CONSISTENCY:",
    "  Causally related operations are seen in order.",
    "  If you see 'Reply to Post X', you must first see 'Post X'.",
    "  Facebook: posts and replies causally consistent.",
    "",
    "EVENTUAL CONSISTENCY (weakest):",
    "  Given no new updates, all replicas converge to same value eventually.",
    "  Reads may return stale data.",
    "  Cassandra default. DNS. Shopping cart.",
    "  'Eventually' could be milliseconds or minutes.",
    "```",
    "",
    "---",
    "",
    "## Consensus — How Nodes Agree",
    "",
    "```",
    "PROBLEM: Distributed database has 5 nodes. A client writes value X.",
    "How do we ensure most nodes agree this write happened?",
    "What if the node that received the write crashes immediately?",
    "",
    "CONSENSUS ALGORITHM: makes nodes agree on a value even with failures.",
    "",
    "PAXOS (Leslie Lamport, 1989):",
    "  - Notoriously hard to understand and implement correctly",
    "  - Phases: Prepare → Promise → Accept → Accepted",
    "  - Used in: Google Spanner, Chubby",
    "",
    "RAFT (2013 — designed to be understandable):",
    "  Three roles: Leader, Follower, Candidate",
    "",
    "  Normal operation:",
    "    Leader receives write request",
    "    Leader appends to its log",
    "    Leader sends AppendEntries to all followers",
    "    Majority (quorum) acknowledge → commit",
    "    Leader responds OK to client",
    "",
    "  Leader election (on timeout with no heartbeat):",
    "    Follower → Candidate → sends RequestVote to all",
    "    If majority vote → becomes new Leader",
    "    Term number increments → old leader's messages rejected",
    "",
    "  Guarantee: if majority of nodes alive → system makes progress",
    "  5-node cluster tolerates 2 failures (majority = 3)",
    "  3-node cluster tolerates 1 failure",
    "",
    "  Used in: etcd (Kubernetes uses this!), CockroachDB, TiKV",
    "```",
    "",
    "---",
    "",
    "## Vector Clocks — Tracking Causality Without Clocks",
    "",
    "```",
    "PROBLEM: Two nodes both update the same key. Which update is newer?",
    "Can't use wall-clock time — distributed systems have clock skew.",
    "",
    "VECTOR CLOCK: each node tracks a counter for each other node.",
    "",
    "  Node A: [A:1, B:0, C:0]",
    "  Node B: [A:0, B:1, C:0]",
    "  Node C: [A:0, B:0, C:1]",
    "",
    "  A writes → A's clock: [A:2, B:0, C:0]",
    "  A sends to B → B updates: max each component → [A:2, B:1, C:0]",
    "  C writes independently → [A:0, B:0, C:2]",
    "",
    "  Compare [A:2, B:1, C:0] vs [A:0, B:0, C:2]:",
    "  Neither is ≥ the other in all components → CONCURRENT (conflict!)",
    "  Must be reconciled by application",
    "",
    "  Used in: Amazon DynamoDB (with last-write-wins or vector clock merge)",
    "  Simpler alternative: Logical clocks (Lamport clocks) — just a counter",
    "```",
    "",
    "---",
    "",
    "## Two-Phase Commit (2PC) — Distributed Transactions",
    "",
    "```",
    "PROBLEM: Transfer $100 from DB1 (bank A) to DB2 (bank B).",
    "Both must succeed or both must fail — atomically across two databases.",
    "",
    "2PC Protocol:",
    "  Phase 1 — PREPARE:",
    "    Coordinator asks all participants: 'Can you commit?'",
    "    Each participant:",
    "      Executes transaction up to commit point",
    "      Writes to transaction log (durably)",
    "      Replies YES or NO",
    "",
    "  Phase 2 — COMMIT or ABORT:",
    "    If all YES → Coordinator sends COMMIT to all",
    "    If any NO  → Coordinator sends ABORT to all",
    "",
    "  Problem: Coordinator can crash after Phase 1 but before Phase 2",
    "  → Participants locked in prepared state, waiting forever",
    "  → This is called the 'blocking' problem of 2PC",
    "",
    "  3PC (Three-Phase Commit) was invented to fix this but rarely used in practice.",
    "  Modern systems: SAGA pattern instead of 2PC.",
    "```",
    "",
    "---",
    "",
    "## SAGA Pattern — Distributed Transactions Without 2PC",
    "",
    "```",
    "SAGA: sequence of local transactions with compensating transactions for rollback.",
    "",
    "Order placement saga:",
    "  1. Create order           → compensate: cancel order",
    "  2. Reserve inventory      → compensate: release inventory",
    "  3. Charge payment         → compensate: refund",
    "  4. Schedule shipping      → compensate: cancel shipping",
    "  5. Send confirmation      → compensate: send cancellation email",
    "",
    "If step 3 (payment) fails:",
    "  Run compensating transactions backwards: release inventory, cancel order",
    "",
    "Two saga coordination styles:",
    "  Choreography: each service emits events, next service listens",
    "    + Simple, no central coordinator",
    "    - Hard to track overall state",
    "",
    "  Orchestration: central SAGA orchestrator (like AWS Step Functions) controls flow",
    "    + Easy to monitor and debug",
    "    - Single orchestrator point",
    "",
    "Used in: microservices, e-commerce order flows, financial workflows",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "DISTRIBUTED SYSTEMS",
    "|",
    "+-- CAP THEOREM",
    "|   +-- C: every read = latest write",
    "|   +-- A: every request gets response",
    "|   +-- P: survives network partition",
    "|   +-- Choose CP or AP (P is mandatory)",
    "|",
    "+-- CONSISTENCY MODELS",
    "|   +-- Linearisable (strongest) → etcd",
    "|   +-- Causal → social feeds",
    "|   +-- Eventual (weakest) → Cassandra, DNS",
    "|",
    "+-- CONSENSUS",
    "|   +-- Raft: Leader+Followers, quorum writes",
    "|   +-- Paxos: proven but complex",
    "|   +-- Quorum: majority of nodes must agree",
    "|",
    "+-- TRANSACTIONS",
    "|   +-- 2PC: coordinator + prepare + commit (blocking)",
    "|   +-- SAGA: local txns + compensations",
    "|",
    "+-- CLOCKS",
    "    +-- Vector clocks (causality tracking)",
    "    +-- Lamport clocks (simpler logical clock)",
    "    +-- NTP: sync wall clocks (not reliable for ordering)",
    "```",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **Distributed Systems in One Lesson** by Tim Berglund (Confluent):",
    "  https://www.youtube.com/watch?v=Y6Ev8GIlbxc",
    "- **Raft Consensus Algorithm explained** by Martin Kleppmann:",
    "  https://www.youtube.com/watch?v=uXEYuDwm7e4",
    "",
    "### Books",
    "- **Designing Data-Intensive Applications** by Martin Kleppmann — THE book on this topic",
    "- **The Raft Paper** (readable!): https://raft.github.io/raft.pdf",
    "- **CAP FAQ**: https://www.the-paper-trail.org/page/cap-faq/",
    "",
    "### Practice",
    "- **Fly.io distributed systems challenges**: https://fly.io/dist-sys/ — hands-on Raft/gossip",
])

DS_Q = [
    {"id":"ds-q1","type":"mcq","prompt":"CAP theorem: during a network partition you must choose between:",
     "choices":["Speed vs correctness","Consistency vs Availability — you can't have both. Nodes can't communicate; do you refuse requests (C) or serve potentially stale data (A)?","SQL vs NoSQL","Sync vs async"],
     "answerIndex":1,"explanation":"Partition tolerance is mandatory (networks fail). The real choice: CP (consistency over availability — block writes during partition) or AP (availability — serve stale reads). Financial systems choose CP; social feeds often choose AP.","tags":["cap","consistency","availability"]},
    {"id":"ds-q2","type":"mcq","prompt":"Cassandra is described as AP. What does this mean in practice?",
     "choices":["Cassandra never has consistency issues","During a partition, Cassandra continues accepting reads and writes (available) but different replicas may have different data (inconsistency). Nodes reconcile after partition heals.","Cassandra always uses consensus","AP means it's async only"],
     "answerIndex":1,"explanation":"Cassandra's default: highly available, eventually consistent. You can write to any node even if some replicas are unreachable. After the network heals, anti-entropy repair reconciles diverged replicas. Use QUORUM consistency level to trade availability for stronger consistency.","tags":["cassandra","cap","eventual-consistency"]},
    {"id":"ds-q3","type":"mcq","prompt":"What is eventual consistency?",
     "choices":["Consistency will be fixed in a future version","If no new updates occur, all replicas will converge to the same value eventually. Reads may return stale data temporarily. 'Eventually' is typically milliseconds to seconds.","Consistency only at end of day","Requires 100% uptime"],
     "answerIndex":1,"explanation":"Eventual consistency is a liveness guarantee (not safety). It says: things will be OK eventually. DNS is eventually consistent — propagation takes up to 48 hours. Shopping carts: adding to cart is eventually consistent. Order placement requires stronger consistency.","tags":["eventual-consistency","cap"]},
    {"id":"ds-q4","type":"mcq","prompt":"Raft consensus: what is a 'quorum'?",
     "choices":["Maximum number of nodes","Majority of nodes — for N nodes, quorum = floor(N/2)+1. A write is committed only when quorum nodes acknowledge. 5-node cluster: quorum=3, tolerates 2 failures.","Minimum 2 nodes","Quorum is specific to Raft"],
     "answerIndex":1,"explanation":"Quorum = majority. For 5 nodes: 3 needed. For 3 nodes: 2 needed. A leader can only commit a log entry when a majority has acknowledged it. This ensures at least one quorum member has the data even if others fail. Two disjoint quorums can't form simultaneously.","tags":["raft","quorum","consensus"]},
    {"id":"ds-q5","type":"mcq","prompt":"How does Raft elect a new leader when the current leader crashes?",
     "choices":["Random node claims leadership","Followers detect timeout (no heartbeat), become Candidates, request votes from peers. Node with most up-to-date log wins majority vote → becomes new Leader. Term number increments to invalidate old leader.","Admin manually promotes leader","Leader promotes a successor before crashing"],
     "answerIndex":1,"explanation":"Raft leader sends heartbeats every ~150ms. No heartbeat within election timeout (150-300ms): follower → candidate. Requests votes. Each node votes for one candidate per term. Majority vote = new leader. Term number prevents split-brain: old leader's messages rejected (stale term).","tags":["raft","leader-election"]},
    {"id":"ds-q6","type":"mcq","prompt":"Two-Phase Commit (2PC) main weakness:",
     "choices":["Too slow","If coordinator crashes between Phase 1 (prepare) and Phase 2 (commit/abort), all participants are blocked in prepared state indefinitely — can't commit or abort without coordinator. 'Blocking' protocol.","Too many messages","Only works for 2 databases"],
     "answerIndex":1,"explanation":"2PC is blocking. Participants vote YES (prepared), write to WAL, wait. Coordinator crashes. Participants can't unilaterally commit (might contradict other participant's state) or abort (coordinator might have committed). System stuck until coordinator recovers.","tags":["2pc","distributed-transactions"]},
    {"id":"ds-q7","type":"mcq","prompt":"SAGA pattern compensating transactions: what IS a compensating transaction?",
     "choices":["A transaction that runs twice","A business-logic operation that semantically undoes the effect of a previous transaction — e.g., if 'Charge $100' succeeded but a later step failed, the compensating transaction is 'Refund $100'.","A timeout","Database rollback"],
     "answerIndex":1,"explanation":"SAGA can't do database rollback (each step is a LOCAL transaction already committed). Compensation is a new forward transaction that semantically negates the previous: cancel order, refund payment, release inventory. Must be idempotent — could be executed more than once.","tags":["saga","compensation"]},
    {"id":"ds-q8","type":"mcq","prompt":"Vector clocks: when are two events [A:2,B:1] and [A:1,B:2] considered 'concurrent'?",
     "choices":["When timestamps are different","When neither vector clock is component-wise ≥ the other — neither happened-before the other. [A:2,B:1] is not ≤ [A:1,B:2] and vice versa. They diverged independently = write conflict.","When they have same values","When clocks differ by >1"],
     "answerIndex":1,"explanation":"Vector clock A ≤ B when every component of A ≤ corresponding component of B. [A:2,B:1] vs [A:1,B:2]: A has higher A-component, B has higher B-component — neither dominates. CONCURRENT = possible write conflict. Application must resolve.","tags":["vector-clocks","causality"]},
    {"id":"ds-q9","type":"mcq","prompt":"Linearisability vs Eventual Consistency — main trade-off?",
     "choices":["No trade-off","Linearisability: every read returns latest write globally (strong guarantees), requires coordination across nodes (slow, availability impact). Eventual: reads may be stale (weak guarantee), no coordination needed (fast, always available).","Eventual is stronger","Linearisability is only for relational databases"],
     "answerIndex":1,"explanation":"Linearisability requires consensus on each operation — every read and write goes through a leader. Single-digit millisecond latency becomes tens of ms with global coordination. Eventual consistency: any replica answers immediately. Choose based on whether stale reads are acceptable in your domain.","tags":["consistency-models","linearisability","eventual"]},
    {"id":"ds-q10","type":"mcq","prompt":"Etcd (used by Kubernetes) uses Raft. What does it store?",
     "choices":["Container images","All Kubernetes cluster state: Pod specs, Service configs, ConfigMaps, node registrations, leader elections for controllers. It's the source of truth — if etcd is corrupted, K8s cluster state is lost.","Application logs","Network routing tables only"],
     "answerIndex":1,"explanation":"Etcd is a CP distributed key-value store (strong consistency). Kubernetes uses it as its backing store. Every kubectl apply writes to etcd. All controllers watch etcd for state changes. etcd uses Raft to stay consistent across its 3-5 node cluster.","tags":["etcd","raft","kubernetes"]},
    {"id":"ds-q11","type":"mcq","prompt":"In Raft, can a node with a stale log become leader?",
     "choices":["Yes — any node can become leader","No — Raft's election safety: a node only votes for a candidate if candidate's log is at least as up-to-date as its own. Most up-to-date node always wins election. Ensures new leader has all committed entries.","Leaders are randomly assigned","Log staleness doesn't matter"],
     "answerIndex":1,"explanation":"Raft election restriction: candidates include their last log index and term in RequestVote. Voters reject candidates with less up-to-date logs. This guarantees: whoever wins election has all previously committed log entries — no data loss on failover.","tags":["raft","safety"]},
    {"id":"ds-q12","type":"mcq","prompt":"SAGA choreography vs orchestration — key difference?",
     "choices":["Orchestration is faster","Choreography: each service publishes events and reacts to others' events (decentralised, no central coordinator). Orchestration: central SAGA orchestrator sends commands and tracks state (centralised, easier to monitor/debug).","Choreography requires a database","They are identical"],
     "answerIndex":1,"explanation":"Choreography: OrderService publishes 'OrderCreated' → InventoryService listens → publishes 'InventoryReserved' → PaymentService listens. Decoupled but state tracking is implicit in event flow. Orchestration: SagaOrchestrator tells InventoryService 'reserve', waits, tells PaymentService 'charge'.","tags":["saga","choreography","orchestration"]},
    {"id":"ds-q13","type":"mcq","prompt":"Why can't you simply use NTP-synchronised wall clocks for ordering events in distributed systems?",
     "choices":["NTP is too expensive","Clock drift: even NTP-synced clocks can be off by 100ms+. A write at 'time T' on Node A might actually happen before a write at 'time T-50ms' on Node B due to drift. Use logical clocks (Lamport/vector) for ordering.","NTP is not available","Wall clocks are fine for ordering"],
     "answerIndex":1,"explanation":"NTP achieves ~100ms accuracy in practice (can be worse). Two servers might have timestamps:  Server A writes at 10:00:00.000, Server B writes at 09:59:59.950 (50ms behind). Wall-clock order: B first. Actual causal order: A first. Logical clocks (Lamport) don't have this problem.","tags":["clocks","lamport","distributed"]},
    {"id":"ds-q14","type":"mcq","prompt":"What is the 'split-brain' problem in distributed systems?",
     "choices":["Memory corruption","Network partition causes two groups of nodes to each elect their own leader and independently accept writes — data diverges. When partition heals, conflicting writes must be resolved.","Database fragmentation","Slow network"],
     "answerIndex":1,"explanation":"Split-brain: Cluster of 5 nodes. Network split: {A,B} can't see {C,D,E}. If consensus is broken, {A,B} might elect leader A and {C,D,E} elect leader C. Both accept writes. Conflicting data. Raft prevents this: group of 2 can't form quorum (needs 3) — no leader elected, no writes accepted.","tags":["split-brain","consensus"]},
    {"id":"ds-q15","type":"mcq","prompt":"Gossip protocol in distributed systems — what is it used for?",
     "choices":["Security","Decentralised information spreading: nodes randomly pick 2-3 peers and exchange state information. State spreads exponentially like a rumour. Used for: failure detection, memberlist maintenance, state propagation in Cassandra.","Consensus","Database replication"],
     "answerIndex":1,"explanation":"Gossip: each round, each node shares its info with K random nodes. After log N rounds, all nodes have the information. Scales to thousands of nodes with constant per-node overhead. Cassandra uses gossip for cluster membership and state. Consul uses gossip for service discovery.","tags":["gossip","protocols"]},
    {"id":"ds-q16","type":"mcq","prompt":"Read repair in Cassandra — what is it?",
     "choices":["Fixing corrupted data","During a read with QUORUM consistency: Cassandra reads from multiple replicas. If they disagree, it returns the most recent value AND asynchronously updates stale replicas. Self-healing consistency without background jobs.","Repairing disk errors","Re-reading failed queries"],
     "answerIndex":1,"explanation":"Read repair is one of Cassandra's anti-entropy mechanisms. QUORUM read: contact 3 of 5 replicas, compare values. Two agree on version 5, one has version 4 (stale) → return version 5 to client, asynchronously send version 5 to stale replica. Gradual convergence.","tags":["cassandra","eventual-consistency","read-repair"]},
    {"id":"ds-q17","type":"mcq","prompt":"What is the difference between replication and sharding?",
     "choices":["No difference","Replication: same data on multiple nodes (redundancy + read scalability). Sharding: different data on different nodes (horizontal partitioning for write scalability). Production: usually both — each shard has multiple replicas.","Sharding is for SQL only","Replication is only for backup"],
     "answerIndex":1,"explanation":"Replication: copy all data to replicas. Node A: users 1-1M. Node B: users 1-1M (same). Benefits: fault tolerance, read scale-out. Sharding: Node A: users 1-500K. Node B: users 500K-1M. Benefits: write scale (each node handles less data/load). Most large systems use both.","tags":["replication","sharding","distributed"]},
    {"id":"ds-q18","type":"mcq","prompt":"Last-Write-Wins (LWW) conflict resolution — main problem?",
     "choices":["Too slow","Concurrent writes both have same timestamp due to clock skew → one arbitrarily wins, other silently lost. Or: write with earlier timestamp arrives late (network delay) but still wins vs earlier arrival. Data loss.","Requires consensus","Only works for SQL"],
     "answerIndex":1,"explanation":"LWW: keep the write with the latest timestamp, discard others. In distributed systems with clock skew: server A's clock is 50ms ahead. A's write at T+50 beats B's write at T, even if B's write was actually submitted later. Silent data loss. CRDTs (Conflict-Free Replicated Data Types) solve this properly.","tags":["conflict-resolution","lww"]},
    {"id":"ds-q19","type":"multi","prompt":"Which systems use Raft or Paxos for consensus? (Select all that apply)",
     "choices":["etcd (Kubernetes cluster state)","CockroachDB (distributed SQL)","Redis (default single-node)","Google Spanner"],
     "answerIndexes":[0,1,3],"explanation":"etcd: Raft. CockroachDB: Raft per range. Google Spanner: Paxos per shard. Redis default is single-node, no consensus protocol. Redis Cluster uses gossip for topology but not Raft/Paxos for data consistency.","tags":["raft","consensus","systems"]},
    {"id":"ds-q20","type":"mcq","prompt":"Why is 3-node Raft cluster preferred over 2-node for fault tolerance?",
     "choices":["3 is a lucky number","3-node tolerates 1 failure (quorum=2). 2-node tolerates 0 failures (quorum=2, any failure breaks quorum). Adding a 3rd node doubles fault tolerance from 0 to 1. 5-node tolerates 2 failures.","2-node uses more bandwidth","3-node is faster"],
     "answerIndex":1,"explanation":"Quorum formula: floor(N/2)+1. N=2: quorum=2 (both nodes needed, zero fault tolerance). N=3: quorum=2 (one node can fail). N=5: quorum=3 (two nodes can fail). Rule: use odd numbers to avoid tie votes. 3 or 5 nodes are the standard choices.","tags":["raft","fault-tolerance","quorum"]},
]

DS_FC = [
    {"id":"ds-fc1","front":"CAP theorem practical choice","back":"P (partition tolerance) is mandatory — networks fail. Real choice: CP (refuse writes when uncertain, stay consistent — banks) vs AP (serve stale reads, stay available — social feeds). Configure per use case (Cassandra: tune consistency level per query).","tags":["cap"]},
    {"id":"ds-fc2","front":"Raft quorum rule","back":"Quorum = floor(N/2)+1. 3 nodes → quorum=2, tolerates 1 failure. 5 nodes → quorum=3, tolerates 2 failures. Write committed only when quorum acknowledges. Leader sends heartbeats; no heartbeat within timeout → election.","tags":["raft","quorum"]},
    {"id":"ds-fc3","front":"Eventual vs Linearisable consistency","back":"Linearisable: every read sees latest write (requires coordination, slower). Eventual: replicas converge over time, reads may be stale (no coordination, fast). Choose based on domain: banking = linearisable, social feed = eventual.","tags":["consistency"]},
    {"id":"ds-fc4","front":"SAGA vs 2PC","back":"2PC: atomic but blocking (coordinator crash = stuck). SAGA: local transactions + compensating transactions. Not atomic but non-blocking. Use SAGA for microservices. Compensating txns must be idempotent (may run multiple times).","tags":["saga","2pc","distributed-transactions"]},
    {"id":"ds-fc5","front":"Vector clock concurrent events","back":"VCs are concurrent when neither is component-wise ≥ the other. A=[A:2,B:0] and B=[A:0,B:2] → concurrent (conflict). A=[A:2,B:0] and B=[A:1,B:1] → B happened after A (B.A >= A.A and B.B >= A.B).","tags":["vector-clocks"]},
    {"id":"ds-fc6","front":"Split-brain prevention","back":"Raft/Paxos prevents split-brain: leader only accepts writes when quorum available. Minority partition (2 of 5 nodes) cannot form quorum → rejects writes → no diverging state. Partition heals → rejoin leader and catch up via log replication.","tags":["split-brain","raft"]},
    {"id":"ds-fc7","front":"Gossip protocol properties","back":"Decentralised, scale-well (O(log N) rounds to reach all nodes). Used for: cluster membership, failure detection, state propagation. Cassandra uses gossip. Consul uses gossip. Alternative to centralised registry (no SPOF).","tags":["gossip","protocols"]},
    {"id":"ds-fc8","front":"Replication vs sharding","back":"Replication: same data on multiple nodes (fault tolerance + read scale). Sharding: different data on different nodes (write scale + storage scale). Production systems use both: each shard is replicated. Adds 2D reliability.","tags":["replication","sharding"]},
]

DS_PROJ = {
    "brief": "You are building a distributed key-value store that will span 3 data centres. Key requirements: writes must be acknowledged by majority before returning to client, leadership changes must be transparent to clients, and the system must continue working if one entire data centre goes offline. Design the replication strategy, leader election, and client failover mechanism. What consistency guarantees can you offer?",
    "checklist": [
        {"id":"dist1","text":"Raft with 5 nodes (2 per DC, 1 shared) or 3 nodes one per DC. Quorum = 3 means 1 DC failure tolerated.","weight":20},
        {"id":"dist2","text":"Write flow: client → leader → log → replicate to quorum → commit → ACK client. Clients retry on leader change.","weight":20},
        {"id":"dist3","text":"Client discovers leader via service discovery (etcd/Consul). On leader change: client retries, cluster redirects to new leader.","weight":20},
        {"id":"dist4","text":"Consistency: linearisable reads by routing to leader. Eventual reads possible via any replica with staleness warning.","weight":20},
        {"id":"dist5","text":"DC failure scenario: 2 remaining DCs have 4 nodes, quorum=3 still achievable. System continues. Healed DC catches up via log replication.","weight":20},
    ],
    "hints": [
        "Raft term numbers prevent a recovered old leader from causing split-brain — its messages are rejected as stale term.",
        "Client library tracks last known leader. On connection refused: try other nodes, they respond with current leader address.",
        "Log compaction (snapshotting): long-running cluster's Raft log grows unbounded. Periodically snapshot state, truncate old log entries.",
    ]
}

write("security", "distributed-systems.json", {
    "id": "distributed-systems",
    "unit": 11,
    "order": 116,
    "title": "Distributed Systems",
    "summary": "CAP theorem, Raft consensus, vector clocks, eventual consistency, and SAGA pattern for microservices.",
    "prereqs": ["system-design-fundamentals"],
    "guide": DS_GUIDE,
    "questions": DS_Q,
    "flashcards": DS_FC,
    "project": DS_PROJ,
})

# ── DATABASE INTERNALS ───────────────────────────────────────────────────────

DBI_GUIDE = "\n".join([
    "# Database Internals",
    "",
    "## Why Learn Database Internals?",
    "",
    "Developers who understand how their database actually works can:",
    "- Choose the right index type",
    "- Explain why a query suddenly got slow",
    "- Understand what VACUUM does and why you need it",
    "- Know when an ORM is hiding something dangerous",
    "",
    "```",
    "Surface level developer: 'Add an index, it will be faster'",
    "After this guide:        'Add a B-tree index on (status, created_at)",
    "                          using CONCURRENTLY so production isn't locked.",
    "                          Expect 20MB overhead. Run ANALYZE after.'",
    "```",
    "",
    "---",
    "",
    "## B-Tree — The Index Data Structure",
    "",
    "```",
    "A B-tree is a self-balancing tree that keeps data sorted,",
    "allowing searches, insertions, and deletions in O(log n).",
    "",
    "B-tree node (PostgreSQL default: 8KB pages):",
    "",
    "  Page 1 (root):        [30 | 70]",
    "                       /    |    \\",
    "  Page 2:           [5|15]  |  [50|60]  ← branch pages",
    "                            |",
    "  Page 3:         ← [30|35|40] →       ← leaf pages (actual data or pointers)",
    "",
    "Leaf pages contain: {key, heap_pointer}",
    "  key = the indexed column value",
    "  heap_pointer = {page_number, slot_number} pointing to actual row in table",
    "",
    "B-tree search (SELECT * FROM orders WHERE user_id = 42):",
    "  1. Read root page: 42 < 70? → go left",
    "  2. Read branch: 42 > 30? → go right subtree",
    "  3. Read leaf: find 42 → get heap pointer",
    "  4. Read heap page at {page:5, slot:7} → actual row",
    "  Total: 3-4 page reads vs potentially millions for Seq Scan",
    "",
    "B-tree height: log_100(rows) (branching factor ~100 per page)",
    "  1M rows: height = 3",
    "  1B rows: height = 5",
    "  → Very flat, very fast",
    "```",
    "",
    "---",
    "",
    "## Write-Ahead Log (WAL)",
    "",
    "```",
    "QUESTION: If PostgreSQL crashes mid-write, how does it not corrupt data?",
    "",
    "ANSWER: Write-Ahead Log",
    "",
    "WAL Rule: Before changing any data page, write the INTENT to the WAL log first.",
    "          WAL is sequential I/O (append-only) → very fast even on HDD.",
    "",
    "Flow for UPDATE orders SET status='shipped' WHERE id=42:",
    "  1. Write WAL record: 'I am about to change page 47, slot 3, field status'",
    "  2. fsync WAL to disk (durable!)",
    "  3. Modify the in-memory page (buffer pool)",
    "  4. Page eventually flushed to disk (async, batched)",
    "",
    "CRASH RECOVERY:",
    "  PostgreSQL restarts → finds uncommitted WAL records → replays them",
    "  Or: finds committed WAL but flushed page is corrupted → replays from WAL",
    "  WAL guarantees durability: 'D' in ACID",
    "",
    "WAL also enables:",
    "  Streaming replication: send WAL records to standby replica in real-time",
    "  Point-in-time recovery: replay WAL from backup to any point in time",
    "  Logical replication: decode WAL changes to SQL events (CDC)",
    "```",
    "",
    "---",
    "",
    "## MVCC — Multi-Version Concurrency Control",
    "",
    "```",
    "PROBLEM: Transaction A is reading rows while Transaction B is updating them.",
    "  - Lock B until A finishes? → terrible for read performance",
    "  - Let A see partially updated data? → consistency violated",
    "",
    "MVCC SOLUTION: Keep multiple versions of each row.",
    "  Every row version has: xmin (transaction that created it)",
    "                         xmax (transaction that deleted/updated it)",
    "",
    "  Original row:  {xmin: 100, xmax: null, status: 'pending'}",
    "  After UPDATE by txn 200:",
    "    Old version: {xmin: 100, xmax: 200, status: 'pending'}  ← now deleted",
    "    New version: {xmin: 200, xmax: null, status: 'shipped'} ← current",
    "",
    "Transaction A (started at txid 150):",
    "  Reads row: which version is visible?",
    "  Rule: visible if xmin <= 150 AND (xmax is null OR xmax > 150)",
    "  Old version: xmin=100 ≤ 150, xmax=200 > 150 → VISIBLE to A",
    "  A sees 'pending' even though B already committed 'shipped'",
    "",
    "Benefits:",
    "  - Readers never block writers",
    "  - Writers never block readers",
    "  - Each transaction sees a consistent snapshot",
    "",
    "Cost: dead tuples accumulate (old versions no longer needed by any transaction)",
    "      Enter: VACUUM",
    "```",
    "",
    "---",
    "",
    "## VACUUM — Dead Tuple Cleanup",
    "",
    "```",
    "Dead tuples = row versions no longer visible to any transaction.",
    "They take space, slow index scans, cause 'table bloat'.",
    "",
    "VACUUM reclaims dead tuple space:",
    "  Marks space as reusable (not returned to OS unless VACUUM FULL)",
    "  Updates visibility map (used for index-only scans)",
    "  Prevents transaction ID wraparound (fatal if not done!)",
    "",
    "AUTOVACUUM: PostgreSQL runs VACUUM automatically when tables change.",
    "  Tunable: autovacuum_vacuum_threshold = 50",
    "            autovacuum_vacuum_scale_factor = 0.2",
    "  Triggers when: 50 + 20% of table rows are dead",
    "",
    "VACUUM FULL: compacts table to minimum size, rewrites entire table.",
    "  Use case: after deleting 90% of rows.",
    "  Cost: takes exclusive lock on table! Use pg_repack instead for zero-downtime.",
    "",
    "ANALYZE: updates table statistics (column histograms for query planner).",
    "  Run after large data loads: ANALYZE tablename;",
    "",
    "Monitor bloat:",
    "  SELECT relname, n_dead_tup, n_live_tup FROM pg_stat_user_tables",
    "  ORDER BY n_dead_tup DESC;",
    "```",
    "",
    "---",
    "",
    "## Index Types in PostgreSQL",
    "",
    "```",
    "+------------------+---------------------------+-------------------------------+",
    "| Index type       | Use case                  | Key feature                   |",
    "+------------------+---------------------------+-------------------------------+",
    "| B-tree (default) | =, <, >, BETWEEN, LIKE    | Equality + range queries      |",
    "| Hash             | = only                    | Faster equality, no range     |",
    "| GIN              | Array containment, JSONB  | Multiple values in one column |",
    "| GiST             | Geometric, full-text, IP  | Generalized search tree       |",
    "| BRIN             | Append-only (time-series) | Very small, block-range only  |",
    "+------------------+---------------------------+-------------------------------+",
    "",
    "GIN example (JSONB):",
    "  CREATE INDEX idx_meta ON events USING GIN(metadata);",
    "  SELECT * FROM events WHERE metadata @> '{\"type\": \"click\"}';",
    "",
    "BRIN example (time-series):",
    "  CREATE INDEX idx_ts ON metrics USING BRIN(created_at);",
    "  -- Stores only min/max per block range",
    "  -- 99% smaller than B-tree, perfect for append-only tables",
    "",
    "Partial index (smaller, faster for specific queries):",
    "  CREATE INDEX idx_active ON users(email) WHERE status = 'active';",
    "  -- Only indexes active users, ignores deleted. Smaller = faster.",
    "",
    "Concurrent index build (zero locks):",
    "  CREATE INDEX CONCURRENTLY idx_orders_user ON orders(user_id);",
    "  -- Takes longer but doesn't block read/write. Use in production.",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "DATABASE INTERNALS",
    "|",
    "+-- B-TREE",
    "|   +-- Balanced, sorted, O(log n)",
    "|   +-- Leaf pages → heap pointers",
    "|   +-- Height = 3-5 for any practical size",
    "|",
    "+-- WAL",
    "|   +-- Write intent BEFORE changing data",
    "|   +-- Enables: crash recovery, replication, PITR",
    "|   +-- Sequential append-only I/O",
    "|",
    "+-- MVCC",
    "|   +-- Multiple row versions (xmin, xmax)",
    "|   +-- Readers never block writers",
    "|   +-- Creates dead tuples → needs VACUUM",
    "|",
    "+-- VACUUM",
    "|   +-- Reclaims dead tuples",
    "|   +-- AUTOVACUUM runs automatically",
    "|   +-- VACUUM FULL locks table (avoid!)",
    "|",
    "+-- INDEX TYPES",
    "    +-- B-tree: default, =/</>",
    "    +-- GIN: JSONB, arrays",
    "    +-- BRIN: time-series",
    "    +-- Partial: WHERE condition",
    "    +-- CONCURRENTLY: no lock",
    "```",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **PostgreSQL Internals** by Hussein Nasser: https://www.youtube.com/watch?v=q8IEtTfwfVQ",
    "- **How Databases Work Internally** by CMU Database Group: https://www.youtube.com/playlist?list=PLSE8ODhjZXjbj8BMuIrRcacnQh20hmY9g",
    "",
    "### Books",
    "- **Database Internals** by Alex Petrov — excellent deep dive",
    "- **PostgreSQL 14 Internals** (free PDF): https://postgrespro.com/community/books/internals",
])

DBI_Q = [
    {"id":"dbi-q1","type":"mcq","prompt":"A B-tree index on a 1-billion row table — approximately how many disk page reads to find one row?",
     "choices":["1 billion (full scan)","log_100(1B) ≈ 5 page reads — B-tree branching factor ~100 per page, height stays very flat even at massive scale","10,000","100"],
     "answerIndex":1,"explanation":"B-tree height = log_branch_factor(N). PostgreSQL page = 8KB, can hold ~100+ key-pointer pairs. log100(1B) = log(1B)/log(100) = 9/2 = 4.5 → ~5 levels. Even for 1B rows, B-tree height rarely exceeds 5 reads. That's why indexes are transformatively fast.","tags":["b-tree","indexes","complexity"]},
    {"id":"dbi-q2","type":"mcq","prompt":"Write-Ahead Log (WAL) — what must happen before data pages can be modified?",
     "choices":["Data must be backed up","WAL record describing the change must be written and durably fsynced to disk first. Only then can the in-memory buffer pool be modified. If crash occurs before page flush, WAL enables recovery.","Memory must be cleared","Transaction must be committed"],
     "answerIndex":1,"explanation":"WAL guarantees: 'D' in ACID (durability). Write intent to WAL (sequential, fast) → modify memory → flush memory to disk eventually (async). If crash between WAL and disk flush: WAL has the intent, replay it on restart. Sequential WAL writes are much faster than random heap writes.","tags":["wal","durability","recovery"]},
    {"id":"dbi-q3","type":"mcq","prompt":"What are 'dead tuples' in PostgreSQL?",
     "choices":["Rows with NULL values","Row versions that are no longer visible to any active transaction — created by UPDATE (old version) and DELETE. They consume space and slow queries until VACUUM reclaims them.","Locked rows","Rows in temporary tables"],
     "answerIndex":1,"explanation":"UPDATE in PostgreSQL doesn't modify in-place. It marks old version deleted (xmax set) and inserts new version. Old version is a 'dead tuple' once no transaction can see it. Without VACUUM, dead tuples accumulate causing table bloat and slower sequential scans.","tags":["mvcc","vacuum","dead-tuples"]},
    {"id":"dbi-q4","type":"mcq","prompt":"MVCC allows readers to never block writers because:",
     "choices":["PostgreSQL uses locks for reading","Readers read old row versions (based on their transaction snapshot) while writers create new versions. Both access different versions simultaneously — no lock contention between readers and writers.","Reads are cached","Writers write to different tables"],
     "answerIndex":1,"explanation":"MVCC: each row version has xmin/xmax transaction IDs. Readers consult visibility rules (is xmin ≤ my txid AND xmax not set or > my txid?) to decide which version to read. Writer creates new version. They access different memory locations — no lock needed.","tags":["mvcc","concurrency"]},
    {"id":"dbi-q5","type":"mcq","prompt":"When should you use CREATE INDEX CONCURRENTLY over regular CREATE INDEX?",
     "choices":["CONCURRENTLY is always slower","In production systems where you can't afford table locks. Regular CREATE INDEX takes ShareLock (blocks writes). CONCURRENTLY doesn't lock but takes 2-3x longer and requires more work. Use CONCURRENTLY for live production tables.","CONCURRENTLY doesn't work on large tables","Regular index is deprecated"],
     "answerIndex":1,"explanation":"Regular CREATE INDEX: ShareLock on table — allows reads, blocks writes. For large tables this could take minutes/hours with writes blocked. CONCURRENTLY: does two passes, allows normal read/write throughout, takes longer but zero downtime. Standard practice for production index creation.","tags":["indexes","concurrency","production"]},
    {"id":"dbi-q6","type":"mcq","prompt":"What does ANALYZE do in PostgreSQL?",
     "choices":["Removes dead tuples","Collects statistics about column value distributions (histograms, most-common values, null fraction) — query planner uses these to estimate rows and choose execution plan. Run after bulk data changes.","Analyzes query syntax","Checks for index corruption"],
     "answerIndex":1,"explanation":"ANALYZE samples table rows, builds histograms per column. Planner uses these to estimate: 'WHERE status=shipped' → maybe 30% of rows. With stale stats: planner estimates 10 rows, does Nested Loop. Actual: 10M rows, should use Hash Join. ANALYZE = accurate estimates = good plans.","tags":["analyze","statistics","query-planner"]},
    {"id":"dbi-q7","type":"mcq","prompt":"When is a GIN index better than a B-tree index?",
     "choices":["GIN is always better","GIN excels at multi-value columns: JSONB fields, arrays, full-text search. A row can have multiple indexed values (e.g., tags array). B-tree handles only single scalar comparisons. GIN: one row maps to many index entries.","GIN is only for full-text","B-tree is deprecated"],
     "answerIndex":1,"explanation":"B-tree: one index entry per row. Perfect for single-value columns. GIN: multiple entries per row. Used for: JSONB containment (@>), array containment (@>), full-text (@@). Slower to build, larger, but enabling queries that B-tree simply can't do efficiently.","tags":["gin","indexes","jsonb"]},
    {"id":"dbi-q8","type":"mcq","prompt":"What is a heap in PostgreSQL database internals?",
     "choices":["The heap data structure (max/min)","The main table storage — unordered collection of 8KB pages containing row data. Indexes point into the heap via (page_number, slot_number). Unlike clustered tables in MySQL, PostgreSQL heap is unordered.","Memory for sorting","A temporary index"],
     "answerIndex":1,"explanation":"PostgreSQL heap = physical table storage. 8KB pages, each holding multiple row versions (tuples). Index leaf entries contain a 6-byte heap tuple ID (ctid): {page_number, slot_within_page}. Index scan: follow index → ctid → fetch from heap. Index-only scan: never touches heap if all columns are in index.","tags":["heap","storage","postgresql"]},
    {"id":"dbi-q9","type":"mcq","prompt":"Transaction ID wraparound in PostgreSQL — why is it dangerous?",
     "choices":["Cosmetic issue only","PostgreSQL transaction IDs are 32-bit integers (max ~2 billion). If wraparound occurs without VACUUM cleaning old txids, rows committed before the wrap look 'in the future' — database refuses to start to prevent data corruption.","WAL handles this automatically","Affects MySQL only"],
     "answerIndex":1,"explanation":"PostgreSQL uses txid for MVCC visibility. 32-bit txid: wraps after ~2.1 billion transactions. If VACUUM doesn't freeze old rows before wraparound, the DB shuts down to prevent showing wrong data to users. Age shown in: SELECT age(relfrozenxid) FROM pg_class. Alert when age approaches 200M.","tags":["vacuum","txid-wraparound","postgresql"]},
    {"id":"dbi-q10","type":"mcq","prompt":"What enables streaming replication in PostgreSQL?",
     "choices":["Shared memory","WAL records are sent from primary to standby replicas in real-time. Standby replays WAL records to stay current. Primary writes WAL anyway for durability — streaming is essentially a zero-cost side effect of the WAL.","Lock tables on primary","Network file system"],
     "answerIndex":1,"explanation":"Streaming replication: WAL records generated on primary are sent via TCP to standbys. Standbys replay WAL in recovery mode. This is synchronous (primary waits for ack before committing, wal_sync_method=remote_apply) or async. Read replicas serve read queries while primary handles writes.","tags":["wal","replication","postgresql"]},
    {"id":"dbi-q11","type":"mcq","prompt":"VACUUM vs VACUUM FULL — when should you use VACUUM FULL?",
     "choices":["Always use VACUUM FULL","VACUUM FULL: rewrites entire table to reclaim disk space back to OS. Takes exclusive lock (table unusable during). Use only when table has huge bloat (80%+ dead) and offline maintenance window is acceptable. Use pg_repack for zero-downtime compaction.","Never use VACUUM FULL","VACUUM FULL is faster"],
     "answerIndex":1,"explanation":"Regular VACUUM: marks dead space reusable but doesn't return to OS. Disk usage stays same. VACUUM FULL: physically rewrites table (like CLUSTER), disk space returned. But: takes AccessExclusiveLock — all reads and writes blocked. In production: schedule maintenance window or use pg_repack which does it without locks.","tags":["vacuum","bloat","postgresql"]},
    {"id":"dbi-q12","type":"mcq","prompt":"What is a 'covering index' also called in PostgreSQL 11+?",
     "choices":["Partial index","INCLUDE index — CREATE INDEX idx ON orders(user_id) INCLUDE (amount, status). user_id is the search key; amount and status are stored in leaf pages but not part of the tree. Enables index-only scans for queries fetching these columns.","Hash index","GIN index"],
     "answerIndex":1,"explanation":"INCLUDE clause adds non-key columns to leaf pages without making them part of the B-tree search structure. SELECT amount, status FROM orders WHERE user_id=42: index scan finds user_id=42, gets amount+status from same page — no heap fetch. Eliminates the 'heap lookup' step.","tags":["indexes","covering","include"]},
    {"id":"dbi-q13","type":"mcq","prompt":"PostgreSQL checkpoint — what is it?",
     "choices":["Manual backup","Point where all dirty buffer pages (modified in memory but not yet on disk) are flushed to disk. Checkpoint records this stable point in WAL. Recovery after crash: replay WAL from last checkpoint only (not entire WAL history).","Index rebuild","Statistics update"],
     "answerIndex":1,"explanation":"Without checkpoints: crash recovery replays WAL from beginning (could be hours). Checkpoints write all dirty pages to disk at regular intervals. Post-crash: replay only WAL after last checkpoint. Trade-off: more frequent checkpoints = faster recovery, more I/O. Configured via checkpoint_completion_target.","tags":["checkpoint","wal","recovery"]},
    {"id":"dbi-q14","type":"mcq","prompt":"What is the difference between MVCC in PostgreSQL and MySQL InnoDB?",
     "choices":["Only PostgreSQL has MVCC","PostgreSQL: stores old row versions in the same heap (all versions in main table). InnoDB: stores old versions in a separate 'undo log' segment, main clustered index always has latest version. Both achieve MVCC but different storage trade-offs.","MySQL doesn't support transactions","They are identical"],
     "answerIndex":1,"explanation":"PostgreSQL heap-based MVCC: dead versions pile up in-place, need VACUUM. InnoDB undo-log MVCC: clustered index is always latest, old versions in separate undo tablespace (auto-compacted). InnoDB: no VACUUM equivalent needed. PostgreSQL: needs autovacuum. Different architectural trade-offs.","tags":["mvcc","postgresql","innodb","comparison"]},
    {"id":"dbi-q15","type":"mcq","prompt":"BRIN index vs B-tree — when is BRIN appropriate?",
     "choices":["BRIN is always better","BRIN (Block Range Index) is tiny and fast for columns that are physically ordered in storage — e.g., auto-increment IDs, timestamps in append-only tables. Stores just min/max per block range. 100-1000x smaller than B-tree. Awful for random data.","BRIN is for booleans","B-tree and BRIN are equivalent"],
     "answerIndex":1,"explanation":"BRIN assumes correlation between column order and physical storage order. For time-series (INSERT always appends, timestamp always increasing): BRIN is perfect. Just store min/max timestamp per 128 pages. WHERE created_at > yesterday: BRIN quickly excludes old blocks. Random UUIDs: BRIN useless (no correlation).","tags":["brin","indexes","time-series"]},
    {"id":"dbi-q16","type":"mcq","prompt":"What does pg_stat_user_tables.n_dead_tup tell you?",
     "choices":["Number of deleted users","Number of dead (obsolete MVCC) tuple versions in the table not yet claimed by VACUUM. High values indicate autovacuum is behind or disabled. Should trigger manual VACUUM if approaching significant % of live tuples.","Table size","Query count"],
     "answerIndex":1,"explanation":"n_dead_tup: current count of dead tuples awaiting VACUUM. Formula: if n_dead_tup > autovacuum_vacuum_threshold + autovacuum_vacuum_scale_factor * n_live_tup, autovacuum will trigger. Monitor this to catch tables autovacuum can't keep up with (high-write tables).","tags":["vacuum","monitoring","postgresql"]},
    {"id":"dbi-q17","type":"mcq","prompt":"What is the purpose of PostgreSQL's shared_buffers setting?",
     "choices":["Total RAM on the server","Size of PostgreSQL's buffer pool — pages read from disk are cached here. Reads served from buffer pool: no disk I/O. Hit rate should be >99%. Rule of thumb: 25% of available RAM. Too small: thrashing. Too large: leaves no RAM for OS page cache.","Number of connections","WAL buffer size"],
     "answerIndex":1,"explanation":"shared_buffers is PostgreSQL's main cache. 8KB pages cached in shared memory. SELECT reads page from disk into shared_buffers, serves from there on subsequent reads. Check hit rate: SELECT sum(heap_blks_hit)/(sum(heap_blks_hit)+sum(heap_blks_read)) FROM pg_statio_user_tables. Target: 0.99+.","tags":["postgresql","shared-buffers","performance"]},
    {"id":"dbi-q18","type":"mcq","prompt":"Logical replication vs WAL streaming replication — key difference?",
     "choices":["No difference","WAL streaming: sends raw binary WAL records, must be same PostgreSQL major version, replicates everything. Logical: decodes WAL into SQL-level changes (INSERT/UPDATE/DELETE), can replicate subset of tables, works across versions and to other databases.","Logical is a backup strategy","WAL streaming is deprecated"],
     "answerIndex":1,"explanation":"Streaming: binary WAL → standby must match primary's exact version and architecture. All or nothing. Logical: decoded as table row changes → can subscribe from different PG version, or stream to Kafka, Debezium CDC. Used for: blue-green upgrades, event streaming, selective table replication.","tags":["replication","wal","logical-replication"]},
    {"id":"dbi-q19","type":"mcq","prompt":"What problem does the 'table bloat' cause for query performance?",
     "choices":["Queries fail","Sequential scan must read ALL pages including those with only dead tuples — larger physical table even if logically small. Index size also bloats. 100% live rows in 2x table size = 2x scan time.","Indexes stop working","Only affects backups"],
     "answerIndex":1,"explanation":"Bloat: table's physical size > logical data size due to dead tuples. Seq scan: reads every page regardless of dead/live. 1M table with 50% dead = physical table of 2M dead rows. Reads 2x the data. VACUUM reclaims space (marks reusable). VACUUM FULL compacts physically.","tags":["vacuum","bloat","performance"]},
    {"id":"dbi-q20","type":"mcq","prompt":"Index-only scan in PostgreSQL — when can it avoid touching the heap?",
     "choices":["Always","When all columns in the SELECT and WHERE are in the index (covering index) AND the visibility map marks the page as all-visible. PostgreSQL then skips the heap entirely — returns data from index pages only.","Only for B-tree indexes","Never actually avoids heap"],
     "answerIndex":1,"explanation":"Index-only scan: conditions: 1) All needed columns in index (INCLUDE or part of key). 2) Page's visibility map bit set to 'all-visible' (VACUUM sets this when page has no dead tuples). If VM bit not set: must visit heap to check row visibility. VACUUM keeps VM up-to-date, enabling index-only scans.","tags":["indexes","index-only-scan","visibility-map"]},
]

DBI_FC = [
    {"id":"dbi-fc1","front":"B-tree height for any row count","back":"Height = ceil(log_100(N)). 1M rows: 3 levels. 1B rows: 5 levels. Each level = 1 page read. B-tree is always at most 5-6 disk reads for any realistic table. That's why indexes transform performance from O(n) to O(log n).","tags":["b-tree","indexes"]},
    {"id":"dbi-fc2","front":"WAL guarantees","back":"Write intent to WAL (sequential, fast) BEFORE modifying data pages. Crash recovery: replay WAL from last checkpoint. Side effects: streaming replication, point-in-time recovery, logical decoding. WAL is the source of truth for PostgreSQL durability.","tags":["wal","durability"]},
    {"id":"dbi-fc3","front":"MVCC row version visibility rule","back":"Row visible if: xmin ≤ current_txid AND (xmax is null OR xmax > current_txid). xmin = transaction that created row. xmax = transaction that deleted/updated it. Enables readers to see consistent snapshots without locking.","tags":["mvcc","visibility"]},
    {"id":"dbi-fc4","front":"VACUUM triggers","back":"autovacuum fires when: n_dead_tup > vacuum_threshold + scale_factor * n_live_tup. Default: 50 + 20% of table. For high-write tables: lower scale_factor. Monitor: SELECT relname, n_dead_tup, last_autovacuum FROM pg_stat_user_tables.","tags":["vacuum","autovacuum"]},
    {"id":"dbi-fc5","front":"Index type selection","back":"B-tree: default, equality + range. Hash: equality only (rarely better than B-tree). GIN: JSONB, arrays, full-text. GiST: geometric, IP ranges. BRIN: time-series append-only tables (tiny, O(blocks) reads). Partial: WHERE condition reduces size.","tags":["indexes","types"]},
    {"id":"dbi-fc6","front":"Production index creation","back":"ALWAYS: CREATE INDEX CONCURRENTLY in production. Regular CREATE INDEX = ShareLock (blocks writes for minutes/hours on large tables). CONCURRENTLY takes 2-3x longer but zero impact on live traffic. Cannot be inside explicit transactions.","tags":["indexes","production","concurrently"]},
    {"id":"dbi-fc7","front":"Table bloat detection","back":"SELECT schemaname, relname, n_dead_tup, n_live_tup, last_autovacuum FROM pg_stat_user_tables WHERE n_dead_tup > 10000 ORDER BY n_dead_tup DESC. Bloat ratio: n_dead_tup/n_live_tup > 0.2 = investigate autovacuum settings.","tags":["vacuum","bloat","monitoring"]},
    {"id":"dbi-fc8","front":"Checkpoint and recovery","back":"Checkpoint = flush all dirty pages to disk. Marks position in WAL. Crash recovery: only replay WAL AFTER last checkpoint. More frequent = faster recovery, more I/O. checkpoint_completion_target=0.9 spreads I/O over 90% of checkpoint_timeout interval.","tags":["checkpoint","recovery","wal"]},
]

DBI_PROJ = {
    "brief": "Your PostgreSQL database serving 10 million users has developed serious performance problems: queries that took 10ms now take 5 seconds. Table orders has 500M rows. Diagnose and fix: identify the slow query, check for missing indexes, identify table bloat, verify statistics freshness, and create a maintenance strategy.",
    "checklist": [
        {"id":"dbi1","text":"EXPLAIN ANALYZE on slow query. Identify: Seq Scan on large table, wrong row estimates, missing index recommendation.","weight":20},
        {"id":"dbi2","text":"Create appropriate index type: B-tree for WHERE user_id + ORDER BY created_at. CONCURRENTLY to avoid production lock.","weight":20},
        {"id":"dbi3","text":"Check pg_stat_user_tables for n_dead_tup. If n_dead_tup/n_live_tup > 0.1: tune autovacuum or run manual VACUUM ANALYZE.","weight":20},
        {"id":"dbi4","text":"Verify statistics freshness: last_analyze timestamp in pg_stat_user_tables. Run ANALYZE if stale (row estimates wrong by 10x).","weight":20},
        {"id":"dbi5","text":"Maintenance schedule: autovacuum tune for high-write tables (lower scale_factor=0.02), checkpoint alerts, txid wraparound monitoring.","weight":20},
    ],
    "hints": [
        "pg_stat_statements extension tracks cumulative query statistics: total_time, calls, mean_time. Install to identify worst queries.",
        "Partial index win: CREATE INDEX CONCURRENTLY idx_pending ON orders(user_id, created_at) WHERE status='pending' — orders without status='pending' excluded.",
        "CLUSTER orders USING idx_orders_user_created (rewrites table in index order) — only if you can afford the downtime. Dramatically improves range scans.",
    ]
}

write("security", "database-internals.json", {
    "id": "database-internals",
    "unit": 11,
    "order": 117,
    "title": "Database Internals",
    "summary": "B-tree indexes, WAL, MVCC, VACUUM, and PostgreSQL internals for writing better queries and maintaining healthy databases.",
    "prereqs": ["relational-databases"],
    "guide": DBI_GUIDE,
    "questions": DBI_Q,
    "flashcards": DBI_FC,
    "project": DBI_PROJ,
})

print("\n=== Batch 3a Complete ===")
print("Written to src/content/topics/security/")
print("  - distributed-systems.json")
print("  - database-internals.json")
print("")
print("💡 After these heavy topics, try lighter ones:")
print("  - regex (30 min topic, very practical)")
print("  - python-fundamentals (already created)")
print("  - git-advanced (already created)")

