"""
Batch 3b: observability (order 118) → security/ folder
Run: python3 scripts/new_topics_batch3b.py
💡 After this heavy topic, try: python-fundamentals, regex, git-advanced
"""
import json
from pathlib import Path

BASE = Path(__file__).parent.parent / "src/content/topics"


def write(folder, filename, data):
    out = BASE / folder / filename
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists():
        existing = json.loads(out.read_text())
        if len(existing.get("questions", [])) >= 20:
            print(f"  SKIP {filename} (already complete)")
            return
    out.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    print(f"  WROTE {filename}: guide={len(data['guide'])} q={len(data['questions'])} fc={len(data['flashcards'])}")


OBS_GUIDE = "\n".join([
    "# Observability",
    "",
    "## What Is Observability?",
    "",
    "Observability is the ability to understand what is happening inside your system",
    "by examining its outputs — without needing to add new code or restart the system.",
    "",
    "```",
    "MONITORING (old way):    Did alarm X fire? (pre-defined questions)",
    "OBSERVABILITY (new way): Why is p99 latency high for users in Tokyo? (unknown questions)",
    "",
    "You can only answer unknown questions if you have rich enough data.",
    "Observability = you can investigate any production problem without deploying code.",
    "```",
    "",
    "**The Three Pillars:**",
    "```",
    "LOGS        METRICS       TRACES",
    "  │              │              │",
    "  ▼              ▼              ▼",
    "What happened  How healthy   Why this request",
    "in detail      is the system  was slow",
    "",
    "2026-01-15 ERROR   cpu: 87%      req → serviceA(12ms)",
    "NullPointer in     mem: 4GB          → DB query(340ms) ← slow!",
    "UserService        errors: 0/min     → cache(1ms)",
    "```",
    "",
    "---",
    "",
    "## Logs — What Happened",
    "",
    "```",
    "STRUCTURED vs UNSTRUCTURED logs:",
    "",
    "Unstructured (bad):",
    "  2026-01-15 10:23:45 ERROR User 42 login failed from IP 1.2.3.4",
    "  Hard to query, parse, or aggregate programmatically.",
    "",
    "Structured (good — JSON):",
    "  {",
    "    'timestamp': '2026-01-15T10:23:45Z',",
    "    'level': 'ERROR',",
    "    'event': 'login_failed',",
    "    'user_id': 42,",
    "    'ip': '1.2.3.4',",
    "    'reason': 'invalid_password',",
    "    'service': 'auth-service',",
    "    'trace_id': 'abc123def456'",
    "  }",
    "",
    "Why structured?",
    "  Search all login failures for user 42: user_id=42 AND event=login_failed",
    "  Count failed logins per IP: group by ip WHERE event=login_failed",
    "  Join with traces: trace_id links log to the full request trace",
    "```",
    "",
    "```",
    "LOG LEVELS (in order of severity):",
    "  DEBUG:   Detailed diagnostic info (disable in production — too noisy)",
    "  INFO:    Normal operations (user logged in, order placed)",
    "  WARN:    Unexpected but handled (retry attempt 2/3, cache miss)",
    "  ERROR:   Error that should be investigated (DB connection failed)",
    "  FATAL:   System cannot continue (OOM, can't start)",
    "",
    "Log sampling: HIGH-TRAFFIC services can emit 1M logs/sec.",
    "  Sample 1% of INFO/DEBUG, 100% of WARN/ERROR.",
    "  Reduces cost 100x without losing critical events.",
    "```",
    "",
    "---",
    "",
    "## Metrics — How Healthy",
    "",
    "```",
    "A metric is a NUMERIC measurement over time.",
    "",
    "Types (USE method):",
    "  Utilisation: what % of resource is in use? (CPU 87%, disk 60%)",
    "  Saturation:  work queued, can't handle? (queue depth 5000)",
    "  Errors:      failure rate? (500 errors / min)",
    "",
    "The Four Golden Signals (Google SRE book):",
    "  1. Latency:     How long does a request take? (p50, p95, p99)",
    "  2. Traffic:     How much demand? (requests/sec, bytes/sec)",
    "  3. Errors:      How many are failing? (error rate %)",
    "  4. Saturation:  How full is the system? (CPU, memory, queue)",
    "",
    "Why percentiles matter:",
    "  Average latency: 50ms  ← hides outliers",
    "  p50: 20ms              ← half of users under 20ms",
    "  p95: 200ms             ← 95% under 200ms, 5% slower",
    "  p99: 2000ms            ← 1% of users wait 2 seconds!",
    "  Always monitor p99 for user-facing systems.",
    "```",
    "",
    "---",
    "",
    "## Prometheus — Metrics Collection",
    "",
    "```",
    "Prometheus is a pull-based time-series database for metrics.",
    "Services expose a /metrics endpoint, Prometheus scrapes it every 15s.",
    "",
    "Architecture:",
    "  Your Service  ──/metrics──►  Prometheus  ──►  Grafana",
    "  (exposes metrics)           (scrapes + stores)  (visualises)",
    "",
    "Prometheus metric types:",
    "  Counter:    Cumulative, only increases. (total_requests, total_errors)",
    "  Gauge:      Can go up or down. (current_connections, memory_usage)",
    "  Histogram:  Distribution of values. (request_duration_seconds)",
    "  Summary:    Sliding window percentiles. (less flexible than histogram)",
    "",
    "Metric naming convention: service_subsystem_unit",
    "  http_requests_total",
    "  http_request_duration_seconds",
    "  jvm_memory_used_bytes",
    "",
    "PromQL query examples:",
    "  # Requests per second (rate over 5 min window):",
    "  rate(http_requests_total[5m])",
    "",
    "  # Error rate (%):",
    "  rate(http_requests_total{status='500'}[5m])",
    "  / rate(http_requests_total[5m]) * 100",
    "",
    "  # 99th percentile latency:",
    "  histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))",
    "",
    "  # Memory usage for a specific pod:",
    "  container_memory_usage_bytes{pod='my-app-abc123'}",
    "```",
    "",
    "---",
    "",
    "## Grafana — Visualisation",
    "",
    "```",
    "Grafana is a dashboard platform that queries Prometheus (and other sources).",
    "",
    "Standard Production Dashboard panels:",
    "+─────────────────────────────────────────────────────────+",
    "│  Requests/sec      │  Error Rate (%)    │  p99 Latency   │",
    "│  ▁▂▃▄▅▆▇█▇▆▅       │  0.1% ↑ 0.8% !!    │  45ms → 280ms  │",
    "+─────────────────────────────────────────────────────────+",
    "│  CPU Usage (%)     │  Memory (GB)       │  Pod Count     │",
    "│  ████░░░░ 42%      │  ████████████ 14GB │  10 → 12 pods  │",
    "+─────────────────────────────────────────────────────────+",
    "│  Active DB Connections  │  Queue Depth  │  Cache Hit Rate│",
    "+─────────────────────────────────────────────────────────+",
    "",
    "Alerting in Grafana/Prometheus:",
    "  # Alert if error rate > 1% for 5 minutes:",
    "  - alert: HighErrorRate",
    "    expr: rate(http_requests_total{status='500'}[5m])",
    "          / rate(http_requests_total[5m]) > 0.01",
    "    for: 5m",
    "    labels:",
    "      severity: critical",
    "    annotations:",
    "      summary: 'Error rate {{ $value | humanizePercentage }}'",
    "```",
    "",
    "---",
    "",
    "## Distributed Tracing — Why This Request Was Slow",
    "",
    "```",
    "PROBLEM: User complains request took 3 seconds.",
    "  Logs: 'request completed in 3001ms'",
    "  But: which of the 8 microservices was slow?",
    "",
    "DISTRIBUTED TRACE: records the entire journey of one request",
    "across ALL services, with timing for each hop.",
    "",
    "Trace ID: abc123 (generated at entry, propagated in headers)",
    "",
    "  Span 1: API Gateway          0ms → 3001ms (3001ms total)",
    "  |─ Span 2: Auth Service      1ms → 12ms   (11ms)",
    "  |─ Span 3: Order Service     13ms → 3000ms (2987ms)  ← HERE",
    "     |─ Span 4: DB Select      14ms → 2800ms (2786ms)  ← HERE",
    "     |─ Span 5: Cache Get      2801ms → 2805ms (4ms)",
    "     |─ Span 6: Email API      2806ms → 3000ms (194ms)",
    "",
    "Root cause: DB Select took 2.786 seconds.",
    "Without tracing: you'd have to add logging to every service and re-deploy.",
    "",
    "W3C Trace Context headers:",
    "  traceparent: 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01",
    "                  version  trace-id (32 hex)              span-id  flags",
    "```",
    "",
    "---",
    "",
    "## OpenTelemetry — The Standard",
    "",
    "```",
    "OpenTelemetry (OTel) = vendor-neutral standard for logs, metrics, traces.",
    "",
    "Before OTel: different SDK per vendor (Datadog agents, New Relic agents...)",
    "  → Switching vendors = rewriting all instrumentation",
    "",
    "With OTel: one SDK, one protocol (OTLP), any backend",
    "  → Switch from Jaeger to Datadog: just change exporter config",
    "",
    "OTel Architecture:",
    "",
    "  Your App",
    "  + OTel SDK (auto and manual instrumentation)",
    "      │",
    "      │ OTLP (gRPC or HTTP)",
    "      ▼",
    "  OTel Collector (receives, processes, exports)",
    "      │",
    "      ├─► Jaeger (traces)",
    "      ├─► Prometheus (metrics)",
    "      └─► Loki (logs)",
    "",
    "Java auto-instrumentation (zero code changes!):",
    "  java -javaagent:opentelemetry-javaagent.jar \\",
    "       -Dotel.service.name=my-service \\",
    "       -Dotel.exporter.otlp.endpoint=http://collector:4317 \\",
    "       -jar myapp.jar",
    "  # Automatically instruments: HTTP, JDBC, Redis, Kafka, gRPC, etc.",
    "",
    "Manual span:",
    "  Tracer tracer = GlobalOpenTelemetry.getTracer('my-component');",
    "  Span span = tracer.spanBuilder('processOrder').startSpan();",
    "  try (Scope scope = span.makeCurrent()) {",
    "    span.setAttribute('order.id', orderId);",
    "    // do work",
    "  } catch (Exception e) {",
    "    span.recordException(e);",
    "    span.setStatus(StatusCode.ERROR, e.getMessage());",
    "  } finally {",
    "    span.end();",
    "  }",
    "```",
    "",
    "---",
    "",
    "## SLI / SLO / SLA — Error Budgets",
    "",
    "```",
    "SLI (Service Level Indicator): the actual measurement",
    "  'What percentage of requests completed in < 200ms?'",
    "  SLI = successful_requests / total_requests",
    "",
    "SLO (Service Level Objective): the target you set for yourself",
    "  '99.9% of requests must complete in < 200ms over a rolling 30-day window'",
    "  SLO = 99.9% — internal team agreement",
    "",
    "SLA (Service Level Agreement): contractual promise to customers",
    "  '99.5% uptime or you get service credits'",
    "  SLA is weaker than SLO (you set SLO tighter than SLA for headroom)",
    "",
    "ERROR BUDGET: how much failure is allowed before SLO is breached",
    "  SLO 99.9% → error budget = 0.1% = 43.2 min/month",
    "  SLO 99.99% → error budget = 0.01% = 4.3 min/month",
    "",
    "Using error budgets:",
    "  Budget remaining? → teams can deploy new features safely",
    "  Budget exhausted?  → freeze deployments, focus on reliability",
    "  Engineer teams and product teams SHARE the error budget",
    "  → Both are motivated to maintain reliability",
    "",
    "Common SLOs:",
    "  Availability SLO: 99.9% of requests return non-5xx",
    "  Latency SLO:      p99 latency < 500ms",
    "  Freshness SLO:    search index updated within 10 minutes",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "OBSERVABILITY",
    "|",
    "+-- THREE PILLARS",
    "|   +-- Logs: what happened (structured JSON)",
    "|   +-- Metrics: numeric health (Prometheus)",
    "|   +-- Traces: request journey (Jaeger/Zipkin)",
    "|",
    "+-- METRICS",
    "|   +-- Four Golden Signals: latency, traffic, errors, saturation",
    "|   +-- Prometheus: Counter/Gauge/Histogram",
    "|   +-- PromQL: rate(), histogram_quantile()",
    "|   +-- Grafana: dashboards + alerting",
    "|",
    "+-- TRACING",
    "|   +-- Trace ID propagated across services",
    "|   +-- Spans: named timed operations",
    "|   +-- OpenTelemetry: vendor-neutral standard",
    "|   +-- W3C traceparent header",
    "|",
    "+-- SLI/SLO/SLA",
    "    +-- SLI: actual measurement",
    "    +-- SLO: internal target (tighter than SLA)",
    "    +-- SLA: contractual promise",
    "    +-- Error budget: 100% - SLO% of time allowed to fail",
    "```",
    "",
    "---",
    "",
    "## How Observability Connects to Other Topics",
    "",
    "- **Kubernetes**: Prometheus scrapes pod /metrics endpoints. K8s cluster metrics (node CPU,",
    "  pod restarts) via kube-state-metrics and node-exporter.",
    "- **CI/CD**: Deploy → watch dashboards. Error budget depleted → CI/CD gate pauses deployments.",
    "- **Distributed Systems**: Traces span multiple microservices. Identify which service breaks SLO.",
    "- **AWS**: CloudWatch = AWS-native metrics/logs. X-Ray = AWS-native traces. OTel can export to all.",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **Observability: Logs, Metrics, Traces** by IBM Technology:",
    "  https://www.youtube.com/watch?v=CAQ_a2-9UOI",
    "- **Prometheus and Grafana setup** by TechWorld with Nana:",
    "  https://www.youtube.com/watch?v=QoDqxm7ybLc",
    "",
    "### Articles",
    "- **Google SRE Book** (free): https://sre.google/sre-book/monitoring-distributed-systems/",
    "- **OpenTelemetry docs**: https://opentelemetry.io/docs/",
    "- **Prometheus PromQL cheatsheet**: https://promlabs.com/promql-cheat-sheet/",
])

OBS_Q = [
    {"id":"obs-q1","type":"mcq","prompt":"What are the Three Pillars of Observability?",
     "choices":["CPU, Memory, Disk","Logs, Metrics, Traces — each answers a different question: Logs=what happened, Metrics=how healthy, Traces=why this request was slow","Alerts, Dashboards, Reports","Prometheus, Grafana, Jaeger"],
     "answerIndex":1,"explanation":"The three pillars are complementary: logs give event detail ('NullPointerException in UserService'), metrics show aggregate health (error rate spiky), traces show end-to-end request path across microservices. You need all three for full observability.","tags":["observability","pillars"]},
    {"id":"obs-q2","type":"mcq","prompt":"What are Google's Four Golden Signals for monitoring?",
     "choices":["CPU, Memory, Disk, Network","Latency (how long), Traffic (how much), Errors (how many fail), Saturation (how full) — these four cover virtually all production service health questions","Uptime, Downtime, Recovery, Alerts","P50, P95, P99, P999"],
     "answerIndex":1,"explanation":"Google SRE: monitoring any service starts with four signals. Latency: p50/p95/p99. Traffic: req/sec. Errors: 4xx/5xx rate. Saturation: CPU%, memory%, queue depth. If these four are green, the service is healthy. Drill into logs/traces when they're red.","tags":["metrics","golden-signals"]},
    {"id":"obs-q3","type":"mcq","prompt":"Why is p99 latency more important than average latency for user-facing APIs?",
     "choices":["p99 is easier to compute","Average masks outliers: avg=50ms might mean p99=2s (1% of users wait 2 seconds). p99 directly tells you: '1 in 100 requests is very slow'. For 1M req/day that's 10,000 bad experiences.","p99 is cheaper to store","Average latency includes errors"],
     "answerIndex":1,"explanation":"Average latency is misleading with skewed distributions. 99 fast requests (10ms) + 1 slow (2000ms) = average 29ms, p99=2000ms. Users experiencing the slow tail complain. SLOs are set on percentiles (p95 < 200ms) not averages. Always alert on percentiles.","tags":["metrics","latency","percentiles"]},
    {"id":"obs-q4","type":"mcq","prompt":"Prometheus metric type: what is a Counter?",
     "choices":["Metric that decreases over time","Metric that only increases monotonically — total requests, total errors. Use rate() in PromQL to compute rate of change. Never reset to 0 (unless process restarts, handled by rate() automatically).","Current value snapshot","Distribution of values"],
     "answerIndex":1,"explanation":"Counter: starts at 0, only increments. http_requests_total{status=200} = 500000. To get req/sec: rate(http_requests_total[5m]). rate() handles counter resets. Wrong usage: using Counter for current connections (should be Gauge — can go down when connections close).","tags":["prometheus","metrics","counter"]},
    {"id":"obs-q5","type":"mcq","prompt":"In a distributed trace, what is a 'span'?",
     "choices":["The entire trace","A named, timed operation representing one unit of work within a request — e.g., 'DB Query', 'HTTP call to AuthService'. Multiple spans form a trace tree. Each span has: trace_id, span_id, parent_span_id, name, duration, status.","An error in the trace","A metric measurement"],
     "answerIndex":1,"explanation":"Span = one hop in the trace. Trace = tree of spans. Root span: API Gateway receives request. Child spans: calls to downstream services, DB queries, cache lookups. Span attributes add context: db.statement, http.url, user.id. Visualised as a Gantt chart in Jaeger/Zipkin.","tags":["tracing","spans"]},
    {"id":"obs-q6","type":"mcq","prompt":"How is a trace ID propagated across microservices?",
     "choices":["Stored in database","Passed in HTTP headers (W3C traceparent standard or X-B3-TraceId). Each service reads the header, creates a child span with same trace_id, makes downstream calls with header attached. Entire chain shares one trace_id.","Via shared memory","Through message queues only"],
     "answerIndex":1,"explanation":"W3C traceparent header format: 00-{trace_id}-{span_id}-{flags}. Service A generates trace_id, passes it to Service B in header. B creates child span referencing A's span_id as parent. All spans with same trace_id are combined into one trace view in Jaeger.","tags":["tracing","trace-propagation"]},
    {"id":"obs-q7","type":"mcq","prompt":"What is OpenTelemetry and why does it matter?",
     "choices":["An open-source monitoring tool","Vendor-neutral standard for instrumentation (logs, metrics, traces). One SDK. Switch backends (Jaeger → Datadog → Honeycomb) by changing only exporter config, not application code. Prevents vendor lock-in.","A JavaScript testing library","AWS-specific monitoring"],
     "answerIndex":1,"explanation":"Before OTel: switching from Datadog to New Relic meant rewriting all instrumentation in every service. OTel: one SDK, OTLP protocol, any backend. OTel Collector can route to multiple backends simultaneously. Java agent auto-instruments JVM frameworks with zero code changes.","tags":["opentelemetry","vendor-neutral"]},
    {"id":"obs-q8","type":"mcq","prompt":"SLO of 99.9% availability — what is the monthly error budget?",
     "choices":["1 minute","0.1% × 30 days × 24 hours × 60 minutes = 43.2 minutes. Any downtime consumes this budget. When exhausted: freeze new deployments until budget resets next month.","100 minutes","10 minutes"],
     "answerIndex":1,"explanation":"Error budget = (1 - SLO%) × time period. 99.9% SLO = 0.1% failure allowed. Per month: 43.2 minutes total downtime/slowness allowed. This converts abstract '99.9%' into tangible '43 minutes' that engineers understand. Track in real-time to know current budget remaining.","tags":["slo","error-budget"]},
    {"id":"obs-q9","type":"mcq","prompt":"What is the difference between SLO and SLA?",
     "choices":["SLO is more lenient than SLA","SLO is your internal target (stricter). SLA is what you contractually promise customers (more lenient). If SLO=99.9%, SLA might be 99.5%. SLO breach alerts your team. SLA breach triggers customer compensation.","SLA and SLO are identical","SLA is for databases only"],
     "answerIndex":1,"explanation":"SLO is tighter than SLA intentionally. If SLA requires 99.5%, set SLO at 99.9%. When SLO is breached, you have headroom before SLA breach occurs. Teams are alerted at SLO breach. Customers are compensated at SLA breach. Buffer between them prevents SLA violations.","tags":["slo","sla"]},
    {"id":"obs-q10","type":"mcq","prompt":"PromQL query: rate(http_requests_total{status='500'}[5m]) / rate(http_requests_total[5m]) — what does this compute?",
     "choices":["Total requests","Error rate — ratio of 500 errors to all requests over 5-minute sliding window. Returns a value between 0 and 1 (multiply by 100 for percentage). Standard alert expression.","Request throughput","Average latency"],
     "answerIndex":1,"explanation":"rate(counter[window]): per-second rate of increase over window. Dividing error rate by total rate = fraction of requests that errored. If result > 0.01 (1%), alert fires. 5m window smooths out spikes while remaining responsive to sustained errors.","tags":["prometheus","promql","error-rate"]},
    {"id":"obs-q11","type":"mcq","prompt":"Why use structured logging (JSON) instead of unstructured text logs?",
     "choices":["JSON is smaller","Structured logs are machine-queryable: filter by user_id=42, count events by type, join with traces via trace_id. Text logs require fragile regex to parse. Log aggregation platforms (Loki, Splunk, CloudWatch) work far better with structured data.","Structured logs are human-readable only","Required by Kubernetes"],
     "answerIndex":1,"explanation":"Unstructured: '2026-01-15 ERROR User 42 login failed' — parse with regex to extract user 42. Structured JSON: {user_id:42, event:'login_failed'} — direct field query. In production with millions of logs/day, structured queries save hours of investigation time.","tags":["logging","structured-logs"]},
    {"id":"obs-q12","type":"mcq","prompt":"Prometheus uses a 'pull' model — what does this mean?",
     "choices":["Services push metrics to Prometheus","Prometheus actively scrapes /metrics endpoints on each service every 15 seconds. Services don't need to know about Prometheus. Benefit: central control of scrape rate, easy service discovery, dead services immediately visible (no scrape response).","Pull means sampling","Prometheus uses event-driven collection"],
     "answerIndex":1,"explanation":"Pull model: Prometheus has a list of targets, periodically GETs /metrics from each. Push model (Graphite, StatsD): apps push metrics to central server. Pull advantages: Prometheus controls rate, easier to monitor availability (missing scrape = alert), no config needed in apps beyond exposing /metrics.","tags":["prometheus","pull-model"]},
    {"id":"obs-q13","type":"mcq","prompt":"What does log sampling at 1% mean, and when is it appropriate?",
     "choices":["Keep 1% of errors","For high-volume low-severity logs (DEBUG/INFO): only keep 1 in 100 log entries. Reduces storage/cost by 100x while preserving statistical representation. Errors (WARN/ERROR) should NEVER be sampled — always keep 100%.","Log to 1% of servers","1% of users are logged"],
     "answerIndex":1,"explanation":"10,000 req/sec × verbose INFO logs = 10,000 log events/sec. At $0.50/GB: could be $10K+/month. Sample 1% INFO: keep 100/sec, save 99%. As long as you keep 100% of errors, you don't lose critical information. Tail sampling in OTel: always keep traces with errors.","tags":["logging","sampling","cost"]},
    {"id":"obs-q14","type":"mcq","prompt":"Prometheus Histogram vs Summary — which is better for p99 latency across multiple instances?",
     "choices":["Summary is better","Histogram: counters per bucket, aggregatable across instances (histogram_quantile(0.99, sum(rate(...)...))). Summary: pre-computed quantiles on each instance — cannot be aggregated. For multi-instance services, always use Histogram.","They are identical","Gauge for latency"],
     "answerIndex":0,"explanation":"Summary computes quantiles client-side per process — you can't sum two summaries' p99s. Histogram stores bucket counts (requests_under_10ms, requests_under_50ms, etc.) — additive. histogram_quantile() approximates any quantile across aggregated fleet. Use Histogram for latency in distributed services.","tags":["prometheus","histogram","summary"]},
    {"id":"obs-q15","type":"mcq","prompt":"What is a Grafana alert and how does it fire?",
     "choices":["Alert fires on every metric change","Alert = Prometheus/Grafana rule: if a PromQL expression returns > threshold for 'for' duration, fire. 'for 5m' means condition must hold for 5 minutes — prevents flapping on momentary spikes. Alert routes to PagerDuty/Slack/email.","Alerts require manual trigger","Alerts are for billing only"],
     "answerIndex":1,"explanation":"Alert rule: EXPR > THRESHOLD for DURATION. The 'for' clause prevents alert storms from momentary spikes. Alert states: Pending (threshold breached but not long enough) → Firing (duration exceeded) → Resolved (condition cleared). Always set 'for' to at least 2 metrics scrape intervals.","tags":["grafana","alerting"]},
    {"id":"obs-q16","type":"multi","prompt":"Which should be captured in a distributed trace span? (Select all)",
     "choices":["HTTP method and URL for external calls","Database query text (sanitised, no PII)","User's password","Service name and span duration"],
     "answerIndexes":[0,1,3],"explanation":"Span attributes add context for debugging: http.method, http.url, db.statement (sanitised — no user values which could be PII), service.name, duration. Never log passwords, tokens, or PII in traces (visible to all engineers in tracing tools).","tags":["tracing","span-attributes","security"]},
    {"id":"obs-q17","type":"mcq","prompt":"What is the OTel Collector and why use it as an intermediary?",
     "choices":["A metrics storage system","Receives telemetry from apps (OTLP), can filter/sample/enrich, then routes to multiple backends. Benefits: consistent sampling, vendor switch without app changes, handles retries, fan-out to multiple destinations.","A log viewer","Kubernetes-specific tool"],
     "answerIndex":1,"explanation":"Without Collector: apps send directly to backend — switching means config change in every service. With Collector: pipeline of processors (add K8s metadata, sample 10% of traces, enrich with environment). Route to Jaeger for dev, Datadog in prod — change one config file.","tags":["opentelemetry","collector"]},
    {"id":"obs-q18","type":"mcq","prompt":"Error budget policy: team has consumed 80% of monthly error budget by day 15. What should happen?",
     "choices":["Keep deploying normally","High-risk deployments paused or require extra approval. Team shifts focus to reliability work. This prevents depleting remaining 20% budget with new risky features.","Reset budget","Ignore — this is normal"],
     "answerIndex":1,"explanation":"Error budget is risk currency. 80% consumed in half the month = trending to exhaust budget. Standard policy: >50% consumed → slow deployment cadence. >100% consumed → feature freeze, only reliability fixes. Budget recovered when new month starts (or errors stop).","tags":["slo","error-budget","policy"]},
    {"id":"obs-q19","type":"mcq","prompt":"kube-state-metrics vs metrics-server in Kubernetes observability — difference?",
     "choices":["Identical","kube-state-metrics: exposes K8s object state (Deployment replica counts, Pod status, PVC capacity) to Prometheus — for long-term trend analysis. metrics-server: node CPU/memory snapshots for kubectl top and HPA — not for Prometheus scraping.","metrics-server is for tracing","kube-state-metrics is for logging"],
     "answerIndex":1,"explanation":"metrics-server: lightweight, in-memory, powers kubectl top and HPA. Not persistent. kube-state-metrics: exposes gauge/counter for every K8s object. Used with Prometheus for: 'how many pods are in CrashLoopBackOff?' or 'what's the history of Deployment replica changes?'","tags":["kubernetes","prometheus","monitoring"]},
    {"id":"obs-q20","type":"mcq","prompt":"What is 'cardinality' in Prometheus context, and why does high cardinality cause problems?",
     "choices":["Metric accuracy","The number of unique label value combinations for a metric. High cardinality (e.g., labelling by user_id = millions of values) creates millions of time series, causing memory explosion in Prometheus and slow queries.","Metric retention period","Alert frequency"],
     "answerIndex":1,"explanation":"Each unique label set = one time series. http_requests_total{path='/api/users/42'} — one series per user ID = millions of series. Prometheus stores all in memory. At 100M series: out of memory. Rule: never use high-cardinality values (user IDs, trace IDs, UUIDs) as Prometheus labels. Use histograms for distributions instead.","tags":["prometheus","cardinality","performance"]},
]

OBS_FC = [
    {"id":"obs-fc1","front":"Three pillars of observability","back":"Logs: structured JSON events (what happened, user_id, error detail). Metrics: numeric time-series (Prometheus — req/sec, p99). Traces: request journey across services (Jaeger — which service was slow). Use all three for full visibility.","tags":["observability","pillars"]},
    {"id":"obs-fc2","front":"Four Golden Signals","back":"Latency (p50/p95/p99 response time), Traffic (requests/sec), Errors (4xx/5xx rate %), Saturation (CPU%, memory%, queue depth). Alert on all four. Dashboard always shows these prominently. From Google SRE book.","tags":["metrics","golden-signals"]},
    {"id":"obs-fc3","front":"Prometheus Counter vs Gauge vs Histogram","back":"Counter: only increases (total_requests). rate() for per-sec rate. Gauge: up/down snapshot (memory_usage_bytes, active_connections). Histogram: distribution (request_duration_seconds_bucket). histogram_quantile(0.99,...) for p99. Never use Summary for multi-instance.","tags":["prometheus","metric-types"]},
    {"id":"obs-fc4","front":"SLO error budget formula","back":"Error budget = (1 - SLO%) × time period. 99.9% SLO/month = 0.1% × 43,200 min = 43.2 min. Monitor in real-time. >80% consumed: slow deployments. Exhausted: feature freeze. Budget resets on period boundary.","tags":["slo","error-budget"]},
    {"id":"obs-fc5","front":"Distributed trace anatomy","back":"Trace = tree of Spans. Span = named timed unit (DB Query, HTTP call). All spans share trace_id. Parent-child via span_id. Propagated via HTTP headers (W3C traceparent). Visualised as Gantt chart. Root cause: find the widest/longest child span.","tags":["tracing","spans"]},
    {"id":"obs-fc6","front":"OpenTelemetry Java zero-code setup","back":"java -javaagent:opentelemetry-javaagent.jar -Dotel.service.name=my-service -Dotel.exporter.otlp.endpoint=http://collector:4317 -jar app.jar. Auto-instruments: HTTP, JDBC, Redis, Kafka, gRPC. No source code changes needed.","tags":["opentelemetry","java"]},
    {"id":"obs-fc7","front":"Prometheus cardinality rule","back":"Never use high-cardinality values as metric labels: no user_id, no trace_id, no UUID. Each unique label combination = separate time series (RAM). OK labels: service, method, status_code, region. Bad: user_id=42, path=/users/42.","tags":["prometheus","cardinality"]},
    {"id":"obs-fc8","front":"Alert rule best practices","back":"Always use 'for' clause (avoid flapping): for: 5m. Alert on symptoms (high error rate) not causes (high CPU). Page on customer impact only. Automate runbooks. Alert fatigue = engineers ignore alerts = missed incidents.","tags":["alerting","sre"]},
]

OBS_PROJ = {
    "brief": "Your microservices-based e-commerce platform has 8 services. Customers report intermittent checkout failures. Design a complete observability stack: what metrics, logs, and traces you would add, what dashboards and alerts to create, how to find the root cause of the checkout failures, and what SLO you would define for the checkout flow.",
    "checklist": [
        {"id":"o1","text":"Metrics: checkout_requests_total counter, checkout_duration_seconds histogram, payment_failures_total counter with label reason","weight":20},
        {"id":"o2","text":"Structured logs with trace_id field so you can jump from log to trace. Log ERROR on payment failure with order_id, user_id, error_type.","weight":20},
        {"id":"o3","text":"OTel trace spans for: UI→APIGateway→OrderService→PaymentService→BankAPI. Span attributes: payment.amount, payment.provider, order.id","weight":20},
        {"id":"o4","text":"SLO: 99.9% of checkout requests complete successfully within 3 seconds. Error budget: 43.2 min/month downtime equivalent.","weight":20},
        {"id":"o5","text":"Root cause workflow: Grafana error rate spike → trace any error → find wide span → check that service logs → find ERROR with cause","weight":20},
    ],
    "hints": [
        "The trace_id as a structured log field is the key bridge: from log error to full request trace in one click.",
        "Grafana exemplars: histogram metrics can store sample trace_ids so you can jump from a p99 data point to the actual slow trace.",
        "Bank API latency is often the culprit — add checkout_external_api_duration_seconds with label provider=bank_name.",
    ]
}

write("security", "observability.json", {
    "id": "observability",
    "unit": 11,
    "order": 118,
    "title": "Observability",
    "summary": "Logs, metrics, traces — using Prometheus, Grafana, OpenTelemetry, and SLI/SLO/SLA error budgets to understand production systems.",
    "prereqs": ["distributed-systems"],
    "guide": OBS_GUIDE,
    "questions": OBS_Q,
    "flashcards": OBS_FC,
    "project": OBS_PROJ,
})

print("\n=== Batch 3b Complete ===")
print("Written: src/content/topics/security/observability.json")
print("")
print("💡 observability is a heavy topic! Try these lighter ones next:")
print("  - python-fundamentals (already done — decorators, generators)")
print("  - regex (pattern matching — 1-2hr topic, very practical)")
print("  - git-advanced (already done — cherry-pick, hooks)")

