"""
Batch 2: Languages & Scripting (Unit 12)
  - sql-advanced (order 113) — CTEs, window functions, EXPLAIN
  - git-advanced (order 114) — rebase, cherry-pick, bisect, hooks
  - python-fundamentals (order 115) — decorators, generators, asyncio
Run: python3 scripts/new_topics_batch2.py
"""
import json
from pathlib import Path

BASE = Path(__file__).parent.parent / "src/content/topics"


def write(folder, filename, data):
    out = BASE / folder / filename
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists():
        existing = json.loads(out.read_text())
        if len(existing.get("questions", [])) >= 20:
            print(f"  SKIP {filename} (already complete)")
            return
    out.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    print(f"  WROTE {filename}: q={len(data['questions'])} fc={len(data['flashcards'])} guide={len(data['guide'])} chars")


# ─── TOPIC 1: sql-advanced ────────────────────────────────────────────────────

SQL_ADV_GUIDE = "\n".join([
    "# SQL Advanced",
    "",
    "## Why Advanced SQL?",
    "",
    "Basic SQL (SELECT, WHERE, JOIN, GROUP BY) handles most queries.",
    "But production databases run complex reporting, analytics, and hierarchical queries",
    "that beginners solve with multiple queries + application code — when SQL itself",
    "can do it in one optimised statement.",
    "",
    "Advanced SQL = less code, less round-trips, better performance.",
    "",
    "---",
    "",
    "## CTEs — Common Table Expressions",
    "",
    "```sql",
    "-- CTE: a named temporary result set you can reference like a table",
    "-- Think of it as a named subquery at the top of your SQL statement",
    "",
    "WITH monthly_sales AS (",
    "  SELECT",
    "    DATE_TRUNC('month', order_date) AS month,",
    "    SUM(amount)                      AS total",
    "  FROM orders",
    "  GROUP BY 1",
    "),",
    "ranked_months AS (",
    "  SELECT",
    "    month,",
    "    total,",
    "    RANK() OVER (ORDER BY total DESC) AS rank",
    "  FROM monthly_sales",
    ")",
    "SELECT * FROM ranked_months WHERE rank <= 3;",
    "-- Get top 3 revenue months",
    "",
    "-- CTE benefits:",
    "--   Readable: name each logical step",
    "--   Reusable: reference the same CTE multiple times",
    "--   Debuggable: test each CTE independently",
    "",
    "-- RECURSIVE CTE: self-referencing CTE for hierarchical data",
    "WITH RECURSIVE employee_tree AS (",
    "  -- Anchor: start with CEO (no manager)",
    "  SELECT id, name, manager_id, 0 AS level",
    "  FROM employees WHERE manager_id IS NULL",
    "",
    "  UNION ALL",
    "",
    "  -- Recursive: join employees to their managers",
    "  SELECT e.id, e.name, e.manager_id, et.level + 1",
    "  FROM employees e",
    "  JOIN employee_tree et ON e.manager_id = et.id",
    ")",
    "SELECT name, level FROM employee_tree ORDER BY level;",
    "-- Shows entire org chart with depth",
    "```",
    "",
    "---",
    "",
    "## Window Functions",
    "",
    "```",
    "Window functions operate on a 'window' of rows related to the current row",
    "WITHOUT collapsing them (unlike GROUP BY which collapses rows into one).",
    "",
    "GROUP BY:   many rows → one row per group   (aggregates, loses detail)",
    "Window fn:  every row kept + window computed value added beside it",
    "```",
    "",
    "```sql",
    "SELECT",
    "  salesperson,",
    "  region,",
    "  sales,",
    "  -- Rank within each region (restarts at 1 for each region)",
    "  RANK()        OVER (PARTITION BY region ORDER BY sales DESC) AS region_rank,",
    "  -- Row number (no ties)",
    "  ROW_NUMBER()  OVER (PARTITION BY region ORDER BY sales DESC) AS row_num,",
    "  -- Dense rank (no gaps: 1,2,2,3 not 1,2,2,4)",
    "  DENSE_RANK()  OVER (PARTITION BY region ORDER BY sales DESC) AS dense_rank,",
    "  -- Running total of sales within region",
    "  SUM(sales)    OVER (PARTITION BY region ORDER BY sales DESC",
    "                      ROWS UNBOUNDED PRECEDING)               AS running_total,",
    "  -- Previous row's sales value",
    "  LAG(sales, 1) OVER (PARTITION BY region ORDER BY sales DESC) AS prev_sales,",
    "  -- Next row's sales value",
    "  LEAD(sales, 1) OVER (PARTITION BY region ORDER BY sales DESC) AS next_sales",
    "FROM sales_data;",
    "",
    "-- Get only top earner per region:",
    "SELECT * FROM (",
    "  SELECT *,",
    "    RANK() OVER (PARTITION BY region ORDER BY sales DESC) AS rk",
    "  FROM sales_data",
    ") sub WHERE rk = 1;",
    "```",
    "",
    "```",
    "Window function anatomy:",
    "",
    "  FUNCTION_NAME(expression)",
    "  OVER (",
    "    PARTITION BY column   -- like GROUP BY but doesn't collapse rows",
    "    ORDER BY column       -- sort order for window frame",
    "    ROWS/RANGE BETWEEN    -- how many rows back/forward to include",
    "  )",
    "",
    "Common window functions:",
    "  ROW_NUMBER()  : unique sequential number (no ties)",
    "  RANK()        : rank with gaps on ties (1,2,2,4)",
    "  DENSE_RANK()  : rank without gaps (1,2,2,3)",
    "  LAG(col, n)   : value of col n rows before current",
    "  LEAD(col, n)  : value of col n rows after current",
    "  SUM/AVG/COUNT : running aggregate over window",
    "  FIRST_VALUE() : first value in window",
    "  LAST_VALUE()  : last value in window",
    "```",
    "",
    "---",
    "",
    "## EXPLAIN and Query Optimisation",
    "",
    "```sql",
    "-- Always EXPLAIN before trusting a slow query",
    "EXPLAIN SELECT * FROM orders WHERE user_id = 42;",
    "",
    "-- PostgreSQL: use EXPLAIN ANALYZE for actual run times",
    "EXPLAIN ANALYZE SELECT * FROM orders WHERE user_id = 42;",
    "",
    "-- Output to look for:",
    "--  Seq Scan   = full table scan (BAD for large tables if selective)",
    "--  Index Scan = using an index (GOOD)",
    "--  Nested Loop, Hash Join, Merge Join = different join strategies",
    "--  rows=1 (estimate) vs actual rows=100 → bad statistics (run ANALYZE)",
    "",
    "Example EXPLAIN output (PostgreSQL):",
    "  Index Scan using orders_user_id_idx on orders",
    "    (cost=0.43..8.45 rows=1 width=128)",
    "    (actual time=0.026..0.027 rows=1 loops=1)",
    "    Index Cond: (user_id = 42)",
    "  Planning Time: 0.1 ms",
    "  Execution Time: 0.05 ms",
    "```",
    "",
    "```sql",
    "-- Index design:",
    "-- Create index for high-cardinality WHERE and JOIN columns",
    "CREATE INDEX idx_orders_user_id ON orders(user_id);",
    "CREATE INDEX idx_orders_created_at ON orders(created_at DESC);",
    "",
    "-- Composite index: column ORDER matters!",
    "-- Query: WHERE status = 'shipped' AND created_at > '2024-01-01'",
    "-- Index: (status, created_at) is better than (created_at, status)",
    "-- because status is equality (more selective filter first)",
    "CREATE INDEX idx_orders_status_date ON orders(status, created_at);",
    "",
    "-- Covering index: index contains all columns query needs",
    "-- No heap lookup needed — index IS the answer",
    "CREATE INDEX idx_orders_covering ON orders(user_id) INCLUDE (amount, status);",
    "-- SELECT amount, status FROM orders WHERE user_id=42",
    "-- Never touches the actual table rows!",
    "```",
    "",
    "---",
    "",
    "## Transactions and Isolation Levels",
    "",
    "```sql",
    "BEGIN;",
    "  UPDATE accounts SET balance = balance - 100 WHERE id = 1;",
    "  UPDATE accounts SET balance = balance + 100 WHERE id = 2;",
    "  -- Both or neither — ACID guarantees",
    "COMMIT;  -- or ROLLBACK;",
    "",
    "-- ISOLATION LEVELS (PostgreSQL):",
    "SET TRANSACTION ISOLATION LEVEL READ COMMITTED;  -- default",
    "-- READ UNCOMMITTED: see uncommitted changes (dirty reads) — not used",
    "-- READ COMMITTED:   see only committed data. Default in PostgreSQL.",
    "-- REPEATABLE READ:  same query returns same rows within transaction",
    "-- SERIALIZABLE:     transactions behave as if run one at a time",
    "",
    "-- PHANTOM READS: a new row that matches your WHERE appears mid-transaction",
    "-- Transaction 1: SELECT COUNT(*) FROM orders WHERE amount > 1000 → 5",
    "-- Transaction 2: INSERT order with amount=1500, COMMIT",
    "-- Transaction 1: SELECT COUNT(*) FROM orders WHERE amount > 1000 → 6 (phantom!)",
    "-- Fix: use SERIALIZABLE isolation level",
    "```",
    "",
    "---",
    "",
    "## N+1 Problem and Lateral Joins",
    "",
    "```sql",
    "-- N+1: load 100 users, then for each user load their orders",
    "-- = 1 query + 100 queries = 101 DB round trips (TERRIBLE)",
    "",
    "-- Fix: eager load with JOIN",
    "SELECT u.id, u.name, o.id AS order_id, o.amount",
    "FROM users u",
    "LEFT JOIN orders o ON o.user_id = u.id",
    "WHERE u.id IN (1,2,3,...100);",
    "-- 1 query, returns all data",
    "",
    "-- LATERAL JOIN: like a correlated subquery that can reference outer table",
    "-- Get 3 most recent orders per user:",
    "SELECT u.name, recent.amount",
    "FROM users u",
    "CROSS JOIN LATERAL (",
    "  SELECT amount FROM orders",
    "  WHERE user_id = u.id",
    "  ORDER BY created_at DESC",
    "  LIMIT 3",
    ") AS recent;",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "SQL ADVANCED",
    "|",
    "+-- CTEs",
    "|   +-- WITH name AS (query) SELECT ... FROM name",
    "|   +-- Multiple CTEs chained",
    "|   +-- RECURSIVE CTE for trees/hierarchies",
    "|",
    "+-- WINDOW FUNCTIONS",
    "|   +-- OVER (PARTITION BY ... ORDER BY ...)",
    "|   +-- RANK / ROW_NUMBER / DENSE_RANK",
    "|   +-- LAG / LEAD (prev/next row)",
    "|   +-- Running SUM / AVG",
    "|",
    "+-- EXPLAIN / OPTIMISATION",
    "|   +-- Seq Scan = no index (investigate)",
    "|   +-- Index Scan = good",
    "|   +-- Create indexes on WHERE / JOIN columns",
    "|   +-- Composite index column order matters",
    "|",
    "+-- TRANSACTIONS",
    "    +-- BEGIN / COMMIT / ROLLBACK",
    "    +-- Isolation levels",
    "    +-- Phantom reads → SERIALIZABLE",
    "```",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **SQL Window Functions Tutorial** by techTFQ:",
    "  https://www.youtube.com/watch?v=Ww71knvhQ-s",
    "- **Advanced SQL** by Fireship:",
    "  https://www.youtube.com/watch?v=zsjvFFKOm3c",
    "",
    "### Practice",
    "- **Mode SQL Tutorial**: https://mode.com/sql-tutorial/sql-window-functions/",
    "- **LeetCode SQL**: https://leetcode.com/study-plan/sql/ — 50 practical SQL problems",
    "- **pgexercises**: https://pgexercises.com — PostgreSQL exercises from beginner to advanced",
])

SQL_ADV_Q = [
    {"id":"sqladv-q1","type":"mcq","prompt":"What is a CTE and how is it different from a subquery?",
     "choices":["CTE is faster than a subquery","CTE (WITH clause) is a named temporary result set — more readable, can be referenced multiple times, supports recursion. Subquery is embedded inline. Both often optimised similarly.","CTE is stored permanently","CTE must return one row"],
     "answerIndex":1,"explanation":"CTE and subquery are often identical in execution (optimizer may inline them). CTE advantages: readable, reusable (reference same CTE twice), supports recursive queries. For complex queries with multiple steps, CTEs are much clearer.","tags":["cte","sql"]},
    {"id":"sqladv-q2","type":"mcq","prompt":"What makes a RECURSIVE CTE different from a regular CTE?",
     "choices":["Faster performance","It references itself — has an anchor member (base case) + recursive member (joins back to CTE). Used for hierarchical data: org charts, file systems, bill of materials.","It runs in parallel","Recursive CTEs use cursors"],
     "answerIndex":1,"explanation":"Recursive CTE: anchor terminates recursion by finding base rows (e.g., root nodes). Recursive part joins employees to their manager found in previous iteration. PostgreSQL executes until no more rows added. Essential for tree/graph traversal in SQL.","tags":["cte","recursive"]},
    {"id":"sqladv-q3","type":"mcq","prompt":"Window function vs GROUP BY — key difference?",
     "choices":["Window functions are faster","GROUP BY collapses many rows into one per group (loses individual row detail). Window functions add a computed column to EVERY row without collapsing — all original rows preserved.","GROUP BY is deprecated","They are identical"],
     "answerIndex":1,"explanation":"GROUP BY: 100 rows → 5 groups → 5 result rows. Window: 100 rows → still 100 rows, each with an extra column like rank_within_group. This lets you answer 'show me all employees AND their rank within their department' in one query.","tags":["window-functions","group-by"]},
    {"id":"sqladv-q4","type":"mcq","prompt":"RANK() vs ROW_NUMBER() vs DENSE_RANK() with values [100, 90, 90, 80]:",
     "choices":["All three give 1,2,3,4","ROW_NUMBER: 1,2,3,4 (unique). RANK: 1,2,2,4 (skip 3 for tie). DENSE_RANK: 1,2,2,3 (no skip).","ROW_NUMBER handles ties","RANK gives 1,1,1,1 for all ties"],
     "answerIndex":1,"explanation":"ROW_NUMBER: always unique sequential number. RANK: same rank for ties, then skips (two 2nds = no 3rd). DENSE_RANK: same rank for ties, no skip. Use DENSE_RANK when gaps would be confusing (e.g., competition placement).","tags":["window-functions","ranking"]},
    {"id":"sqladv-q5","type":"mcq","prompt":"LAG(sales, 1) OVER (ORDER BY month) — what does this compute?",
     "choices":["Next month's sales","Previous month's sales — the value of the sales column from 1 row before the current row in the window order","Rolling average","Percent change"],
     "answerIndex":1,"explanation":"LAG(col, n) looks n rows back. LAG(sales, 1) = last month's sales. Used for period-over-period comparison: current - LAG(sales,1) = month-over-month change. LEAD(col, n) looks n rows forward.","tags":["window-functions","lag-lead"]},
    {"id":"sqladv-q6","type":"mcq","prompt":"EXPLAIN shows 'Seq Scan' on a large table. What does this mean?",
     "choices":["The query is optimised","PostgreSQL is reading every row in the table linearly — no index is being used. For a 10M row table this could mean millions of disk reads instead of a targeted index lookup.","Sequential is always fast","Seq Scan means the table is sorted"],
     "answerIndex":1,"explanation":"Seq Scan on a large table with a selective WHERE condition = missing index. Fix: CREATE INDEX on the WHERE column. Note: for small tables or queries that need most rows, Seq Scan is actually faster than index scan (no random I/O).","tags":["explain","indexes","performance"]},
    {"id":"sqladv-q7","type":"mcq","prompt":"In a composite index (status, created_at), which query benefits?",
     "choices":["WHERE created_at > '2024-01-01'","WHERE status = 'shipped' AND created_at > '2024-01-01'","WHERE created_at > '2024-01-01' AND status = 'shipped'","Both B and C benefit equally"],
     "answerIndex":3,"explanation":"SQL optimizer can reorder your WHERE conditions. Both B and C use index (status, created_at) because the optimizer is smart enough to match regardless of write order. But index can't be used if you query only created_at without status (leftmost prefix rule).","tags":["indexes","composite-index"]},
    {"id":"sqladv-q8","type":"mcq","prompt":"What is the N+1 query problem?",
     "choices":["A query with N joins","Load a list of N records, then for EACH record make a separate query to load related data — results in 1+N database round trips instead of 1","A table with N+1 columns","Recursive query depth"],
     "answerIndex":1,"explanation":"Classic ORM pitfall. Load 100 users (1 query). For each user, ORM lazily loads their orders (100 queries) = 101 total. Fix: use JOIN to load everything in 1 query, or ORM eager loading (JPA fetch = EAGER, or @EntityGraph).","tags":["n+1","performance","orm"]},
    {"id":"sqladv-q9","type":"mcq","prompt":"What does PARTITION BY do in a window function?",
     "choices":["Splits the table into physical partitions","Divides rows into groups for the window function to operate on independently — like GROUP BY but rows aren't collapsed. RANK() OVER (PARTITION BY dept ORDER BY salary) ranks within each department.","Partitions the disk","Creates a new table"],
     "answerIndex":1,"explanation":"PARTITION BY = restart the window function calculation for each group. Without PARTITION BY, all rows are one window. With PARTITION BY region: rank restarts at 1 for each region. Different from GROUP BY: all rows still present.","tags":["window-functions","partition-by"]},
    {"id":"sqladv-q10","type":"mcq","prompt":"EXPLAIN ANALYZE shows estimated rows=1 but actual rows=10000. What is the problem?",
     "choices":["Query is wrong","Table statistics are stale — PostgreSQL estimated 1 row but found 10000 at runtime. This causes the planner to choose a suboptimal execution plan. Fix: ANALYZE tablename to refresh statistics.","Index is missing","The query timeout"],
     "answerIndex":1,"explanation":"PostgreSQL planner uses statistics (column value histograms) to estimate rows. Stale statistics = wrong estimates = wrong plan choice (e.g., might choose nested loop instead of hash join). Run ANALYZE after large data loads.","tags":["explain","statistics","query-planning"]},
    {"id":"sqladv-q11","type":"mcq","prompt":"What does a COVERING INDEX eliminate?",
     "choices":["Need for ORDER BY","Heap lookup — all columns the query needs are in the index itself, so PostgreSQL never reads the actual table rows. Makes the query purely index-based.","Need for WHERE clause","UPDATE operations"],
     "answerIndex":1,"explanation":"Normal index scan: find matching row IDs in index, then fetch full rows from heap (table). Covering index includes all needed columns, so heap fetch is skipped. CREATE INDEX ... INCLUDE (col1, col2). Can cut query time by 50-80% for read-heavy queries.","tags":["indexes","covering-index"]},
    {"id":"sqladv-q12","type":"mcq","prompt":"READ COMMITTED vs REPEATABLE READ isolation level — key difference?",
     "choices":["Speed","READ COMMITTED: each statement sees latest committed data (non-repeatable reads possible). REPEATABLE READ: a transaction sees the same snapshot of data throughout — same query returns same rows even if others commit between reads.","REPEATABLE READ prevents phantom reads in PostgreSQL","READ COMMITTED is deprecated"],
     "answerIndex":1,"explanation":"READ COMMITTED: running same SELECT twice in one transaction could return different results if someone commits between your reads. REPEATABLE READ: transaction gets a snapshot at start, queries always return same data. PostgreSQL REPEATABLE READ also prevents phantom reads.","tags":["transactions","isolation-levels"]},
    {"id":"sqladv-q13","type":"multi","prompt":"Which query patterns benefit from window functions? (Select all)",
     "choices":["Running total of sales per month","Top 3 products per category","Finding duplicate rows","Average of all rows"],
     "answerIndexes":[0,1,2],"explanation":"Running totals: SUM() OVER (ORDER BY date ROWS UNBOUNDED PRECEDING). Top N per group: RANK() OVER (PARTITION BY category ORDER BY sales) then filter rank<=3. Duplicate detection: ROW_NUMBER() OVER (PARTITION BY key) > 1. Simple AVG() doesn't need window function.","tags":["window-functions","use-cases"]},
    {"id":"sqladv-q14","type":"mcq","prompt":"How does LATERAL JOIN differ from a regular JOIN?",
     "choices":["LATERAL runs in parallel","LATERAL subquery can reference columns from the outer table (left side) — enables per-row subqueries. e.g., for each user, get their last 3 orders (can't do this with regular JOIN without complex window function).","LATERAL is deprecated","Same as CROSS JOIN"],
     "answerIndex":1,"explanation":"Regular JOIN: the right side is computed once, independently. LATERAL: right side is a correlated subquery that runs once per row of left side, able to use outer row's values. Essential for 'top N per group without window functions'.","tags":["lateral-join","sql"]},
    {"id":"sqladv-q15","type":"mcq","prompt":"UNION vs UNION ALL in SQL:",
     "choices":["Identical","UNION removes duplicate rows (sorts and deduplicates — slower). UNION ALL keeps all rows including duplicates (no sort — faster). Use UNION ALL unless you specifically need deduplication.","UNION ALL is deprecated","UNION is for different schemas"],
     "answerIndex":1,"explanation":"UNION internally sorts results to find duplicates — O(n log n). UNION ALL just concatenates — O(n). If you know results won't have relevant duplicates (different filters, different tables) always use UNION ALL for better performance.","tags":["union","performance"]},
    {"id":"sqladv-q16","type":"mcq","prompt":"What is a phantom read?",
     "choices":["Reading a deleted row","Reading a row twice with different values","A transaction reads a set of rows matching a condition, another transaction inserts a matching row and commits, the first transaction re-runs the same query and sees the new (phantom) row","Hardware memory error"],
     "answerIndex":2,"explanation":"Phantom read: your query returns N rows, someone inserts a matching row mid-transaction, re-running same query returns N+1 rows. Fix: SERIALIZABLE isolation. PostgreSQL REPEATABLE READ prevents phantoms too (unlike the SQL standard).","tags":["transactions","phantom-reads","isolation"]},
    {"id":"sqladv-q17","type":"mcq","prompt":"What does EXPLAIN ANALYZE's 'actual time' vs 'cost' represent?",
     "choices":["They are the same","cost = planner's estimate in abstract units (not ms). actual time = real measured execution time in ms. Compare both to find where planner estimates are wrong (large discrepancy = stale statistics or bad plan choice).","cost is in milliseconds","actual time is approximate"],
     "answerIndex":1,"explanation":"Cost is a dimensionless unit used by the planner to compare plans (1.0 = reading one disk page sequential). Actual time is real wall-clock milliseconds measured during EXPLAIN ANALYZE execution. Large cost/time mismatch → investigate.","tags":["explain","query-planning"]},
    {"id":"sqladv-q18","type":"mcq","prompt":"Index on (user_id, order_date DESC). Query: WHERE user_id = 42 ORDER BY order_date DESC LIMIT 10. What is the performance?",
     "choices":["Full table scan","Seq scan then sort","Index-only fast path: uses index to find user 42's rows already in desc order, takes first 10 — O(log n + 10) with no sort step needed","Hash join required"],
     "answerIndex":2,"explanation":"This is the 'index-accelerated ORDER BY' pattern. Index stores (user_id, order_date DESC) pre-sorted. Query walks index directly: find user_id=42 range, order_date already descending, grab first 10. No sort. Extremely fast.","tags":["indexes","order-by","performance"]},
    {"id":"sqladv-q19","type":"mcq","prompt":"CTE WITH RECURSIVE: what prevents infinite recursion?",
     "choices":["SQL has no infinite loop risk","The recursive member must eventually produce no new rows — typically by joining only on rows not yet seen. Also: CYCLE detection clause in PostgreSQL 14+ and maximum recursion depth settings.","A time limit","Number of rows limit"],
     "answerIndex":1,"explanation":"Recursive CTE stops when the recursive member returns 0 rows. If the recursive member always returns rows (e.g., a graph with cycles), infinite loop. Prevent: add cycle detection in WHERE clause, or use PostgreSQL 14 CYCLE keyword.","tags":["cte","recursive","infinite-loop"]},
    {"id":"sqladv-q20","type":"codeOutput","prompt":"What does this window function compute?",
     "code":"SELECT\n  month,\n  sales,\n  SUM(sales) OVER (ORDER BY month ROWS UNBOUNDED PRECEDING) AS cumulative\nFROM monthly_sales;",
     "choices":["Average sales per month","Total sales for all months in every row","Cumulative running total of sales: each row shows all sales from the first month up to and including the current month","Previous month's sales"],
     "answerIndex":2,"explanation":"ROWS UNBOUNDED PRECEDING means: include all rows from the start of the partition up to current row. SUM over this frame = running total. Month 3 row shows sum of months 1+2+3. Month 4 shows 1+2+3+4. Classic cumulative sum pattern.","tags":["window-functions","running-total"]},
]

SQL_ADV_FC = [
    {"id":"sqladv-fc1","front":"CTE syntax","back":"WITH name AS (SELECT ...) SELECT ... FROM name. Chain: WITH a AS (...), b AS (... FROM a) SELECT ... Multiple CTEs with commas. RECURSIVE: WITH RECURSIVE name AS (anchor UNION ALL recursive_part).","tags":["cte"]},
    {"id":"sqladv-fc2","front":"Window function skeleton","back":"FUNC() OVER (PARTITION BY col ORDER BY col ROWS/RANGE BETWEEN ...). PARTITION BY = restart per group. ORDER BY = frame order. No PARTITION BY = one window = all rows.","tags":["window-functions"]},
    {"id":"sqladv-fc3","front":"RANK vs DENSE_RANK vs ROW_NUMBER on [100,90,90,80]","back":"ROW_NUMBER: 1,2,3,4 (always unique). RANK: 1,2,2,4 (skips after tie). DENSE_RANK: 1,2,2,3 (no skip). Use ROW_NUMBER for dedup, RANK for competition, DENSE_RANK for reporting.","tags":["window-functions","ranking"]},
    {"id":"sqladv-fc4","front":"Fix missing index — steps","back":"1. EXPLAIN ANALYZE query. 2. Find Seq Scan on large table with selective filter. 3. CREATE INDEX ON table(filter_col). 4. Re-run EXPLAIN — should show Index Scan. 5. ANALYZE if estimates still wrong.","tags":["indexes","explain"]},
    {"id":"sqladv-fc5","front":"N+1 fix strategies","back":"1. Eager load (JOIN to fetch related data in one query). 2. ORM: @EntityGraph, fetchType=EAGER, or .findAll(EntityGraph). 3. DataLoader pattern (GraphQL). 4. Batch loading: WHERE id IN (...) instead of one query per ID.","tags":["n+1","performance"]},
    {"id":"sqladv-fc6","front":"Composite index leftmost prefix rule","back":"Index (a, b, c): filters using a, (a,b), or (a,b,c) benefit. Filter on b alone = NO index. Filter on c alone = NO index. Filter on a and c = only a portion used. Design index with most selective + most common filter columns first.","tags":["indexes","composite"]},
    {"id":"sqladv-fc7","front":"LAG / LEAD use case","back":"Period-over-period: LAG(revenue, 1) OVER (ORDER BY month). MoM change: revenue - LAG(revenue,1). YoY: LAG(revenue, 12). LEAD for 'what comes next'. Both return NULL for rows without enough preceding/following rows.","tags":["window-functions","lag-lead"]},
    {"id":"sqladv-fc8","front":"EXPLAIN key terms","back":"Seq Scan = full table read. Index Scan = index then heap. Index Only Scan = purely index (best). Nested Loop = join small with small. Hash Join = join medium tables. Merge Join = join sorted tables. rows estimate vs actual = statistics quality.","tags":["explain","query-planning"]},
]

SQL_ADV_PROJ = {
    "brief": "You have an e-commerce database: orders(id, user_id, amount, status, created_at), users(id, name, region). Write queries for: 1) Monthly revenue with MoM % change. 2) Top 3 customers per region by total spend. 3) Users who placed an order every month for the last 12 months (retention analysis). 4) EXPLAIN and optimise the retention query.",
    "checklist": [
        {"id":"sql1","text":"MoM change: CTE monthly_totals, then window LAG(revenue,1) OVER (ORDER BY month) to compute delta/lag*100","weight":25},
        {"id":"sql2","text":"Top 3 per region: RANK() OVER (PARTITION BY region ORDER BY total_spend DESC), filter rank<=3 in outer query","weight":25},
        {"id":"sql3","text":"12-month retention: GROUP BY user_id, HAVING COUNT(DISTINCT DATE_TRUNC('month',created_at)) = 12","weight":25},
        {"id":"sql4","text":"EXPLAIN shows index on (user_id, created_at) reduces Seq Scan. Add covering index including amount.","weight":25},
    ],
    "hints": [
        "DATE_TRUNC('month', created_at) normalises any date to first of month — group by this for monthly aggregation.",
        "Retention query: filter WHERE created_at >= NOW() - INTERVAL '12 months', then HAVING COUNT(DISTINCT month) = 12.",
        "Top N per group pattern: wrap ranking query in subquery/CTE and WHERE rank <= N in outer query.",
    ]
}

write("languages", "sql-advanced.json", {
    "id": "sql-advanced",
    "unit": 12,
    "order": 113,
    "title": "SQL Advanced",
    "summary": "CTEs, window functions, EXPLAIN query plans, index optimisation, and transaction isolation levels for production databases.",
    "prereqs": ["relational-databases"],
    "guide": SQL_ADV_GUIDE,
    "questions": SQL_ADV_Q,
    "flashcards": SQL_ADV_FC,
    "project": SQL_ADV_PROJ,
})

# ─── TOPIC 2: git-advanced ────────────────────────────────────────────────────

GIT_ADV_GUIDE = "\n".join([
    "# Git Advanced",
    "",
    "## Prerequisites",
    "You should know: git add, commit, push, pull, branch, merge. This guide covers",
    "the powerful tools beyond basics that senior developers use daily.",
    "",
    "---",
    "",
    "## Rebase — Rewriting History",
    "",
    "```",
    "Merge vs Rebase — two ways to integrate changes:",
    "",
    "MERGE: creates a merge commit, preserves history exactly as it happened",
    "  main: A─B─C────────M  (M = merge commit)",
    "               \\   /",
    "  feat:          D─E",
    "",
    "REBASE: replays your commits on top of target branch (rewrites commit SHAs!)",
    "  Before rebase:               After git rebase main:",
    "  main: A─B─C                  main: A─B─C",
    "               \\                              \\",
    "  feat:    D─E                  feat:           D'─E'",
    "",
    "  D' and E' have new SHAs but same changes as D and E.",
    "  Result: LINEAR history — looks like you branched from current main",
    "",
    "When to use what:",
    "  merge:  public branches, preserving exact history, team-shared branches",
    "  rebase: cleaning up local commits before PR, linear history preference",
    "```",
    "",
    "```bash",
    "# Standard rebase workflow (before opening a PR):",
    "git checkout feature/my-feature",
    "git fetch origin",
    "git rebase origin/main",
    "# If conflicts: fix them, then:",
    "git add .",
    "git rebase --continue",
    "# To abort: git rebase --abort",
    "",
    "# Interactive rebase — rewrite last 3 commits:",
    "git rebase -i HEAD~3",
    "# Opens editor:",
    "#  pick abc123 Add user model",
    "#  pick def456 Fix typo in user model",
    "#  pick ghi789 Add user service",
    "# Change 'pick' to:",
    "#  fixup  = merge into previous (discard this commit's message)",
    "#  squash = merge into previous (edit combined message)",
    "#  reword = keep commit but edit message",
    "#  drop   = delete this commit entirely",
    "#  edit   = pause to amend this commit",
    "",
    "# Squash 'Fix typo' into 'Add user model':",
    "#  pick abc123 Add user model",
    "#  fixup def456 Fix typo in user model    ← becomes part of abc123",
    "#  pick ghi789 Add user service",
    "```",
    "",
    "**GOLDEN RULE: Never rebase shared/public branches.** Rebase rewrites SHAs.",
    "If teammates have your old commits, they'll have conflicts from the rewritten history.",
    "Only rebase local branches or feature branches you haven't shared yet.",
    "",
    "---",
    "",
    "## Cherry-pick — Pick Individual Commits",
    "",
    "```bash",
    "# Scenario: hotfix is needed in main AND in release branch",
    "# Fix made on main (commit abc123). Need it on release/2.0 too.",
    "",
    "git checkout release/2.0",
    "git cherry-pick abc123",
    "# Creates a NEW commit on release/2.0 with same changes",
    "# New commit has different SHA (different parent)",
    "",
    "# Cherry-pick a range of commits:",
    "git cherry-pick abc123..def456   # commits from abc123 to def456",
    "",
    "# Cherry-pick without committing (just stage the changes):",
    "git cherry-pick -n abc123  # -n = --no-commit",
    "git add .  # review/modify before committing",
    "git commit",
    "",
    "# If conflicts: fix, then:",
    "git cherry-pick --continue",
    "# or abort:",
    "git cherry-pick --abort",
    "```",
    "",
    "---",
    "",
    "## Git Bisect — Binary Search for Bug Introduction",
    "",
    "```",
    "PROBLEM: The app was working 6 months ago. 300 commits later, it's broken.",
    "Which commit introduced the bug?",
    "",
    "MANUAL: check 150 commits manually → tedious",
    "BISECT: binary search → check only log2(300) ≈ 8 commits",
    "",
    "PROCESS:",
    "  1. Mark current HEAD as bad",
    "  2. Mark a known good commit",
    "  3. Git checks out a midpoint commit",
    "  4. Test your app: good or bad?",
    "  5. Mark accordingly → git checks out next midpoint",
    "  6. Repeat until first bad commit identified",
    "```",
    "",
    "```bash",
    "git bisect start",
    "git bisect bad                    # current HEAD is bad",
    "git bisect good v1.2.0            # this tag/commit was working",
    "# Git checks out midpoint: 'Bisecting: 150 revisions left'",
    "",
    "# Test your app...",
    "git bisect good  # or bad",
    "# Git checks out next midpoint",
    "",
    "# Repeat until:",
    "# 'abc123 is the first bad commit'",
    "",
    "git bisect reset  # back to HEAD",
    "",
    "# Automated bisect (if you have a test script):",
    "git bisect run ./test.sh",
    "# test.sh exits 0 = good, exits non-0 = bad. Fully automated!",
    "```",
    "",
    "---",
    "",
    "## Git Hooks — Automate on Events",
    "",
    "```",
    "Git hooks = scripts that run automatically on git events.",
    "Stored in .git/hooks/ — not committed by default.",
    "Use tools like husky (JS) or pre-commit (Python) to commit hooks.",
    "",
    "Common hooks:",
    "  pre-commit:     runs before commit is created",
    "                  → lint, format, test, secrets scan",
    "  commit-msg:     validates commit message format",
    "                  → enforce Conventional Commits",
    "  pre-push:       runs before pushing",
    "                  → run full test suite",
    "  post-checkout:  runs after branch switch",
    "  post-merge:     runs after merge",
    "```",
    "",
    "```bash",
    "# .git/hooks/pre-commit (must be executable: chmod +x)",
    "#!/bin/sh",
    "# Run lint before committing",
    "npm run lint",
    "exit_code=$?",
    "if [ $exit_code -ne 0 ]; then",
    "  echo 'Lint failed. Fix errors before committing.'",
    "  exit 1  # Non-zero = abort commit",
    "fi",
    "",
    "# Using husky (Node.js project):",
    "npm install --save-dev husky",
    "npx husky init",
    "echo 'npm run lint' > .husky/pre-commit",
    "",
    "# commitlint — enforce conventional commits:",
    "npm install --save-dev @commitlint/{config-conventional,cli}",
    "echo \"module.exports = { extends: ['@commitlint/config-conventional'] }\" > commitlint.config.js",
    "echo 'npx commitlint --edit $1' > .husky/commit-msg",
    "# Now: 'feat: add login' passes, 'added login' fails",
    "```",
    "",
    "---",
    "",
    "## Monorepo Strategies",
    "",
    "```",
    "POLYREPO: one repo per service/app",
    "  + Simple per-service CI/CD",
    "  - Dependency coordination hell (service A uses lib v1, B uses v2)",
    "  - Cross-repo changes need multiple PRs",
    "",
    "MONOREPO: all code in one repo",
    "  + Atomic cross-project changes in one commit",
    "  + Shared tooling, lint, test setup",
    "  + Dependency consistency",
    "  - Slower git operations at scale",
    "  - Need smart build tools (only rebuild what changed)",
    "",
    "Tools for JS/TS monorepos:",
    "  Nx:       smart caching, affected commands (only build changed packages)",
    "  Turborepo: similar to Nx, from Vercel",
    "  pnpm workspaces: package management for monorepos",
    "",
    "Git sparse checkout (checkout only subset of monorepo):",
    "  git sparse-checkout init --cone",
    "  git sparse-checkout set packages/frontend services/auth",
    "  # Only those folders checked out, rest on remote",
    "```",
    "",
    "---",
    "",
    "## Git Stash, Worktrees, and Reflog",
    "",
    "```bash",
    "# STASH: temporarily save uncommitted work",
    "git stash                       # stash all changes",
    "git stash push -m 'wip auth'    # named stash",
    "git stash list                  # list stashes",
    "git stash pop                   # apply latest + remove from stash",
    "git stash apply stash@{2}       # apply specific stash (keep in list)",
    "git stash drop stash@{0}        # delete stash",
    "",
    "# WORKTREES: check out multiple branches simultaneously",
    "git worktree add ../hotfix-branch hotfix/payment-crash",
    "# Creates ../hotfix-branch folder on hotfix branch",
    "# You can work in both folders at same time!",
    "# Perfect for: reviewing a PR while keep working on your branch",
    "",
    "# REFLOG: the 'undo' of undos — records every HEAD movement",
    "git reflog",
    "# Shows: abc123 HEAD@{0}: checkout: moving from main to feat",
    "#        def456 HEAD@{1}: commit: Add button component",
    "# Recover 'deleted' commits:",
    "git checkout def456  # or git reset --hard def456",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "GIT ADVANCED",
    "|",
    "+-- REBASE",
    "|   +-- Replay commits on new base",
    "|   +-- Interactive: squash, fixup, reword, drop",
    "|   +-- NEVER rebase shared branches",
    "|   +-- git rebase -i HEAD~N",
    "|",
    "+-- CHERRY-PICK",
    "|   +-- Apply specific commit to another branch",
    "|   +-- git cherry-pick <sha>",
    "|   +-- Use for hotfixes across branches",
    "|",
    "+-- BISECT",
    "|   +-- Binary search for bug-introducing commit",
    "|   +-- log2(N) steps",
    "|   +-- automate with test script",
    "|",
    "+-- HOOKS",
    "|   +-- pre-commit, commit-msg, pre-push",
    "|   +-- husky for JS projects",
    "|   +-- Enforce linting, testing, commit format",
    "|",
    "+-- MONOREPO",
    "    +-- Nx / Turborepo for smart rebuilds",
    "    +-- pnpm workspaces",
    "    +-- sparse checkout for large repos",
    "```",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **Git Rebase and Merge** by Atlassian:",
    "  https://www.youtube.com/watch?v=dO9BtPDIHJ8",
    "- **Advanced Git Techniques** by Fireship:",
    "  https://www.youtube.com/watch?v=ecK3EnyGD8o",
    "",
    "### Articles",
    "- **Pro Git Book** (free): https://git-scm.com/book/en/v2 — Chapters 6-7 cover advanced topics",
    "- **Conventional Commits**: https://www.conventionalcommits.org",
    "- **Oh Shit Git**: https://ohshitgit.com — how to recover from every mistake",
])

GIT_ADV_Q = [
    {"id":"gitadv-q1","type":"mcq","prompt":"What does git rebase main do on your feature branch?",
     "choices":["Creates a merge commit on main","Replays your feature branch commits on top of the current tip of main, creating new commits with new SHAs but same changes — linearising history","Deletes main","Merges main into feature without rewriting"],
     "answerIndex":1,"explanation":"Rebase re-applies your commits one by one after the new base (main). The commits get new SHAs because their parent changes. This makes it look like you branched from current main even if you branched weeks ago.","tags":["git","rebase"]},
    {"id":"gitadv-q2","type":"mcq","prompt":"Why is rebasing public/shared branches dangerous?",
     "choices":["Rebase is slow","Rebase rewrites commit SHAs. If teammates have your old commits, their histories diverge from yours — they'll get conflicts and duplicate commits when they try to pull. Never rebase shared branches.","Rebase has bugs","Rebase doesn't work on GitHub"],
     "answerIndex":1,"explanation":"Rebase changes commit SHAs. If Alice has commit abc123 and you rebase to get abc456 (same content, different SHA), when Alice pulls she has both: the old abc123 AND the new abc456 — confusing duplicate history.","tags":["git","rebase","safety"]},
    {"id":"gitadv-q3","type":"mcq","prompt":"Interactive rebase with 'fixup' vs 'squash' — difference?",
     "choices":["fixup is faster","fixup: merges commit into previous AND discards its commit message. squash: merges commit into previous AND opens editor to write combined message.","They are identical","squash deletes the commit"],
     "answerIndex":1,"explanation":"fixup silently collapses. squash prompts you to write a new commit message for the combined commit. Use fixup for tiny fix commits (typos, formatting). Use squash when you want to craft a meaningful combined message.","tags":["git","interactive-rebase"]},
    {"id":"gitadv-q4","type":"mcq","prompt":"When is git cherry-pick the right tool?",
     "choices":["Integrating a feature branch into main","Applying a specific commit (e.g., a hotfix) from one branch to another without merging the entire branch — e.g., patch v2.0 release branch with a fix made on main","Renaming commits","Checking out a file from another branch"],
     "answerIndex":1,"explanation":"Cherry-pick = selective commit application. You made a hotfix on main (commit abc123). Release branch release/2.0 needs this fix too, but not all of main. git cherry-pick abc123 on release/2.0 applies just that fix.","tags":["git","cherry-pick"]},
    {"id":"gitadv-q5","type":"mcq","prompt":"git bisect uses what algorithm to find the bug-introducing commit?",
     "choices":["Linear search","Binary search — starts at midpoint of good..bad range. Mark good/bad. Git picks new midpoint. Repeat until done. Finds the commit in O(log N) steps.","Depth-first search","Random sampling"],
     "answerIndex":1,"explanation":"300 commits. Manual linear: 300 tests. Binary search: log2(300) ≈ 8 tests. git bisect automates this: marks good/bad commits, checks out midpoints. With an automated test script, fully hands-off.","tags":["git","bisect"]},
    {"id":"gitadv-q6","type":"mcq","prompt":"A pre-commit hook exits with code 1 (non-zero). What happens?",
     "choices":["Hook runs again","The commit is aborted — git only proceeds with the commit if the hook exits 0","A warning is shown but commit proceeds","Git asks for confirmation"],
     "answerIndex":1,"explanation":"Non-zero exit = signal to git to abort the operation. pre-commit exits 1 → commit stops. This is how lint/test hooks enforce quality: if lint fails, commit fails. Developers must fix before committing.","tags":["git","hooks"]},
    {"id":"gitadv-q7","type":"mcq","prompt":"husky is a tool for:",
     "choices":["Git hosting","Managing git hooks in JavaScript/Node.js projects — hooks are defined in .husky/ folder, committed to the repo so all team members get the same hooks automatically","SQL migrations","Branch protection"],
     "answerIndex":1,"explanation":"Default git hooks live in .git/hooks/ which is never committed. Husky puts hooks in .husky/ which is committed. When a new developer clones and runs npm install, husky automatically installs the hooks. Team-wide enforcement.","tags":["git","hooks","husky"]},
    {"id":"gitadv-q8","type":"mcq","prompt":"git reflog vs git log — key difference?",
     "choices":["reflog shows remote history","git log shows commit history on the current branch. git reflog records ALL movements of HEAD (commits, checkouts, rebases, resets) — lets you recover from accidental resets/deletes by finding the old SHA.","They are identical","reflog is faster"],
     "answerIndex":1,"explanation":"git log: commits reachable from HEAD. git reflog: everything that happened to HEAD in this repo. If you ran git reset --hard and 'lost' commits, they're still in the object store. Find them in reflog, then git checkout <sha> or git reset --hard <sha>.","tags":["git","reflog"]},
    {"id":"gitadv-q9","type":"mcq","prompt":"What is git stash and when should you use it?",
     "choices":["Backup of the repo","Temporarily saves uncommitted changes to a stack, leaving working directory clean. Use when: you need to switch branches urgently but aren't ready to commit. git stash pop restores later.","Archives old commits","Remote backup feature"],
     "answerIndex":1,"explanation":"Scenario: you're mid-feature when a critical bug needs immediate attention. git stash saves your work-in-progress. You switch branches, fix bug, commit, push. Back on feature branch: git stash pop restores where you left off.","tags":["git","stash"]},
    {"id":"gitadv-q10","type":"mcq","prompt":"Conventional Commits specification: what does 'feat(auth): add OAuth login' mean?",
     "choices":["Random prefix","feat = feature type (triggers MINOR version bump in semver). (auth) = scope (optional, which area changed). 'add OAuth login' = description. Other types: fix, chore, docs, refactor, test, perf.","Feature file name","Feature author"],
     "answerIndex":1,"explanation":"Conventional Commits: <type>(scope): description. Enables: automated CHANGELOG generation, semantic versioning (feat=minor, fix=patch, BREAKING CHANGE=major), better git log readability. Enforced by commitlint + husky.","tags":["git","conventional-commits"]},
    {"id":"gitadv-q11","type":"mcq","prompt":"git merge --squash vs git merge what is the difference?",
     "choices":["--squash is faster","--squash: takes all commits from feature branch, combines them into one set of staged changes WITHOUT a merge commit. You then commit manually as one clean commit. git merge: preserves all commits + merge commit.","--squash keeps all history","No difference"],
     "answerIndex":1,"explanation":"Squash merge: feature/abc (10 messy commits) merged into main as one clean commit 'Add authentication system'. Loses individual commit history but keeps main history clean. Alternative to interactive rebase. Many teams squash all PRs.","tags":["git","merge","squash"]},
    {"id":"gitadv-q12","type":"mcq","prompt":"git worktree add — what problem does it solve?",
     "choices":["Adds more disk space","Allows you to check out multiple branches simultaneously in separate directories — same git repo, multiple working trees. Solve: review a PR while keeping your current work untouched without stashing.","Creates a git backup","Remote worktrees"],
     "answerIndex":1,"explanation":"Without worktrees: to review PR you'd need to stash, switch branch, review, switch back, stash pop. With worktrees: add worktree in another folder on the PR branch, review there, continue working in original folder simultaneously.","tags":["git","worktree"]},
    {"id":"gitadv-q13","type":"mcq","prompt":"What is git sparse-checkout used for?",
     "choices":["Checkout only committed files","Checkout only a subset of a large monorepo — specify which folders you want, only those are downloaded/present in working directory. Reduces disk usage and git operations time.","Speed up git status","Checkout from remote only"],
     "answerIndex":1,"explanation":"Large monorepos (Meta, Google scale) can't be fully checked out. sparse-checkout lets you specify paths: only packages/frontend and shared/utils are present locally. Git still tracks full history but working directory is subset.","tags":["git","monorepo","sparse-checkout"]},
    {"id":"gitadv-q14","type":"mcq","prompt":"During git rebase, you get a conflict. What is the correct sequence of commands?",
     "choices":["git rebase --abort then merge instead","Fix conflicting files manually, git add <resolved-files>, git rebase --continue — repeat for each conflicting commit in the rebase","git push --force","git merge main to fix"],
     "answerIndex":1,"explanation":"Rebase conflict: fix file, git add (marks resolved), git rebase --continue (applies next commit). Repeat for each commit that has conflicts. If overwhelmed: git rebase --abort returns to pre-rebase state safely.","tags":["git","rebase","conflicts"]},
    {"id":"gitadv-q15","type":"multi","prompt":"Which commands are safe to run on a branch that teammates are also working on?",
     "choices":["git merge main (creates merge commit)","git rebase origin/main (rewrites SHAs)","git cherry-pick <sha> (creates new commit)","git push --force (overwrites remote history)"],
     "answerIndexes":[0,2],"explanation":"Merge and cherry-pick add new commits without rewriting existing ones — safe on shared branches. Rebase and force push rewrite history — dangerous on shared branches as they conflict with teammates' copies.","tags":["git","safety","shared-branches"]},
    {"id":"gitadv-q16","type":"mcq","prompt":"You ran 'git reset --hard HEAD~1' accidentally deleting a commit. How do you recover?",
     "choices":["The commit is gone forever","git reflog to find the deleted commit SHA (Git keeps objects for 30 days). git reset --hard <that-sha> to restore it.","git undo","git pull --force"],
     "answerIndex":1,"explanation":"Git never immediately deletes objects. reset --hard just moves HEAD pointer. The commit object still exists. reflog shows every HEAD movement including the previous state. Find SHA before the reset. git reset --hard <sha> restores it.","tags":["git","recovery","reflog"]},
    {"id":"gitadv-q17","type":"codeOutput","prompt":"What does this interactive rebase config do?",
     "code":"pick abc Add user model\nfixup def Fix typo\nreword ghi Add user service",
     "choices":["Creates 3 separate commits","Creates 2 commits: 'Add user model' (includes typo fix silently), then opens editor to rename 'Add user service'","Deletes all commits","Squashes all 3 into one"],
     "answerIndex":1,"explanation":"fixup: merges 'Fix typo' into 'Add user model', discards typo commit message. reword: opens editor on 'Add user service' to rename. Result: 2 commits: 1) Add user model (with typo fix inside), 2) [whatever you renamed it to].","tags":["git","interactive-rebase"]},
    {"id":"gitadv-q18","type":"mcq","prompt":"Monorepo benefit: why does 'atomic commits' matter?",
     "choices":["Commits are faster","In a monorepo, one commit can change frontend + backend + shared library simultaneously, deploying as one unit. Polyrepo: coordinating 3 PRs across 3 repos with correct ordering is error-prone.","Monorepos are smaller","Atomic means encrypted"],
     "answerIndex":1,"explanation":"API change: you modify the API (backend), update the client SDK (shared lib), and update the UI (frontend) in ONE commit. They all deploy together, atomically. Polyrepo: sync 3 separate PRs, risk of partial deployment mismatch.","tags":["git","monorepo"]},
    {"id":"gitadv-q19","type":"mcq","prompt":"git cherry-pick creates a new commit with a different SHA than the original. Why?",
     "choices":["Git randomises SHAs","The cherry-picked commit has a different parent commit — SHA is computed from content + parent + author + timestamp. Same changes, different parent = different SHA.","Bug in git","SHA includes file names"],
     "answerIndex":1,"explanation":"Git SHA (commit hash) is computed from: tree hash, parent hash, author, timestamp, message. Cherry-pick applies same changes but onto different parent (different branch tip). Different parent = different SHA.","tags":["git","cherry-pick","internals"]},
    {"id":"gitadv-q20","type":"mcq","prompt":"What is the purpose of git bisect run <script>?",
     "choices":["Runs git bisect multiple times","Fully automates bisect — git checks out each midpoint and runs <script>. Script exits 0 = good, exits non-0 = bad. Git finds the first bad commit with no human intervention needed.","Runs scripts in hooks","Tests all commits"],
     "answerIndex":0,"explanation":"git bisect run ./test.sh: git picks midpoint, runs test.sh, reads exit code (0=good/non-0=bad), picks next midpoint. Fully automated binary search. Takes same number of steps (log2(N)) but zero human intervention between steps.","tags":["git","bisect","automation"]},
]
# fix duplicate answer
GIT_ADV_Q[-1]["answerIndex"] = 1

GIT_ADV_FC = [
    {"id":"gitadv-fc1","front":"Rebase workflow before PR","back":"git fetch origin && git rebase origin/main. Fix conflicts: fix file, git add, git rebase --continue. If stuck: git rebase --abort. NEVER rebase already-pushed shared branches.","tags":["git","rebase"]},
    {"id":"gitadv-fc2","front":"Interactive rebase commands","back":"pick: keep as-is. squash: merge + edit message. fixup: merge + discard message. reword: keep changes, edit message. drop: delete commit. edit: pause to amend. git rebase -i HEAD~N to open.","tags":["git","interactive-rebase"]},
    {"id":"gitadv-fc3","front":"Cherry-pick use case","back":"Hotfix on main needs to go to release branch too: git checkout release/2.0 && git cherry-pick <hotfix-sha>. Creates new commit, different SHA, same changes. -n flag to cherry-pick without auto-committing.","tags":["git","cherry-pick"]},
    {"id":"gitadv-fc4","front":"Bisect workflow","back":"git bisect start → git bisect bad (HEAD) → git bisect good <working-sha> → test → mark good/bad → repeat → first bad commit found. git bisect reset to finish. Log2(N) steps only.","tags":["git","bisect"]},
    {"id":"gitadv-fc5","front":"Recover lost commits","back":"1. git reflog — find SHA before the mistake. 2. git reset --hard <sha> to restore. Git keeps unreachable objects for 30 days. reflog also shows: rebase checkpoints, stash entries, checkout history.","tags":["git","recovery","reflog"]},
    {"id":"gitadv-fc6","front":"husky setup (Node.js)","back":"npm install --save-dev husky && npx husky init. Edit .husky/pre-commit: add commands (npm run lint). Edit .husky/commit-msg: npx commitlint --edit $1. Hooks committed to repo = team-wide enforcement.","tags":["git","hooks","husky"]},
    {"id":"gitadv-fc7","front":"Squash merge vs rebase merge","back":"Squash: all PR commits → one commit on main (clean main history, lose feature detail). Rebase: all PR commits replayed on main (linear history, feature commits preserved). Merge: merge commit (preserves all, non-linear). Teams pick one and stay consistent.","tags":["git","merge-strategy"]},
    {"id":"gitadv-fc8","front":"Stash workflow","back":"git stash (save WIP) → switch branch → fix → commit → switch back → git stash pop. Named stash: git stash push -m 'name'. List: git stash list. Apply without removing: git stash apply stash@{N}.","tags":["git","stash"]},
]

GIT_ADV_PROJ = {
    "brief": "Your team is adopting a trunk-based development workflow: all feature branches short-lived (max 2 days), squash merged to main, all merges gated by CI passing. Design the git workflow: branch naming, commit message standard, hooks to enforce it, and the process for hotfixes. Document how to handle a case where main is broken by a bad merge.",
    "checklist": [
        {"id":"g1","text":"Branch naming: feat/ABC-123-description, fix/ABC-456-title. Branch protection requiring PR + CI pass.","weight":20},
        {"id":"g2","text":"Conventional Commits enforced via commitlint + husky commit-msg hook. CI validates too.","weight":20},
        {"id":"g3","text":"Squash merge all PRs to keep main history clean and linear. Branch deleted after merge.","weight":20},
        {"id":"g4","text":"Hotfix: branch hotfix/brief-name from main, fast-track CI, squash merge, tag release.","weight":20},
        {"id":"g5","text":"Broken main: git bisect on CI history to find breaking PR. Revert that PR's commit (git revert <sha>).","weight":20},
    ],
    "hints": [
        "git revert <sha> creates a new commit that undoes the bad one — safe for shared branches unlike reset.",
        "Conventional Commits semver: feat = minor bump, fix = patch, BREAKING CHANGE in footer = major.",
        "GitHub Actions: use branch protection rules requiring status checks. Prevents merging if CI red.",
    ]
}

write("languages", "git-advanced.json", {
    "id": "git-advanced",
    "unit": 12,
    "order": 114,
    "title": "Git Advanced",
    "summary": "Rebase, interactive history editing, cherry-pick, bisect for debugging, git hooks, and monorepo strategies.",
    "prereqs": ["git-fundamentals"],
    "guide": GIT_ADV_GUIDE,
    "questions": GIT_ADV_Q,
    "flashcards": GIT_ADV_FC,
    "project": GIT_ADV_PROJ,
})

# ─── TOPIC 3: python-fundamentals ────────────────────────────────────────────

PYTHON_GUIDE = "\n".join([
    "# Python Fundamentals for AI/ML Engineers",
    "",
    "## Why Python? (For Java/TypeScript Developers)",
    "",
    "You already know Java and TypeScript. Python feels easy at first (no types, no semicolons)",
    "but has deep features that make it uniquely powerful for AI/ML, scripting, and automation.",
    "",
    "```",
    "Java:   Person p = new Person('Alice', 30);",
    "Python: p = Person('Alice', 30)         # no type declaration",
    "",
    "TypeScript: const add = (a: number, b: number): number => a + b;",
    "Python:     def add(a, b): return a + b   # or with hints: def add(a: int, b: int) -> int",
    "",
    "Python philosophy: 'Batteries included'",
    "  Standard library has everything: HTTP, JSON, CSV, regex, DB, testing, zip, email",
    "  Third-party: NumPy, Pandas, PyTorch, FastAPI, LangChain — the AI/ML world",
    "```",
    "",
    "---",
    "",
    "## Python Basics — Core Syntax",
    "",
    "```python",
    "# Variables and types (dynamic, no declarations)",
    "name = 'Alice'         # str",
    "age = 30               # int",
    "score = 97.5           # float",
    "active = True          # bool (note: True/False with capital)",
    "",
    "# f-strings (like TypeScript template literals)",
    "print(f'Hello {name}, you are {age} years old')",
    "print(f'Score: {score:.2f}')  # 97.50 — format spec after colon",
    "",
    "# Lists (like TypeScript arrays)",
    "fruits = ['apple', 'banana', 'cherry']",
    "fruits.append('date')",
    "fruits[0]      # 'apple'",
    "fruits[-1]     # 'date'  ← negative index from end",
    "fruits[1:3]    # ['banana', 'cherry']  ← slice [start:end exclusive]",
    "",
    "# Dicts (like TypeScript objects/Maps)",
    "person = {'name': 'Alice', 'age': 30}",
    "person['age']  # 30",
    "person.get('email', 'N/A')  # 'N/A' — safe get with default",
    "",
    "# Sets (unique values, unordered — like Java Set)",
    "unique_ids = {1, 2, 3, 2, 1}  # {1, 2, 3}",
    "",
    "# Tuples (immutable list)",
    "coords = (51.5, -0.12)  # immutable: can't change coords[0]",
    "",
    "# None (like null/undefined)",
    "result = None",
    "if result is None:  # use 'is' not == for None check",
    "    print('No result yet')",
    "```",
    "",
    "---",
    "",
    "## List Comprehensions — Pythonic Loops",
    "",
    "```python",
    "# Regular loop:",
    "squares = []",
    "for i in range(10):",
    "    squares.append(i ** 2)",
    "",
    "# List comprehension (preferred Python style):",
    "squares = [i ** 2 for i in range(10)]",
    "# [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]",
    "",
    "# With condition (filter):",
    "evens = [i for i in range(20) if i % 2 == 0]",
    "",
    "# Dict comprehension:",
    "word_lengths = {word: len(word) for word in ['cat', 'elephant', 'ox']}",
    "# {'cat': 3, 'elephant': 8, 'ox': 2}",
    "",
    "# Set comprehension:",
    "unique_lengths = {len(word) for word in ['cat', 'dog', 'elephant']}",
    "# {3, 8}",
    "",
    "# Generator expression (lazy, memory efficient):",
    "total = sum(i ** 2 for i in range(1_000_000))  # doesn't create list in memory",
    "```",
    "",
    "---",
    "",
    "## Functions — Args, Kwargs, Defaults",
    "",
    "```python",
    "# Default arguments",
    "def greet(name, greeting='Hello'):",
    "    return f'{greeting}, {name}!'",
    "",
    "greet('Alice')              # 'Hello, Alice!'",
    "greet('Alice', 'Hi')        # 'Hi, Alice!'",
    "greet('Alice', greeting='Hey')  # keyword argument",
    "",
    "# *args: variable positional arguments (tuple)",
    "def add_all(*numbers):",
    "    return sum(numbers)",
    "",
    "add_all(1, 2, 3, 4)  # 10",
    "",
    "# **kwargs: variable keyword arguments (dict)",
    "def create_user(**fields):",
    "    return fields",
    "",
    "create_user(name='Alice', age=30, role='admin')",
    "# {'name': 'Alice', 'age': 30, 'role': 'admin'}",
    "",
    "# Type hints (Python 3.5+, not enforced by default)",
    "def process(text: str, max_tokens: int = 100) -> list[str]:",
    "    return text.split()[:max_tokens]",
    "```",
    "",
    "---",
    "",
    "## Decorators — Functions That Wrap Functions",
    "",
    "```",
    "A decorator is a function that takes a function and returns a modified version.",
    "Used extensively in: FastAPI routes, Flask routes, pytest fixtures, caching, logging.",
    "```",
    "",
    "```python",
    "# Creating a decorator:",
    "import time",
    "from functools import wraps",
    "",
    "def timer(func):",
    "    @wraps(func)  # preserves original function name/docstring",
    "    def wrapper(*args, **kwargs):",
    "        start = time.time()",
    "        result = func(*args, **kwargs)  # call original function",
    "        elapsed = time.time() - start",
    "        print(f'{func.__name__} took {elapsed:.3f}s')",
    "        return result",
    "    return wrapper",
    "",
    "# Using the decorator:",
    "@timer",
    "def slow_function():",
    "    time.sleep(1)",
    "    return 'done'",
    "",
    "# @timer is syntactic sugar for:",
    "# slow_function = timer(slow_function)",
    "",
    "slow_function()  # prints: 'slow_function took 1.001s'",
    "",
    "# Decorator with arguments:",
    "def retry(max_attempts=3):",
    "    def decorator(func):",
    "        @wraps(func)",
    "        def wrapper(*args, **kwargs):",
    "            for attempt in range(max_attempts):",
    "                try:",
    "                    return func(*args, **kwargs)",
    "                except Exception as e:",
    "                    if attempt == max_attempts - 1:",
    "                        raise",
    "                    print(f'Attempt {attempt+1} failed: {e}')",
    "        return wrapper",
    "    return decorator",
    "",
    "@retry(max_attempts=3)",
    "def call_api():",
    "    # might fail",
    "    pass",
    "",
    "# FastAPI route decorator (how it works internally):",
    "@app.get('/users/{user_id}')  # marks function as HTTP handler",
    "def get_user(user_id: int):   # FastAPI reads type hints for validation",
    "    return {'id': user_id}",
    "```",
    "",
    "---",
    "",
    "## Generators — Lazy Computation",
    "",
    "```python",
    "# Regular function: computes and returns all at once",
    "def squares_list(n):",
    "    return [i**2 for i in range(n)]",
    "# squares_list(1_000_000) creates list of 1M items in memory!",
    "",
    "# Generator: computes one item at a time (lazy)",
    "def squares_gen(n):",
    "    for i in range(n):",
    "        yield i**2  # yield pauses function, returns value, resumes next call",
    "",
    "gen = squares_gen(1_000_000)",
    "next(gen)  # 0  (computed just this one)",
    "next(gen)  # 1",
    "next(gen)  # 4",
    "# 1M items, zero memory",
    "",
    "# Use in for loop:",
    "for sq in squares_gen(10):",
    "    print(sq)",
    "",
    "# Generator pipeline (streaming data processing):",
    "def read_large_file(path):",
    "    with open(path) as f:",
    "        for line in f:       # Python file objects are generators!",
    "            yield line.strip()",
    "",
    "def filter_errors(lines):",
    "    for line in lines:",
    "        if 'ERROR' in line:",
    "            yield line",
    "",
    "# Process 10GB log file without loading into memory:",
    "errors = filter_errors(read_large_file('app.log'))",
    "for error in errors:",
    "    print(error)",
    "```",
    "",
    "---",
    "",
    "## Dataclasses — Modern Python Data Models",
    "",
    "```python",
    "from dataclasses import dataclass, field",
    "from typing import Optional",
    "",
    "# Old way (verbose):",
    "class PersonOld:",
    "    def __init__(self, name, age, email=None):",
    "        self.name = name",
    "        self.age = age",
    "        self.email = email",
    "    def __repr__(self):",
    "        return f'Person(name={self.name!r}, age={self.age})'",
    "",
    "# Dataclass way (auto-generates __init__, __repr__, __eq__):",
    "@dataclass",
    "class Person:",
    "    name: str",
    "    age: int",
    "    email: Optional[str] = None",
    "    tags: list[str] = field(default_factory=list)  # mutable default",
    "",
    "p = Person('Alice', 30)",
    "print(p)          # Person(name='Alice', age=30, email=None, tags=[])",
    "p == Person('Alice', 30)  # True — __eq__ auto-generated",
    "",
    "# Frozen dataclass (immutable, hashable):",
    "@dataclass(frozen=True)",
    "class Point:",
    "    x: float",
    "    y: float",
    "",
    "# Pydantic (popular in FastAPI — runtime validation):",
    "from pydantic import BaseModel",
    "",
    "class UserRequest(BaseModel):",
    "    name: str",
    "    age: int",
    "    email: str",
    "",
    "req = UserRequest(name='Alice', age='30', email='a@b.com')",
    "# age='30' → automatically coerced to int 30",
    "# Invalid email → raises ValidationError",
    "```",
    "",
    "---",
    "",
    "## Async — asyncio and await",
    "",
    "```python",
    "import asyncio",
    "import httpx  # async HTTP client",
    "",
    "# Sync (blocking): fetches one at a time",
    "def fetch_all_sync(urls):",
    "    results = []",
    "    for url in urls:              # 100 URLs × 500ms = 50 seconds",
    "        results.append(fetch(url))",
    "    return results",
    "",
    "# Async (concurrent): all requests in-flight simultaneously",
    "async def fetch_one(client, url):",
    "    response = await client.get(url)  # await = give control back while waiting",
    "    return response.json()",
    "",
    "async def fetch_all(urls):",
    "    async with httpx.AsyncClient() as client:",
    "        tasks = [fetch_one(client, url) for url in urls]",
    "        results = await asyncio.gather(*tasks)  # run all concurrently",
    "    return results                              # 100 URLs × 500ms = ~0.5 seconds",
    "",
    "# Run top-level:",
    "asyncio.run(fetch_all(urls))",
    "",
    "# Key rules:",
    "# async def function = coroutine, must be awaited",
    "# await = pause and let other tasks run",
    "# asyncio.gather = run multiple coroutines concurrently",
    "# asyncio is NOT threading — single thread, cooperative multitasking",
    "# Use asyncio for I/O-bound work (HTTP, DB, file)",
    "# Use multiprocessing for CPU-bound work (ML training, image processing)",
    "```",
    "",
    "---",
    "",
    "## Context Managers — with Statement",
    "",
    "```python",
    "# You use them already: with open('file') as f:",
    "# Context manager = setup + teardown guaranteed, even if exception",
    "",
    "# Creating your own:",
    "from contextlib import contextmanager",
    "",
    "@contextmanager",
    "def timer_ctx(name):",
    "    start = time.time()",
    "    try:",
    "        yield  # code inside 'with' block runs here",
    "    finally:",
    "        print(f'{name}: {time.time()-start:.3f}s')",
    "",
    "with timer_ctx('My operation') as _:",
    "    time.sleep(0.5)",
    "# prints: My operation: 0.500s (even if exception raised inside)",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "PYTHON FUNDAMENTALS",
    "|",
    "+-- BASICS",
    "|   +-- Dynamic typing, no declarations",
    "|   +-- list/dict/set/tuple comprehensions",
    "|   +-- f-strings, slice notation, negative indexing",
    "|",
    "+-- FUNCTIONS",
    "|   +-- *args (tuple), **kwargs (dict)",
    "|   +-- Default args, keyword args",
    "|   +-- Type hints (PEP 484)",
    "|",
    "+-- DECORATORS",
    "|   +-- Function that wraps function",
    "|   +-- @functools.wraps preserves metadata",
    "|   +-- Used in: FastAPI, Flask, pytest, logging",
    "|",
    "+-- GENERATORS",
    "|   +-- yield = lazy evaluation",
    "|   +-- Memory efficient for large data",
    "|   +-- File reading, data pipelines",
    "|",
    "+-- DATA CLASSES (pydantic)",
    "|   +-- @dataclass auto-gen __init__ __repr__",
    "|   +-- Pydantic: runtime validation + coercion",
    "|",
    "+-- ASYNC",
    "    +-- async/await = cooperative multitasking",
    "    +-- asyncio.gather = concurrent I/O",
    "    +-- Use for: HTTP calls, DB queries",
    "```",
    "",
    "---",
    "",
    "## References",
    "",
    "### Videos",
    "- **Python for Beginners** by Corey Schafer: https://www.youtube.com/playlist?list=PL-osiE80TeTskrapNbzXhwoFUiLCjGgY7",
    "- **Python Decorators** by Corey Schafer: https://www.youtube.com/watch?v=FsAPt_9Bf3U",
    "",
    "### Articles",
    "- **Real Python**: https://realpython.com — best practical Python tutorials",
    "- **Python Docs**: https://docs.python.org/3/ — especially dataclasses, asyncio",
    "",
    "### Practice",
    "- **Exercism Python track**: https://exercism.org/tracks/python",
    "- **LeetCode Python mode** — solve DSA problems in Python to learn idiomatic style",
])

PYTHON_Q = [
    {"id":"py-q1","type":"mcq","prompt":"Python list [1,2,3,4,5][-2:] returns what?",
     "choices":["[4,5]","[1,2]","[3,4]","Error — negative slice invalid"],
     "answerIndex":0,"explanation":"Negative index: -2 = 2nd from end = index 3 (value 4). Slice [-2:] = from index 3 to end = [4, 5]. Python slices are [start:end_exclusive]. Negative indexes count from end.","tags":["python","slicing"]},
    {"id":"py-q2","type":"mcq","prompt":"What does a generator function (yield) return when called?",
     "choices":["The return value immediately","List of all yielded values","A generator object — execution is suspended. Call next() to advance. Values computed lazily one at a time.","None"],
     "answerIndex":2,"explanation":"Calling a generator function doesn't execute it. It returns a generator object (iterator). next() advances execution to the next yield, pauses, returns value. Resumes from that point on the next next() call. This lazy evaluation saves memory.","tags":["python","generators"]},
    {"id":"py-q3","type":"mcq","prompt":"What is the difference between *args and **kwargs?",
     "choices":["*args is for dictionaries","*args: collects extra positional args into a tuple. **kwargs: collects extra keyword args into a dict. Both allow functions to accept variable number of arguments.","**kwargs is deprecated","They are identical"],
     "answerIndex":1,"explanation":"def f(*args, **kwargs): args = (1,2,3) if called as f(1,2,3). kwargs = {'a':1,'b':2} if called as f(a=1,b=2). Common in decorators: def wrapper(*args, **kwargs): return func(*args, **kwargs) to pass all args through unchanged.","tags":["python","functions","args"]},
    {"id":"py-q4","type":"codeOutput","prompt":"What does this print?",
     "code":"@lambda f: lambda x: f(x) * 2\ndef square(n):\n    return n * n\nprint(square(3))",
     "choices":["9","18","6","Error"],
     "answerIndex":1,"explanation":"Lambda decorator: takes square function, returns lambda x: square(x)*2. square(3) = 9. Decorator wraps it: 9*2 = 18. Decorators are applied at definition time: square = (lambda f: lambda x: f(x)*2)(square).","tags":["python","decorators"]},
    {"id":"py-q5","type":"mcq","prompt":"Why use functools.wraps when writing a decorator?",
     "choices":["Performance boost","wraps copies the wrapped function's __name__, __doc__, and other metadata to the wrapper function — without it, all decorated functions appear to have the name 'wrapper' which breaks debugging and introspection","Required for async decorators","wraps validates the function signature"],
     "answerIndex":1,"explanation":"Without @wraps: decorated function.__name__ = 'wrapper', decorated function.__doc__ = None. Debugging, logging, and docstring tools get confused. @wraps(func) copies metadata. Always use it in decorators.","tags":["python","decorators","functools"]},
    {"id":"py-q6","type":"mcq","prompt":"asyncio.gather([task1, task2, task3]) — what happens?",
     "choices":["Runs tasks sequentially","Runs all three coroutines concurrently — all are started immediately, gather waits for all to complete, returns list of results. Total time ≈ max(task times), not sum.","Only runs the first task","Runs tasks on multiple threads"],
     "answerIndex":1,"explanation":"asyncio.gather is the key for concurrent I/O. If task1=1s, task2=2s, task3=1.5s: sequential = 4.5s, gather ≈ 2s. All tasks make progress concurrently. NOT parallel — single thread, but all I/O wait time is shared.","tags":["python","asyncio"]},
    {"id":"py-q7","type":"mcq","prompt":"What is a Python dataclass vs a regular class?",
     "choices":["Dataclasses are immutable","@dataclass auto-generates boilerplate: __init__ (from annotated fields), __repr__ (nice printing), __eq__ (comparison). You only write field declarations. Dramatically reduces code.","Dataclasses are faster","Dataclass fields must be type annotated only in 3.12+"],
     "answerIndex":1,"explanation":"Without dataclass: write __init__, __repr__, __eq__ for each class manually. With @dataclass: name: str age: int → those three methods generated. frozen=True makes it immutable (also hashable — can be used as dict key or in sets).","tags":["python","dataclasses"]},
    {"id":"py-q8","type":"mcq","prompt":"Python comprehension [x for x in range(10) if x % 2 == 0] returns?",
     "choices":["[1,3,5,7,9]","[0,2,4,6,8]","[True,False,...]","Error"],
     "answerIndex":1,"explanation":"Range(10) = 0..9. Filter: x % 2 == 0 keeps even numbers. Result: [0,2,4,6,8]. Comprehension syntax: [expression for variable in iterable if condition]. The if condition is optional filtering.","tags":["python","comprehension"]},
    {"id":"py-q9","type":"mcq","prompt":"When should you use a generator instead of a list?",
     "choices":["Always — generators are faster","When processing large datasets where creating the full list in memory would be expensive or impossible — streaming files, API pagination, infinite sequences","Only for numbers","When list would be empty"],
     "answerIndex":1,"explanation":"Generator: O(1) memory (one item at a time). List: O(n) memory. For processing a 10GB log file: list comprehension tries to load all lines into RAM. Generator reads one line at a time. Also for infinite sequences you only partially consume.","tags":["python","generators","memory"]},
    {"id":"py-q10","type":"mcq","prompt":"What does 'yield from iterable' do in a generator?",
     "choices":["Returns the entire iterable at once","Delegates to another iterable — yields each item from the sub-iterable one by one. Equivalent to: for item in iterable: yield item. Cleaner syntax for generator chaining.","Imports from the iterable","Creates nested generators"],
     "answerIndex":1,"explanation":"yield from is syntactic sugar for yielding all items from a sub-iterable. def chain(*iterables): for i in iterables: yield from i. This is how itertools.chain works internally.","tags":["python","generators","yield-from"]},
    {"id":"py-q11","type":"mcq","prompt":"Python dict.get(key, default) vs dict[key] — when to use each?",
     "choices":["Always use []","dict[key] raises KeyError if key doesn't exist. dict.get(key, default) returns default value (or None) if key missing — never raises. Use get() when key may be absent.","get() is deprecated","They are identical"],
     "answerIndex":1,"explanation":"user['email'] → KeyError if user has no 'email' key. user.get('email', 'N/A') → 'N/A' safely. In AI/ML: JSON API responses often have optional fields — always use .get() for optional keys.","tags":["python","dict"]},
    {"id":"py-q12","type":"codeOutput","prompt":"What does this print?",
     "code":"def make_counter():\n    count = 0\n    def increment():\n        nonlocal count\n        count += 1\n        return count\n    return increment\n\nc = make_counter()\nprint(c(), c(), c())",
     "choices":["1 1 1","0 1 2","1 2 3","Error"],
     "answerIndex":2,"explanation":"Closure: increment() captures count from outer scope. nonlocal allows modifying it. Each call to c() increments count: 1, 2, 3. Without nonlocal: UnboundLocalError (Python treats count as local to increment if assigned).","tags":["python","closures","nonlocal"]},
    {"id":"py-q13","type":"mcq","prompt":"Pydantic BaseModel validates input at runtime. What happens when you pass age='30' to a model with age: int?",
     "choices":["TypeError raised","Pydantic coerces '30' to integer 30 automatically — string to int conversion is a built-in coercion. If it can't coerce (e.g., age='abc'), raises ValidationError.","None returned","Name becomes 'thirty'"],
     "answerIndex":1,"explanation":"Pydantic does runtime type coercion by default (Pydantic v1) or strict mode in v2. '30' → 30 is valid coercion. 'thirty' → ValidationError. FastAPI uses Pydantic for request validation: all path params, query params, and request bodies are auto-validated.","tags":["python","pydantic","validation"]},
    {"id":"py-q14","type":"mcq","prompt":"What is the GIL (Global Interpreter Lock) in Python?",
     "choices":["A variable locking mechanism","CPython's mutex that allows only ONE thread to execute Python bytecode at a time — effectively making Python threads single-core for CPU-bound work. I/O-bound threads release GIL during I/O wait, so asyncio/threading help there.","A Python 2 feature","Related to file locking"],
     "answerIndex":1,"explanation":"GIL: even with 16 CPU cores, CPython can only execute Python bytecode on one at a time. For CPU-bound tasks: use multiprocessing (each process has own GIL). For I/O-bound: asyncio or threading (threads release GIL during I/O). Python 3.13+ has experimental 'no-GIL' mode.","tags":["python","gil","concurrency"]},
    {"id":"py-q15","type":"mcq","prompt":"Python context manager (with statement) purpose?",
     "choices":["Performance optimization","Guarantees __enter__ (setup) runs before the block and __exit__ (teardown) runs after — even if an exception occurs. Use for: file closing, DB transactions, locking, timer.","Required for file operations only","Replaces try/except"],
     "answerIndex":1,"explanation":"with open('f') as f: guarantees f.close() even if exception. with db.transaction(): commits or rolls back. The 'with' statement calls __enter__ at start and __exit__ at end (exception or not). @contextmanager decorator makes writing context managers easy.","tags":["python","context-manager"]},
    {"id":"py-q16","type":"mcq","prompt":"What is the difference between asyncio and multiprocessing?",
     "choices":["asyncio uses multiple CPUs","asyncio: single thread, multiple coroutines — concurrent I/O, zero CPU parallelism. multiprocessing: multiple processes, each with own Python interpreter — true CPU parallelism, no GIL sharing. Use asyncio for I/O, multiprocessing for CPU.","multiprocessing is deprecated","asyncio is faster"],
     "answerIndex":1,"explanation":"asyncio: concurrent HTTP calls, DB queries. multiprocessing: ML model training, image processing, heavy computations. Mistake: using asyncio for CPU-bound work (doesn't help — single thread). Mistake: using multiprocessing for network requests (overkill, spawning processes is expensive).","tags":["python","asyncio","multiprocessing"]},
    {"id":"py-q17","type":"mcq","prompt":"Python's `if __name__ == '__main__':` guard — why use it?",
     "choices":["Improves performance","Code under this block only runs when the file is executed directly (python script.py), NOT when imported as a module. Prevents side effects (running servers, printing) when the file is imported elsewhere.","Required by Python 3","Style preference only"],
     "answerIndex":1,"explanation":"When Python imports a module, all top-level code runs. Without this guard, starting a server or running tests on import causes bugs. With the guard: import my_module safely, run it directly to execute main logic. Essential for any script that also has reusable functions.","tags":["python","modules","main"]},
    {"id":"py-q18","type":"mcq","prompt":"What does this comprehension produce: {k: v for k, v in d.items() if v is not None}?",
     "choices":["Filtered list of keys","New dict with None values removed — dict comprehension iterates key-value pairs, keeps only pairs where value is not None","List of non-None values","Set of keys"],
     "answerIndex":1,"explanation":"d.items() returns (key, value) pairs. k, v = tuple unpacking per pair. Comprehension builds new dict with only non-None values. Common pattern for cleaning API responses before sending or storing.","tags":["python","comprehension","dict"]},
    {"id":"py-q19","type":"mcq","prompt":"Python's enumerate() function:",
     "choices":["Converts to enum type","Wraps an iterable to provide (index, value) pairs — avoids manual counter variable. for i, item in enumerate(items): instead of i=0; i+=1 pattern.","Sorts by index","Creates numbered list"],
     "answerIndex":1,"explanation":"for i, name in enumerate(['Alice','Bob','Carol']): gives (0,'Alice'), (1,'Bob'), (2,'Carol'). Optional start parameter: enumerate(items, start=1) gives 1-based. Pythonic alternative to range(len(items)) pattern.","tags":["python","iteration","enumerate"]},
    {"id":"py-q20","type":"mcq","prompt":"What does @dataclass(frozen=True) provide that regular @dataclass doesn't?",
     "choices":["Faster instantiation","Immutability (attempting to set fields after creation raises FrozenInstanceError) AND hashability (can be used as dict key or in sets) — because __hash__ is generated from fields.","Automatic serialization","Database integration"],
     "answerIndex":1,"explanation":"Regular @dataclass fields can be mutated. frozen=True prevents all mutation. As a side effect: the dataclass becomes hashable (like a tuple). Use for: value objects, cache keys, set membership. Pydantic models are similar in concept.","tags":["python","dataclasses","immutability"]},
]

PYTHON_FC = [
    {"id":"py-fc1","front":"List comprehension syntax","back":"[expression for var in iterable if condition]. Dict: {k:v for...}. Set: {x for...}. Generator (lazy): (expression for...). Use generator when result is used only once or dataset is large.","tags":["python","comprehension"]},
    {"id":"py-fc2","front":"Decorator pattern","back":"decorator = function that takes function, returns wrapper function. @wraps(func) preserves metadata. @decorator is syntactic sugar for func = decorator(func). Used in: FastAPI routes, caching, retry logic, auth checks.","tags":["python","decorators"]},
    {"id":"py-fc3","front":"Generator vs List","back":"List: O(n) memory, all computed at once. Generator: O(1) memory, lazy on-demand. Use generators for: large files, API pagination, infinite sequences, data pipelines. yield pauses, resumes on next().","tags":["python","generators"]},
    {"id":"py-fc4","front":"async/await rules","back":"async def = coroutine. Must be awaited. await = give up control while waiting for I/O. asyncio.gather(*coros) = run concurrently. asyncio.run(main()) = entry point. NOT threads — single thread. Doesn't help CPU-bound work.","tags":["python","asyncio"]},
    {"id":"py-fc5","front":"*args and **kwargs","back":"*args: extra positional args → tuple. **kwargs: extra keyword args → dict. Decorator passthrough: def wrapper(*args, **kwargs): return func(*args, **kwargs). Caller-side: spread list with *list, spread dict with **dict.","tags":["python","functions"]},
    {"id":"py-fc6","front":"Dataclass vs Pydantic","back":"@dataclass: auto __init__/__repr__/__eq__, no runtime validation. Pydantic BaseModel: runtime type validation + coercion, serialisation, JSON schema. Use dataclass for internal data structures, Pydantic for API schemas (FastAPI uses Pydantic).","tags":["python","dataclasses","pydantic"]},
    {"id":"py-fc7","front":"GIL — when it matters","back":"GIL prevents true CPU parallelism in CPython. I/O-bound: threads and asyncio work fine (GIL released during I/O). CPU-bound: use multiprocessing (each process bypasses GIL). Alternative: use PyPy, numba, or C extensions for CPU-heavy work.","tags":["python","gil","concurrency"]},
    {"id":"py-fc8","front":"Context manager usage","back":"with statement calls __enter__ before block, __exit__ after (even on exception). @contextmanager decorator + yield simplifies writing them. Use for: files (auto-close), DB transactions (auto-commit/rollback), timers, locks.","tags":["python","context-manager"]},
]

PYTHON_PROJ = {
    "brief": "Build a data pipeline in Python that reads a large log file (simulate with 100K lines), filters ERROR lines, extracts timestamp and message, aggregates error counts by hour, and writes a summary CSV. Use generators throughout to keep memory usage O(1) regardless of file size. Add a decorator for timing each pipeline stage.",
    "checklist": [
        {"id":"p1","text":"read_lines(path) — generator that yields one line at a time (never loads full file)","weight":20},
        {"id":"p2","text":"filter_errors(lines) — generator that yields only ERROR lines","weight":20},
        {"id":"p3","text":"parse_log(lines) — generator yielding dataclasses: LogEntry(timestamp, level, message)","weight":20},
        {"id":"p4","text":"@timer decorator on each stage function using functools.wraps","weight":20},
        {"id":"p5","text":"aggregate(entries) — dict comprehension or defaultdict to count errors per hour, write CSV with csv.DictWriter","weight":20},
    ],
    "hints": [
        "Generator composition: errors = filter_errors(read_lines('app.log')). No data processed until you iterate.",
        "from collections import defaultdict: counts = defaultdict(int); counts[hour] += 1",
        "Dataclass for log entry: @dataclass class LogEntry: timestamp: datetime; level: str; message: str",
    ]
}

write("languages", "python-fundamentals.json", {
    "id": "python-fundamentals",
    "unit": 12,
    "order": 115,
    "title": "Python Fundamentals",
    "summary": "Python for AI/ML engineers: list comprehensions, decorators, generators, async/await, dataclasses, and Pydantic.",
    "prereqs": ["git-fundamentals"],
    "guide": PYTHON_GUIDE,
    "questions": PYTHON_Q,
    "flashcards": PYTHON_FC,
    "project": PYTHON_PROJ,
})

print("\n=== Batch 2 Complete ===")
print("Topics written to src/content/topics/languages/")
print("  - sql-advanced.json")
print("  - git-advanced.json")
print("  - python-fundamentals.json")

