import json
from pathlib import Path

# ═══════════════════════════════════════════════════════════════
#  PYCHARM POWER-USE
# ═══════════════════════════════════════════════════════════════
p_py = Path('/Users/eptr6dj/IdeaProjects/master-cs/cs-mastery/src/content/topics/cloud-devops/pycharm.json')
d_py = json.loads(p_py.read_text())

PYCHARM_GUIDE = "\n".join([
    "# PyCharm Power-Use",
    "",
    "## What Is PyCharm? (Start From Zero)",
    "",
    "PyCharm is an IDE (Integrated Development Environment) built by JetBrains specifically",
    "for Python development. If you have used VS Code, think of PyCharm as a supercharged",
    "version that deeply understands Python — it knows your code structure, catches errors",
    "before you run anything, and automates repetitive tasks.",
    "",
    "**You might ask: why not just use VS Code or Notepad?**",
    "",
    "When you write a single 50-line script, any editor works. But when you work on a",
    "large Python project with hundreds of files, multiple environments, complex dependencies,",
    "and a team of developers — PyCharm's deep tooling saves hours every day.",
    "",
    "```",
    "Editor:                              PyCharm:",
    "  You type code                        Auto-completes as you type",
    "  You run it to find mistakes          Red underlines before you run",
    "  You manually search for a method     Ctrl+click goes to definition instantly",
    "  You read docs in a browser           Docs appear in-editor on hover",
    "  You manually run tests               Run all tests with one click, see results",
    "  You switch Python versions manually  Manage environments in Settings",
    "```",
    "",
    "---",
    "",
    "## Setting Up PyCharm for the First Time",
    "",
    "```",
    "Download: https://www.jetbrains.com/pycharm/",
    "  Community Edition: free, everything covered in this guide",
    "  Professional Edition: paid, adds Django/Flask support, remote dev, DB tools",
    "  Students: free Professional licence via JetBrains Student Pack",
    "",
    "First-time setup checklist:",
    "  1. Open PyCharm, click 'New Project'",
    "  2. Set the project location (folder)",
    "  3. Under Python Interpreter: choose 'New Virtualenv Environment'",
    "     - This creates an isolated Python environment just for this project",
    "     - Libraries installed here don't affect other projects",
    "  4. Click Create",
    "  5. PyCharm creates: your project folder + venv/ subfolder",
    "",
    "Every Python project should have its OWN virtual environment.",
    "Never install everything into the system Python.",
    "```",
    "",
    "---",
    "",
    "## Virtual Environments — Why They Matter",
    "",
    "```",
    "Problem: Project A needs Django 3.2. Project B needs Django 4.2.",
    "Without venv: install both? Python can only have one version installed globally.",
    "Result: one project breaks.",
    "",
    "Solution: Virtual environments",
    "  Project A: venv/ -> Django 3.2, requests 2.28",
    "  Project B: venv/ -> Django 4.2, requests 2.31",
    "  Each project is completely isolated.",
    "",
    "In PyCharm:",
    "  Settings -> Project -> Python Interpreter",
    "  Click gear icon -> Add Interpreter",
    "  Choose: Virtualenv (local), Conda, or system",
    "",
    "From terminal in PyCharm:",
    "  python -m venv venv        # create virtual environment",
    "  source venv/bin/activate   # activate (Mac/Linux)",
    "  venv\\Scripts\\activate    # activate (Windows)",
    "  pip install requests       # installs into THIS venv only",
    "  pip freeze > requirements.txt  # record exact versions",
    "  pip install -r requirements.txt  # recreate on another machine",
    "```",
    "",
    "---",
    "",
    "## The Most Important Keyboard Shortcuts",
    "",
    "Memorising these shortcuts turns PyCharm from a fancy text editor into a superpower.",
    "",
    "```",
    "NAVIGATION (finding things fast):",
    "  Shift+Shift           Search Everywhere — file, class, action, setting",
    "  Ctrl+N  (Cmd+O)       Go to Class by name",
    "  Ctrl+Shift+N          Go to File by name",
    "  Ctrl+Click            Go to Definition — jump to where method/class is defined",
    "  Ctrl+Alt+←/→          Navigate back/forward (like browser history)",
    "  Ctrl+E                Recent files popup",
    "  Alt+F7                Find all usages of selected symbol",
    "  Ctrl+F12              File structure popup — see all methods in current file",
    "",
    "CODE EDITING:",
    "  Ctrl+Space            Code completion",
    "  Ctrl+Shift+Space      Smart completion (context-aware)",
    "  Alt+Enter             Show quick fixes (fix import, create method, suppress warning)",
    "  Ctrl+D                Duplicate line",
    "  Ctrl+Y                Delete line",
    "  Ctrl+/                Comment/uncomment line",
    "  Ctrl+Shift+/          Block comment",
    "  Tab / Shift+Tab       Indent / Unindent selection",
    "  Ctrl+Shift+F          Reformat code (apply PEP 8 style)",
    "  Ctrl+Alt+L  (Cmd+Opt+L)  Reformat file",
    "",
    "REFACTORING:",
    "  Shift+F6              Rename — renames ALL usages simultaneously",
    "  Ctrl+Alt+M            Extract Method — turn selection into a function",
    "  Ctrl+Alt+V            Extract Variable",
    "  Ctrl+Alt+C            Extract Constant",
    "  F6                    Move file/class to different module",
    "",
    "RUNNING & DEBUGGING:",
    "  Shift+F10             Run current configuration",
    "  Shift+F9              Debug current configuration",
    "  Ctrl+F2               Stop running process",
    "  F8                    Step over (debugger)",
    "  F7                    Step into (debugger)",
    "  Shift+F8              Step out (debugger)",
    "  F9                    Resume program (debugger)",
    "",
    "SEARCH:",
    "  Ctrl+F                Find in file",
    "  Ctrl+R                Find and replace in file",
    "  Ctrl+Shift+F          Find in project (all files)",
    "  Ctrl+Shift+R          Replace in project",
    "```",
    "",
    "---",
    "",
    "## Code Completion and Smart Suggestions",
    "",
    "```",
    "Basic completion (Ctrl+Space):",
    "  Type 're' -> PyCharm suggests: requests, re, read, readline...",
    "  Type 'my_list.' -> suggests: append, extend, pop, sort, reverse...",
    "",
    "Smart completion (Ctrl+Shift+Space):",
    "  Knows the TYPE of what you are typing.",
    "  If function expects a str, only shows string variables.",
    "",
    "Postfix completion:",
    "  Type: my_list.for  then press Tab",
    "  Result: for item in my_list:",
    "              ...",
    "",
    "  Type: condition.if  then Tab",
    "  Result: if condition:",
    "              ...",
    "",
    "  Type: 'hello'.len  then Tab",
    "  Result: len('hello')",
    "",
    "Live Templates (code snippets):",
    "  Type 'iter' + Tab -> for item in collection: ...",
    "  Type 'main' + Tab -> if __name__ == '__main__': ...",
    "  Type 'def' + Tab  -> def function_name(params): ...",
    "  Settings -> Editor -> Live Templates to see and add your own",
    "```",
    "",
    "---",
    "",
    "## The Debugger — Step Through Your Code",
    "",
    "The debugger is one of the biggest productivity gains. Instead of adding `print()`",
    "statements everywhere, you pause execution and inspect everything.",
    "",
    "```",
    "HOW TO DEBUG:",
    "  1. Click in the gutter (left margin) next to a line number",
    "     A RED DOT appears — this is a BREAKPOINT",
    "  2. Press Shift+F9 (Debug) instead of Shift+F10 (Run)",
    "  3. Program pauses at the breakpoint",
    "  4. In the Debug panel you see:",
    "     - Variables: current values of ALL variables in scope",
    "     - Call stack: how you got here (which functions called which)",
    "  5. Navigate:",
    "     F8 = Step Over   (go to next line, don't enter calls)",
    "     F7 = Step Into   (go inside the function being called)",
    "     F9 = Resume      (run until next breakpoint)",
    "",
    "EVALUATE EXPRESSION (most powerful feature):",
    "  While paused, press Alt+F8",
    "  Type any Python expression and see its value RIGHT NOW",
    "  e.g.: len(my_list), my_dict.get('key'), type(obj)",
    "  No need to restart or add print statements",
    "",
    "WATCHES:",
    "  In Variables panel, click + to add a watch expression",
    "  PyCharm evaluates it continuously as you step through",
    "",
    "CONDITIONAL BREAKPOINTS:",
    "  Right-click a breakpoint -> Edit",
    "  Add condition: only pause when count > 100",
    "  Useful in loops where you only care about specific iterations",
    "```",
    "",
    "---",
    "",
    "## Integrated Terminal and Run Configurations",
    "",
    "```",
    "TERMINAL (Alt+F12 or View -> Tool Windows -> Terminal):",
    "  Opens a terminal inside PyCharm",
    "  Automatically activates your project's virtualenv",
    "  Run: pip install, git commands, scripts",
    "",
    "RUN CONFIGURATIONS:",
    "  A saved set of 'how to run this program'",
    "  Top right dropdown -> Edit Configurations",
    "",
    "  Add configuration:",
    "    Script path: path to your main.py",
    "    Parameters: command-line arguments",
    "    Environment variables: DB_URL=..., DEBUG=True",
    "    Working directory: where to run from",
    "",
    "  Why save configurations?",
    "  - Run the same script with one button",
    "  - Different configs for dev/test/prod",
    "  - Set env vars without modifying code",
    "  - Share via .run/ folder in git (optional)",
    "```",
    "",
    "---",
    "",
    "## Refactoring Tools",
    "",
    "```",
    "RENAME (Shift+F6) — the most-used refactoring:",
    "  Place cursor on variable/function/class name",
    "  Press Shift+F6",
    "  Type new name -> Enter",
    "  PyCharm renames EVERY occurrence in the ENTIRE project",
    "  Including string references and comments (optional)",
    "  This is safe: PyCharm understands the code, not just text",
    "",
    "EXTRACT METHOD (Ctrl+Alt+M):",
    "  Select a block of code",
    "  Press Ctrl+Alt+M",
    "  Name the new function",
    "  PyCharm creates the function, moves the code, adds the call",
    "  Parameters are inferred from used variables",
    "",
    "EXTRACT VARIABLE (Ctrl+Alt+V):",
    "  Select an expression: len(my_list) * 2",
    "  Press Ctrl+Alt+V",
    "  Name it: doubled_length",
    "  Code becomes: doubled_length = len(my_list) * 2",
    "  All occurrences of that expression are replaced",
    "",
    "MOVE (F6):",
    "  Move a class/function to a different file/module",
    "  All imports are updated automatically",
    "```",
    "",
    "---",
    "",
    "## Code Inspections and Quick Fixes",
    "",
    "```",
    "PyCharm continuously analyses your code and shows problems:",
    "",
    "Red underline:     Error — code will not run (undefined name, syntax error)",
    "Yellow underline:  Warning — potential issue (unused import, shadowed variable)",
    "Green underline:   Weak warning — style suggestion",
    "",
    "Quick Fix (Alt+Enter on any underlined code):",
    "  Missing import -> 'Import requests'",
    "  Undefined method -> 'Create method'",
    "  Wrong type -> type annotation suggestion",
    "  Long line -> 'Split string'",
    "  Unused variable -> 'Rename to _'",
    "",
    "The inspection marker in the top-right gutter shows overall file health.",
    "Green check = no issues. Yellow = warnings. Red = errors.",
    "",
    "Run inspections on whole project:",
    "  Analyze -> Inspect Code",
    "  See all issues across ALL files at once",
    "```",
    "",
    "---",
    "",
    "## Testing with PyTest in PyCharm",
    "",
    "```",
    "SETUP:",
    "  Settings -> Tools -> Python Integrated Tools",
    "  Default test runner: pytest",
    "",
    "RUNNING TESTS:",
    "  Green run icon next to test function/class/file",
    "  Click to run that specific test",
    "  Ctrl+Shift+F10 = run tests in current file",
    "  Run -> Run All Tests = run entire test suite",
    "",
    "TEST PANEL:",
    "  Shows all tests: green = passed, red = failed",
    "  Click a failed test to see the assertion error",
    "  Re-run only failed tests (useful for large suites)",
    "",
    "DEBUGGING A TEST:",
    "  Click the debug icon (bug icon) next to a test",
    "  Set a breakpoint in your test or the tested code",
    "  Step through to see exactly why it fails",
    "",
    "COVERAGE:",
    "  Run with Coverage (Shift+Alt+F10, or right-click -> Run with Coverage)",
    "  Editor shows: green lines = covered, red = not covered by tests",
    "  Highlights exactly which code paths your tests miss",
    "```",
    "",
    "---",
    "",
    "## Git Integration",
    "",
    "```",
    "PyCharm has full Git support without leaving the IDE.",
    "",
    "COMMIT (Ctrl+K):",
    "  Opens commit panel",
    "  See all changed files (diff on right)",
    "  Check which files to include",
    "  Write commit message",
    "  Press Commit (or Commit and Push)",
    "",
    "PUSH (Ctrl+Shift+K):",
    "  Push committed changes to remote",
    "",
    "PULL:",
    "  Git menu -> Pull (or fetch first to see what's incoming)",
    "",
    "DIFF VIEW:",
    "  Right-click any file -> Git -> Compare with Branch",
    "  Side-by-side diff of your changes vs any branch",
    "",
    "HISTORY (RIGHT-CLICK FILE):",
    "  Show History -> see every commit that touched this file",
    "  Who changed it, when, what was the message",
    "  Click any revision to see the diff",
    "",
    "ANNOTATE (git blame):",
    "  Right-click in editor gutter -> Annotate with Git Blame",
    "  Each line shows: author, date, commit hash",
    "",
    "RESOLVE MERGE CONFLICTS:",
    "  PyCharm shows a 3-panel merge tool",
    "  Left: your changes, Middle: result, Right: incoming",
    "  Click arrows to accept/reject each change",
    "  Much cleaner than resolving conflicts in a terminal",
    "```",
    "",
    "---",
    "",
    "## Database Tools (Professional Edition)",
    "",
    "```",
    "View -> Tool Windows -> Database",
    "  Add Data Source: PostgreSQL, MySQL, SQLite, etc.",
    "  Enter connection details",
    "",
    "Once connected:",
    "  Browse tables in tree view",
    "  Run SQL queries in an editor with autocomplete",
    "  Edit cells directly in the table view",
    "  Export query results as CSV",
    "  View table structure (columns, types, indexes)",
    "",
    "SQL autocomplete:",
    "  PyCharm knows your schema",
    "  SELECT * FROM  ->  suggests table names",
    "  WHERE user.  ->  suggests column names",
    "  Joins are autocompleted based on foreign keys",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "PYCHARM POWER-USE",
    "|",
    "+-- ENVIRONMENTS",
    "|   +-- Virtual environments (isolated per project)",
    "|   +-- Settings -> Python Interpreter",
    "|   +-- pip + requirements.txt",
    "|",
    "+-- NAVIGATION",
    "|   +-- Shift+Shift (search everywhere)",
    "|   +-- Ctrl+Click (go to definition)",
    "|   +-- Alt+F7 (find usages)",
    "|   +-- Ctrl+E (recent files)",
    "|",
    "+-- EDITING",
    "|   +-- Alt+Enter (quick fixes)",
    "|   +-- Shift+F6 (rename all usages)",
    "|   +-- Ctrl+Alt+M (extract method)",
    "|   +-- Ctrl+Alt+L (reformat code)",
    "|",
    "+-- DEBUGGING",
    "|   +-- Breakpoints (click gutter)",
    "|   +-- Step Over/Into/Out (F8/F7/Shift+F8)",
    "|   +-- Evaluate Expression (Alt+F8)",
    "|   +-- Conditional breakpoints",
    "|",
    "+-- TESTING",
    "|   +-- Run/debug individual tests",
    "|   +-- Coverage view",
    "|   +-- Re-run failed only",
    "|",
    "+-- GIT",
    "|   +-- Commit (Ctrl+K)",
    "|   +-- History / Blame",
    "|   +-- Merge conflict tool",
    "|",
    "+-- RUN CONFIGS",
    "    +-- Script path + args + env vars",
    "    +-- Multiple configs per project",
    "```",
    "",
    "---",
    "",
    "## References and Further Learning",
    "",
    "### Videos (Watch These!)",
    "- **PyCharm Tips and Tricks** by JetBrains (official):",
    "  https://www.youtube.com/watch?v=NoDx0MEESDw",
    "  - Official JetBrains video. Demonstrates key features in real workflow.",
    "- **Top 10 PyCharm Shortcuts You Need to Know** by Tech With Tim:",
    "  https://www.youtube.com/watch?v=Gz0f8iFhOAs",
    "  - Practical shortcuts with demos. Great for beginners.",
    "",
    "### Free Books and Articles",
    "- **PyCharm official documentation**: https://www.jetbrains.com/help/pycharm/",
    "  - 'Getting Started' and 'Debugging' sections are most useful first.",
    "- **JetBrains Academy** (interactive Python + PyCharm course): https://hyperskill.org/",
    "  - Free tier available. Learn Python while using PyCharm features.",
    "",
    "### Diagrams and Cheatsheets",
    "- **PyCharm Keyboard Shortcuts PDF (Mac)**: https://resources.jetbrains.com/storage/products/pycharm/docs/PyCharm_ReferenceCard_mac.pdf",
    "- **PyCharm Keyboard Shortcuts PDF (Win/Linux)**: https://resources.jetbrains.com/storage/products/pycharm/docs/PyCharm_ReferenceCard.pdf",
    "  - Print this and stick it on your monitor. Use it daily for 2 weeks — muscle memory locks in.",
    "",
    "### Practice",
    "- **JetBrains IDE Features Trainer** (built into PyCharm!):",
    "  Help -> IDE Features Trainer",
    "  Built-in interactive lessons for shortcuts and features. Do all of them.",
])

PYCHARM_NEW_Q = [
    {"id":"pycharm-q1-real","type":"mcq","prompt":"What is the keyboard shortcut to search for ANYTHING in PyCharm (files, classes, actions, settings)?",
     "choices":["Ctrl+F","Ctrl+N","Shift+Shift (double Shift)","Ctrl+Shift+F"],
     "answerIndex":2,"explanation":"Double Shift opens 'Search Everywhere' — a single dialog that finds files, classes, symbols, actions, and settings. The single most useful shortcut in PyCharm.","tags":["shortcuts","navigation"]},
    {"id":"pycharm-q2-real","type":"mcq","prompt":"What does Alt+Enter do in PyCharm?",
     "choices":["Runs the current file","Opens terminal","Shows context-aware quick fixes — adds missing imports, creates missing methods, fixes type issues",
                "Formats the code"],
     "answerIndex":2,"explanation":"Alt+Enter is PyCharm's magic wand. On any red/yellow underline, it offers intelligent fixes. Most common: auto-import a missing module. Learn this one shortcut and your productivity triples immediately.","tags":["shortcuts","quick-fixes"]},
    {"id":"pycharm-q3-real","type":"mcq","prompt":"Why should each Python project have its own virtual environment?",
     "choices":["Virtual environments make code run faster","They allow different projects to have different (potentially conflicting) dependency versions without interfering with each other","They are required by PyCharm","They encrypt your code"],
     "answerIndex":1,"explanation":"Project A needs Django 3.2, Project B needs Django 4.2. Without venv, only one can be installed globally. Virtual environments give each project an isolated Python environment with its own packages.","tags":["virtualenv","environments"]},
    {"id":"pycharm-q4-real","type":"mcq","prompt":"You want to rename a function used in 50 files. What is the safest way in PyCharm?",
     "choices":["Find+Replace in all files","Manually edit each file","Shift+F6 (Rename refactoring) — PyCharm finds and renames ALL usages across the entire project safely",
                "Delete and rewrite"],
     "answerIndex":2,"explanation":"Rename refactoring (Shift+F6) understands code structure — not just text. It renames the definition and every reference. Find+Replace is text-based and can rename unrelated things with the same name.","tags":["refactoring","rename"]},
    {"id":"pycharm-q5-real","type":"mcq","prompt":"What does Ctrl+Click on a function name do?",
     "choices":["Runs the function","Copies the function","Jumps to the function's definition — wherever it is defined in the codebase",
                "Deletes the function"],
     "answerIndex":2,"explanation":"Go to Definition instantly navigates you to where the function/class/variable was defined — in the same file, another file, or even inside a library. Essential for understanding unfamiliar codebases.","tags":["navigation","shortcuts"]},
    {"id":"pycharm-q6-real","type":"mcq","prompt":"You set a breakpoint and press Shift+F9. Execution pauses. You press F8. What happens?",
     "choices":["Program terminates","Execution jumps to the next breakpoint","Executes the current line and moves to the next line WITHOUT entering any called functions (Step Over)",
                "Enters the function on the current line"],
     "answerIndex":2,"explanation":"F8 = Step Over. Runs the current line and stops at the next. If the line calls a function, that function runs entirely — you stay at the same level. F7 = Step Into (enters the function call).","tags":["debugging","shortcuts"]},
    {"id":"pycharm-q7-real","type":"mcq","prompt":"What is the Evaluate Expression feature in the debugger?",
     "choices":["Runs the entire program","Evaluates a Python expression in the current paused stack frame — lets you inspect any value or test any code without restarting",
                "Shows stack trace","Opens the terminal"],
     "answerIndex":1,"explanation":"While paused at a breakpoint (Alt+F8): type any Python expression and see its value right now. type(my_var), len(list), my_dict['key'] — all evaluated in the CURRENT execution context. Huge time saver.","tags":["debugging","evaluate"]},
    {"id":"pycharm-q8-real","type":"mcq","prompt":"What does Ctrl+Alt+M (Extract Method) do?",
     "choices":["Creates a new method from scratch","Moves the selected code block into a new function, with parameters inferred from used variables, and replaces the selection with a call to that function",
                "Copies a method","Deletes a method"],
     "answerIndex":1,"explanation":"Extract Method is one of the most powerful refactorings. Select any block of code, press Ctrl+Alt+M, name the function — PyCharm moves the code, figures out what parameters are needed, and inserts the function call.","tags":["refactoring","extract"]},
    {"id":"pycharm-q9-real","type":"mcq","prompt":"What does 'Run with Coverage' show in PyCharm?",
     "choices":["Performance profiling data","Memory usage","Green/red highlighting in the editor showing which lines ARE covered by tests and which are NOT",
                "Security vulnerabilities"],
     "answerIndex":2,"explanation":"Coverage runs your tests and marks each line: green = executed by some test, red = never executed. You can visually see which code paths your tests miss — making it obvious where to add test cases.","tags":["testing","coverage"]},
    {"id":"pycharm-q10-real","type":"mcq","prompt":"What is a Run Configuration in PyCharm?",
     "choices":["A Python configuration file","A saved setup for running a script — script path, arguments, environment variables, working directory — so you can run it consistently with one click",
                "A virtualenv setting","A test framework"],
     "answerIndex":1,"explanation":"Run Configurations save how to run your program: which script, with what args, with which env vars. Multiple configs per project: 'Run dev server', 'Run tests', 'Run migration'. Never type long commands again.","tags":["run-config","productivity"]},
    {"id":"pycharm-q11-real","type":"mcq","prompt":"What does Shift+F6 do in PyCharm?",
     "choices":["Formats code","Renames the symbol under cursor and ALL its usages across the entire project simultaneously",
                "Runs tests","Opens settings"],
     "answerIndex":1,"explanation":"Rename refactoring. The most important refactoring. Cursor on a variable, function, class, or file name -> Shift+F6 -> type new name -> Enter. Every reference is updated. Safe, complete, instant.","tags":["refactoring","shortcuts"]},
    {"id":"pycharm-q12-real","type":"mcq","prompt":"What information does the PyCharm debugger's Variables panel show while paused at a breakpoint?",
     "choices":["Stack trace only","Current values of all variables in scope at the breakpoint — their names, types, and values",
                "Error messages","Code coverage"],
     "answerIndex":1,"explanation":"The Variables panel shows every variable in the current scope: local variables, parameters, self attributes. Click to expand objects and see their internals. No print() needed.","tags":["debugging","variables"]},
    {"id":"pycharm-q13-real","type":"mcq","prompt":"In PyCharm's Git integration, what does Ctrl+K open?",
     "choices":["Push dialog","Pull dialog","Commit dialog — shows changed files, diff preview, commit message field",
                "Branch manager"],
     "answerIndex":2,"explanation":"Ctrl+K opens the Commit panel. See all modified files, review diffs side-by-side, write your commit message, choose which files to include — all without leaving PyCharm.","tags":["git","shortcuts"]},
    {"id":"pycharm-q14-real","type":"mcq","prompt":"What does a red underline in PyCharm code mean?",
     "choices":["Code style suggestion","A warning about a potential issue","An error — the code will not run: undefined name, syntax error, wrong argument count",
                "A comment"],
     "answerIndex":2,"explanation":"Red = error. PyCharm's static analysis catches real bugs: undefined variables, wrong number of arguments, imported but missing modules. Fix these before running — they are always real problems.","tags":["inspections","errors"]},
    {"id":"pycharm-q15-real","type":"mcq","prompt":"How do you search for a method/class name across ALL files in the project?",
     "choices":["Ctrl+F (in current file only)","Ctrl+Shift+F (Find in Path — searches all files in project)",
                "Ctrl+N","Alt+F7"],
     "answerIndex":1,"explanation":"Ctrl+Shift+F opens Find in Path — searches all project files for text. Add file type filter (*.py) and case sensitivity. Alt+F7 finds usages of a specific symbol (smarter than text search).","tags":["search","navigation"]},
    {"id":"pycharm-q16-real","type":"mcq","prompt":"What is a conditional breakpoint and when would you use one?",
     "choices":["A breakpoint in an if statement","A breakpoint that only pauses execution when a specified condition is true — useful when a bug only occurs for certain values in a loop",
                "A breakpoint that logs to console","A disabled breakpoint"],
     "answerIndex":1,"explanation":"Right-click a breakpoint -> Edit, add condition e.g. i == 999. Without conditional breakpoints, you would press F9 999 times to reach the interesting iteration. Conditional breakpoints go straight to the relevant case.","tags":["debugging","breakpoints"]},
    {"id":"pycharm-q17-real","type":"mcq","prompt":"What does `pip freeze > requirements.txt` do and why is it important?",
     "choices":["Installs packages","Clears the virtual environment","Records the exact version of every installed package to a text file — allows exact environment recreation on any machine",
                "Updates all packages"],
     "answerIndex":2,"explanation":"requirements.txt lists exact versions: requests==2.31.0, Django==4.2.1. Anyone can run pip install -r requirements.txt and get the identical environment. Essential for reproducible deployments and team collaboration.","tags":["virtualenv","dependencies"]},
    {"id":"pycharm-q18-real","type":"mcq","prompt":"When PyCharm shows 'Annotate with Git Blame' in the editor gutter, what does it display?",
     "choices":["Test coverage","Memory usage per line","For each line: who last modified it, when, and in which commit",
                "Code complexity"],
     "answerIndex":2,"explanation":"Git Blame annotation shows the author, date, and commit hash next to each line. Invaluable for understanding why code was written a certain way, who to ask about it, and when a bug was introduced.","tags":["git","blame"]},
    {"id":"pycharm-q19-real","type":"mcq","prompt":"What is the IDE Features Trainer in PyCharm?",
     "choices":["A plugin for training ML models","A built-in interactive tutorial that teaches PyCharm features through hands-on lessons inside the IDE itself",
                "A performance profiler","A code review tool"],
     "answerIndex":1,"explanation":"Help -> IDE Features Trainer. Interactive lessons that walk you through shortcuts and features directly in the editor. Better than reading docs — you practice each feature immediately in context.","tags":["learning","shortcuts"]},
    {"id":"pycharm-q20-real","type":"mcq","prompt":"What is the key benefit of PyCharm's 'Extract Variable' refactoring (Ctrl+Alt+V)?",
     "choices":["Speeds up execution","Gives a complex expression a meaningful name as a variable — improving readability and replacing all occurrences of that expression simultaneously",
                "Moves code to another file","Adds type annotations"],
     "answerIndex":1,"explanation":"Select: len(items) * price_per_unit. Extract Variable. Name it: total_cost. Now every place that expression appeared is replaced with total_cost. Code becomes self-documenting.","tags":["refactoring","readability"]},
]

PYCHARM_NEW_FC = [
    {"id":"pycharm-fc1-real","front":"Top 5 PyCharm shortcuts to learn first","back":"1. Shift+Shift (search everywhere)  2. Alt+Enter (quick fix)  3. Ctrl+Click (go to definition)  4. Shift+F6 (rename all)  5. Ctrl+Alt+L (reformat code). Master these five, learn the rest gradually.","tags":["shortcuts"]},
    {"id":"pycharm-fc2-real","front":"Debugger: F7 vs F8 vs F9","back":"F8=Step Over (run line, don't enter calls)  F7=Step Into (enter the function being called)  Shift+F8=Step Out (finish current function, return to caller)  F9=Resume (run to next breakpoint)","tags":["debugging"]},
    {"id":"pycharm-fc3-real","front":"Alt+Enter — when to use it","back":"On ANY red/yellow underline. Common fixes: add missing import, create missing method/variable, change to compatible type, suppress warning, split long string. The single most important shortcut for fixing problems fast.","tags":["quick-fixes","shortcuts"]},
    {"id":"pycharm-fc4-real","front":"Virtual environment best practices","back":"One venv per project. Never use system Python for projects. Always pip freeze > requirements.txt after installing. Commit requirements.txt to git (not the venv/ folder itself — add venv/ to .gitignore).","tags":["virtualenv","environments"]},
    {"id":"pycharm-fc5-real","front":"Rename refactoring vs Find+Replace","back":"Shift+F6 (Rename): understands code structure, renames only the correct symbol across all files. Find+Replace: text-based, may rename unrelated things with same name. Always use Rename for code symbols.","tags":["refactoring"]},
    {"id":"pycharm-fc6-real","front":"Run Configuration use cases","back":"Save: script path, CLI args, env vars (DB_URL=..., DEBUG=True), working directory. Multiple configs: 'Run dev', 'Run tests', 'Run migrations'. Eliminates typing long commands. Share via .run/ in git.","tags":["run-config","productivity"]},
    {"id":"pycharm-fc7-real","front":"Code coverage workflow","back":"Run with Coverage -> editor shows green (covered) and red (not covered) lines. Red lines = your tests never execute that code path. Add test cases targeting red paths until all critical code is green.","tags":["testing","coverage"]},
    {"id":"pycharm-fc8-real","front":"Evaluate Expression during debugging","back":"Alt+F8 while paused at breakpoint. Type any Python expression: len(items), type(x), my_obj.attr. Evaluated in CURRENT execution context. Test hypotheses about bugs without adding print statements or restarting.","tags":["debugging","evaluate"]},
]

# Replace ALL questions and flashcards (existing ones are garbage stubs)
d_py['guide'] = PYCHARM_GUIDE
d_py['questions'] = PYCHARM_NEW_Q
d_py['flashcards'] = PYCHARM_NEW_FC

with open(p_py, 'w') as f:
    json.dump(d_py, f, indent=2, ensure_ascii=False)
print(f"pycharm.json done: guide={len(PYCHARM_GUIDE)} q={len(d_py['questions'])} fc={len(d_py['flashcards'])}")

