import json
from pathlib import Path

p = Path('/Users/eptr6dj/IdeaProjects/master-cs/cs-mastery/src/content/topics/cloud-devops/aws-mastery.json')
d = json.loads(p.read_text())

GUIDE = "\n".join([
    "# AWS Mastery — Lambda, API Gateway, CloudFormation, CDK",
    "",
    "## Beyond the Basics — What This Course Covers",
    "",
    "AWS Practitioner gives you the vocabulary. AWS Mastery is about building real systems.",
    "This topic focuses on the serverless-first, infrastructure-as-code approach that",
    "modern AWS engineers use daily.",
    "",
    "```",
    "The serverless stack you will master:",
    "",
    "  Client Browser/Mobile",
    "        |",
    "        | HTTPS",
    "        v",
    "  API Gateway   --- routes requests by path/method",
    "        |",
    "        v",
    "  Lambda Functions  --- stateless business logic",
    "        |",
    "        v",
    "  DynamoDB / RDS / S3 / ElastiCache  --- data tier",
    "",
    "All of this defined in code (CDK/SAM/CloudFormation)",
    "Deployed and updated via CI/CD pipeline",
    "```",
    "",
    "---",
    "",
    "## Lambda Deep Dive — Memory, Concurrency, Invocation Types",
    "",
    "```",
    "MEMORY AND CPU:",
    "  Lambda: 128MB - 10,240MB memory",
    "  CPU is proportional to memory (no separate CPU setting)",
    "  128MB  = 0.125 vCPU",
    "  1024MB = 1 vCPU",
    "  10GB   = ~6 vCPU",
    "",
    "  Key insight: increasing memory often reduces duration enough to be cost-neutral",
    "  or cheaper. Profile your function.",
    "",
    "  Cost = (duration in ms) x (memory in GB) x price_per_GB_second",
    "  512MB for 100ms vs 1024MB for 50ms = same cost, twice the speed",
    "",
    "INVOCATION TYPES:",
    "  Synchronous:  caller waits for response",
    "    API Gateway -> Lambda -> caller gets response",
    "    If Lambda errors: caller immediately gets error",
    "",
    "  Asynchronous: caller doesn't wait",
    "    S3 event, SNS, EventBridge -> Lambda",
    "    Lambda retries 2x on failure",
    "    Configure DLQ for failed events",
    "",
    "  Stream/Poll:  Lambda polls the source",
    "    SQS, Kinesis, DynamoDB Streams -> Lambda",
    "    Lambda manages polling, you manage batch size and concurrency",
    "",
    "CONCURRENCY TYPES:",
    "  Unreserved concurrency:  shares account limit (default 1000)",
    "  Reserved concurrency:    guarantees N for this function, caps it at N",
    "  Provisioned concurrency: pre-warms containers (eliminates cold start)",
    "",
    "LAMBDA EXECUTION CONTEXT REUSE:",
    "  INIT code (outside handler):  runs once per cold start",
    "    db_client = boto3.client('dynamodb')     # runs once",
    "    secret = get_secret()                     # runs once",
    "",
    "  HANDLER code:  runs on every invocation",
    "    def handler(event, context):",
    "        result = db_client.get_item(...)     # reuses connection",
    "        return result",
    "```",
    "",
    "---",
    "",
    "## API Gateway — Types and Configuration",
    "",
    "API Gateway is the front door for your Lambda-based APIs.",
    "Two main flavours:",
    "",
    "```",
    "REST API (API Gateway v1):",
    "  Full-featured: request/response transformation, API keys, usage plans,",
    "  WAF integration, per-stage deployments, stage variables",
    "  More expensive, more configuration",
    "  Use when: you need API keys for third-party access, custom authorisers,",
    "  request validation, response mapping",
    "",
    "HTTP API (API Gateway v2):",
    "  Simpler, 70% cheaper than REST API",
    "  Lower latency",
    "  Supports: JWT authorisers, CORS, Lambda proxy",
    "  Missing: API keys, usage plans, request/response transformation",
    "  Use when: simple Lambda proxy, internal microservices, JWT auth",
    "",
    "REQUEST FLOW:",
    "  Browser sends: POST /users",
    "        |",
    "        v",
    "  API Gateway receives request",
    "  Validates (optional: request schema, API key)",
    "  Applies authoriser (optional: Lambda authoriser, JWT)",
    "        |",
    "        v",
    "  Lambda invoked with event:",
    "  {",
    "    httpMethod: 'POST',",
    "    path: '/users',",
    "    headers: {...},",
    "    body: '{\"name\": \"Alice\"}'",
    "  }",
    "        |",
    "        v",
    "  Lambda returns:",
    "  {",
    "    statusCode: 201,",
    "    headers: {'Content-Type': 'application/json'},",
    "    body: '{\"userId\": \"abc123\"}'",
    "  }",
    "        |",
    "        v",
    "  API Gateway forwards response to browser",
    "",
    "AUTHORISATION:",
    "  Lambda Authoriser:  custom Bearer token validation lambda",
    "                      returns IAM policy allowing/denying access",
    "  JWT Authoriser:     API Gateway validates JWT against JWKS endpoint",
    "                      (Cognito, Auth0, custom)",
    "  IAM Authoriser:     AWS Signature V4 — for service-to-service calls",
    "  Cognito Authoriser: built-in Cognito User Pool integration",
    "```",
    "",
    "---",
    "",
    "## CloudFormation — Infrastructure as Code",
    "",
    "CloudFormation lets you define ALL your AWS infrastructure in a YAML/JSON template.",
    "The same template, deployed twice, creates identical environments every time.",
    "",
    "```yaml",
    "# cloudformation-template.yaml",
    "AWSTemplateFormatVersion: '2010-09-09'",
    "Description: Simple web app infrastructure",
    "",
    "Parameters:",
    "  Environment:",
    "    Type: String",
    "    AllowedValues: [dev, staging, production]",
    "    Default: dev",
    "",
    "Resources:",
    "  # DynamoDB Table",
    "  UsersTable:",
    "    Type: AWS::DynamoDB::Table",
    "    Properties:",
    "      TableName: !Sub 'users-${Environment}'",
    "      BillingMode: PAY_PER_REQUEST",
    "      AttributeDefinitions:",
    "        - AttributeName: userId",
    "          AttributeType: S",
    "      KeySchema:",
    "        - AttributeName: userId",
    "          KeyType: HASH",
    "",
    "  # Lambda Function",
    "  GetUserFunction:",
    "    Type: AWS::Lambda::Function",
    "    Properties:",
    "      FunctionName: !Sub 'get-user-${Environment}'",
    "      Runtime: python3.12",
    "      Handler: index.handler",
    "      MemorySize: 512",
    "      Timeout: 10",
    "      Role: !GetAtt LambdaExecutionRole.Arn",
    "      Environment:",
    "        Variables:",
    "          TABLE_NAME: !Ref UsersTable",
    "",
    "  # IAM Role for Lambda",
    "  LambdaExecutionRole:",
    "    Type: AWS::IAM::Role",
    "    Properties:",
    "      AssumeRolePolicyDocument:",
    "        Version: '2012-10-17'",
    "        Statement:",
    "          - Effect: Allow",
    "            Principal: {Service: lambda.amazonaws.com}",
    "            Action: sts:AssumeRole",
    "      ManagedPolicyArns:",
    "        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    "      Policies:",
    "        - PolicyName: DynamoDBAccess",
    "          PolicyDocument:",
    "            Statement:",
    "              - Effect: Allow",
    "                Action: [dynamodb:GetItem, dynamodb:PutItem]",
    "                Resource: !GetAtt UsersTable.Arn",
    "",
    "Outputs:",
    "  TableName:",
    "    Value: !Ref UsersTable",
    "    Export:",
    "      Name: !Sub '${Environment}-UsersTableName'",
    "```",
    "",
    "```bash",
    "# Deploy:",
    "aws cloudformation deploy \\",
    "  --template-file template.yaml \\",
    "  --stack-name my-app-production \\",
    "  --parameter-overrides Environment=production \\",
    "  --capabilities CAPABILITY_IAM",
    "",
    "# Update (same command — CF detects changes, updates only what changed):",
    "aws cloudformation deploy ...",
    "",
    "# Delete everything:",
    "aws cloudformation delete-stack --stack-name my-app-production",
    "```",
    "",
    "---",
    "",
    "## AWS CDK — CloudFormation with Real Code",
    "",
    "CDK (Cloud Development Kit) lets you define infrastructure in TypeScript, Python,",
    "Java, or Go. It compiles to CloudFormation under the hood.",
    "",
    "**Why CDK over raw CloudFormation?**",
    "```",
    "CloudFormation YAML:                    CDK (TypeScript):",
    "  500 lines of YAML                       100 lines of TypeScript",
    "  No loops, no conditions (limited)       Full programming language features",
    "  No type checking                        TypeScript type safety",
    "  No IDE completion                       Full IDE autocompletion",
    "  Copy-paste for repetition               Loops, functions, abstractions",
    "  Hard to understand structure            Code is self-documenting",
    "```",
    "",
    "```typescript",
    "// AWS CDK TypeScript example",
    "import * as cdk from 'aws-cdk-lib';",
    "import * as lambda from 'aws-cdk-lib/aws-lambda';",
    "import * as apigateway from 'aws-cdk-lib/aws-apigateway';",
    "import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';",
    "",
    "export class MyAppStack extends cdk.Stack {",
    "  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {",
    "    super(scope, id, props);",
    "",
    "    // DynamoDB Table",
    "    const table = new dynamodb.Table(this, 'UsersTable', {",
    "      partitionKey: { name: 'userId', type: dynamodb.AttributeType.STRING },",
    "      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,",
    "      removalPolicy: cdk.RemovalPolicy.RETAIN,  // don't delete on stack delete",
    "    });",
    "",
    "    // Lambda Function",
    "    const getUser = new lambda.Function(this, 'GetUser', {",
    "      runtime: lambda.Runtime.PYTHON_3_12,",
    "      handler: 'index.handler',",
    "      code: lambda.Code.fromAsset('src/handlers/get-user'),",
    "      memorySize: 512,",
    "      timeout: cdk.Duration.seconds(10),",
    "      environment: {",
    "        TABLE_NAME: table.tableName,",
    "      },",
    "    });",
    "",
    "    // Grant Lambda access to table (CDK generates least-privilege IAM policy)",
    "    table.grantReadData(getUser);",
    "",
    "    // API Gateway",
    "    const api = new apigateway.RestApi(this, 'UsersApi');",
    "    api.root",
    "      .addResource('users')",
    "      .addResource('{userId}')",
    "      .addMethod('GET', new apigateway.LambdaIntegration(getUser));",
    "  }",
    "}",
    "```",
    "",
    "```bash",
    "cdk synth   # compile to CloudFormation YAML (review it)",
    "cdk diff    # show what would change if deployed",
    "cdk deploy  # deploy to AWS",
    "cdk destroy # tear down all resources in stack",
    "```",
    "",
    "---",
    "",
    "## Design Exercise: Serverless URL Shortener",
    "",
    "Design a URL shortener (like bit.ly) using serverless AWS services.",
    "This is a classic AWS design interview question.",
    "",
    "```",
    "Requirements:",
    "  POST /shorten  body: {longUrl: 'https://...'} -> returns {shortCode: 'abc123'}",
    "  GET  /{code}   -> 301 redirect to original URL",
    "",
    "Architecture:",
    "",
    "  Client",
    "    |",
    "    v",
    "  API Gateway (HTTP API)",
    "    |",
    "    +--- POST /shorten ---> Lambda: ShortenUrl",
    "    |                           |",
    "    |                       DynamoDB: put item",
    "    |                           {shortCode: 'abc123', longUrl: '...', ttl: ...}",
    "    |                           Return {shortCode: 'abc123'}",
    "    |",
    "    +--- GET /{code} ----> Lambda: RedirectUrl",
    "                               |",
    "                           DynamoDB: get item by shortCode",
    "                           Return 301 Location: longUrl",
    "",
    "Design decisions:",
    "  Short code generation:",
    "    Option A: hash(longUrl) -> take first 6 chars of MD5",
    "    Option B: base62(auto-increment counter in DynamoDB atomic counter)",
    "    Option C: random 6-char alphanumeric, check for collisions",
    "",
    "  DynamoDB schema:",
    "    PK: shortCode (partition key)",
    "    Attributes: longUrl, createdAt, userId, clickCount",
    "    TTL attribute: auto-expire codes after 1 year",
    "",
    "  CDK stack includes:",
    "    DynamoDB table (PAY_PER_REQUEST, TTL enabled)",
    "    2 Lambda functions (ShortenUrl, RedirectUrl)",
    "    API Gateway HTTP API (2 routes)",
    "    Lambda execution roles (least privilege DynamoDB access)",
    "    CloudWatch alarms (error rate > 1%)",
    "```",
    "",
    "---",
    "",
    "## X-Ray — Distributed Tracing",
    "",
    "```",
    "X-Ray traces requests as they flow through your distributed system.",
    "Without X-Ray: 'My API is slow, but which Lambda / which DynamoDB call?'",
    "With X-Ray: see a timeline of every service hop with durations.",
    "",
    "  API Gateway (5ms)",
    "    |",
    "    v",
    "  Lambda: GetUser (250ms total)",
    "    |",
    "    +-- DynamoDB GetItem (45ms)  <- this is slow!",
    "    +-- ElastiCache Get (2ms)",
    "    +-- Processing (200ms)",
    "",
    "Enable in Lambda:",
    "  In CDK:  tracing: lambda.Tracing.ACTIVE",
    "  In SAM:  Tracing: Active",
    "",
    "Adds subsegments automatically for AWS SDK calls.",
    "Add custom subsegments for expensive business logic.",
    "View traces in AWS Console -> X-Ray -> Service Map.",
    "```",
    "",
    "---",
    "",
    "## Secrets Manager and Parameter Store",
    "",
    "```",
    "Never hardcode secrets in Lambda environment variables or code.",
    "",
    "AWS SECRETS MANAGER:",
    "  Store: DB passwords, API keys, certificates",
    "  Automatic rotation: rotates RDS passwords automatically",
    "  Access: Lambda fetches secret at runtime",
    "  Cost: $0.40/secret/month + API calls",
    "",
    "  # Lambda (Python) example:",
    "  import boto3, json",
    "  client = boto3.client('secretsmanager')",
    "  secret = json.loads(client.get_secret_value(",
    "      SecretId='prod/myapp/db-password',",
    "  )['SecretString'])",
    "  DB_PASSWORD = secret['password']",
    "",
    "  Cache secrets in Lambda global scope (fetched once per cold start).",
    "",
    "AWS SYSTEMS MANAGER PARAMETER STORE:",
    "  Store: non-sensitive config that needs versioning",
    "  SecureString tier: encrypted with KMS",
    "  Free for standard parameters",
    "  Use for: feature flags, config values, environment-specific settings",
    "",
    "WHEN TO USE WHICH:",
    "  Secrets Manager: actual secrets (passwords, API keys) + auto-rotation",
    "  Parameter Store: config values, feature flags, non-secret strings",
    "```",
    "",
    "---",
    "",
    "## VPC Lambda — When and Why",
    "",
    "```",
    "By default, Lambda runs OUTSIDE your VPC and cannot access:",
    "  - RDS in private subnet",
    "  - ElastiCache in private subnet",
    "  - Other private resources",
    "",
    "VPC Lambda: attach Lambda to your VPC subnets",
    "  Lambda can now reach private resources inside the VPC",
    "  Lambda gets an ENI (Elastic Network Interface) in your subnet",
    "",
    "TRADE-OFF:",
    "  VPC Lambda: can reach RDS, ElastiCache",
    "  Non-VPC Lambda: faster cold start, can reach internet directly",
    "",
    "VPC Lambda cold starts: used to be much slower (ENI creation)",
    "AWS fixed this in 2019 — VPC Lambda cold starts now similar to non-VPC",
    "",
    "CONFIGURATION:",
    "  Lambda -> Configuration -> VPC",
    "  Select VPC, private subnets, security group",
    "  Security group: must allow outbound to RDS security group on port 5432",
    "  RDS security group: must ALLOW inbound from Lambda security group",
    "",
    "CDK example:",
    "  const fn = new lambda.Function(this, 'MyFn', {",
    "    vpc: myVpc,",
    "    vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },",
    "    securityGroups: [lambdaSg],",
    "    ... other props",
    "  })",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "AWS MASTERY",
    "|",
    "+-- LAMBDA ADVANCED",
    "|   +-- Memory = CPU (proportional)",
    "|   +-- Sync / Async / Stream invocation types",
    "|   +-- Reserved vs Provisioned concurrency",
    "|   +-- Execution context reuse (global scope)",
    "|   +-- VPC Lambda (private resource access)",
    "|",
    "+-- API GATEWAY",
    "|   +-- REST API (full features, expensive)",
    "|   +-- HTTP API (simpler, 70% cheaper)",
    "|   +-- Authorisation: JWT, Lambda, IAM, Cognito",
    "|   +-- Request/response flow and event structure",
    "|",
    "+-- CLOUDFORMATION",
    "|   +-- YAML/JSON template declares resources",
    "|   +-- Parameters, Outputs, !Ref, !GetAtt",
    "|   +-- Stacks: create / update / delete atomically",
    "|",
    "+-- CDK",
    "|   +-- TypeScript/Python/Java -> CloudFormation",
    "|   +-- Type safety, IDE support, real code constructs",
    "|   +-- cdk synth / diff / deploy / destroy",
    "|   +-- grantReadData = least-privilege auto-IAM",
    "|",
    "+-- OBSERVABILITY",
    "|   +-- X-Ray (distributed tracing)",
    "|   +-- CloudWatch (metrics, logs, alarms)",
    "|",
    "+-- SECRETS",
    "    +-- Secrets Manager (passwords + rotation)",
    "    +-- Parameter Store (config + feature flags)",
    "```",
    "",
    "---",
    "",
    "## How AWS Mastery Connects to Other Topics",
    "",
    "- **Serverless Patterns**: This topic adds depth to Lambda + API Gateway coverage.",
    "  CDK/CloudFormation is how you actually deploy those patterns.",
    "- **CI/CD**: CDK deploy wired into your CI/CD pipeline = GitOps for AWS infrastructure.",
    "- **Security**: IAM roles for Lambda, Secrets Manager, VPC isolation — all security fundamentals.",
    "- **Docker/K8s**: CDK also deploys ECS Fargate and EKS — the same IaC approach applies.",
    "",
    "---",
    "",
    "## References and Further Learning",
    "",
    "### Videos (Watch These!)",
    "- **AWS CDK Course for Beginners** by freeCodeCamp:",
    "  https://www.youtube.com/watch?v=T-H4nJQyMig",
    "  - 3 hours. Build real infrastructure with CDK TypeScript.",
    "- **API Gateway + Lambda Deep Dive** by Be A Better Dev:",
    "  https://www.youtube.com/watch?v=M91vXdjve7A",
    "  - REST vs HTTP API comparison, authorisers, performance.",
    "",
    "### Free Books and Articles",
    "- **AWS CDK Official Workshop**: https://cdkworkshop.com/",
    "  - Interactive CDK tutorial. Build a complete serverless app step by step.",
    "- **The CDK Book** (free chapter): https://thecdkbook.com/",
    "- **AWS Well-Architected Serverless Lens**: https://docs.aws.amazon.com/wellarchitected/latest/serverless-applications-lens/",
    "",
    "### Practice",
    "- **Build a Serverless URL Shortener** — implement the design exercise in this guide.",
    "- **CDK Patterns**: https://cdkpatterns.com/ — ready-made CDK patterns for common architectures.",
])

NEW_Q = [
    {"id":"aws-mastery-q1","type":"mcq","prompt":"In Lambda, what is the relationship between memory and CPU?",
     "choices":["CPU and memory are configured independently","There is no CPU — Lambda is memory only","CPU scales proportionally with memory — more memory = more vCPU. 128MB ≈ 0.125 vCPU, 1024MB ≈ 1 vCPU",
                "CPU is fixed at 1 vCPU regardless of memory"],
     "answerIndex":2,"explanation":"Lambda has no separate CPU setting. Allocate more memory and you get proportionally more CPU. Often doubling memory reduces duration enough that cost stays the same or decreases while performance doubles.","tags":["lambda","performance","memory"]},
    {"id":"aws-mastery-q2","type":"mcq","prompt":"What is the difference between synchronous and asynchronous Lambda invocation?",
     "choices":["No difference in practice","Sync: caller waits for response, gets error immediately on failure. Async: caller returns immediately, Lambda retries 2x on failure, DLQ captures final failures",
                "Async is always faster","Sync invocations don't support retry"],
     "answerIndex":1,"explanation":"API Gateway -> Lambda: synchronous (caller waits). S3/SNS/EventBridge -> Lambda: asynchronous (event source doesn't wait). Async adds 2 automatic retries and DLQ support. Choose based on whether the caller needs a real-time response.","tags":["lambda","invocation-types"]},
    {"id":"aws-mastery-q3","type":"mcq","prompt":"What is the key advantage of AWS CDK over raw CloudFormation YAML?",
     "choices":["CDK is faster to deploy","CDK uses a real programming language (TypeScript/Python/Java) enabling loops, functions, type safety, and IDE autocompletion — making complex infra manageable",
                "CDK doesn't use CloudFormation","CDK is always cheaper"],
     "answerIndex":1,"explanation":"CDK compiles to CloudFormation under the hood but lets you write real code. 500-line CloudFormation YAML becomes 100-line TypeScript. Use loops to create 5 identical resources. Use functions for reusable patterns. IDE catches type errors before deployment.","tags":["cdk","cloudformation","iac"]},
    {"id":"aws-mastery-q4","type":"mcq","prompt":"What does `table.grantReadData(lambdaFn)` do in CDK?",
     "choices":["Copies table data to Lambda","Creates a CloudWatch alarm","Automatically generates an IAM policy granting the Lambda role minimum DynamoDB read permissions on that specific table",
                "Configures DynamoDB Streams"],
     "answerIndex":2,"explanation":"CDK's grant methods implement least privilege automatically. grantReadData creates a policy allowing only GetItem, Query, Scan on that table. No need to write IAM JSON by hand. CDK knows what permissions each action requires.","tags":["cdk","iam","least-privilege"]},
    {"id":"aws-mastery-q5","type":"mcq","prompt":"What is the difference between REST API and HTTP API in API Gateway?",
     "choices":["REST API is HTTP, HTTP API is WebSocket","REST API: full features (API keys, usage plans, transformations, WAF). HTTP API: simpler, 70% cheaper, JWT auth. Use HTTP API unless you need REST API features.",
                "They are identical","REST API only works with Lambda"],
     "answerIndex":1,"explanation":"HTTP API launched in 2019: lower latency, 70% cheaper, supports JWT authorisers and Lambda proxy. Missing: API keys, usage plans, request/response transformation, per-method throttling. Use HTTP API as default for new projects.","tags":["api-gateway","rest-api","http-api"]},
    {"id":"aws-mastery-q6","type":"mcq","prompt":"Why would you attach a Lambda function to a VPC?",
     "choices":["VPC Lambda always runs faster","To access private resources in the VPC — RDS databases, ElastiCache caches, internal services — that have no public internet endpoint",
                "VPC Lambda is required for all production functions","To reduce Lambda costs"],
     "answerIndex":1,"explanation":"Non-VPC Lambda runs outside your VPC. It can hit public internet but not your private RDS or ElastiCache. VPC Lambda gets a network interface in your private subnet, enabling access to private resources. Cold starts are now similar to non-VPC.","tags":["lambda","vpc","networking"]},
    {"id":"aws-mastery-q7","type":"mcq","prompt":"What does `cdk diff` do?",
     "choices":["Shows git diff for CDK files","Shows what AWS resource changes WOULD be made if you ran cdk deploy — without actually deploying",
                "Compares two CDK stacks","Rolls back the last deployment"],
     "answerIndex":1,"explanation":"cdk diff is like git diff but for infrastructure. It compares your current CDK code against what is deployed and shows: resources to add, modify, or delete. Always run cdk diff before cdk deploy in production.","tags":["cdk","safety"]},
    {"id":"aws-mastery-q8","type":"mcq","prompt":"What is AWS X-Ray used for?",
     "choices":["Security vulnerability scanning","Distributed tracing — shows the request journey across Lambda, DynamoDB, API Gateway with timing for each segment to identify bottlenecks",
                "Monitoring billing","Log aggregation"],
     "answerIndex":1,"explanation":"X-Ray traces requests end-to-end. Instead of 'my API is slow', you see: API Gateway 5ms -> Lambda 250ms (DynamoDB 45ms + processing 200ms). Identify the slow subsegment. Enable with Tracing: Active in Lambda config.","tags":["x-ray","observability","tracing"]},
    {"id":"aws-mastery-q9","type":"mcq","prompt":"When should you use Secrets Manager over Parameter Store?",
     "choices":["Secrets Manager is always better","Secrets Manager for sensitive secrets that need automatic rotation (RDS passwords, API keys). Parameter Store for non-sensitive config, feature flags, app settings (free, simpler).",
                "Parameter Store for all secrets","They serve identical purposes"],
     "answerIndex":1,"explanation":"Secrets Manager: $0.40/secret/month, supports automatic rotation of RDS passwords. Parameter Store: free for standard tier, simpler, no rotation. Use Secrets Manager for passwords/tokens that rotate. Parameter Store for DB hostnames, feature flags, config.","tags":["secrets-manager","parameter-store","security"]},
    {"id":"aws-mastery-q10","type":"mcq","prompt":"What does CloudFormation's !Ref intrinsic function do?",
     "choices":["Creates a reference to an external API","Returns the physical ID or value of a resource — used to pass resource identifiers (table name, ARN) to other resources in the same template",
                "Imports a module","Makes an HTTP request"],
     "answerIndex":1,"explanation":"!Ref UsersTable returns the DynamoDB table name. !GetAtt UsersTable.Arn returns the ARN. These are CF intrinsic functions for wiring resources together without hardcoding. Dynamic references that resolve at deploy time.","tags":["cloudformation","intrinsic-functions"]},
    {"id":"aws-mastery-q11","type":"mcq","prompt":"In a serverless URL shortener, where should you store the short code to long URL mapping?",
     "choices":["In Lambda global variables (in-memory)","In S3 as JSON files","In DynamoDB with shortCode as partition key — fast key-value lookups, scales to billions of records, pay per request",
                "In RDS with a URLs table"],
     "answerIndex":2,"explanation":"URL shortener: simple key-value lookup (shortCode -> longUrl). DynamoDB PK=shortCode. GetItem = single-digit ms at any scale. No JOINs needed. Enable TTL to auto-expire old codes. No EC2/RDS to manage. Perfect DynamoDB use case.","tags":["dynamodb","architecture","design"]},
    {"id":"aws-mastery-q12","type":"mcq","prompt":"What is the purpose of the Lambda execution context reuse principle?",
     "choices":["Reduces Lambda costs by sharing containers","Allows expensive initialisation (DB connections, SDK clients, secret fetching) to run once per cold start and be reused across many warm invocations",
                "Enables Lambda to share state with other functions","Reduces memory usage"],
     "answerIndex":1,"explanation":"Code outside the handler function runs once on cold start. Code inside runs per invocation. DB connection outside = one connection per container, reused. DB connection inside = new connection every request (very slow). Global scope is for expensive-to-create, safe-to-reuse objects.","tags":["lambda","performance","context-reuse"]},
    {"id":"aws-mastery-q13","type":"mcq","prompt":"What are CloudFormation Outputs used for?",
     "choices":["Print debug information","Export resource values (ARNs, names, URLs) from a stack for use by other stacks or to display after deployment",
                "Define stack parameters","Rollback configuration"],
     "answerIndex":1,"explanation":"Outputs export values from a stack. Other stacks import them with Fn::ImportValue. Example: network stack exports VPC ID and subnet IDs. Application stack imports them. Enables modular multi-stack architectures without duplicating resource definitions.","tags":["cloudformation","outputs","cross-stack"]},
    {"id":"aws-mastery-q14","type":"mcq","prompt":"In API Gateway, what is a Lambda Authoriser?",
     "choices":["A Lambda function that handles all requests","A Lambda function that validates bearer tokens or headers and returns an IAM policy allowing or denying the request — enables custom auth logic",
                "An IAM role for API Gateway","A CloudWatch alarm for API quotas"],
     "answerIndex":1,"explanation":"Lambda Authoriser: API Gateway calls your auth Lambda with the token. Lambda validates it (verify JWT signature, call a user database, check an internal auth service) and returns Allow or Deny. Cached for performance. Use for custom auth not covered by built-in JWT/Cognito.","tags":["api-gateway","authorisation","lambda"]},
    {"id":"aws-mastery-q15","type":"mcq","prompt":"What does `cdk synth` produce?",
     "choices":["Python bytecode","A CloudFormation template (YAML) from your CDK code — review it before deploying to understand exactly what AWS resources will be created",
                "A Docker image","A test report"],
     "answerIndex":1,"explanation":"cdk synth compiles your CDK TypeScript/Python to a CloudFormation template. This is what gets deployed. Running synth and reviewing the output is how you verify CDK is generating the correct resources and IAM policies.","tags":["cdk","cloudformation"]},
    {"id":"aws-mastery-q16","type":"mcq","prompt":"What is Lambda Reserved Concurrency?",
     "choices":["Pre-warmed containers","A concurrency setting that both GUARANTEES a minimum and CAPS a maximum — the function cannot exceed this concurrency, protecting downstream resources",
                "Maximum concurrent Lambda requests across account","Free Lambda tier allocation"],
     "answerIndex":1,"explanation":"Reserved Concurrency = N means: (1) this function always has N concurrency available (not stolen by other functions), AND (2) this function cannot exceed N. Cap your payment Lambda at 20 to prevent overwhelming the payment API with 20+ simultaneous requests.","tags":["lambda","concurrency","reserved"]},
    {"id":"aws-mastery-q17","type":"mcq","prompt":"In CloudFormation, what happens when a stack update fails?",
     "choices":["Partial update remains in place","CloudFormation rolls back ALL changes in the update — restores every resource to its previous state automatically",
                "Stack is deleted","You must manually roll back"],
     "answerIndex":1,"explanation":"CloudFormation updates are transactional. If any resource update fails, CF rolls back all changes in that update. Your infrastructure returns to the last known-good state. This is why CF is safer than running individual API calls that can leave infra in inconsistent states.","tags":["cloudformation","rollback","reliability"]},
    {"id":"aws-mastery-q18","type":"mcq","prompt":"What does `CAPABILITY_IAM` flag mean in CloudFormation deploy commands?",
     "choices":["Enables IAM user creation only","Acknowledges that the template creates or modifies IAM resources (roles, policies) — required as a safety confirmation to prevent accidental privilege escalation",
                "Grants admin IAM access","Required for all deployments"],
     "answerIndex":1,"explanation":"CloudFormation requires explicit acknowledgement when creating IAM resources because misconfigured IAM can grant excessive permissions. --capabilities CAPABILITY_IAM tells CF: 'Yes, I understand this template creates IAM resources, proceed.'","tags":["cloudformation","iam","safety"]},
    {"id":"aws-mastery-q19","type":"mcq","prompt":"What is the purpose of DynamoDB TTL (Time to Live)?",
     "choices":["TTL controls DynamoDB performance","TTL automatically deletes items after a specified timestamp — no cost for deletion, no Lambda needed, great for session data, caches, expired short URLs",
                "TTL limits DynamoDB table size","TTL is for DynamoDB Global Tables"],
     "answerIndex":1,"explanation":"Enable TTL on a timestamp attribute. Items with that attribute set to a past Unix timestamp are automatically deleted within 48 hours. No cost for TTL deletions. Perfect for: session tokens, short URL expiration, cache invalidation, event logs.","tags":["dynamodb","ttl","data-management"]},
    {"id":"aws-mastery-q20","type":"mcq","prompt":"What is a CloudFormation Stack?",
     "choices":["A list of AWS regions","A collection of AWS resources managed as a unit — created, updated, and deleted together. One template = one stack.",
                "A Lambda deployment package","An S3 bucket for CloudFormation templates"],
     "answerIndex":1,"explanation":"A stack is a collection of resources that are created and managed together. Deploying a template creates a stack. Update the template = update the stack (CF handles change detection). Delete the stack = deletes all resources in it (including data — be careful!).","tags":["cloudformation","stacks"]},
]

NEW_FC = [
    {"id":"aws-mastery-fc1","front":"CDK workflow commands","back":"cdk synth (compile to CF YAML, review) -> cdk diff (see what changes) -> cdk deploy (apply changes). Always diff before deploy in prod. cdk destroy = delete entire stack (including databases if not RETAIN).","tags":["cdk","workflow"]},
    {"id":"aws-mastery-fc2","front":"Lambda cold start mitigation order","back":"1. Smaller package (deps in Layers)  2. Python/Node over Java  3. Provisioned Concurrency (pre-warm, costs $)  4. Ping with EventBridge (free)  5. GraalVM native for Java  6. Use HTTP API (lower overhead than REST API)","tags":["lambda","cold-start"]},
    {"id":"aws-mastery-fc3","front":"API Gateway: REST API vs HTTP API","back":"HTTP API: default choice. 70% cheaper, lower latency, JWT auth, CORS, Lambda proxy. REST API: only when you need API keys/usage plans, per-method auth, request/response transformation, WAF at API level.","tags":["api-gateway","rest-api","http-api"]},
    {"id":"aws-mastery-fc4","front":"CloudFormation atomic rollback","back":"Stack update fails -> CF rolls back ALL changes in that update atomically. Infrastructure returns to last known-good state. This is why IaC > manual API calls for production.","tags":["cloudformation","reliability"]},
    {"id":"aws-mastery-fc5","front":"Serverless URL shortener design","back":"DynamoDB (PK=shortCode, TTL=expiry). HTTP API + 2 Lambda functions (shorten, redirect). ShortenUrl: generate base62 code, write to DynamoDB, return short URL. RedirectUrl: GetItem by code, return 301 Location header.","tags":["design","dynamodb","lambda"]},
    {"id":"aws-mastery-fc6","front":"Lambda global scope rule","back":"OUTSIDE handler: initialise once (DB client, secrets, large config). Reused across warm invocations = good. INSIDE handler: per-request state only (user-specific data, request context). NEVER store user data globally.","tags":["lambda","context-reuse"]},
    {"id":"aws-mastery-fc7","front":"Secrets Manager vs Parameter Store","back":"Secrets Manager: passwords + API keys + auto-rotation support. $0.40/secret/month. Parameter Store: config + feature flags. Free (standard tier). Use SM for actual secrets, SSM PS for config. Both much better than env vars in Lambda.","tags":["secrets","security"]},
    {"id":"aws-mastery-fc8","front":"X-Ray tracing — enable and use","back":"CDK: tracing: lambda.Tracing.ACTIVE. SAM: Tracing: Active. Automatically traces AWS SDK calls. Add custom segments with xray.begin_segment(). View in Console -> X-Ray -> Traces or Service Map to find slow subsegments.","tags":["x-ray","observability"]},
]

d['guide'] = GUIDE
d['questions'] = NEW_Q
d['flashcards'] = NEW_FC

with open(p, 'w') as f:
    json.dump(d, f, indent=2, ensure_ascii=False)
print(f"aws-mastery.json done: guide={len(GUIDE)} q={len(d['questions'])} fc={len(d['flashcards'])}")

