import json
from pathlib import Path

p = Path('/Users/eptr6dj/IdeaProjects/master-cs/cs-mastery/src/content/topics/cloud-devops/linux-essentials.json')
d = json.loads(p.read_text())

NEW_GUIDE = (
    "# Linux Essentials\n\n"
    "## What Even Is Linux? (Start Here If You Are New)\n\n"
    "Imagine your computer is a restaurant. The **hardware** (CPU, RAM, disk) is the kitchen equipment. "
    "The **operating system** is the head chef who controls everything — decides who gets to use the grills, "
    "hands out ingredients, and keeps order. Linux is one such head chef, and it runs on almost every server, "
    "cloud machine, Docker container, and CI/CD pipeline in the world.\n\n"
    "You have likely used Windows or macOS as your personal computer OS. Linux is different — it was designed "
    "from the ground up for servers, automation, and multi-user environments. It is fast, stable, free, and open "
    "source (anyone can read or modify its code).\n\n"
    "**Why should a developer learn Linux?**\n"
    "- Your code runs on Linux servers (AWS EC2, GCP, Azure — all Linux under the hood)\n"
    "- Docker containers ARE Linux\n"
    "- CI/CD pipelines run bash scripts on Linux runners\n"
    "- SSH into any production machine = you are in a Linux terminal\n"
    "- Kubernetes pods run Linux containers\n\n"
    "```\n"
    "Your laptop (macOS/Windows)\n"
    "        |\n"
    "        | SSH connection\n"
    "        v\n"
    "Linux Server (AWS EC2, GCP VM, VPS...)\n"
    "  - Ubuntu 22.04 LTS  (most popular for servers)\n"
    "  - CentOS / RHEL     (enterprise)\n"
    "  - Alpine Linux      (used inside Docker - tiny 5MB)\n"
    "```\n\n"
    "---\n\n"
    "## The Terminal - Your New Best Friend\n\n"
    "When you work with Linux, you do not click around a graphical UI. You type commands in a **terminal** "
    "(also called shell, command line, or CLI - Command Line Interface).\n\n"
    "**Analogy:** Think of the terminal like texting your computer. Instead of clicking 'New Folder', "
    "you type `mkdir my-folder`. It feels weird at first, but it is 10x faster once you know the language.\n\n"
    "The most common shell is **bash** (Bourne Again Shell). When you open a terminal, you see a prompt:\n\n"
    "```\n"
    "alice@myserver:~$\n"
    "  |       |    | |\n"
    "  |       |    | +-- $ means regular user  (# means root/admin)\n"
    "  |       |    +---- ~ means you are in your home directory\n"
    "  |       +--------- hostname (the server name)\n"
    "  +----------------- your username\n"
    "```\n\n"
    "You type a command, press Enter, see the output, done:\n\n"
    "```bash\n"
    "alice@myserver:~$ echo \"Hello Linux\"\n"
    "Hello Linux\n"
    "alice@myserver:~$        <-- prompt returns, ready for next command\n"
    "```\n\n"
    "---\n\n"
    "## The Filesystem - Everything Is a File\n\n"
    "Linux has one giant directory tree. Everything lives inside it — programs, configs, logs, "
    "even hardware devices. This is different from Windows which has C:\\ D:\\ etc.\n\n"
    "```\n"
    "/                          <- the root - the very top of everything\n"
    "|\n"
    "+-- bin/                   <- essential programs: ls, cp, mv, echo\n"
    "+-- etc/                   <- ALL configuration files live here\n"
    "|   +-- nginx/\n"
    "|   |   +-- nginx.conf     <- Nginx web server config\n"
    "|   +-- ssh/\n"
    "|   |   +-- sshd_config    <- SSH server settings\n"
    "|   +-- hosts              <- hostname to IP mappings\n"
    "+-- home/                  <- user home directories\n"
    "|   +-- alice/             <- alice personal space (written as ~)\n"
    "|   +-- bob/\n"
    "+-- var/                   <- data that changes over time\n"
    "|   +-- log/               <- LOG FILES live here!\n"
    "|       +-- syslog         <- system-wide events\n"
    "|       +-- auth.log       <- login attempts\n"
    "|       +-- nginx/access.log  <- every HTTP request\n"
    "+-- tmp/                   <- temporary files - WIPED on reboot\n"
    "+-- usr/                   <- user-installed programs\n"
    "|   +-- bin/               <- programs installed via apt\n"
    "+-- proc/                  <- VIRTUAL: shows running processes as files\n"
    "+-- dev/                   <- device files (disks, terminals)\n"
    "    +-- sda                <- your primary hard drive\n"
    "```\n\n"
    "**Memory trick - what each folder means:**\n"
    "- `/etc` = The HR / Policy office (all the rules and configs)\n"
    "- `/var/log` = The security camera room (audit logs)\n"
    "- `/home/alice` = Alice's personal office\n"
    "- `/tmp` = A whiteboard erased every morning\n"
    "- `/usr/bin` = Where all the installed software tools live\n"
    "- `/proc` = A live snapshot of what the system is doing RIGHT NOW\n\n"
    "**Real-world scenario:** Your Spring Boot app crashes at 3am. You SSH in and:\n"
    "1. Go to `/var/log/` to find your app log file\n"
    "2. Run `tail -100 /var/log/myapp/app.log` to see the last 100 lines\n"
    "3. Spot the `OutOfMemoryError`, understand it, fix the heap setting\n\n"
    "---\n\n"
    "## Navigating the Filesystem - Moving Around\n\n"
    "These are the commands you will type hundreds of times per day:\n\n"
    "```bash\n"
    "# WHERE AM I RIGHT NOW?\n"
    "pwd\n"
    "# Output: /home/alice\n"
    "# pwd = Print Working Directory\n\n"
    "# WHAT IS IN THIS FOLDER?\n"
    "ls              # basic list\n"
    "ls -l           # long format: shows permissions, size, date\n"
    "ls -a           # show hidden files too (files starting with .)\n"
    "ls -lah         # everything: long + all + human-readable sizes\n"
    "# Example output:\n"
    "# drwxr-xr-x  3 alice alice 4.0K Jan 15 09:00 projects/\n"
    "# -rw-r--r--  1 alice alice  82K Jan 14 18:30 notes.txt\n"
    "# d = directory, - = regular file\n\n"
    "# MOVE TO A DIFFERENT FOLDER\n"
    "cd /etc                # go to /etc  (absolute path - starts from /)\n"
    "cd projects            # go to projects/ folder (relative - from where you are)\n"
    "cd ..                  # go up one level (like clicking back)\n"
    "cd ~                   # go to YOUR home directory\n"
    "cd -                   # go back to where you just were\n\n"
    "# CREATE FOLDERS AND FILES\n"
    "mkdir photos           # make a new folder\n"
    "mkdir -p a/b/c/d       # make nested folders all at once\n"
    "touch notes.txt        # create empty file\n\n"
    "# COPY, MOVE, RENAME, DELETE\n"
    "cp file.txt backup.txt        # copy a file\n"
    "cp -r folder/ backup_folder/  # copy a folder (need -r for recursive)\n"
    "mv old.txt new.txt            # rename a file\n"
    "mv file.txt /tmp/             # move file to /tmp folder\n"
    "rm file.txt                   # delete a file (NO RECYCLE BIN!)\n"
    "rm -rf folder/                # delete folder and EVERYTHING inside\n"
    "```\n\n"
    "> WARNING: `rm -rf` has no undo. There is no trash. Always double-check before running it.\n\n"
    "---\n\n"
    "## Reading Files - Viewing Content\n\n"
    "```bash\n"
    "cat file.txt          # print the whole file on screen\n"
    "less file.txt         # page through (q to quit, arrow keys to scroll, / to search)\n"
    "head -20 file.txt     # show first 20 lines only\n"
    "tail -20 file.txt     # show last 20 lines only\n"
    "tail -f app.log       # LIVE VIEW - shows new lines as they appear\n"
    "                      # perfect for watching logs in real time! Ctrl+C to stop\n\n"
    "# SEARCH INSIDE FILES\n"
    "grep \"ERROR\" app.log               # find lines containing ERROR\n"
    "grep -i \"error\" app.log            # same but case-insensitive\n"
    "grep -r \"database\" /etc/           # search inside ALL files in /etc\n"
    "grep -n \"NullPointer\" app.log      # show line numbers with matches\n"
    "grep -A 3 -B 3 \"FATAL\" app.log     # show 3 lines before and after each match\n"
    "grep -c \"ERROR\" app.log            # just count how many lines match\n"
    "```\n\n"
    "**Real-world scenario:** App is throwing errors in production. You run:\n"
    "```bash\n"
    "tail -f /var/log/myapp/app.log | grep ERROR\n"
    "```\n"
    "This pipes tail into grep - you see ONLY error lines as they appear, live. "
    "You can spot patterns instantly.\n\n"
    "---\n\n"
    "## File Permissions - Who Can Do What\n\n"
    "Every single file in Linux has **access rules** for three groups of people. "
    "This matters a LOT in production - wrong permissions = app crashes or security holes.\n\n"
    "```\n"
    "-rw-r--r--  1  alice  developers  4096  Jan 15  report.txt\n"
    "|          |   |      |\n"
    "|          |   |      +- group name (developers)\n"
    "|          |   +-------- owner name (alice)\n"
    "|          +------------ number of hard links\n"
    "+----------------------- permission string (10 characters)\n"
    "```\n\n"
    "**The 10-character permission string explained:**\n"
    "```\n"
    "  -  r w -  r - -  r - -\n"
    "  |  |   |  |   |  |   |\n"
    "  |  +---+  +---+  +---+\n"
    "  |  owner  group  others\n"
    "  |\n"
    "  + file type: - = regular file\n"
    "               d = directory\n"
    "               l = symbolic link (shortcut)\n"
    "```\n\n"
    "**What r, w, x mean:**\n"
    "```\n"
    "r = read    = can you open and read this file?       (value = 4)\n"
    "w = write   = can you change or delete this file?   (value = 2)\n"
    "x = execute = can you run this as a program?        (value = 1)\n"
    "- = no permission for this slot\n"
    "```\n\n"
    "**How the numbers work in chmod:**\n"
    "```\n"
    "You add up the values to get one number per group:\n\n"
    "rwx = 4+2+1 = 7   (full access)\n"
    "rw- = 4+2+0 = 6   (read + write, no execute)\n"
    "r-x = 4+0+1 = 5   (read + execute, no write)\n"
    "r-- = 4+0+0 = 4   (read only)\n"
    "--- = 0+0+0 = 0   (no access whatsoever)\n\n"
    "chmod 755 script.sh\n"
    "       |||\n"
    "       ||+-- others: 5 = r-x (can read and run, cannot write)\n"
    "       |+--- group:  5 = r-x\n"
    "       +---- owner:  7 = rwx (full access)\n\n"
    "chmod 600 private_key\n"
    "       |||\n"
    "       ||+-- others: 0 = --- (NO access at all)\n"
    "       |+--- group:  0 = --- (NO access at all)\n"
    "       +---- owner:  6 = rw- (can read and write)\n"
    "```\n\n"
    "**Common permission recipes to memorize:**\n"
    "```bash\n"
    "chmod 755 script.sh        # shell scripts: owner full, everyone can read+run\n"
    "chmod 644 config.txt       # config files: owner can edit, everyone can read\n"
    "chmod 600 ~/.ssh/id_rsa    # SSH private key: ONLY owner reads (SSH refuses if wrong!)\n"
    "chmod 700 ~/.ssh/          # .ssh folder: only owner can enter\n"
    "chmod +x deploy.sh         # add execute for everyone (keeps other permissions)\n"
    "chmod -R 755 /var/www/     # -R = recursive: apply to all files inside\n"
    "```\n\n"
    "**chown - change who owns a file:**\n"
    "```bash\n"
    "chown alice report.txt              # change owner to alice\n"
    "chown alice:developers report.txt   # change owner AND group\n"
    "sudo chown -R www-data /var/www/html  # recursive ownership change\n"
    "```\n\n"
    "**Real-world pitfall:** Your app cannot write to its log folder:\n"
    "```bash\n"
    "ls -la /var/log/\n"
    "# drwxr-xr-x  2  root  root  4096  Jan 15  myapp/\n"
    "# Problem: folder is owned by root! Your app user cannot write to it.\n"
    "# Fix:\n"
    "sudo chown -R myappuser:myappuser /var/log/myapp/\n"
    "```\n\n"
    "---\n\n"
    "## Processes - Running Programs\n\n"
    "When you run a program, the OS creates a **process** - an instance of the program "
    "with its own chunk of memory and a unique **PID** (Process ID - just a number).\n\n"
    "```\n"
    "You type: java -jar app.jar\n"
    "                |\n"
    "                v\n"
    "Kernel creates a process:\n"
    "  PID:    4521\n"
    "  Memory: 512MB heap allocated\n"
    "  Files:  opens app.jar, log file, network sockets\n"
    "  CPU:    scheduled to run on available core\n"
    "                |\n"
    "                v\n"
    "Process runs until:\n"
    "  - Normal exit   (code calls System.exit(0))\n"
    "  - Error crash   (unhandled exception)\n"
    "  - You kill it   (SIGTERM or SIGKILL)\n"
    "```\n\n"
    "**Viewing processes:**\n"
    "```bash\n"
    "ps aux\n"
    "# Shows ALL running processes\n"
    "# a=all users  u=user-friendly format  x=include background\n"
    "# Output:\n"
    "# USER   PID  %CPU  %MEM  COMMAND\n"
    "# alice  4521  25.3  12.8  java -jar app.jar\n"
    "# root    234   0.1   0.2  nginx: master process\n\n"
    "top           # live updating process viewer (like Windows Task Manager)\n"
    "htop          # prettier version of top (install: sudo apt install htop)\n"
    "              # q to quit\n\n"
    "pgrep nginx   # find the PID of process named nginx\n"
    "pgrep -a java # find all java processes with their full command\n"
    "```\n\n"
    "**Stopping processes:**\n"
    "```bash\n"
    "kill 4521       # send SIGTERM - politely ask the process to stop\n"
    "kill -9 4521    # send SIGKILL - immediate force kill (no cleanup)\n"
    "killall java    # kill ALL processes named java\n\n"
    "# ALWAYS try SIGTERM first!\n"
    "# SIGTERM = like asking a chef to finish the dish before going home\n"
    "# SIGKILL = like cutting the power - no chance to save anything\n"
    "```\n\n"
    "**Running in background:**\n"
    "```bash\n"
    "./long_script.sh &    # & = run in background, get prompt back immediately\n"
    "nohup ./server.sh &   # nohup = keep running even after terminal closes\n"
    "jobs                  # list background jobs in this terminal\n"
    "fg %1                 # bring job 1 to foreground\n"
    "Ctrl+Z                # pause/suspend current program\n"
    "Ctrl+C                # stop/kill current program\n"
    "```\n\n"
    "---\n\n"
    "## Pipes and Redirection - The Unix Superpower\n\n"
    "This is where Linux becomes incredibly powerful. You can **chain commands together** — "
    "the output of one command becomes the input of the next. It is like an assembly line.\n\n"
    "```\n"
    "command1  |  command2  |  command3\n"
    "    |            |            |\n"
    "    |      takes command1     |\n"
    "    |      output as input    +-- takes command2 output as input\n"
    "    +-- runs first, produces output\n"
    "```\n\n"
    "**Examples:**\n"
    "```bash\n"
    "# Count ERROR lines in a log file\n"
    "grep 'ERROR' app.log | wc -l\n\n"
    "# Find top 10 IPs making POST requests\n"
    "cat access.log | grep 'POST' | awk '{print $1}' | sort | uniq -c | sort -rn | head -10\n"
    "#     |               |               |            |        |           |          |\n"
    "#  read file      keep POSTs    get 1st column  sort   count     sort by count  top 10\n\n"
    "# Find all java processes and show only their PIDs\n"
    "ps aux | grep java | awk '{print $2}'\n"
    "```\n\n"
    "**Redirection - sending output to files instead of screen:**\n"
    "```bash\n"
    "ls -la > filelist.txt        # > OVERWRITES the file (creates if not exists)\n"
    "ls -la >> filelist.txt       # >> APPENDS to end of file\n"
    "cat nope.txt 2> errors.txt   # 2> redirects only ERROR output\n"
    "java -jar app.jar > app.log 2>&1  # both normal AND error output to one file\n"
    "                                   # 2>&1 means 'send stderr to wherever stdout goes'\n\n"
    "# Useful pattern: run app in background, log everything:\n"
    "nohup java -jar app.jar > app.log 2>&1 &\n"
    "```\n\n"
    "---\n\n"
    "## SSH - Connecting to Remote Servers\n\n"
    "SSH (Secure Shell) lets you control a remote Linux server as if you are sitting at it. "
    "All traffic is encrypted - nobody can snoop on your commands.\n\n"
    "```\n"
    "Your Laptop                      Remote Server\n"
    "    |                                 |\n"
    "    |  === encrypted SSH tunnel ===>  |\n"
    "    |                           you control it\n"
    "    |                           run commands\n"
    "    |                           read files\n"
    "    |                           restart services\n"
    "```\n\n"
    "**Connecting to a server:**\n"
    "```bash\n"
    "ssh alice@192.168.1.50           # connect by IP address\n"
    "ssh alice@myserver.com           # connect by hostname\n"
    "ssh -p 2222 alice@server.com     # use port 2222 (default is 22)\n"
    "ssh -i ~/.ssh/mykey.pem ec2-user@3.14.159.26  # AWS EC2 with key file\n"
    "```\n\n"
    "**SSH Key Authentication (better than passwords):**\n"
    "```bash\n"
    "# STEP 1: Generate a key pair on YOUR OWN machine\n"
    "ssh-keygen -t ed25519 -C \"my work laptop key\"\n"
    "# This creates TWO files:\n"
    "#   ~/.ssh/id_ed25519      <- PRIVATE KEY (never share this, ever!)\n"
    "#   ~/.ssh/id_ed25519.pub  <- PUBLIC KEY  (safe to give to servers)\n\n"
    "# STEP 2: Put your public key on the server\n"
    "ssh-copy-id alice@192.168.1.50\n"
    "# Or manually append to server's ~/.ssh/authorized_keys\n\n"
    "# STEP 3: Connect without password!\n"
    "ssh alice@192.168.1.50\n"
    "```\n\n"
    "**How it works (simplified):**\n"
    "```\n"
    "Your public key  ---> goes to the server  (like a padlock)\n"
    "Your private key ---> stays on your laptop (like the key)\n\n"
    "Server says: \"Prove you have the key for this padlock\"\n"
    "Your laptop signs a challenge with private key, sends the signature\n"
    "Server checks the signature with public key\n"
    "Server: \"Valid! Come in.\"\n"
    "You never send the private key over the network!\n"
    "```\n\n"
    "**Copying files over SSH:**\n"
    "```bash\n"
    "scp report.txt alice@server:/home/alice/      # copy TO server\n"
    "scp alice@server:/var/log/app.log ./          # copy FROM server\n"
    "scp -r ./project alice@server:/home/alice/   # copy entire folder\n"
    "```\n\n"
    "**Common SSH problem - Permission denied (publickey):**\n"
    "```\n"
    "Fix checklist:\n"
    "1. chmod 600 ~/.ssh/id_ed25519       (private key must be owner-only)\n"
    "2. chmod 700 ~/.ssh/                 (.ssh folder must be owner-only)\n"
    "3. Check public key is in server ~/.ssh/authorized_keys\n"
    "4. Use correct username (ec2-user for AWS, ubuntu for Ubuntu AMIs)\n"
    "5. Verify server IP/hostname is correct\n"
    "6. Check SSH service: sudo systemctl status ssh\n"
    "```\n\n"
    "---\n\n"
    "## Package Management - Installing Software\n\n"
    "In Linux you do not download installers from websites. "
    "You use a **package manager** - a built-in tool that downloads, installs, and updates software safely.\n\n"
    "**Ubuntu/Debian (apt):**\n"
    "```bash\n"
    "sudo apt update              # first: refresh what packages are available\n"
    "sudo apt install nginx       # install nginx web server\n"
    "sudo apt install -y openjdk-17-jdk  # -y = yes to all prompts\n"
    "sudo apt remove nginx        # uninstall\n"
    "sudo apt upgrade             # upgrade all installed packages\n"
    "apt search \"text editor\"    # search for packages\n"
    "apt show nginx               # get details about a package\n"
    "```\n\n"
    "**CentOS / RHEL / Fedora (dnf):**\n"
    "```bash\n"
    "sudo dnf update\n"
    "sudo dnf install nginx\n"
    "sudo dnf remove nginx\n"
    "```\n\n"
    "**What is sudo?**\n"
    "Most system commands need **root** (admin) privileges. "
    "`sudo` runs that ONE command as root, then drops back:\n"
    "```bash\n"
    "sudo apt install nginx    # runs apt install as root (asks your password)\n"
    "sudo systemctl restart nginx\n"
    "sudo nano /etc/nginx/nginx.conf  # edit a protected config file\n"
    "```\n\n"
    "---\n\n"
    "## Environment Variables - Configuring Programs\n\n"
    "Environment variables are **name=value** settings that programs can read. "
    "This is how you pass database URLs, API keys, and config to your app without hardcoding.\n\n"
    "```bash\n"
    "env                    # see ALL environment variables\n"
    "echo $HOME             # /home/alice\n"
    "echo $USER             # alice\n"
    "echo $PATH             # /usr/local/bin:/usr/bin:/bin\n\n"
    "# Set for current session only\n"
    "export DB_URL=\"postgresql://localhost:5432/mydb\"\n\n"
    "# Set permanently (survives terminal restarts)\n"
    "echo 'export DB_URL=\"postgresql://localhost:5432/mydb\"' >> ~/.bashrc\n"
    "source ~/.bashrc       # reload - makes it active NOW\n"
    "```\n\n"
    "**How PATH works:**\n"
    "```\n"
    "PATH=/usr/local/bin:/usr/bin:/bin\n"
    "          |              |      |\n"
    "          |              |      +-- check /bin/ for the command\n"
    "          |              +--------- check /usr/bin/ next\n"
    "          +------------------------ check /usr/local/bin/ FIRST\n\n"
    "When you type: java\n"
    "Linux searches each PATH folder left-to-right until it finds 'java'\n"
    "If not found: 'command not found' error\n\n"
    "Fix: if java is at /opt/java/bin/java, add to PATH:\n"
    "export PATH=$PATH:/opt/java/bin\n"
    "```\n\n"
    "---\n\n"
    "## System Health - Monitoring Your Server\n\n"
    "```bash\n"
    "# DISK SPACE\n"
    "df -h         # disk free - shows all filesystems with human-readable sizes\n"
    "# Output:\n"
    "# Filesystem   Size   Used  Avail  Use%  Mounted on\n"
    "# /dev/sda1     50G    23G    25G   48%  /\n"
    "du -sh /var/log/   # disk usage of a specific folder\n"
    "du -sh /*          # disk usage of all top-level folders\n\n"
    "# RAM\n"
    "free -h       # show memory usage\n"
    "# Output:\n"
    "#             total   used   free   available\n"
    "# Mem:         15Gi   8Gi    2Gi    6Gi\n\n"
    "# UPTIME AND LOAD\n"
    "uptime        # how long system has been running + load averages\n\n"
    "# HARDWARE INFO\n"
    "lscpu         # CPU info (cores, speed, architecture)\n"
    "ip addr       # network interfaces and IP addresses\n"
    "cat /etc/os-release   # what distro and version is this?\n"
    "uname -a      # kernel version\n"
    "```\n\n"
    "---\n\n"
    "## Editing Text Files\n\n"
    "```bash\n"
    "# NANO - beginner friendly editor\n"
    "nano /etc/hosts\n"
    "# Ctrl+O = save file\n"
    "# Ctrl+X = exit\n"
    "# Ctrl+W = search\n"
    "# Bottom bar shows all shortcuts in plain English\n\n"
    "# VIM - powerful but needs learning\n"
    "vim /etc/nginx/nginx.conf\n"
    "# Press i = enter INSERT mode (now you can type)\n"
    "# Press Esc = back to command mode\n"
    "# Type :wq = save and quit\n"
    "# Type :q! = quit WITHOUT saving (emergency exit!)\n"
    "# Type /word = search for word\n\n"
    "# QUICK EDITS without opening editor\n"
    "sed -i 's/old/new/g' config.txt     # replace 'old' with 'new' in file\n"
    "echo \"new line\" >> config.txt       # append a line to end of file\n"
    "```\n\n"
    "---\n\n"
    "## Mind Map - The Big Picture\n\n"
    "```\n"
    "LINUX ESSENTIALS\n"
    "|\n"
    "+-- FILESYSTEM\n"
    "|   +-- / is root of everything\n"
    "|   +-- /etc = configs\n"
    "|   +-- /var/log = log files\n"
    "|   +-- /home/user = your space\n"
    "|   +-- /tmp = temp (wiped on reboot)\n"
    "|   +-- /proc = virtual (live process info)\n"
    "|\n"
    "+-- NAVIGATION\n"
    "|   +-- pwd (where am I?)\n"
    "|   +-- ls (what is here?)\n"
    "|   +-- cd (move around)\n"
    "|   +-- mkdir, touch, cp, mv, rm\n"
    "|\n"
    "+-- READING FILES\n"
    "|   +-- cat (dump to screen)\n"
    "|   +-- less (scroll through)\n"
    "|   +-- tail -f (live follow)\n"
    "|   +-- grep (search inside)\n"
    "|\n"
    "+-- PERMISSIONS\n"
    "|   +-- rwx = read/write/execute\n"
    "|   +-- 3 groups: owner, group, others\n"
    "|   +-- chmod (change permissions)\n"
    "|   +-- chown (change owner)\n"
    "|   +-- Key recipes: 600=private, 755=script\n"
    "|\n"
    "+-- PROCESSES\n"
    "|   +-- ps aux (see all)\n"
    "|   +-- top/htop (live monitor)\n"
    "|   +-- kill PID (SIGTERM = graceful)\n"
    "|   +-- kill -9 PID (SIGKILL = force)\n"
    "|   +-- & and nohup (background)\n"
    "|\n"
    "+-- PIPES & REDIRECTION\n"
    "|   +-- | (pipe: chain commands)\n"
    "|   +-- > (overwrite to file)\n"
    "|   +-- >> (append to file)\n"
    "|   +-- 2>&1 (merge errors into output)\n"
    "|\n"
    "+-- SSH\n"
    "|   +-- ssh user@host (connect)\n"
    "|   +-- ssh-keygen (generate key pair)\n"
    "|   +-- chmod 600 private key!\n"
    "|   +-- scp (copy files over SSH)\n"
    "|\n"
    "+-- PACKAGES\n"
    "    +-- apt update (refresh list)\n"
    "    +-- apt install X (install)\n"
    "    +-- sudo prefix for admin commands\n"
    "```\n\n"
    "---\n\n"
    "## How This Connects to Other Topics\n\n"
    "- **Git**: You run `git` commands from bash. Every `git push` is a Linux command.\n"
    "- **Docker**: Containers ARE Linux. `docker exec -it container bash` drops you into a Linux shell.\n"
    "- **CI/CD Pipelines**: Pipeline steps are bash scripts on Linux runners.\n"
    "- **Kubernetes**: `kubectl exec -it pod -- bash` gives you a Linux shell inside a pod.\n"
    "- **AWS/Cloud**: EC2 instances are Linux VMs. You SSH in, manage processes, tail logs.\n\n"
    "---\n\n"
    "## Common Beginner Mistakes\n\n"
    "1. **Forgetting sudo** — `Permission denied`? Add `sudo` in front.\n"
    "2. **rm -rf wrong path** — Always `ls` first to confirm what is there before deleting.\n"
    "3. **File not writable** — `ls -la` to check permissions before editing.\n"
    "4. **SSH Permission denied** — Check: `chmod 600 ~/.ssh/id_rsa`, correct username, key in authorized_keys.\n"
    "5. **Command not found** — Program installed but not in PATH. Use `which programname` to find it.\n"
    "6. **Lost in directories** — Run `pwd` to see where you are. `cd ~` always gets you home.\n"
    "7. **grep finds nothing** — Try `grep -i` for case-insensitive. The case might not match.\n\n"
    "---\n\n"
    "## References and Further Learning\n\n"
    "### Videos (Watch These!)\n"
    "- **Linux Command Line Full Course** by tutorialinux: https://www.youtube.com/watch?v=ZtqBQ68cfJc\n"
    "  - 5-hour beginner to intermediate. Go at your own pace.\n"
    "- **60 Linux Commands you NEED to know** by NetworkChuck: https://www.youtube.com/watch?v=gd7BXuUQ91w\n"
    "  - Fast-paced, practical, fun. Great overview.\n\n"
    "### Free Books and Articles\n"
    "- **The Linux Command Line** (free full book): https://linuxcommand.org/tlcl.php\n"
    "  - Best free beginner book by William Shotts. Read chapters 1-10 first.\n"
    "- **Linux Journey** (interactive exercises): https://linuxjourney.com/\n"
    "  - Gamified step-by-step lessons. Do 15 min per day.\n"
    "- **Explain Shell** (paste any command, get it explained): https://explainshell.com/\n"
    "  - Paste `find /var -name '*.log' -mtime -1` and see every part explained visually.\n\n"
    "### Diagrams and Cheatsheets\n"
    "- **Linux Filesystem Hierarchy Diagram**: search 'Linux FHS diagram' on Google Images\n"
    "- **chmod calculator** (visual permissions tool): https://chmod-calculator.com/\n"
    "- **Bash reference manual**: https://www.gnu.org/software/bash/manual/bash.html\n\n"
    "### Practice (hands-on is the only way)\n"
    "- **OverTheWire Bandit** (gamified Linux challenges from zero): https://overthewire.org/wargames/bandit/\n"
    "  - Level 0 starts with just `ssh`. By level 30 you know Linux well.\n"
    "- **TryHackMe Linux Fundamentals** (browser terminal, no install needed): https://tryhackme.com/module/linux-fundamentals\n"
)

d['guide'] = NEW_GUIDE
with open(p, 'w') as f:
    json.dump(d, f, indent=2, ensure_ascii=False)
print(f"Done! Guide length: {len(NEW_GUIDE)} chars")
print(f"Questions: {len(d['questions'])}, Flashcards: {len(d['flashcards'])}")

