import json
from pathlib import Path

p = Path('/Users/eptr6dj/IdeaProjects/master-cs/cs-mastery/src/content/topics/cloud-devops/docker.json')
d = json.loads(p.read_text())

# ── GUIDE ─────────────────────────────────────────────────────────────────────
lines = []
lines += [
    "# Docker",
    "",
    "## What Is Docker? (Zero Assumptions)",
    "",
    "Picture this: you build a Java Spring Boot app on your MacBook. It works perfectly.",
    "You deploy it to an Ubuntu server — it crashes. 'Works on my machine!' is the classic",
    "developer nightmare. Different OS, different Java version, different library versions,",
    "missing environment variables — anything can go wrong.",
    "",
    "Docker solves this by packaging your **app + everything it needs** into one unit called",
    "a **container**. The container runs identically everywhere — your laptop, a colleague's",
    "Windows machine, an AWS server, a CI/CD pipeline. Same result, every time.",
    "",
    "**Analogy:** Think of a Docker container like a shipping container on a cargo ship.",
    "Before shipping containers existed, cargo was loaded piece by piece — slow, inconsistent,",
    "error-prone. Shipping containers standardised everything: same box, same crane interface,",
    "works on any ship or truck. Docker does the same for software.",
    "",
    "```",
    "Without Docker:                    With Docker:",
    "  Your laptop: Java 17              Container image packages:",
    "  Server:      Java 11              - Your app .jar",
    "  CI server:   Java 21              - Java 17 (exact version)",
    "  'It works on my machine!'         - All dependencies",
    "                                    - Config files",
    "                                    Runs IDENTICALLY everywhere",
    "```",
    "",
    "---",
    "",
    "## Virtual Machines vs Containers",
    "",
    "Both give you an isolated environment, but they work very differently:",
    "",
    "```",
    "VIRTUAL MACHINE:                    CONTAINER:",
    "",
    "+---------------------------+        +---------------------------+",
    "| App A      | App B        |        | App A  | App B  | App C  |",
    "| (Node.js)  | (Java)       |        +--------+--------+--------+",
    "+------------+--------------+        | Container Runtime (runc) |",
    "| Guest OS A | Guest OS B   |        +---------------------------+",
    "| (Ubuntu)   | (Windows)    |        | Host OS Kernel (Linux)   |",
    "+------------+--------------+        +---------------------------+",
    "| Hypervisor (VMware/VBox)  |        | Physical Hardware         |",
    "+---------------------------+        +---------------------------+",
    "| Physical Hardware         |",
    "+---------------------------+",
    "",
    "VM:        Each app has its OWN full OS = heavy (GBs), slow to start (minutes)",
    "Container: Apps SHARE the host OS kernel = light (MBs), starts in seconds",
    "```",
    "",
    "**Key differences:**",
    "| Feature | Virtual Machine | Container |",
    "| --- | --- | --- |",
    "| Startup time | 1-5 minutes | Under 1 second |",
    "| Size | 1-20 GB | 10-500 MB |",
    "| Isolation | Full OS isolation | Process isolation |",
    "| OS | Each VM has its own | Shares host kernel |",
    "| Use case | Full environment isolation | App packaging and deployment |",
    "",
    "---",
    "",
    "## Core Concepts: Image vs Container",
    "",
    "This is the most important distinction to understand:",
    "",
    "```",
    "IMAGE                               CONTAINER",
    "(a blueprint / recipe)              (a running instance)",
    "",
    "Like a class in OOP                 Like an object (instance of the class)",
    "Like a cookie cutter                Like an actual cookie",
    "Like a CD-ROM with the OS           Like a running OS on your machine",
    "",
    "Read-only snapshot                  Running process with its own memory,",
    "stored on disk                      filesystem, network",
    "",
    "You BUILD images                    You RUN containers FROM images",
    "You PUSH images to registries       You can run many containers",
    "You PULL images to machines         from the same image",
    "```",
    "",
    "**Docker Hub** is the public registry where images live:",
    "- `nginx` = official Nginx web server image",
    "- `postgres:15` = PostgreSQL version 15",
    "- `openjdk:17-slim` = lean Java 17 runtime",
    "- `yourusername/myapp:v1.2` = your own custom image",
    "",
    "---",
    "",
    "## Installing Docker and First Commands",
    "",
    "```bash",
    "# Install on Ubuntu",
    "sudo apt update",
    "sudo apt install docker.io",
    "sudo systemctl start docker",
    "sudo systemctl enable docker  # start on boot",
    "",
    "# Add yourself to docker group (avoid needing sudo every time)",
    "sudo usermod -aG docker $USER",
    "# Log out and back in for this to take effect",
    "",
    "# Verify installation",
    "docker --version",
    "docker run hello-world   # downloads and runs a test container",
    "```",
    "",
    "---",
    "",
    "## Essential Docker Commands",
    "",
    "```bash",
    "# IMAGES",
    "docker images                    # list images on your machine",
    "docker pull nginx                # download nginx image from Docker Hub",
    "docker pull postgres:15          # specific version tag",
    "docker rmi nginx                 # remove an image",
    "docker image prune               # remove all unused images",
    "",
    "# RUNNING CONTAINERS",
    "docker run nginx                 # start a container (foreground, blocks terminal)",
    "docker run -d nginx              # -d = detached (background), returns container ID",
    "docker run -d -p 8080:80 nginx   # -p host_port:container_port (port mapping)",
    "                                  # now http://localhost:8080 hits nginx inside container",
    "docker run -d --name my-nginx nginx  # give container a name (easier to reference)",
    "docker run --rm nginx            # --rm = auto-delete when container stops",
    "",
    "# VIEWING CONTAINERS",
    "docker ps                        # list RUNNING containers",
    "docker ps -a                     # list ALL containers (including stopped)",
    "docker logs my-nginx             # see container output/logs",
    "docker logs -f my-nginx          # follow logs live (like tail -f)",
    "docker stats                     # live CPU/memory usage of all containers",
    "",
    "# MANAGING CONTAINERS",
    "docker stop my-nginx             # graceful stop (SIGTERM, waits for cleanup)",
    "docker kill my-nginx             # force stop (SIGKILL immediately)",
    "docker start my-nginx            # restart a stopped container",
    "docker rm my-nginx               # delete a stopped container",
    "docker rm -f my-nginx            # force remove running container",
    "",
    "# GOING INSIDE A CONTAINER (like SSH)",
    "docker exec -it my-nginx bash    # open interactive bash terminal inside container",
    "docker exec -it my-nginx sh      # use sh if bash not available (Alpine images)",
    "# -i = interactive  -t = allocate a pseudo-TTY (needed for terminal)",
    "",
    "# COPYING FILES",
    "docker cp my-nginx:/etc/nginx/nginx.conf ./   # copy FROM container to host",
    "docker cp ./app.jar my-container:/app/        # copy FROM host TO container",
    "```",
    "",
    "**Port mapping explained:**",
    "```",
    "docker run -d -p 8080:80 nginx",
    "                  |   |",
    "                  |   +-- container port (nginx listens on 80 inside)",
    "                  +------- host port (you access via localhost:8080)",
    "",
    "Browser: http://localhost:8080",
    "                    |",
    "                    | Docker NAT",
    "                    v",
    "        Container port 80 (nginx)",
    "```",
    "",
    "---",
    "",
    "## The Dockerfile — Building Your Own Image",
    "",
    "A `Dockerfile` is a recipe that tells Docker how to build your image.",
    "Each instruction creates a new **layer** (cached).",
    "",
    "```dockerfile",
    "# Start FROM an existing base image",
    "FROM openjdk:17-slim",
    "",
    "# Set the working directory inside the container",
    "WORKDIR /app",
    "",
    "# COPY files from host into the image",
    "# Copy pom.xml FIRST (changes rarely) — layer cache trick",
    "COPY pom.xml .",
    "COPY src ./src",
    "",
    "# RUN a command during image BUILD (not at runtime)",
    "RUN ./mvnw package -DskipTests",
    "",
    "# Declare which port the app listens on (documentation only, does not publish)",
    "EXPOSE 8080",
    "",
    "# Set an environment variable",
    "ENV SPRING_PROFILES_ACTIVE=production",
    "",
    "# CMD = default command when container STARTS (can be overridden)",
    "CMD [\"java\", \"-jar\", \"target/app.jar\"]",
    "",
    "# ENTRYPOINT = fixed command, CMD becomes its arguments",
    "# ENTRYPOINT [\"java\", \"-jar\", \"target/app.jar\"]",
    "```",
    "",
    "**Build and run your image:**",
    "```bash",
    "docker build -t myapp:v1 .          # build image, tag as myapp:v1, use current dir",
    "docker build -t myapp:v1 -f Dockerfile.prod .  # use specific Dockerfile",
    "docker run -d -p 8080:8080 myapp:v1",
    "```",
    "",
    "---",
    "",
    "## Layer Caching — Why Order Matters",
    "",
    "Docker caches each layer. If a layer has not changed, it reuses the cache.",
    "This makes rebuilds much faster. Order your Dockerfile to maximise cache hits.",
    "",
    "```",
    "BAD ORDER (slow rebuilds):",
    "  COPY . .              <- copies ALL source code (changes every edit)",
    "  RUN mvn install       <- runs every time because source changed",
    "",
    "GOOD ORDER (fast rebuilds):",
    "  COPY pom.xml .        <- pom.xml changes rarely -> layer cache usually HIT",
    "  RUN mvn dependency:go-offline  <- downloads deps once, cached",
    "  COPY src ./src        <- source changes often, but only this layer reruns",
    "  RUN mvn package       <- only reruns if src changed",
    "",
    "Layer cache logic:",
    "  If layer N changes -> ALL layers after N must rebuild",
    "  Put rarely-changing steps FIRST, frequently-changing steps LAST",
    "```",
    "",
    "---",
    "",
    "## Multi-Stage Builds — Smaller Production Images",
    "",
    "Problem: your build tools (Maven, npm) are only needed during build — not at runtime.",
    "Multi-stage builds let you build in one container and copy only the output to a lean image.",
    "",
    "```dockerfile",
    "# STAGE 1: build (has Maven, JDK, all build tools — big image)",
    "FROM maven:3.9-openjdk-17 AS builder",
    "WORKDIR /build",
    "COPY pom.xml .",
    "RUN mvn dependency:go-offline",
    "COPY src ./src",
    "RUN mvn package -DskipTests",
    "",
    "# STAGE 2: runtime (only JRE, no Maven, no source code — tiny image)",
    "FROM openjdk:17-slim AS runtime",
    "WORKDIR /app",
    "COPY --from=builder /build/target/app.jar app.jar",
    "EXPOSE 8080",
    "CMD [\"java\", \"-jar\", \"app.jar\"]",
    "",
    "# Result: builder image = ~800MB, runtime image = ~180MB",
    "# Only the runtime stage is shipped to production",
    "```",
    "",
    "---",
    "",
    "## Docker Volumes — Persistent Data",
    "",
    "Containers are ephemeral — when you remove a container, all data inside is lost.",
    "Volumes let you persist data outside the container lifecycle.",
    "",
    "```bash",
    "# Named volume (Docker manages storage location)",
    "docker volume create mydata",
    "docker run -d -v mydata:/var/lib/postgresql/data postgres:15",
    "# Database data survives container removal",
    "",
    "# Bind mount (maps a host directory into the container)",
    "docker run -d -v /home/alice/config:/app/config myapp",
    "# /home/alice/config on host IS /app/config inside container",
    "# Changes on either side are immediately visible to the other",
    "",
    "# List volumes",
    "docker volume ls",
    "docker volume inspect mydata",
    "docker volume rm mydata       # delete (data gone!)",
    "```",
    "",
    "```",
    "Volume types:",
    "  Named volume:    Docker stores at /var/lib/docker/volumes/mydata/",
    "                   Good for databases, persistent state",
    "  Bind mount:      You choose the host directory",
    "                   Good for config files, development (live code reload)",
    "  tmpfs mount:     In-memory only, never written to disk",
    "                   Good for sensitive temp data",
    "```",
    "",
    "---",
    "",
    "## Docker Compose — Multi-Container Apps",
    "",
    "Real apps have multiple services: web server, database, cache, queue.",
    "Docker Compose lets you define and run them all with one file.",
    "",
    "```yaml",
    "# docker-compose.yml",
    "version: '3.8'",
    "",
    "services:",
    "  app:                          # your Spring Boot app",
    "    build: .                    # build from Dockerfile in current dir",
    "    ports:",
    "      - '8080:8080'",
    "    environment:",
    "      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb",
    "      - SPRING_DATASOURCE_PASSWORD=secret",
    "    depends_on:",
    "      - db                      # wait for db service to start",
    "    networks:",
    "      - backend",
    "",
    "  db:                           # PostgreSQL database",
    "    image: postgres:15",
    "    environment:",
    "      - POSTGRES_DB=mydb",
    "      - POSTGRES_PASSWORD=secret",
    "    volumes:",
    "      - pgdata:/var/lib/postgresql/data",
    "    networks:",
    "      - backend",
    "",
    "  redis:                        # Redis cache",
    "    image: redis:7-alpine",
    "    networks:",
    "      - backend",
    "",
    "volumes:",
    "  pgdata:                       # named volume for database",
    "",
    "networks:",
    "  backend:                      # private network — services talk to each other by service name",
    "```",
    "",
    "```bash",
    "docker compose up -d       # start all services in background",
    "docker compose down        # stop and remove containers",
    "docker compose down -v     # also delete volumes (wipes database!)",
    "docker compose logs -f app # follow logs for 'app' service",
    "docker compose ps          # status of all services",
    "docker compose exec app bash  # shell into running 'app' container",
    "docker compose build       # rebuild images",
    "```",
    "",
    "**How services find each other:** Inside a Compose network, services reach each other",
    "by their service name. Your app connects to `db:5432` — Docker DNS resolves `db`",
    "to the database container's IP automatically.",
    "",
    "---",
    "",
    "## Docker Networking",
    "",
    "```",
    "Default networks:",
    "  bridge:  Default for standalone containers. Containers can communicate",
    "           via IP but not by name (use user-defined networks instead)",
    "  host:    Container shares host network stack (no isolation)",
    "           Use only when performance is critical",
    "  none:    No networking at all",
    "",
    "User-defined bridge network (best practice):",
    "  docker network create mynet",
    "  docker run -d --network mynet --name app myapp",
    "  docker run -d --network mynet --name db postgres:15",
    "  Now 'app' can reach 'db' by hostname 'db' — automatic DNS resolution",
    "```",
    "",
    "---",
    "",
    "## Environment Variables and Secrets",
    "",
    "```bash",
    "# Pass env vars at runtime",
    "docker run -e DB_PASSWORD=secret myapp",
    "docker run --env-file .env myapp    # load from file",
    "",
    "# In docker-compose.yml",
    "# environment:",
    "#   - DB_PASSWORD=${DB_PASSWORD}    # reads from host environment",
    "",
    "# .env file (NEVER commit to git!)",
    "# DB_PASSWORD=supersecret",
    "# API_KEY=abc123",
    "```",
    "",
    "**Rule:** Never hardcode secrets in Dockerfiles or docker-compose.yml.",
    "Use environment variables loaded from a `.env` file (in `.gitignore`)",
    "or a secrets manager (AWS Secrets Manager, Vault).",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "DOCKER",
    "|",
    "+-- CONCEPTS",
    "|   +-- Image  = blueprint (read-only)",
    "|   +-- Container = running instance",
    "|   +-- Registry = image storage (Docker Hub)",
    "|   +-- Layer = cached filesystem change",
    "|",
    "+-- DOCKERFILE",
    "|   +-- FROM (base image)",
    "|   +-- COPY (add files)",
    "|   +-- RUN  (build-time commands)",
    "|   +-- CMD  (runtime default command)",
    "|   +-- EXPOSE (document port)",
    "|   +-- Multi-stage (small prod images)",
    "|",
    "+-- COMMANDS",
    "|   +-- docker build -t name .",
    "|   +-- docker run -d -p host:container",
    "|   +-- docker exec -it name bash",
    "|   +-- docker logs -f name",
    "|   +-- docker ps / docker ps -a",
    "|",
    "+-- DATA",
    "|   +-- Volume (persistent, managed)",
    "|   +-- Bind mount (host directory)",
    "|",
    "+-- COMPOSE",
    "|   +-- docker-compose.yml",
    "|   +-- services, networks, volumes",
    "|   +-- docker compose up/down",
    "|",
    "+-- NETWORKING",
    "    +-- bridge (default)",
    "    +-- user-defined (DNS by name)",
    "    +-- host (no isolation)",
    "```",
    "",
    "---",
    "",
    "## How Docker Connects to Other Topics",
    "",
    "- **Kubernetes**: K8s orchestrates Docker containers at scale.",
    "  Every K8s pod runs container images built with Docker.",
    "- **CI/CD**: Pipelines build Docker images on every commit and push to a registry.",
    "- **Linux**: Containers ARE Linux processes. `docker exec -it` drops you into a",
    "  Linux shell. All Linux skills (permissions, processes, logs) apply inside containers.",
    "- **Microservices**: Docker enables each service to have its own isolated environment,",
    "  dependencies, and runtime — making microservice architectures practical.",
    "",
    "---",
    "",
    "## Common Beginner Mistakes",
    "",
    "1. **Running as root inside container** — use `USER appuser` in Dockerfile for security.",
    "2. **Storing secrets in Dockerfile or image** — they become visible in `docker history`.",
    "3. **Using `latest` tag in production** — `nginx:latest` changes over time, breaking reproducibility. Always pin versions: `nginx:1.25.3`.",
    "4. **Huge images** — use slim/alpine base images, multi-stage builds, add `.dockerignore`.",
    "5. **No `.dockerignore`** — COPY . . copies node_modules, .git, logs. Add `.dockerignore` like `.gitignore`.",
    "6. **Data loss** — removing a container without volumes deletes all its data.",
    "7. **Port conflicts** — two containers cannot bind the same host port. Use different host ports.",
    "",
    "---",
    "",
    "## References and Further Learning",
    "",
    "### Videos (Watch These!)",
    "- **Docker Tutorial for Beginners** by TechWorld with Nana:",
    "  https://www.youtube.com/watch?v=3c-iBn73dDE",
    "  - 3 hours. Covers containers, images, Dockerfile, Compose, volumes. Best beginner course.",
    "- **Docker in 100 Seconds** by Fireship:",
    "  https://www.youtube.com/watch?v=Gjnup-PuquQ",
    "  - 2 minutes. Perfect high-level mental model before going deep.",
    "",
    "### Free Books and Articles",
    "- **Docker official docs - Get Started guide**: https://docs.docker.com/get-started/",
    "  - Official beginner tutorial. Do Parts 1-5.",
    "- **Play with Docker** (free browser-based Docker lab): https://labs.play-with-docker.com/",
    "  - No installation needed. Spin up Linux VMs with Docker in browser.",
    "",
    "### Diagrams and Cheatsheets",
    "- **Docker Cheatsheet by wsargent**: https://github.com/wsargent/docker-cheat-sheet",
    "  - Comprehensive command reference with explanations.",
    "- **Container vs VM diagram**: search 'Docker vs VM architecture diagram' on Google Images.",
    "",
    "### Practice",
    "- **KodeKloud Docker for Beginners** (free course with browser labs):",
    "  https://kodekloud.com/courses/docker-for-the-absolute-beginner/",
    "- **DockerLabs**: https://dockerlabs.collabnix.com/",
    "  - 100+ hands-on labs from beginner to advanced.",
]

DOCKER_GUIDE = "\n".join(lines)

# ── QUESTIONS ─────────────────────────────────────────────────────────────────
NEW_QUESTIONS = [
    {"id":"dkr-q4","type":"mcq",
     "prompt":"What is the difference between a Docker image and a container?",
     "choices":["They are the same thing","An image is a read-only blueprint; a container is a running instance of that image","A container is read-only; an image is running","Images run on VMs; containers run on bare metal"],
     "answerIndex":1,"explanation":"Image = static blueprint stored on disk (like a class). Container = live running instance of that image (like an object). You can run many containers from one image.","tags":["docker-basics","image"]},
    {"id":"dkr-q5","type":"mcq",
     "prompt":"What does `docker run -d -p 8080:80 nginx` do?",
     "choices":["Runs nginx in foreground on port 80","Runs nginx detached in background, maps host port 8080 to container port 80","Runs nginx on port 8080 inside the container","Downloads nginx without running it"],
     "answerIndex":1,"explanation":"-d = detached (background). -p 8080:80 maps host port 8080 to container port 80. Accessing localhost:8080 on the host reaches nginx inside the container.","tags":["docker-run","ports"]},
    {"id":"dkr-q6","type":"mcq",
     "prompt":"Which Dockerfile instruction runs a command AT BUILD TIME (not at container start)?",
     "choices":["CMD","ENTRYPOINT","RUN","EXEC"],
     "answerIndex":2,"explanation":"RUN executes during image build (e.g. apt install, mvn package). CMD and ENTRYPOINT define what runs when the container starts. EXEC is not a Dockerfile instruction.","tags":["dockerfile","layers"]},
    {"id":"dkr-q7","type":"mcq",
     "prompt":"You want your Spring Boot container to persist database files after the container is removed. What should you use?",
     "choices":["COPY instruction","docker exec","Docker volume","Multi-stage build"],
     "answerIndex":2,"explanation":"Volumes persist data outside the container lifecycle. When the container is removed, the volume data survives. COPY, exec, and multi-stage are unrelated to data persistence.","tags":["volumes","persistence"]},
    {"id":"dkr-q8","type":"mcq",
     "prompt":"What does `docker exec -it myapp bash` do?",
     "choices":["Builds the myapp image","Starts a new container from myapp","Opens an interactive bash shell INSIDE the running myapp container","Stops the myapp container"],
     "answerIndex":2,"explanation":"exec runs a command inside an ALREADY RUNNING container. -it = interactive terminal. This is how you 'SSH into' a container to debug it.","tags":["docker-exec","debugging"]},
    {"id":"dkr-q9","type":"mcq",
     "prompt":"What is the primary benefit of Docker multi-stage builds?",
     "choices":["Faster runtime performance","Smaller production images by excluding build tools and source code","Automatic scaling","Better networking"],
     "answerIndex":1,"explanation":"Multi-stage builds let you compile in a large image (with Maven/npm etc.) and copy only the output artifact to a lean runtime image. Result: images shrink from ~800MB to ~180MB.","tags":["dockerfile","multi-stage"]},
    {"id":"dkr-q10","type":"mcq",
     "prompt":"Why should you add a `.dockerignore` file to your project?",
     "choices":["It speeds up container networking","It prevents COPY . . from including node_modules, .git, logs in the image — keeping images small and secure","It's required for docker-compose","It sets environment variables"],
     "answerIndex":1,"explanation":".dockerignore works like .gitignore — it excludes files from the build context sent to Docker daemon. Without it, COPY . . includes node_modules (hundreds of MB), .git history, and local config files.","tags":["dockerfile","best-practices"]},
    {"id":"dkr-q11","type":"mcq",
     "prompt":"In docker-compose, services in the same user-defined network reach each other by:",
     "choices":["IP addresses only","Their service names (Docker DNS resolves them automatically)","Port numbers","Container IDs"],
     "answerIndex":1,"explanation":"Docker Compose creates a network where services discover each other by service name. app can connect to db:5432 and Docker DNS resolves 'db' to the database container's IP.","tags":["compose","networking"]},
    {"id":"dkr-q12","type":"mcq",
     "prompt":"What happens to data inside a container when you run `docker rm mycontainer`?",
     "choices":["Data is automatically backed up","Data persists in the image","Data is permanently lost unless stored in a volume or bind mount","Data moves to /tmp on the host"],
     "answerIndex":2,"explanation":"Containers are ephemeral. Their writable layer is deleted with the container. Only data in volumes or bind mounts persists. This is why databases must use volumes.","tags":["volumes","containers"]},
    {"id":"dkr-q13","type":"mcq",
     "prompt":"Which base image choice results in the smallest production image?",
     "choices":["ubuntu:22.04","openjdk:17","openjdk:17-slim or eclipse-temurin:17-alpine","debian:latest"],
     "answerIndex":2,"explanation":"slim and alpine variants strip out non-essential packages. Alpine Linux is ~5MB vs ubuntu at ~70MB. openjdk:17-slim is ~250MB vs openjdk:17 at ~470MB.","tags":["dockerfile","image-size"]},
    {"id":"dkr-q14","type":"codeOutput",
     "prompt":"What does this command output?",
     "code":"docker ps -a | grep Exited | wc -l",
     "choices":["Number of running containers","Number of all containers","Number of stopped (Exited) containers","Error — invalid syntax"],
     "answerIndex":2,"explanation":"docker ps -a lists all containers including stopped. grep Exited filters only stopped ones. wc -l counts matching lines. Result = count of stopped containers.","tags":["docker-commands","pipes"]},
    {"id":"dkr-q15","type":"mcq",
     "prompt":"You hardcode `ENV DB_PASSWORD=mypassword` in your Dockerfile. What is the security risk?",
     "choices":["No risk — env vars are encrypted in images","The password is visible via `docker history` and to anyone who has the image","It causes a build error","The container cannot start"],
     "answerIndex":1,"explanation":"docker history shows every layer including ENV instructions in plain text. Anyone with access to the image can read the password. Always pass secrets via -e flag or --env-file at runtime.","tags":["security","dockerfile"]},
    {"id":"dkr-q16","type":"mcq",
     "prompt":"What is the correct Dockerfile instruction order for maximum layer cache efficiency in a Java project?",
     "choices":["COPY src -> RUN mvn install -> COPY pom.xml","COPY pom.xml -> RUN mvn dependency:go-offline -> COPY src -> RUN mvn package","COPY . . -> RUN mvn package","RUN mvn package -> COPY . ."],
     "answerIndex":1,"explanation":"pom.xml changes rarely, so its layer is cached. Dependencies download once. Source code changes frequently, so it goes last. If only src changes, only the last two layers rebuild — much faster.","tags":["dockerfile","layer-cache"]},
    {"id":"dkr-q17","type":"multi",
     "prompt":"Which of these should you include in a `.dockerignore` file? (Select all that apply)",
     "choices":["node_modules/",".git/",".env","src/main/java/"],
     "answerIndexes":[0,1,2],"explanation":"node_modules (huge), .git (exposes history), .env (contains secrets) should all be ignored. Source code (src/) must be included for the build to work.","tags":["dockerfile","security"]},
    {"id":"dkr-q18","type":"mcq",
     "prompt":"What does `docker compose down -v` do differently than `docker compose down`?",
     "choices":["They are identical","down -v also removes named volumes defined in compose file — deletes persistent data","down -v removes all images","down -v is faster"],
     "answerIndex":1,"explanation":"docker compose down stops and removes containers and networks. -v additionally removes named volumes. This deletes database data, uploaded files etc. Use with caution in production.","tags":["compose","volumes"]},
    {"id":"dkr-q19","type":"mcq",
     "prompt":"In a Dockerfile, what is the difference between CMD and ENTRYPOINT?",
     "choices":["CMD runs at build time; ENTRYPOINT at runtime","ENTRYPOINT = fixed command (hard to override); CMD = default arguments (easy to override)","They are identical","ENTRYPOINT is for Linux only"],
     "answerIndex":1,"explanation":"ENTRYPOINT sets the main executable — it runs every time. CMD provides default arguments to ENTRYPOINT, easily overridden. Together: ENTRYPOINT=[java -jar] CMD=[app.jar] allows: docker run myapp different.jar","tags":["dockerfile","cmd-entrypoint"]},
    {"id":"dkr-q20","type":"mcq",
     "prompt":"Why should you avoid using `image:latest` tag in production deployments?",
     "choices":["latest is too large","latest is not cached","latest points to whatever the newest version is — it changes over time, making deployments non-reproducible and breaking things unexpectedly","latest requires internet access"],
     "answerIndex":2,"explanation":"latest is a moving target. nginx:latest today might be 1.25, tomorrow 1.26 with breaking changes. Always pin: nginx:1.25.3. Your production config should be immutable and reproducible.","tags":["best-practices","tags"]},
]

# ── FLASHCARDS ─────────────────────────────────────────────────────────────────
NEW_FLASHCARDS = [
    {"id":"dkr-fc5","front":"docker run flags: -d -p -v -e --name","back":"-d=detached(background)  -p host:container port mapping  -v volume/bind mount  -e environment variable  --name give container a name","tags":["docker-run"]},
    {"id":"dkr-fc6","front":"Layer cache order rule","back":"Put rarely-changing steps first (COPY pom.xml, RUN mvn dependency:go-offline), frequently-changing steps last (COPY src, RUN mvn package). Any changed layer invalidates all subsequent layers.","tags":["dockerfile","performance"]},
    {"id":"dkr-fc7","front":"Container data persistence rule","back":"Containers are ephemeral — data inside is gone on rm. Use named volumes for databases/state. Use bind mounts in development for live code. Never rely on container filesystem for important data.","tags":["volumes","data"]},
    {"id":"dkr-fc8","front":"Secrets in Docker — the rule","back":"Never put secrets in Dockerfile ENV or image layers. Pass at runtime: docker run -e KEY=val or --env-file .env. Use Docker Secrets or AWS Secrets Manager in production. docker history reveals all image layers.","tags":["security","secrets"]},
]

# ── WRITE ──────────────────────────────────────────────────────────────────────
d['guide'] = DOCKER_GUIDE

existing_q_ids = {q['id'] for q in d['questions']}
for q in NEW_QUESTIONS:
    if q['id'] not in existing_q_ids:
        d['questions'].append(q)

existing_fc_ids = {fc['id'] for fc in d['flashcards']}
for fc in NEW_FLASHCARDS:
    if fc['id'] not in existing_fc_ids:
        d['flashcards'].append(fc)

with open(p, 'w') as f:
    json.dump(d, f, indent=2, ensure_ascii=False)

print(f"docker.json done!")
print(f"  Guide: {len(DOCKER_GUIDE)} chars")
print(f"  Questions: {len(d['questions'])}")
print(f"  Flashcards: {len(d['flashcards'])}")
print(f"  YouTube: {'youtube.com' in DOCKER_GUIDE}")
print(f"  References: {'References' in DOCKER_GUIDE}")

