import json
from pathlib import Path

p = Path('/Users/eptr6dj/IdeaProjects/master-cs/cs-mastery/src/content/topics/cloud-devops/aws-sqs.json')
d = json.loads(p.read_text())

GUIDE = "\n".join([
    "# AWS SQS — Simple Queue Service",
    "",
    "## What Is a Message Queue? (Start From Zero)",
    "",
    "Imagine a busy coffee shop. Customers walk in and place orders. If the barista had to",
    "serve each customer instantly with no waiting — one slow customer blocks everyone else.",
    "Instead: customers place orders at the register (a queue), the order ticket goes on a",
    "board, and baristas pick up tickets when they are ready. The register does not wait",
    "for the coffee to be made before taking the next order.",
    "",
    "A **message queue** does the same for software services.",
    "",
    "**Without a queue (tight coupling):**",
    "```",
    "User clicks 'Place Order'",
    "    |",
    "    v",
    "Order Service calls Payment Service directly",
    "    |",
    "    | (waits synchronously)",
    "    v",
    "Payment Service calls Email Service directly",
    "    |",
    "    | (waits synchronously)",
    "    v",
    "Response returned to user",
    "",
    "Problem: if Email Service is slow or down, the user waits. If Payment Service is",
    "overwhelmed (Black Friday spike), Order Service fails too.",
    "```",
    "",
    "**With SQS (loose coupling):**",
    "```",
    "User clicks 'Place Order'",
    "    |",
    "    v",
    "Order Service puts message in SQS queue",
    "    |",
    "    v (immediate response to user: 'Order received!')",
    "User gets response",
    "",
    "Meanwhile, asynchronously:",
    "SQS queue -> Payment Service picks up message, processes it",
    "SQS queue -> Email Service picks up message, sends confirmation",
    "",
    "If Email Service crashes: message stays in queue, retried when it recovers.",
    "Spike of 10,000 orders: queue absorbs all of them, workers process at their pace.",
    "```",
    "",
    "---",
    "",
    "## SQS Core Concepts",
    "",
    "```",
    "PRODUCER:  Service that sends messages to the queue",
    "           (your Order Service)",
    "",
    "MESSAGE:   JSON payload, up to 256KB",
    "           {orderId: 'abc123', userId: 'u456', amount: 49.99}",
    "",
    "QUEUE:     Durable buffer storing messages until consumed",
    "           Messages can wait from seconds to 14 days",
    "",
    "CONSUMER:  Service that reads (polls) messages from the queue",
    "           (your Payment Service, Email Service)",
    "",
    "VISIBILITY TIMEOUT:",
    "   When consumer picks up a message, it becomes INVISIBLE to other consumers.",
    "   If consumer processes successfully: deletes the message (gone forever).",
    "   If consumer crashes (no delete): timeout expires, message reappears for retry.",
    "",
    "Message lifecycle:",
    "  SENT -> [Queue] -> RECEIVED (invisible for 30s default) -> DELETED",
    "                                         |",
    "                              (crash, no delete)",
    "                                         v",
    "                              Reappears after visibility timeout",
    "                              Retried by another consumer",
    "```",
    "",
    "---",
    "",
    "## Standard Queue vs FIFO Queue",
    "",
    "```",
    "+------------------+----------------------------+----------------------------+",
    "| Feature          | Standard Queue             | FIFO Queue                 |",
    "+------------------+----------------------------+----------------------------+",
    "| Ordering         | Best-effort ordering       | Strict FIFO (guaranteed)   |",
    "| Delivery         | At-least-once (duplicates) | Exactly-once processing    |",
    "| Throughput       | Unlimited (~infinite)      | Up to 3000 msg/sec         |",
    "| Use case         | Most tasks (email, logs)   | Financial txns, ordering   |",
    "| Naming           | any-name                   | must end in .fifo          |",
    "+------------------+----------------------------+----------------------------+",
    "",
    "Standard: A message MIGHT be delivered twice (at-least-once).",
    "  Your consumer MUST be idempotent (safe to process twice).",
    "",
    "FIFO: Message delivered exactly once in the order sent.",
    "  Use for: bank transfers, inventory updates, anything where order matters.",
    "",
    "When to use which:",
    "  Standard: sending emails (duplicate = extra email, annoying but ok)",
    "  FIFO:     charging a credit card (duplicate = double charge, unacceptable)",
    "```",
    "",
    "---",
    "",
    "## Key SQS Settings",
    "",
    "```",
    "VISIBILITY TIMEOUT (default: 30 seconds):",
    "  Time a message is invisible after being received.",
    "  Set to > your max processing time.",
    "  If processing takes 2 min but timeout is 30s: message reappears, processed twice!",
    "  Rule: set visibility timeout = 6x your average processing time.",
    "",
    "MESSAGE RETENTION PERIOD (default: 4 days, max: 14 days):",
    "  How long unprocessed messages stay in the queue.",
    "  After this period, messages are automatically deleted.",
    "",
    "MESSAGE SIZE (max: 256KB):",
    "  For larger payloads: store data in S3, send only the S3 key in SQS.",
    "  SQS Extended Client Library (Java/Python) handles this pattern.",
    "",
    "DELIVERY DELAY (default: 0, max: 15 minutes):",
    "  Messages become invisible for N seconds after sent.",
    "  Use: delay an action (send invoice email 5 min after order).",
    "",
    "LONG POLLING vs SHORT POLLING:",
    "  Short polling: consumer calls ReceiveMessage, AWS checks a subset of servers.",
    "                 May return empty even if messages exist. More API calls = higher cost.",
    "  Long polling:  consumer waits up to 20 seconds for a message to arrive.",
    "                 Fewer empty responses. Lower cost. Use long polling (WaitTimeSeconds=20).",
    "```",
    "",
    "---",
    "",
    "## Dead Letter Queue (DLQ)",
    "",
    "```",
    "WHAT IS A DLQ?",
    "  A separate SQS queue for messages that fail processing repeatedly.",
    "  Instead of retrying forever, after N failures the message goes to the DLQ.",
    "",
    "WHY USE IT?",
    "  Without DLQ: a poison pill message (one your code cannot process) retries",
    "  forever, blocking other messages and generating noise in logs.",
    "  With DLQ: poison pill is isolated, other messages are unaffected.",
    "",
    "SETUP:",
    "  Create a separate SQS queue: my-queue-dlq",
    "  Set on main queue: Redrive Policy:",
    "    maxReceiveCount: 3   (fail 3 times -> move to DLQ)",
    "    deadLetterTargetArn: arn:...:my-queue-dlq",
    "",
    "WORKFLOW:",
    "  Message arrives -> Consumer processes -> FAILS",
    "  Message reappears (visibility timeout expires)",
    "  Consumer tries again -> FAILS (receive count = 2)",
    "  Consumer tries again -> FAILS (receive count = 3 = maxReceiveCount)",
    "  Message moves to DLQ -> alert fires -> engineer investigates",
    "",
    "WHAT TO DO WITH DLQ MESSAGES?",
    "  - Investigate root cause (bad data? bug in consumer?)",
    "  - Fix the bug",
    "  - Replay messages back to main queue",
    "  - AWS Console: DLQ Redrive feature does this automatically",
    "```",
    "",
    "---",
    "",
    "## Lambda + SQS — The Most Common Pattern",
    "",
    "```",
    "Lambda can consume SQS messages as an event source mapping.",
    "Lambda polls the queue automatically — you don't write polling code.",
    "",
    "Architecture:",
    "  Producer -> SQS Queue -> Lambda (auto-scales with queue depth)",
    "",
    "Event source mapping behaviour:",
    "  Lambda polls the queue in batches (default: 10 messages per invocation)",
    "  If Lambda succeeds: SQS deletes all messages in the batch",
    "  If Lambda fails: ALL messages in batch reappear (retry)",
    "",
    "BATCH SIZE:",
    "  Small batch (1): easy partial failure handling, more Lambda invocations",
    "  Large batch (10): fewer invocations (cheaper), harder partial failure",
    "",
    "PARTIAL BATCH FAILURE:",
    "  Lambda processes messages 1-10. Message 7 fails. Others succeed.",
    "  Without partial failure handling: all 10 retry (messages 1-6, 8-10 re-processed!)",
    "  With batchItemFailures response: return only failed message IDs to retry:",
    "",
    "  def handler(event, context):",
    "      failures = []",
    "      for record in event['Records']:",
    "          try:",
    "              process(record)",
    "          except Exception as e:",
    "              failures.append({'itemIdentifier': record['messageId']})",
    "      return {'batchItemFailures': failures}",
    "",
    "Concurrency:",
    "  Lambda scales one concurrent execution per active message group (FIFO)",
    "  or up to 1000 concurrency for standard queues.",
    "  Set Lambda reserved concurrency to cap downstream DB load.",
    "```",
    "",
    "---",
    "",
    "## SQS vs SNS vs EventBridge",
    "",
    "```",
    "+------------------+----------------------+------------------------+",
    "| Feature          | SQS                  | SNS                    |",
    "+------------------+----------------------+------------------------+",
    "| Model            | Queue (pull-based)   | Topic (push-based)     |",
    "| Consumers        | One consumer group   | Multiple subscribers   |",
    "| Persistence      | Messages wait        | Fire and forget        |",
    "| Retry            | Built-in (visibility)| No retry by default    |",
    "| Use case         | Work queue           | Fan-out notifications  |",
    "+------------------+----------------------+------------------------+",
    "",
    "COMMON PATTERN: SNS + SQS fan-out:",
    "  OrderPlaced event -> SNS topic",
    "  SNS fans out to:",
    "    SQS queue 1 -> Email Lambda (send confirmation)",
    "    SQS queue 2 -> Inventory Lambda (reserve stock)",
    "    SQS queue 3 -> Analytics Lambda (record sale)",
    "  Each service gets its own queue, processes independently.",
    "  One service slow/down doesn't affect others.",
    "",
    "EventBridge vs SQS:",
    "  SQS: work queue, exact delivery, backpressure, retry, DLQ",
    "  EventBridge: event routing with rules, multiple targets, schema registry",
    "  Use SQS for work distribution, EventBridge for event-driven reactions",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "AWS SQS",
    "|",
    "+-- CORE CONCEPTS",
    "|   +-- Producer sends messages",
    "|   +-- Queue buffers messages",
    "|   +-- Consumer polls and deletes",
    "|   +-- Visibility timeout = processing lease",
    "|",
    "+-- QUEUE TYPES",
    "|   +-- Standard: high throughput, at-least-once, best-effort order",
    "|   +-- FIFO: strictly ordered, exactly-once, lower throughput",
    "|",
    "+-- KEY SETTINGS",
    "|   +-- Visibility timeout (>6x processing time)",
    "|   +-- Message retention (4 days default, 14 max)",
    "|   +-- Long polling (WaitTimeSeconds=20)",
    "|   +-- Delivery delay",
    "|",
    "+-- DLQ",
    "|   +-- maxReceiveCount retries then -> DLQ",
    "|   +-- Isolates poison pill messages",
    "|   +-- DLQ Redrive to replay fixed messages",
    "|",
    "+-- LAMBDA INTEGRATION",
    "|   +-- Event source mapping (auto-poll + scale)",
    "|   +-- Batch size (1-10000)",
    "|   +-- Partial batch failure response",
    "|",
    "+-- PATTERNS",
    "    +-- Work queue (producer -> SQS -> Lambda workers)",
    "    +-- Fan-out (SNS -> multiple SQS -> multiple Lambdas)",
    "    +-- Backpressure buffer (absorb traffic spikes)",
    "```",
    "",
    "---",
    "",
    "## How SQS Connects to Other Topics",
    "",
    "- **Lambda**: Lambda's event source mapping consumes SQS automatically.",
    "  Lambda + SQS is the most common async processing pattern in serverless.",
    "- **SNS**: SNS fan-out -> SQS queues = multiple independent consumers of same event.",
    "- **Serverless Patterns**: SQS absorbs traffic spikes, Lambda workers scale to drain queue.",
    "- **Kafka vs SQS**: Kafka retains messages for days and supports replay.",
    "  SQS is simpler (managed, no cluster), Kafka is more powerful for streaming.",
    "",
    "---",
    "",
    "## Common Beginner Mistakes",
    "",
    "1. **Visibility timeout too short** — message reappears while still being processed -> double processing.",
    "2. **No DLQ** — poison pill messages retry forever, filling logs and blocking workers.",
    "3. **Not using long polling** — short polling wastes API calls and costs more.",
    "4. **FIFO when not needed** — FIFO has lower throughput limits. Use Standard unless order/deduplication is required.",
    "5. **Large messages in SQS** — 256KB limit. Store large payloads in S3, send S3 key in SQS.",
    "6. **Not handling partial batch failure** — one bad message in batch causes all messages to retry.",
    "7. **Assuming Standard queue deduplicates** — it does NOT. Your consumer must be idempotent.",
    "",
    "---",
    "",
    "## References and Further Learning",
    "",
    "### Videos (Watch These!)",
    "- **Amazon SQS Tutorial** by TechWorld with Nana:",
    "  https://www.youtube.com/watch?v=CyYZ3adwboc",
    "  - 45 minutes. SQS concepts, demo, Lambda integration.",
    "- **SQS vs SNS vs EventBridge** by Be A Better Dev:",
    "  https://www.youtube.com/watch?v=RoKAEzdcr7k",
    "  - Clear comparison of the three AWS messaging services.",
    "",
    "### Free Books and Articles",
    "- **AWS SQS Developer Guide**: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/",
    "- **Lambda + SQS event source mapping**: https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html",
    "",
    "### Diagrams",
    "- **SNS + SQS fan-out diagram**: search 'AWS SNS SQS fan-out diagram' on Google Images",
    "",
    "### Practice",
    "- **AWS Free Tier**: SQS is free for first million requests/month. Build and test locally.",
    "- **LocalStack**: https://localstack.cloud/ — run AWS services locally including SQS.",
])

NEW_Q = [
    {"id":"aws-sqs-q1-real","type":"mcq","prompt":"What problem does SQS solve in a microservices architecture?",
     "choices":["Stores application code","Provides a managed message queue that decouples producers from consumers — producers send at their pace, consumers process at their pace, no direct dependency",
                "Hosts Lambda functions","Manages IAM policies"],
     "answerIndex":1,"explanation":"SQS decouples services. Producer (Order Service) sends to queue and returns immediately. Consumer (Payment Service) processes when ready. If consumer is slow or down, messages wait in queue rather than failing the producer.","tags":["sqs","decoupling"]},
    {"id":"aws-sqs-q2-real","type":"mcq","prompt":"What is the SQS visibility timeout?",
     "choices":["How long messages are retained in the queue","The time a received message is hidden from other consumers while being processed — prevents duplicate processing",
                "The delay before a message is delivered","Maximum message size"],
     "answerIndex":1,"explanation":"When consumer A receives a message, it becomes invisible for the visibility timeout period. If A processes and deletes it before timeout: gone. If A crashes: timeout expires, message reappears for consumer B to retry.","tags":["sqs","visibility-timeout"]},
    {"id":"aws-sqs-q3-real","type":"mcq","prompt":"Standard SQS queue guarantees 'at-least-once delivery'. What does this mean for your consumer?",
     "choices":["Messages are never delivered twice","Your consumer must be idempotent — the same message may be delivered more than once and processing it twice must produce the same result",
                "Messages are guaranteed to arrive in order","You must acknowledge each message twice"],
     "answerIndex":1,"explanation":"Standard SQS can deliver duplicates. A consumer processing 'charge user $10' twice would double-charge. Idempotent design: check if this requestId was already processed. If yes, skip. FIFO queues offer exactly-once delivery.","tags":["sqs","at-least-once","idempotency"]},
    {"id":"aws-sqs-q4-real","type":"mcq","prompt":"When should you use a FIFO queue instead of a Standard queue?",
     "choices":["When you need maximum throughput","When message order and exactly-once delivery are required — financial transactions, ordered inventory updates",
                "For large messages","FIFO is always better"],
     "answerIndex":1,"explanation":"FIFO queues guarantee ordering and exactly-once delivery but cap at 3000 msg/sec. Standard handles virtually unlimited throughput but may deliver out of order and duplicate. Choose FIFO only when order/dedup are business requirements.","tags":["sqs","fifo","standard"]},
    {"id":"aws-sqs-q5-real","type":"mcq","prompt":"What is a Dead Letter Queue (DLQ)?",
     "choices":["A queue for low-priority messages","A queue that receives messages which have failed processing maxReceiveCount times — isolates poison pill messages and prevents infinite retry loops",
                "A backup queue","Queue for deleted messages"],
     "answerIndex":1,"explanation":"DLQ catches messages that repeatedly fail. After maxReceiveCount retries, the message moves to DLQ instead of retrying forever. Engineers investigate, fix the bug, and replay messages from DLQ.","tags":["sqs","dlq"]},
    {"id":"aws-sqs-q6-real","type":"mcq","prompt":"Your SQS consumer takes 45 seconds to process a message. What visibility timeout should you set?",
     "choices":["30 seconds (default)","10 seconds","At least 270 seconds (6x processing time is the recommended minimum)",
                "180 seconds exactly"],
     "answerIndex":2,"explanation":"If visibility timeout < processing time, the message reappears before processing is done — another consumer picks it up = duplicate processing. Recommended: set to 6x average processing time. For 45s processing: 270s minimum.","tags":["sqs","visibility-timeout","configuration"]},
    {"id":"aws-sqs-q7-real","type":"mcq","prompt":"What is long polling in SQS?",
     "choices":["Waiting 24 hours for a message","Consumer waits up to 20 seconds for a message to arrive (WaitTimeSeconds=20) — reduces empty responses, fewer API calls, lower cost vs short polling",
                "Sending very long messages","Polling from multiple regions"],
     "answerIndex":1,"explanation":"Short polling returns immediately even if empty — many wasted API calls. Long polling waits up to 20 seconds before returning empty. Dramatically reduces costs for queues with low/intermittent traffic. Always use long polling.","tags":["sqs","long-polling"]},
    {"id":"aws-sqs-q8-real","type":"mcq","prompt":"What happens to messages that exceed the SQS message retention period?",
     "choices":["They are moved to S3","They are moved to DLQ","They are permanently deleted from the queue automatically",
                "They are archived"],
     "answerIndex":2,"explanation":"Default retention: 4 days. Maximum: 14 days. After retention period expires, messages are deleted regardless of whether they were consumed. Monitor queue depth to ensure consumers process faster than retention expires.","tags":["sqs","retention"]},
    {"id":"aws-sqs-q9-real","type":"mcq","prompt":"In the SNS + SQS fan-out pattern, what is the benefit of having one SQS queue per consumer?",
     "choices":["Reduces costs","Each consumer processes at its own pace independently — a slow Email service doesn't delay the Inventory service, and failures are isolated per service",
                "Increases message throughput","Required by AWS"],
     "answerIndex":1,"explanation":"SNS publishes to multiple SQS queues. Each queue serves one consumer service. Service A slow? Its queue backs up but doesn't affect Service B. Service B crashes? Its messages wait in queue until it recovers. Complete isolation.","tags":["sqs","sns","fan-out"]},
    {"id":"aws-sqs-q10-real","type":"mcq","prompt":"What is the maximum message size in SQS?",
     "choices":["64KB","1MB","256KB","10MB"],
     "answerIndex":2,"explanation":"SQS messages are limited to 256KB. For larger payloads (images, documents): store in S3, send only the S3 object key in the SQS message. The SQS Extended Client Library (Java/Python) handles this S3 offload pattern automatically.","tags":["sqs","limits"]},
    {"id":"aws-sqs-q11-real","type":"mcq","prompt":"When Lambda is configured with SQS as an event source, what happens if Lambda fails to process a message batch?",
     "choices":["Messages are deleted","Messages are immediately moved to DLQ","All messages in the batch return to the queue (visibility timeout expires) and become available for retry",
                "Lambda retries automatically without returning messages to queue"],
     "answerIndex":2,"explanation":"If Lambda throws an exception (or times out) while processing a batch, it does NOT delete the messages. After visibility timeout, all batch messages reappear. With partial batch failure response, only failed messages retry.","tags":["sqs","lambda","batch"]},
    {"id":"aws-sqs-q12-real","type":"mcq","prompt":"What is the purpose of the SQS message deduplication ID in FIFO queues?",
     "choices":["Authentication token","A unique ID for the message — within a 5-minute deduplication window, SQS ignores messages with the same ID, preventing duplicates",
                "Message ordering key","Consumer ID"],
     "answerIndex":1,"explanation":"FIFO queues use MessageDeduplicationId to prevent duplicates. If you send two messages with the same dedup ID within 5 minutes, only the first is delivered. Use a hash of the message content or a UUID generated once and stored.","tags":["sqs","fifo","deduplication"]},
    {"id":"aws-sqs-q13-real","type":"mcq","prompt":"What is SQS message group ID used for in FIFO queues?",
     "choices":["Authentication","Messages with the same group ID are processed in FIFO order with one consumer at a time — enables parallelism across groups while maintaining per-group ordering",
                "Message deduplication","Consumer targeting"],
     "answerIndex":1,"explanation":"MessageGroupId controls ordering scope. Group ID 'customer-123' ensures that customer's messages are ordered. Group ID 'customer-456' is handled independently in parallel. Without group IDs, all messages share one sequence (single consumer).","tags":["sqs","fifo","message-groups"]},
    {"id":"aws-sqs-q14-real","type":"mcq","prompt":"How does SQS help handle a traffic spike (e.g., Black Friday)?",
     "choices":["SQS rejects excess messages","SQS automatically scales the consumer service","SQS acts as a buffer — absorbs millions of messages instantly without dropping any, consumers drain the queue at their own rate rather than being overwhelmed",
                "SQS charges extra for spikes"],
     "answerIndex":2,"explanation":"SQS queue depth grows during a spike. Consumers process at their capacity. No messages lost, no consumer crashes from being overwhelmed. Lambda event source mapping also auto-scales consumers to drain the queue faster.","tags":["sqs","backpressure","scaling"]},
    {"id":"aws-sqs-q15-real","type":"mcq","prompt":"What is the delivery delay feature in SQS?",
     "choices":["How long it takes to deliver across regions","A configured delay (0-15 minutes) before a newly sent message becomes visible to consumers — useful for deferred processing",
                "Message retention period","DLQ retry delay"],
     "answerIndex":1,"explanation":"Delivery delay makes messages invisible for a specified time after they are sent. Use case: send order confirmation email 5 minutes after order placed, not immediately. Or: delay a retry after a known processing window.","tags":["sqs","delivery-delay"]},
    {"id":"aws-sqs-q16-real","type":"mcq","prompt":"What is the difference between SQS and Kafka for message queuing?",
     "choices":["They are identical","SQS: fully managed, messages deleted after consumption, simpler ops. Kafka: self-managed cluster, messages retained for replay, supports multiple consumer groups reading same data independently",
                "Kafka is always better","SQS handles more messages"],
     "answerIndex":1,"explanation":"SQS: AWS manages everything, messages consumed and gone, great for work queues. Kafka: you run the cluster, messages persist for days/weeks enabling replay and multiple independent consumers reading the same stream. Choose Kafka for event streaming, SQS for task queues.","tags":["sqs","kafka","comparison"]},
    {"id":"aws-sqs-q17-real","type":"mcq","prompt":"What is partial batch failure response in Lambda + SQS?",
     "choices":["Lambda rejecting the entire batch","Lambda returns a batchItemFailures list with only failed message IDs — SQS retries only those messages, successfully processed messages are deleted",
                "Lambda deleting all messages in batch","Lambda sending failed messages to SNS"],
     "answerIndex":1,"explanation":"Without partial failure: one bad message in a batch of 10 causes all 10 to retry — 9 messages re-processed unnecessarily. With batchItemFailures response: return only the failed messageId(s). SQS retries only those while deleting successful ones.","tags":["sqs","lambda","partial-failure"]},
    {"id":"aws-sqs-q18-real","type":"mcq","prompt":"How does Lambda auto-scaling work with an SQS event source mapping?",
     "choices":["Lambda doesn't auto-scale with SQS","Lambda scales one instance per message","Lambda poller scales Lambda concurrency based on queue depth — more messages in queue = more concurrent Lambda executions (up to account concurrency limit)",
                "You must manually configure auto-scaling"],
     "answerIndex":2,"explanation":"SQS event source mapping automatically scales Lambda. As queue depth grows, Lambda concurrency scales up to drain messages faster. As queue empties, concurrency scales back down. Scales to zero when queue is empty.","tags":["sqs","lambda","scaling"]},
    {"id":"aws-sqs-q19-real","type":"mcq","prompt":"What is the recommended way to monitor SQS queue health in production?",
     "choices":["Check AWS Console manually","Configure CloudWatch alarm on ApproximateNumberOfMessagesNotVisible and ApproximateAgeOfOldestMessage — alert if queue backs up or messages age too long",
                "Log every message","Use AWS X-Ray only"],
     "answerIndex":1,"explanation":"Key SQS CloudWatch metrics: ApproximateNumberOfMessages (depth), ApproximateAgeOfOldestMessage (how stale is oldest unprocessed message). Stale messages = consumer is stuck or dead. Set alarms on both for production queues.","tags":["sqs","monitoring","cloudwatch"]},
    {"id":"aws-sqs-q20-real","type":"mcq","prompt":"Why should you set Lambda reserved concurrency when using SQS as event source?",
     "choices":["To make Lambda run faster","Lambda can scale to account limits consuming SQS — without reserved concurrency, a spike could create thousands of Lambda executions that overwhelm downstream databases or APIs",
                "Required by SQS FIFO","To reduce costs only"],
     "answerIndex":1,"explanation":"Unconstrained Lambda + SQS = Lambda scales to 1000+ concurrent executions during a spike. Your RDS database has 100 connection limit. Result: connection pool exhaustion, database crash. Set reserved concurrency = your downstream capacity.","tags":["sqs","lambda","concurrency","backpressure"]},
]

NEW_FC = [
    {"id":"aws-sqs-fc1-real","front":"SQS visibility timeout rule","back":"Set to 6x your average processing time. Message in flight = invisible for this period. Too short = duplicate processing (message reappears while still being processed). Change during processing with ChangeMessageVisibility API.","tags":["sqs","visibility-timeout"]},
    {"id":"aws-sqs-fc2-real","front":"Standard vs FIFO queue choice","back":"Standard: unlimited throughput, at-least-once (may duplicate), best-effort ordering. FIFO: 3000/sec limit, exactly-once, strict order. Use Standard unless order or dedup is a business requirement (financial transactions = FIFO).","tags":["sqs","fifo","standard"]},
    {"id":"aws-sqs-fc3-real","front":"DLQ configuration","back":"Set maxReceiveCount = 3-5 on main queue. Create separate SQS as DLQ. After maxReceiveCount failures, message moves to DLQ. Alert on DLQ depth. Fix bug. Use DLQ Redrive to replay messages back to main queue.","tags":["sqs","dlq"]},
    {"id":"aws-sqs-fc4-real","front":"SNS + SQS fan-out pattern","back":"SNS topic receives event, fans out to N SQS queues. Each queue serves one independent consumer. Benefits: each service scales independently, failures are isolated, slow consumer doesn't block others. Default pattern for event-driven microservices.","tags":["sqs","sns","fan-out"]},
    {"id":"aws-sqs-fc5-real","front":"Lambda partial batch failure","back":"Return {batchItemFailures: [{itemIdentifier: failedMessageId}]}. SQS retries ONLY failed messages and deletes successful ones. Without this: entire batch retries when one message fails = 9 re-processed unnecessarily.","tags":["sqs","lambda","batch"]},
    {"id":"aws-sqs-fc6-real","front":"SQS long polling — always use it","back":"WaitTimeSeconds=20 in ReceiveMessage call. Waits up to 20s for a message. Compared to short polling: 99% fewer empty receives, lower cost, same latency. Turn on in queue settings (ReceiveMessageWaitTimeSeconds=20).","tags":["sqs","long-polling"]},
    {"id":"aws-sqs-fc7-real","front":"SQS max message size workaround","back":"SQS limit = 256KB. For large payloads: store in S3, put S3 object key in SQS message. Consumer reads key, fetches from S3. SQS Extended Client Library (Java/Python) automates this pattern transparently.","tags":["sqs","limits","s3"]},
    {"id":"aws-sqs-fc8-real","front":"SQS backpressure pattern","back":"Traffic spike: producer sends 100K messages faster than consumers can process. SQS absorbs all (no messages lost). Consumers drain at their pace. Lambda scales up to drain faster. Cap Lambda concurrency = protect downstream DB from connection storm.","tags":["sqs","backpressure","scaling"]},
]

d['guide'] = GUIDE
d['questions'] = NEW_Q
d['flashcards'] = NEW_FC

with open(p, 'w') as f:
    json.dump(d, f, indent=2, ensure_ascii=False)
print(f"aws-sqs.json done: guide={len(GUIDE)} q={len(d['questions'])} fc={len(d['flashcards'])}")

