import json
from pathlib import Path

p = Path('/Users/eptr6dj/IdeaProjects/master-cs/cs-mastery/src/content/topics/cloud-devops/serverless-patterns.json')
d = json.loads(p.read_text())

GUIDE = "\n".join([
    "# Serverless Patterns",
    "",
    "## What Is Serverless? (Start From Zero)",
    "",
    "The word 'serverless' is a bit misleading — there ARE servers, you just don't see them.",
    "What it really means: you write code (functions), upload it, and AWS runs it for you.",
    "You do not provision servers, patch OS, configure capacity, or pay for idle time.",
    "",
    "**Traditional server-based model:**",
    "```",
    "You:  rent an EC2 instance ($50/month)",
    "      configure the OS",
    "      deploy your app",
    "      pay $50 whether it gets 0 or 1 million requests",
    "      scale manually when traffic grows",
    "      wake up at 3am if the server crashes",
    "```",
    "",
    "**Serverless (Lambda) model:**",
    "```",
    "You:  write a function (50 lines of Python/Java/Node)",
    "      upload to Lambda",
    "      AWS runs it when triggered",
    "      pay ONLY per execution (first million requests/month FREE)",
    "      AWS scales automatically (0 to 10,000 concurrent in seconds)",
    "      AWS handles all failures and restarts",
    "```",
    "",
    "**Analogy:** Serverless is like a taxi vs owning a car.",
    "Owning a car (EC2): pay insurance, maintenance, fuel all the time — even when parked.",
    "Taxi (Lambda): pay only when you actually ride. Perfect for irregular trips.",
    "",
    "---",
    "",
    "## AWS Lambda — The Core Serverless Building Block",
    "",
    "Lambda is a Function-as-a-Service (FaaS). You provide a function, AWS runs it on demand.",
    "",
    "```",
    "Lambda function lifecycle:",
    "",
    "COLD START (first invocation or after idle period):",
    "  1. AWS allocates a container (VM slot)",
    "  2. Downloads your deployment package",
    "  3. Starts the runtime (JVM, Node, Python interpreter)",
    "  4. Runs initialisation code (outside handler)",
    "  5. Runs your handler function",
    "  Total: 100ms - 3 seconds depending on runtime + package size",
    "",
    "WARM INVOCATION (container reused):",
    "  1. Runs your handler function",
    "  Total: your actual code execution time only",
    "",
    "COLD START visual:",
    "  Request ---> [Cold: init container + runtime + code] ---> Response",
    "               |                                      |",
    "               |<-------- 1-3 seconds extra --------->|",
    "",
    "  Request ---> [Warm: just run handler] ---> Response",
    "               |                       |",
    "               |<--- milliseconds ----->|",
    "```",
    "",
    "**Lambda configuration basics:**",
    "```",
    "Memory:    128MB to 10,240MB  (CPU scales proportionally with memory)",
    "Timeout:   1 second to 15 minutes (max)",
    "Runtime:   Python 3.12, Node 20, Java 21, Go, etc.",
    "Package:   .zip file or container image (up to 10GB)",
    "",
    "# Python Lambda handler structure",
    "def handler(event, context):",
    "    # event = the trigger payload (S3 event, API Gateway request, etc.)",
    "    # context = metadata (function name, remaining time, request ID)",
    "",
    "    print(f'Processing event: {event}')",
    "",
    "    result = process(event['data'])",
    "",
    "    return {",
    "        'statusCode': 200,",
    "        'body': json.dumps({'result': result})",
    "    }",
    "```",
    "",
    "---",
    "",
    "## Lambda Triggers — What Can Invoke a Lambda?",
    "",
    "```",
    "Lambda is event-driven — something must trigger it.",
    "",
    "+------------------+--------------------------------------------+",
    "| Trigger          | Use case                                   |",
    "+------------------+--------------------------------------------+",
    "| API Gateway      | HTTP endpoint -> Lambda = REST API         |",
    "| S3               | File uploaded -> Lambda processes it       |",
    "| SQS              | Message in queue -> Lambda consumes it     |",
    "| SNS              | Notification published -> Lambda receives  |",
    "| DynamoDB Streams | DB record changed -> Lambda reacts         |",
    "| EventBridge      | Scheduled (cron) or custom events          |",
    "| Cognito          | User sign-up -> Lambda validates/enriches  |",
    "| CloudWatch       | Log pattern matched -> Lambda alerts       |",
    "+------------------+--------------------------------------------+",
    "",
    "PATTERN 1: HTTP API",
    "  Browser -> API Gateway -> Lambda -> DynamoDB -> Response",
    "",
    "PATTERN 2: File processing",
    "  Upload image to S3 -> S3 triggers Lambda -> Lambda resizes image -> saves to S3",
    "",
    "PATTERN 3: Queue worker",
    "  API writes message to SQS -> Lambda polls SQS -> Lambda processes message",
    "  (decoupled, retryable, handles bursts via queue buffering)",
    "",
    "PATTERN 4: Scheduled job",
    "  EventBridge cron: '0 2 * * *' -> Lambda runs daily at 2am -> sends report emails",
    "```",
    "",
    "---",
    "",
    "## API Gateway + Lambda — Building a REST API",
    "",
    "This is the most common serverless pattern: replace a traditional server with",
    "API Gateway (HTTP router) + Lambda (business logic).",
    "",
    "```",
    "Traditional:               Serverless:",
    "  EC2 running Spring Boot    API Gateway + Lambda",
    "  Always on = always paying  Pay per request",
    "  Manual scaling             Auto-scales to millions",
    "  You manage OS/runtime      Zero ops",
    "",
    "Architecture:",
    "  Client",
    "    |",
    "    | HTTPS request",
    "    v",
    "  API Gateway",
    "    | matches route: GET /users/{id}",
    "    v",
    "  Lambda function: getUserById",
    "    | queries",
    "    v",
    "  DynamoDB",
    "    |",
    "    v (response bubbles back up)",
    "  Client receives JSON response",
    "",
    "Terraform / SAM / CDK define both API Gateway and Lambda together.",
    "```",
    "",
    "---",
    "",
    "## Cold Start Problem — Causes and Solutions",
    "",
    "```",
    "WHY COLD STARTS HAPPEN:",
    "  Lambda containers are created on first request and reused for ~15 min.",
    "  After 15 min idle, container is recycled.",
    "  Next request creates a new container -> cold start again.",
    "",
    "COLD START DURATION BY RUNTIME:",
    "  Python/Node.js:  ~100-300ms   (fast startup, small runtime)",
    "  Java (JVM):      ~1-3 seconds (JVM startup is slow!)",
    "  Container image: up to 5-10s  (larger image = slower pull)",
    "",
    "SOLUTIONS:",
    "",
    "1. PROVISIONED CONCURRENCY:",
    "   Tell Lambda to keep N containers warm at all times.",
    "   Cost: you pay for idle warm containers.",
    "   Use for: user-facing APIs where latency matters.",
    "",
    "2. KEEP-ALIVE PING:",
    "   Schedule EventBridge to invoke Lambda every 5 minutes.",
    "   Free (Lambda gets ~1M free invocations/month).",
    "   Use for: low-traffic functions that must be fast occasionally.",
    "",
    "3. PACKAGE SIZE OPTIMISATION:",
    "   Smaller .zip = faster cold start.",
    "   Only include needed libraries.",
    "   Use Lambda Layers for shared dependencies.",
    "   Java: use GraalVM native image (compiles to native binary, no JVM startup).",
    "",
    "4. CHOOSE FAST RUNTIME:",
    "   For latency-sensitive APIs: Node.js or Python over Java.",
    "   Java is great for CPU-heavy batch work where cold start % is small.",
    "",
    "5. MEMORY SIZE:",
    "   More RAM = more CPU = faster init + execution.",
    "   1024MB often sweet spot: 2x memory, still cheaper than EC2.",
    "```",
    "",
    "---",
    "",
    "## Step Functions — Orchestrating Multiple Lambdas",
    "",
    "When your workflow needs multiple steps, conditional logic, retries, and parallelism,",
    "chaining Lambda A -> Lambda B in code is fragile.",
    "Step Functions is a visual state machine for orchestrating workflows.",
    "",
    "```",
    "WITHOUT Step Functions (Lambda chaining):",
    "  Lambda A calls Lambda B calls Lambda C",
    "  Problems:",
    "    - If Lambda B fails, who retries?",
    "    - If Lambda A times out waiting for B, what happens?",
    "    - How do you see what step failed?",
    "    - Nested timeouts: 15min max chains are hard",
    "",
    "WITH Step Functions:",
    "  Define states in JSON (Amazon States Language)",
    "  Step Functions engine manages transitions, retries, timeouts",
    "  Visual flow diagram in AWS Console",
    "  Full audit trail: see every step, input/output, error",
    "",
    "Example: Order Processing Workflow:",
    "  [ValidateOrder]",
    "       |",
    "  [ChargePayment] -- FAIL -> [RefundPayment]",
    "       |",
    "  [ReserveInventory] -- FAIL -> [RefundPayment]",
    "       |",
    "  [SendConfirmationEmail]",
    "       |",
    "  [Done]",
    "",
    "Each box is a Lambda function. Step Functions handles:",
    "  - Executing each step",
    "  - Catching errors (Catch states)",
    "  - Retrying with exponential backoff (Retry states)",
    "  - Parallel branches (Parallel state)",
    "  - Waiting for external events (Wait for Token pattern)",
    "```",
    "",
    "---",
    "",
    "## EventBridge — Cloud Event Bus",
    "",
    "```",
    "EventBridge is a serverless event bus — it routes events between services.",
    "",
    "SCHEDULED EVENTS (cron):",
    "  EventBridge rule: rate(1 hour) or cron(0 2 * * ? *)",
    "  Action: invoke Lambda function",
    "  Use: scheduled reports, cleanup jobs, notifications",
    "",
    "CUSTOM EVENTS (event-driven architecture):",
    "  Service A publishes event: {source: 'orders', detail-type: 'OrderPlaced', detail: {...}}",
    "  Rules match on event fields",
    "  Multiple targets can receive same event:",
    "    -> Lambda: process fraud check",
    "    -> SQS: queue for email service",
    "    -> Step Functions: start workflow",
    "",
    "Benefits:",
    "  - Services don't need to know about each other (loose coupling)",
    "  - Add new consumers without modifying publishers",
    "  - Built-in retry with DLQ (dead letter queue)",
    "  - Schema registry to document event shapes",
    "```",
    "",
    "---",
    "",
    "## Lambda Best Practices",
    "",
    "```",
    "1. KEEP FUNCTIONS SMALL AND SINGLE-PURPOSE:",
    "   One Lambda = one responsibility.",
    "   getUserById, processPayment, sendEmail — separate functions.",
    "   Not: doEverything.",
    "",
    "2. STORE STATE EXTERNALLY:",
    "   Lambda is stateless — containers can be recycled any time.",
    "   Store state in DynamoDB, S3, ElastiCache — NOT in Lambda global variables.",
    "   Global variables persist ACROSS warm invocations — can cause bugs!",
    "   (Exception: connection pooling: keep DB connection in global = fine.)",
    "",
    "3. SET APPROPRIATE TIMEOUT:",
    "   Default: 3 seconds. Know your max expected execution time.",
    "   Too low = functions killed mid-execution.",
    "   Too high = runaway functions run up your bill.",
    "",
    "4. ENVIRONMENT VARIABLES FOR CONFIG:",
    "   DB_URL, TABLE_NAME, REGION — never hardcode.",
    "   Use Systems Manager Parameter Store or Secrets Manager for secrets.",
    "",
    "5. USE LAMBDA LAYERS FOR SHARED CODE:",
    "   Common libraries (pandas, numpy, shared utils) as a Layer.",
    "   Multiple functions share one Layer — update once, applies everywhere.",
    "",
    "6. IDEMPOTENCY:",
    "   Lambda can be invoked more than once for the same event (retries).",
    "   Your handler must produce same result if called twice.",
    "   Use idempotency keys: check if already processed before doing work.",
    "",
    "7. DEAD LETTER QUEUES (DLQ):",
    "   Configure SQS or SNS as DLQ for failed Lambda invocations.",
    "   Failed events are not lost — they go to DLQ for investigation/replay.",
    "```",
    "",
    "---",
    "",
    "## Serverless Application Model (SAM)",
    "",
    "```",
    "SAM is AWS's framework for building serverless apps locally and deploying them.",
    "It extends CloudFormation with serverless-specific resources.",
    "",
    "# template.yaml",
    "AWSTemplateFormatVersion: '2010-09-09'",
    "Transform: AWS::Serverless-2016-10-31",
    "",
    "Resources:",
    "  GetUserFunction:",
    "    Type: AWS::Serverless::Function",
    "    Properties:",
    "      Handler: src/handlers/getUser.handler",
    "      Runtime: python3.12",
    "      MemorySize: 512",
    "      Timeout: 10",
    "      Events:",
    "        GetUser:",
    "          Type: Api",
    "          Properties:",
    "            Path: /users/{id}",
    "            Method: GET",
    "      Environment:",
    "        Variables:",
    "          USERS_TABLE: !Ref UsersTable",
    "",
    "  UsersTable:",
    "    Type: AWS::Serverless::SimpleTable",
    "    Properties:",
    "      PrimaryKey:",
    "        Name: userId",
    "        Type: String",
    "",
    "# Commands:",
    "sam build              # build deployment package",
    "sam local invoke       # test Lambda locally",
    "sam local start-api    # run API Gateway locally on port 3000",
    "sam deploy --guided    # deploy to AWS",
    "```",
    "",
    "---",
    "",
    "## Serverless vs Containers vs EC2 — When to Use Each",
    "",
    "```",
    "+------------------+----------------------+----------------------------+",
    "| Factor           | Lambda (Serverless)  | Container/EC2              |",
    "+------------------+----------------------+----------------------------+",
    "| Startup time     | 100ms-3s cold start  | Always warm                |",
    "| Max runtime      | 15 minutes           | Unlimited                  |",
    "| Cost model       | Per request          | Per hour (even idle)       |",
    "| State            | Stateless            | Can be stateful            |",
    "| Cold start       | Yes (mitigable)      | No                         |",
    "| Scaling          | Automatic (fast)     | Manual or HPA (slower)     |",
    "| Ops overhead     | Near zero            | OS patching, monitoring    |",
    "+------------------+----------------------+----------------------------+",
    "",
    "USE LAMBDA WHEN:",
    "  - Sporadic/unpredictable traffic",
    "  - Event-driven triggers (S3 upload, queue message)",
    "  - Short-duration tasks (under 15 min)",
    "  - Rapid prototyping",
    "  - Budget-sensitive (pay per use)",
    "",
    "AVOID LAMBDA WHEN:",
    "  - Long-running jobs (>15 min) -> use ECS Fargate",
    "  - Latency-critical API with consistent traffic -> EC2/ECS cheaper",
    "  - Large ML models that need specialised hardware -> SageMaker",
    "  - Complex stateful workflows -> Step Functions + ECS",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "SERVERLESS PATTERNS",
    "|",
    "+-- LAMBDA",
    "|   +-- FaaS: pay per execution",
    "|   +-- Triggers: API GW, S3, SQS, EventBridge, cron",
    "|   +-- Cold start: init overhead (worst on JVM)",
    "|   +-- Handler: event + context -> response",
    "|   +-- Stateless: store state externally",
    "|",
    "+-- API GATEWAY + LAMBDA",
    "|   +-- Replace traditional server",
    "|   +-- Route -> Lambda -> DynamoDB",
    "|   +-- Pay per request, auto-scale",
    "|",
    "+-- STEP FUNCTIONS",
    "|   +-- Orchestrate multi-Lambda workflows",
    "|   +-- Retry/catch/parallel built-in",
    "|   +-- Visual state machine",
    "|",
    "+-- EVENTBRIDGE",
    "|   +-- Event bus: publish/subscribe",
    "|   +-- Scheduled cron -> Lambda",
    "|   +-- Decoupled architecture",
    "|",
    "+-- BEST PRACTICES",
    "|   +-- Single-purpose functions",
    "|   +-- External state (DynamoDB/S3)",
    "|   +-- Idempotent handlers",
    "|   +-- DLQ for failures",
    "|   +-- Lambda Layers for shared code",
    "|",
    "+-- SAM",
    "    +-- template.yaml = Lambda + API Gateway",
    "    +-- sam local = test offline",
    "    +-- sam deploy = ship to AWS",
    "```",
    "",
    "---",
    "",
    "## How Serverless Connects to Other Topics",
    "",
    "- **AWS Mastery**: Lambda is the foundation of AWS serverless. API Gateway +",
    "  Lambda + DynamoDB is the canonical serverless stack.",
    "- **SQS**: Lambda + SQS is one of the most common patterns: queue absorbs bursts,",
    "  Lambda workers consume at controlled concurrency.",
    "- **CI/CD**: SAM/CDK pipelines build and deploy Lambda functions automatically.",
    "- **Docker/Containers**: Lambda also supports container images — bridge between",
    "  serverless and container worlds.",
    "",
    "---",
    "",
    "## Common Beginner Mistakes",
    "",
    "1. **Storing state in Lambda global variables** — persists across warm invocations,",
    "   causes bugs. Exception: DB connection objects are fine to cache globally.",
    "2. **Timeout too short** — Lambda killed mid-execution. Understand your p99 latency.",
    "3. **Huge deployment packages** — 100MB+ packages cause slow cold starts. Tree-shake,",
    "   use Layers, use slim base images.",
    "4. **No DLQ** — failed events silently disappear. Always configure a DLQ.",
    "5. **Chaining Lambdas directly** — use Step Functions for multi-step workflows.",
    "6. **No idempotency** — Lambda retries on failure. Running twice = double charge,",
    "   double email, double insert unless you guard against it.",
    "7. **Ignoring cold starts for Java** — JVM cold start can be 2-3s. Use Provisioned",
    "   Concurrency or switch to Python/Node for latency-sensitive endpoints.",
    "",
    "---",
    "",
    "## References and Further Learning",
    "",
    "### Videos (Watch These!)",
    "- **AWS Lambda Tutorial for Beginners** by TechWorld with Nana:",
    "  https://www.youtube.com/watch?v=eOBq__h4OJ4",
    "  - 1 hour. Lambda architecture, triggers, hands-on demo.",
    "- **Serverless Architecture Explained** by Fireship:",
    "  https://www.youtube.com/watch?v=vxJobGtqKVM",
    "  - 7 minutes. Visual walkthrough of serverless patterns.",
    "",
    "### Free Books and Articles",
    "- **AWS Lambda official docs - Getting Started**:",
    "  https://docs.aws.amazon.com/lambda/latest/dg/getting-started.html",
    "- **Serverless Land** (AWS patterns library): https://serverlessland.com/patterns",
    "  - Real-world serverless patterns with CDK/SAM code. Browse patterns by use case.",
    "",
    "### Diagrams and Cheatsheets",
    "- **Serverless patterns diagram**: https://serverlessland.com/",
    "- **AWS Step Functions visualiser**: https://states-language.net/spec.html",
    "",
    "### Practice",
    "- **AWS Serverless Workshop**: https://s12d.com/workshop",
    "- **Build a Serverless API** (free AWS tutorial): https://aws.amazon.com/getting-started/hands-on/build-serverless-web-app-lambda-apigateway-s3-dynamodb-cognito/",
])

NEW_Q = [
    {"id":"sls-q4","type":"mcq","prompt":"What is a Lambda cold start?",
     "choices":["Lambda crashing permanently","The latency overhead when AWS must initialise a new container, download the code, and start the runtime — happens on first invocation after idle","Lambda running out of memory","Lambda timeout"],
     "answerIndex":1,"explanation":"Cold start = Lambda container provisioning overhead. After ~15 min idle, containers are recycled. Next request pays the cold start tax. Warm invocations (reused container) have no overhead.","tags":["lambda","cold-start"]},
    {"id":"sls-q5","type":"mcq","prompt":"Which runtime has the LONGEST Lambda cold start times?",
     "choices":["Python 3.12","Node.js 20","Java (JVM)","Ruby"],
     "answerIndex":2,"explanation":"JVM startup time (loading classes, JIT compilation) adds 1-3 seconds to Lambda cold starts. Python and Node.js start in ~100-300ms. For latency-sensitive APIs, prefer Python/Node or use Provisioned Concurrency with Java.","tags":["lambda","cold-start","java"]},
    {"id":"sls-q6","type":"mcq","prompt":"What is Provisioned Concurrency in Lambda?",
     "choices":["Maximum number of concurrent Lambda executions","Pre-warming a specified number of Lambda containers so they are always ready — eliminating cold starts at the cost of paying for idle warm containers",
                "Automatic scaling policy","Reserved Lambda capacity"],
     "answerIndex":1,"explanation":"Provisioned Concurrency keeps N containers initialised and warm. No cold start for requests up to N concurrency. You pay for the warm containers even if no requests come in. Worth it for user-facing latency-critical APIs.","tags":["lambda","provisioned-concurrency"]},
    {"id":"sls-q7","type":"mcq","prompt":"Why must Lambda functions be designed to be idempotent?",
     "choices":["Lambda charges per invocation","Lambda can retry failed invocations — if your handler isn't idempotent, retries cause duplicate actions (double charge, double email, duplicate DB record)",
                "Lambda has no retry behaviour","Idempotency improves performance"],
     "answerIndex":1,"explanation":"Lambda retries on errors (SQS triggers retry up to maxReceiveCount times). If processPayment() runs twice, customer is charged twice unless you check 'already processed this request ID' first.","tags":["lambda","idempotency"]},
    {"id":"sls-q8","type":"mcq","prompt":"What happens if you store state in a Lambda global variable?",
     "choices":["It is lost after every invocation","It persists across warm invocations of the SAME container — can cause data leakage between unrelated requests",
                "It causes a cold start","Lambda resets all globals on every call"],
     "answerIndex":1,"explanation":"Lambda containers are reused for warm invocations. A global variable set in request 1 is still there in request 2 on the same container. 'Store DB connection globally' = fine. 'Store user data globally' = data leakage bug.","tags":["lambda","state","gotcha"]},
    {"id":"sls-q9","type":"mcq","prompt":"What is the maximum timeout for a Lambda function?",
     "choices":["30 seconds","5 minutes","15 minutes","1 hour"],
     "answerIndex":2,"explanation":"Lambda maximum timeout is 15 minutes. For longer jobs, use AWS Fargate (ECS tasks) or AWS Batch. Step Functions can coordinate multiple Lambda calls but each individual Lambda still has the 15-min limit.","tags":["lambda","limits"]},
    {"id":"sls-q10","type":"mcq","prompt":"What is the primary benefit of using Step Functions over chaining Lambdas directly?",
     "choices":["Step Functions is cheaper","Step Functions provides built-in state management, retry/catch logic, parallel execution, and a visual audit trail — replacing fragile hand-coded orchestration logic in Lambda",
                "Step Functions is faster","Step Functions removes the need for Lambda"],
     "answerIndex":1,"explanation":"Hand-coded Lambda chains are brittle: no built-in retry, hard to debug, nested timeouts. Step Functions gives you: Retry with backoff, Catch for error handling, Parallel states, Wait states, and a visual execution history in the console.","tags":["step-functions","orchestration"]},
    {"id":"sls-q11","type":"mcq","prompt":"What is an AWS Lambda Layer?",
     "choices":["A networking concept","A reusable package of shared code or dependencies that multiple Lambda functions can reference — uploaded once, attached to many functions",
                "Lambda version alias","Cold start optimisation"],
     "answerIndex":1,"explanation":"Layers let you share: libraries (pandas, boto3), custom runtimes, company-wide utilities. Update the Layer once and all attached functions get the update. Keeps deployment packages small (faster cold starts).","tags":["lambda","layers"]},
    {"id":"sls-q12","type":"mcq","prompt":"What is a Dead Letter Queue (DLQ) in serverless context?",
     "choices":["A queue for spam messages","A destination (SQS or SNS) where failed Lambda invocations are sent after all retries are exhausted — prevents event loss",
                "A Lambda error log","A backup Lambda function"],
     "answerIndex":1,"explanation":"Without DLQ, failed events are silently discarded after retries. With DLQ: failed events go to an SQS queue for investigation, alerting, and manual replay. Always configure DLQ for async Lambda invocations.","tags":["lambda","dlq","reliability"]},
    {"id":"sls-q13","type":"mcq","prompt":"Which AWS service replaces traditional cron jobs in a serverless architecture?",
     "choices":["CloudWatch Logs","AWS Batch","Amazon EventBridge (Scheduler) — triggers Lambda on a cron or rate schedule","SQS FIFO"],
     "answerIndex":2,"explanation":"EventBridge Scheduler (formerly CloudWatch Events) lets you define cron expressions or rates. It triggers Lambda at the scheduled time. No server needed for 'run every day at 2am' tasks.","tags":["eventbridge","scheduling"]},
    {"id":"sls-q14","type":"mcq","prompt":"In SAM (Serverless Application Model), what does `sam local start-api` do?",
     "choices":["Deploys to AWS","Creates API Gateway in AWS","Starts a local HTTP server that simulates API Gateway and invokes your Lambda handler locally — for testing without deploying",
                "Builds the Docker image"],
     "answerIndex":2,"explanation":"sam local start-api spins up a local API Gateway emulator on port 3000. You can hit it with Postman or curl, and SAM invokes your Lambda handler with the same event structure as real API Gateway — all locally.","tags":["sam","local-development"]},
    {"id":"sls-q15","type":"mcq","prompt":"What is the 'Lambda execution environment' reuse benefit for database connections?",
     "choices":["Lambda automatically manages DB connection pools","You can initialise a DB connection OUTSIDE the handler function — it persists in the warm container and is reused across invocations, avoiding reconnect overhead",
                "Lambda has built-in connection pooling","There is no benefit"],
     "answerIndex":1,"explanation":"Initialise expensive resources (DB connections, SDK clients) outside the handler function body. They are created once during cold start and reused across warm invocations. This is the ONE case where global state in Lambda is correct.","tags":["lambda","performance","database"]},
    {"id":"sls-q16","type":"mcq","prompt":"What does the `event` parameter in a Lambda handler contain?",
     "choices":["HTTP headers only","Empty by default","The trigger payload — for API Gateway: HTTP request details; for S3: bucket/key info; for SQS: message bodies. Format varies by trigger type.",
                "Lambda configuration settings"],
     "answerIndex":2,"explanation":"The event object is the trigger's input data. API Gateway event contains httpMethod, path, headers, body. S3 event contains bucket name, object key, event type. SQS event contains an array of messages with their bodies.","tags":["lambda","event","triggers"]},
    {"id":"sls-q17","type":"mcq","prompt":"When would you choose EC2/ECS over Lambda for a workload?",
     "choices":["When requests are sporadic","When you need auto-scaling","When the workload runs longer than 15 minutes, needs consistent low latency under constant traffic, or requires GPU/specialised hardware",
                "Lambda is always better"],
     "answerIndex":2,"explanation":"Lambda excels at sporadic, short-duration, event-driven work. But: video encoding (hours), ML training (GPU needed), constant high-traffic API (EC2/ECS often cheaper than Lambda at scale) — these are EC2/Fargate territory.","tags":["lambda","vs-containers","trade-offs"]},
    {"id":"sls-q18","type":"multi","prompt":"Which of these are valid Lambda triggers? (Select all that apply)",
     "choices":["HTTP request via API Gateway","File uploaded to S3","Message added to SQS queue","Cron schedule via EventBridge"],
     "answerIndexes":[0,1,2,3],"explanation":"All four are valid Lambda triggers. Lambda is event-driven and integrates with practically every AWS service. You can also trigger it from DynamoDB Streams, SNS, Kinesis, IoT Core, and more.","tags":["lambda","triggers"]},
    {"id":"sls-q19","type":"mcq","prompt":"What is the Lambda concurrency limit and what happens when it is hit?",
     "choices":["No limit","When concurrent executions exceed the account limit (default 1000), new requests get a 429 TooManyRequestsException and are throttled",
                "Lambda auto-scales infinitely","Requests are queued automatically"],
     "answerIndex":1,"explanation":"Each AWS account has a default concurrency limit (1000 across all Lambdas). When exceeded, new invocations are throttled (429). Request a limit increase via AWS Support or use Reserved Concurrency to guarantee capacity for critical functions.","tags":["lambda","concurrency","limits"]},
    {"id":"sls-q20","type":"mcq","prompt":"What is the 'fan-out' serverless pattern?",
     "choices":["Lambda calling one downstream service","One event triggers multiple parallel Lambda executions — used for parallel processing of different aspects of the same event",
                "Lambda reading from multiple queues","Step Functions sequential execution"],
     "answerIndex":1,"explanation":"Fan-out: SNS topic receives one event, fans out to multiple SQS queues, each consumed by different Lambda functions in parallel. Example: OrderPlaced -> simultaneously trigger inventory Lambda, email Lambda, analytics Lambda.","tags":["patterns","fan-out","sns"]},
]

NEW_FC = [
    {"id":"sls-fc4","front":"Lambda cold start mitigation options","back":"1. Provisioned Concurrency (pre-warm containers, costs money)  2. EventBridge keep-alive ping every 5 min (free)  3. Reduce package size (fewer deps, Lambda Layers)  4. Use Python/Node over Java  5. GraalVM native for Java (no JVM startup)","tags":["lambda","cold-start"]},
    {"id":"sls-fc5","front":"Lambda global variable rule","back":"Initialise OUTSIDE handler: DB connections, SDK clients, config (safe, reused across warm invocations = good performance). Store INSIDE handler: per-request user data, request state (not safe to persist across invocations = data leakage).","tags":["lambda","state"]},
    {"id":"sls-fc6","front":"Step Functions when to use","back":"Use when: multi-step workflow with error handling, parallel branches, or human approval. Avoid for: simple A->B Lambda chains that rarely fail. Step Functions cost per state transition — don't overuse for trivial chains.","tags":["step-functions"]},
    {"id":"sls-fc7","front":"Lambda DLQ — why mandatory for async","back":"Async Lambda invocations (SQS, SNS, S3) retry on failure. After retries exhausted, event is LOST unless DLQ configured. DLQ = SQS queue receiving failed events for investigation/replay. Always configure DLQ for async Lambda.","tags":["lambda","dlq","reliability"]},
    {"id":"sls-fc8","front":"Serverless vs container decision","back":"Lambda: sporadic traffic, event-driven, <15min, pay per use, zero ops. ECS/Fargate: long-running, consistent high traffic (cheaper per request at scale), >15min, stateful. EC2: full control, specialised hardware (GPU), legacy apps.","tags":["trade-offs","architecture"]},
]

d['guide'] = GUIDE
d['questions'] = NEW_Q
d['flashcards'] = NEW_FC

with open(p, 'w') as f:
    json.dump(d, f, indent=2, ensure_ascii=False)
print(f"serverless-patterns.json done: guide={len(GUIDE)} q={len(d['questions'])} fc={len(d['flashcards'])}")

