import json
from pathlib import Path

p = Path('/Users/eptr6dj/IdeaProjects/master-cs/cs-mastery/src/content/topics/cloud-devops/kubernetes.json')
d = json.loads(p.read_text())

lines = []
lines += [
    "# Kubernetes",
    "",
    "## What Is Kubernetes? (No Prior Knowledge Assumed)",
    "",
    "Imagine you are running a popular food delivery app. On Friday evenings, traffic spikes",
    "10x. You need 50 servers. At 3am Sunday, you need 2 servers. Manually spinning servers",
    "up and down, restarting crashed apps, and distributing traffic is a full-time job.",
    "",
    "**Kubernetes (K8s) automates all of that.** It is an orchestration system that:",
    "- Runs your containerised apps across a cluster of machines",
    "- Automatically restarts crashed containers",
    "- Scales up (more containers) when traffic is high, scales down when quiet",
    "- Distributes traffic evenly across healthy containers",
    "- Rolls out new versions without downtime",
    "- Rolls back automatically if a new version is broken",
    "",
    "**Analogy:** Kubernetes is like the manager of a huge restaurant kitchen.",
    "You tell the manager: 'I need 5 chefs making pizza at all times.'",
    "The manager hires them, replaces any who quit, and adjusts staffing for rush hour —",
    "without you micromanaging each chef individually.",
    "",
    "```",
    "Without Kubernetes:                 With Kubernetes:",
    "  You manually SSH into servers       kubectl apply -f deployment.yaml",
    "  Restart crashed apps manually       K8s restarts crashed pods automatically",
    "  Scale servers by hand               K8s auto-scales based on CPU/memory",
    "  Roll out updates carefully          K8s does rolling updates (zero downtime)",
    "  Stay up at 3am for incidents        K8s self-heals 24/7",
    "```",
    "",
    "---",
    "",
    "## Cluster Architecture — The Big Picture",
    "",
    "A Kubernetes cluster has two types of machines:",
    "",
    "```",
    "+-------------------------------------------+",
    "|           CONTROL PLANE (Master)           |",
    "|                                           |",
    "|  +----------+  +---------+  +----------+ |",
    "|  | API       |  | Sched-  |  | etcd     | |",
    "|  | Server    |  | uler    |  | (cluster | |",
    "|  | (the hub) |  |         |  |  state)  | |",
    "|  +----------+  +---------+  +----------+ |",
    "|  +-----------+                            |",
    "|  | Controller|  (watches desired vs       |",
    "|  | Manager   |   actual state, fixes gaps)|",
    "|  +-----------+                            |",
    "+-------------------------------------------+",
    "         |            |            |",
    "   +-----+----+  +----+-----+  +--+-------+",
    "   |  WORKER  |  |  WORKER  |  |  WORKER  |",
    "   |  NODE 1  |  |  NODE 2  |  |  NODE 3  |",
    "   |          |  |          |  |          |",
    "   | [Pod][Pod|  | [Pod][Pod|  | [Pod]    |",
    "   |  kubelet |  |  kubelet |  |  kubelet |",
    "   |  kube-   |  |  kube-   |  |  kube-  |",
    "   |  proxy   |  |  proxy   |  |  proxy  |",
    "   +----------+  +----------+  +---------+",
    "",
    "Control Plane = the brain (decides what runs where)",
    "Worker Nodes  = the muscles (actually run your containers)",
    "```",
    "",
    "**Control Plane components:**",
    "- **API Server** — the front door. All kubectl commands hit this. `kubectl apply` talks to API Server.",
    "- **etcd** — a distributed key-value store. Stores ALL cluster state. If etcd is lost, the cluster is lost.",
    "- **Scheduler** — decides which worker node to place a new Pod on (based on resources, rules).",
    "- **Controller Manager** — watches actual vs desired state and fixes gaps (restarts crashed pods, etc.).",
    "",
    "**Worker Node components:**",
    "- **kubelet** — agent on each node. Receives instructions from API Server, starts/stops containers.",
    "- **kube-proxy** — handles networking rules so Pods can talk to each other and to Services.",
    "- **Container Runtime** — usually containerd (runs the actual containers, formerly Docker).",
    "",
    "---",
    "",
    "## Core Objects — The Building Blocks",
    "",
    "### Pod — The Smallest Unit",
    "",
    "```",
    "A Pod is one or more containers that:",
    "  - Share the same network namespace (same IP address)",
    "  - Share storage volumes",
    "  - Are always scheduled together on the same node",
    "",
    "+-----------------------------------+",
    "|              POD                  |",
    "|  +----------+  +---------------+ |",
    "|  | Main      |  | Sidecar       | |",
    "|  | Container |  | Container     | |",
    "|  | (app)     |  | (log shipper) | |",
    "|  +----------+  +---------------+ |",
    "|  Shared: IP address, volumes      |",
    "+-----------------------------------+",
    "",
    "99% of Pods contain just ONE container.",
    "Multi-container Pods are for tightly coupled helpers (sidecars).",
    "```",
    "",
    "**You almost never create Pods directly.** You create Deployments which manage Pods.",
    "",
    "### Deployment — Managing Replicas",
    "",
    "```yaml",
    "# deployment.yaml",
    "apiVersion: apps/v1",
    "kind: Deployment",
    "metadata:",
    "  name: my-app",
    "spec:",
    "  replicas: 3             # keep 3 Pods running at all times",
    "  selector:",
    "    matchLabels:",
    "      app: my-app",
    "  template:",
    "    metadata:",
    "      labels:",
    "        app: my-app       # Pods get this label",
    "    spec:",
    "      containers:",
    "        - name: my-app",
    "          image: myregistry/myapp:v1.2.3   # NEVER use :latest in production",
    "          ports:",
    "            - containerPort: 8080",
    "          resources:",
    "            requests:         # minimum guaranteed resources",
    "              cpu: '100m'     # 100 milliCPU = 0.1 CPU core",
    "              memory: '256Mi'",
    "            limits:           # maximum allowed",
    "              cpu: '500m'",
    "              memory: '512Mi'",
    "```",
    "",
    "```bash",
    "kubectl apply -f deployment.yaml    # create or update the deployment",
    "kubectl get deployments             # list deployments",
    "kubectl get pods                    # list pods",
    "kubectl describe deployment my-app  # detailed status",
    "kubectl rollout status deployment my-app  # watch rollout progress",
    "```",
    "",
    "### Service — Stable Network Access",
    "",
    "Pods are temporary — they die and restart with new IP addresses.",
    "A Service is a stable endpoint that always points to healthy Pods.",
    "",
    "```",
    "Client                Service                 Pods",
    "                     (stable IP/DNS)      (ephemeral IPs)",
    "",
    "browser -------> my-app-service -----> Pod 10.0.0.5",
    "  :80            10.96.0.100:80  \\---> Pod 10.0.0.8",
    "                                 \\---> Pod 10.0.0.12",
    "",
    "Even when Pods restart with new IPs, the Service IP stays the same.",
    "The Service load-balances across healthy Pods automatically.",
    "```",
    "",
    "```yaml",
    "# service.yaml",
    "apiVersion: v1",
    "kind: Service",
    "metadata:",
    "  name: my-app-service",
    "spec:",
    "  selector:",
    "    app: my-app          # routes traffic to Pods with label app=my-app",
    "  ports:",
    "    - port: 80           # Service port",
    "      targetPort: 8080   # Pod port",
    "  type: ClusterIP        # internal only (default)",
    "  # type: NodePort       # accessible on each node's IP:nodePort",
    "  # type: LoadBalancer   # creates a cloud load balancer (AWS ELB, GCP LB)",
    "```",
    "",
    "### ConfigMap and Secret",
    "",
    "```yaml",
    "# ConfigMap: non-sensitive config",
    "apiVersion: v1",
    "kind: ConfigMap",
    "metadata:",
    "  name: app-config",
    "data:",
    "  DATABASE_HOST: 'postgres-service'",
    "  LOG_LEVEL: 'INFO'",
    "",
    "# Secret: sensitive data (base64 encoded, use external secrets manager in prod)",
    "apiVersion: v1",
    "kind: Secret",
    "metadata:",
    "  name: app-secrets",
    "type: Opaque",
    "data:",
    "  DB_PASSWORD: c3VwZXJzZWNyZXQ=   # base64 of 'supersecret'",
    "```",
    "",
    "```yaml",
    "# Use in a Pod spec:",
    "env:",
    "  - name: DATABASE_HOST",
    "    valueFrom:",
    "      configMapKeyRef:",
    "        name: app-config",
    "        key: DATABASE_HOST",
    "  - name: DB_PASSWORD",
    "    valueFrom:",
    "      secretKeyRef:",
    "        name: app-secrets",
    "        key: DB_PASSWORD",
    "```",
    "",
    "---",
    "",
    "## kubectl — The Command Line Tool",
    "",
    "```bash",
    "# VIEWING RESOURCES",
    "kubectl get pods                         # list pods in current namespace",
    "kubectl get pods -n production           # list pods in 'production' namespace",
    "kubectl get pods -o wide                 # more detail (node, IP)",
    "kubectl get all                          # pods, services, deployments etc.",
    "kubectl describe pod my-pod-abc12        # detailed info including events (debug here!)",
    "",
    "# LOGS",
    "kubectl logs my-pod-abc12                # logs from a pod",
    "kubectl logs my-pod-abc12 -f             # follow live logs",
    "kubectl logs my-pod-abc12 --previous     # logs from crashed previous container",
    "",
    "# SHELL INTO A RUNNING POD",
    "kubectl exec -it my-pod-abc12 -- bash    # interactive shell (like docker exec)",
    "kubectl exec -it my-pod-abc12 -- sh      # use sh if bash not available",
    "",
    "# APPLY / DELETE",
    "kubectl apply -f deployment.yaml         # create or update resource",
    "kubectl delete -f deployment.yaml        # delete resource",
    "kubectl delete pod my-pod-abc12          # delete specific pod (Deployment restarts it)",
    "",
    "# SCALING",
    "kubectl scale deployment my-app --replicas=10  # scale to 10 pods",
    "",
    "# ROLLOUTS",
    "kubectl rollout status deployment my-app       # watch current rollout",
    "kubectl rollout history deployment my-app      # see revision history",
    "kubectl rollout undo deployment my-app         # roll back to previous version",
    "kubectl rollout undo deployment my-app --to-revision=3  # roll back to specific revision",
    "",
    "# PORT FORWARDING (debug locally)",
    "kubectl port-forward pod/my-pod-abc12 8080:8080  # access pod port locally",
    "kubectl port-forward service/my-app-service 8080:80",
    "",
    "# NAMESPACES",
    "kubectl get namespaces",
    "kubectl create namespace staging",
    "kubectl config set-context --current --namespace=staging  # set default namespace",
    "```",
    "",
    "---",
    "",
    "## Health Checks — Readiness vs Liveness Probes",
    "",
    "```",
    "Liveness Probe:   Is this container ALIVE? Should K8s restart it?",
    "Readiness Probe:  Is this container READY to receive traffic?",
    "",
    "Both are checked periodically by kubelet.",
    "",
    "LIVENESS failure  -> container killed and restarted",
    "READINESS failure -> container removed from Service endpoints (no traffic sent)",
    "                     but NOT restarted",
    "```",
    "",
    "```yaml",
    "livenessProbe:",
    "  httpGet:",
    "    path: /healthz    # your app must return 200 on this path",
    "    port: 8080",
    "  initialDelaySeconds: 30  # wait 30s before first check (app needs time to start)",
    "  periodSeconds: 10         # check every 10 seconds",
    "  failureThreshold: 3       # restart after 3 consecutive failures",
    "",
    "readinessProbe:",
    "  httpGet:",
    "    path: /ready      # return 200 when app is ready to serve traffic",
    "    port: 8080",
    "  initialDelaySeconds: 10",
    "  periodSeconds: 5",
    "  failureThreshold: 3",
    "```",
    "",
    "**Why both?**",
    "- App starts but crashes in a loop -> **liveness** probe detects -> K8s restarts.",
    "- App starts but DB connection not ready yet -> **readiness** probe returns 500 -> K8s holds",
    "  traffic until DB is connected -> then starts sending traffic. Zero dropped requests.",
    "",
    "---",
    "",
    "## Rolling Updates — Zero Downtime Deployments",
    "",
    "When you update an image tag in a Deployment, K8s rolls it out gradually:",
    "",
    "```",
    "Strategy: RollingUpdate (default)",
    "  maxUnavailable: 1   <- at most 1 pod down at a time",
    "  maxSurge: 1         <- at most 1 extra pod created during update",
    "",
    "Step 1:  [v1] [v1] [v1]       (3 old pods running)",
    "Step 2:  [v1] [v1] [v2]       (1 new pod started, readiness checked)",
    "Step 3:  [v1] [v2] [v2]       (1 old pod removed, 1 more new)",
    "Step 4:  [v2] [v2] [v2]       (rollout complete!)",
    "",
    "At every step, at least 2 pods are serving traffic.",
    "Traffic is only sent to pods that pass readiness probe.",
    "```",
    "",
    "```bash",
    "# Update image version (triggers rolling update)",
    "kubectl set image deployment/my-app my-app=myregistry/myapp:v1.3.0",
    "",
    "# Watch it happen",
    "kubectl rollout status deployment my-app",
    "",
    "# Something wrong? Roll back instantly",
    "kubectl rollout undo deployment my-app",
    "```",
    "",
    "---",
    "",
    "## Namespaces — Logical Isolation",
    "",
    "```",
    "Namespaces partition one cluster into virtual clusters.",
    "Use them to separate environments and teams.",
    "",
    "cluster/",
    "+-- namespace: default         (where things go if you don't specify)",
    "+-- namespace: kube-system     (K8s internal components)",
    "+-- namespace: production      (your prod workloads)",
    "+-- namespace: staging         (your staging workloads)",
    "+-- namespace: team-payments   (payments team's stuff)",
    "",
    "Benefits:",
    "  - Resource quotas per namespace (production gets more CPU budget)",
    "  - RBAC per namespace (staging team can't touch production)",
    "  - Clear separation, easier to manage",
    "```",
    "",
    "---",
    "",
    "## Resource Requests and Limits",
    "",
    "```",
    "requests: what the Pod is GUARANTEED to get (scheduler uses this to place Pod)",
    "limits:   maximum the Pod can USE (kernel enforces this)",
    "",
    "CPU:    measured in millicores. 1000m = 1 CPU core.",
    "Memory: measured in Mi (mebibytes) or Gi (gibibytes).",
    "",
    "If Pod exceeds memory LIMIT -> OOMKilled (Out Of Memory killed, then restarted)",
    "If Pod exceeds CPU LIMIT    -> throttled (slowed down, not killed)",
    "",
    "Best practice: set both requests and limits.",
    "requests too low  = Pod gets scheduled on overloaded node",
    "limits too low    = Pod OOMKilled frequently",
    "no limits at all  = one bad Pod can starve all others on the node",
    "```",
    "",
    "---",
    "",
    "## Ingress — HTTP Routing into the Cluster",
    "",
    "```",
    "Without Ingress:",
    "  Each Service needs its own LoadBalancer -> expensive (one cloud LB per service)",
    "",
    "With Ingress:",
    "  One LoadBalancer -> Ingress Controller -> routes to Services by host/path",
    "",
    "  External          Ingress            Services",
    "  Traffic    ->  Controller  ->  api.myapp.com  -> api-service",
    "                              ->  myapp.com/app -> frontend-service",
    "                              ->  myapp.com/pay -> payment-service",
    "```",
    "",
    "```yaml",
    "apiVersion: networking.k8s.io/v1",
    "kind: Ingress",
    "metadata:",
    "  name: my-ingress",
    "  annotations:",
    "    nginx.ingress.kubernetes.io/rewrite-target: /",
    "spec:",
    "  rules:",
    "    - host: myapp.com",
    "      http:",
    "        paths:",
    "          - path: /api",
    "            pathType: Prefix",
    "            backend:",
    "              service:",
    "                name: api-service",
    "                port:",
    "                  number: 80",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "KUBERNETES",
    "|",
    "+-- CLUSTER",
    "|   +-- Control Plane (API Server, etcd, Scheduler, Controller Manager)",
    "|   +-- Worker Nodes  (kubelet, kube-proxy, container runtime)",
    "|",
    "+-- CORE OBJECTS",
    "|   +-- Pod          (smallest unit: 1+ containers)",
    "|   +-- Deployment   (manages replicas + rolling updates)",
    "|   +-- Service      (stable network endpoint, load balancer)",
    "|   +-- ConfigMap    (non-sensitive config)",
    "|   +-- Secret       (sensitive config, base64 encoded)",
    "|   +-- Namespace    (logical cluster partition)",
    "|   +-- Ingress      (HTTP routing from outside)",
    "|",
    "+-- HEALTH",
    "|   +-- Liveness probe  (restart if dead)",
    "|   +-- Readiness probe (hold traffic if not ready)",
    "|",
    "+-- OPERATIONS (kubectl)",
    "|   +-- apply/delete     (create/remove resources)",
    "|   +-- get/describe     (view state)",
    "|   +-- logs/exec        (debug pods)",
    "|   +-- scale            (change replicas)",
    "|   +-- rollout undo     (rollback)",
    "|",
    "+-- RESOURCES",
    "    +-- requests (guaranteed minimum)",
    "    +-- limits   (enforced maximum)",
    "    +-- OOMKill  (memory limit breach)",
    "```",
    "",
    "---",
    "",
    "## How Kubernetes Connects to Other Topics",
    "",
    "- **Docker**: K8s runs Docker (or containerd) container images. Every app deployed to K8s",
    "  is a Docker image built and pushed to a registry.",
    "- **CI/CD**: Pipelines build images, push to registry, then `kubectl apply` to deploy.",
    "  GitOps tools (ArgoCD, Flux) watch git repos and auto-sync K8s state.",
    "- **Cloud/AWS**: AWS EKS is managed Kubernetes. GCP has GKE, Azure has AKS.",
    "  The control plane is managed for you — you only manage worker nodes.",
    "- **Linux**: Every K8s node is a Linux machine. When you `kubectl exec` into a pod,",
    "  you are in a Linux shell. Linux process/network skills apply.",
    "",
    "---",
    "",
    "## Common Beginner Mistakes",
    "",
    "1. **Using `image:latest`** — breaks reproducibility. Always pin: `myapp:v1.2.3`.",
    "2. **No resource requests/limits** — one runaway pod starves the entire node.",
    "3. **No readiness probe** — K8s sends traffic to pods before app is ready -> 502 errors during deploys.",
    "4. **Deleting pods to 'restart' them** — the correct way is `kubectl rollout restart deployment my-app`. Deleting pods in a Deployment just causes K8s to create new ones anyway.",
    "5. **Storing secrets in ConfigMaps** — ConfigMaps are not encrypted. Use Secrets (or better: External Secrets Operator + AWS Secrets Manager).",
    "6. **Everything in the default namespace** — use namespaces to separate environments and teams.",
    "7. **No liveness probe** — deadlocked pods keep running, serving no traffic, eating resources.",
    "",
    "---",
    "",
    "## References and Further Learning",
    "",
    "### Videos (Watch These!)",
    "- **Kubernetes Tutorial for Beginners** by TechWorld with Nana:",
    "  https://www.youtube.com/watch?v=X48VuDVv0do",
    "  - 4 hours. Complete K8s beginner course. Architecture, commands, real deployments.",
    "- **Kubernetes Explained in 100 Seconds** by Fireship:",
    "  https://www.youtube.com/watch?v=PziYflu8cB8",
    "  - 2 minutes. Perfect mental model overview.",
    "",
    "### Free Books and Articles",
    "- **Kubernetes official docs - Learn Kubernetes Basics interactive tutorial**:",
    "  https://kubernetes.io/docs/tutorials/kubernetes-basics/",
    "  - Browser-based interactive minikube tutorial. No install needed.",
    "- **Kubernetes the Hard Way** by Kelsey Hightower:",
    "  https://github.com/kelseyhightower/kubernetes-the-hard-way",
    "  - Advanced: build K8s from scratch to truly understand it.",
    "",
    "### Diagrams and Cheatsheets",
    "- **kubectl cheatsheet (official)**: https://kubernetes.io/docs/reference/kubectl/cheatsheet/",
    "- **Kubernetes architecture diagram**: search 'Kubernetes architecture diagram' — the official",
    "  CNCF diagram is the best visual reference.",
    "",
    "### Practice",
    "- **Killer Shell** (CKA/CKAD exam simulator): https://killer.sh/",
    "- **KodeKloud Kubernetes for Beginners** (browser labs, free tier):",
    "  https://kodekloud.com/courses/kubernetes-for-the-absolute-beginners-hands-on/",
    "- **Play with Kubernetes** (free browser K8s lab): https://labs.play-with-k8s.com/",
]

K8S_GUIDE = "\n".join(lines)

# ── QUESTIONS ──────────────────────────────────────────────────────────────────
NEW_QUESTIONS = [
    {"id":"k8s-q4","type":"mcq",
     "prompt":"What is a Kubernetes Pod?",
     "choices":["A virtual machine","A physical server in a cluster","The smallest deployable unit — one or more containers sharing a network namespace and storage","A load balancer"],
     "answerIndex":2,"explanation":"A Pod is K8s smallest deployable unit. Containers in a Pod share an IP address and can share volumes. 99% of Pods contain a single container.","tags":["pods","k8s-basics"]},
    {"id":"k8s-q5","type":"mcq",
     "prompt":"What is the role of a Kubernetes Deployment?",
     "choices":["Handles HTTP routing","Stores cluster configuration","Declares desired state: how many Pod replicas to run, which image, rolling update strategy","Provides persistent storage"],
     "answerIndex":2,"explanation":"A Deployment manages a ReplicaSet which ensures the specified number of Pod replicas are always running. It also handles rolling updates and rollbacks.","tags":["deployment","k8s-core"]},
    {"id":"k8s-q6","type":"mcq",
     "prompt":"Why do Pods need a Service in front of them?",
     "choices":["Pods cannot run without a Service","Pods have dynamic IP addresses that change when they restart — a Service provides a stable IP/DNS name that always routes to healthy Pods","Services provide persistent storage","Services make Pods faster"],
     "answerIndex":1,"explanation":"When a Pod restarts, it gets a new IP address. A Service is a stable network endpoint with a fixed IP/DNS that automatically routes to current healthy Pods via label selectors.","tags":["services","networking"]},
    {"id":"k8s-q7","type":"mcq",
     "prompt":"What happens when a liveness probe fails repeatedly?",
     "choices":["The node is restarted","Traffic is stopped to the Pod","The container is killed and restarted by kubelet","The Deployment is deleted"],
     "answerIndex":2,"explanation":"Liveness probe failure = container is not alive/responsive. kubelet kills and restarts the container. This handles deadlocks and infinite loops that don't crash but stop responding.","tags":["probes","health"]},
    {"id":"k8s-q8","type":"mcq",
     "prompt":"A Pod passes its liveness probe but fails its readiness probe. What does Kubernetes do?",
     "choices":["Restarts the Pod","Deletes the Pod","Removes the Pod from the Service's endpoint list — no traffic is sent to it","Nothing — both probes must fail"],
     "answerIndex":2,"explanation":"Readiness failure means the container is alive but not ready for traffic. K8s removes it from Service endpoints. Traffic is only sent to ready Pods. The container is NOT restarted.","tags":["probes","readiness"]},
    {"id":"k8s-q9","type":"mcq",
     "prompt":"What does `kubectl rollout undo deployment my-app` do?",
     "choices":["Deletes the deployment","Scales the deployment to zero","Rolls back to the previous image version using Deployment revision history","Pauses the rollout"],
     "answerIndex":2,"explanation":"K8s Deployments keep a rollout history. rollout undo reverts to the previous revision — changing the image tag back and doing a rolling update in reverse. Fast and safe.","tags":["rollout","updates"]},
    {"id":"k8s-q10","type":"mcq",
     "prompt":"What is the difference between resource `requests` and `limits` in K8s?",
     "choices":["They are identical","requests = minimum guaranteed resources (scheduler uses to place Pod); limits = maximum allowed (enforced by kernel — OOMKill if exceeded)","requests = maximum; limits = minimum","limits only apply to CPU"],
     "answerIndex":1,"explanation":"requests guarantees the Pod gets at least that much CPU/memory. The scheduler uses requests to decide which node can fit the Pod. limits caps usage — memory overuse causes OOMKill; CPU overuse causes throttling.","tags":["resources","scheduling"]},
    {"id":"k8s-q11","type":"mcq",
     "prompt":"What does a Kubernetes Namespace provide?",
     "choices":["Network isolation between nodes","DNS resolution","Logical partitioning of cluster resources — lets different teams/environments share one cluster without interfering","Container image versioning"],
     "answerIndex":2,"explanation":"Namespaces partition a cluster logically. production and staging namespaces can coexist on the same cluster with separate resource quotas and RBAC policies.","tags":["namespaces","organization"]},
    {"id":"k8s-q12","type":"mcq",
     "prompt":"What is the role of `etcd` in the Kubernetes control plane?",
     "choices":["Schedules Pods to nodes","Runs containers","Distributed key-value store that holds ALL cluster state — the source of truth","Load balances services"],
     "answerIndex":2,"explanation":"etcd is K8s database. Every object (Pods, Deployments, Services, Secrets) is stored in etcd. If etcd is lost, the cluster state is lost. This is why etcd backups are critical.","tags":["control-plane","etcd"]},
    {"id":"k8s-q13","type":"mcq",
     "prompt":"You deploy a new image version and it is broken. Traffic is dropping. Fastest safe fix?",
     "choices":["kubectl delete deployment my-app and recreate","kubectl rollout undo deployment my-app","Manually edit each Pod","kubectl apply a ConfigMap change"],
     "answerIndex":1,"explanation":"kubectl rollout undo immediately reverts to the previous working revision using K8s rollout history. No downtime — it does a rolling update back to the old version.","tags":["rollout","incident-response"]},
    {"id":"k8s-q14","type":"mcq",
     "prompt":"What is the purpose of a Kubernetes Ingress?",
     "choices":["Internal pod-to-pod communication","Provides persistent volumes","Single entry point for HTTP/HTTPS traffic with host/path-based routing to multiple Services","Encrypts etcd data"],
     "answerIndex":2,"explanation":"Ingress routes external HTTP traffic to internal Services by hostname and path. Instead of one LoadBalancer per Service (expensive), one Ingress Controller handles all HTTP routing.","tags":["ingress","networking"]},
    {"id":"k8s-q15","type":"mcq",
     "prompt":"What is the difference between a ConfigMap and a Secret in Kubernetes?",
     "choices":["Secrets are bigger","ConfigMaps are for non-sensitive config (env vars, properties); Secrets are for sensitive data (passwords, tokens) and are base64-encoded","Secrets are encrypted at rest by default","They are identical"],
     "answerIndex":1,"explanation":"ConfigMaps store plain non-sensitive configuration. Secrets store sensitive data in base64 encoding (not encryption!). For true security, use external secrets managers (AWS Secrets Manager + External Secrets Operator).","tags":["configmap","secrets"]},
    {"id":"k8s-q16","type":"multi",
     "prompt":"Which kubectl commands are useful for debugging a crashing Pod? (Select all that apply)",
     "choices":["kubectl logs pod-name --previous","kubectl describe pod pod-name","kubectl exec -it pod-name -- bash","kubectl scale deployment my-app --replicas=0"],
     "answerIndexes":[0,1,2],"explanation":"logs --previous shows logs from the last crashed container. describe shows events and probe failures. exec drops you in for interactive debugging. Scaling to 0 just stops pods — not debugging.","tags":["debugging","kubectl"]},
    {"id":"k8s-q17","type":"mcq",
     "prompt":"Why is `image:latest` dangerous in Kubernetes production deployments?",
     "choices":["latest is not cached by Docker","latest tag makes rolling updates impossible","latest always pulls the newest version — a new image push could change your running app unpredictably, and K8s cannot tell old from new for rollout tracking","latest is not valid in K8s"],
     "answerIndex":2,"explanation":"If you use latest, any time K8s pulls the image it might get a different version. K8s also tracks rollout history by image digest — two 'latest' images may be different internally, breaking rollback.","tags":["best-practices","image-tags"]},
    {"id":"k8s-q18","type":"mcq",
     "prompt":"What does `kubectl port-forward pod/my-pod 8080:8080` do?",
     "choices":["Exposes the pod to the internet","Creates a temporary tunnel from your local port 8080 to port 8080 inside the pod — for local debugging","Changes the Service port","Scales the pod"],
     "answerIndex":1,"explanation":"port-forward creates a local tunnel directly to a Pod's port. You can access http://localhost:8080 and it tunnels to the Pod. No Service or Ingress needed. Great for debugging without exposing publicly.","tags":["kubectl","debugging"]},
    {"id":"k8s-q19","type":"mcq",
     "prompt":"In a rolling update with maxUnavailable=1 and maxSurge=1, starting from 3 replicas, what is the minimum number of Pods available during the update?",
     "choices":["0","1","2","3"],
     "answerIndex":2,"explanation":"maxUnavailable=1 means at most 1 pod can be down. Starting from 3, minimum available = 3-1 = 2. This ensures traffic continues flowing during the update.","tags":["rollout","availability"]},
    {"id":"k8s-q20","type":"mcq",
     "prompt":"What is kubelet's primary responsibility on a worker node?",
     "choices":["Routes external traffic","Stores cluster state","Watches the API Server for Pod assignments and ensures containers are running as specified on that node","Handles DNS resolution"],
     "answerIndex":2,"explanation":"kubelet is the K8s agent on each node. It watches the API Server for Pods assigned to its node, then starts/stops/restarts containers accordingly via the container runtime.","tags":["control-plane","kubelet"]},
]

# ── FLASHCARDS ─────────────────────────────────────────────────────────────────
NEW_FLASHCARDS = [
    {"id":"k8s-fc4","front":"Deployment vs Pod — when to create each","back":"Never create bare Pods in production. Always use Deployments. Deployments manage replicas, handle rolling updates, and restart crashed Pods automatically. Bare Pods are not restarted if they crash.","tags":["deployment","pods"]},
    {"id":"k8s-fc5","front":"Service types: ClusterIP / NodePort / LoadBalancer","back":"ClusterIP = internal only (default). NodePort = accessible on node IP:port (dev). LoadBalancer = creates cloud load balancer (production external traffic). Use Ingress + ClusterIP for HTTP at scale.","tags":["services","networking"]},
    {"id":"k8s-fc6","front":"OOMKilled — cause and fix","back":"Pod exceeded its memory LIMIT. Kubernetes kills and restarts it. Fix: increase memory limit, profile memory leak in code, or set limit closer to actual usage. CPU overuse = throttled (slowed), not killed.","tags":["resources","debugging"]},
    {"id":"k8s-fc7","front":"Rolling update safety rule","back":"Always set readiness probe. K8s only sends traffic to pods that pass readiness. Without it, pods get traffic before app is ready -> 502 errors. With it: seamless zero-downtime deploys.","tags":["rollout","probes"]},
    {"id":"k8s-fc8","front":"kubectl debug workflow","back":"1. kubectl get pods (find the pod name) 2. kubectl describe pod <name> (see events, probe failures) 3. kubectl logs <name> --previous (crashed container logs) 4. kubectl exec -it <name> -- bash (interactive debug)","tags":["debugging","kubectl"]},
]

# ── WRITE ──────────────────────────────────────────────────────────────────────
d['guide'] = K8S_GUIDE

existing_q_ids = {q['id'] for q in d['questions']}
for q in NEW_QUESTIONS:
    if q['id'] not in existing_q_ids:
        d['questions'].append(q)

existing_fc_ids = {fc['id'] for fc in d['flashcards']}
for fc in NEW_FLASHCARDS:
    if fc['id'] not in existing_fc_ids:
        d['flashcards'].append(fc)

with open(p, 'w') as f:
    json.dump(d, f, indent=2, ensure_ascii=False)

print(f"kubernetes.json done!")
print(f"  Guide: {len(K8S_GUIDE)} chars")
print(f"  Questions: {len(d['questions'])}")
print(f"  Flashcards: {len(d['flashcards'])}")
print(f"  YouTube: {'youtube.com' in K8S_GUIDE}")
print(f"  References: {'References' in K8S_GUIDE}")

