import json
from pathlib import Path

p = Path('/Users/eptr6dj/IdeaProjects/master-cs/cs-mastery/src/content/topics/cloud-devops/aws-practitioner.json')
d = json.loads(p.read_text())

GUIDE = "\n".join([
    "# AWS Practitioner Fundamentals",
    "",
    "## AWS in Plain English — Why It Exists",
    "",
    "AWS (Amazon Web Services) started because Amazon built a huge internal infrastructure",
    "to run amazon.com, then realised other companies needed the same thing.",
    "In 2006 they opened it up — rent Amazon's servers and infrastructure on-demand.",
    "Today AWS is the world's largest cloud provider, used by Netflix, Airbnb, NASA, startups,",
    "and Fortune 500 companies alike.",
    "",
    "**The core promise:** You get access to world-class infrastructure — data centres,",
    "networking, databases, security — without buying or managing any hardware.",
    "Pay only for what you use. Scale in minutes. Global in hours.",
    "",
    "```",
    "AWS has 200+ services across every category:",
    "  Compute:    EC2, Lambda, ECS, EKS, Fargate",
    "  Storage:    S3, EBS, EFS, Glacier",
    "  Database:   RDS, DynamoDB, ElastiCache, Redshift",
    "  Networking: VPC, CloudFront, Route 53, API Gateway",
    "  Security:   IAM, KMS, WAF, Shield, GuardDuty",
    "  AI/ML:      SageMaker, Bedrock, Rekognition, Transcribe",
    "  DevOps:     CodePipeline, CodeBuild, CloudFormation, CDK",
    "  Monitoring: CloudWatch, X-Ray, CloudTrail",
    "```",
    "",
    "---",
    "",
    "## Core Compute: EC2",
    "",
    "EC2 (Elastic Compute Cloud) is a virtual machine (VM) in the cloud.",
    "It is the most fundamental AWS service — everything else often runs on top of EC2.",
    "",
    "```",
    "EC2 instance = a Linux (or Windows) server you rent by the hour",
    "",
    "Instance types: different CPU/RAM/storage combinations",
    "  t3.micro:   2 vCPU,  1GB RAM   ($0.01/hr) - free tier, dev/test",
    "  t3.medium:  2 vCPU,  4GB RAM   ($0.04/hr) - small apps",
    "  m5.xlarge:  4 vCPU, 16GB RAM   ($0.19/hr) - general workloads",
    "  c5.2xlarge: 8 vCPU, 16GB RAM   ($0.34/hr) - CPU-intensive",
    "  r5.4xlarge:16 vCPU,128GB RAM   ($1.00/hr) - memory-intensive (Redis,DBs)",
    "  p3.2xlarge: 8 vCPU, 61GB RAM + V100 GPU  - ML training",
    "",
    "Instance type naming convention:",
    "  [family][generation].[size]",
    "  m5.xlarge",
    "  |  | ---",
    "  |  +-- generation (5th gen is newer/better than 4th gen)",
    "  +----- family: m=general, c=compute, r=memory, p=GPU",
    "```",
    "",
    "**Launching an EC2 instance (mental model):**",
    "```",
    "1. Choose AMI (Amazon Machine Image) = the OS template",
    "   Amazon Linux 2023, Ubuntu 22.04, Windows Server 2022",
    "",
    "2. Choose instance type (CPU/RAM)",
    "",
    "3. Configure networking",
    "   Which VPC? Which subnet (public/private)?",
    "",
    "4. Configure storage (EBS volume)",
    "   Root volume: OS disk (default 8GB, encrypted)",
    "",
    "5. Configure security group (firewall rules)",
    "   Allow port 22 (SSH) from your IP",
    "   Allow port 443 (HTTPS) from anywhere",
    "",
    "6. Choose or create key pair (for SSH access)",
    "",
    "7. Launch -> running in ~60 seconds",
    "",
    "8. SSH: ssh -i mykey.pem ec2-user@<public-ip>",
    "```",
    "",
    "---",
    "",
    "## S3 — Simple Storage Service",
    "",
    "S3 is AWS's object storage. Think of it as an infinitely large, durable,",
    "globally accessible hard drive for files.",
    "",
    "```",
    "Key concepts:",
    "",
    "BUCKET:",
    "  Container for objects (files)",
    "  Globally unique name across all AWS accounts",
    "  Belongs to one region",
    "  Example: my-company-logs-2026",
    "",
    "OBJECT:",
    "  A file stored in a bucket",
    "  Key = the 'path': photos/2026/01/vacation.jpg",
    "  Value = the file data (any format, up to 5TB)",
    "  Metadata: content-type, custom tags",
    "",
    "URL: https://my-bucket.s3.amazonaws.com/photos/vacation.jpg",
    "",
    "STORAGE CLASSES (cost vs retrieval speed):",
    "  S3 Standard:            Frequent access, millisecond retrieval",
    "  S3-IA (Infrequent):     Lower cost, retrieval fee, 30-day min",
    "  S3 Glacier Instant:     Archive, millisecond retrieval",
    "  S3 Glacier Flexible:    Archive, 1-5 hour retrieval, cheapest storage",
    "",
    "COMMON USE CASES:",
    "  Static website hosting (React/Vue SPA)",
    "  Application logs and backups",
    "  Large file storage (videos, datasets)",
    "  Data lake for analytics",
    "  Docker image layer caching",
    "  CloudFront origin (serve files globally)",
    "```",
    "",
    "**S3 access control:**",
    "```",
    "Bucket Policy (JSON):  who can access which objects",
    "IAM Policy:            which IAM identities can access which bucket",
    "ACLs:                  legacy, avoid for new buckets",
    "Pre-signed URLs:       temporary URLs giving time-limited access to private objects",
    "",
    "Block Public Access:   account-level setting, blocks all public access",
    "  Enable this on all buckets unless the bucket hosts a public website.",
    "  A misconfigured S3 public bucket has leaked millions of records.",
    "```",
    "",
    "---",
    "",
    "## VPC — Virtual Private Cloud",
    "",
    "VPC is your private network in AWS. All your resources (EC2, RDS, Lambda) live inside a VPC.",
    "",
    "```",
    "VPC: 10.0.0.0/16  (65,536 IP addresses)",
    "|",
    "+-- Public Subnet: 10.0.1.0/24",
    "|   +-- Internet Gateway (allows inbound + outbound internet)",
    "|   +-- Load Balancer (public IP, receives external traffic)",
    "|   +-- Bastion Host (SSH jump server)",
    "|",
    "+-- Private Subnet: 10.0.2.0/24",
    "|   +-- EC2 App Servers (no public IP)",
    "|   +-- RDS Database (no public IP)",
    "|   +-- ElastiCache (no public IP)",
    "|",
    "+-- NAT Gateway (in public subnet)",
    "    Allows private subnet resources to reach internet (outbound only)",
    "    e.g. EC2 app server downloads packages from internet",
    "    but internet cannot initiate connections TO private EC2",
    "",
    "Security Groups:  stateful firewall attached to instances",
    "  ALLOW port 443 from 0.0.0.0/0   (anyone can reach HTTPS)",
    "  ALLOW port 5432 from sg-app      (only app security group can reach DB)",
    "",
    "Route Tables:  rules for how traffic is routed",
    "  Public subnet route: 0.0.0.0/0 -> Internet Gateway",
    "  Private subnet route: 0.0.0.0/0 -> NAT Gateway",
    "```",
    "",
    "---",
    "",
    "## IAM — Identity and Access Management",
    "",
    "IAM controls who can do what in your AWS account. Get this wrong and",
    "your entire AWS account can be compromised.",
    "",
    "```",
    "USERS:    Human identities (Alice, Bob)",
    "          Credentials: password (console) or access keys (CLI/API)",
    "          Best practice: human users should use SSO, not long-term access keys",
    "",
    "GROUPS:   Collections of users sharing permissions",
    "          'developers' group: read S3, describe EC2, invoke Lambda",
    "          'admins' group: full access",
    "",
    "ROLES:    Identities for services (not humans)",
    "          EC2 instance assumes role -> gets temporary credentials",
    "          Lambda assumes role -> can write to DynamoDB",
    "          No hardcoded secrets! Credentials auto-rotate every hour",
    "",
    "POLICIES: JSON permission documents attached to users/groups/roles",
    "  {",
    "    'Effect': 'Allow',",
    "    'Action': 's3:GetObject',",
    "    'Resource': 'arn:aws:s3:::my-bucket/*'",
    "  }",
    "",
    "CRITICAL RULE: Never use root account for daily work.",
    "  Root = god mode. Create an admin IAM user for yourself.",
    "  Enable MFA on root account immediately.",
    "  Root account credentials = keys to the kingdom.",
    "```",
    "",
    "---",
    "",
    "## RDS — Relational Database Service",
    "",
    "RDS is managed relational database. AWS handles: installation, patching,",
    "backups, replication, failover. You manage: schema, queries, data.",
    "",
    "```",
    "Supported engines:",
    "  PostgreSQL, MySQL, MariaDB, Oracle, SQL Server, Aurora",
    "",
    "Aurora:",
    "  AWS's own MySQL/PostgreSQL-compatible engine",
    "  5x faster than MySQL, 3x faster than PostgreSQL",
    "  Storage auto-scales up to 128TB",
    "  Multi-AZ by default, automated failover",
    "  Aurora Serverless: scales compute to zero when idle",
    "",
    "Key RDS features:",
    "  Multi-AZ:           automatic standby in another AZ, failover in 60-120s",
    "  Read Replicas:      read-only copies for offloading read traffic",
    "  Automated backups:  daily snapshot + transaction logs (point-in-time recovery)",
    "  Encryption at rest: KMS-managed keys",
    "",
    "RDS in your VPC (always):",
    "  RDS in private subnet = not reachable from internet",
    "  Only your app servers (same VPC) can reach it",
    "  Security group: ALLOW port 5432 from app-server security group only",
    "```",
    "",
    "---",
    "",
    "## DynamoDB — NoSQL at Scale",
    "",
    "DynamoDB is AWS's serverless NoSQL database. Zero servers to manage.",
    "Single-digit millisecond latency at any scale.",
    "",
    "```",
    "Core concepts:",
    "  TABLE:          collection of items (like a table in SQL, but schemaless)",
    "  ITEM:           a record (like a row), JSON-like, up to 400KB",
    "  PRIMARY KEY:    uniquely identifies each item",
    "    Partition key:         single attribute (userId)",
    "    Partition + Sort key:  two attributes (userId + timestamp)",
    "",
    "Capacity modes:",
    "  ON-DEMAND:    pay per read/write request, scales automatically, good for unpredictable",
    "  PROVISIONED:  specify RCU/WCU, predictable traffic, cheaper at steady load",
    "",
    "Global Secondary Index (GSI):",
    "  Query on non-primary-key attributes",
    "  Table has userId as PK, but you want to query by email -> add GSI on email",
    "",
    "DynamoDB Streams:",
    "  Record every change (insert/update/delete) as a stream",
    "  Trigger Lambda on change -> event-driven architecture",
    "",
    "When to use DynamoDB vs RDS:",
    "  DynamoDB:  simple access patterns, high throughput, unlimited scale, serverless",
    "  RDS:       complex queries, JOINs, transactions, relational data model",
    "```",
    "",
    "---",
    "",
    "## CloudWatch — Monitoring and Observability",
    "",
    "```",
    "CloudWatch is AWS's monitoring service. Collect, visualise, alert on:",
    "  - Metrics: CPU, memory, request count, error rate, latency",
    "  - Logs: application logs, Lambda logs, VPC flow logs",
    "  - Alarms: trigger actions when metric crosses threshold",
    "  - Dashboards: visualise metrics in real-time",
    "",
    "Key metrics to monitor:",
    "  EC2:    CPUUtilization, NetworkIn/Out, DiskReadOps",
    "  RDS:    DatabaseConnections, FreeStorageSpace, CPUUtilization, ReadLatency",
    "  Lambda: Duration, Errors, Throttles, ConcurrentExecutions",
    "  SQS:    ApproximateNumberOfMessagesVisible, AgeOfOldestMessage",
    "  ALB:    RequestCount, TargetResponseTime, HTTPCode_ELB_5XX",
    "",
    "CloudWatch Alarms:",
    "  Metric: Lambda Errors > 10 per 5 min",
    "  Action: Send SNS notification -> trigger PagerDuty -> wake up engineer",
    "",
    "CloudWatch Logs Insights (query language):",
    "  fields @timestamp, @message",
    "  | filter @message like /ERROR/",
    "  | stats count() by bin(5m)",
    "  | sort @timestamp desc",
    "  | limit 100",
    "",
    "CloudTrail (different from CloudWatch!):",
    "  Logs ALL AWS API calls: who did what, when, from where",
    "  'Who deleted that S3 bucket at 3am?' -> CloudTrail shows you",
    "  Enable in all accounts and regions. Required for compliance.",
    "```",
    "",
    "---",
    "",
    "## Elastic Load Balancing (ELB)",
    "",
    "```",
    "Load balancer distributes incoming traffic across multiple EC2/containers.",
    "",
    "ALB (Application Load Balancer) - Layer 7 (HTTP):",
    "  Routes by URL path, hostname, headers",
    "  /api/* -> target group 1 (API servers)",
    "  /static/* -> target group 2 (static file servers)",
    "  Header: X-Version: v2 -> new version canary group",
    "  Supports WebSockets, HTTP/2, gRPC",
    "",
    "NLB (Network Load Balancer) - Layer 4 (TCP):",
    "  Ultra-low latency (millions of requests per second)",
    "  Routes by IP/port, no HTTP awareness",
    "  Use for: gaming, financial trading, IoT",
    "",
    "Health checks:",
    "  ALB sends requests to /health endpoint on each target",
    "  Unhealthy target -> removed from rotation until healthy",
    "  New EC2 instance -> waits for N consecutive health checks -> added to rotation",
    "",
    "Auto Scaling Group:",
    "  Automatically add/remove EC2 instances based on load",
    "  Scale out when CPU > 70%, scale in when CPU < 30%",
    "  ALB automatically routes to new instances as they join",
    "```",
    "",
    "---",
    "",
    "## Well-Architected Framework — Five Pillars",
    "",
    "```",
    "AWS Well-Architected Framework = best practices guide for cloud architecture.",
    "Five pillars:",
    "",
    "1. OPERATIONAL EXCELLENCE:",
    "   Run and monitor systems, improve processes continuously.",
    "   IaC for everything, small reversible changes, automate operations.",
    "",
    "2. SECURITY:",
    "   Protect data and systems. Least privilege IAM, encrypt at rest and in transit,",
    "   enable CloudTrail, patch regularly, use private subnets.",
    "",
    "3. RELIABILITY:",
    "   Recover from failures, meet demand.",
    "   Multi-AZ deployments, auto-scaling, backups, chaos engineering.",
    "",
    "4. PERFORMANCE EFFICIENCY:",
    "   Use resources efficiently. Right-size instances, use managed services,",
    "   CloudFront for global distribution, caching.",
    "",
    "5. COST OPTIMISATION:",
    "   Avoid waste. Right-size, use Reserved Instances for steady workloads,",
    "   Spot for batch, turn off dev environments at night, use S3 lifecycle policies.",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "AWS PRACTITIONER",
    "|",
    "+-- COMPUTE",
    "|   +-- EC2 (VMs, hourly billing, AMI, instance types)",
    "|   +-- Lambda (serverless functions)",
    "|   +-- ECS/EKS (containers)",
    "|",
    "+-- STORAGE",
    "|   +-- S3 (object storage, static websites, backups)",
    "|   +-- EBS (block storage for EC2)",
    "|   +-- EFS (shared filesystem)",
    "|",
    "+-- DATABASE",
    "|   +-- RDS (managed relational: PostgreSQL/MySQL/Aurora)",
    "|   +-- DynamoDB (NoSQL, serverless, ms latency)",
    "|   +-- ElastiCache (managed Redis/Memcached)",
    "|",
    "+-- NETWORKING",
    "|   +-- VPC (private network, subnets, routing)",
    "|   +-- ALB/NLB (load balancers)",
    "|   +-- CloudFront (CDN)",
    "|   +-- Route 53 (DNS)",
    "|",
    "+-- SECURITY",
    "|   +-- IAM (users, roles, policies, least privilege)",
    "|   +-- KMS (key management)",
    "|   +-- CloudTrail (API audit log)",
    "|",
    "+-- MONITORING",
    "    +-- CloudWatch (metrics, logs, alarms)",
    "    +-- X-Ray (distributed tracing)",
    "```",
    "",
    "---",
    "",
    "## References and Further Learning",
    "",
    "### Videos (Watch These!)",
    "- **AWS Certified Cloud Practitioner - Full Course** by freeCodeCamp:",
    "  https://www.youtube.com/watch?v=SOTamWNgDKc",
    "  - 13 hours. Complete beginner to practitioner. Chapters 1-5 are essential.",
    "- **AWS Services Explained** by Fireship:",
    "  https://www.youtube.com/watch?v=M988_fsOSWo",
    "  - Quick 6-minute overview. Great starting point.",
    "",
    "### Free Books and Articles",
    "- **AWS Well-Architected Framework**: https://aws.amazon.com/architecture/well-architected/",
    "- **AWS Architecture Center**: https://aws.amazon.com/architecture/",
    "  - Reference architectures for common patterns (3-tier web, serverless, etc.)",
    "",
    "### Practice",
    "- **AWS Skill Builder** (official free training): https://skillbuilder.aws/",
    "  - 'AWS Cloud Practitioner Essentials' = 6 hours, free.",
    "- **AWS Free Tier**: https://aws.amazon.com/free/",
    "  - 12 months free EC2, always-free Lambda/DynamoDB tier.",
])

NEW_Q = [
    {"id":"aws-prac-q1","type":"mcq","prompt":"What is EC2?",
     "choices":["AWS email service","A serverless function","A virtual machine (server) you rent in the cloud — choose OS, CPU, RAM, and pay by the hour",
                "AWS database service"],
     "answerIndex":2,"explanation":"EC2 (Elastic Compute Cloud) is the foundational AWS compute service. You get a virtual Linux/Windows machine, SSH in, install your app, and pay per second it runs. It is the most flexible but most ops-heavy compute option.","tags":["ec2","compute"]},
    {"id":"aws-prac-q2","type":"mcq","prompt":"What does S3 store?",
     "choices":["Virtual machines","Running code","Objects (any file up to 5TB) in globally unique named buckets — images, videos, backups, static websites, datasets",
                "Container images only"],
     "answerIndex":2,"explanation":"S3 is object storage. Not a filesystem — each object has a key (like a path) and value (file data). 11 nines durability. Used for: static websites, application backups, data lakes, logs, ML datasets, CloudFront origins.","tags":["s3","storage"]},
    {"id":"aws-prac-q3","type":"mcq","prompt":"What is the core purpose of an IAM Role?",
     "choices":["An IAM role is for human users","An IAM role provides temporary, automatically-rotated credentials to AWS services (EC2, Lambda) — eliminates the need for hardcoded access keys",
                "IAM Roles are for read-only access","IAM Roles are required for billing"],
     "answerIndex":1,"explanation":"Roles are assumed by services. EC2 instance assumes a role -> gets temporary credentials refreshed every hour. Lambda assumes a role -> can write to DynamoDB. No hardcoded secrets in config files. This is the correct pattern for service-to-service access.","tags":["iam","roles","security"]},
    {"id":"aws-prac-q4","type":"mcq","prompt":"What is the difference between RDS and DynamoDB?",
     "choices":["RDS is NoSQL, DynamoDB is relational","RDS = managed relational database (SQL, joins, ACID transactions). DynamoDB = managed NoSQL key-value/document store (ms latency, infinite scale, serverless)",
                "They are the same service","DynamoDB only works with Lambda"],
     "answerIndex":1,"explanation":"RDS: SQL engine (PostgreSQL/MySQL), complex queries with joins, ACID transactions, vertical scaling. DynamoDB: NoSQL, simple key-based access, scales horizontally to any load, pay per request, single-digit ms latency.","tags":["rds","dynamodb","databases"]},
    {"id":"aws-prac-q5","type":"mcq","prompt":"Why should RDS always be in a private subnet?",
     "choices":["Private subnets are faster","To reduce costs","Databases in public subnets are directly accessible from the internet — a security risk. Private subnet = only VPC-internal resources can connect.",
                "RDS requires private subnets"],
     "answerIndex":2,"explanation":"RDS in a public subnet has a public IP. Any attacker on the internet can attempt connections. Private subnet = no public IP, unreachable from internet. Only app servers in the same VPC (via security group rules) can connect.","tags":["rds","vpc","security"]},
    {"id":"aws-prac-q6","type":"mcq","prompt":"What does CloudTrail record?",
     "choices":["Application logs","AWS API calls — who did what action, when, from which IP, with what result across your entire AWS account",
                "Network traffic","CloudWatch metrics"],
     "answerIndex":1,"explanation":"CloudTrail is the audit log for your AWS account. Every API call is logged: 'user alice deleted security group sg-123 at 14:32 from IP 1.2.3.4'. Essential for security auditing, compliance, and incident investigation.","tags":["cloudtrail","security","auditing"]},
    {"id":"aws-prac-q7","type":"mcq","prompt":"What is an Application Load Balancer (ALB) used for?",
     "choices":["Storing application data","Running Lambda functions","Distributing HTTP/HTTPS traffic across multiple EC2/container targets, with routing by URL path and hostname",
                "Encrypting S3 data"],
     "answerIndex":2,"explanation":"ALB operates at Layer 7 (HTTP). Routes /api/* to API servers, /static/* to static file servers. Health-checks backend targets, removes unhealthy ones from rotation. Works with EC2, ECS containers, Lambda, and Kubernetes pods.","tags":["alb","load-balancing","networking"]},
    {"id":"aws-prac-q8","type":"mcq","prompt":"What is CloudFront?",
     "choices":["A compute service","AWS CDN (Content Delivery Network) — caches content at 400+ edge locations worldwide so users get content from a nearby server, reducing latency",
                "A database service","A VPN service"],
     "answerIndex":1,"explanation":"CloudFront has edge locations globally. User in Tokyo requests your US-hosted image -> gets it from Tokyo edge cache (milliseconds) instead of US server (hundreds of ms). Also protects against DDoS and integrates with WAF.","tags":["cloudfront","cdn","networking"]},
    {"id":"aws-prac-q9","type":"mcq","prompt":"What is the Principle of Least Privilege in IAM?",
     "choices":["Grant all permissions and revoke as needed","Give every IAM identity only the exact minimum permissions it needs — nothing more. Limits blast radius if credentials are compromised.",
                "Only root account should have policies","Never deny any action"],
     "answerIndex":1,"explanation":"An EC2 with only s3:GetObject on one bucket can only read that bucket — even if credentials are stolen. An EC2 with AdministratorAccess: attacker controls your entire AWS account. Start with zero, add permissions as needed.","tags":["iam","security","least-privilege"]},
    {"id":"aws-prac-q10","type":"mcq","prompt":"What is an AWS Security Group?",
     "choices":["An IAM group for security engineers","A stateful virtual firewall for EC2/RDS instances — controls which inbound/outbound traffic is allowed by IP address, port, and protocol",
                "A VPC routing table","An encryption service"],
     "answerIndex":1,"explanation":"Security Groups are instance-level firewalls. Stateful: if inbound connection is allowed, the response is automatically allowed. Default: deny all inbound. Your job: ALLOW only the specific ports from specific sources your app needs.","tags":["security-groups","vpc","security"]},
    {"id":"aws-prac-q11","type":"mcq","prompt":"What is the S3 Block Public Access setting?",
     "choices":["Prevents S3 from being accessed from other regions","Account-level safeguard that overrides all bucket policies/ACLs to prevent any public access — prevents accidental data exposure",
                "Encrypts all S3 data","Limits S3 storage size"],
     "answerIndex":1,"explanation":"Misconfigured S3 public buckets have caused massive data breaches. Block Public Access = account-level killswitch. Enable it everywhere and only disable for specific buckets that genuinely need public access (static website hosting).","tags":["s3","security","public-access"]},
    {"id":"aws-prac-q12","type":"mcq","prompt":"What is Auto Scaling in AWS?",
     "choices":["Automatically provisions new AWS accounts","Automatically adds or removes EC2 instances based on demand — scale out during traffic spikes, scale in when traffic drops",
                "Automatically upgrades instance types","Automatic cost optimisation"],
     "answerIndex":1,"explanation":"Auto Scaling Group (ASG) maintains a fleet of EC2 instances. Define: min (always keep N), max (never exceed N), desired (target). Scaling policies: add instance when CPU > 70%, remove when CPU < 30%. Works with ALB to add new instances to rotation.","tags":["auto-scaling","ec2","elasticity"]},
    {"id":"aws-prac-q13","type":"mcq","prompt":"What is AWS CloudFormation?",
     "choices":["A monitoring service","Infrastructure as Code — define AWS resources in YAML/JSON templates, deploy and manage them consistently",
                "A billing service","A container registry"],
     "answerIndex":1,"explanation":"CloudFormation lets you declare: 'I want a VPC with 2 subnets, an EC2 in the private subnet, an RDS, and a security group'. CF creates them in the right order, handles dependencies. Version-controlled infra, reproducible environments.","tags":["cloudformation","iac","devops"]},
    {"id":"aws-prac-q14","type":"mcq","prompt":"What is AWS KMS used for?",
     "choices":["Key-based routing in DynamoDB","Managed encryption key service — create, store, and control cryptographic keys used to encrypt S3, EBS, RDS, DynamoDB data",
                "Kubernetes service","Load balancing"],
     "answerIndex":1,"explanation":"KMS (Key Management Service) manages encryption keys. You never see the raw key material — you just say 'encrypt this data with my key'. AWS handles key storage, rotation, and access control. All major AWS services integrate with KMS for encryption at rest.","tags":["kms","security","encryption"]},
    {"id":"aws-prac-q15","type":"mcq","prompt":"What is a NAT Gateway and why is it needed?",
     "choices":["Network Address Table — routes traffic between regions","Allows resources in PRIVATE subnets to make OUTBOUND internet connections (download packages, call APIs) without being reachable FROM the internet",
                "A VPN endpoint","A firewall for public subnets"],
     "answerIndex":1,"explanation":"Private subnet EC2s need to download OS updates, call third-party APIs — but should not have public IPs. NAT Gateway (in public subnet) receives their outbound traffic, routes it to internet with NAT Gateway's public IP. Internet sees NAT Gateway IP, not EC2.","tags":["nat","vpc","networking"]},
    {"id":"aws-prac-q16","type":"mcq","prompt":"What is the difference between CloudWatch and CloudTrail?",
     "choices":["They are the same","CloudWatch = performance monitoring (metrics, logs, alarms). CloudTrail = security audit log (who made what AWS API call, when, from where). Both are essential.",
                "CloudTrail is newer","CloudWatch is for security only"],
     "answerIndex":1,"explanation":"CloudWatch: your app's health (CPU, errors, latency). CloudTrail: your account's security audit (who changed IAM policy, who deleted the S3 bucket). Enable both. CloudTrail should log to a separate account so attackers cannot delete the evidence.","tags":["cloudwatch","cloudtrail","monitoring"]},
    {"id":"aws-prac-q17","type":"mcq","prompt":"What is Route 53?",
     "choices":["EC2 instance type","AWS's managed DNS service — translates domain names (myapp.com) to IP addresses. Also supports health checks and failover routing.",
                "A load balancer","A CDN service"],
     "answerIndex":1,"explanation":"Route 53 is AWS DNS. Register domains, create records (A, CNAME, ALIAS), configure routing policies: simple, weighted (A/B testing), latency-based (route to nearest region), failover (primary/standby). Integrates with CloudFront, ALB, S3.","tags":["route53","dns","networking"]},
    {"id":"aws-prac-q18","type":"mcq","prompt":"What is ElastiCache?",
     "choices":["A custom cache service you deploy on EC2","Managed Redis or Memcached — in-memory cache that sits in front of your database to serve frequent queries in microseconds instead of hitting the DB",
                "AWS caching for Lambda only","CDN cache"],
     "answerIndex":1,"explanation":"ElastiCache Redis: sub-millisecond reads, data structures (sorted sets, pub/sub), persistence, atomic operations. ElastiCache Memcached: simpler, multi-threaded, pure cache. Use in front of RDS to handle read-heavy traffic without scaling the DB.","tags":["elasticache","redis","caching"]},
    {"id":"aws-prac-q19","type":"multi","prompt":"Which AWS services are ALWAYS in a private subnet in a well-architected 3-tier web app? (Select all that apply)",
     "choices":["Application Load Balancer","EC2 application servers","RDS database","ElastiCache Redis"],
     "answerIndexes":[1,2,3],"explanation":"ALB must be in a public subnet to receive internet traffic. App servers, databases, and caches have no reason to be publicly accessible — private subnet protects them from direct internet exposure. Only ALB (and NAT GW) go in public subnets.","tags":["vpc","architecture","security"]},
    {"id":"aws-prac-q20","type":"mcq","prompt":"What is the AWS Free Tier?",
     "choices":["All AWS services are free","Selected services are free up to defined usage limits — t2.micro EC2 for 12 months, Lambda 1M requests forever, S3 5GB forever, DynamoDB 25GB forever",
                "Free tier applies only to new services","Free tier requires a credit card with no charge"],
     "answerIndex":1,"explanation":"AWS Free Tier has three categories: 12-month free (EC2 t2.micro, S3 5GB), always free (Lambda 1M/mo, DynamoDB 25GB, CloudWatch 10 metrics), and trials. A credit card is required but you are not charged if you stay within limits.","tags":["free-tier","pricing"]},
]

NEW_FC = [
    {"id":"aws-prac-fc1","front":"EC2 vs Lambda vs Fargate choice","back":"EC2: full control, steady traffic, long-running, manage OS. Lambda: event-driven, sporadic, <15min, zero ops, pay per call. Fargate: containers, no EC2 mgmt, longer tasks. Default starting point: Lambda for new APIs if fits constraints.","tags":["compute","ec2","lambda"]},
    {"id":"aws-prac-fc2","front":"S3 vs EBS vs EFS","back":"S3: object store (files), HTTP API access, infinite scale, cheap. EBS: block device attached to ONE EC2 (like a hard drive). EFS: shared POSIX filesystem mounted by MULTIPLE EC2s simultaneously. Each has distinct use cases.","tags":["storage","s3","ebs","efs"]},
    {"id":"aws-prac-fc3","front":"IAM: User vs Group vs Role vs Policy","back":"User=human identity. Group=users sharing permissions. Role=identity for services/apps (temporary creds, no passwords). Policy=JSON permission document attached to any of the above. Roles > hardcoded access keys always.","tags":["iam","security"]},
    {"id":"aws-prac-fc4","front":"RDS Multi-AZ vs Read Replica","back":"Multi-AZ: standby replica in another AZ for HIGH AVAILABILITY. Auto-failover in 60s. NOT for read scaling. Read Replica: async copy for READ SCALING. No automatic failover. You promote manually.","tags":["rds","high-availability"]},
    {"id":"aws-prac-fc5","front":"CloudWatch vs CloudTrail","back":"CloudWatch: operational monitoring (metrics, logs, alarms). 'Is my app healthy?' CloudTrail: security audit ('who changed what in my AWS account?'). Both are mandatory. CloudTrail logs to isolated account so attackers can't delete evidence.","tags":["cloudwatch","cloudtrail","monitoring"]},
    {"id":"aws-prac-fc6","front":"VPC public vs private subnet rule","back":"Public subnet: has internet gateway route, resources get public IPs. For: ALB, NAT Gateway, bastion hosts. Private subnet: no internet route, no public IPs. For: EC2 app servers, RDS, ElastiCache. Everything except the front door stays private.","tags":["vpc","networking","security"]},
    {"id":"aws-prac-fc7","front":"Well-Architected 5 pillars","back":"1.Operational Excellence (automate, IaC, small changes)  2.Security (least privilege, encrypt, trail)  3.Reliability (multi-AZ, backups, auto-recover)  4.Performance (right-size, CDN, cache)  5.Cost (reserved, spot, turn off idle)","tags":["well-architected"]},
    {"id":"aws-prac-fc8","front":"Top 3 AWS security mistakes","back":"1. Root account for daily work (create IAM user, enable MFA on root)  2. Hardcoded access keys in code (use IAM roles)  3. Public S3 bucket (enable Block Public Access everywhere). These three cause 90% of AWS security incidents.","tags":["security","iam","s3"]},
]

d['guide'] = GUIDE
d['questions'] = NEW_Q
d['flashcards'] = NEW_FC

with open(p, 'w') as f:
    json.dump(d, f, indent=2, ensure_ascii=False)
print(f"aws-practitioner.json done: guide={len(GUIDE)} q={len(d['questions'])} fc={len(d['flashcards'])}")

