import json
from pathlib import Path

# ═══════════════════════════════════════════════════════════════
#  CLOUD FUNDAMENTALS
# ═══════════════════════════════════════════════════════════════
p_cloud = Path('/Users/eptr6dj/IdeaProjects/master-cs/cs-mastery/src/content/topics/cloud-devops/cloud-fundamentals.json')
d_cloud = json.loads(p_cloud.read_text())

CLOUD_GUIDE = "\n".join([
    "# Cloud Fundamentals",
    "",
    "## What Is Cloud Computing? (Start From Zero)",
    "",
    "Before cloud computing, if you wanted to run a website, you had to:",
    "1. Buy physical servers (thousands of dollars)",
    "2. Find a data centre to put them in (expensive rent)",
    "3. Hire someone to maintain them 24/7",
    "4. Guess how much traffic you would get and buy enough hardware upfront",
    "5. Wait weeks for the hardware to arrive and be set up",
    "",
    "If your website suddenly became popular, you were stuck — more hardware took weeks.",
    "If traffic was low, your expensive servers sat idle wasting money.",
    "",
    "**Cloud computing flips this model.** You rent computing resources (servers, storage,",
    "databases) from a cloud provider (AWS, Google Cloud, Azure) over the internet.",
    "You pay only for what you use, scale up or down in minutes, and never touch hardware.",
    "",
    "**Analogy:** Think of electricity. You do not build your own power plant to get electricity.",
    "You plug into the grid, use what you need, and pay the bill. Cloud computing is the",
    "same idea for servers, storage, and software infrastructure.",
    "",
    "```",
    "Before cloud:                          After cloud:",
    "  Buy servers = $50,000 upfront          Pay $0.02/hour per server",
    "  Setup time = 4-8 weeks                 Setup time = 2 minutes",
    "  Traffic spike = site goes down         Traffic spike = auto-scale in seconds",
    "  Low traffic = wasted hardware          Low traffic = scale to zero, pay nothing",
    "  Hardware failure = your problem        Hardware failure = provider's problem",
    "```",
    "",
    "---",
    "",
    "## The Three Main Cloud Providers",
    "",
    "```",
    "+----------+-----------------------------------------------------------+",
    "| Provider | Key facts                                                 |",
    "+----------+-----------------------------------------------------------+",
    "| AWS      | Amazon Web Services. Largest market share (31%).         |",
    "| (Amazon) | Most services, most mature. EC2, S3, Lambda, RDS, EKS.  |",
    "+----------+-----------------------------------------------------------+",
    "| Azure    | Microsoft Azure. Strong in enterprise/Windows shops.      |",
    "| (MS)     | AKS (K8s), Active Directory integration, Office365.      |",
    "+----------+-----------------------------------------------------------+",
    "| GCP      | Google Cloud Platform. Strongest in ML/AI, BigQuery.     |",
    "| (Google) | GKE (K8s), BigQuery, Vertex AI, Cloud Run.              |",
    "+----------+-----------------------------------------------------------+",
    "",
    "All three offer similar services under different names.",
    "AWS: EC2  |  Azure: Virtual Machines  |  GCP: Compute Engine",
    "AWS: S3   |  Azure: Blob Storage      |  GCP: Cloud Storage",
    "AWS: RDS  |  Azure: Azure SQL         |  GCP: Cloud SQL",
    "```",
    "",
    "---",
    "",
    "## Service Models — IaaS, PaaS, SaaS, FaaS",
    "",
    "Cloud services come in layers — each layer abstracts away more complexity.",
    "The higher up you go, the less you manage.",
    "",
    "```",
    "ON-PREMISES (you manage everything):",
    "  Hardware, Network, Storage, Virtualization,",
    "  OS, Runtime, Middleware, Applications, Data",
    "  You manage: EVERYTHING",
    "",
    "IAAS (Infrastructure as a Service):",
    "  Cloud manages: Hardware, Network, Storage, Virtualization",
    "  You manage:    OS, Runtime, Middleware, Applications, Data",
    "  Examples:      AWS EC2, Azure VMs, Google Compute Engine",
    "  Use when:      Need full control over OS and runtime",
    "",
    "PAAS (Platform as a Service):",
    "  Cloud manages: Hardware, Network, Storage, Virtualization, OS, Runtime",
    "  You manage:    Applications, Data",
    "  Examples:      AWS Elastic Beanstalk, Heroku, Google App Engine",
    "  Use when:      Just want to deploy code without managing servers",
    "",
    "SAAS (Software as a Service):",
    "  Cloud manages: EVERYTHING",
    "  You manage:    Just use the application",
    "  Examples:      Gmail, Slack, Salesforce, GitHub",
    "  Use when:      End-user product — no infrastructure responsibility",
    "",
    "FAAS (Function as a Service / Serverless):",
    "  Cloud manages: Hardware, OS, Runtime, Scaling",
    "  You provide:   A function (code snippet)",
    "  You pay for:   Execution time only (milliseconds)",
    "  Examples:      AWS Lambda, Google Cloud Functions, Azure Functions",
    "  Use when:      Event-driven, sporadic workloads",
    "```",
    "",
    "**Analogy — pizza:**",
    "```",
    "On-premises = make pizza at home (buy ingredients, oven, everything yourself)",
    "IaaS         = use a restaurant kitchen (they provide oven + space, you cook)",
    "PaaS         = pizza delivery kit (they provide dough+sauce, you just add toppings)",
    "SaaS         = order pizza delivery (someone else does everything, you just eat)",
    "FaaS         = pay per slice eaten (only pay when you consume something)",
    "```",
    "",
    "---",
    "",
    "## Regions and Availability Zones",
    "",
    "Cloud providers divide the world into geographic areas to provide low latency",
    "and fault tolerance.",
    "",
    "```",
    "REGION = a geographic area with multiple data centres",
    "  Examples: us-east-1 (N. Virginia), eu-west-1 (Ireland), ap-southeast-1 (Singapore)",
    "  AWS has 30+ regions globally.",
    "  You choose a region close to your users for low latency.",
    "",
    "AVAILABILITY ZONE (AZ) = one or more physical data centres within a region",
    "  Each region has 2-6 AZs.",
    "  AZs are physically separated (different buildings, different power/network)",
    "  but connected with high-speed private fibre.",
    "",
    "  us-east-1",
    "  +-------------------------------------------------------+",
    "  |  AZ: us-east-1a    AZ: us-east-1b    AZ: us-east-1c  |",
    "  |  Data centre 1     Data centre 2     Data centre 3    |",
    "  +-------------------------------------------------------+",
    "",
    "MULTI-AZ = deploy your app in multiple AZs simultaneously",
    "  If one AZ has a power outage, your app keeps running in the others.",
    "  Load balancer distributes traffic across all healthy AZs.",
    "",
    "Why not one big data centre?",
    "  Single point of failure: one storm, power outage, or fire takes everything down.",
    "  Multi-AZ = high availability (HA).",
    "```",
    "",
    "**Key distinction:**",
    "```",
    "Region failure: entire geographic area down (rare, major disaster)",
    "AZ failure:     one data centre down (more common: power, hardware)",
    "",
    "Best practice for production:",
    "  Deploy across at least 2 AZs in one region.",
    "  For true disaster recovery: active-active across 2 regions.",
    "```",
    "",
    "---",
    "",
    "## Core Cloud Networking",
    "",
    "```",
    "VPC (Virtual Private Cloud) = your private network in the cloud",
    "  Isolated network just for your account.",
    "  You define IP address ranges, subnets, routing rules.",
    "",
    "  +--------------------------------------------------+",
    "  |                VPC: 10.0.0.0/16                  |",
    "  |                                                  |",
    "  |  Public Subnet         Private Subnet            |",
    "  |  10.0.1.0/24           10.0.2.0/24               |",
    "  |  (Internet accessible) (No direct internet)      |",
    "  |  [Load Balancer]       [App Servers]             |",
    "  |  [Bastion Host]        [Databases]               |",
    "  +--+-----------------------------------------------+",
    "     |",
    "  Internet Gateway -> connects VPC to internet",
    "",
    "PUBLIC SUBNET: resources have public IPs, reachable from internet",
    "  Use for: load balancers, bastion hosts, NAT gateways",
    "",
    "PRIVATE SUBNET: no public IPs, not directly reachable from internet",
    "  Use for: app servers, databases, internal services",
    "  Can reach internet via NAT Gateway (outbound only)",
    "",
    "Security Groups = stateful firewall for EC2/RDS instances",
    "  Rule: ALLOW port 443 from 0.0.0.0/0 (any IP)",
    "  Rule: ALLOW port 5432 from 10.0.0.0/16 (VPC only)",
    "",
    "NACLs = stateless firewall at subnet level",
    "```",
    "",
    "---",
    "",
    "## IAM — Identity and Access Management",
    "",
    "IAM controls WHO can do WHAT in your cloud account.",
    "This is arguably the most important security concept in cloud.",
    "",
    "```",
    "IAM concepts:",
    "",
    "USER:    A person or service that interacts with AWS",
    "         Has credentials (password for console, access key for API)",
    "",
    "GROUP:   Collection of users with shared permissions",
    "         e.g. 'developers' group has read-only prod, full dev access",
    "",
    "ROLE:    An identity assumed by a service or user temporarily",
    "         EC2 instance assumes role 'app-role' to read from S3",
    "         No hardcoded credentials needed!",
    "",
    "POLICY:  JSON document defining allowed/denied actions",
    "         Attached to users, groups, or roles",
    "",
    "Example policy (S3 read-only):",
    "{",
    "  'Effect': 'Allow',",
    "  'Action': ['s3:GetObject', 's3:ListBucket'],",
    "  'Resource': 'arn:aws:s3:::my-bucket/*'",
    "}",
    "```",
    "",
    "**Principle of Least Privilege:**",
    "```",
    "Give every identity the MINIMUM permissions it needs — nothing more.",
    "",
    "Bad:  EC2 instance has AdministratorAccess policy",
    "      -> if compromised, attacker controls your entire AWS account",
    "",
    "Good: EC2 instance has a role allowing ONLY:",
    "      - s3:GetObject on the specific bucket it needs",
    "      - secretsmanager:GetSecretValue for its DB password",
    "",
    "Use IAM roles for EC2/Lambda/ECS — NEVER use access keys on servers.",
    "Access keys can be stolen. Roles are automatically rotated by AWS.",
    "```",
    "",
    "---",
    "",
    "## Cloud Pricing Models",
    "",
    "```",
    "ON-DEMAND:",
    "  Pay per second/hour you use.",
    "  No commitment. Most flexible. Most expensive per hour.",
    "  Use for: unpredictable workloads, short-term needs.",
    "",
    "RESERVED INSTANCES:",
    "  Commit to 1 or 3 years. Pay upfront or monthly.",
    "  Up to 72% cheaper than on-demand.",
    "  Use for: steady, predictable workloads (production databases).",
    "",
    "SPOT INSTANCES (AWS-specific):",
    "  Bid on spare AWS capacity. Up to 90% cheaper than on-demand.",
    "  AWS can reclaim with 2-minute notice.",
    "  Use for: batch jobs, ML training, fault-tolerant workloads.",
    "  NOT for: databases, anything that cannot handle interruption.",
    "",
    "SAVINGS PLANS:",
    "  Commit to a dollar amount of compute per hour for 1-3 years.",
    "  More flexible than Reserved Instances.",
    "  Applies across services (EC2, Lambda, Fargate).",
    "",
    "FREE TIER:",
    "  AWS, GCP, Azure all have free tiers for learning.",
    "  AWS: 750 hours EC2 t2.micro/month for 12 months.",
    "  AWS: 5GB S3 storage forever.",
    "  AWS Lambda: 1 million requests/month forever.",
    "```",
    "",
    "---",
    "",
    "## Key Cloud Services Quick Reference",
    "",
    "```",
    "COMPUTE:",
    "  EC2          = virtual machine (you manage OS, patches)",
    "  Lambda       = serverless function (you just write code)",
    "  ECS/EKS      = run Docker containers / Kubernetes",
    "  Fargate      = serverless containers (no EC2 to manage)",
    "",
    "STORAGE:",
    "  S3           = object storage (files, images, backups, static sites)",
    "  EBS          = block storage (like a hard drive, attached to EC2)",
    "  EFS          = shared filesystem (multiple EC2s mount same volume)",
    "",
    "DATABASE:",
    "  RDS          = managed relational DB (MySQL, PostgreSQL, etc.)",
    "  DynamoDB     = NoSQL, serverless, millisecond latency",
    "  ElastiCache  = managed Redis/Memcached (caching)",
    "",
    "NETWORKING:",
    "  VPC          = private network",
    "  Route 53     = DNS service",
    "  CloudFront   = CDN (cache content close to users globally)",
    "  ELB/ALB      = load balancer",
    "",
    "SECURITY:",
    "  IAM          = identity and access control",
    "  KMS          = encryption key management",
    "  WAF          = web application firewall",
    "",
    "DEVOPS:",
    "  CloudWatch   = monitoring, logs, alerts",
    "  CloudFormation = infrastructure as code (YAML/JSON templates)",
    "  CDK          = CloudFormation but in real code (TypeScript/Python)",
    "  CodePipeline = AWS-native CI/CD",
    "```",
    "",
    "---",
    "",
    "## The Shared Responsibility Model",
    "",
    "```",
    "Cloud security is a shared responsibility between you and the provider.",
    "",
    "Cloud provider responsible for:     You are responsible for:",
    "  Physical hardware security          Your application code",
    "  Data centre facilities              Your data (encryption, backups)",
    "  Network hardware                    IAM (who has access to what)",
    "  Hypervisor/virtualisation layer     OS patching (for IaaS/EC2)",
    "  Service availability (SLA)          Security group rules",
    "                                      Data classification",
    "",
    "Simple rule:",
    "  Cloud provider secures the CLOUD (infrastructure)",
    "  You secure what is IN the cloud (your code, data, access)",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "CLOUD FUNDAMENTALS",
    "|",
    "+-- WHY CLOUD",
    "|   +-- Pay per use (no upfront hardware)",
    "|   +-- Scale in minutes (not weeks)",
    "|   +-- Global reach (regions/AZs)",
    "|   +-- No hardware maintenance",
    "|",
    "+-- SERVICE MODELS",
    "|   +-- IaaS   (EC2: you manage OS, they manage hardware)",
    "|   +-- PaaS   (Elastic Beanstalk: you deploy app, they manage platform)",
    "|   +-- SaaS   (Gmail: use the software, manage nothing)",
    "|   +-- FaaS   (Lambda: pay per function execution)",
    "|",
    "+-- GEOGRAPHIC CONCEPTS",
    "|   +-- Region   (geographic area: us-east-1)",
    "|   +-- AZ       (data centre: us-east-1a)",
    "|   +-- Multi-AZ (high availability — survive one AZ failure)",
    "|",
    "+-- NETWORKING",
    "|   +-- VPC       (your private network)",
    "|   +-- Public subnet  (internet-facing: load balancers)",
    "|   +-- Private subnet (internal: databases, app servers)",
    "|   +-- Security Groups (stateful firewall)",
    "|",
    "+-- IDENTITY (IAM)",
    "|   +-- User, Group, Role, Policy",
    "|   +-- Least privilege principle",
    "|   +-- Use roles on EC2/Lambda, never access keys",
    "|",
    "+-- PRICING",
    "    +-- On-demand (per second, no commitment)",
    "    +-- Reserved  (1-3 year commitment, 72% discount)",
    "    +-- Spot      (cheapest, can be interrupted)",
    "    +-- Savings Plans (flexible commitment)",
    "```",
    "",
    "---",
    "",
    "## How Cloud Fundamentals Connects to Other Topics",
    "",
    "- **Docker + Kubernetes**: ECS runs Docker containers; EKS is managed Kubernetes.",
    "  K8s worker nodes are EC2 instances in a VPC.",
    "- **CI/CD**: Pipelines deploy to AWS using IAM roles with least-privilege access.",
    "  CodePipeline is AWS-native CI/CD.",
    "- **Databases**: RDS is managed PostgreSQL/MySQL in your VPC. DynamoDB is serverless NoSQL.",
    "- **Networking**: CloudFront CDN sits in front of your app. Route 53 handles DNS.",
    "  ALB is the load balancer distributing traffic across AZs.",
    "",
    "---",
    "",
    "## Common Beginner Mistakes",
    "",
    "1. **Hardcoding AWS access keys in code** — commit to git = key stolen in minutes by bots.",
    "   Use IAM roles on EC2/Lambda instead.",
    "2. **Everything in one AZ** — one power outage takes down your whole app.",
    "   Deploy across at least 2 AZs.",
    "3. **Overly permissive security groups** — ALLOW all traffic from 0.0.0.0/0 on all ports.",
    "   Only open the exact ports needed, from the exact sources needed.",
    "4. **No cost alerts** — cloud bills can spiral. Set a billing alert at your expected spend.",
    "5. **Public databases** — RDS should be in a private subnet. Never expose your database to the internet.",
    "6. **Ignoring the free tier** — for learning, stay within free tier. Set a $5 budget alert.",
    "7. **Using root account for daily work** — create IAM users with appropriate permissions.",
    "   Root account is for account-level emergencies only.",
    "",
    "---",
    "",
    "## References and Further Learning",
    "",
    "### Videos (Watch These!)",
    "- **AWS Certified Cloud Practitioner - Full Course** by freeCodeCamp:",
    "  https://www.youtube.com/watch?v=SOTamWNgDKc",
    "  - 13 hours. Complete beginner-to-practitioner. Even if you don't want the cert, chapters 1-4 are gold.",
    "- **Cloud Computing in 6 Minutes** by Simplilearn:",
    "  https://www.youtube.com/watch?v=M988_fsOSWo",
    "  - Quick overview of IaaS/PaaS/SaaS with examples.",
    "",
    "### Free Books and Articles",
    "- **AWS Well-Architected Framework**: https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html",
    "  - AWS best practices across 6 pillars: reliability, security, performance, cost, etc.",
    "- **AWS Free Tier guide**: https://aws.amazon.com/free/",
    "  - What you can use for free to practice. Start here.",
    "",
    "### Diagrams and Cheatsheets",
    "- **AWS Global Infrastructure map**: https://infrastructure.aws/",
    "  - Live map of all regions and AZs worldwide.",
    "- **AWS Shared Responsibility diagram**: search 'AWS shared responsibility model diagram'",
    "",
    "### Practice",
    "- **AWS Skill Builder** (free official training): https://skillbuilder.aws/",
    "  - 'AWS Cloud Practitioner Essentials' is a free 6-hour course.",
    "- **CloudQuest by AWS** (gamified cloud learning): https://aws.amazon.com/training/digital/aws-cloud-quest/",
])

CLOUD_NEW_Q = [
    {"id":"cloud-q4","type":"mcq","prompt":"What is the main benefit of cloud computing over buying physical servers?",
     "choices":["Cloud servers are faster","You only pay for what you use and can scale in minutes without upfront hardware investment",
                "Cloud is always cheaper","Cloud servers never fail"],
     "answerIndex":1,"explanation":"Cloud trades capital expenditure (buy hardware upfront) for operational expenditure (pay per use). You scale in minutes, not weeks, and pay nothing when idle.","tags":["cloud-basics","economics"]},
    {"id":"cloud-q5","type":"mcq","prompt":"An EC2 instance is an example of which service model?",
     "choices":["SaaS","PaaS","IaaS","FaaS"],
     "answerIndex":2,"explanation":"EC2 is Infrastructure as a Service. AWS provides the hardware and virtualisation, but you manage the OS, patching, runtime, and application. You have full control but more responsibility.","tags":["iaas","service-models"]},
    {"id":"cloud-q6","type":"mcq","prompt":"AWS Lambda is an example of which service model?",
     "choices":["IaaS","PaaS","SaaS","FaaS (serverless)"],
     "answerIndex":3,"explanation":"Lambda is Function as a Service. You write a function, AWS handles everything else: servers, OS, scaling, availability. You pay only per execution (milliseconds of compute time).","tags":["faas","serverless"]},
    {"id":"cloud-q7","type":"mcq","prompt":"What is the purpose of multiple Availability Zones (AZs) in one region?",
     "choices":["Reduce network latency","Provide lower costs","High availability — if one AZ has an outage (power, fire, hardware), the app keeps running in other AZs",
                "Separate dev and prod environments"],
     "answerIndex":2,"explanation":"AZs are physically separate data centres with independent power/cooling/network. Deploying across multiple AZs means one AZ failure (which happens) does not take down your application.","tags":["availability-zones","high-availability"]},
    {"id":"cloud-q8","type":"mcq","prompt":"What is an IAM Role in AWS?",
     "choices":["A user account for humans","A set of allowed IP addresses","A temporary identity with permissions that services (EC2, Lambda) can assume — no hardcoded credentials needed",
                "A VPC routing rule"],
     "answerIndex":2,"explanation":"IAM Roles are assumed by services (not humans). An EC2 instance assumes a role to get temporary credentials automatically rotated by AWS. This avoids hardcoding access keys — the most common AWS security mistake.","tags":["iam","security"]},
    {"id":"cloud-q9","type":"mcq","prompt":"An EC2 instance needs to read files from S3. What is the CORRECT way to provide credentials?",
     "choices":["Hardcode access key and secret in the application code","Create an IAM Role with S3 read permissions, attach it to the EC2 instance",
                "SSH into the instance and run aws configure","Store credentials in /etc/environment"],
     "answerIndex":1,"explanation":"IAM Roles on EC2 provide temporary, automatically-rotated credentials via the instance metadata service. No hardcoding needed. Hardcoded keys in code are a critical security vulnerability.","tags":["iam","ec2","security"]},
    {"id":"cloud-q10","type":"mcq","prompt":"What is the difference between a public subnet and a private subnet in a VPC?",
     "choices":["Public subnets are cheaper","Public subnets have internet gateway routes (internet accessible); private subnets have no direct internet route (protected, used for databases and app servers)",
                "Private subnets are faster","There is no difference"],
     "answerIndex":1,"explanation":"Public subnets have an Internet Gateway route — instances can have public IPs. Private subnets have no internet gateway — instances are not directly reachable from internet. Databases should always be in private subnets.","tags":["vpc","networking"]},
    {"id":"cloud-q11","type":"mcq","prompt":"What is the Principle of Least Privilege in cloud IAM?",
     "choices":["Give all users admin access for convenience","Give every identity only the minimum permissions it needs — nothing more. Reduces blast radius if credentials are compromised.",
                "Use root account for all operations","Rotate passwords every 90 days"],
     "answerIndex":1,"explanation":"Least privilege limits damage. A compromised EC2 with only S3 read access cannot delete databases or spin up new instances. A compromised admin account can destroy everything.","tags":["iam","security","least-privilege"]},
    {"id":"cloud-q12","type":"mcq","prompt":"What AWS pricing model gives up to 90% discount but can be interrupted with 2 minutes notice?",
     "choices":["Reserved Instances","On-Demand","Spot Instances","Savings Plans"],
     "answerIndex":2,"explanation":"Spot Instances use spare AWS capacity at massive discounts. AWS can reclaim them with 2-minute notice when capacity is needed. Perfect for batch ML training, data processing — anything fault-tolerant.","tags":["pricing","spot-instances"]},
    {"id":"cloud-q13","type":"mcq","prompt":"What does S3 store?",
     "choices":["Virtual machines","Relational database records","Objects (files, images, videos, backups, static website assets) — any file up to 5TB",
                "Docker container images only"],
     "answerIndex":2,"explanation":"S3 (Simple Storage Service) is object storage. Store any file — images, videos, backups, ML datasets, static websites. Infinitely scalable, 11 nines durability. Not a filesystem (no hierarchical directories).","tags":["s3","storage"]},
    {"id":"cloud-q14","type":"mcq","prompt":"What is the cloud provider's responsibility under the Shared Responsibility Model?",
     "choices":["Your application code security","Your IAM configuration","Security OF the cloud: physical data centres, hardware, virtualisation infrastructure, and service availability",
                "Your data encryption"],
     "answerIndex":2,"explanation":"AWS secures the underlying infrastructure. You are responsible for what runs ON it: your code, your data, your IAM policies, your security groups, OS patching (for EC2). 'Security of the cloud vs security in the cloud.'","tags":["shared-responsibility","security"]},
    {"id":"cloud-q15","type":"mcq","prompt":"What is CloudFront used for?",
     "choices":["Running containers","Managed Kubernetes","A CDN (Content Delivery Network) that caches content at edge locations globally — serving users from nearby servers instead of your origin, reducing latency",
                "VPC routing"],
     "answerIndex":2,"explanation":"CloudFront has 400+ edge locations worldwide. A user in Tokyo requesting your US-hosted image gets it from a nearby edge cache — milliseconds instead of hundreds of milliseconds. Also protects against DDoS (integrates with WAF).","tags":["cloudfront","cdn"]},
    {"id":"cloud-q16","type":"mcq","prompt":"What is the key difference between RDS and DynamoDB?",
     "choices":["RDS is serverless; DynamoDB is not","RDS = managed relational database (SQL, tables, joins, ACID); DynamoDB = serverless NoSQL key-value/document store (millisecond latency, infinite scale)",
                "They are the same service","RDS is cheaper"],
     "answerIndex":1,"explanation":"RDS runs MySQL/PostgreSQL/etc. — structured data, SQL queries, joins, transactions. DynamoDB is NoSQL — flexible schema, built for high-throughput, low-latency reads/writes. Choose based on data model.","tags":["rds","dynamodb","databases"]},
    {"id":"cloud-q17","type":"mcq","prompt":"What is Infrastructure as Code (IaC)?",
     "choices":["Writing application code","Running code in the cloud","Defining cloud infrastructure in code files (YAML/JSON/TypeScript) that are version-controlled and applied automatically — AWS CloudFormation, CDK, Terraform",
                "Serverless functions"],
     "answerIndex":2,"explanation":"IaC treats infrastructure like application code. Version controlled in git. Reproducible environments. Review infrastructure changes in PRs. CloudFormation (AWS), Terraform (multi-cloud), CDK (CloudFormation via real code).","tags":["iac","cloudformation"]},
    {"id":"cloud-q18","type":"multi","prompt":"Which of these belong in a PRIVATE subnet? (Select all that apply)",
     "choices":["RDS database","EC2 application server (no public access needed)","Load balancer (receives external traffic)","Redis ElastiCache"],
     "answerIndexes":[0,1,3],"explanation":"Databases (RDS), internal app servers, and caches should be in private subnets — no direct internet access. Load balancers need to be in public subnets to receive external traffic (they have a public IP).","tags":["vpc","subnets","security"]},
    {"id":"cloud-q19","type":"mcq","prompt":"What is a Security Group in AWS?",
     "choices":["An IAM group for security engineers","A stateful virtual firewall for EC2 instances — controls inbound and outbound traffic by IP, port, and protocol",
                "An encryption service","A VPC routing table"],
     "answerIndex":1,"explanation":"Security Groups are stateful (if inbound is allowed, response is automatically allowed). They attach to EC2 instances and RDS. Default: deny all inbound, allow all outbound. Open only specific ports from specific sources.","tags":["security-groups","networking","security"]},
    {"id":"cloud-q20","type":"mcq","prompt":"What is the key advantage of a Reserved Instance over On-Demand pricing?",
     "choices":["Reserved Instances can be stopped easily","Reserved Instances are always available","Up to 72% cost reduction in exchange for a 1 or 3-year commitment — ideal for steady predictable workloads like production databases",
                "Reserved Instances have no storage limit"],
     "answerIndex":2,"explanation":"On-demand flexibility costs more per hour. If you know a workload will run 24/7 for a year (production database, core API), Reserved Instances give huge savings. 1-year = ~40% off; 3-year = ~72% off.","tags":["pricing","reserved-instances"]},
]

CLOUD_NEW_FC = [
    {"id":"cloud-fc4","front":"EC2 vs Lambda vs Fargate","back":"EC2 = IaaS (you manage OS, runtime). Lambda = FaaS pay per ms, no servers. Fargate = serverless containers (no EC2 to manage). Fargate = between EC2 and Lambda for container workloads.","tags":["compute","service-models"]},
    {"id":"cloud-fc5","front":"Public vs Private subnet rule","back":"Public subnet: has IGW route, instances get public IPs. Load balancers live here. Private subnet: no internet route. Databases, app servers, caches live here. Only reachable from within VPC.","tags":["vpc","networking"]},
    {"id":"cloud-fc6","front":"IAM Role vs IAM User","back":"User = person (human) with long-term credentials (password, access key). Role = identity for services/automation (temporary, auto-rotated credentials). Use roles for EC2/Lambda. NEVER use access keys on servers.","tags":["iam","security"]},
    {"id":"cloud-fc7","front":"On-Demand vs Reserved vs Spot","back":"On-Demand: pay per second, no commitment, most flexible, most expensive. Reserved: 1-3yr commit, 40-72% cheaper, use for steady workloads. Spot: 70-90% cheaper, can be interrupted, use for batch jobs.","tags":["pricing"]},
    {"id":"cloud-fc8","front":"S3 vs EBS vs EFS","back":"S3 = object storage (any file, accessed via HTTP API, globally unique URL). EBS = block storage (like an HD, attached to ONE EC2). EFS = shared filesystem (mounted by MULTIPLE EC2s simultaneously).","tags":["storage"]},
]

d_cloud['guide'] = CLOUD_GUIDE
qids = {q['id'] for q in d_cloud['questions']}
for q in CLOUD_NEW_Q:
    if q['id'] not in qids:
        d_cloud['questions'].append(q)
fcids = {f['id'] for f in d_cloud['flashcards']}
for fc in CLOUD_NEW_FC:
    if fc['id'] not in fcids:
        d_cloud['flashcards'].append(fc)
with open(p_cloud, 'w') as f:
    json.dump(d_cloud, f, indent=2, ensure_ascii=False)
print(f"cloud-fundamentals.json done: guide={len(CLOUD_GUIDE)} q={len(d_cloud['questions'])} fc={len(d_cloud['flashcards'])}")

