import json
from pathlib import Path

# ═══════════════════════════════════════════════════════════════
#  CI/CD PIPELINES
# ═══════════════════════════════════════════════════════════════
p_cicd = Path('/Users/eptr6dj/IdeaProjects/master-cs/cs-mastery/src/content/topics/cloud-devops/cicd-pipelines.json')
d_cicd = json.loads(p_cicd.read_text())

CICD_GUIDE = "\n".join([
    "# CI/CD Pipelines",
    "",
    "## What Is CI/CD? (Start From Zero)",
    "",
    "Imagine baking a cake. The old way: bake the whole thing, put it in the oven for an hour,",
    "discover you forgot sugar — throw it away and start over. The new way: taste the batter",
    "at every step, catch mistakes early, ship a perfect cake every time.",
    "",
    "CI/CD does that for software. Without it, developers work in isolation for weeks,",
    "merge everything at once, and spend days fixing conflicts and broken builds.",
    "With CI/CD, every small change is automatically built, tested, and deployed —",
    "catching problems within minutes, not weeks.",
    "",
    "**CI = Continuous Integration**",
    "Every time a developer pushes code, an automated system:",
    "1. Pulls the latest code",
    "2. Builds it (compiles, packages)",
    "3. Runs all tests",
    "4. Reports pass/fail back to the developer in minutes",
    "",
    "**CD = Continuous Delivery / Continuous Deployment**",
    "- **Continuous Delivery**: code is ALWAYS in a deployable state. Deploy to production is a manual button click.",
    "- **Continuous Deployment**: every passing commit is AUTOMATICALLY deployed to production. No human click needed.",
    "",
    "```",
    "Developer pushes code",
    "        |",
    "        v",
    "  CI Server picks it up",
    "        |",
    "        v",
    "  Build (compile, package)",
    "        |",
    "        v",
    "  Run Tests (unit, integration, security scan)",
    "        |",
    "   Pass? |  Fail?",
    "        |         \\",
    "        v          v",
    "  Deploy to      Notify developer",
    "  Staging env    (email/Slack)",
    "        |",
    "        v",
    "  Run smoke tests",
    "        |",
    "        v",
    "  Deploy to Production",
    "  (auto or manual click)",
    "```",
    "",
    "---",
    "",
    "## CI vs CD vs CD — Clarified",
    "",
    "```",
    "+---------------------+---------------------------------------------------+",
    "| Term                | What it means                                     |",
    "+---------------------+---------------------------------------------------+",
    "| Continuous          | Merge small changes often (not once a month).     |",
    "| Integration (CI)    | Every merge triggers build + tests automatically. |",
    "+---------------------+---------------------------------------------------+",
    "| Continuous          | The pipeline always produces a deployable         |",
    "| Delivery (CD)       | artifact. Deployment to prod = manual trigger.    |",
    "+---------------------+---------------------------------------------------+",
    "| Continuous          | Every passing build is deployed to production     |",
    "| Deployment (CD)     | automatically. No human in the loop.              |",
    "+---------------------+---------------------------------------------------+",
    "",
    "Most companies use Continuous Delivery (manual prod deploy).",
    "High-trust orgs (Netflix, Amazon) use Continuous Deployment.",
    "```",
    "",
    "---",
    "",
    "## The Pipeline — Stage by Stage",
    "",
    "A pipeline is a series of automated stages. Each stage must pass before the next runs.",
    "",
    "```",
    "STAGE 1: SOURCE",
    "  Developer pushes to feature/my-feature branch",
    "  Opens Pull Request -> pipeline triggers",
    "",
    "STAGE 2: BUILD",
    "  Pull source code",
    "  Run: mvn package / npm run build / gradle build",
    "  Output: .jar / .war / Docker image",
    "  Fail here? -> build error (typo, missing import)",
    "",
    "STAGE 3: UNIT TESTS",
    "  Run: mvn test / npm test",
    "  Fast: thousands of tests in seconds",
    "  Fail here? -> logic bug, regression",
    "",
    "STAGE 4: STATIC ANALYSIS",
    "  Run: SonarQube / ESLint / Checkstyle",
    "  Checks: code quality, security vulnerabilities, style",
    "  Fail here? -> code smell, known CVE in dependency",
    "",
    "STAGE 5: BUILD DOCKER IMAGE",
    "  docker build -t myapp:${GIT_SHA} .",
    "  docker push registry/myapp:${GIT_SHA}",
    "  Tag with git commit SHA for traceability",
    "",
    "STAGE 6: DEPLOY TO STAGING",
    "  kubectl set image deployment/myapp myapp=registry/myapp:${GIT_SHA}",
    "  Wait for rollout to complete",
    "",
    "STAGE 7: INTEGRATION / E2E TESTS",
    "  Run against staging environment",
    "  Slower: tests real API calls, DB operations",
    "  Fail here? -> service interaction bug",
    "",
    "STAGE 8: DEPLOY TO PRODUCTION",
    "  Auto (Continuous Deployment) or manual approve button (Continuous Delivery)",
    "  Deployment strategy: rolling / blue-green / canary",
    "",
    "STAGE 9: POST-DEPLOY VERIFICATION",
    "  Smoke tests, health checks, error rate monitoring",
    "  Automatic rollback if error rate spikes",
    "```",
    "",
    "---",
    "",
    "## Popular CI/CD Tools",
    "",
    "```",
    "+------------------+--------------------------------------------------+",
    "| Tool             | What it is                                       |",
    "+------------------+--------------------------------------------------+",
    "| GitHub Actions   | Built into GitHub. YAML files in .github/        |",
    "|                  | workflows/. Free for public repos.               |",
    "+------------------+--------------------------------------------------+",
    "| GitLab CI/CD     | Built into GitLab. .gitlab-ci.yml in root.       |",
    "|                  | Powerful for self-hosted setups.                 |",
    "+------------------+--------------------------------------------------+",
    "| Jenkins          | Open-source, self-hosted. Very flexible,         |",
    "|                  | needs lots of config. Older but widely used.     |",
    "+------------------+--------------------------------------------------+",
    "| CircleCI         | Cloud-based. Fast parallel jobs.                 |",
    "+------------------+--------------------------------------------------+",
    "| AWS CodePipeline | Managed by AWS. Integrates with ECR, ECS, EKS.  |",
    "+------------------+--------------------------------------------------+",
    "| ArgoCD           | GitOps tool for Kubernetes. Watches git repo,    |",
    "|                  | auto-syncs K8s cluster state.                    |",
    "+------------------+--------------------------------------------------+",
    "```",
    "",
    "---",
    "",
    "## GitHub Actions — A Real Example",
    "",
    "GitHub Actions is the most common starting point. Pipelines are YAML files",
    "stored in `.github/workflows/` in your repo.",
    "",
    "```yaml",
    "# .github/workflows/ci.yml",
    "name: CI/CD Pipeline",
    "",
    "on:",
    "  push:",
    "    branches: [main, 'feature/**']  # trigger on push to main or feature branches",
    "  pull_request:",
    "    branches: [main]                # trigger on PRs to main",
    "",
    "jobs:",
    "  build-and-test:",
    "    runs-on: ubuntu-latest           # fresh Linux VM for each run",
    "",
    "    steps:",
    "      - name: Checkout code",
    "        uses: actions/checkout@v4    # clone the repo",
    "",
    "      - name: Set up Java 17",
    "        uses: actions/setup-java@v4",
    "        with:",
    "          java-version: '17'",
    "          distribution: 'temurin'",
    "",
    "      - name: Build with Maven",
    "        run: mvn -B package -DskipTests",
    "",
    "      - name: Run tests",
    "        run: mvn -B test",
    "",
    "      - name: Build Docker image",
    "        run: |",
    "          docker build -t myapp:${{ github.sha }} .",
    "          echo \"IMAGE_TAG=${{ github.sha }}\" >> $GITHUB_ENV",
    "",
    "  deploy-staging:",
    "    runs-on: ubuntu-latest",
    "    needs: build-and-test           # only runs if build-and-test passes",
    "    if: github.ref == 'refs/heads/main'  # only on main branch",
    "",
    "    steps:",
    "      - name: Deploy to staging",
    "        run: |",
    "          kubectl set image deployment/myapp \\",
    "            myapp=registry/myapp:${{ github.sha }}",
    "",
    "  deploy-production:",
    "    runs-on: ubuntu-latest",
    "    needs: deploy-staging",
    "    environment: production         # requires manual approval in GitHub UI",
    "",
    "    steps:",
    "      - name: Deploy to production",
    "        run: |",
    "          kubectl set image deployment/myapp \\",
    "            myapp=registry/myapp:${{ github.sha }}",
    "```",
    "",
    "**Key concepts in the YAML:**",
    "- `on:` — what triggers the pipeline (push, PR, schedule, manual)",
    "- `jobs:` — parallel or sequential units of work",
    "- `steps:` — individual commands within a job",
    "- `needs:` — job dependency (deploy only if build passed)",
    "- `environment: production` — requires manual approval gate",
    "- `github.sha` — the git commit hash, used to tag Docker images for traceability",
    "",
    "---",
    "",
    "## Deployment Strategies",
    "",
    "How you deploy new versions matters. Different strategies trade off risk vs speed.",
    "",
    "```",
    "ROLLING DEPLOYMENT (default in Kubernetes):",
    "  Replace old pods one by one with new ones.",
    "  At any moment, mix of old and new running.",
    "  Zero downtime. Rollback = kubectl rollout undo.",
    "",
    "  v1 v1 v1  ->  v1 v1 v2  ->  v1 v2 v2  ->  v2 v2 v2",
    "",
    "BLUE-GREEN DEPLOYMENT:",
    "  Run two identical environments: Blue (current) and Green (new).",
    "  Deploy new version to Green. Run full tests.",
    "  Switch load balancer from Blue to Green instantly.",
    "  Instant rollback: flip load balancer back to Blue.",
    "",
    "  Load Balancer ---> Blue (v1) [active]",
    "                 --> Green (v2) [idle, being tested]",
    "  Switch:",
    "  Load Balancer ---> Green (v2) [now active]",
    "                 --> Blue (v1) [idle, ready as rollback]",
    "",
    "CANARY DEPLOYMENT:",
    "  Send small % of traffic to new version. Observe metrics.",
    "  Gradually increase if healthy. Roll back if errors spike.",
    "",
    "  All users ---> v1  (95% traffic)",
    "            +--> v2  (5% traffic = 'canary')",
    "  If v2 metrics OK after 30 min:",
    "  All users ---> v1  (50%)",
    "            +--> v2  (50%)",
    "  ...continue until 100%",
    "",
    "RECREATE (simplest, has downtime):",
    "  Stop all v1 pods. Start all v2 pods.",
    "  Downtime = time between stop and start.",
    "  Only for non-critical, off-hours deployments.",
    "```",
    "",
    "---",
    "",
    "## Feature Flags",
    "",
    "Feature flags let you deploy code to production but keep it hidden behind a toggle.",
    "Deploy the code first, then enable the feature when ready — no new deployment needed.",
    "",
    "```",
    "// Code with feature flag",
    "if (featureFlags.isEnabled('new-checkout-flow', userId)) {",
    "    renderNewCheckout();",
    "} else {",
    "    renderOldCheckout();",
    "}",
    "",
    "Benefits:",
    "  - Deploy code without releasing features (decouple deploy from release)",
    "  - Enable for 1% of users first (like canary, but at code level)",
    "  - Instant kill switch: turn off broken feature in seconds",
    "  - A/B test: enable for group A, keep old for group B",
    "  - Enable for internal users first, then gradual rollout",
    "",
    "Tools: LaunchDarkly, AWS AppConfig, Unleash (open-source)",
    "```",
    "",
    "---",
    "",
    "## Artifacts and Image Registries",
    "",
    "```",
    "Artifact = the output of a build stage",
    "  Java: .jar or .war file",
    "  Node: bundled JS files",
    "  Docker: container image",
    "",
    "Image Registry = storage for Docker images",
    "  Docker Hub:     public registry (free for public images)",
    "  AWS ECR:        Amazon's private registry",
    "  GitHub CR:      ghcr.io — integrated with GitHub",
    "  GitLab Registry: built into GitLab",
    "",
    "Best practice: tag images with git commit SHA",
    "  myapp:latest              <- BAD: always moving, non-reproducible",
    "  myapp:a1b2c3d             <- GOOD: exact commit, reproducible",
    "  myapp:v1.2.3              <- GOOD: semantic version",
    "  myapp:main-20260428-a1b2  <- GOOD: branch + date + SHA",
    "",
    "Why SHA tag? You can trace any running container back to",
    "the exact git commit that produced it.",
    "```",
    "",
    "---",
    "",
    "## Secrets in CI/CD",
    "",
    "Pipelines need secrets: Docker registry credentials, K8s tokens, AWS keys.",
    "NEVER hardcode them in YAML files.",
    "",
    "```",
    "GitHub Actions: store in Settings -> Secrets and Variables -> Actions",
    "  Access in YAML: ${{ secrets.DOCKER_PASSWORD }}",
    "",
    "GitLab CI: Settings -> CI/CD -> Variables",
    "  Access in YAML: $DOCKER_PASSWORD",
    "",
    "Jenkins: Credentials Manager plugin",
    "  Reference in Jenkinsfile: credentials('my-docker-creds')",
    "",
    "Rule: secrets should NEVER appear in pipeline logs.",
    "CI tools auto-mask registered secrets.",
    "Use separate credentials per environment (staging creds != prod creds).",
    "```",
    "",
    "---",
    "",
    "## GitOps — The Modern Approach",
    "",
    "```",
    "Traditional CI/CD:                 GitOps:",
    "  Pipeline runs kubectl apply        Git repo = source of truth",
    "  Pipeline has cluster access        ArgoCD/Flux watches the repo",
    "  Manual cloud credentials           Detects drift, auto-syncs",
    "  Hard to audit changes              Every change = git commit",
    "                                     Full audit trail",
    "                                     Rollback = git revert",
    "",
    "GitOps flow:",
    "  Developer merges PR",
    "       |",
    "       v",
    "  CI pipeline builds + pushes image",
    "       |",
    "       v",
    "  Updates image tag in k8s manifests repo (separate git repo)",
    "       |",
    "       v",
    "  ArgoCD detects git change",
    "       |",
    "       v",
    "  ArgoCD syncs cluster to match git state",
    "```",
    "",
    "---",
    "",
    "## Mind Map",
    "",
    "```",
    "CI/CD PIPELINES",
    "|",
    "+-- CONCEPTS",
    "|   +-- CI = build + test on every push",
    "|   +-- Continuous Delivery = always deployable, manual prod",
    "|   +-- Continuous Deployment = auto deploy to prod",
    "|",
    "+-- PIPELINE STAGES",
    "|   +-- Source (git trigger)",
    "|   +-- Build (compile/package)",
    "|   +-- Test (unit -> integration -> E2E)",
    "|   +-- Security scan",
    "|   +-- Build Docker image",
    "|   +-- Deploy staging",
    "|   +-- Deploy production",
    "|",
    "+-- DEPLOYMENT STRATEGIES",
    "|   +-- Rolling (gradual, default K8s)",
    "|   +-- Blue-Green (instant switch, easy rollback)",
    "|   +-- Canary (% traffic to new version)",
    "|   +-- Recreate (downtime, avoid in prod)",
    "|",
    "+-- TOOLS",
    "|   +-- GitHub Actions (.github/workflows/*.yml)",
    "|   +-- GitLab CI (.gitlab-ci.yml)",
    "|   +-- Jenkins (Jenkinsfile)",
    "|   +-- ArgoCD (GitOps for K8s)",
    "|",
    "+-- BEST PRACTICES",
    "    +-- Tag images with git SHA",
    "    +-- Secrets via vault/CI secrets, never in YAML",
    "    +-- Fail fast: put fastest tests first",
    "    +-- Feature flags for safe rollouts",
    "```",
    "",
    "---",
    "",
    "## How CI/CD Connects to Other Topics",
    "",
    "- **Git**: Every pipeline is triggered by a git event (push, merge). Your branching",
    "  strategy (GitHub Flow) directly shapes your pipeline design.",
    "- **Docker**: Pipelines build Docker images and push them to registries.",
    "- **Kubernetes**: Pipelines deploy to K8s clusters via kubectl or ArgoCD.",
    "- **Linux**: Pipeline steps run bash scripts on Linux runners.",
    "",
    "---",
    "",
    "## Common Beginner Mistakes",
    "",
    "1. **Secrets in YAML files** — anyone who reads the pipeline file sees your AWS key.",
    "2. **Too many manual steps** — the value of CI/CD comes from automation. Manual = slow.",
    "3. **No staging environment** — deploying untested code straight to production.",
    "4. **Monolithic pipeline** — one giant job. Split into parallel jobs for speed.",
    "5. **Not pinning Action versions** — `uses: actions/checkout@main` can change unexpectedly. Pin: `@v4`.",
    "6. **Slow tests blocking pipeline** — run unit tests first (fast), integration tests last (slow). Fail fast.",
    "7. **Using `latest` image tag** — makes deployments non-reproducible. Use git SHA.",
    "",
    "---",
    "",
    "## References and Further Learning",
    "",
    "### Videos (Watch These!)",
    "- **GitHub Actions Tutorial - Basic Concepts and CI/CD Pipeline** by TechWorld with Nana:",
    "  https://www.youtube.com/watch?v=R8_veQiYBjI",
    "  - 32 minutes. Clear GitHub Actions walkthrough from scratch.",
    "- **CI/CD Explained in 100 Seconds** by Fireship:",
    "  https://www.youtube.com/watch?v=scEDHsr3APg",
    "  - 2 minutes. Perfect high-level overview.",
    "",
    "### Free Books and Articles",
    "- **GitHub Actions official docs**: https://docs.github.com/en/actions",
    "  - 'Quickstart for GitHub Actions' is the best starting point.",
    "- **Google's DevOps Research (DORA metrics)**: https://dora.dev/",
    "  - The research behind why CI/CD matters. Understand deploy frequency and lead time.",
    "",
    "### Diagrams and Cheatsheets",
    "- **GitHub Actions Cheatsheet**: https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.html",
    "- **Blue-Green vs Canary diagram**: search 'deployment strategies comparison diagram'",
    "",
    "### Practice",
    "- **GitHub Actions Starter Workflows**: https://github.com/actions/starter-workflows",
    "  - Official templates for Java, Node, Docker, K8s — start from a working example.",
    "- **KodeKloud CI/CD with GitHub Actions** (free tier):",
    "  https://kodekloud.com/courses/github-actions/",
])

CICD_NEW_Q = [
    {"id":"cicd-q4","type":"mcq","prompt":"What is the primary purpose of Continuous Integration (CI)?",
     "choices":["Automatically deploy to production","Merge and test code changes automatically on every push, catching bugs early",
                "Monitor production systems","Manage cloud infrastructure"],
     "answerIndex":1,"explanation":"CI ensures every code push triggers an automated build and test run. Bugs are caught within minutes of introduction, not discovered weeks later during a big merge.","tags":["ci","pipeline"]},
    {"id":"cicd-q5","type":"mcq","prompt":"In a GitHub Actions workflow, what does `needs: build-and-test` do on a deploy job?",
     "choices":["Runs the deploy job in parallel with build-and-test","Runs build-and-test after deploy","Prevents deploy from running unless build-and-test job passed","Skips build-and-test"],
     "answerIndex":2,"explanation":"needs creates a dependency. The deploy job waits for build-and-test to complete successfully. If build-and-test fails, deploy is skipped entirely.","tags":["github-actions","pipeline"]},
    {"id":"cicd-q6","type":"mcq","prompt":"What deployment strategy allows instant rollback by switching a load balancer?",
     "choices":["Rolling deployment","Recreate deployment","Blue-Green deployment","Canary deployment"],
     "answerIndex":2,"explanation":"Blue-Green keeps two identical environments. Rollback is instant — just flip the load balancer back to the old (Blue) environment. No pod restarts, no downtime.","tags":["deployment-strategies","blue-green"]},
    {"id":"cicd-q7","type":"mcq","prompt":"A canary deployment sends 5% of traffic to the new version. Why not 100% immediately?",
     "choices":["The registry can only handle 5%","To limit blast radius — if the new version has bugs, only 5% of users are affected while you monitor metrics before full rollout",
                "Kubernetes requires this","It is cheaper"],
     "answerIndex":1,"explanation":"Canary limits risk. You observe error rates, latency, and business metrics on the 5% canary. If metrics stay healthy, gradually increase. If they spike, roll back — only 5% of users experienced the bug.","tags":["deployment-strategies","canary"]},
    {"id":"cicd-q8","type":"mcq","prompt":"Why should Docker images be tagged with the git commit SHA rather than `latest`?",
     "choices":["SHA tags are smaller","latest is not valid in CI","SHA creates a permanent, traceable link between a running container and the exact code commit that produced it — enabling reproducibility and rollback",
                "SHA tags deploy faster"],
     "answerIndex":2,"explanation":"myapp:latest changes over time. myapp:a1b2c3d is permanent. You can trace a production issue to the exact commit, reproduce the exact environment, and roll back to a specific previous SHA.","tags":["artifacts","best-practices"]},
    {"id":"cicd-q9","type":"mcq","prompt":"What is the key difference between Continuous Delivery and Continuous Deployment?",
     "choices":["They are the same","Continuous Delivery deploys automatically; Continuous Deployment requires manual approval",
                "Continuous Delivery requires manual approval for production; Continuous Deployment deploys automatically on every passing build",
                "Continuous Deployment only works with Kubernetes"],
     "answerIndex":2,"explanation":"Continuous Delivery: pipeline produces a deployable artifact. Deployment to production needs a human to click approve. Continuous Deployment: no human — every passing build goes straight to production.","tags":["cd","pipeline"]},
    {"id":"cicd-q10","type":"mcq","prompt":"Where should CI/CD pipeline secrets (Docker credentials, AWS keys) be stored?",
     "choices":["In the .yml workflow file (base64 encoded)","In a .env file committed to git","In the CI platform's secret store (GitHub Secrets, GitLab Variables, Jenkins Credentials)","In a README comment"],
     "answerIndex":2,"explanation":"CI platforms have built-in encrypted secret stores. Secrets are injected as environment variables at runtime — never visible in logs or source code. Never commit secrets to git.","tags":["security","secrets"]},
    {"id":"cicd-q11","type":"mcq","prompt":"What does a feature flag let you do that a standard deployment does not?",
     "choices":["Deploy faster","Deploy code to production without activating the feature — and enable it for specific users/% without redeploying",
                "Skip testing","Deploy multiple services at once"],
     "answerIndex":1,"explanation":"Feature flags decouple deploy from release. Code is deployed but hidden. You can enable for 1% of users, monitor, then roll out gradually. Instant kill switch: just toggle off. No new deployment needed.","tags":["feature-flags","deployment"]},
    {"id":"cicd-q12","type":"mcq","prompt":"In a pipeline, why should unit tests run BEFORE integration tests?",
     "choices":["Unit tests are more important","Unit tests are fast (seconds) and catch logic bugs early — fail fast principle. Integration tests are slow (minutes). No point running slow tests if fast ones already failed.",
                "Integration tests require unit tests to pass first","It is a GitLab requirement"],
     "answerIndex":1,"explanation":"Fail fast: run cheapest, fastest checks first. Unit tests run in seconds. If a unit test fails, skip the 10-minute integration test suite. This gives developers faster feedback and saves CI compute time.","tags":["pipeline","testing"]},
    {"id":"cicd-q13","type":"mcq","prompt":"What is GitOps?",
     "choices":["Using git for code reviews only","A git branching strategy","A practice where git is the single source of truth for infrastructure state — tools like ArgoCD watch git and auto-sync the cluster to match",
                "A type of deployment strategy"],
     "answerIndex":2,"explanation":"GitOps: every change to infrastructure goes through a git commit. ArgoCD watches the git repo and makes Kubernetes match it. Full audit trail, rollback = git revert, no manual kubectl from pipelines.","tags":["gitops","kubernetes"]},
    {"id":"cicd-q14","type":"mcq","prompt":"A rolling deployment and a recreate deployment both deploy a new version. Key difference?",
     "choices":["Rolling is faster","Recreate works only on Kubernetes","Rolling replaces pods gradually (zero downtime); Recreate stops all old pods then starts new ones (has downtime)",
                "They are identical"],
     "answerIndex":2,"explanation":"Rolling: at every step some pods serve traffic — no downtime. Recreate: all old pods stop, then new pods start — gap = downtime. Use rolling or blue-green in production.","tags":["deployment-strategies","rolling"]},
    {"id":"cicd-q15","type":"mcq","prompt":"What is the `environment: production` key in GitHub Actions used for?",
     "choices":["Sets environment variables","Specifies which OS to use","Creates a manual approval gate — the job waits for a reviewer to approve before running",
                "Points to a production .env file"],
     "answerIndex":2,"explanation":"GitHub Environments let you require manual reviewers before a job runs. Useful for production deploys: CI auto-deploys to staging, but production requires a human to approve in GitHub UI.","tags":["github-actions","approval"]},
    {"id":"cicd-q16","type":"mcq","prompt":"What is a pipeline artifact?",
     "choices":["A test failure report","The output of a build stage (compiled .jar, Docker image, test reports) passed to subsequent stages","A git branch","A deployment strategy"],
     "answerIndex":1,"explanation":"Artifacts are the build outputs: compiled binaries, Docker images, test coverage reports. They are stored and passed between pipeline stages. The Docker image produced in build is deployed in the deploy stage.","tags":["artifacts","pipeline"]},
    {"id":"cicd-q17","type":"multi","prompt":"Which are valid triggers for a GitHub Actions workflow? (Select all that apply)",
     "choices":["push to a branch","pull_request opened","schedule (cron)","manual workflow_dispatch"],
     "answerIndexes":[0,1,2,3],"explanation":"GitHub Actions supports: push (on code push), pull_request (PR events), schedule (cron-like), workflow_dispatch (manual trigger from UI), and many more. All four listed are valid.","tags":["github-actions","triggers"]},
    {"id":"cicd-q18","type":"mcq","prompt":"What DORA metric measures how often a team deploys to production?",
     "choices":["Mean Time to Recovery","Change Failure Rate","Lead Time for Changes","Deployment Frequency"],
     "answerIndex":3,"explanation":"DORA (DevOps Research and Assessment) defines 4 metrics: Deployment Frequency, Lead Time for Changes, Mean Time to Recovery (MTTR), and Change Failure Rate. Deployment Frequency = how often you ship.","tags":["dora","metrics"]},
    {"id":"cicd-q19","type":"mcq","prompt":"Why should you pin GitHub Action versions (`uses: actions/checkout@v4`) instead of using `@main`?",
     "choices":["v4 is faster","@main is invalid","@main always uses the newest version which may have breaking changes. @v4 is a locked version — your pipeline is reproducible and safe from unexpected upstream changes.",
                "It is a git requirement"],
     "answerIndex":2,"explanation":"Third-party actions should be pinned. actions/checkout@main could change any day. @v4 is stable. Better practice: pin to exact SHA (actions/checkout@abc1234) for maximum security.","tags":["github-actions","best-practices"]},
    {"id":"cicd-q20","type":"mcq","prompt":"What is the blast radius of a bug in continuous deployment vs continuous delivery?",
     "choices":["Identical — the bug is in prod either way","Continuous Deployment can affect all users immediately (auto-deployed). Continuous Delivery gives humans a chance to catch issues before approving the production deploy.",
                "Continuous Delivery has larger blast radius","Blast radius depends only on test coverage"],
     "answerIndex":1,"explanation":"With Continuous Deployment, a bug that passes tests reaches all production users automatically. With Continuous Delivery, a human reviews before prod — potential extra safety net. Both still require good test coverage.","tags":["cd","risk"]},
]

CICD_NEW_FC = [
    {"id":"cicd-fc4","front":"CI pipeline stage order (fail-fast)","back":"Source -> Build -> Unit Tests (fast) -> Static Analysis -> Build Image -> Deploy Staging -> Integration Tests (slow) -> Deploy Prod. Put fastest checks first to fail fast and save compute.","tags":["ci","pipeline"]},
    {"id":"cicd-fc5","front":"Rolling vs Blue-Green vs Canary","back":"Rolling: replace pods gradually, zero downtime. Blue-Green: two envs, instant LB switch, easy rollback. Canary: % traffic to new version, gradual increase. Recreate: all-stop then all-start (has downtime, avoid).","tags":["deployment-strategies"]},
    {"id":"cicd-fc6","front":"Feature flag vs new deployment","back":"Feature flag: code in prod but toggled off. Enable per user/% without redeploying. Kill switch in seconds. Deploy = code change. Feature flag = behaviour change. Decouple both.","tags":["feature-flags"]},
    {"id":"cicd-fc7","front":"GitOps in one sentence","back":"Git repo is the source of truth for infrastructure state. ArgoCD/Flux watches git and auto-syncs Kubernetes. Every change is a git commit. Rollback = git revert. Full audit trail.","tags":["gitops"]},
    {"id":"cicd-fc8","front":"CI/CD secrets rule","back":"Store in CI secret store (GitHub Secrets/GitLab Variables). Reference as ${{ secrets.KEY }}. Never in YAML files, never in git. Use separate credentials per environment. CI platforms auto-mask secrets in logs.","tags":["security","secrets"]},
]

d_cicd['guide'] = CICD_GUIDE
qids = {q['id'] for q in d_cicd['questions']}
for q in CICD_NEW_Q:
    if q['id'] not in qids:
        d_cicd['questions'].append(q)
fcids = {f['id'] for f in d_cicd['flashcards']}
for fc in CICD_NEW_FC:
    if fc['id'] not in fcids:
        d_cicd['flashcards'].append(fc)
with open(p_cicd, 'w') as f:
    json.dump(d_cicd, f, indent=2, ensure_ascii=False)
print(f"cicd-pipelines.json done: guide={len(CICD_GUIDE)} q={len(d_cicd['questions'])} fc={len(d_cicd['flashcards'])}")

