import json
from pathlib import Path

p = Path('/Users/eptr6dj/IdeaProjects/master-cs/cs-mastery/src/content/topics/cloud-devops/git-fundamentals.json')
d = json.loads(p.read_text())

lines = []

lines.append("# Git Fundamentals")
lines.append("")
lines.append("## What Even Is Git? (No Prior Knowledge Assumed)")
lines.append("")
lines.append("Imagine you are writing a long essay and you save it as `essay.docx`.")
lines.append("Then you make changes and save again. Now you want to go back to yesterday's version —")
lines.append("but you only have one file. You are stuck.")
lines.append("")
lines.append("Now imagine every time you save, you take a **snapshot** of the entire project,")
lines.append("label it with a message like 'added introduction', and can jump back to ANY")
lines.append("previous snapshot at any time. That is exactly what Git does.")
lines.append("")
lines.append("Git is a **version control system** — software that tracks every change you make")
lines.append("to your code files, so you can:")
lines.append("- Go back to any previous version")
lines.append("- See exactly what changed and who changed it")
lines.append("- Work on new features without breaking the working version")
lines.append("- Collaborate with a team without overwriting each other's work")
lines.append("")
lines.append("**Git vs GitHub — they are NOT the same thing:**")
lines.append("```")
lines.append("Git     = the tool on your computer that tracks changes")
lines.append("GitHub  = a website that hosts your Git repositories online")
lines.append("          (like Google Drive, but for code with Git superpowers)")
lines.append("")
lines.append("Other hosting sites: GitLab, Bitbucket — all use Git underneath")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Installing Git and First-Time Setup")
lines.append("")
lines.append("```bash")
lines.append("# Check if Git is already installed")
lines.append("git --version")
lines.append("# Output: git version 2.43.0")
lines.append("")
lines.append("# Install on Ubuntu/Debian")
lines.append("sudo apt install git")
lines.append("")
lines.append("# Install on macOS")
lines.append("brew install git")
lines.append("")
lines.append("# REQUIRED: tell Git who you are (stored in every commit)")
lines.append('git config --global user.name "Alice Smith"')
lines.append('git config --global user.email "alice@example.com"')
lines.append("")
lines.append("# Set VS Code as default editor (optional but nice)")
lines.append('git config --global core.editor "code --wait"')
lines.append("")
lines.append("# See all your config")
lines.append("git config --list")
lines.append("```")
lines.append("")
lines.append("Why set name and email? Every commit you make gets stamped with this info.")
lines.append("Your teammates see 'Alice Smith committed: fixed login bug' — not just a random hash.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## The Three Areas — The Most Important Mental Model")
lines.append("")
lines.append("Git manages your project through three distinct areas. Understanding this")
lines.append("eliminates 80% of Git confusion.")
lines.append("")
lines.append("```")
lines.append("  WORKING TREE          STAGING AREA           REPOSITORY")
lines.append("  (your files)          (the index)            (.git folder)")
lines.append("")
lines.append("  what you see          what you are           permanent")
lines.append("  and edit today        about to commit        history")
lines.append("")
lines.append("  essay.txt             [essay.txt v2]         commit abc123")
lines.append("  style.css             [style.css v3]         commit def456")
lines.append("  app.js                                       commit ghi789")
lines.append("")
lines.append("     |                       |                       |")
lines.append("     |------ git add ------->|                       |")
lines.append("     |                       |--- git commit ------->|")
lines.append("     |<------ git restore ---|                       |")
lines.append("     |<------ git checkout ---------------------------")
lines.append("```")
lines.append("")
lines.append("**Analogy — the photographer:**")
lines.append("- **Working Tree** = the scene in front of you (messy, in progress)")
lines.append("- **Staging Area** = you are choosing which subjects to include in the photo")
lines.append("- **Repository** = the photo album (permanent snapshots, never deleted)")
lines.append("")
lines.append("You stage only the changes relevant to one logical unit of work,")
lines.append("then commit them. This gives you a clean, meaningful history.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Your First Repository — Step by Step")
lines.append("")
lines.append("```bash")
lines.append("# OPTION A: Start fresh")
lines.append("mkdir my-project")
lines.append("cd my-project")
lines.append("git init")
lines.append("# Git creates a hidden .git/ folder — this IS the repository")
lines.append("# Output: Initialized empty Git repository in /my-project/.git/")
lines.append("")
lines.append("# OPTION B: Download an existing project from GitHub")
lines.append("git clone https://github.com/someuser/some-repo.git")
lines.append("cd some-repo")
lines.append("# You now have a full copy with all history")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## The Core Daily Workflow")
lines.append("")
lines.append("This is what you will do dozens of times per day:")
lines.append("")
lines.append("```bash")
lines.append("# STEP 1: Check what is going on")
lines.append("git status")
lines.append("# Shows:")
lines.append("# - Which files changed (red = unstaged, green = staged)")
lines.append("# - Which files are new (untracked)")
lines.append("# - Which branch you are on")
lines.append("")
lines.append("# STEP 2: See the actual changes (the diff)")
lines.append("git diff             # unstaged changes (working tree vs staging area)")
lines.append("git diff --staged    # staged changes (staging area vs last commit)")
lines.append("")
lines.append("# STEP 3: Stage the changes you want to commit")
lines.append("git add filename.txt    # stage one specific file")
lines.append("git add src/           # stage everything inside src/ folder")
lines.append("git add .              # stage EVERYTHING changed in this directory")
lines.append("git add -p             # interactive: stage specific chunks/lines (powerful!)")
lines.append("")
lines.append("# STEP 4: Commit with a clear message")
lines.append('git commit -m "feat: add user login endpoint"')
lines.append("# The message is permanent — make it descriptive!")
lines.append("")
lines.append("# STEP 5: Push to remote (GitHub/GitLab/etc.)")
lines.append("git push origin main")
lines.append("# origin = the name of the remote (GitHub)")
lines.append("# main   = the branch name")
lines.append("")
lines.append("# GETTING latest changes from remote")
lines.append("git pull             # fetch + merge in one step")
lines.append("git fetch            # only download, do not merge yet")
lines.append("git pull --rebase    # fetch + rebase instead of merge (cleaner)")
lines.append("```")
lines.append("")
lines.append("**What makes a good commit message?**")
lines.append("```")
lines.append("Bad:  'changes'  'fix'  'wip'  'asdf'")
lines.append("Good: 'feat: add password reset email flow'")
lines.append("      'fix: null pointer in UserService.findById()'")
lines.append("      'chore: upgrade spring-boot to 3.2.1'")
lines.append("      'docs: add API endpoint documentation'")
lines.append("")
lines.append("Convention: <type>: <short summary>")
lines.append("Types: feat, fix, chore, docs, refactor, test, style")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Branches — Working in Parallel")
lines.append("")
lines.append("A branch is just a **lightweight pointer** to a specific commit.")
lines.append("Creating one is instant and costs almost nothing.")
lines.append("")
lines.append("```")
lines.append("main branch:")
lines.append("  A --- B --- C          <- production code, always working")
lines.append("               \\")
lines.append("feature/login:  D --- E  <- your new feature, in progress")
lines.append("                         <- nobody else is affected until you merge")
lines.append("```")
lines.append("")
lines.append("```bash")
lines.append("git branch                    # list all branches (* = current)")
lines.append("git branch feature/login      # create a new branch (does NOT switch to it)")
lines.append("git checkout feature/login    # switch to a branch")
lines.append("git checkout -b feature/login # create AND switch in one command (shortcut)")
lines.append("git switch feature/login      # newer Git 2.23+ syntax for checkout")
lines.append("git switch -c feature/login   # create + switch (newer syntax)")
lines.append("")
lines.append("# When feature is done: merge it back")
lines.append("git checkout main")
lines.append("git merge feature/login")
lines.append("")
lines.append("# Clean up the branch after merging")
lines.append("git branch -d feature/login   # delete local branch")
lines.append("git push origin --delete feature/login  # delete remote branch")
lines.append("```")
lines.append("")
lines.append("**Real-world scenario:** Three developers on one team:")
lines.append("```")
lines.append("Alice  creates: feature/payment-gateway")
lines.append("Bob    creates: feature/email-notifications")
lines.append("Charlie creates: fix/login-timeout-bug")
lines.append("")
lines.append("All three branch FROM main.")
lines.append("Each works independently — no interference.")
lines.append("Each opens a Pull Request when done.")
lines.append("Code review happens. Approved? Merge to main.")
lines.append("Your CI/CD pipeline runs tests on every PR automatically.")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Merge vs Rebase — Explained Simply")
lines.append("")
lines.append("Both combine changes from one branch into another. The difference is HOW.")
lines.append("")
lines.append("**Merge** — joins two branches, creates a merge commit:")
lines.append("```")
lines.append("Before:")
lines.append("  main:    A --- B --- C")
lines.append("                \\")
lines.append("  feature:  D --- E")
lines.append("")
lines.append("After: git checkout main && git merge feature")
lines.append("  main:    A --- B --- C --- M   (M = merge commit)")
lines.append("                \\           /")
lines.append("  feature:  D --- E ---------")
lines.append("")
lines.append("History shows exactly WHEN branches met. Non-destructive.")
lines.append("```")
lines.append("")
lines.append("**Rebase** — replays your commits on top of another branch:")
lines.append("```")
lines.append("Before:")
lines.append("  main:    A --- B --- C")
lines.append("                \\")
lines.append("  feature:  D --- E")
lines.append("")
lines.append("After: git checkout feature && git rebase main")
lines.append("  main:    A --- B --- C")
lines.append("                       \\")
lines.append("  feature:              D' --- E'  (rewritten commits)")
lines.append("")
lines.append("Linear history! D and E are rewritten with new hashes.")
lines.append("```")
lines.append("")
lines.append("**When to use each:**")
lines.append("```")
lines.append("Merge:  merging feature branches into main (shows the full picture)")
lines.append("Rebase: updating your feature branch with latest main changes (local only)")
lines.append("")
lines.append("GOLDEN RULE: Never rebase commits that others have already pulled.")
lines.append("Rebase rewrites history. If Bob has your old commits, his branch")
lines.append("will diverge and everything gets messy.")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Undoing Mistakes")
lines.append("")
lines.append("Git's safety net — every mistake is recoverable (mostly).")
lines.append("")
lines.append("```bash")
lines.append("# UNDO UNSTAGED CHANGES (working tree)")
lines.append("git restore filename.txt     # throw away changes to one file")
lines.append("git restore .                # throw away ALL unstaged changes (careful!)")
lines.append("")
lines.append("# UNDO STAGED CHANGES (move back to working tree)")
lines.append("git restore --staged filename.txt  # unstage a file")
lines.append("")
lines.append("# UNDO LAST COMMIT (but keep the changes)")
lines.append("git reset --soft HEAD~1")
lines.append("# HEAD~1 means 'one commit before current'")
lines.append("# Changes go back to staging area — you can re-commit differently")
lines.append("")
lines.append("# UNDO LAST COMMIT AND DISCARD CHANGES (nuclear option)")
lines.append("git reset --hard HEAD~1")
lines.append("# WARNING: changes are gone from working tree too. No undo for this!")
lines.append("")
lines.append("# SAFE UNDO for shared branches: create an 'anti-commit'")
lines.append("git revert abc1234")
lines.append("# Creates a NEW commit that reverses the changes of abc1234")
lines.append("# Safe because it does NOT rewrite history")
lines.append("")
lines.append("# FIX YOUR LAST COMMIT (before pushing)")
lines.append("git commit --amend -m 'corrected message'")
lines.append("# Or: add a forgotten file, then amend:")
lines.append("git add forgotten-file.txt")
lines.append("git commit --amend --no-edit")
lines.append("```")
lines.append("")
lines.append("```")
lines.append("Decision tree for undoing:")
lines.append("")
lines.append("Did I push yet?")
lines.append("  NO:")
lines.append("    Unstaged change  --> git restore filename")
lines.append("    Staged change    --> git restore --staged filename")
lines.append("    Wrong commit msg --> git commit --amend")
lines.append("    Undo last commit --> git reset --soft HEAD~1")
lines.append("  YES (already pushed to shared branch):")
lines.append("    ALWAYS use git revert (never reset on shared branches!)")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Stashing — Saving Work in Progress")
lines.append("")
lines.append("You are in the middle of a feature and your boss says 'urgent bug fix needed now!'.")
lines.append("You cannot commit half-done work. Stash saves it temporarily.")
lines.append("")
lines.append("```bash")
lines.append("git stash             # save all uncommitted changes to a hidden stack")
lines.append("                      # working tree becomes clean again")
lines.append("")
lines.append("git stash list        # see all saved stashes")
lines.append("# stash@{0}: WIP on feature/login: abc123 half-done auth logic")
lines.append("")
lines.append("git stash pop         # restore the most recent stash and remove it")
lines.append("git stash apply       # restore without removing (keeps it in list)")
lines.append("")
lines.append("git stash push -m 'half-done payment logic'  # stash with a label")
lines.append("git stash drop stash@{0}                      # delete a specific stash")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Viewing History")
lines.append("")
lines.append("```bash")
lines.append("git log                        # full commit history")
lines.append("git log --oneline              # compact: one line per commit")
lines.append("git log --oneline --graph --all # ASCII graph of all branches")
lines.append("git log -5                     # last 5 commits only")
lines.append("git log --author 'Alice'       # commits by Alice")
lines.append("git log --since '2 weeks ago'  # commits from last 2 weeks")
lines.append("git log -- filename.txt        # commits that touched filename.txt")
lines.append("")
lines.append("# See what changed in a specific commit")
lines.append("git show abc1234")
lines.append("")
lines.append("# Who wrote each line of a file?")
lines.append("git blame src/UserService.java")
lines.append("# Output: each line prefixed with: hash (author date) line-number | code")
lines.append("")
lines.append("# Find which commit introduced a bug (binary search!)")
lines.append("git bisect start")
lines.append("git bisect bad         # current commit is broken")
lines.append("git bisect good v1.0   # v1.0 was fine")
lines.append("# Git checks out the mid-point commit, you test it")
lines.append("git bisect good/bad    # tell Git the result, repeat")
lines.append("# Git narrows down to the exact breaking commit")
lines.append("git bisect reset       # exit bisect mode")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## .gitignore — What NOT to Track")
lines.append("")
lines.append("Some files should NEVER go into Git: build output, IDE configs, secrets.")
lines.append("")
lines.append("```")
lines.append("# Create a .gitignore file in your project root:")
lines.append("")
lines.append("# Java build output")
lines.append("target/")
lines.append("*.class")
lines.append("*.jar")
lines.append("")
lines.append("# Secrets — CRITICAL: never commit these!")
lines.append(".env")
lines.append("application-secrets.yml")
lines.append("*.pem")
lines.append("credentials.json")
lines.append("")
lines.append("# IDE files")
lines.append(".idea/")
lines.append("*.iml")
lines.append(".vscode/")
lines.append("")
lines.append("# macOS")
lines.append(".DS_Store")
lines.append("")
lines.append("# Node.js")
lines.append("node_modules/")
lines.append("```")
lines.append("")
lines.append("**CRITICAL MISTAKE — Committed a Secret:**")
lines.append("```")
lines.append("Scenario: You committed an AWS API key in application.properties")
lines.append("Even if you delete it in the next commit, it is still in git history.")
lines.append("Anyone who clones the repo can find it with: git log -p")
lines.append("")
lines.append("Solution:")
lines.append("1. Immediately rotate/revoke the key (make the leaked key useless)")
lines.append("2. Use BFG Repo Cleaner to remove it from history:")
lines.append("   java -jar bfg.jar --delete-files application.properties")
lines.append("3. Force-push the rewritten history")
lines.append("4. Add the file to .gitignore")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## GitHub Flow — The Standard Team Workflow")
lines.append("")
lines.append("```")
lines.append("1. Branch off main")
lines.append("   git checkout -b feature/my-feature")
lines.append("")
lines.append("2. Commit your work")
lines.append("   (many small commits with clear messages)")
lines.append("")
lines.append("3. Push to GitHub")
lines.append("   git push origin feature/my-feature")
lines.append("")
lines.append("4. Open a Pull Request (PR) on GitHub")
lines.append("   - Describe what you did and why")
lines.append("   - Tag reviewers")
lines.append("")
lines.append("5. Code review")
lines.append("   - Teammates comment on specific lines")
lines.append("   - You push fixes as new commits")
lines.append("")
lines.append("6. CI/CD runs automated tests on your branch")
lines.append("   - Must pass before merge")
lines.append("")
lines.append("7. Merge to main (squash-merge = one clean commit)")
lines.append("")
lines.append("8. Deploy (auto-triggered from main)")
lines.append("")
lines.append("9. Delete the feature branch")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Remote Repositories")
lines.append("")
lines.append("```bash")
lines.append("git remote -v                         # see all remotes and their URLs")
lines.append("git remote add origin https://github.com/user/repo.git  # add a remote")
lines.append("git remote set-url origin <new-url>   # change remote URL")
lines.append("")
lines.append("git push -u origin main               # push and set upstream (first time)")
lines.append("                                       # -u = --set-upstream")
lines.append("git push                               # after -u is set, just this")
lines.append("git push --force-with-lease            # force push safely (checks nobody else pushed)")
lines.append("")
lines.append("# Work with forks (common in open source)")
lines.append("git remote add upstream https://github.com/original/repo.git")
lines.append("git fetch upstream")
lines.append("git merge upstream/main               # sync your fork with original")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Detached HEAD — What It Means")
lines.append("")
lines.append("```")
lines.append("Normally, HEAD points to a branch name:")
lines.append("  HEAD -> main -> commit abc123")
lines.append("")
lines.append("Detached HEAD: HEAD points directly to a commit hash:")
lines.append("  HEAD -> commit abc123   (no branch!)")
lines.append("")
lines.append("How you get here:")
lines.append("  git checkout abc1234   (checking out a specific old commit)")
lines.append("  git checkout v1.2.3    (checking out a tag)")
lines.append("")
lines.append("What it means:")
lines.append("  You can look around and experiment.")
lines.append("  Any new commits you make are NOT connected to any branch.")
lines.append("  If you switch away, those commits become unreachable (lost!).")
lines.append("")
lines.append("How to save work done in detached HEAD:")
lines.append("  git checkout -b my-experiment   <- creates a branch HERE")
lines.append("  Now your commits are safe on 'my-experiment' branch.")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Mind Map — Everything at a Glance")
lines.append("")
lines.append("```")
lines.append("GIT FUNDAMENTALS")
lines.append("|")
lines.append("+-- THREE AREAS")
lines.append("|   +-- Working Tree (your files)")
lines.append("|   +-- Staging Area (git add)")
lines.append("|   +-- Repository   (git commit)")
lines.append("|")
lines.append("+-- CORE WORKFLOW")
lines.append("|   +-- git status    (what changed?)")
lines.append("|   +-- git add       (stage changes)")
lines.append("|   +-- git commit    (save snapshot)")
lines.append("|   +-- git push      (upload to remote)")
lines.append("|   +-- git pull      (download + merge)")
lines.append("|")
lines.append("+-- BRANCHES")
lines.append("|   +-- git checkout -b (create + switch)")
lines.append("|   +-- git merge       (join branches)")
lines.append("|   +-- git rebase      (linearize history)")
lines.append("|   +-- Pull Requests   (code review flow)")
lines.append("|")
lines.append("+-- UNDOING")
lines.append("|   +-- git restore      (discard changes)")
lines.append("|   +-- git reset --soft (undo commit, keep changes)")
lines.append("|   +-- git reset --hard (undo + discard)")
lines.append("|   +-- git revert       (safe undo for shared branches)")
lines.append("|   +-- git commit --amend (fix last commit)")
lines.append("|")
lines.append("+-- UTILITIES")
lines.append("|   +-- git stash         (save WIP temporarily)")
lines.append("|   +-- git log --graph   (visual history)")
lines.append("|   +-- git blame         (who wrote this line?)")
lines.append("|   +-- git bisect        (find breaking commit)")
lines.append("|   +-- .gitignore        (exclude files)")
lines.append("|")
lines.append("+-- REMOTES")
lines.append("    +-- origin            (your GitHub fork/repo)")
lines.append("    +-- upstream          (original repo)")
lines.append("    +-- git push/pull/fetch")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## How Git Connects to Other Topics")
lines.append("")
lines.append("- **CI/CD Pipelines**: Every git push triggers your pipeline. Branch strategy")
lines.append("  defines deployment flow. Merging to main = auto-deploy to production.")
lines.append("- **Docker**: Images are often tagged with git commit hashes (`image:abc1234`).")
lines.append("  Dockerfiles live in the git repo.")
lines.append("- **Linux**: You run all git commands from the bash terminal.")
lines.append("  Bash scripting skills help automate git workflows.")
lines.append("- **Code Review / PRs**: GitHub, GitLab, Bitbucket are all built on top of Git.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Common Beginner Mistakes")
lines.append("")
lines.append("1. **Committing directly to main** — always branch. main should only receive merges.")
lines.append("2. **Vague commit messages** — 'fix stuff' is useless. Future-you will hate present-you.")
lines.append("3. **git add .** always — review what you stage. Use `git status` first.")
lines.append("4. **Committing .env or secrets** — add to .gitignore BEFORE first commit.")
lines.append("5. **git reset --hard on shared branches** — destroys history others have pulled.")
lines.append("   Use `git revert` instead.")
lines.append("6. **Not pulling before pushing** — leads to rejected pushes. Always `git pull` first.")
lines.append("7. **Rebase on shared branches** — rewrites history others depend on. Chaos ensues.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## References and Further Learning")
lines.append("")
lines.append("### Videos (Watch These!)")
lines.append("- **Git and GitHub for Beginners - Crash Course** by freeCodeCamp:")
lines.append("  https://www.youtube.com/watch?v=RGOj5yH7evk")
lines.append("  - 1 hour. Covers everything from init to pull requests. Best starting point.")
lines.append("- **13 Advanced Git Tips and Tricks** by Fireship:")
lines.append("  https://www.youtube.com/watch?v=ecK3EnyGD8o")
lines.append("  - 8 minutes. Fast-paced demos of stash, bisect, reflog, and more.")
lines.append("")
lines.append("### Free Books and Articles")
lines.append("- **Pro Git Book** (official, free, complete): https://git-scm.com/book")
lines.append("  - The definitive Git reference. Chapters 1-3 are essential for beginners.")
lines.append("- **Oh Shit, Git!** (common mistakes and how to fix them): https://ohshitgit.com/")
lines.append("  - Bookmark this. When you mess up (you will), this has the exact fix.")
lines.append("")
lines.append("### Diagrams and Cheatsheets")
lines.append("- **Git Visual Cheatsheet**: https://ndpsoftware.com/git-cheatsheet.html")
lines.append("  - Interactive diagram showing how commands move changes between the three areas.")
lines.append("- **GitHub Git Cheatsheet** (PDF): https://education.github.com/git-cheat-sheet-education.pdf")
lines.append("")
lines.append("### Practice")
lines.append("- **Learn Git Branching** (visual interactive): https://learngitbranching.js.org/")
lines.append("  - Best interactive Git tutorial. Visualizes branches as you type commands.")
lines.append("- **GitHub Skills**: https://skills.github.com/")
lines.append("  - Hands-on courses directly in GitHub repos.")

NEW_GUIDE = "\n".join(lines)

d['guide'] = NEW_GUIDE
with open(p, 'w') as f:
    json.dump(d, f, indent=2, ensure_ascii=False)
print(f"Done! Guide length: {len(NEW_GUIDE)} chars")
print(f"Questions: {len(d['questions'])}, Flashcards: {len(d['flashcards'])}")
print(f"Has YouTube links: {'youtube.com' in NEW_GUIDE}")
print(f"Has References section: {'References' in NEW_GUIDE}")

